### ISSUE TITLE
Allow variable shadow depths on buttons

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1001]
In the spec for [Floating Action Buttons](http://www.google.com/design/spec/components/buttons-floating-action-button.html) many of the FAB's have a large shadow depth. Currently MDL doesn't have a CSS class to achieve this.

I tried to use mdl-shadow--* which is mentioned in the cards documentation but it doesn't work on buttons. Possibly mdl-shadow--* could be expanded to also include buttons?

**Comment by Garbee** [comment]
We can move shadow down just before grid in the import to give them more specificity. Since that is the problem here. BC issues shouldn't be a problem, it just means existing projects hacking around this behavior have a bit of extra code until they catch up.

**Comment by SeanBannister** [comment]
Awesome, didn't realise it'd be this easy, great work! Thanks a heap.

**Comment by Garbee** [comment]
@SeanBannister Thanks for filing so many good issues on things. They really help since we weren't able to test through everything manually.

**Comment by SeanBannister** [comment]
@Garbee We decided Friday we'd take the plunge and be an early adopter. Just rolling it out on a new project. I'll let you know how it goes :) Thanks for taming the issue queues!!
