### ISSUE TITLE
Card subtitle not aligning correctly

### ISSUE THREAD

**Issue by jdepypere** [google/material-design-lite#1002]
Looking into the cards, the `mdl-card__subtitle-text` is not behaving as expected. It does style the content correctly, but positioning is off. [Here](http://codepen.io/anon/pen/LVrEjK) is a codepen sample and this is how it looks:

![card](https://cloud.githubusercontent.com/assets/3522063/8647329/4dcbbd80-2957-11e5-89b0-692c4b5fad5c.PNG)

According to the mdl docs, the `mdl-card__subtitle-text` should be a child of the title element, which it is. This issue looks related to [this](https://github.com/google/material-design-lite/issues/125) issue from a while ago with the solution:

>I would recommend adding the subtitle in the line below.

Which doesn't really seem like a valid solution since it has to be a child of the title element.

I've also checked the [specs](http://www.google.be/design/spec/components/cards.html) but can't find a subtitle styled like this anywhere. Am I missing something obvious?

**Comment by kybarg** [comment]
+1 
<code>.mdl-card__subtitle</code> needs to have <code>flex-direction: column;</code>

**Comment by johnsonium** [comment]
The Google documentation is vague. When it says the subtitle should "be a child of the title element" it doesn't indicate whether it should be a child of the inner div containing the title or a child of the h2 element that houses the title itself. It doesn't say what type of element should be used for the subtitle. There is also no indication whether the subtitle requires it's own inner div container.

I think I've tried every combination and I've found that if you make the subtitle a 'small' element, apply the class 'mdl-card__subtitle-text' and make it a child of the title inner div then you get a much more pleasing result with the subtitle appearing just after the title but aligned to the top of the lowercase letters of the title. See Codepen [here.](http://codepen.io/anon/pen/xGQqEg)

I'm still not sure if that's where the subtitle is supposed to appear, or whether it should be on a line below the title.

**Comment by Garbee** [comment]
@johnsonium We purposefully don't detail every element to use. Since in this case, any inline element (say span or small) will work fine. It is up to developers to play around and use what they find best or need.

I think the docs need some updating here as well. The subtitle doesn't necessarily *have* to be a child of the header text.

**Comment by johnsonium** [comment]
I thought the point of MDL was to provide a consistent look and feel. Yet, a <small> and <h3> render differently if given the 'mdl-card__subtitle-text' class though they are both inline elements.

I'm really not sure what it's supposed to look like. An <h3> renders as a superscript of the title while both <small> and <span> render on the same line though aligned with the top of the lowercase letters in the title.

**Comment by acrogenesis** [comment]
+1 for this google's spec does show the subtitle below the title. https://www.google.com/design/spec/components/cards.html#cards-actions

**Comment by mibcadet** [comment]
@johnsonium: You are right, MDL was to provide a consistent look and feel. If I have to set correct subtitle style manually why this element 'mdl-card__subtitle-text' exist if it is useless??

**Comment by VivaLaPanda** [comment]
@mibcadet Umm, isn't placing <div> inside of an <h> tag invalid syntax?

**Comment by mibcadet** [comment]
@VivaLaPanda I have shared sollution when title and subtitle in MDL works fine. However DIV are fine everywhere (IMO) as long you close them inside selector they were opened.

**Comment by noinkling** [comment]
+1 on this, very confusing.

@mibcadet Your solution seems to work well, thanks.

**Comment by Garbee** [comment]
Just looked into this (since stuff works in the V2 mockup fine.) We can't fix this due to BC issues.

Actual fix
```
.mdl-card__title {
  flex-direction: column;
}
.mdl-card__subtitle-text {
  align-self: flex-start;
}
```

Will work as it should in 2.x. But sadly 1.x is stuck with the bad layout. Sorry all, this one is surely my fault from refactoring and not including a subtitle to test with.

**Comment by noinkling** [comment]
@Garbee With those rules the title seems to be aligning to the right: https://jsfiddle.net/dzL25bmq/

Am I missing something?

**Comment by Garbee** [comment]
We can't add that into 1.x since if people have already done other  hacks to get it working then it could collide. SemVer means we can't introduce it.

As I recall, the subtitle should show just under the primary title, not towards the end of the container. I'll look at the spec again later to verify.

**Comment by lars-derichter** [comment]
+1

**Comment by sgomes** [comment]
Cards will be rewritten in #4472. Not feasible to fix until then.
