### ISSUE TITLE
bug: out of place button

### ISSUE THREAD

**Issue by hkminegod** [google/material-design-lite#1004]
Is this a new component, or a missing feature in an existing one?
Component name: button
Material Design spec URL for the component (if any):
http://www.getmdl.io/components/index.html#buttons-section

What does this component or feature allow you to do which isn’t possible at the moment?
out of place shadow/ripple(?) on chrome (samsung galaxy tab 3 lite)

Please provide any URLs or screenshots of good examples of usage of this component or feature that you may have come across.
![screenshot_2015-07-10-01-41-57](https://cloud.githubusercontent.com/assets/1128055/8648739/c87fdc9e-2995-11e5-885c-7ce20fe3d0ba.png)

**Comment by rachid804** [comment]
I noticed the same problem in my android: check the screenshots for more details:
![screenshot_1](https://cloud.githubusercontent.com/assets/1418027/8768313/c57c80ea-2e6a-11e5-9efe-92f1ce8d80ff.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/1418027/8768312/c57ba198-2e6a-11e5-971d-dc3b86b33fe0.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/1418027/8768314/c57c96ca-2e6a-11e5-9154-f6cf80523129.png)

**Comment by sgomes** [comment]
Closing, as it should no longer be an issue.
