### ISSUE TITLE
Document proper footer classes

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1006]
Document the element classes instead of modifier.

**Comment by felixvictor** [comment]
The documentation at [getmdl.io](http://www.getmdl.io/components/index.html#layout-section/footer)  has not been updated accordingly.

**Comment by Garbee** [comment]
@felixvictor It has, the snippets (demos) are what haven't been. Updating those now.

**Comment by Garbee** [comment]
The update will be pushed out with the next site refresh.

**Comment by felixvictor** [comment]
That was fast :-)
