### ISSUE TITLE
Improve docs for JS manipulation

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1008]
So, our docs fell through some cracks. In development we all got used to how the widget system worked and it was just second nature. Completely forgetting, no one else knows how it works!

We need to clearly document what is available from any component that is a widget. This can be addressed with the following actions:

1. New section copying "configuration" where we provide a table of widget methods and what their purpose is.
2. We provide a few snippets for showing different methods being used (primarily any disable/change value methods.)

This is carried out for every component configured to be a widget. As well as any future components being added in.

Setting the milestone as 1.1. That is when every component should have full docs. However, we can slowly land all the docs we want in previous patch releases as things get finished.

**Comment by sgomes** [comment]
This is core to our documentation plans for v2, so I don't think it needs separate tracking. Closing this issue.
