### ISSUE TITLE
Navigation bar with optional drawer & custom icons

### ISSUE THREAD

**Issue by jdepypere** [google/material-design-lite#1014]
It would be very handy to have the possibility for custom icons in the navigation bar as well as an optional drawer.

Use case: see [video](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-STJiN2FwYU4yYXM/components-buttons-fab-transition_fullscreen_02.mp4) from material design spec [buttons: fab](http://www.google.be/design/spec/components/buttons-floating-action-button.html) when going full screen. This use case requires an alternative icon instead of the `menu`-icon as well as no sidebar.

Related to [this issue](https://github.com/google/material-design-lite/issues/540)

**Comment by Garbee** [comment]
That icon isn't a part of the layout, but another component. The part from the video and button spec is a full-screen dialog it appears, which isn't something we are supporting anytime soon.

You can currently handle this with a custom button positioned over the menu button and providing it a higher z-index.

Allowing custom icons in the drawer may lead to non-MD spec'ed menu icons.

**Comment by jdepypere** [comment]
Too bad.

It isn't really that easy overlaying it with a custom button, considering the various screensize layouts. It's doable, but very hacky and dependant on the current MDL release. I guess I'll patch it up like this for now and hope for a tad more customizability in the future.

**Comment by smcardle** [comment]
Here is a simple way to change default MD icons IF YOU HAVE TO....

Personally I think there should be a better way as it's your site and your rules. Being told it's a non-MD spec'ed menu icon is a bit too ridged for my liking, thats the reason I choose Android devices and not IOS .

Personally we use the Drawer as a chat area for our app rather than a menu of any kind and we wanted a chat icon instead of the default hamburger menu....

    <script>
        $(function() {
            // This is a hack to replace the mdl-layout__drawer-button icon from the standard hamburger menu icon to the chat icon for our use.
            // This is not usually a good way to do this but as MDL has provided no other way outside of editing the CSS directly .... viola...
            function changeIcon() {
                var _db = document.querySelector('.mdl-layout__drawer-button i');
                if (_db) {
                    _db.textContent = 'chat';
                }
                if(!_db) {
                    setTimeout(function() {
                        changeIcon();
                    }, 50);
                }
            }
            changeIcon();
        });
    </script>

Have fun....

**Comment by MikeiLL** [comment]
Thanks. I came up with a similar approach to replace with an SVG version of the same icon:

//Replace MDL icon with our sprite

> function mdl_drawer_btn() {
>     var mdl_drawer_button = document.querySelector('.mdl-layout__drawer-button');
>     if (mdl_drawer_button != null) {
>         mdl_drawer_button.innerHTML = '<svg viewBox="0 0 100 100" class="icon nav-icon"><use xlink:href="#nav-icon"></use></svg>';
>       } else {
>         setTimeout(mdl_drawer_btn, 100);
>       }
>   }
> 
> setTimeout(mdl_drawer_btn, 100);

**Comment by traviskaufman** [comment]
Closing this as it is superseded by #4476. Our navigation drawer in v2 will be much more configurable; We'd like to the use of whichever icon / element one chooses as a "trigger" to open the menu.
