### ISSUE TITLE
Buttons & FAB (UX Review 3 feedback)

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#102]
### Button

Review comments:

- [ ] Boxed button should have about 16px spacing on the left and right of the text and 10px on top and bottom

### Floating Action Button

Demo:
http://google.github.io/web-starter-kit/reviews-round1/styleguide/fab/demo.html 

Review comments:

- [ ] ~~Ripple isn’t clipped to the button.~~
- [x] Double check the shadow on the FAB circle - because it is pretty harsh right now the icon in the middle (should be 16px padding on all sides) doesn’t seem visually centered

**Comment by sgomes** [comment]
Closing this issue, as buttons will be reimplemented and reevaluated from scratch.
