### ISSUE TITLE
MaterialMenu once opened blocks other interaction

### ISSUE THREAD

**Issue by jh3y** [google/material-design-lite#1025]
Hi!

I've put together a strange one and not sure if it's a case of implementing a fix or having to redesign UI structure because of it.

Essentially, if you have a `MaterialMenu` within say a layout header and then there was to be another `MaterialMenu` button absolutely positioned under where the first menu header would render, after opening the first, you can never open the second.

You can see an example of this here; http://codepen.io/anon/pen/KpeMeM (Not sure why the header color blinks)

The fix would be to remove the style attribute of the list when the `is-visible` class is removed if there was to be one. I can imagine this scenario not being uncommon in various UI designs.

__EDIT::__ Although upon removing the `is-visible` class, the z-index for the container is indeed -1. Chrome does not seem to respect this until the positioning attributes are altered.

@jh3y

**Comment by Garbee** [comment]
I don't see why opening the second menu would be an issue at all. The menu is covering it up, so logically you would need to hide the menu to get back to where you can open the other item. This is an inherit function of all menu/dropdown systems.

**Comment by Garbee** [comment]
I'm going to assign this to sgnomes since they built the initial component.

I'm going to try and build a minimal case for this, could be a glitch in how Chrome handles z-index changing.

**Comment by jh3y** [comment]
Hey @Garbee , 

Sorry, not sure I worded myself clearly but I meant if you open the first and then close it, you are never able to open the second because the menu content, although hidden, blocks interaction with the seconds' button somehow even though the z-index is -1.

@jh3y

**Comment by jh3y** [comment]
Been playing with this some more to see what I could come up with.

I patched an event listener in that removed the `style` attribute on close initially. However, this meant on reopening the menu, the styling was all over the place. Then it kinda hit me that the `height` property is the problem. I don't actually think that declaring the height is necessary.

Although use of `!important` isn't ideal, adding this to my CSS has fixed all menu behaviour for me and means I don't have to patch in a JS fix.

```css
.mdl-menu__container {
   height: 0px !important;
}
```

@jh3y

**Comment by Garbee** [comment]
Ah, good catch @jh3y. Looking things over it appears `clip` is the problem here. I notice it is modified on show, but trying to even manually modify the clip value isn't working via DevTools, so I can't confirm 100% if that is the case.

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) page also shows this as being a deprecated feature, so we should look into alternatives if that is the case.

**Comment by jh3y** [comment]
Yeah potentially could be.

Lines [366](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L366) and [368](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L368) of [menu.js](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js) apply the height value to the menu content. Commenting them out gave me the right behaviour. Interestingly, the animation then appeared to work correctly in both directions not just upon expansion. Tested this out by setting the `mdl-menu` to a bright color like `red`. The issue being though after that the menu of course has a transparent background because of the `0px` height, so a background color would need to be applied to the menu content to stop the transparency.

@jh3y

**Comment by nipid** [comment]
I fixed this by editing [show](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L356) and [hide](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L421) methods, I just added CSS display attribute for method show `this.container_.style.display = 'block';` and for method hide to none

**Comment by Hunsin** [comment]
I tried to fix that by adding `visibility:hidden`, removing `z-index:-1` to **.mdl-menu__container** & add `visibility:initial` to **.mdl-menu__container.is-visible**.
And it works! FYI.
