### ISSUE TITLE
Light green as primary color produces visually unpleasing components

### ISSUE THREAD

**Issue by ColtonProvias** [google/material-design-lite#1027]
When using light green as the primary color, the text is set to black, which creates a visually unpleasing combination in navigation bars, buttons, etc.  It may be better to have light green set the text color to white instead.

**Comment by Garbee** [comment]
Maybe do some manual testing and make an if statement to the primary color being used around key areas?

Seems like that kind of solution is the only viable option to fix this. Further triage needed still, that is just a quick thought from the description.

**Comment by gregorsmith** [comment]
https://www.google.com/design/spec/style/color.html#color-color-palette suggests this is correct usage of the light green palette, white isn't a good enough contrast on the lower weights

**Comment by surma** [comment]
Text color is clearly prescribed by the MD spec. The MD spec actually [uses a formula](https://github.com/google/material-design-lite/blob/master/docs/_assets/customizer.js#L458) to calculate the text color by choosing either white or black to maximize contrast.
