### ISSUE TITLE
component Menubar  like tabs with links

### ISSUE THREAD

**Issue by hannespreishuber** [google/material-design-lite#1028]
so not sure about the correct wording. From a Prior conversation I learned that there is no Material Design Lite proper way to style menubars with links, like the Tab Navigation.
From my point this is essential- the single page all content html, navigatet by anchor tags, is not the solution for  rich web sites. Websites should be splitette in pages (and links).
From this perspective the navigation is the first  task for a web dev (example here http://www.getmdl.io/). And this should be easy.

as q&d Workaround I have done this
 var navigationlinks = document.getElementsByClassName("mdl-navigation__link");
    var p = window.location.pathname.toLowerCase();
    for (var i = 0; i < navigationlinks.length; i++) {
        var a = navigationlinks[i].getAttribute("href").toLowerCase();
        if (p.indexOf(a) > 0) {
            navigationlinks[i].className = "mdl-navigation__link about";

        };
    }

**Comment by Garbee** [comment]
I'm not quite sure what the exact request is.

Do you want us to provide default active state styling?

Or do you want us to allow general links in a tab navigation layout?

Something else?

**Comment by hannespreishuber** [comment]
hmm... 
Default active state styling - means a menu link is styled as active? not bad
tab navigation with URL - sounds better and feels more natural- cause the limitation on #hash is surprising

**Comment by hkminegod** [comment]
Allowing general links in mdl-layout__tab would be cool too, I was figuring out why I couldn't set a link for it to point to.

**Comment by Garbee** [comment]
General links shouldn't use the tab system. That is confusing. "Am I getting a new page or new content on this one?" You should use a normal navigation area for links and tabs for content changing without reloading the entire page.

**Comment by Twaldigas** [comment]
@Garbee The MDL website do the same. The header navigation contains real links and is styled like tabs. http://www.getmdl.io/

**Comment by Garbee** [comment]
@Twaldigas *Styling* like tabs is one thing. But we are not using the tab component to dynamically change the content without redirecting the user and then mixing in anchors that take them away into the same UX.

We should get in touch with the MD team and see if this is an acceptable pattern to them. It isn't defined in the spec and is a major UX concern.

**Comment by Garbee** [comment]
What exactly is a use-case for having normal links mixed with tabs? As far as I can tell the spec makes no direct mention of this case. However I don't see where the spec would have any substance to support the functionality.

It seems best that we just add an active modifier to navigation links inside of the layout header to fit the case for having some active styling of links there. Then you should have a section of external links in the primary header row with a secondary header row with the tabs for the page.

**Comment by tleunen** [comment]
Based on what you said @Garbee, maybe we could have something to easily style a navigation as tabs? (meaning having just the styles without the tab-panel switch)

On the doc website, you pretty much styled it as tabs, but because of that, it set a relation between the custom css and the MDL css, which means that if for any reason the tab styles changes in MDL, you'll have to change it there as well.

**Comment by tleunen** [comment]
What do you think of using the same CSS classes as the one used for the Tabs component?
That way, we could have the same styling, keeping them inside MDL, and without the code to switch panels?

**Comment by kyleledbetter** [comment]
I'd like to use an href on tabs for navigation also. The spec specifically states "different views" 
![image](https://cloud.githubusercontent.com/assets/867883/12107818/b2c1f91c-b335-11e5-914a-79d184754a55.png)
https://www.google.com/design/spec/components/tabs.html

and also says they're a navigation pattern:
![image](https://cloud.githubusercontent.com/assets/867883/12107825/d2a35d5c-b335-11e5-972b-5097e66a002b.png)
https://www.google.com/design/spec/patterns/navigation.html#navigation-patterns

**Comment by kyleledbetter** [comment]
looks like this PR may have fixed, is that correct? https://github.com/google/material-design-lite/pull/929 (doesn't look like this is in the latest release though)

**Comment by Garbee** [comment]
It will be in V1.1.
