### ISSUE TITLE
Should not reserve space for hidden hamburger button when navigation drawer is permanent

### ISSUE THREAD

**Issue by patrick-jones** [google/material-design-lite#1032]
When the navigation bar is permanent, the title is rendered with extra left padding to accommodate where the hamburger menu used to be.  I don't see where [the spec](http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior) says it explicitly, but none of the examples depict similar behavior. For example, note the example of "an open persistent drawer."

**Comment by Garbee** [comment]
Yea, it doesn't explicitly state in the drawer spec nor the layout spec. I'd assume this is just a byproduct of how the templates are setup to make sure the drawer button has the space it needs. We should get in touch with the MD spec team and see if what we currently do is acceptable. If not then make sure the space isn't preserved.

**Comment by kybarg** [comment]
Or when drawer is shown only no phones, tablets...

**Comment by Garbee** [comment]
@surma Do you think we could include the CSS from #1078 in a patch or minor bump? Looks safe enough and BC concerns are pretty minor (aside from manually set things due to existing spaces. But I'm not too worried about that.)
