### ISSUE TITLE
MDL + React + Webpack

### ISSUE THREAD

**Issue by highlabs** [google/material-design-lite#1033]
Hi! :)

I'm using MDL (with cdn) in my first React app.

When I change route, I need to declare:
```
  componentDidMount: function() {
    componentHandler.upgradeAllRegistered();
  }
```
Without this, my component don't work.

But when I open the page url directly, appear this error in console:
```
Uncaught ReferenceError: componentHandler is not defined
```

have a better way do include MDL in my project or solve this error?

**Comment by yan-foto** [comment]
Do you load MDL before React?

**Comment by highlabs** [comment]
I'm loading MDL inside .html file:
```
    <script src="/assets/js/vendors/material.js"></script>
```

**Comment by Garbee** [comment]
Support questions should be asked on StackOverflow. You can use the `material-design-lite` tag along with any other relevant tags. This will allow more developers to see and help with the problem as well as find it when they have a related issue.

**Comment by jjalonso** [comment]
Well Im using React with MDL and two routes

component A (page1) 
component B (page2) (MDL layout is here)

Basically when I redirect from A to B the screen is white, when I enter directly in /B is fine, and with your code I refresh the components and now is rendering fine @highlabs 

I also tried putting it on index.html outside of the react bootstrap but doesnt work. I heard that another idea is use a parent component that hold all others. (which include the layout)
