### ISSUE TITLE
Access MDL instances through componentHandler

### ISSUE THREAD

**Issue by yan-foto** [google/material-design-lite#1034]
`componentHandler` keeps track of all upgraded elements using [`createdComponents_`](https://github.com/google/material-design-lite/blob/v1.0.0/material.js#L29) array. This, however, is not accessible externally. Being able to access MDL components has the advantage of using their methods (e.g. `MaterialCheckbox.uncheck()`).

The only solution to access the MDL components is to create them manually (e.g. `var c = new MaterialCheckbox(el)`). In such case if the DOM element `el` has already been upgraded to an MDL component, there are going to be duplication in the DOM tree.

I suggest to expose `findCreatedComponentByNodeInternal` also for external use.

**Comment by Garbee** [comment]
I'm inherently against this. Components that need to be accessed by the developer expose themselves via the widget system. This means the component developer is in control of whether the methods can be called externally. In which case, you query the element the css class for JS trigger is specified on and access it through the JS classname property.

This kind of addition adds in extra complexity that makes the widget setup useless for blocking off your classes methods. What is the exact use-case that this is supposed to fix that isn't currently possible?

**Comment by yan-foto** [comment]
The use case is checking and unchecking a checkbox and according to your [answer](http://stackoverflow.com/a/31419856/2295964) this is a bug in 1.0.0 and is patched in 1.0.1.

I would say the problem is clarified and will close the issue.
