### ISSUE TITLE
mdl-card--expand not documented

### ISSUE THREAD

**Issue by nikvm** [google/material-design-lite#1036]
Component : Card

What are you trying to do or find out more about?
Modifier class mdl-card--expand

Where have you looked?
http://www.getmdl.io/components/index.html#cards-section

Where did you expect to find this information?
In section "Configuration options"

What did I find out?
* Sets flex-grow: 1
* Docs show it applied to mdl-card__title element

**Comment by Garbee** [comment]
I'm actually not sure why this class exists. It is a targeted case effect that doesn't match our browser support. 

Let me look into why it exists before documenting it. Looks prime for deprecation and eventual removal.

**Comment by Garbee** [comment]
Yea, we are [using it](https://github.com/google/material-design-lite/search?utf8=%E2%9C%93&q=mdl-card--expand&type=Code) in the snippets and in one template to show stuff off.

It seems to only ever be used with title though, which is odd. If it is meant for that only, it should be named `.mdl-card__title--expand` instead. Also it should try to cover non-flex support (IE9 primarily.) 

@sgomes Do you remember why this class was added in?

**Comment by Garbee** [comment]
Adding a `BC Break` tag here. Looking into it more I'm not seeing any reason for this class to exist upstream looking at the specification.

**Comment by traviskaufman** [comment]
Closing this as it is superseded by #4472 , which will cover cards with expandable content
