### ISSUE TITLE
Documentation: Use MDL on dynamic websites Codepen example misleading

### ISSUE THREAD

**Issue by mikeymckay** [google/material-design-lite#1042]
On this page:

http://www.getmdl.io/started/index.html#dynamic

If you follow the codepen link, it looks like it is working. But then if you remove the line:

    componentHandler.upgradeElement(button, 'MaterialButton');

It still works (which drove me a little bit crazy). If you add a window.setTimeout to delay the DOM editing by 1000ms, then it works. Seems like the javascript on Codepen is run before the material design transform occurs. 

    (function () {
        window.setTimeout(function () {
            $('#container').html('<div class="mdl-textfield mdl-js-textfield"> <input class="mdl-textfield__input" type="text" id="sample1" /> <label class="mdl-textfield__label" for="sample1">Text..</label> </div>');
            return componentHandler.upgradeDom();
        }, 1000);
    }.call(this));

In general, it would be helpful to have more documentation about how best to do dynamic upgrades.

**Comment by muten84** [comment]
Hi I'm trying to do the same and i have a lot of elements to pass to the upgrade function, I read the documentation and I can't find any reference to the upgradeDom function, the name suggests what this function could do, any suggestions?

**Comment by mikeymckay** [comment]
@muten84 - it seems like you can call componentHandler.upgradeDom() and it will upgrade all elements that have the mdl classes on them. You can call it multiple times without side effects. This is all learned through trial, error and reading the code!

**Comment by muten84** [comment]
@mikeymckay Great thanks for your experience sharing!! I'll try the upgradeDom just now! :)

**Comment by Garbee** [comment]
This is a by-product of how Codepen sets up the example.

Overall, the example code works as just that, an example. Since there is nothing directly actionable beyond "Better docs" I'm closing this issue out. It is being worked on, so don't take the closing as a sign that there isn't a problem.

**Comment by hesus001** [comment]
@mikeymckay Thanks for the tip , the method works just fine and upgrades all the elements, it's just that it throws an error:

ripple.js:243 :  Uncaught TypeError: Cannot read property 'parentElement' of null 

Not sure if it's a bug , in any case thanks!
