### ISSUE TITLE
Focusing text-fields / AJAX

### ISSUE THREAD

**Issue by GabrielCousin** [google/material-design-lite#1043]
Hi, I don't know if I am creating a duplicate issue (which case I appologize).
I am calling some text-fields in AJAX, and it seems like JS doesn't add neither `.is-focused` class nor `data-upgrade` attributes.
Thanks for you help!

**Comment by kybarg** [comment]
@GabrielCousin Try to use `componentHandler.upgradeDom();` after AJAX call

**Comment by GabrielCousin** [comment]
Thank you so much, it works perfectly.

**Comment by mrfaizanhaider** [comment]
Hi i'm working on a portal using MDL & angular ... i'm facing some issue on TEXT FIELDS. 

TEXT FIELDS all effect not working when i click on login page. but when i refresh the page , all effecst working good. 

please help...

**Comment by Garbee** [comment]
@mrfaizanhaider please use StackOverflow for support and usage help.
