### ISSUE TITLE
Mobile navigation in heavy text template doesn't work

### ISSUE THREAD

**Issue by kitzu** [google/material-design-lite#1045]
If you open the heavy text template ( http://www.getmdl.io/templates/text-only/index.html ) on your phone instead of desktop, you get a navigation drawer instead of the tabs, but navigating via the drawer links doesn't work. If you click one of the features links, nothing happens.

Edit:
directly opening http://www.getmdl.io/templates/text-only/index.html#features in a mobile browser also just opens the overview page.

**Comment by Garbee** [comment]
Duplicate of issue #835. Just waiting for a site refresh so it goes live.

**Comment by surma** [comment]
It’s live :)
