### ISSUE TITLE
Titled panel of some sort

### ISSUE THREAD

**Issue by anton-johansson** [google/material-design-lite#1046]
Hi!

I was wondering if there is support (or a plan for support) for some kind of titled panel? See example below (note that this is not MDL):
![material-titled-panels](https://cloud.githubusercontent.com/assets/6347803/8695639/88b70a40-2ae6-11e5-9eff-14db5563912e.png)
Sorry about the swedish nonsense.

I couldn't see anything like this in the [documentation](http://www.getmdl.io/components/index.html). Same goes for dialogs. Any plans for modal dialogs? Dialogs are in the [Material Design specification](https://www.google.com/design/spec/components/dialogs.html) atleast. :)

But I'd like to have a grid layout beneath my top title, with a 3 column sidepanel and a 9 column content panel. These two I want to be titled, like the image above. Maybe even with a little icon next to the title.

Not sure if there's anything like this in the Material Design specification.

Any info, help, tips, etc, are much welcome!

**Comment by Garbee** [comment]
Cards can cover this use-case.

**Comment by anton-johansson** [comment]
Indeed they can! Just messed around with it, looks perfect. Thanks for the quick reply!
