### ISSUE TITLE
Broken links in toggle documenation

### ISSUE THREAD

**Issue by bmesuere** [google/material-design-lite#1048]
In the introduction sections of [toggles](http://www.getmdl.io/components/index.html#toggles-section), there are broken links to the Material Design spec. The links point to http://www.google.com/design/spec/components/switches.html but this should be http://www.google.be/design/spec/components/selection-controls.html.

**Comment by Garbee** [comment]
Fixed via commit 70479405abf57510649b4398bd058b2575ca3152.

Thanks for reporting.

**Comment by bmesuere** [comment]
The same (broken) link is also in the radio and switches introduction on the same page. Sorry if I wasn't clear enough.

**Comment by Garbee** [comment]
Oh, "sections". No you were clear enough I just didn't catch it. One moment, updating the other two...

These links must have been from a previous revision of the spec.

**Comment by Garbee** [comment]
The other one is fixed (third was previously fixed by another commit.) Just waiting for a site refresh to go live (which should be Fridayish if all goes well.)
