### ISSUE TITLE
Layouts (UX Review 3 feedback)

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#105]
All:
- [ ] title color #eee? should be white 87%

Fixed drawer with header and no header
- [x] remove div line at bottom: 
![screen shot 2015-04-01 at 11 23 54](https://cloud.githubusercontent.com/assets/110953/6939168/9e391b74-d861-11e4-8b54-3082a3c65977.png)

- [ ] .wsk-layout__drawer .wsk-navigation__link  - add padding at top so it’s 48 pixels from title.

Multi-row layout
- [x] remove “Multi-row layout demo” copy?
- [x]  `<span id="my_text_changes">Web Starter Kit</span> should be same as <span class="wsk-layout-title">Web Starter Kit</span>`

Scrollable tabs

- [ ] change background to white
- [ ] change link underline select state white

Fixed tabs

- [ ] remove this one? seems like an app UI

Content tabs

- [ ] ensure margin on top of nax text is same as bottom (seems like bottom is more) 
![screen shot 2015-04-01 at 11 24 18](https://cloud.githubusercontent.com/assets/110953/6939176/b4c763e6-d861-11e4-86ba-3941376430ea.png)

- [ ] add margin top spacing before first li (48px?)

**Comment by sgomes** [comment]
Layout will be split up into multiple components and reimplemented from scratch.
