### ISSUE TITLE
Data table within Cards

### ISSUE THREAD

**Issue by jackielii** [google/material-design-lite#1051]
Hi,

Per [Data Table within Cards](https://www.google.com/design/spec/components/data-tables.html#data-tables-tables-within-cards) Spec, is it possible to do it in current Card+Data table implementation? If yes, should we add an example?

**Comment by Garbee** [comment]
We don't directly support within cards since that spec defines functionality we don't provide yet.

**Comment by jackielii** [comment]
Thanks Garbee, can we make this a feature request?

**Comment by Garbee** [comment]
What exactly were you looking to do?

**Comment by jackielii** [comment]
Just a data table with a title, with some actions on the title. The data table within cards makes perfect sense for my scenario.

**Comment by Garbee** [comment]
Then, you can use a card with a title area and put some actions in there.
