### ISSUE TITLE
How to customize the colour of one specified elements?

### ISSUE THREAD

**Issue by futursolo** [google/material-design-lite#1052]
It is possible to select primary colour and accent colour to customize the colour of MDL elements, but how can I customize the colour of some specified elements(such as: use css selectors or attributes) other than the primary and accent colours.

**Comment by kybarg** [comment]
@futursolo Use `.mdl-color--indigo-100` for background and `mdl-color-text--grey-800"` for text color.
Color names and depths you can find at [MD docs](https://www.google.com/design/spec/style/color.html)

**Comment by Garbee** [comment]
Our classes for these are quasi-deprecated. Adhereing to MD restricts you to the primary and accent color (using 3 hues from each.) In the next major these specific classes are going to be removed by default. I am going to look into ways to help with getting pallet color hues in, but using direct classes isn't a good method. Including these is a bunch of bloat when most of the classes are never used.

> Limit your selection of colors by choosing three hues from the primary palette and one accent color from the secondary palette. ---- Via [MD color](https://www.google.com/design/spec/style/color.html#color-color-palette)

The preferred solution at the moment (and unto the future) is to use a Sass build pipe and use the color variables directly in your classes to set colors.
