### ISSUE TITLE
con't find '../spacing.css'

### ISSUE THREAD

**Issue by maguowei** [google/material-design-lite#1056]
https://github.com/google/material-design-lite/blob/master/templates/blog/entry.html#L49 .  I con't find spacing.css and in the browser it report 404.

![image](https://cloud.githubusercontent.com/assets/7894483/8701367/e6d643fe-2b43-11e5-80d7-436682ef4acc.png)

**Comment by Garbee** [comment]
Fixed via direct commit 6c96e69602126884cec8a21a53d89973ee7d73ce.

Thanks for reporting!
