### ISSUE TITLE
Touch Friendly Tooltips

### ISSUE THREAD

**Issue by Andy561** [google/material-design-lite#1061]
Playing around with tooltips and noticed something a bit interesting. It seems as if the tooltips were designed as more of a mouseover feature. When using touch the tooltips aren't dismissible. 

I am not sure if there is a work around or not, but I thought I would bring this to attention.

**Comment by SeanBannister** [comment]
This might be related to #1064

When the tooltips are showing they should disappear if you scroll down the page or tap somewhere else on the page, does this happen? What browser and phone are you using?

**Comment by Andy561** [comment]
I don't know that I tried scrolling but I do know that touching elsewhere on the screen does not dismiss them.

**Comment by Andy561** [comment]
Oh and this is on iOS 8.4 Safari

**Comment by SeanBannister** [comment]
Just tested this on iOS Safari, your right, if a tooltip is showing tapping elsewhere on the page does not hide it. But if you scroll or shift focus to another element it does hide. This appears to be a bug.

**Comment by tmd-uk** [comment]
Hi guys, I have just tested this on Android v5.0.2,and v4.2.2, on Chrome Version 43..... it shows the tool tip when icon is tapped or scrolling it disappears no problems. So not sure if it's an issue with iOS safari.
