### ISSUE TITLE
Feature: Support for "segmented" buttons?

### ISSUE THREAD

**Issue by victorhooi** [google/material-design-lite#1065]
It would be neat if there was direct support for segmented buttons - e.g.:

![uisegmentedcontrol_intro_2x](https://cloud.githubusercontent.com/assets/243499/8711058/f55f107e-2b91-11e5-804a-2242b97efd2e.png)

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/UIKitUICatalog/UISegmentedControl.html

The above seems to be a fairly common UI pattern.

However, I couldn't find this in the MD guidelines (somebody please correct me if I missed them), so not sure what the scope here is.

**Comment by Garbee** [comment]
We don't have this specified by Material Design. With MD you should put filtering under a menu item or use tabs. Those are the methods used in every example throughout the specification. This keeps the primary interface clean and clutter-free for as much content as possible.

**Comment by victorhooi** [comment]
Aha, in my case it was actually for radio buttons:

<img width="339" alt="screenshot 2015-07-16 12 13 48" src="https://cloud.githubusercontent.com/assets/243499/8714049/25511f1c-2bb4-11e5-823e-ee36468ac72f.png">

As in, instead of using radio buttons, as per the top, I was hoping to use segmented buttons. In this case, using coloured buttons makes sense, as the text/colour link up.

Is there an equivalent way of doing that in MD? (Or is the advice - use native radios).
