### ISSUE TITLE
Alignment of icon buttons inside a toolbar

### ISSUE THREAD

**Issue by peluprvi** [google/material-design-lite#1068]
- The search icon button is not on the middle of the toolbar (.mdl-layout__header-row).

![search_button_alignment](https://cloud.githubusercontent.com/assets/1561360/8715567/72152a32-2b5a-11e5-9cd1-9ef75d2ab825.png)

- All icon buttons are going up when the screen is <= 850px, including the menu button.

![button_aligment_under_or_eguals_850_px](https://cloud.githubusercontent.com/assets/1561360/8715699/70134e6a-2b5c-11e5-8efe-9cf36589d018.png)

Documentation section: http://www.getmdl.io/components/index.html#layout-section

Exemples of the right aligments and Google Material Design Specs:
https://www.google.com/design/icons/
https://www.google.com/design/spec/components/toolbars.html#toolbars-usage
https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

**Comment by tschiela** [comment]
The problem is the padding of the .mdl-textfield (padding: 20px 0). Because the parent (.mdl-layout__header-row) uses display: flex and align-items: center; we dont need the padding of .mdf-textfield for vertical center the searchfield.

The simple solution would be:
- remove the padding of .mdl-textfield
- remove the bottom: 20px of .mdl-textfield .mdl-button

**Comment by djalmaaraujo** [comment]
+1

**Comment by lucas-sartore** [comment]
Hello,

I am having a similar issue with a simple page, see code below.

![capture mdl](https://cloud.githubusercontent.com/assets/5740510/8894603/b4128f30-33b4-11e5-84f9-3d32b55670fe.PNG)

I am getting this up alignment only on this icon, and it is similar on Firefox (v39.0) and Chrome (v44.0.2403.107 m)

```html
<html>
<head>
	<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.indigo-pink.min.css">
	<script src="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.min.js"></script>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>

<!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Title</span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link" href="">Link</a>
      </nav>
    </div>
  </header>

  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="">Link</a>
    </nav>
  </div>

  <main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->Content</div>
  </main>

</div>
</body>
</html>
```

**Comment by Garbee** [comment]
@lucas-sartore please use StackOverflow for support. Your exact problem has already been asked and answered and is unrelated to this issue.

**Comment by lucas-sartore** [comment]
@Garbee, got you, I removed my comment, sorry for that!

**Comment by surma** [comment]
See #1400
