### ISSUE TITLE
Position menus over the emitting element

### ISSUE THREAD

**Issue by cptawakward** [google/material-design-lite#1070]
Shouldn't the menu cover the emitting element while it appears? 

Current Behaviour:
![image](https://cloud.githubusercontent.com/assets/4501018/8718979/fa706a98-2bc5-11e5-86a4-acdd7a0c664a.png)

Intended Behaviour:
![image](https://cloud.githubusercontent.com/assets/4501018/8719013/280a2cbe-2bc6-11e5-8282-ec41aae73400.png)

The MD design guidelines mentions that. Quoting from the spec page @ http://www.google.com/design/spec/components/menus.html#menus-behavior

"Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element."

**Comment by kybarg** [comment]
+1

**Comment by Garbee** [comment]
I think this may be done since we need a clear way to close the menu back out. Otherwise you are reduced to hitting somewhere else on the page so the menu isn't active, and then you hope you don't trigger another action by accident.

**Comment by innerpeace0** [comment]
The MD spec related to this is internally inconsistent. It gives the option to tap on the emitting element to dismiss, then goes on to say to position the menu so as to cover the emitting element, which would make tapping the emitting element to dismiss impossible. 

Tapping (or clicking) outside of something like an expanded menu to dismiss it is a very common ui today. Most users know to use neutral areas such as margins or text body for this so as not to trigger something else.

**Comment by Garbee** [comment]
No matter how common the UX pattern is to us, it isn't always obvious to end-users. Since there is inconsistency, we should get MD Guidance on proper alignment and see if what we do can pass (since it is good UX to provide an obvious out of a menu without a close action.)

**Comment by kengruven** [comment]
They show examples of emitting control being lots of types of things, from nothing at all (e.g., when right-clicking on some text), to this kind of button (the 3 dots), to a row of words (a menu bar).

Clearly in some cases the emitting control will always be visible (menu bar), and in some cases it will never be (right-clicking on some text).  I assume that's what they mean by "Dismiss a menu by tapping outside of the menu, or by tapping the emitting button (if visible)."

They do say "Menus are positioned over their emitting elements", and show menus appearing over the 3 dots, so I take it to mean that's where it should appear.

I'd say the ambiguous part of this spec is that it shows menus appearing fully below menu bars (as they always do), but there's no exception mentioned for this case.

**Comment by Garbee** [comment]
The spec is actually inconsistent with this point.

> Dismiss a menu by tapping outside of the menu, or by tapping the emitting button (if visible).

Then there is also this case: 

> Generally, selecting a menu item will also dismiss the menu. An exception is when a menu allows for multiple items to be chosen, for example, by using checkmarks.

Of which, showing the emitting element is a good thing to trigger a menu close.

There are also specific use-cases, such as creating toolbars, where you still show the emitting item. This is displayed in the form of the toolbar for Google Docs in the spec examples.

Positioning a menu *over* the emitting element, is a nice-to-have but not a requirement. Handling this positioning ourselves is going to be complicated. It also lowers accessibility since there is no clear way to hide the menu once opened. Overall, this is a low-priority task that will be handled as time is available. It will be an option in addition to the current default menu state.

**Comment by Garbee** [comment]
From @oddui in issue #1848.

> @Garbee i don't understand why it is tricky to get done in a way that is performant. It seems as simple as +/- the emitting element's height to the existing position :grey_question:

Performance is one niche aspect of integration. Yes, could be easily solved with the current setup (my test was completely redoing the menu setup in whole.) However, we still have a11y to worry about and the fact that the specification itself is very murky.

On the point of a11y alone, this may never be integrated into core. We need to do good testing there and make sure this addition doesn't hinder user experiences.

**Comment by Garbee** [comment]
I just tossed TNT to the v1 implementation and started a rebuild from scratch for V2. Covering the emitting element is trivial with a fresh start and none of this container stuff going on.

However, I'm still worried about a11y introducing this behavior into core. I will try to get some outside assistance in assessing these concerns. As long as there are clear expectations for a11y we can implement so covering the emitting element doesn't cause people problems, I'm good with introducing it with the v2 implementation.

**Comment by traviskaufman** [comment]
closing this; superseded by #4474
