### ISSUE TITLE
Menu: Invisibile Menu is over a data-table

### ISSUE THREAD

**Issue by choallin** [google/material-design-lite#1073]
I have a card with a title and in the title I have a menu added. Another part of the card is a data-table with the selectable class. Although the menu is hidden, I can not check the first few rows of the table.
![menu-table](https://cloud.githubusercontent.com/assets/1136392/8727424/e60eda3e-2bdf-11e5-99f6-9d1055d7555e.png)

![menu-table](https://cloud.githubusercontent.com/assets/1136392/8727437/0385783e-2be0-11e5-853e-5c48d7f53b0c.png)

**Comment by Garbee** [comment]
Duplicate #1025
