### ISSUE TITLE
Fixed header title is not displayed correctly

### ISSUE THREAD

**Issue by Gab-Metzger** [google/material-design-lite#1074]
Hello,

I'm using a fixed header but I have a weird issue:

On Chrome:
<img width="633" alt="capture d ecran 2015-07-16 a 17 26 54" src="https://cloud.githubusercontent.com/assets/5833788/8727467/3233cb40-2be0-11e5-852c-51b44cbb4b61.png">

On Firefox there is no menu button:
<img width="455" alt="capture d ecran 2015-07-16 a 17 31 10" src="https://cloud.githubusercontent.com/assets/5833788/8727526/7f2e6b30-2be0-11e5-8a3f-19357bcd1b32.png">

```html
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <span class="mdl-layout-title">Example Website</span>
  </div>
</header>
```

Am I doing something wrong ?

Thanks,
Gabriel

**Comment by Garbee** [comment]
Support questions should be asked on StackOverflow. You can use the `material-design-lite` tag along with any other appropriate tags. This will allow the most developers to see the problem to answer and for developers facing similar issues to find solutions more easily.

**Comment by madisona** [comment]
I'm not sure this is a stackoverflow kind of issue. The Dashboard template shows the same exact problem.

http://www.getmdl.io/templates/dashboard/index.html

(using chrome 44.0.2403.125)

<img width="879" alt="screen shot 2015-08-14 at 5 39 08 am" src="https://cloud.githubusercontent.com/assets/426479/9272355/1285499a-4247-11e5-8b9f-7ed6f4459f64.png">

**Comment by surma** [comment]
Confirmed. This probably sneaked in with PRs like #1174

**Comment by surma** [comment]
Unconfirmed :D This is actually fixed on master already. Ignore what I said.
