### ISSUE TITLE
Drawer with scrolling header

### ISSUE THREAD

**Issue by braginteractive** [google/material-design-lite#1076]
If you use the scrolling header with a drawer there is an issue. 

When the drawer is opened you can still scroll your webpage. This shows the bottom of the drawer and the rest of the webpage without the overlay. 

This can be reproduced at http://www.getmdl.io/components/index.html#layout-section/layout in the Scrolling Header section. 

Open the drawer and then scroll down within the example.

**Comment by SeanBannister** [comment]
Here's a [codepen of the bug in action](http://codepen.io/anon/pen/vOaKRa). Click the menu icon and scroll down the page.

**Comment by Garbee** [comment]
Thanks for the codepen Sean. I've been having trouble getting to the main site where I'm at today.
