### ISSUE TITLE
Site Showcase Request

### ISSUE THREAD

**Issue by kix2902** [google/material-design-lite#1077]
Please include:
- Description: Personal Webpage of Ismael Reyes
- Primary Link: http://kix2902.es
- Screenshot:
  ![screencapture-kix2902-es](https://cloud.githubusercontent.com/assets/222587/8733542/8f47c196-2c04-11e5-875f-7cbe797731e7.png)

**Comment by innerpeace0** [comment]
+1

**Comment by jericbryledy** [comment]
what are the qualifications to showcase a site?

**Comment by addyosmani** [comment]
@jericbryledy Uses MDL in a sane way really. I'll be including examples folks have submitted on the site in the very near future.
