### ISSUE TITLE
Drawer button is missing a :hover and :active state

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1079]
```mdl-layout__drawer-button``` is missing a :hover or :active state. There's nothing specifically mentioned in the spec but as a button its safe to say it should have these states. And existing Google applications are doing this.

**Comment by surma** [comment]
@santokii Do you know anything about a hover state of the drawer button?

**Comment by surma** [comment]
Hover has been generally avoided in the MD spec, as hover is not a thing on mobile. However, there’s nothing speaking against a hover state. It’s not something that will make it into core, but you are free to add that yourself,obviously.

**Comment by SeanBannister** [comment]
Can understand, however it does feel inconsistent, take [this (codepen)](http://codepen.io/anon/pen/ZGwGqy) layout example which is in the documentation. The search button on the right has a hover state but the hamburger doesn't.

Also I was just browsing the [button documentation](http://www.getmdl.io/components/index.html#buttons-section) and it's really odd that some of the buttons have hover states and others don't.

**Comment by surma** [comment]
I totally see your point, however, this was direct feedback from the MD team. They also said, a ripple is possible and even adequate, but hasn’t officially made the spec yet. So for now, we are going to leave it as is :)

**Comment by lancebeaudry** [comment]
Does anyone know of a simple workaround to make the hover states apply on touch/mobile?
