### ISSUE TITLE
Dropdown menu (UX Review 3 feedback)

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#108]
- [ ] Download the general [stickersheet](https://storage.googleapis.com/spec-prod-media/quantum006/0Bx4BSt6jniD7Q3FVZ0FnM18yTHM/stickersheet_general.sketch) sketch file for spec and refer to Folder > Components > menu > menu (I believe that we show the default selected item in the dropdown menu at the top with the arrow as part of the clicked state) 

![](http://i.imgur.com/x1enwWQ.png)

**Comment by jbiron** [comment]
i added standard mdl-textfield css classes on the <select> tag and worked great with some little custom tweak like classlist.add("is-dirty") here and there

**Comment by sgomes** [comment]
Superseded by #4475
