### ISSUE TITLE
[Component Request] Lists: Controls

### ISSUE THREAD

**Issue by nickretallack** [google/material-design-lite#1080]
[Lists: Controls](https://www.google.com/design/spec/components/lists-controls.html)

I'd like some CSS classes to position icons inside of mdl-navigation__link elements, especially inside a mdl-drawer.  There's a primary action on the left, and a secondary action on the right.

These are even used in the [example dashboard template](http://www.getmdl.io/templates/dashboard/index.html), but it uses custom CSS to position them there and center them vertically.  I'd prefer if this CSS was included in MDL so it could be better tested and hardened for cross-browser support.  Polymer shows them off in [paper-item](https://elements.polymer-project.org/elements/paper-item?view=demo:demo/index.html) and they also appear in the [Polymer Web Starter Kit](https://developers.google.com/web/tools/polymer-starter-kit/index?hl=en) template.

**Comment by nickretallack** [comment]
I'll reference the [parent issue](https://github.com/google/material-design-lite/issues/584).

**Comment by innerpeace0** [comment]
+1

**Comment by traviskaufman** [comment]
Closing; superseded by #4473, which will include first-class support for primary/secondary actions.
