### ISSUE TITLE
First Google result still says "Coming Soon"

### ISSUE THREAD

**Issue by nickretallack** [google/material-design-lite#1081]
When I Google search "Material Design Lite" the first thing I get is [this page](https://developers.google.com/web/tools/material-design-lite/index?hl=en).  It says "Coming Soon" and has no links to the real site.  Can we get that page changed?

**Comment by innerpeace0** [comment]
The [website for this project] (http://www.getmdl.io/) forwarded to [that page] (https://developers.google.com/web/tools/material-design-lite/index?hl=en) before the project was opened to the public. Sometimes it takes a few days for googlebots to catch up.

**Comment by addyosmani** [comment]
I've sent over a PR upstream that should get landed shortly to address this. It's over in https://github.com/google/WebFundamentals/pull/1443. Let's track it there.
