### ISSUE TITLE
Hamburger icon in header badly positioned except in codepen.io

### ISSUE THREAD

**Issue by alextekartik** [google/material-design-lite#1084]
If I take a simple example such as a fixed header. The example work fine in codepen.io:

http://codepen.io/alextekartik/pen/ZGjLeb

However, locally or using any other online tool the exact same example looks wrong:

http://cssdeck.com/labs/uxxls0yo

and the hamburger icon is a little bit too high. What is causing this and how to fix this?

**Comment by Garbee** [comment]
Looks like CSSDeck is doing something funky with asset loading. Handling it in such a way using JS that a CORs check occurs which is failing since we don't set those headers.

**Comment by apollo13** [comment]
Add `<!DOCTYPE html>` and it works on both… (go figure, took me an hour last time I ran into this ;))

**Comment by alextekartik** [comment]
Adding <pre><!DOCTYPE html></pre> indeed works...Sorry for the trouble, that was driving me crazey
