### ISSUE TITLE
Problems with tabs

### ISSUE THREAD

**Issue by Eliezer-Pujols** [google/material-design-lite#1091]
In the simple header with scrollable tabs , I found a problem.

That  it happens in small screen sizes if not fit the tabs are cut .

This is because,  the arrow left and right to move tabs appear only in sizes of desks and not on phones.

**Comment by Garbee** [comment]
Right now, it is in absolute alignment with the spec which states "Checkboxes should accompany each row if the user needs to select or manipulate data."

Instead of breaking spec, we simply need to introduce lists and eventually list controls.
