### ISSUE TITLE
mdl-card__menu not documented

### ISSUE THREAD

**Issue by nikvm** [google/material-design-lite#1094]
Component : Card

What are you trying to do or find out more about?
Element class mdl-card__menu

Where have you looked?
http://www.getmdl.io/components/index.html#cards-section

Where did you expect to find this information?
In section "Configuration options"

What did I find out?
- Container for positioning child elements in top right card corner
- Docs show an example share button

Thanks.

**Comment by kattybilly** [comment]
Any updates about it's documentation ?

**Comment by Bwc84** [comment]
Sorry for the late Commons I've barely figured out how to comment back. Business and commercial window cleaning and my family has been in this industry for seven four years basically before my uncle died he mention that in business you have to own all aspects of your business so I'm at the point where you know I'm figuring out how to code and do all my internet or any kind of identity for the business on my own then go to school been in business for 9 years so please bear with me thank you

**Comment by Bwc84** [comment]
And by the way my phone number is 619-796-0553 please feel free to contact me I'm running out of Hosting support for my website people as I have already started to out grow my support. no educational background I'm completely self-taught as you can see I'm not the best but I am very very very very interested in learning
