### ISSUE TITLE
Are we overselecting?

### ISSUE THREAD

**Issue by nickretallack** [google/material-design-lite#1097]
I'm seeing selectors that look like this:

```css
.mdl-layout__drawer .mdl-navigation .mdl-navigation__link {}
```

Is this necessary?  I'd think this would suffice:

```css
.mdl-layout__drawer .mdl-navigation__link {}
```

It's implied that a `mdl-navigation__link` will be inside a `mdl-navigation`.  You don't need nested selectors.  Putting nested selectors adds specificity, which makes it harder to override things in special cases.

**Comment by surma** [comment]
I am not saying we are not overselecting, but changing the CSS rules now needs *extensive* testing as we are lowering the specificity. Not sure that’s worth the effort at least for the current, rather fast-evolving MDL.

**Comment by Garbee** [comment]
The selectors also help enforce that the proper structure is followed. If you aren't following what is provided then you won't get the full and proper design.

I don't really see this as an issue. For those "special cases" where some modification is needed, the developers doing it should *know* what to do and how to handle specificity.

**Comment by jimbojetlag** [comment]
Over selecting makes refactoring a royal pain in the bios. It would require editing a lot of markup.

- In the future, would MDL 2.0 require these longs selectors to be changed?
- Should we feel safe to generously apply a lot of selectors in the markup without being worried about refactoring? This does not seem promising as @surma called the current state of MDL as 'fast evolving'.
- Is there a recommended strategy to minimize this? Eg, should we use sass `@extend` to rename `.mdl-layout__drawer .mdl-navigation__link` to `.my-link`, and the refactor the sass file only, if required in the future?

**Comment by Garbee** [comment]
> MDL 2.0 require these longs selectors to be changed?

Major updates are *breaking* so... expect things to need to be worked on there. I'm not sure how that should be a concern.

> Should we feel safe to generously apply a lot of selectors in the markup without being worried about refactoring?

You should feel as safe as you do. The selector problem shouldn't get *worse* in any areas. So, for example we won't go making things more specific later which could break your code. If you code to what we have now then, unless something random happens, what you write will continue to work without a problem.

> Is there a recommended strategy to minimize this?

There is nothing we see that needs to be minimized, so the official answer on that is no. As a side note though, your abstracting two classes into one isn't going to work how you think it is. The same level of specificity will be applied, just more selectors created (unless sass has some super-cool thing that can do that which I haven't seen yet.)

**Comment by jimbojetlag** [comment]
> There is nothing we see that needs to be minimized, so the official answer on that is no.

Consider this div tag in the android template:

```html
<div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-card mdl-shadow--3dp">...</div>
```
A page might have a list of hundreds of cards. The above class makes the markup size increasing fast. That's a lot of repeated data to be sent to mobile clients. Cannot this be reduced to something like `my-card` with sass `@extend`?

**Comment by Garbee** [comment]
@jimbojetlag That can be done (and should be), but it doesn't address the concerns raised here at all.

**Comment by Garbee** [comment]
I'm closing this one off. There is no clear action here except to reduce specificity as much as possible which will be very time-consuming and may cause plenty of breakage internally.

Specificity is something developers need to understand and take into account when modifying any styles provided.
