### ISSUE TITLE
Color on fab, mini-fab and raised buttons does not reflect colored and disabled properties

### ISSUE THREAD

**Issue by Nils-Kolvenbach** [google/material-design-lite#1102]
Although I could understand why the fab and mini-fab buttons does not reflect the mdl-button--colored property (to attract attention), I don't see why the disabled property only resets the standard and icon buttons to the grey scheme. Bug or feature? ;)
![button-color](https://cloud.githubusercontent.com/assets/2317940/8763575/f15f24f0-2da3-11e5-8275-25b4381483ef.jpg)

**Update**
Well, I now see that it was planned to reset the disabled buttons to a grey scheme.
Interestingly i have to set the CSS property to !important to make it work ...
My browser is Chrome 43.0.2357.134 m (64-bit) (latest version)
![button-disabled](https://cloud.githubusercontent.com/assets/2317940/8763625/053e9c00-2da7-11e5-9ad1-999be44968d8.jpg)

**Comment by Garbee** [comment]
Fixed with commit af2443f4b26321999ea5cae0ef826cb04cd19609. Just waiting for a patch to go out on stable.
