### ISSUE TITLE
Have any modal system in MDL?

### ISSUE THREAD

**Issue by tanbir2013** [google/material-design-lite#1104]
Hello concern,I'm much pleasing see this MDL.It is great than twitter Bootstrap,but I think it has some lack. Such as bootstrap has a own modal system but I did not find modal system in it's component.

I want to know that have any modal system in MDL or have you any plan to make it's own modal system.Please inform me as soon as possible.I want to use MDL in my web application.

Best Regards,
Hasan Tanbir
Lecturer,Dhaka Engineering Institute

**Comment by Garbee** [comment]
Issue #781

**Comment by foo-baar** [comment]
@tanbir2013 : Hey Tanbir, I am also struggling for the same same features, thought to check if you have found any right replacement for this ?

**Comment by Garbee** [comment]
@foo-baar please check the upstream issue for all updates relating to MDL. For anything else please use StackOverflow for support.
