### ISSUE TITLE
Images block on getmdl.io

### ISSUE THREAD

**Issue by sleepydisaster** [google/material-design-lite#1106]
Is there going to be a separate block for images? Which classes to apply etc.?

**Comment by kybarg** [comment]
@sleepydisaster  According to MD specs there are two components that can handle that - images grid and tiles. But in [MDL](http://www.getmdl.io/components/index.html#cards-section) cards only can help you with it (third example). Also you can use MDL grid, but need to change gutter size to make it look like MD grid list.

**Comment by Garbee** [comment]
Can you be more specific about what you mean by "Image Block"? A grid is one thing, but this sounds like something else to me.

If a better description isn't easy, then could you point out where on the site you are seeing what you are looking for?

Thanks.

**Comment by sleepydisaster** [comment]
Thanks for your answers. I thought about this class "mdl-components__link-image". I haven't found any information regarding its usage. So I was wondering if it would be possible to add images section to the getmdl website. So, that users can easily find the demanded information.

**Comment by csotomon** [comment]
@sleepydisaster 

U can find the class in this file:

https://github.com/google/material-design-lite/blob/69c34ee3596c8087b3d17136192dd92dd82d281a/docs/_assets/components.css

**Comment by sgomes** [comment]
Closing this issue, as it seems to be referring to microsite styling, rather than an MDL component.
