### ISSUE TITLE
Proposal: Tooltip bindings also on classes

### ISSUE THREAD

**Issue by Gambloide** [google/material-design-lite#1112]
As the headline implies this is regarding the [mdl tooltips component](http://www.getmdl.io/components/index.html#tooltips-section). [(Tooltips design spec)](http://www.google.com/design/spec/components/tooltips.html#)

Sometimes it would useful to be able to assign the same tooltip to multiple elements. If you had e.g. multiple `mdl-card` elements where some `mdl-card__menu` buttons are identical you would not want to give each button a unique `id` if you could just give them all one `class` that is associated to the tooltip.

Since the `for` tag is reserved for associations with `id` attributes I implemented a `MaterialTooltip.prototype.init()` function which also resolves a custom attribute `for-class` . This approach also prevents the degradation of performance of the current implementation relying on the `id`.

My proposal for `material-design-lite/src/tooltip/tooltip.js:MaterialTooltip.prototype.init`

```javascript
/**
 * Initialize element.
 */
MaterialTooltip.prototype.init = function() {
  'use strict';

  if (this.element_) {
    var forElId = this.element_.getAttribute('for');
    this.forElements_ = [];
      
    if (forElId) {
      this.forElements_.push(document.getElementById(forElId));
    } else {
      var forElClass = this.element_.getAttribute('for-class');
      if (forElClass) {
        this.forElements_ = document.getElementsByClassName(forElClass);
      }
    }

    for (var i = 0; i < this.forElements_.length; i++) {
      this.boundMouseEnterHandler = this.handleMouseEnter_.bind(this);
      this.boundMouseLeaveHandler = this.handleMouseLeave_.bind(this);
      this.forElements_[i].addEventListener('mouseenter', this.boundMouseEnterHandler,
        false);
      this.forElements_[i].addEventListener('click', this.boundMouseEnterHandler,
        false);
      this.forElements_[i].addEventListener('mouseleave', this.boundMouseLeaveHandler);
    }
  }
};
```

Since I only intended to be a user and not a developer of MDL neither have I set up anything to run the needed tests and create a clean pull request for this, nor have I studied the Google JavaScript Style Guide or signed the CLA yet. As such I am leaving this here for discussion (maybe inclusion by someone that does have his/her environment set up properly) and as a possible remedy for others coming across this limitation.

**Comment by Garbee** [comment]
This seems to break the idea that  one component is an isolated item. The idea of components is they only touch what is within their elements bounds. The suggestion here is to make the tooltip touch the entire document which is a big no-go in my opinion.

**Comment by traviskaufman** [comment]
Closing; superseded by #4495 

We are still in the very early stages of v2 and are currently working towards an alpha. Our `master` branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄
