### ISSUE TITLE
compile sass fail in gulp-sass current version.

### ISSUE THREAD

**Issue by zeakd** [google/material-design-lite#1118]
I use gulp-sass

and my gulp code
``` js
gulp.task('sass:dev', function(){
    return gulp.src([
        config.app + '/styles/beanbrothers.scss'
    ])
        .pipe(gp.sass())
        .pipe(gp.rename({
            basename: 'style'
        }))
        .pipe(gulp.dest(config.tmp + '/styles'));
})
```

and my project structure
```
.
├── app
│   └── styles
│       ├── beanbrothers.scss
│       ├── bootstrap/
│       └── material-design-lite/ (clone)
...
└── gulpfile.js

```
beanbrothers.scss have same code (just path changed) with material-design-lite.scss for test 

and I got compile error
``` bash
gulp sass:dev
[11:29:42] Using gulpfile ~/work/client/mockup/gulpfile.js
[11:29:42] Starting 'sass:dev'...
Assertion failed: (utf8_validate(str)), function emit_string, file ../src/libsass/json.cpp, line 1139.
Abort trap: 6
```
just variable and mixin, same.

I know mdl also use gulp-sass, so I changed to same gulp-sass version of your project ( ^2.0.4 -> ^1.3.3 ) and it works. does mdl have any issue with current gulp-sass?

**Comment by surma** [comment]
Could this be related to #523?

**Comment by Garbee** [comment]
Well #1075 landed which may have caused the breakage. Let's update gulp-sass (and node-sass as well under it) to see if that fixes it. I'm not hitting any issues compiling the updates locally, but I seem to miss things like that.

**Comment by addyosmani** [comment]
@sgomes when you're back, could you verify this isn't still breaking under 1.0.1? (soon 1.0.2). I have't been able to repro locally.

**Comment by sgomes** [comment]
Looks like MDL has been updated to use gulp-sass 2.0.x, so this should be fixed. Feel free to reopen if there are any issues left!

**Comment by enanox** [comment]
Hi, I run into a similar issue on another project with Material Design (the one that is hosted on the angular/bower-material repo), and the thing is, I found several ´\0´ characters throughout the code (mainly on `@media queries`). 
When I removed those, the compilation went fine.
I hope this is not a leak on `node_sass`, and that this workaround helps someone else.
