### ISSUE TITLE
refreshing page won't remember your scroll position

### ISSUE THREAD

**Issue by jericbryledy** [google/material-design-lite#1120]
What steps will reproduce the problem:
1. scroll page to anywhere but the top
2. hit refresh
3. page will reload at the top

**Comment by kybarg** [comment]
@jericbryledy cause layout is generated by javascript, I don't like it too

**Comment by surma** [comment]
@kybarg The reason is not really the JavaScript but the fact that we enclosing the content into a scrolling `<div>`.

@jericbryledy I don’t think we can do anything about this. It’s the browsers job really to remember scroll positions while reloading (which Chrome does just fine). You’d have to file an upstream bug against your respective browser.

**Comment by jericbryledy** [comment]
Oh I see. Just FYI, I have tried http://www.getmdl.io/ on Chrome and Firefox for both Windows and Linux, + Internet Explorer which none remembers the scroll.

**Comment by Garbee** [comment]
@surma Testing here on the latest dev channel of Chrome it isn't going back to the previous scroll position either. Looks like this is a side-effect of how layout is handled.

**Comment by Gheoan** [comment]
Removing position:absolute for .mdl-layout__container seems to fix this.
https://github.com/google/material-design-lite/blob/master/src/layout/_layout.scss#L58

**Comment by jericbryledy** [comment]
will this give side effects though?

**Comment by Gheoan** [comment]
I think it does. The line was added to fix a layout issue but the commit does not reference a GitHub issuse.
https://github.com/google/material-design-lite/commit/d8e63d676b3a11d01e3e1c960d3d88d8fa5f1116

**Comment by jericbryledy** [comment]
how do you reopen an issue?

**Comment by innerpeace0** [comment]
You can't re-open your own issue on github if a collaborator has closed it. You'd need to file a new one, perhaps, referencing the old one and giving some reasons why it shouldn't just get closed again as being a duplicate. Good luck.

**Comment by Garbee** [comment]
Please do *not* file new issues simply because you feel one was closed improperly. We read follow-up comments and will reopen if appropriate.

Nothing can be done here without a layout refactor in a major version since any change could break things already relied upon.

**Comment by surma** [comment]
@Garbee @addyosmani I was thinking about reopening this and marking it as v2 or something. A refactor of the entire layout component *might* be desirable and feasible. WDYT?

**Comment by Garbee** [comment]
I think we have enough little problems with Layout cropping up. Instead of re-opening we should make a new issue to track the layout issues brought up that need a BC break. Tag it right and use it for tracking reference.

**Comment by surma** [comment]
SGTM

**Comment by Sam-Hepworth** [comment]
In my view this a very serious problem and so user-unfriendly that I cannot use the framework for any real stuff.

**Comment by Garbee** [comment]
We know it is a real problem. However, we are doing our best to *not* break things within a major version. So there is nothing we can do here until 2.x when a full layout refactor is being carried out.

**Comment by Sam-Hepworth** [comment]
Fair enough. As a workaround the scroll position can be stored when the page is unloaded and restored when the page is loaded again (see https://developer.mozilla.org/en-US/docs/Web/API/History_API) A lot of stuff I work with uses history.state anyway...

**Comment by kybarg** [comment]
For those who lost faith)
Now scroll position is remembered!
```javascript
      // FIX scroll bug
      var mainScrollArea = document.getElementsByClassName('mdl-layout__content')[0];

      window.onload = function () {
        if(window.location.href == localStorage.getItem('lastUrl')) {
          mainScrollArea.scrollTop = localStorage.getItem('scrollTop');
        } else {
          localStorage.setItem('lastUrl', window.location.href);
          localStorage.setItem('scrollTop', 0);
        }
      }

      mainScrollArea.addEventListener('scroll', function() {
        localStorage.setItem('scrollTop', this.scrollTop);
      });
```

**Comment by pratik** [comment]
This worked for me : 

Add this code in css file AFTER importing material.min.css

`.mdl-layout__container {
	position: relative;
}`

**Comment by jericbryledy** [comment]
@pratik the header wouldn't follow you as you scroll down the page if you do that
