### ISSUE TITLE
NavBar and TabPanel

### ISSUE THREAD

**Issue by qlecomte** [google/material-design-lite#1129]
Hello,
On my website, I use Tabs with TabPanel to display informations.
For more convenience, I want to use a NavBar instead of tabs when the user is on his mobile phone (because tabs are too small to be display nicely).
But with the same links in both cases (tabs and nav), the links in the navbar has not effect at all.

Is there a way to handle this ? Or will it be possible in the future ?
Thank you for your answers.

**Comment by surma** [comment]
I think #929 is addressing the same issue. This is a bigger undertaking, we’ll have to do some code rework for this to work consistently and in accordance with the MD spec.
 Closing this in favor of the aforementioned PR.
