### ISSUE TITLE
Textfield validation

### ISSUE THREAD

**Issue by thebigb** [google/material-design-lite#1132]
Textfield validation is triggered immediately on element upgrade, which could be nice in some scenarios, but in others negatively affects user experience.

Example: 

When you add a `required` attribute to a text field and you load an empty form, consider sitting on layer 8 and watching a complete form you haven't started to fill in turning into a red abyss.

My suggestion is triggering validation on the blur event, or immediately if the field or encapsulating form is marked with a server-set class/attribute indicating that the form was pre-populated.

Also, are there any plans for server-side validation facilities (such as the manually setting of errors)?

**Comment by Garbee** [comment]
> Also, are there any plans for server-side validation facilities (such as the manually setting of errors)?

We aren't handling server-side cases directly in any way. However we can look at making component methods to help with triggering errors in the right places programatically. Opened issue #1136 to handle that.

Let's keep this issue focused on the initial validation state itself.

On that note, what we do is inline with standard HTML5 validation. [Example jsfiddle](http://jsfiddle.net/fbvfffuc/) shows invalid state applied immediately on load even though no user interaction. I'm not sure why we should stray away from what browsers do. So until browsers support a neutral state themselves, I'd say this isn't an issue for us to handle.

**Comment by thebigb** [comment]
> Opened issue #1136 to handle that.

Thanks!

> On that note, what we do is inline with standard HTML5 validation. Example jsfiddle shows invalid state applied immediately on load even though no user interaction.

Ah, I didn't realize that. I had been fiddling around with the textfield javascript and assumed it was `this.input_.validity.valid` that was triggering validation.

> I'm not sure why we should stray away from what browsers do. So until browsers support a neutral state themselves, I'd say this isn't an issue for us to handle

Agreed.

Thanks for the elaboration.
