### ISSUE TITLE
Example of two column menu 

### ISSUE THREAD

**Issue by adaro** [google/material-design-lite#1133]
Hey guys is there an example (with css overrides if need be) of how to have a a menu with two columns? 

I am trying to do the following: 

          <span id="menu-lower-left" class="select-category"><span>Select a category</span></span>
          <ul class="category-list mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect"
              for="menu-lower-left">
            <li class="mdl-menu__item">Some Action</li>
            <li class="mdl-menu__item">Another Action</li>
            <li class="mdl-menu__item">Additional Action</li>
            <li class="mdl-menu__item">Yet Another Action</li>
          </ul>

CSS looks like:
`
  .category-list {
    list-style-type: disc;
    columns: 2;
    -webkit-columns: 2;
    -moz-columns: 2;
    list-style-position: inside;
  }
`
When I try simply add 2 columns, it works but my list items disappear! 

<img width="318" alt="screen shot 2015-07-20 at 1 04 35 pm" src="https://cloud.githubusercontent.com/assets/3979857/8785912/e74b75d0-2edf-11e5-9662-cd748eba4a5b.png">

Any idea why this is happening?

**Comment by Garbee** [comment]
Please go to StackOverflow for support. This tracker is for problems directly related to the core Material Design Lite code.

**Comment by adaro** [comment]
Okay here is a plunker as well. Def a bug: http://plnkr.co/edit/d9nNB7jg4W8nsGzdlnC4

**Comment by innerpeace0** [comment]
Works fine on Pale Moon (a lightweight Firefox derivitive) on Linux.

**Comment by adaro** [comment]
@innerpeace0 - yeah, works fine in firefox. chrome unfortunately, does not work.

**Comment by Garbee** [comment]
This is absolutely *not* a bug with MDL. The [menu specification](https://www.google.com/design/spec/components/menus.html) does not define multi-column menus. If you have numerous choices, then a scrollbar should be displayed as per the specification.

You are doing custom code to modify default behavior in a way it is not intended to support. Which also goes against the specification. This is not a core issue and support should be handled on StackOverflow.

**Comment by adaro** [comment]
it's not a bug according the spec, but it's a bug. looks and walks like a duck.

**Comment by innerpeace0** [comment]
@adaro. You seem new here. I've been following this project from its public launch, so I can bring you up to speed on what's happening here. This is a very active project with a great team of people who really have it together, but MDL isn't trying to be all things to all webmasters. They are very focused on bringing MD, per its specs, to the web. 

If what you want isn't in the MD specs, this isn't the place for it, no matter how much you want it. You'll have to either figure it out yourself or get help elsewhere like stackoverflow.

**Comment by adaro** [comment]
@Garbee new here indeed and really like MDL so far, great alternative to using components. Whether it's a feature or bug, 6 or half a dozen, right? is there a forum for submitting feature requests?

**Comment by innerpeace0** [comment]
> is there a forum for submitting feature requests? 

If the feature requested is in the MD specs, it'll get immediate attention and may even get added amazingly fast.

If it isn't in the MD specs, it probably won't be happening here.

**Comment by Garbee** [comment]
> If the feature requested is in the MD specs, it'll get immediate attention and may even get added amazingly fast.

Let's leave the "may even get added amazingly fast" off of here, the core team makes no promises as to how fast things are done. Everything gets done in due time. It takes a lot of review to add new things so it isn't like we can whip it up and toss it out in a few days.

> If it isn't in the MD specs, it probably won't be happening here.

Reword to "If it isn't in the MD spec, it won't happen here unless we goof up or are ahead of the specification in its public form." MDL provides direct MD only, nothing more.

>  is there a forum for submitting feature requests?

This is the forum for feature requests. The way this issue is stated directly is support for non-specified (nor provided) functionality. Getting ahead to having a FR filed, the dogma is this... How is a multi-column layout more useful than a simple single-row dropdown? As far as I can tell, it isn't. Then, in what cases should you use mutli-colum compared to single-column? Finally, just off the top, how should submenu's react when put within multi-column layouts (if they are even allowed)?

**Comment by innerpeace0** [comment]
@Garbee said:

> Let's leave the "may even get added amazingly fast" off of here, the core team makes no promises as to how fast things are done. Everything gets done in due time.

I wasn't making promises on behalf of the team, just giving recognition for the amzaing progress I've been observing here. You folks are a true inspiration.

**Comment by adaro** [comment]
This fellow on SO helped! http://stackoverflow.com/questions/31527063/material-design-lite-example-of-two-column-menu-not-working-in-chrome
