### ISSUE TITLE
Memory leak if component has no downgrade method

### ISSUE THREAD

**Issue by jakub300** [google/material-design-lite#1134]
In `deconstructComponentInternal` if component has no downgrade method it is never removed from `createdComponents_` array and stays in memory forever.

[mdlComponentHandler.js#L274-281](https://github.com/google/material-design-lite/blob/21d6bb41d1c88203bb28a1130bd454fec56f3ca8/src/mdlComponentHandler.js#L274-281)

Simple fix (not tested):
```javascript
function deconstructComponentInternal(component) {
  if (component) {
    var componentIndex = createdComponents_.indexOf(component);
    createdComponents_.splice(componentIndex, 1);

    if(component[componentConfigProperty_]
        .classConstructor.prototype
        .hasOwnProperty(downgradeMethod_)) {
      component[downgradeMethod_]();

      var upgrades = component.element_.dataset.upgraded.split(',');
      var componentPlace = upgrades.indexOf(
        component[componentConfigProperty_].classAsString);
      upgrades.splice(componentPlace, 1);
      component.element_.dataset.upgraded = upgrades.join(',');

      var ev = document.createEvent('Events');
      ev.initEvent('mdl-componentdowngraded', true, true);
      component.element_.dispatchEvent(ev);
    }
  }
}
```

**Comment by Garbee** [comment]
I don't think we want to use desconstruct to simply remove it from the created components. The entire point of this is to de-register event listeners and do other cleanup work before DOM removal.

If this were to be done it should be its own method (which is then called from deconstruct) that only removes it from the created array. That way it is clear intent that you aren't doing any cleaning, just removing from the created array internally.

**Comment by addyosmani** [comment]
> If this were to be done it should be its own method (which is then called from deconstruct) that only removes it from the created array. That way it is clear intent that you aren't doing any cleaning, just removing from the created array internally

I agree with this being a more appropriate approach here. @Garbee I was going to suggest moving this to 1.0.2, but if you feel that we can tackle in the next day or two it should be able to land for 1.0.1. I'm happy to help with before/after leak analysis if you're working on a fix.

**Comment by Garbee** [comment]
This is a P0 for the next tag after 1.0.1.

Did an initial mockup that would function, but only one component at a time instead of all the components within the internal array. Plus raising #1144 back to my mind to work on. So, going to tackle both of these in the next tag release instead of shoehorning a crap patch into this one.

**Comment by reinholdk** [comment]
I'm using 1.0.4. MaterialLayout is still not being removed from createdComponents_ when calling downgradeElements. This is quite critical since a layout usually occupies quite some memory in the _content property.

**Comment by Garbee** [comment]
@reinholdk Issue #1340 is more appropriate for discussion on that point. I'll respond over there to your comment.

**Comment by samccone** [comment]
I can write a perf test for this... or maybe all of the components where we can upgrade and downgrade :)

**Comment by sgomes** [comment]
This should now be fixed.
