### ISSUE TITLE
Floating Label doenst work

### ISSUE THREAD

**Issue by hannespreishuber** [google/material-design-lite#1137]
copied from components
div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ">
                                        <input class="mdl-textfield__input" type="text" id="sample3" />
                                        <label class="mdl-textfield__label" for="sample3">Text...</label>
                                    </div>
got
![floating](https://cloud.githubusercontent.com/assets/3587156/8787277/86ce5d0e-2f33-11e5-8f29-0ef2fee36719.PNG)

**Comment by surma** [comment]
Can you create a codepen that reproduces the issue for you and give us the specs of your system (OS version, browser version etc)? The labels are working fine for me.

**Comment by hannespreishuber** [comment]
was in layer 8 - js path
