### ISSUE TITLE
Header Being Removed

### ISSUE THREAD

**Issue by findborg** [google/material-design-lite#1138]
I am having a hard time figuring out why my header is being removed on screen resizing to small.
I am not using any of the responsive classes. Just the straight layout classes.
Here is the code I am using:
```
<header class="mdl-layout__header mdl-layout__header--scroll mdl-layout__header--transparent">
    <!-- Top row, always visible -->
    <div class="mdl-layout__header-row ">
      <!-- Title -->
       <span class="mdl-layout-title"></span>
      <div class="mdl-layout-spacer"></div>
      <jdoc:include type="modules" name="tbar-right" />
      
              <!-- Right aligned menu below button -->
<button id="demo-appmenu-lower-right"
        class="mdl-button mdl-js-button mdl-button--icon">
  <i class="material-icons">apps</i>
</button>

<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
    for="demo-appmenu-lower-right">
  <jdoc:include type="modules" name="f-nav" style="html"/>
  
  <li class="mdl-menu__item">More soon</li>
</ul>
      
        
        
 
        <!-- Right aligned menu below button -->
<button id="demo-menu-lower-right"
        class="mdl-button mdl-js-button mdl-button--icon">
  <i class="material-icons">more_vert</i>
</button>

<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
    for="demo-menu-lower-right">
  
  <li class=""><a class="mdl-menu__item" rel="nofollow" href="<?=$script_url?>/login"><?=$word[51]?></a></li>
  
  <li class="mdl-menu__item">Yet Another Action</li>
</ul>

      
    </div>
    
  </header>

```

**Comment by surma** [comment]
@findborg Would you mind creating a codepen that reproduces the issue? Also, what’s your OS version and browser version?

**Comment by findborg** [comment]
Ubuntu 14.04 LTS
Chrome Version 43.0.2357.134
here is an example with the issue. http://findborg.com/n

Also, forgot to mention that I am pulling in one of the theme style sheets as well.
https://storage.googleapis.com/code.getmdl.io/1.0.0/material.grey-indigo.min.css

**Comment by Garbee** [comment]
Check the configuration options in the documentation. It provides the class needed to show the header on smaller screens.

**Comment by Garbee** [comment]
Also for future reference, support questions should be asked on StackOverflow. This tracker is for issues with the code provided by the project itself.
