### ISSUE TITLE
Offline Capable

### ISSUE THREAD

**Issue by labnol** [google/material-design-lite#1139]
Not exactly an issue but more a feature request. It would be nice if MDL has offline capabilities built-in.

**Comment by surma** [comment]
@labnol What exactly do you mean? If you set up a service worker for your site, MDL will work offline just fine as MDL has no dynamic parts. But we are not a framework per se, so we won’t include something that does the SW for you as it is highly specific to the website.

**Comment by sgomes** [comment]
Unclear request.
