### ISSUE TITLE
mdl-data-table--selectable  doesnt show checkboxes with Angular

### ISSUE THREAD

**Issue by hannespreishuber** [google/material-design-lite#1140]
effect table with mdl-data-table--selectable  and angular binded list 
![unbenannt1](https://cloud.githubusercontent.com/assets/3587156/8794760/cb659b32-2f86-11e5-84be-f54976a6b87c.PNG)

Works with Chrome-
not work with IE11 and Mozilla

**Comment by Garbee** [comment]
Please use StackOverflow for support. The core team can't support every technology combination that may be used.

**Comment by hannespreishuber** [comment]
it's not a question of support- It's a question of Fitting together. Angular does (like any spa Framework) a kind of late binding dom Manipulation. There must be a feature to update UI Rendering, regarding the JavaScript manipulated dom from MDL

**Comment by Garbee** [comment]
>It's a question of Fitting together

You can get semantic with the wording all you want, at the end of the day it is support. It is using MDL with technology that we don't directly support. StackOverflow already has some answers guiding people as to how to handle these situations, which is another reason to go there. You can see other questions that are related much more easily than searching out issue tracker. Then if you still don't find the help you need, you can ask a question there and people who understand the full stack you are using can help out.

**Comment by tonxxd** [comment]
I had the same problem and I solved it by calling this function componentHandler.upgradeAllRegistered();

**Comment by Clar64** [comment]
+1 It will be great if this could be fixed.

**Comment by Principe92** [comment]
I had the same problem. I finally resulted to using ng-repeat to include the checkboxes myself and use jQuery to wire up the logic of selecting all checkboxes when the master is selected and added the corresponding mdl classes.
