### ISSUE TITLE
Downgrading multiple items at once

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1144]
Just resurfaced a known issue with downgrading. It will only downgrade the *first* found component. We need to loop over and find *all* components possible and downgrade them all at once.

No time to land this properly before 1.0.1, but is a P0 for the next release of any kind.

Example: Something with `,MaterialButton,MaterialRipple` will only have `MaterialRipple` downgraded on the first pass. Leading to downgrade needing to be called again to get MaterialButton downgraded.

**Comment by sgomes** [comment]
This should now be fixed.
