### ISSUE TITLE
npm update material-design-lite   is broken

### ISSUE THREAD

**Issue by mikeymckay** [google/material-design-lite#1150]
npm update material-design-lite

 material-design-lite@1.0.0 install /var/www/coconut-mobile/_attachments/node_modules/material-design-lite
 napa mojombo/clippy

sh: 1: napa: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! material-design-lite@1.0.0 install: `napa mojombo/clippy`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the material-design-lite@1.0.0 install script.
npm ERR! This is most likely a problem with the material-design-lite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     napa mojombo/clippy
npm ERR! You can get their info via:
npm ERR!     npm owner ls material-design-lite
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-22-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "update" "material-design-lite"
npm ERR! cwd /var/www/coconut-mobile/_attachments
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/coconut-mobile/_attachments/npm-debug.log
npm ERR! not ok code 0

**Comment by Garbee** [comment]
1.0.0 has a packaging issue. You need to install 1.0.0-3 for things to work until the first patch release. Can you give that a shot?

**Comment by mikeymckay** [comment]
I think it is still broken in 1.0.0-3. If I install 1.0.0-3 from scratch and then upgrade I have the same error:


    crazy@shoshone /var/www/coconut-mobile/_attachments npm install material-design-lite --save
npm WARN package.json coconut-mobile@0.9.0 No description
npm WARN package.json coconut-mobile@0.9.0 No repository field.
npm WARN package.json coconut-mobile@0.9.0 No README data
npm WARN package.json node@0.0.0 No repository field.
material-design-lite@1.0.0-3 node_modules/material-design-lite

    crazy@shoshone /var/www/coconut-mobile/_attachments npm update material-design-lite

material-design-lite@1.0.0 install /var/www/coconut-mobile/_attachments/node_modules/material-design-lite
napa mojombo/clippy

sh: 1: napa: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! material-design-lite@1.0.0 install: `napa mojombo/clippy`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the material-design-lite@1.0.0 install script.
npm ERR! This is most likely a problem with the material-design-lite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     napa mojombo/clippy
npm ERR! You can get their info via:
npm ERR!     npm owner ls material-design-lite
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.19.0-22-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "update" "material-design-lite"
npm ERR! cwd /var/www/coconut-mobile/_attachments
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/coconut-mobile/_attachments/npm-debug.log
npm ERR! not ok code 0

**Comment by surma** [comment]
> If I install 1.0.0-3 from scratch and then upgrade I have the same error

Not sure what you mean by that. Can you try removing `node_modules`, running `npm install --save material-design-lite@1.0.0-3` and see if that works?

**Comment by Garbee** [comment]
Also, node version 0.10 is very old. With the next patch release we are not supporting it anymore. Try using nvm or some other means to get node version 0.12 and see if that makes a difference.

**Comment by surma** [comment]
> Also, node version 0.10 is very old.

Oh didn’t even see that. Yes, please try node >=0.12

**Comment by mikeymckay** [comment]
This is default node on the latest Ubuntu 15.04:

    node --version

v0.10.25

I can certainly upgrade node, but I use npm to manage dozens and dozens of
npm packages without an issue. If it is indeed a node issue, then if
someone is deploying an npm managed application on stock ubuntu (think
digital ocean, aws, coreOS) then it will fail, hence I would not recommend
dropping support for 'old' node versions.

**Comment by mikeymckay** [comment]
@surma - by installing from scratch, I mean doing exactly what you said.
(removing node_modules and then reinstalling). That works fine, the problem
is when you try and do

    npm update material-design-lite

Not only does the command fail, but it also removes the currently installed
package.

**Comment by Garbee** [comment]
Ubuntu does not factor into our support. NodeJS provides updated code and nvm allows for easy management of multiple versions, including newer ones.

**Comment by surma** [comment]
Okay, I can [reproduce](http://showterm.io/683d242e9238ce9e27b60) this locally.

All in all, this is the same issue as #859 and will be fixed with the next release scheduled for this week.
