### ISSUE TITLE
<video> element's autoplay attribute doesn't work.

### ISSUE THREAD

**Issue by uplusion23** [google/material-design-lite#1155]
When a video element is within a mdl div, such as;

```html
<div class="android-wear-section">
      <video class="landing" poster="#" autoplay loop muted>
        <source src="costarica.mp4" type="video/mp4" />
        <source src="costarica.webm" type="video/webm" />
      </video>
</div>
```

I've been able to trace it down to a JS issue with MDL. No avail on a solution though

**Comment by uplusion23** [comment]
Even using JQuery to wait until the document is ready, then appending the video does not help.

**Comment by uplusion23** [comment]
I did find a "workaround" after some attempts with JQuery. Waiting 300ms then using JS to play the video allows it to work again.

```javascript
 setTimeout(
  function() 
  {
    $("video.landing").get(0).play();
  }, 300);
```

**Comment by Garbee** [comment]
Can you provide an actual code demo of this problem via a codepen? MDL does nothing that would directly affect video playback like this. Perhaps there is something else going on in your code.

**Comment by uplusion23** [comment]
@Garbee 
http://codepen.io/uplusion23/pen/RPYLeo
Here's a quick demo. Line 288 is the video's CSS.

**Comment by Garbee** [comment]
> I've been able to trace it down to a JS issue with MDL.

So what is the JS issue you found? You are pointing out CSS that is not MDL CSS but custom CSS for that template.

**Comment by Garbee** [comment]
Looking at the codepen autoplay is working, looping is not.

**Comment by Garbee** [comment]
It is because of the layout JS resizing things. Probably chokes browsers up having it begin at one place then get reflowed into another.

**Comment by uplusion23** [comment]
It's not being choked out on any browser I've tested, and on the three machines I've tested. Invoking the play command works every time, just after the page is loaded. Seems to be something the JS does while applying all of the material attributes and classes.

**Comment by Bound3R** [comment]
@uplusion23  I spend the same to add MDL not know why, but it solved simply using
```javascript
$( window ).load(function() {
          $( '.video-element' ).get(0).play();
 });
```
I hope this help :wink:

**Comment by uplusion23** [comment]
Thanks, that works. :)

**Comment by bjfletcher** [comment]
I'm experiencing this issue too.

- It plays very briefly (about 500ms) then pauses.
- If I put the video tag outside of the MDL layout tag, I don't experience this issue.
- If I put in a `setTimeout` to `.play()` the video after 500ms then it will work, presumably after MDL somehow pauses the video.

**Comment by bjfletcher** [comment]
@Bound3R's workaround works well here.

**Comment by bjfletcher** [comment]
If anyone's interested and using Riot (or similar):

```
    const play = () => video.play();
    tag.on("mount", () => window.addEventListener("load", play));
    tag.on("unmount", () => window.removeEventListener("load", play));
```

**Comment by gplanchat** [comment]
The issue appears to be still present on Chrome 49.

It happens when I use a MDL layout, at this line :

https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L294

Here is my simplified page :

https://gist.github.com/gplanchat/3da29e50e8911f7430e9

The dynamic elements removal and re-insertion in a container seems to break autoplay and looping.

**Comment by Garbee** [comment]
It will continue to be a problem until V2 is released with a completely refactored layout setup.

**Comment by dkaatz** [comment]
Got the same issue with autoplay and loop on video and audio tags. 
I was able to fix the autoplay and looping  with following workaround:

`video.addEventListener('resize', function() {
      setTimeout(function() {
        video.play();
        setInterval(function() {
          video.currentTime = 0;
        }, 
          6680);  //add the duration of the video -20 ms here
      }, 500);   //maybe need to be higher for systems with low performance...
 });`

Regards...

**Comment by Garbee** [comment]
Listen for the layout upgrade and then play your video manually.

The work-around to this until V2 ships, don't use `autoplay` attribute and:

```javascript
  document.querySelector('.mdl-js-layout').addEventListener('mdl-componentupgraded', e => {
    if (e.target.classList.contains('.mdl-js-layout') {
      document.querySelector('video').play();
    }
  });
```

**Comment by Exac** [comment]
Can't we just add the following code to the project until v2 arrives?
    document.querySelector('.mdl-js-layout').addEventListener('mdl-componentupgraded',
            function(){
                var apvs = document.querySelectorAll('.mdl-js-layout video[autoplay]');
                [].forEach.call(apvs, function(e) {
                    e.play();
                });
            }
    );

**Comment by Garbee** [comment]
V2 layout won't affect this at all so the problem will be solved naturally. Projects need to implement this patch listener on their own for V1 as we won't be adding it into core.

Since there is no action the internal team will take here and there is a reasonable fix for developers within projects that need it, I'm closing this out to keep our open issue list as small as we can get.

Thank you.

**Comment by davidtaubmann** [comment]
@Exac , your solution worked fine once I remembered to run it on window.onload (would appreciate to mention).

@Garbee , your code seems to be missing a parenthesis and even when putting it, the solution didn't worked for me.

**Comment by Exac** [comment]
@davidtaubmann Glad it worked for you. This issue made me switch to Angular+Angular Material.

**Comment by Garbee** [comment]
My example code is just that, example code. Not a complete solution nor meant to be syntatically correct. It is just a mockup to give people the idea of the logic needed to solve the problem.  Yes, you may need to modify it for you application specifically to handle autoplaying the correct video.
