### ISSUE TITLE
Fix CONTRIBUTING.md reference for website

### ISSUE THREAD

**Issue by Frozenfire92** [google/material-design-lite#1156]
In [this section](https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md#-want-a-feature) it says to post website related issues to the Web Fundamentals repository. As I found out by the owner of that repository [here](https://github.com/google/WebFundamentals/issues/1450) that is indeed the wrong repository.

> Website related issues should be filed on the Web Fundamentals issue tracker.

My guess is this document was copied from another repo and that link not fixed

**Comment by Garbee** [comment]
Ah, that is from where we were going to be hosted under the same area. I'll just remove it real fast. Thanks for letting us know!

**Comment by Frozenfire92** [comment]
+1
