### ISSUE TITLE
Simpler maintenence for customization of colors for MDL

### ISSUE THREAD

**Issue by Frozenfire92** [google/material-design-lite#1157]
Repost of https://github.com/google/WebFundamentals/issues/1450 because of #1156 

[This customization](http://www.getmdl.io/customize/index.html) page offers a great way to change your primary and secondary color. However the only option provided is to download the whole css library with the customized colors. I believe most users (like myself) will use a package manager such as bower to maintain their libraries to the most recent versions. By adding an option to just download (or copy) the css snippet that overrides the colors will make things much more maintainable for typical projects

**Comment by Garbee** [comment]
There is no "CSS snippet" that does this. Did you mean Scss snippet?

Most users will actually just use the JS and CSS provided, package managers tend to get confused easily.

**Comment by Frozenfire92** [comment]
Originally it is scss but it does get compiled down to css.

>Most users will actually just use the JS and CSS provided, package managers tend to get confused easily.

Correct which is where I'm getting at. I use bower to get the js and css for use in my project. However if I want to customize colors either I have to download the whole css library from that customization page, and thus losing the purpose of having a package manager. Where I think it would be a better solution to at least provide the option to copy/paste the css that overwrites the primary/secondary default colors. Does this make sense?

Here is the workflow I envision

1) Have your project and use a package manager like bower to get MDL
2) Include MDL from the `bower_components` directory in your website/project
3) Be able to use [the customization page](http://www.getmdl.io/customize/index.html) to choose a color scheme
4) Get a snippet of css to include after MDL's css from bower which overrides the default primary colors (the original full "customized" library could still be downloaded here, but give the option for the css to copy as well)

**Comment by Frozenfire92** [comment]
Sorry I misinterpreted

>Most users will actually just use the JS and CSS provided, package managers tend to get confused easily.

I disagree. I think a great majority of people will use a package manager and find this use case / scenario valid and useful

**Comment by Garbee** [comment]
> Get a snippet of css to include after MDL's css from bower which overrides the default primary colors 

This is an instant no-go. This only induces poor performing output which we don't want to support. If you want to customize colors in your custom build process, you should use the Sass sources (being provided in the next release in the bower/npm packages) to build your copy.

Colors are not simple variables within CSS to change, they are tightly integrated throughout the system and this means upkeeping yet another thing in core. Way too much effort to only help poor development practices.

You can disagree all you want with how most developers build, but CDNs are in demand for a reason. I wish more would use sources and build copies with only what they need as well, but we don't always get what we want. Most developers (Bootstrap has proven this) just take what is provided in its direct CSS and JS form and move on.

**Comment by Frozenfire92** [comment]
> If you want to customize colors in your custom build process, you should use the Sass sources (being provided in the next release in the bower/npm packages) to build your copy.

Well as long as there is a solution moving forward. Any idea when that will be? I am completely ok with this solution :smile:. Where it is currently is not maintainable for anyone using a package manager to (easily) change the colors, thus my desire for this issue.

Thank you

**Comment by khooz** [comment]
Why not providing color schemes as primary_{color}.css and accent_{color}.css as separate Bower/NPM packages? It is a finite set, less than 40 packages that can be combined as 20x20 for variations. Or provide Sass files for primary and accent coloured components to generate custom colours by changing one variable per file, then built and included separately along with base MDL components?

**Comment by Garbee** [comment]
Because that is over-complicating the output we provide and the build process. And with some of the changes in V2 using css vars for colors it would make things even harder to grock.
