### ISSUE TITLE
Could mdl-cell--hide-* be decoupled from cell so we can hide any element.

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1162]
I was implementing a header and needed a button to disappear on mobile devices. I was wondering if ```mdl-cell--hide-phone``` should be changed to something like ```mdl-hide-phone``` so it could fit more use cases. The CSS behind it is ```display: none !important``` which is generic enough for wider usage.

Just wanted to open this for discussion.

**Comment by Garbee** [comment]
That is a specific part of the grid system. We don't do any "helper"
classes directly since we are not a framework. Changing names provides
little benefit and may confuse people more as to what the project provides.

If you wish, you can do an extend in a sass build pipeline to trim the name
down.

**Comment by Garbee** [comment]
PR #1159 if accepted will introduce names not tied to the cell element naming. I think this is the best we are going to get here.
