### ISSUE TITLE
Toggles should add/remove the "checked" attribute to/from the input element when clicked

### ISSUE THREAD

**Issue by lots0logs** [google/material-design-lite#1163]
Currently the input element's `checked` attribute is not updated when the toggle is clicked. Though its obviously not difficult to handle this outside of the mdl script, it shouldn't have to be.

**Comment by Drestin** [comment]
I found out this curiosity too.
Why is this issue closed ?

**Comment by Garbee** [comment]
Which component are you talking about exactly? I'd assume switch, but not entirely sure since "toggle" has many meanings.

**Comment by lots0logs** [comment]
@Drestin I closed it because I discovered that the behavior is actually consistent with the spec. The `checked` ***attribute*** is only referenced by the browser when initially loading the page. After the page has been loaded, the state of the toggle is stored in the `checked` ***property*** (not the same thing :unamused: )

**Comment by jadjoubran** [comment]
I think he was talking about the Switch toggle: http://www.getmdl.io/components/index.html#toggles-section/switch

if you want to programmatically update the switch, you need to use

```javascript
yourElement.MaterialSwitch.on()
//and
yourElement.MaterialSwitch.off();
```

Source code: https://github.com/google/material-design-lite/blob/20d325fd8b2123110c62b574b0558906e60cbb31/src/switch/switch.js#L185

**Comment by aderbas** [comment]
I'm using MDL 1.3.0 and MaterialSwitch is undefined =/

**Comment by BrowserPlugs** [comment]
Me too aderbas, MaterialSwitch  is undefined in my MDL 1.3.0 too and that is how I found this page
