### ISSUE TITLE
http://getmdl.io blocked in China

### ISSUE THREAD

**Issue by WG-C** [google/material-design-lite#1164]
http://getmdl.io blocked in China ?

**Comment by addyosmani** [comment]
Works fine here in Japan. @marcacohen do you know why the site might be getting blocked? Is it because we're on the same backend storage as other Google services that might similarly be getting blocked?

**Comment by marcacohen** [comment]
@HuaTiMeiTian Hello and thank you for the problem report. Would you be kind enough to try two other experiments for us?
1. The fully qualified domain name (http://www.getmdl.io). 
2. The URL which www.getmdl.io redirects to:  http://www.getmdl.io.storage.googleapis.com/index.html

Thanks!

**Comment by insanehong** [comment]
Works fine here in South Korea too!

**Comment by HuaTiMeiTian** [comment]
All Google services are blocked, We can not access the domain and IP，Unless the use of VPN
this is http://www.getmdl.io/：
![222](https://cloud.githubusercontent.com/assets/9836101/8820951/4ce07780-308c-11e5-8386-e6806f401ed6.png)
http://www.getmdl.io.storage.googleapis.com/index.html:(I've been on this page for 10 minutes.)
<img width="811" alt="111" src="https://cloud.githubusercontent.com/assets/9836101/8820964/5efdc09e-308c-11e5-9723-16509a97f257.png">

Please put the document on the GitHub pages. thanks

**Comment by marcacohen** [comment]
Thanks for running those tests. Are you able to reach other sites under the .io top level domain? 
Also, could you share a Chrome network trace of the failure to reach www.getmdl.io? Thanks!

**Comment by HuaTiMeiTian** [comment]
www.getmdl.io =  NO 
http://gitbook.io = YES

```
ping www.getmdl.io
PING storage.l.googleusercontent.com (173.194.72.128) 56(84) bytes of data.
^C
--- storage.l.googleusercontent.com ping statistics ---
23 packets transmitted, 0 received, 100% packet loss, time 22000ms
```

**Comment by HuaTiMeiTian** [comment]
googleusercontent.com blocked

**Comment by HuaTiMeiTian** [comment]
Sorry, the following page can not open also, My Company have VPN, some Google service and domain can be accessed, but now in the home can not visit 

http://www.getmdl.io.storage.googleapis.com/index.html 
```
PING googleapis.com (216.58.221.100): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
^C
--- googleapis.com ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss
```
return : ERR_CONNECTION_TIMED_OUT

So all Google services, domain，IP  can not be used in China

**Comment by innerpeace0** [comment]
Could getmdl.io be zipped and made available for download here?

**Comment by HuaTiMeiTian** [comment]
amazon AWS is very unstable(github use AWS storage file ), usually I download the zip file is very trouble, often download interrupt, sometimes ERR_CONNECTION_TIMED_OUT

**Comment by HereChen** [comment]
I got the same problem, but it can be reach when i use my mobile phone.

**Comment by sgomes** [comment]
MDL releases are available on GitHub which is not hosted on Google infrastructure. In addition, we have NPM packages available, which are hosted on their own infrastructure.
