### ISSUE TITLE
How to upgrade dynamically mdl-layout--fixed-tabs

### ISSUE THREAD

**Issue by gjuchault** [google/material-design-lite#1165]
Hi,

Following the layout explained at `Fixed tabs` in http://www.getmdl.io/components/index.html#layout-section/tabs, I'd like to upgrade dynamically the tabs, that I generate after an AJAX request.
The tabs are shown but nothing happen when I click on it (neither the ripple effect, neither the tab change).

I see that classic tabs are upgradable with
```js
componentHandler.upgradeElement(domElement, 'MaterialTabs');
```

But there is no `mdl-tabs-js` (basing on https://github.com/google/material-design-lite/blob/master/src/tabs/tabs.js#L148)

So what I saw in https://github.com/google/material-design-lite/issues/871#issuecomment-119592296 is not usable I think.

What's the solution here ?

**Comment by surma** [comment]
I whipped up a codepen for you. No `upgradeElement` required to make this work:

http://codepen.io/anon/pen/bdxMKV

I’ll close this for now, as this isn’t an issue with MDL. If this is NOT helping, I’d recommend heading over to StackOverflow using the `material-design-lite` tag.

**Comment by gjuchault** [comment]
Wrap your code in a `setTimeout(..yourcode.., 1500).
Tabs will not work :)

**Comment by Garbee** [comment]
Yea it won't because the script adding the links is going to run before document.load which is when MDL JS fires.

Currently, there is no way to dynamically add tabs to the layout. What exactly is the use-case?

**Comment by gjuchault** [comment]
There is a workaround that I noted in the first post.
Upagrading the element may work with your example. But I'm using the example in the layout page of the docs, which has special tabs I think because the structure is not the same.

Use case : I'm using the layout, and the tabs are categories based on what is returned by an AJAX request. So I get the ajax result, do some maths, and I use vuejs to render so I have basically (examples in angular) a ng-repeat on the links, and a ng-show in the tab container to hide the tabs while the AJAX request is loading

**Comment by surma** [comment]
Ah, I thought the inline script would run after. Anyways, here’s a version working with `setTimeout`. It’s a bit hacky, so I agree we should have a proper API for this.

http://codepen.io/anon/pen/bdxMKV

**Comment by gjuchault** [comment]
Ok, your example is working nicely.
Can you explain to me how to achieve the same thing with that structure :

```html
<!-- Simple header with fixed tabs. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header
            mdl-layout--fixed-tabs">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Title</span>
    </div>
    <!-- Tabs -->
    <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
      <a href="#fixed-tab-1" class="mdl-layout__tab is-active">Tab 1</a>
      <a href="#fixed-tab-2" class="mdl-layout__tab">Tab 2</a>
      <a href="#fixed-tab-3" class="mdl-layout__tab">Tab 3</a>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title">Title</span>
  </div>
  <main class="mdl-layout__content">
    <section class="mdl-layout__tab-panel is-active" id="fixed-tab-1">
      <div class="page-content"><!-- Your content goes here --></div>
    </section>
    <section class="mdl-layout__tab-panel" id="fixed-tab-2">
      <div class="page-content"><!-- Your content goes here --></div>
    </section>
    <section class="mdl-layout__tab-panel" id="fixed-tab-3">
      <div class="page-content"><!-- Your content goes here --></div>
    </section>
  </main>
</div>
```

Which comes from here : http://www.getmdl.io/components/index.html#layout-section/layout

**Comment by Garbee** [comment]
Codepen actually isn't working since tabs isn't defined, at least for me.

@gjuchault Please use StackOverflow for that, it is support.

Considering the project isn't targeting highly dynamic web apps, I don't think we need to provide an API for this. People can use our styling and create their own JS components to handle more dynamic logic. Or use something like Polymer.

**Comment by gjuchault** [comment]
Well; this isn't a support question, this is a API matter : you provide useful functions (http://www.getmdl.io/started/index.html : « Use MDL on dynamic websites ») which works on pretty much anything but the layout tabs.

And well, I won't switch everything I've done this far to Polymer because of one special element is (probably) missing in the JS API..

**Comment by surma** [comment]
@Garbee Ugh, accidentally deleted a line -.- Fix'd now

@gjuchault If you get the idea from my codepen, I encourage you to look at the [tab section of layout](https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L328) and just do the same initialization manually. It’s pretty straight forward.

**Comment by gjuchault** [comment]
Lining here what I'm working on :
http://codepen.io/anon/pen/BNOVvw

So far, there is a MaterialLayout component but not a MaterialTabs so I couldn't make your script work @surma : I don't have any context to give (`tabs.MaterialTabs`). Moreover, the material layout element (I put it in window so I could search with devtools) has a tabBar_ (`l.MaterialLayout.tabBar_`) but this element has no MaterialTabs.

Maybe by rendering again the MaterialLayout; the tabs could be working but, `init()` throws.
Too bad, because the code I want to call is here : https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L329

But I see at https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L391 that using MaterialLayoutTab, it could be working.

After some codepen tries this work : http://codepen.io/anon/pen/BNOVvw

What do you think of it ?

**Comment by surma** [comment]
@gjuchault Your solution is correct. You just forgot to adjust the IDs of the `.mdl-layout__tab-panel` ;)

**Comment by gjuchault** [comment]
Well thanks.
I do believe there should be a part on the MDL website to explain how to manage, constructors, some doc on componentHandler, etc.

**Comment by gjuchault** [comment]
Hi,

I'm reopening this : since this commit https://github.com/google/material-design-lite/commit/d45ab8000c25f6ab5f160d8d92606552d3740781, MaterialLayoutTab is not exposed, so the solution before does not work anymore. Is there a way to pass around that ?

**Comment by stefanhaustein** [comment]
Just ran into this problem. The initial codepen suggestion doesn't really work at all -- the highlight is not removed from previous tabs for the linked version 1.0.0 (I suppose because the tab list used for clearing doesn't get updated with this approach). In more recent versions (1.2.1), MaterialTab doesn't seem to be exposed at all any longer.

After looking at the source code, I am using the following workaround now:

     var ihtml = tabs.firstElementChild.innerHTML;
     tabs.firstElementChild.innerHTML = ihtml;     // Kill old listeners
     container.MaterialTabs.initTabs_();

However, that seems a bit fragile, as it only works because initTabs_ currently isn't minified properly.

Concerning "the project isn't targeting highly dynamic web apps": you really should add a big warning about this to the section "Use MDL on dynamic websites" on the "getting started" page.

BTW: Won't the querySelectorAll calls in initTabs_() match for nested tab components -- I suppose they are not supported? Wouldn't it be safer to access the children directly -- or to add a parent filter?

**Comment by rianby64** [comment]
The presence of ```setTimeout``` is the clue to use in some way a ```Promise``` in order to avoid a big value for timeout. It's just an idea...

@surma Thanks a million for the codepen example. Was very useful to me :smile:
