### ISSUE TITLE
How do I capture a Scroll event?

### ISSUE THREAD

**Issue by Errvald** [google/material-design-lite#1166]
There must be a conflict when I try this because no logs are showing:
``window.addEventListener('scroll', function() {
    console.log('test');
});``

**Comment by fatihkahveci** [comment]
This because your mdl-layout__content scrolling this div not on your window.

**Comment by Errvald** [comment]
How do I capture a scroll event then, listening to ``mdl-layout__content`` doesn't work.

**Comment by fatihkahveci** [comment]
```javascript
document.getElementById('container').addEventListener('scroll',function(){console.log('wow scroll');});
}
```

This will be work.

**Comment by Errvald** [comment]
Adding the ``container`` id to ``.mdl-layout__content``? Still doesn't capture the scroll event.

**Comment by fatihkahveci** [comment]
I'm already check this my own project it work :/. Can you give me sample jsfidle or codepen so we can test?

**Comment by Garbee** [comment]
Catch it on `.mdl-layout`. To test, open up Chrome DevTools console and run `monitorEvents($('.mdl-layout'), 'scroll')`

**Comment by Garbee** [comment]
Closing this out since it is more support than a core issue. Further discussion of the problem should be addressed on StackOverflow.

**Comment by kuralexa** [comment]
I have the same problem. I found that if exclude the "material.min.js" from the page - everything work correctly and we can to capture the scroll event. The same positive result we can get  if exclude the "mdl-js-layout" class from the outer "div". But it is not a decision of course.
Did you solve it?  How? Thanks in advance for  your reply

**Comment by Garbee** [comment]
@kuralexa It has already been answered. This is **not** a support forum. If you need help, use StackOverflow.

**Comment by Errvald** [comment]
@kuralexa here's a working jsfiddle for your situation: https://jsfiddle.net/sygwvhjc
