### ISSUE TITLE
Highlight changes to the source code on examples on the documentation page.

### ISSUE THREAD

**Issue by biwin** [google/material-design-lite#1169]
On the basic section of the layout documentation, http://www.getmdl.io/components/index.html#layout-section trying out while reading, find so difficult to figure out what classes are added (examples), may be due to the 'weird'  dashed classes (and most users come from bootstrap or foundation world) would be better if highlight the changes added to the source on each step.

**Comment by Garbee** [comment]
I think we can improve the text for each step. Highlighting the modifications is more trouble than it is worth.

**Comment by sgomes** [comment]
Closing this issue, as we likely won't have the opportunity to make further improvements to getmdl.io.
