### ISSUE TITLE
an mdl class to expand the grid to the full width?

### ISSUE THREAD

**Issue by biwin** [google/material-design-lite#1172]
Does there exist some utility class that expands the grid to the full width? 
while stacking the columns up a line as here, http://jsfiddle.net/biwin007/o1s4783q/10/, at larger widths (desktop) the grid shrinks to the left, Question on stackoverflow (http://stackoverflow.com/questions/31566782/how-do-i-adjust-the-grid-gutter-on-mdl-as-that-of-foundation-or-bootstrap) suggests this solution http://jsfiddle.net/biwin007/o1s4783q/11/. Do there exist a class to align the grid the same way? If not, consider adding one.

**Comment by surma** [comment]
I don’t agree with the answer on SO. Add `mdl-grid--no-spacing` to the `mdl-grid` container and you should be good to go.

**Comment by biwin** [comment]
Couldn't find anything about this class `mdl-grid--no-spacing` on the documentation page. (http://www.getmdl.io/components/#layout-section/grid)

**Comment by Garbee** [comment]
Just added an entry for the configuration option via commit 6c6f1346b0cfb2f23b541afb7ac8c81c7e4bfa7c.

**Comment by surma** [comment]
@biwin That must have slipped through somehow. Sorry about that.

**Comment by biwin** [comment]
@Garbee why couldn't you arrange the class such a way that grid's classes first then cell's classes? that would feel some stacked way. Good job. Thank you.

**Comment by biwin** [comment]
@surma Its okay. cheers.

**Comment by Garbee** [comment]
I just tossed it in to be there for now. We can re-organize stuff later.

I was thinking, base classes for the primary parts, then modifiers on those, then the element-level classes, then those modifiers as far as how the ordering should go. Really we don't have some official ordering structure, but we should find one in the future once we go over everything and make sure they are BEM compliant.

**Comment by biwin** [comment]
@Garbee well okay! Cheers. Thanks
