### ISSUE TITLE
support nested tabs

### ISSUE THREAD

**Issue by flying-sheep** [google/material-design-lite#1173]
when i create a tabbar in a tab panel, selecting an inner tab closes the outer one.

to fix this, all `.mdl_tabs` elements should be excluded from the `querySelectorAll` call in tabs.js.

```js
var allTabs = this.element_.querySelectorAll('.' + this.CssClasses_.TAB_CLASS);
var excludedTabs = new Set(this.element_.querySelectorAll('.mdl-tabs .' + this.CssClasses_.TAB_CLASS));
this.tabs_ = Array.filter.call(allTabs, function(tab) { !excludedTabs.has(tab) })
```

[or](https://github.com/ericclemmons/unique-selector)

```js
var noSub = ':not(' + unique(this.element_) + ' .mdl-tabs *)';
this.tabs_ = this.element_.querySelectorAll('.' + this.CssClasses_.TAB_CLASS + noSub);
```

**Comment by surma** [comment]
I don’t think nested tabs are something the MD spec accounts for. They are widely considered bad UX (as are any kind of nesting state). Closing this for now.

**Comment by flying-sheep** [comment]
i have an installation guide.

i use in-content tabs to allow the user to choose his/her setup.

the first choice is binary/source/development install. if the user chooses source installation, after a common prelude he’s presented with an OS choice which will show him install instructions for a certain dependency.

what else should i use here? if it’s bad UX, you’ll have to prove how to do it better :wink:

**Comment by Garbee** [comment]
We don't need to prove anything. StackOverflow should be able to help finding a better UX. This issue tracker is not here for support.

**Comment by flying-sheep** [comment]
did the winking smiley not arrive on your side?

would you accept a PR fixing this? it’s really not hard and as mentioned i have a valid use case here.

**Comment by Garbee** [comment]
We won't accept a PR for something we believe induces bad UX. You are free to maintain your own implementation and use that instead if you feel it is vital.

**Comment by flying-sheep** [comment]
could you point me to an explaination why it is “widely considered bad UX”?

saying so does’t make it so

**Comment by surma** [comment]
There is no golden rule for tabs within tabs. [There *is* use-cases](http://ux.stackexchange.com/questions/5136/is-there-evidence-to-suggest-that-designing-tabs-within-tabs-creates-a-bad-user) where they are actually valid (but they need to be carefully crafted), however they are mostly abused where this leads to horrible UIs.

In any case, the argument here is: The MD spec doesn’t provide any guidance for nested tabs (and I don’t think I have ever seen any in a Google app – feel to prove me wrong here).

**Comment by Garbee** [comment]
This is a part of where the **opinionated** part of MDL comes into play as well. We need to make decisions so sites using the project are as consistent in functionality as they can be while still expressing their unique style.

We have the opinion that nested tabs are generally bad. You believe you have a use-case where they are exceptionally useful. That's fine. We are deciding to not support this in core. Nothing is stopping you from maintaining your own JS code that allows for this. MDL was constructed very well to allow for this.

**Comment by flying-sheep** [comment]
http://www.getmdl.io/ has nested tabs: the toplevel tabs and the [layout/tabs](http://www.getmdl.io/components/index.html#layout-section/tabs) examples.

they are just implemented as link, but if they wouldn’t, they’d be subject to the same bug.

**Comment by Garbee** [comment]
Ugh, why do people keep calling those tabs. That is a standard navigation menu.

**Comment by flying-sheep** [comment]
because they use the same design as tabs, and save the same purpose (replacing the whole page content except from the header)

there’s no difference between `mdl-layout__tab-bar` and `mdl-navigation` other than implementation: one is mapped to a URL /directory and the other to the #fragment, one downloads only one page/tab, the other all pages/tabs that can be switched.

with a proper implementation, you could even make a tabbar load the tab via XMLHTTPRequest and update the URL via pushState, which would completely remove any difference.

**Comment by flying-sheep** [comment]
but that’s beside the point. nested state is what you do as well:

http://www.getmdl.io/components#layout-section

you just chose to represent the second layer as components instead of tabs.

i have it like this right now:

![easy1](https://cloud.githubusercontent.com/assets/291575/8831155/c2674cf4-30a0-11e5-99a0-8af263937f99.png)

it may be not the best UX, but using components vs tabs strikes me as a aesthetic choice

**Comment by surma** [comment]
I’ll bring this up with the MD team to get their input on this.

**Comment by Garbee** [comment]
Where in that page do we nest tabs? Other than the *examples* to show how the components should look.

**Comment by flying-sheep** [comment]
> I’ll bring this up with the MD team to get their input on this.

great, thanks!

---

all in all i’d be happy to have some other form of hierarchical document, where you can switch out parts to get to the ones relevant to you.

1. everyone installs the requirements: bla bla

2. do you want to
	
	1. install binary? do this: bla
	2. install from source:

		1. Do this if you have windows: bla
		2. Do this if you have osx: bla
		3. ...

	3. install dev version? do this: bla

3. now start via …

i simply don’t want to present users with the irrelevant parts.

---

and this is basically what navigation is for as well: allow to switch to the relevant part. no difference from tabs. so i don’t get the artificial division into “one layer of navigation” → “one layer of tabs”

**Comment by surma** [comment]
Apparently, I overlooked it, but the MD spec actually says that [nested tabs are a no-go]
(https://www.google.co.uk/design/spec/components/tabs.html#tabs-usage).

For multiple levels of navigation, see [this section](https://www.google.co.uk/design/spec/patterns/navigation.html#navigation-two-levels).

**Comment by flying-sheep** [comment]
thanks, that section is very helpful!

**Comment by PeterWolter** [comment]
Hi,

you can use this code: [https://daschmi.de/verschachtelte-tabs-mit-material-design-light/](https://daschmi.de/verschachtelte-tabs-mit-material-design-light/)

**Comment by flying-sheep** [comment]
thanks, but i already have a working solution. also sadly yours doesn’t work. selecting a second-level tab deselects first-level tabs

**Comment by PeterWolter** [comment]
Here is a working example:

[https://jsfiddle.net/j44mm43k/](url)

**Comment by flying-sheep** [comment]
no, it’s not. clicking on “Tab 1.1” or  “Tab 1.2” results in only the top tabs being visible, both deselected.

**Comment by kpost** [comment]
I know this thread is old, but I just wanted to add an observation. Sure the guidelines say nested tabs are bad, but since MDL doesn't offer an alternative, I'm forced to use tabs as the bottom navigation bar, which is a valid component according to the guidelines (https://material.io/guidelines/components/bottom-navigation.html). So from a UI perspective there are no nested tabs in my app. 

As some people pointed out, there are valid use cases out there for nested tabs. In the end the user is responsible for correctly implementing material design. It seems to me the creators of the MDL framework are not.

So +1 for me. :)

**Comment by Danbardo** [comment]
@PeterWolter thank you!
