### ISSUE TITLE
upgradeElement and upgradeDom has no effect on dynamically-inserted Tab Bar

### ISSUE THREAD

**Issue by dstaley** [google/material-design-lite#1175]
When adding a tab bar dynamically, it breaks the layout of the header bar.
![Broken tab bar layout](http://i.imgur.com/pD6NZEe.png)

However, even after calling `upgradeElement` on the tab bar and `upgradeDom`, the tab bar has no ripple effect and the blank space below the tabs is still there. From the documentation, I was under the impression that something like `upgradeDom` should properly render the tab bar and give it the proper functionality.

I am using version 1.0.0. This is occurring on Chrome 44 and Safari 8 on OS X 10.10.4.

I've made a small demo [here](http://jsbin.com/nelazeqiti/edit?html,js,output). When you click "Add Tab Bar", the tabs are added to the header, which causes the funky layout. "Upgrade Tab Bar" calls `upgradeElement` on the element with the `mdl-tabs` class. This seems to have no effect. "Upgrade Dom" calls `upgradeDom` which should properly upgrade all elements in the DOM. It also has no effect.

Both `upgradeElement` and `upgradeDom` *seem* to do what they're supposed to, in that the elements now have the `is-upgraded` class and the `data-upgraded=",MaterialTabs"` attribute. However, they still don't have the ripple effect, and the blank space is still below them.

**Comment by surma** [comment]
At least for now, MDL is aimed at *static* content-heavy websites. So dynamically adding tabs is definitely not a first-class citizen in terms of support. So I’ll close this.

However, two things come to mind:

* I feel like the discussion in #1165 might be of interest to you
* Try downgrading the entire tab bar before you run `upgradeElement`

**Comment by innerpeace0** [comment]
> At least for now, MDL is aimed at static content-heavy websites.

@surma, This comment, along with some of the issues I've seen posted related to using MDL with AngularJS, leads me to ask something I haven't seen specifically addressed yet. 

I'm planning on using AngjuarJS to redo some SPA's (once I finish reworking my content). Before MDL came out, I was planning on using angular-material. However, even though it's much newer, MDL seems like it's getting more development attention and is already more mature.

So, my question (and I doubt I'm the only one who'd be interested in the answer) is: would MDL or angular-material be the better way to use MD on SPA's using AngularJS?

**Comment by dstaley** [comment]
@surma Thanks for the insight! I can definitely understand your point.

That being said, I feel that dismissing the web app use case is a pretty egregious stance to take, especially considering the trend of client-side web applications. I can understand not having things like the ripple effect or other minor annoyances, but important elements like the tab bar and layouts like the fixed header and drawer *just don't work* without being paired with the Javascript.

I can understand your current stance, and I get that at the moment dynamic web apps aren't a first-class citizen, but I strongly encourage you to either rethink this stance and accept issues that target this use case, or rework elements to have at least basic functionality without being upgraded.

I absolutely love the ideas behind MDL, and I was incredibly excited to begin implementing it in one of my apps. I actually got a significant amount of work done before running into this issue. However, because the web app use case isn't supported, and there seems to be no effort to support it, I've had to rethink my decision to use it. I sincerely look forward to the day where this is no longer the case.

**Comment by surma** [comment]
I never meant to imply that SPAs are *completely* off the table. Explicitly targeting static content web pages simplifies reasoning about new features and allows us to move forward quickly with development; something that we have grown to appreciate. For now, our focus lies on MD specification compliance, cross-browser functionality and completeness (in that order, I guess). The fact the we have a downgrade method in our component handler shows, that we have been thinking about dynamic content as well, just not to the same extent.

There’s a lot of work to be done, but once we have fulfilled our goals sufficiently, there’s a good chance we’ll promote SPAs to first-class citizens. But that’s something the probably won’t (and can’t) happen before v2. 

Personally, I think you might be better of using Angular Material, if you are using Angular.

**Comment by douglassouza** [comment]
Eu estava tendo esse problema de renderização, mais para criação de elementos dinamicamente que utiliza o javascript do MDL (ex: menu) ele não era renderizado corretamente. Ai criei uma solução para executar o componentHandler.upgradeDom() apenas quando for adicionado um novo elemento:

    var app = angular.module('app');
    app.run(function () {
        var mdlUpgradeDom = false;
        setInterval(function() {
          if (mdlUpgradeDom) {
            componentHandler.upgradeDom();
            mdlUpgradeDom = false;
          }
        }, 200);

        var observer = new MutationObserver(function () {
          mdlUpgradeDom = true;
        });
        observer.observe(document.body, {
            childList: true,
            subtree: true
        });
        /* support <= IE 10
        angular.element(document).bind('DOMNodeInserted', function(e) {
            mdlUpgradeDom = true;
        });
        */
    });

**Comment by surma** [comment]
Judging from the accents, this is Portuguese 🇵🇹. 

@douglassouza Please try to comment in English, as you are making a possible solution unavailable to people who don’t speak Portuguese.
