### ISSUE TITLE
Textarea on focus misalignment underline

### ISSUE THREAD

**Issue by jdepypere** [google/material-design-lite#1178]
The custom css theme builder file that gets downloaded is different from the hosted file. At first sight no issues, but there is an alignment issue in the textarea:

![wrong_alignment](https://cloud.githubusercontent.com/assets/3522063/8837730/1dbc3232-30c8-11e5-8639-9bc8b4c877be.PNG)

This only happens with the downloaded theme (I've tried with multiple), but it doesn't happen with the css hosted on the googleapis CDN. [Here is an example of the textarea misalignment](http://codepen.io/anon/pen/aOaPdy).

**Comment by surma** [comment]
We are pushing 1.0.1 this week (probably today). I am confident it will resolve this issue. I will close this for now, but feel free to re-open if the issue should not disappear.

**Comment by jdepypere** [comment]
Good for me. I did try using the current 1.0.1 commit today and the issue on the textarea persisted (using the `material.min.css` at least), but I guess more changes will be made before the official push.

**Comment by Garbee** [comment]
Well, the current site isn't serving the new zips. I think that is the last piece we are waiting on.

If the issue persists when you are cloning directly, then please provide a codepen with the full HTML markup that reproduces the problem please.

**Comment by jdepypere** [comment]
It seems it has persisted. Downloading the latest MDL from [http://www.getmdl.io/started/index.html#download](http://www.getmdl.io/started/index.html#download) I get the misalignment. Also on the [components page for textfields](http://www.getmdl.io/components/index.html#textfields-section) the textarea underline is misaligned:

![textarea_misalignment](https://cloud.githubusercontent.com/assets/3522063/8869460/38cb901e-31e4-11e5-90ad-bcf03a5b2b54.PNG)
