### ISSUE TITLE
Dynamic component construction in documentation is broken

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#1180]
The sample in the documentation fails:

```
Uncaught Unable to find a registered component for the given class.
```

http://codepen.io/anon/pen/WvgLLx

**Comment by tleunen** [comment]
It's because you're trying to upgrade an element that is not in the DOM.

**Comment by jimbojetlag** [comment]
You're right. Upgrade element should be called at the end. The documentation needs a tiny correction.

**Comment by Garbee** [comment]
It is because the ripple effect is there which creates a container element. The example is 100% correct since it only use the button js class. This is being addressed with better dev documentation for understanding how the component handler works and how the components themselves work.

**Comment by jimbojetlag** [comment]
@Garbee removing `mdl-js-ripple-effect`:

```javascript
button.className = 'mdl-button mdl-js-button';
```

still gives the same error.

**Comment by tleunen** [comment]
This is because in `1.0` you also have to specify which class you want to upgrade.
`upgradeElement(element, 'MaterialButton')`. It has been changed in the latest master version.

**Comment by tleunen** [comment]
This reflects another problem though. The doc should always be the latest available stable version, not the master.

**Comment by jimbojetlag** [comment]
I thought the docs on getmdl.io are corresponded to the latest release, not unstable version.

**Comment by innerpeace0** [comment]
On most projects, there's often a time lag between the versions and the docs. On fast moving projects like this, it can be expected.

**Comment by surma** [comment]
@jimbojetlag I agree. In this case, we just consciously updated the docs (i.e. the website) ahead of time because we wanted to get some other documentation and wording fixed out ASAP.
