### ISSUE TITLE
Avoid "dataset" in dom data getter and setter

### ISSUE THREAD

**Issue by mattsahr** [google/material-design-lite#1187]
Internet Explorer 10 and below can't use "dataset" to access data on a DOM element.  Here's a fix for the `mdlComponentHandler.js` file.

__ORIGINAL__
```javascript
var upgrades = component.element_.dataset.upgraded.split(',');
var componentPlace = upgrades.indexOf(
    component[componentConfigProperty_].classAsString);
upgrades.splice(componentPlace, 1);
component.element_.dataset.upgraded = upgrades.join(',');
```

__UPDATED__
```javascript
var upgrades = component.element_.getAttribute("data-upgraded").split(',');
var componentPlace = upgrades.indexOf(
    component[componentConfigProperty_].classAsString);
upgrades.splice(componentPlace, 1);
component.element_.setAttribute("data-upgraded", upgrades.join(','));
```

**Comment by surma** [comment]
Confirmed. [IE10 does not support `dataset`](http://caniuse.com/#search=dataset).

**Comment by Garbee** [comment]
Whoops, we also have problems in the component handler then... thanks for pointing this out.

**Comment by Garbee** [comment]
Oh, I think Surma may have mis-tagged this... I have  patch for the problem in with PR #1190.

**Comment by surma** [comment]
My bad. Brain lag.
