### ISSUE TITLE
Buggy spinner animation on mobile device

### ISSUE THREAD

**Issue by nodegin** [google/material-design-lite#1188]
Mine is running on an Android 4.4.2 phone with mobile Chrome

The spinner animation is buggy, will produce a little stop after rotating

But the material spinner used in Google image search does not occurs this problem

**Comment by sgomes** [comment]
Hi @nodegin, thanks for the bug report!

I'm having trouble reproducing this issue, so I'm assuming there's something hardware-specific going on there. Any chance you could share your Chrome version and device specs (processor, RAM, etc.)?

Also, could you test this page and see if the spinners there have the same issue? https://elements.polymer-project.org/elements/paper-spinner?view=demo:demo/index.html

**Comment by nodegin** [comment]
I made a recording, my phone is Sharp Aquos Crystal 305sh

https://www.dropbox.com/s/ez2jixcl2hwrnyo/bug2.mp4

If I toggle it the animation will ran normally

**Comment by sgomes** [comment]
Sorry, can't reproduce the issue :-/
