### ISSUE TITLE
Remove unused components from css and js

### ISSUE THREAD

**Issue by raunaqrox** [google/material-design-lite#1189]
I want to use only parts of the library like the input and button, how do I customize it? My app has memory constraint!

**Comment by surma** [comment]
This is not officially supported yet, but it certainly is on the roadmap. So I’m closing this for now.

Unofficially, you can clone the repo and modify [material-design-lite.scss](https://github.com/google/material-design-lite/blob/060a4b016a17fe08630be4f40f26c9f5eec28bf0/src/material-design-lite.scss) to strip out the things you don’t need.
