### ISSUE TITLE
Tooling to help avoid browser-specific issues

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1191]
As we add new things and refactor old code, we need to be sure that we are still adhearing to our browser support. This shows in issue #1187 which brought up dataset was being used, which IE10 doesn't support.

Is there any kind of tooling we could put in place to check for things like this and error out if they are getting used?

**Comment by traviskaufman** [comment]
Closing; we can address this for v2 in either #4464 or #4465 . We could also spin off a new issue to perform image diffing or the like, which could come after the initial setup.

**Comment by Garbee** [comment]
Yah, eslint is what we're on now so this is all good. Just needed closing. Thanks.
