### ISSUE TITLE
mdl-layout documentation and examples need clarification (breaks links otherwise)

### ISSUE THREAD

**Issue by sejr** [google/material-design-lite#1193]
http://www.getmdl.io/components/index.html#layout-section/layout

I tried to implement this on my site, which is powered by Angular and ngView. I added the transparent layout to my index.html, before the content from my Angular views. All buttons, links, etc, were unusable, except for the link to open up the mdl-layout drawer.

I feel like this may be because my code wasn't encapsulated within:

```
<main class="mdl-layout__content">
</main>
```

However, I didn't test to see if that was the case. Either way, the sample code on the website I shared above should be modified to indicate that your content is supposed to go in there. I will submit a pull request for that, as I think it is counter-intuitive to have to scroll all the way to the bottom to use the sample code.

On that note, perhaps these examples should be collapsed upon page load, and the actual information regarding how to use these components should be given higher priority.

**Comment by Garbee** [comment]
The element with the class is shown in each example snippet. The element being necessary is also clearly stated in step 11 of usage plus the configuration table shows it as required.

What exactly should be improved?

**Comment by cliffordp** [comment]
I agree the Layout documentation is long and isn't obvious unless you know to look for the Configuration Options section at the bottom of each component. This page has 4 components one right after the other so each component's information blends into the next. I'd recommend adding additional sub-headings/links right to each component's Configuration Options or Examples or Basic Use or whatever... just something at the very top of the page to indicate there's more than just code examples on this page.

But, yes, the required `<main>` is clearly documented if you figure out how to get to the actual spec/documentation.

**Comment by Garbee** [comment]
`<main>` actually isn't a requirement, just something with the `.mdl-layout__content` class. Unless I'm missing something.

**Comment by cliffordp** [comment]
Similar discussion at https://github.com/google/material-design-lite/issues/1381#issuecomment-130609508
