### ISSUE TITLE
iOS off-screen rendering

### ISSUE THREAD

**Issue by PatrickOgilvie** [google/material-design-lite#1194]
Hi guys, I have implemented a table using MDL. In 1.0.0 this was subject to a jarring scroll on iOS devices. The changes recommended in Issue #730, and since included in 1.0.1 have indeed fixed that problem, scrolling down the page works as expected. However since using the 1.0.1 update this fix appears to cause some strange behaviour. Using a table full of dummy data I can reproduce this effect like this:

This image shows a table that carries on below the break. Everything here appears as normal.
![onload](https://cloud.githubusercontent.com/assets/10631117/8864826/bad2b542-319e-11e5-98f5-89319b00570f.jpg)

Scrolling down reveals that whilst the table rows are there, the content within them cannot be seen.
![scrolled](https://cloud.githubusercontent.com/assets/10631117/8864827/bad771cc-319e-11e5-97df-ef5aca7ba53d.jpg)

Finally, this image show what happens when I rotate the screen. The content within the rows that was missing appears.
![rotated](https://cloud.githubusercontent.com/assets/10631117/8864825/bad256f6-319e-11e5-914a-52f374e5a68a.jpg)

I haven't changed the table at all since updating to 1.0.1, so it must be the update that has caused this behaviour. I cannot say for sure that it was the updated lines in #730, but from the short amount of time I spent testing im 90% certain this is where the change in behaviour occurred. I have tried this on both iPhone and iPad using Safari. I will look into iOS Chrome asap. I also can't yet say whether this is specific to just tables as I haven't tried anything else.

**Comment by PatrickOgilvie** [comment]
I have built essentially the same thing in codepen: http://codepen.io/anon/pen/VLEvJy - Unfortunately the same issue hasn't quite been replicated. On the iPad (iOS8), scrolling the codepen does cause a flickering effect that doesn't show up on my android phone, nor my desktop pc.

**Comment by PatrickOgilvie** [comment]
Ok I think I have a fix. Using this article: 

http://cantina.co/thought_leadership/ios-5-native-scrolling-grins-and-gothcas/ 

and applying '-webkit-transform: translate3d(0,0,0);' to .mdl-data-table the problem seems to be fixed. This SO (http://stackoverflow.com/questions/9807620/ipad-safari-scrolling-causes-html-elements-to-disappear-and-reappear-with-a-dela) discusses the same thing with reference to '-webkit-overflow-scrolling: touch' (one of the additions in 1.0.1) causing problems. Applying the transform to the mdl-layout doesn't seem to work, only by applying it to the content that is off screen does it fix my issue.

I've submitted a pull request, but it's probably best you take a look at everything to make sure I'm not causing critical meltdowns elsewhere with this fix.

**Comment by surma** [comment]
LGTM. iOS devices and browsers seem to look fine as do browsers :) 

Waiting for @sgomes to ACK'n'merge

**Comment by sgomes** [comment]
I'd prefer the change to be limited in scope as I'm a bit wary of side effects on other browsers, but after running some tests there don't seem to be any issues. Happy to merge whenever @PatrickOgilvie thinks it's ready, thanks again!
