### ISSUE TITLE
Tooltip: impossible to click on icon when using tooltip

### ISSUE THREAD

**Issue by andkulakov** [google/material-design-lite#1196]
https://github.com/google/material-design-lite/blob/master/src/tooltip/tooltip.js (line 117)
```javascript
this.forElement_.addEventListener('click', this.boundMouseEnterHandler, false);
```
this event listener override event listener on icon, so it's impossible to click and therefore useless.
Code example:
```html
<i class="material-icons" id="remove">remove</i>
<div class="mdl-tooltip" for="remove">Remove</div>
```

**Comment by tschiela** [comment]
As far as i know event listeners dont get overridden. The source of the problem must be something other. Do you have a running code example?

**Comment by andkulakov** [comment]
I'm using jQuery (2.1.4)
```javascript
$(document).ready(function(){
    $(document).on('click', '.remove', function() {
        console.log('removed');
    });
});
```
Doesn't work
```html
<i class="material-icons" id="remove">remove</i>
<div class="mdl-tooltip" for="remove">Remove</div>
```

Works
```html
<i class="material-icons" id="remove">remove</i>
<!--div class="mdl-tooltip" for="remove">Remove</div-->
```

**Comment by tschiela** [comment]
Do you tried to bind the event directly on the element and not waiting for the event bubbling up to the document? Maybe there is an event.stopPropagation() between and so you never get the event?

```javascript
$(document).ready(function(){
    $(#remove).on('click', function() {
        console.log('removed');
    });
});
```

**Comment by andkulakov** [comment]
Thanks tschiela, it works. I didn't think about `event.stopPropagation();`

**Comment by tschiela** [comment]
you are welcome!
