### ISSUE TITLE
Responsive break points issues

### ISSUE THREAD

**Issue by nobitakun** [google/material-design-lite#1197]
Hi. I try to resize browser to smaller and i aware that some break points in responsive not work as expected.

Eg: width = 800px;

**Comment by SnaKKo** [comment]
I don't know if it's the same bug but i try anyway: if you check the "dashboard template" and you try to resize the browser you will see the bug.

![schermata del 2015-07-24 11 15 36](https://cloud.githubusercontent.com/assets/4040872/8871418/598ae38e-31f5-11e5-9fe6-889b03349a30.png)

**Comment by mspl13** [comment]
Duplicate of #1185.

**Comment by nobitakun** [comment]
yep! It is.

**Comment by nobitakun** [comment]
Hi @surma  does it fixed?

**Comment by mspl13** [comment]
Nope, it is not fixed but this is a duplicate and duplicates usually get closed. Also the an explanation from  @surma to the issue in the original [issue](https://github.com/google/material-design-lite/issues/1185#issuecomment-124117470).
