### ISSUE TITLE
Icon styling

### ISSUE THREAD

**Issue by DJWassink** [google/material-design-lite#1198]
Correct me if I am wrong but currently it seems that there is not way to edit the font-sizing/color without writing css yourself.

On the material-design-icon page there actually is a little snippet which follows the spec and tells developers how to write the proper css for this. Isn't it a great idea to integrate this in mdl itself?

See: http://google.github.io/material-design-icons/#styling-icons-in-material-design

**Comment by Garbee** [comment]
Currently there are some color classes provided so you can just use those. However, these do cause bloat in the output and will be removed from the *default* build with the next major release. At that time you would need to do your own compile to get them back.

You can see the full list of these within the [palette.scss](https://github.com/google/material-design-lite/blob/master/src/palette/_palette.scss#L22-2260) file.
