### ISSUE TITLE
Textfield floating label type number issue

### ISSUE THREAD

**Issue by jdepypere** [google/material-design-lite#1200]
I have noticed an issue that occurs when a textfield has a floating label, has an error and is of type number.

With the input type number, if you are focused on the textfield the floating label floats correctly. However, when you lose focus and an error is present, the floating label drops down again, intermingling with the faulty text you wrote.

It does not seem to happen for type email though. [Here is some sample code.](http://codepen.io/anon/pen/QbZGJa)

![textfield_issue](https://cloud.githubusercontent.com/assets/3522063/8874903/79854132-3215-11e5-9586-1528cf0fd364.PNG)

**Comment by Garbee** [comment]
How exactly do you get invalid input into the number type like that? Browsers that support the type (all we support) aren't allowing it to happen.

**Comment by jdepypere** [comment]
Well it's not that magical actually - by regularly typing into it. Using Chrome 44.0.2403.107 m (64-bit). I also just tested n Firefox 39.0, same behaviour. In IE 11.0.9600.17914 however, I can type whatever I want into the field (without an error triggering), but upon losing focus if the contents are not a int they are removed. Also in IE 11, if the content I enter starts with a number, it thinks everything is OK:

![ie11](https://cloud.githubusercontent.com/assets/3522063/8891551/20412e90-332f-11e5-89cf-9dac3b7d8e7f.PNG)

**Comment by Garbee** [comment]
So, Chrome it doesn't reproduce. However in FF I am able to type alphabetical chars into a number type to reproduce.

**Comment by jdepypere** [comment]
I did some additional testing for Chrome, and it appears to be due to the `--disable-web-security` flag I have set for development purposes. So I guess it's no issue in Chrome. My other browsers don't have any special flags set so there something is wrong though.

**Comment by Garbee** [comment]
Well, not wrong. The *textfield* input is not designed for number inputs. If it works great, otherwise, use a pattern for the time being. It is a bug technically, but not a priority to be solved until we decide how to handle number types going forward.

**Comment by Garbee** [comment]
Merging into #889 which is the original issue for adding number type support.

Currently, there is no bug just usage we haven't coded for intentionally (missing feature.)
