### ISSUE TITLE
Determinate Circular Progress Indicator

### ISSUE THREAD

**Issue by caiofbpa** [google/material-design-lite#1201]
*Is this a new component, or a missing feature in an existing one?*
Missing feature

*Component name:*
Determinate Circular Progress Indicator

*Material Design spec URL for the component (if any):* http://www.google.com.br/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

*What does this component or feature allow you to do which isn’t possible at the moment?*
Convey determinate progress in a circular way :-)

*Please provide any URLs or screenshots of good examples of usage of this component or feature that you may have come across.*
The only web implementation I found wasn't fully compliant to the spec: https://material.angularjs.org/latest/#/demo/material.components.progressCircular
There are some Java implementations for Android that seem to comply to the spec:
https://github.com/rahatarmanahmed/CircularProgressView
https://github.com/pnikosis/materialish-progress

**Comment by azastrael** [comment]
+1

**Comment by traviskaufman** [comment]
We will be implementing this component in v2 - see #4488 

We are still in the very early stages of v2 and are currently working towards an alpha. Our master branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄
