### ISSUE TITLE
List of all possible color combinations / stylesheets

### ISSUE THREAD

**Issue by cliffordp** [google/material-design-lite#1206]
I know about the color wheel at http://www.getmdl.io/customize/ and I did some playing around on my own outside of it.

I discovered that setting primary and secondary colors to the same is apparently OK, although the color wheel does not allow picking/previewing this.

Examples:
- `teal-teal` exists: https://storage.googleapis.com/code.getmdl.io/1.0.1/material.teal-teal.min.css even though it's not selectable via the color wheel
  - Primary teal is [RGB(0,150,136)](http://www.htmlhexcolor.com/009688)
  - Secondary teal is [RGB(100,255,218)](http://www.htmlhexcolor.com/64ffda)
  - so I guess it's good to go!
- `teal-brown` does not exist: https://storage.googleapis.com/code.getmdl.io/1.0.1/material.teal-brown.min.css which makes sense since it's disallowed on the color wheel
- `brown-brown` does not exist

I found https://github.com/google/material-design-lite/blob/master/docs/_assets/customizer.js#L74-78:
```
  var COLORS = ['Cyan', 'Teal', 'Green', 'Light Green', 'Lime',
                        'Yellow', 'Amber', 'Orange', 'Brown', 'Blue Grey',
                        'Grey', 'Deep Orange', 'Red', 'Pink', 'Purple',
                        'Deep Purple', 'Indigo', 'Blue', 'Light Blue'];
  var FORBIDDEN_ACCENTS = ['Blue Grey', 'Brown', 'Grey'];
```
But it wasn't clear to me, since `Brown` *is* allowed as secondary/accent if `Orange` is the primary.

If it helps, here's a list of all the existing / "valid" color combos for v1.0.1 CSS files, as of today:
```
teal-teal
teal-purple
teal-deep_purple
teal-deep_orange
teal-pink
teal-indigo
teal-red
teal-yellow
teal-blue
teal-green
teal-orange
teal-light_blue
teal-amber
teal-cyan
teal-light_green
teal-lime
purple-teal
purple-purple
purple-deep_purple
purple-deep_orange
purple-pink
purple-indigo
purple-red
purple-yellow
purple-blue
purple-green
purple-orange
purple-light_blue
purple-amber
purple-cyan
purple-light_green
purple-lime
deep_purple-teal
deep_purple-purple
deep_purple-deep_purple
deep_purple-deep_orange
deep_purple-pink
deep_purple-indigo
deep_purple-red
deep_purple-yellow
deep_purple-blue
deep_purple-green
deep_purple-orange
deep_purple-light_blue
deep_purple-amber
deep_purple-cyan
deep_purple-light_green
deep_purple-lime
deep_orange-teal
deep_orange-purple
deep_orange-deep_purple
deep_orange-deep_orange
deep_orange-pink
deep_orange-indigo
deep_orange-red
deep_orange-yellow
deep_orange-blue
deep_orange-green
deep_orange-orange
deep_orange-light_blue
deep_orange-amber
deep_orange-cyan
deep_orange-light_green
deep_orange-lime
pink-teal
pink-purple
pink-deep_purple
pink-deep_orange
pink-pink
pink-indigo
pink-red
pink-yellow
pink-blue
pink-green
pink-orange
pink-light_blue
pink-amber
pink-cyan
pink-light_green
pink-lime
indigo-teal
indigo-purple
indigo-deep_purple
indigo-deep_orange
indigo-pink
indigo-indigo
indigo-red
indigo-yellow
indigo-blue
indigo-green
indigo-orange
indigo-light_blue
indigo-amber
indigo-cyan
indigo-light_green
indigo-lime
blue_grey-teal
blue_grey-purple
blue_grey-deep_purple
blue_grey-deep_orange
blue_grey-pink
blue_grey-indigo
blue_grey-red
blue_grey-yellow
blue_grey-blue
blue_grey-green
blue_grey-orange
blue_grey-light_blue
blue_grey-amber
blue_grey-cyan
blue_grey-light_green
blue_grey-lime
red-teal
red-purple
red-deep_purple
red-deep_orange
red-pink
red-indigo
red-red
red-yellow
red-blue
red-green
red-orange
red-light_blue
red-amber
red-cyan
red-light_green
red-lime
yellow-teal
yellow-purple
yellow-deep_purple
yellow-deep_orange
yellow-pink
yellow-indigo
yellow-red
yellow-yellow
yellow-blue
yellow-green
yellow-orange
yellow-light_blue
yellow-amber
yellow-cyan
yellow-light_green
yellow-lime
blue-teal
blue-purple
blue-deep_purple
blue-deep_orange
blue-pink
blue-indigo
blue-red
blue-yellow
blue-blue
blue-green
blue-orange
blue-light_blue
blue-amber
blue-cyan
blue-light_green
blue-lime
green-teal
green-purple
green-deep_purple
green-deep_orange
green-pink
green-indigo
green-red
green-yellow
green-blue
green-green
green-orange
green-light_blue
green-amber
green-cyan
green-light_green
green-lime
brown-teal
brown-purple
brown-deep_purple
brown-deep_orange
brown-pink
brown-indigo
brown-red
brown-yellow
brown-blue
brown-green
brown-orange
brown-light_blue
brown-amber
brown-cyan
brown-light_green
brown-lime
grey-teal
grey-purple
grey-deep_purple
grey-deep_orange
grey-pink
grey-indigo
grey-red
grey-yellow
grey-blue
grey-green
grey-orange
grey-light_blue
grey-amber
grey-cyan
grey-light_green
grey-lime
orange-teal
orange-purple
orange-deep_purple
orange-deep_orange
orange-pink
orange-indigo
orange-red
orange-yellow
orange-blue
orange-green
orange-orange
orange-light_blue
orange-amber
orange-cyan
orange-light_green
orange-lime
light_blue-teal
light_blue-purple
light_blue-deep_purple
light_blue-deep_orange
light_blue-pink
light_blue-indigo
light_blue-red
light_blue-yellow
light_blue-blue
light_blue-green
light_blue-orange
light_blue-light_blue
light_blue-amber
light_blue-cyan
light_blue-light_green
light_blue-lime
amber-teal
amber-purple
amber-deep_purple
amber-deep_orange
amber-pink
amber-indigo
amber-red
amber-yellow
amber-blue
amber-green
amber-orange
amber-light_blue
amber-amber
amber-cyan
amber-light_green
amber-lime
cyan-teal
cyan-purple
cyan-deep_purple
cyan-deep_orange
cyan-pink
cyan-indigo
cyan-red
cyan-yellow
cyan-blue
cyan-green
cyan-orange
cyan-light_blue
cyan-amber
cyan-cyan
cyan-light_green
cyan-lime
light_green-teal
light_green-purple
light_green-deep_purple
light_green-deep_orange
light_green-pink
light_green-indigo
light_green-red
light_green-yellow
light_green-blue
light_green-green
light_green-orange
light_green-light_blue
light_green-amber
light_green-cyan
light_green-light_green
light_green-lime
lime-teal
lime-purple
lime-deep_purple
lime-deep_orange
lime-pink
lime-indigo
lime-red
lime-yellow
lime-blue
lime-green
lime-orange
lime-light_blue
lime-amber
lime-cyan
lime-light_green
lime-lime
```
Please advise:
1) Is there a maintained whitelist of all existing color combinations? (Instead of me just testing for all possible files that exist)
2) What's up with teal-teal, purple-purple, etc? (I see they're valid CSS files but why not selectable on the color wheel if valid)?

**Comment by surma** [comment]
> - `teal-teal` exists

It shouldn’t :smile: That’s a case I forgot to eliminate. AFAIK primary and accent color have to be distinct.

> But it wasn't clear to me, since `Brown` *is* allowed as secondary/accent if `Orange` is the primary.

Where do you get that idea from?

> Please advise:
> 1) Is there a maintained whitelist of all existing color combinations? (Instead of me just testing for all possible files that exist)

No, we don’t have an explicit list. The snippet you pasted actually says it best:

```JS
  var COLORS = ['Cyan', 'Teal', 'Green', 'Light Green', 'Lime',
                        'Yellow', 'Amber', 'Orange', 'Brown', 'Blue Grey',
                        'Grey', 'Deep Orange', 'Red', 'Pink', 'Purple',
                        'Deep Purple', 'Indigo', 'Blue', 'Light Blue'];
  var FORBIDDEN_ACCENTS = ['Blue Grey', 'Brown', 'Grey'];
```

Choose two colors from `COLORS`, although the second color cannot be any color in `FORIBDDEN_ACCENTS` and they must be distinct.

HTH

**Comment by cliffordp** [comment]
> But it wasn't clear to me, since Brown is allowed as secondary/accent if Orange is the primary.

Um, not sure now. Maybe color picker allowed it before? Disregard now.

The picker at http://www.getmdl.io/customize/ now does follow the `var COLORS` and `var FORBIDDEN_ACCENTS` and everything makes more sense now.

However, https://storage.googleapis.com/code.getmdl.io/1.0.1/material.teal-teal.min.css still exists. Will that be deleted or will it just not exist for v1.0.2 and future versions?

Thanks.

**Comment by Garbee** [comment]
@cliffordp What exists now, exists. We can't remove it. The changes will take effect with the next version push.

**Comment by cliffordp** [comment]
:+1:

**Comment by surma** [comment]
Now I’m really curious if people have been downloading the unofficial color combinations.

**Comment by cliffordp** [comment]
FYI just for my own curiosity and to share...

There are 240 "valid" color combinations (listed below):
[304 actually exist for v1.0.1, as previously discussed]
```
teal-purple
teal-deep_purple
teal-deep_orange
teal-pink
teal-indigo
teal-red
teal-yellow
teal-blue
teal-green
teal-orange
teal-light_blue
teal-amber
teal-cyan
teal-light_green
teal-lime
purple-teal
purple-deep_purple
purple-deep_orange
purple-pink
purple-indigo
purple-red
purple-yellow
purple-blue
purple-green
purple-orange
purple-light_blue
purple-amber
purple-cyan
purple-light_green
purple-lime
deep_purple-teal
deep_purple-purple
deep_purple-deep_orange
deep_purple-pink
deep_purple-indigo
deep_purple-red
deep_purple-yellow
deep_purple-blue
deep_purple-green
deep_purple-orange
deep_purple-light_blue
deep_purple-amber
deep_purple-cyan
deep_purple-light_green
deep_purple-lime
deep_orange-teal
deep_orange-purple
deep_orange-deep_purple
deep_orange-pink
deep_orange-indigo
deep_orange-red
deep_orange-yellow
deep_orange-blue
deep_orange-green
deep_orange-orange
deep_orange-light_blue
deep_orange-amber
deep_orange-cyan
deep_orange-light_green
deep_orange-lime
pink-teal
pink-purple
pink-deep_purple
pink-deep_orange
pink-indigo
pink-red
pink-yellow
pink-blue
pink-green
pink-orange
pink-light_blue
pink-amber
pink-cyan
pink-light_green
pink-lime
indigo-teal
indigo-purple
indigo-deep_purple
indigo-deep_orange
indigo-pink
indigo-red
indigo-yellow
indigo-blue
indigo-green
indigo-orange
indigo-light_blue
indigo-amber
indigo-cyan
indigo-light_green
indigo-lime
red-teal
red-purple
red-deep_purple
red-deep_orange
red-pink
red-indigo
red-yellow
red-blue
red-green
red-orange
red-light_blue
red-amber
red-cyan
red-light_green
red-lime
yellow-teal
yellow-purple
yellow-deep_purple
yellow-deep_orange
yellow-pink
yellow-indigo
yellow-red
yellow-blue
yellow-green
yellow-orange
yellow-light_blue
yellow-amber
yellow-cyan
yellow-light_green
yellow-lime
blue-teal
blue-purple
blue-deep_purple
blue-deep_orange
blue-pink
blue-indigo
blue-red
blue-yellow
blue-green
blue-orange
blue-light_blue
blue-amber
blue-cyan
blue-light_green
blue-lime
green-teal
green-purple
green-deep_purple
green-deep_orange
green-pink
green-indigo
green-red
green-yellow
green-blue
green-orange
green-light_blue
green-amber
green-cyan
green-light_green
green-lime
orange-teal
orange-purple
orange-deep_purple
orange-deep_orange
orange-pink
orange-indigo
orange-red
orange-yellow
orange-blue
orange-green
orange-light_blue
orange-amber
orange-cyan
orange-light_green
orange-lime
light_blue-teal
light_blue-purple
light_blue-deep_purple
light_blue-deep_orange
light_blue-pink
light_blue-indigo
light_blue-red
light_blue-yellow
light_blue-blue
light_blue-green
light_blue-orange
light_blue-amber
light_blue-cyan
light_blue-light_green
light_blue-lime
amber-teal
amber-purple
amber-deep_purple
amber-deep_orange
amber-pink
amber-indigo
amber-red
amber-yellow
amber-blue
amber-green
amber-orange
amber-light_blue
amber-cyan
amber-light_green
amber-lime
cyan-teal
cyan-purple
cyan-deep_purple
cyan-deep_orange
cyan-pink
cyan-indigo
cyan-red
cyan-yellow
cyan-blue
cyan-green
cyan-orange
cyan-light_blue
cyan-amber
cyan-light_green
cyan-lime
light_green-teal
light_green-purple
light_green-deep_purple
light_green-deep_orange
light_green-pink
light_green-indigo
light_green-red
light_green-yellow
light_green-blue
light_green-green
light_green-orange
light_green-light_blue
light_green-amber
light_green-cyan
light_green-lime
lime-teal
lime-purple
lime-deep_purple
lime-deep_orange
lime-pink
lime-indigo
lime-red
lime-yellow
lime-blue
lime-green
lime-orange
lime-light_blue
lime-amber
lime-cyan
lime-light_green
```

**Comment by somombo** [comment]
I'm not really understanding, does this all mean that for example indigo-blue_grey is forbidden or discouraged in the material design spec?

If not why is this not available in the customizer at https://getmdl.io/customize/index.html ?
Please advise, because this would actually be the perfect combo for our brand.

**Comment by Garbee** [comment]
What would make you think `indigo-blue_grey` is forbidden?

**Comment by somombo** [comment]
because https://code.getmdl.io/1.3.0/material.indigo-blue_grey.min.css is 404

whereas e.g.  https://code.getmdl.io/1.3.0/material.blue_grey-indigo.min.css is not

what I need is the former

**Comment by Garbee** [comment]
That's an odd one. Not sure exactly why it isn't allowed. Could be something the spec doesn't allow or could be a bug in the contrast math happening.

You can always download and build your own version from the source with the colors you want.

**Comment by somombo** [comment]
Well, it can only either be a bug or the spec.. I posted on this thread with the hopes of narrowing down which of these two it is so that if it is the former then we can open a separate issue for it.

I'd be surprised if I am the only one who has ever wanted that color combination, let alone the only one who will ever want it.

**Comment by Garbee** [comment]
MDL is no longer being maintained by the core team so much. We are focusing on Material Components for Web (previously MDLv2) and MDL is primarily up to community members to handle at this point.

A color combination, possible bug, with the color picker is a non-critical issue. If someone really wants it, they can do a manual build with the colors. I have a feeling the a11y contrast is the problem here and that is why it is a discouraged color setup.

Remember, in reality you can use whatever colors you want. The palettes provided are just examples build to work well together in most cases.

**Comment by somombo** [comment]
thanks for pointing me to Material Components. I was unaware. appreciate it

**Comment by cliffordp** [comment]
Is there a link to find out more about Material Components for Web (previously MDLv2) ?

**Comment by Garbee** [comment]
https://github.com/material-components/material-components-web

**Comment by mandadimuralidharreddy** [comment]
Javascript array
            var COLORS=["teal-purple","teal-deep_purple","teal-deep_orange","teal-pink","teal-indigo","teal-red","teal-yellow","teal-blue","teal-green","teal-orange","teal-light_blue","teal-amber","teal-cyan","teal-light_green","teal-lime","purple-teal","purple-deep_purple","purple-deep_orange","purple-pink","purple-indigo","purple-red","purple-yellow","purple-blue","purple-green","purple-orange","purple-light_blue","purple-amber","purple-cyan","purple-light_green","purple-lime","deep_purple-teal","deep_purple-purple","deep_purple-deep_orange","deep_purple-pink","deep_purple-indigo","deep_purple-red","deep_purple-yellow","deep_purple-blue","deep_purple-green","deep_purple-orange","deep_purple-light_blue","deep_purple-amber","deep_purple-cyan","deep_purple-light_green","deep_purple-lime","deep_orange-teal","deep_orange-purple","deep_orange-deep_purple","deep_orange-pink","deep_orange-indigo","deep_orange-red","deep_orange-yellow","deep_orange-blue","deep_orange-green","deep_orange-orange","deep_orange-light_blue","deep_orange-amber","deep_orange-cyan","deep_orange-light_green","deep_orange-lime","pink-teal","pink-purple","pink-deep_purple","pink-deep_orange","pink-indigo","pink-red","pink-yellow","pink-blue","pink-green","pink-orange","pink-light_blue","pink-amber","pink-cyan","pink-light_green","pink-lime","indigo-teal","indigo-purple","indigo-deep_purple","indigo-deep_orange","indigo-pink","indigo-red","indigo-yellow","indigo-blue","indigo-green","indigo-orange","indigo-light_blue","indigo-amber","indigo-cyan","indigo-light_green","indigo-lime","red-teal","red-purple","red-deep_purple","red-deep_orange","red-pink","red-indigo","red-yellow","red-blue","red-green","red-orange","red-light_blue","red-amber","red-cyan","red-light_green","red-lime","yellow-teal","yellow-purple","yellow-deep_purple","yellow-deep_orange","yellow-pink","yellow-indigo","yellow-red","yellow-blue","yellow-green","yellow-orange","yellow-light_blue","yellow-amber","yellow-cyan","yellow-light_green","yellow-lime","blue-teal","blue-purple","blue-deep_purple","blue-deep_orange","blue-pink","blue-indigo","blue-red","blue-yellow","blue-green","blue-orange","blue-light_blue","blue-amber","blue-cyan","blue-light_green","blue-lime","green-teal","green-purple","green-deep_purple","green-deep_orange","green-pink","green-indigo","green-red","green-yellow","green-blue","green-orange","green-light_blue","green-amber","green-cyan","green-light_green","green-lime","orange-teal","orange-purple","orange-deep_purple","orange-deep_orange","orange-pink","orange-indigo","orange-red","orange-yellow","orange-blue","orange-green","orange-light_blue","orange-amber","orange-cyan","orange-light_green","orange-lime","light_blue-teal","light_blue-purple","light_blue-deep_purple","light_blue-deep_orange","light_blue-pink","light_blue-indigo","light_blue-red","light_blue-yellow","light_blue-blue","light_blue-green","light_blue-orange","light_blue-amber","light_blue-cyan","light_blue-light_green","light_blue-lime","amber-teal","amber-purple","amber-deep_purple","amber-deep_orange","amber-pink","amber-indigo","amber-red","amber-yellow","amber-blue","amber-green","amber-orange","amber-light_blue","amber-cyan","amber-light_green","amber-lime","cyan-teal","cyan-purple","cyan-deep_purple","cyan-deep_orange","cyan-pink","cyan-indigo","cyan-red","cyan-yellow","cyan-blue","cyan-green","cyan-orange","cyan-light_blue","cyan-amber","cyan-light_green","cyan-lime","light_green-teal","light_green-purple","light_green-deep_purple","light_green-deep_orange","light_green-pink","light_green-indigo","light_green-red","light_green-yellow","light_green-blue","light_green-green","light_green-orange","light_green-light_blue","light_green-amber","light_green-cyan","light_green-lime","lime-teal","lime-purple","lime-deep_purple","lime-deep_orange","lime-pink","lime-indigo","lime-red","lime-yellow","lime-blue","lime-green","lime-orange","lime-light_blue","lime-amber","lime-cyan","lime-light_green"];
