### ISSUE TITLE
[Angularjs] - Textfield not considering ngModel

### ISSUE THREAD

**Issue by Piou2fois** [google/material-design-lite#1215]
I am facing an issue regarding the textfield behavior.
On the below plnkr, follow the steps:
1-click on "groups working"
2-click on "copy" on one item
3-look at the very end new textfield appeared with the ngModel associated (angular.copy) but the behavior of the textfield is strange, even if there is a value, the label is not floating but if you click in the textfield, it floats as expected. If you modify the field the behavior remains, but if you quit it without any modification label comes back with overlay.
http://plnkr.co/edit/MUI2iBslIH9jd4fgEQPL?p=preview

Hope it is clear enough.
Thank you

**Comment by Garbee** [comment]
Please use StackOverflow for support.
