### ISSUE TITLE
Same HTML different View

### ISSUE THREAD

**Issue by LoveAndHappiness** [google/material-design-lite#1216]
Hi guys,

simple components are not working properly. See f.e. the Icon on the Top Left here:

http://temp.leavingblue.com/5.html

But when you Copy/Paste the code like this:

1. Copy source code with cmd+U
2. Open codepen.io/pen
3. Paste the HTML to Codepen

You'll see it working properly.

Well, why doesn't it work on the link above? (Also not on my local windows machine, my linux virtual machine, firefox and chrome canary)

I also openend a stackoverflow question here: http://stackoverflow.com/questions/31637546/html-equal-html-different-view

**Comment by Garbee** [comment]
Please use SO for support (as you already had) and open issues here when there is a determined problem with what is provided in core.
