### ISSUE TITLE
Native Feel on Cordova

### ISSUE THREAD

**Issue by der-ede** [google/material-design-lite#1221]
Hi there,

has anyone tested MDL on Cordova yet?
Does it have the common problems of juddery or choppy scrolling etc. or is it "native feel"?

Regards

**Comment by Garbee** [comment]
Please use this tracker only for problems with what MDL provides. We do not support technologies not provided by us.

**Comment by MGageMorgan** [comment]
I'm tryna do this, but it doesn't seem to build but that's just me.

**Comment by rockneverdies55** [comment]
@Garbee - very helpful answer thanks!

**Comment by MGageMorgan** [comment]
I've done it already as a project afterward and forgot to post back here. I understand this thread is closed, and I apologize about ignorance (though it is bliss), but it does work just like anything else you can shove through Cordova. I'm working on a different project using a similar toolkit called Electron, which is Cordova without mobile. 

Yes, the thread is closed.
