### ISSUE TITLE
is-invalid but not is-dirty colored red

### ISSUE THREAD

**Issue by rhythnic** [google/material-design-lite#1223]
This may be a design choice and not a bug, but empty required fields are displaying as invalid prior to the form being submitted.

**Comment by Garbee** [comment]
> empty required fields are displaying as invalid

Working as normal HTML5 validation is. Not seeing a problem.

**Comment by thejae** [comment]
Hello all, I ran into this issue and thought it was odd. For example, Chrome won't show the error tooltip until form submission is triggered. 

It is weird for MDL to mark fields as invalid right after page load without user triggered event.

![image](https://cloud.githubusercontent.com/assets/738694/9436048/4128a1a8-4a7f-11e5-93d8-55de9bedc211.png)
