### ISSUE TITLE
Page "jumps to top" on material.min.js load-in

### ISSUE THREAD

**Issue by ShadeLotus** [google/material-design-lite#1224]
After material.min.js loads in, my website "jumps" to the top of the page.  

http://gaming-thrones.tumblr.com

This is annoying because when the page loads in you want to start scrolling down and then bam snaps you back up to the top.

Help?

**Comment by Garbee** [comment]
This is because of the layout JS taking effect. Nothing can really be done about it without a full refactor of the layout system.

**Comment by shadesoflight** [comment]
Could you point me towards the layout system?

**Comment by shadesoflight** [comment]
I mean, even a hook to wait until loading finishes and hide a spinner.

**Comment by shadesoflight** [comment]
here, obviously:  https://github.com/google/material-design-lite/blob/master/src/layout/layout.js

**Comment by shadesoflight** [comment]
Looks like a mix between MutationObserver and Mutation events (for IE9) might allow me to hook the "IS_UPGRADED" (i.e. 'is-upgraded') class after init?  https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L396

**Comment by Garbee** [comment]
StackOverflow is the proper place to get support.

**Comment by shadesoflight** [comment]
This isn't support on how to use your framework.  This is an obvious defect in a google library.

I'm asking about development guidance for the prospect of sending in a PR to add basic "post-init" event emitting -- do you feel that github is the wrong location to discuss improvements to the code base?

**Comment by Garbee** [comment]
Sorry, it wasn't obvious that you were recommending adding something into core.

We are not adding MutationObservers into core, they don't support the browsers our JS needs to support (IE10+). We also don't support IE9 at all with JS (therefore layout) so supporting that is irrelevant to this issue.

**Comment by shadesoflight** [comment]
I also duly appologize for not being clear with my intent.

I'm saying that if you don't add an event being emitted after init, maybe I can hook into the class being added using MutationObservers and/or Mutation Events.

Ideally, there would be a "layout-rendered" event, after which I can hide a spinner.

Please and thank you? <3s

**Comment by Garbee** [comment]
ah, so you want a custom event fired in the constructor after intitialization happens. That is entirely reasonable imo.

cc @surma for thoughts on that since as I recall he wrote the layout component.

**Comment by surma** [comment]
Well, I didn’t write the layout component, but I’ll gladly try to help anyways ;)

@ShadeLotus We [do emit a `mdl-componentupgrade` event](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js#L166). Is this sufficient (I feel like it should be)?

**Comment by ShadeLotus** [comment]
@surma I can try it and get back to you.  As long as it only fires once and only after all of the layout is rendered, then it will work.

Deal breakers would be if I cannot get it to fire once (i.e. cannot hook into an element like body or what-have-you) and it fires before the page is completely loaded (i.e. hides a spinner and then snaps to the top anyways)

Sufficient if it satisfies the above, otherwise otherwise.

**Comment by surma** [comment]
It should fire exactly once on the element being upgrade (i.e. the node with `.mdl-layout`). Our upgrade procedure runs after page load, so that should work as well. Give it a try and let me know :)

**Comment by claudiordgz** [comment]
THIS IS FANTASTIC!!! THANKS @surma My ads are loading correctly now thanks to you. Kudos to you. ![](https://media.giphy.com/media/SBI7lnqk2NaA8/giphy.gif)

**Comment by surma** [comment]
Lol. Glad to hear :)

**Comment by RoyMankin** [comment]
@surma 
I am facing the exact same problem in my site, but I didn't get the answer given above can you please explain how to fix this issue?

**Comment by Thlenzi** [comment]
I have set it **` .mdl-layout__container { position: relative; }`** after mdl.min.css Now it works fine.
