### ISSUE TITLE
Include classes for larger icon font sizes

### ISSUE THREAD

**Issue by cliffordp** [google/material-design-lite#1227]
Could do something like this and be used for icon sizing or whatever else.

```
.font-size-2x {
font-size: 2em;
}
.font-size-3x {
font-size: 3em;
}
etc...
```

Like http://fortawesome.github.io/Font-Awesome/examples/#larger

I don't have class name preferences.

Possibly related: #864

**Comment by Garbee** [comment]
Something like this adds considerable bloat for niche cases. If you need to resize things, just do it in your own CSS.

**Comment by cliffordp** [comment]
Sounds good. Just didn't want to duplicate if it'd be added to MDL core.
