### ISSUE TITLE
componentHandler in global scope

### ISSUE THREAD

**Issue by yongxu** [google/material-design-lite#1230]
```
var componentHandler = (function() {
           ....
})();
```
from mdlComponentHandler.js is injected into the global scope.

I feel this name might cause name collision one day.
Wound't it be better to name it to mdlComponentHandler?

**Comment by traviskaufman** [comment]
Closing this as we will be removing global upgrade handlers altogether within v2.

We are still in the very early stages of v2 and are currently working towards an alpha. Our master branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄
