### ISSUE TITLE
Radio onchange refactor

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1232]
The onchange event for radios is fairly wasteful. For large pages with lots of radios, it can use many more cycles than needed. A better implementation is to query up just the radios of the given name, then loop over those and call updateClasses_ against them.

This can't be done in the lifecycle of 1.x due to compatibility concerns with existing sites which may have wrapped the radio inputs in other elements in between the label.

**Comment by addyosmani** [comment]
I think holding off until post 1.x to address this makes sense.

**Comment by traviskaufman** [comment]
ref. #4477

**Comment by Garbee** [comment]
Nothing we can do in V1 about this. Let's just make sure it is taken care of building the new engine out for V2.
