### ISSUE TITLE
Textfield error message position

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1236]
Having some issues with the position of the error message
Currently the styles are like this:
```
// TextField Error.
.mdl-textfield__error {
  color: $input-text-error-color;
  position: absolute;
  font-size: 12px;
  margin-top: 3px;
  visibility: hidden;

  .mdl-textfield.is-invalid & {
    visibility: visible;
  }
}
```

Shouldn't we put a `left: 0` and transform the `margin-top` in just `top` (with a bigger value) to put it at the right place?

Here's what I get using a textfield (width 200px) without any styles other than MDL:
<img width="266" alt="screen shot 2015-07-28 at 7 12 14 pm" src="https://cloud.githubusercontent.com/assets/1972567/8946217/b0d5c14e-355c-11e5-8955-451dd2e0ebfa.png">

**Comment by Garbee** [comment]
I'm able to reproduce, but only after modifying `input` to have a set width of 200px. Which means the containing element (label) has an extra 100 pixels to put the error into.

Why are you setting hard widths on the inputs? By default you can set the width of `.mdl-textfield` and the input and error will display properly within that constraint. Since you are modifying the input itself, it is messing up the built in styling.

**Comment by tleunen** [comment]
Hmm... Not in my case, I'm setting the width of the container `mdl-textfield`, not the input.

**Comment by tleunen** [comment]
Not sure why I don't reproduce it in codepen but I have it in a local environment, with only MDL.. Let me investigate a bit

**Comment by tleunen** [comment]
Checked and tried to compare the example in codepen and the one in my blank page. Both have the same css computed properties by Chrome, so I have no idea why the error is offset like that :/

**Comment by tleunen** [comment]
Found the issue.

Remove the space between the input and the label, and the label and the error, and you'll get the UI issue. Here's the codepen: http://codepen.io/anon/pen/BNGdQG (no need to set a width btw)
Tested on Chrome, FF and Safari and all 3 have the same issue.

Because of the spaces, the text is going back to the next line, but in a world where almost everything is minified, we cannot based the code on that. I think it would be safer to use top/bottom/left/right to set the position, unless there's another way of fixing that?

**Comment by surma** [comment]
Great work, @tleunen. I’m not sure we can easily switch to absolute positioning without causing breaking changes, but we’ll look into that.
