### ISSUE TITLE
Footer fixed on Mobile

### ISSUE THREAD

**Issue by juanscv** [google/material-design-lite#1237]
The footer becomes fixed at the bottom and doesn't scroll when i reach mobile UI. Been unsuccessful in getting to position appropriately and scroll.
I removed my CSS and made a test page, and it still happens.
_____
![screen shot 2015-07-29 at 00 14 53](https://cloud.githubusercontent.com/assets/955241/8950430/2252ce8c-3587-11e5-8770-a8014ddd1afc.png)

**Comment by surma** [comment]
Can you provide a codepen that reproduces the issue for you?

**Comment by juanscv** [comment]
Here it is in jsfiddle http://jsfiddle.net/mqxd5dz6/1/

**Comment by Garbee** [comment]
The footer should be within  the content area of the layout. In this  case the `<main>` element, since it has the `.mdl-layout__content` class. All page content goes within that.
