### ISSUE TITLE
HTML can't be include

### ISSUE THREAD

**Issue by vulcaryn** [google/material-design-lite#1242]
Hi,

Today i decide to try MDL on an angular app.
The first page are pretty cool but when i try to use ng-view to insert a template, mdl stop working.
The style is broken and components doesn't start, and I have no bugs in JS console.

Someone have a idea about how fix this ?

Thanks

**Comment by surma** [comment]
We don’t directly support Angular (as we are targeting static content for now). There’s been a bunch of discussions on StackOverflow, though. I recommend head over there and looking for the `material-design-lite` tag.
