### ISSUE TITLE
Dropdown menu not working as expected

### ISSUE THREAD

**Issue by creatifDynamics** [google/material-design-lite#1243]
Hello,

When the button is clicked, the dropdown is ok but when I scroll the page the dropdown list stays in the same place. If I click out and click back the button the dropdown appears when it was the first time.

See screenshots.
I'm using MDL with Angular + Bower + RequireJS

I'm also doing this :
<pre lang="javascript"><code>
$rootScope.$on('$viewContentLoaded', function() {
    $timeout(function() {
        componentHandler.upgradeAllRegistered();
     })
});
</code></pre>

![screen shot 2015-07-29 at 12 26 15](https://cloud.githubusercontent.com/assets/5292942/8955504/9f7acf7a-35ed-11e5-864f-e819463d7731.png)
![screen shot 2015-07-29 at 12 26 23](https://cloud.githubusercontent.com/assets/5292942/8955505/9f9446ee-35ed-11e5-9bed-7e4bd0924f44.png)

**Comment by surma** [comment]
I [can’t reproduce](http://codepen.io/anon/pen/LVXezz). Can you provide me with a codepen that reproduces the issue? Preferably *without* Angular.

**Comment by creatifDynamics** [comment]
.mdl-layout__content {
  position: relative;
}

This fixed it ! Thanks for your help
