### ISSUE TITLE
Loading progress bar (Indeterminate) is not taking whole length

### ISSUE THREAD

**Issue by ranajit484** [google/material-design-lite#1254]
Hi,
I am using Indeterminate loading in one of our material lite page. 
The problem is that it not taking whole length applied to it.

I am using div with class 'mdl-grid' and inside that I am using another div with class 'mdl-cell mdl-cell--12-col'. in this inner div I am actually using progress bar div.

I am using following HTML code:
`<div class="mdl-grid">`
    `    <div class="mdl-cell mdl-cell--12-col">`
            `     <div class="mdl-progress mdl-js-progress mdl-progress__indeterminate"></div>`
        `     </div>`
`    </div>`

The output of which is:
![col12](https://sc-cdn.scaleengine.net/i/b0812a65a46892bf0bc0aa700db1aad5.png)

As you can see, it's not taking whole length of the div i.e. 100%
So, I tried with two 6 column grids and tried to add progress bar component into those like,

`<div class="mdl-cell mdl-cell--6-col">`
           ` <div class="mdl-progress mdl-js-progress mdl-progress__indeterminate"></div>`
        `</div> `
        `<div class="mdl-cell mdl-cell--6-col">`
            `<div class="mdl-progress mdl-js-progress mdl-progress__indeterminate"></div>`
        `</div>`

And now the output is as below:
![col6](https://sc-cdn.scaleengine.net/i/7af2f56aac540ffb9be99b3752a9f608.png)

Could you please guide us on how can we use inderminate progress bar to take whole length assigned to it?

**Comment by Garbee** [comment]
Please use StackOverflow for support questions.
