### ISSUE TITLE
Fire events from form toggle methods

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1264]
Currently if you use say `MaterialRadio.check()` no change event is fired. This is consistent with how normal JS works, since if you call `checked` directly, it won't fire the event either. However, since we are already doing some extra logic around these, should we add firing events right into the methods? This will save developers from needing to remember to trigger them on their own.

**Comment by Garbee** [comment]
cc @surma @addyosmani @sgomes 

Any thoughts on this? If it is something we want to do then I can fix it up this week. However, I believe there are some BC concerns, since we could end up firing an extra event in applications already designed to handle this themselves. That could cause slowness or breaks in poorly written JS.

**Comment by surma** [comment]
My2¢: `check()` will be called by the user, so event should be emitted by the user as well, if desired. If we want to provide convenience, make it `check(bool dispatchEvent)`. But it’s unnecessary, imo.

**Comment by Garbee** [comment]
SGTM to not add any helper for this. I dislike bool attributes in this context. We are also currently following closely with what regular JS will do. I will still await input from one or two others, maybe there is a good case for doing so (beyond pure convenience) that we aren't thinking of.

**Comment by Garbee** [comment]
After sleeping on it more, closing this issue out. Staying true to "lite" and attempting to be simple to integrate and understand the API, adding this functionality would go against both.
