### ISSUE TITLE
Cursor not moving with textfield on Safari mobile with fixed header

### ISSUE THREAD

**Issue by JhoongRoh** [google/material-design-lite#1267]
Steps on mobile Safari (haven't verified on other platforms):
1. Fixed header
2. Page is longer than the screen size
3. Tap on textfield and virtual keyboard pops up
4. Move non keyboard part of the screen (scroll up/down)

What's Happening: 
The cursor will not move relative to the textfield when you scroll up/down. Once you've stopped scrolling, the cursor will jump to where the textfield is and everything appears normal.

What Should Happen:
Either hide the cursor when you move the screen or have the cursor move with the page.

![thumb_img_0587_1024](https://cloud.githubusercontent.com/assets/3443329/9001202/28b2b584-3709-11e5-800a-b051474888ce.jpg)

**Comment by surma** [comment]
[Confirmed](https://youtu.be/-E58p8hmo6I). Sadly, I’m not sure there’s anything we can do about this. Seems more like a WebKit bug to me.
