### ISSUE TITLE
Material Icons on Windows Phone

### ISSUE THREAD

**Issue by filippomartini** [google/material-design-lite#1275]
The material icons are not showing on Internet Explorer of Windows Phone 8.1
Just look at a random template like the Dashboard one: no icon displayed and all the layout messed up

**Comment by surma** [comment]
I was about to write “Can’t reproduce” when I realized you were talking about Windows *Phone*. Weird.

@addyosmani @marcacohen Do we have Windows 8.1 mobile devices and/or an emulator or something? My arsenal of VMs seems insufficient still :smile:

**Comment by filippomartini** [comment]
I don't know if this is the same set of icons, but maybe can help: https://github.com/google/material-design-icons/issues/179

**Comment by surma** [comment]
That seems related. Thanks for linking, @filippomartini

**Comment by addyosmani** [comment]
Thanks for reporting this. As was mentioned in https://github.com/google/material-design-icons/issues/179, this issue has now been reported to the Material Design icon font team. Unfortunately we can't address the issue here as we just pull in the icon font, but keep an eye on the upstream issue for a fix.

**Comment by jitendravyas** [comment]
I'm facing the same issue on Windows Phone

**Comment by surma** [comment]
@jitendravyas Can you do me a favor and [try the workaround I mentioned in another issue](https://github.com/google/material-design-lite/issues/1375#issuecomment-130721748)?

**Comment by jitendravyas** [comment]
I just used this https://www.google.com/design/icons/#ic_accessibility on my Windows Phone 8.1

```
<i class="material-icons">&#xE84E;</i>
```
output = Nothing just blank white. No icon
````
<i class="material-icons">accessibility</i>
```
output = it renders the text "accessibility". No icon

**Comment by surma** [comment]
@jitendravyas Thank you for your effort. I feel like there’s not much we can do. I’m pretty confident this is an issue with the font itself not with MDL. I’ll also keep an eye on google/material-design-icons#179.
