### ISSUE TITLE
Expanding text fields don't work in iOS 8 with Safari.

### ISSUE THREAD

**Issue by simodorg** [google/material-design-lite#1276]
After I click the button, and the text field doesn't expand.

Here's the HTML template:

    <form role="search" method="get" id="searchform" class="searchform" action="/" >
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
        <label class="mdl-button mdl-js-button mdl-button--icon" for="s">
          <i class="material-icons">search</i>
        </label>
        <div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" placeholder="Search..." type="text" value="' . get_search_query() . '" name="s" id="s" />
         <label class="mdl-textfield__label" for="sample-expandable">Expandable Input</label>
        </div>
      </div>
    </form>

**Comment by surma** [comment]
I can’t reproduce the issue using the [dashboard template](http://www.getmdl.io/templates/dashboard/index.html). Would you mind creating a codepen that we can look at?

**Comment by simodorg** [comment]
@surma Sorry, it's my fault. It works now.

**Comment by surma** [comment]
Glad to hear :)

**Comment by sjt003** [comment]
what did you do to fix this? I have been having the same issue.

**Comment by Pjaerr** [comment]
@sjt003 ![Wisdom Of The Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
