### ISSUE TITLE
[Automatically Aligning FAB] {Component}

### ISSUE THREAD

**Issue by pippintook** [google/material-design-lite#1278]
In the Material Design spec regarding layout (https://www.google.com/design/spec/layout/principles.html#principles-floating-action-button), it is specified how a Floating Action Button can "straddle" a step or a seam between two pieces of paper. It would be helpful if the MDL code contained an aligning class that could be used to automatically position a FAB on the edge of a div.

**Comment by Garbee** [comment]
Duplicate of #737
