### ISSUE TITLE
Improve templates getting started experience

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#1284]
Currently after downloading the `mdl-templates.zip` archive there is no clear next step guiding developers into using the template(s). This could be fixed by, for instance, adding a `README` inside the archive describing the content of the archive and next steps.

**Comment by addyosmani** [comment]
@nicolasgarnier I think this is something we would start to flesh out as part of http://www.getmdl.io/started/index.html#whats-next and we could then link to this from inside mdl-templates.zip and mdl.zip.

Do you want to take a stab at writing a few paragraphs that would tackle this? I think you've got a good handle on what we're missing here.

**Comment by addyosmani** [comment]
@nicolasgarnier do you think you'll have a chance to take a look at this this week? We're trying to get 1.0.3 out the door soon :)

**Comment by nicolasgarnier** [comment]
Hey sure, sorry for missing this was upgraded to P0  :smiley: I'll get to it.

**Comment by nicolasgarnier** [comment]
Hey @addyosmani, @surma,

While reviewing this a few things came up that felt confusing. Please let me know what you think for each:

 - There is a bower.json and a package.json in the template zip file. This was a bit confusing because then I was looking for a build step of some kind especially since the package.json contained a lot of devDependencies that includes Gulp. What about removing the package.json and bower.json file? or do they have any use?

 - On the [documentation's templates page](http://www.getmdl.io/templates/index.html) there are 5 "Downloads" link, one for each templates: 
![image](https://cloud.githubusercontent.com/assets/3766663/9307956/8f6048c2-4501-11e5-8d5a-3a9c0fdbcf18.png)
The issue is that because of that I was expecting the zip file to contain only the files for the one template that I'm trying to download so there is an expectation/result mismatch here. Two ways to fix this:
    - Generate 5 different zip files containing only the content for one template (this is the more user friendly IMO)
    - Remove the 5 downloads link and create a small intro text with only one download link at the top. The zip file would still contain the 5 templates inside but then that would fix the expectations/result mismatch.

Let me know!

**Comment by addyosmani** [comment]
Good catch on the expectation mismatch. Our original intention was that we would only give you the template zip for the template you were trying to grab. Unfortunately, our build process doesn't support this yet but we could update it to be more granular in this regard. 

Perhaps in the short term, dropping the download links and just having a single one at the top would improve matching expectations here.

bower.json/package.json: IIRC these are leftover from the way our build process generates build assets. We create a bundle that we then tag and publish to npm, however we're not excluding these build files when creating our zips. We could do this.

**Comment by surma** [comment]
>  Unfortunately, our build process doesn't support this yet but we could update it to be more granular in this regard. 

Personally, I think we should not provide downloads for each template individually. MDL is our library/product, not the templates. Deleting the ones you don’t want isn’t too much to ask, is it? Feel free to correct me here :)

>Perhaps in the short term, dropping the download links and just having a single one at the top would improve matching expectations here.

:+1: 

> bower.json/package.json: IIRC these are leftover from the way our build process generates build assets. We create a bundle that we then tag and publish to npm, however we're not excluding these build files when creating our zips. We could do this.

We are actually [actively adding](https://github.com/google/material-design-lite/blob/master/gulpfile.js#L504-L519) both `bower.json` and `package.json` and I feel like we had a reason to do so but I don’t remember. I’m definitely in favor of removing these files if they are not needed (anymore).

**Comment by nicolasgarnier** [comment]
Depending on how long we have until 1.0.3 I can try to generate the 5 zips. :D (or not if you actually prefer only one link)

More things that I plan on changing please let me know if you think otherwise:

 - Add a README inside the ZIP ile(s) giving a short description of the template and next steps if the user want to customize.
 - Currently `material.min.css` and `material.min.js` are included in the zip. Since the CDN hosted libs are our recommended option I'll switch to referencing the CDN hosted version directly (FYI the android template does that already for the JS but the version in the link does not get updated) and stop including the libs file's inside the zip.
 - Currently a custom `material.min.css` is also included inside each templates' folder, this was to customize the color accents. We won't need this since I can refer to a color specific CDN hosted CSS.

WDYT? This will make the zip file a LOT simpler by removing a lot of files and show developers how to use the CDN hosted libs.

**Comment by nicolasgarnier** [comment]
Also the zip has an `assets` folder which contains all the documentation's CSS and images. I guess it's here by mistake. Shall I remove it or was there a good reason it's here? :)

**Comment by surma** [comment]
I like your plan. I don’t have a strong opinion on 1 vs 5 ZIPs. I gave my personal 2¢ already.

The `assets` were added because the ZIP contains `templates/index.html` as a listing of all the templates, which needs the assets. If we agree to remove that, `assets` can go as well. 

I give you full decision making power (and thereby responsibility) on this matter @nicolasgarnier :stuck_out_tongue:

**Comment by Garbee** [comment]
I'd say keep one zip. It isn't a big deal to move to 5, only makes more variables to mess up at some point.

Remove `templates/index.html` and make the templates zip just that, the templates using the CDN copies. Keep it as light as possible.

What kind of information would a README contain here? It seems like low-hanging fruit to describe next steps for example templates.

**Comment by nicolasgarnier** [comment]
I have something for the 5 zips which shouldn't require us to maintain 5 variables (it uses the folder name which is already used when generating the template documentation page anyways) so I'll send that for review soon :)

Yes the README was just going to give some pointers about what folder contains what files for which template although now that we've removed most files from the zip and that there are 5 separate zips it feels almost superfluous...

**Comment by Garbee** [comment]
I didn't mean variable so literally. I just meant it as, 5 possible variations to get reports about vs reports on a singular zip. Overall though, they are pretty basic so it doesn't matter much either way. Just felt one is enough.

The README is very much not-needed imo. If developers don't understand what to do with the templates then they shouldn't be using them at all. They are not built to let just anyone throw a site up and be good, they are just example work.

**Comment by nicolasgarnier** [comment]
Yup lets not include READMEs anymore. I can't really think of anything to put in there which is a sign they are not needed. The zips are so small now anyways (just the index.html, the css and - sometimes -an images folder...) as you said, web developers should know what to do at this point :D 

I was initially thinking to add a README because the templates archive contained a lot more files, the index.html for all the templates, the generated libs. Also I thought there might have been a build step since there was a package.json file etc... but in fact it's just a static website made of 2 files :)
