### ISSUE TITLE
Text filed code examples have uneeded textfield-demo class

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1288]
On each of the [text filed](http://www.getmdl.io/components/index.html#textfields-section) code examples and codepens there's a class called ```textfield-demo``` which isn't used or needed.

Please note I'm referring to the code example and not the demoed text fields. The ```textfield-demo``` class is applied to the demos because it sets the width of the text fields to 100px. But in the code examples it isn't used and isn't needed.

**Comment by addyosmani** [comment]
@surma I assume this is fixed per https://github.com/google/material-design-lite/commit/493dfed5334134900da1c1c4fca1cf84ccac39b5 but just checking.

**Comment by surma** [comment]
It would have been if that PR wasn’t really bad by me ;) #1295 is my 2nd attempt
