### ISSUE TITLE
Can't define gutter width.

### ISSUE THREAD

**Issue by sankhadeeproy007** [google/material-design-lite#1297]
![screen shot 2015-08-04 at 7 49 49 pm 2](https://cloud.githubusercontent.com/assets/10998047/9062792/23fd0b7a-3ae2-11e5-8ab7-a417b4a76a62.png)
As you can see in the screenshot attached from the documentation page, the gutter width and the height between the two grids aren't the same. Is there any way I can make them equal? Thanks.

**Comment by surma** [comment]
This is because each row is it’s own `mdl-grid`. Within the same grid, you the gutter will have equal size (resize your browser window!).

If you actually have multiple `mdl-grid`s, you could add
```CSS
.mdl-grid {
  margin-top: 0;
  margin-bottom: 0;
}```

**Comment by sankhadeeproy007** [comment]
@surma What if I want the margin between two grid elements to be greater? How do I set that without extensively writing CSS properties for all the child divs?

**Comment by surma** [comment]
The gutter width is prescribed by the MD spec. So it is somewhat on purpose to make it hard to change that. Having said that, you could run SASS on the grid yourself and set [`$grid-gutter-width`](https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L535) to whatever you desire.

**Comment by sankhadeeproy007** [comment]
Thank you so much.
