### ISSUE TITLE
[Component Request] {Component}

### ISSUE THREAD

**Issue by helmuthva** [google/material-design-lite#1298]
It would be lovely to see the FAB Speed Dial, FAB Toolbar, Bottom Sheet and Progress Linear (cp. Angular Material) in mdl.

In this context - are mdl and angular material somehow related / coordinated or fully separate efforts? This is of importance for all ionic(framework) developers as ionic and angular material cannot merge but we would like to see material design in ionic some time - the ionic material design light project seems to be a way in this direction but if the component library will merge some time is unclear atm.

From a developer perspective the optimum would be to implement google material design using angular material for web apps and some material-add-on for ionic for mobile apps with the component library fully synchronized.

**Comment by Garbee** [comment]
Please file individual issues for components. Also search existing feature-request tagged issues as well, at least one of these already has an issue you  can subscribe to for updates.
