### ISSUE TITLE
Issue fixing windows/unix line endings

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1299]
I believe I'm experiencing issues with line endings under Windows as mentioned in the README.md and #743. The errors I'm seeing when running ```gulp serve```:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ←[1mInvalid line break←[22m at ←[32mmdlComponentHandler.js←[39m :
 ←[90m    1 |←[39m/**
←[90m-----------^←[39m
 ←[90m    2 |←[39m * @license
 ←[90m    3 |←[39m * Copyright 2015 Google Inc. All Rights Reserved.

←[1mInvalid line break←[22m at ←[32manimation\demo.js←[39m :
 ←[90m    1 |←[39m/**
←[90m-----------^←[39m
 ←[90m    2 |←[39m * @license
 ←[90m    3 |←[39m * Copyright 2015 Google Inc. All Rights Reserved.

←[1mInvalid line break←[22m at ←[32mbutton\button.js←[39m :
 ←[90m    1 |←[39m/**
←[90m-----------^←[39m
 ←[90m    2 |←[39m * @license
 ←[90m    3 |←[39m * Copyright 2015 Google Inc. All Rights Reserved.
```

According to the README.md I need to:
```
git config core.eol lf
git config core.autocrlf input
```
But these commands need to be run inside a git repo so I cloned the repo first, but once the repo is cloned I already have the incorrect line endings. If this is correct this documentation needs updating to better explain what to do.

I tried to force a re-pull with the following, but this didn't seem to fix it: 
```
git fetch origin master
git reset --hard FETCH_HEAD
git clean -df
```

**Comment by surma** [comment]
See the *2nd* answer on the [SO question](http://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows/2517442#2517442) @sindresorhus linked to. It says how to “re-checkout” once you changed the line endings.

**Comment by SeanBannister** [comment]
For anyone else pulling their hair out with this, the SO answer is [hidden in a comment](http://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows/2517442#comment19533325_2557397). Type this inside the MDL directory:

```
git rm --cached -r .
git reset --hard
```

**Comment by surma** [comment]
Thanks for documenting :)

**Comment by SeanBannister** [comment]
@surma Now that I have MDL working I'm thinking my first pull request should be better documenting this in README.md? :)

**Comment by surma** [comment]
Go for it!
