### ISSUE TITLE
Local Docs no more?

### ISSUE THREAD

**Issue by seanmavley** [google/material-design-lite#1303]
Previously, about 3 weeks or so ago, I could use the getmdl.io whole documentation locally simply by doing this after pulling repo updates:
`gulp serve` and I the browser will automatically load to localhost:5000 where I could navigate the docs even without internet connection.

Now when I do gulp serve, I get the screen at localhost:5000 with, just links to the mdl css and js files

What step am I missing? Is local docs no longer supported?

**Comment by surma** [comment]
We reworked the gulp file a little in #1147.

T;DR: `gulp all && gulp serve`

**Comment by seanmavley** [comment]
If only somewhere in the docs mentioned it...
I kept going here to see if there's been something changed, but nothing: 
http://www.getmdl.io/started/index.html

Thanks

**Comment by surma** [comment]
@seanmavley I hear you. Running the site locally has not been a use-case we paid great attention to (just didn’t expect that). I’ll make sure it’s in the docs somewhere for 1.1 :)

**Comment by nicolasgarnier** [comment]
Actually we describe how to do that on the README. The Site itself focuses on the library usage.
I see that we forgot to update the README following the #1147 changes. I'll send a PR :)
