### ISSUE TITLE
Programmatic way to select a different tab

### ISSUE THREAD

**Issue by kengruven** [google/material-design-lite#1305]
(Following [this][1] template.)

> Is this a new component, or a missing feature in an existing one?

Missing feature in existing component.

> Component name:

"Tabs"
> Material Design spec URL for the component (if any):

https://www.google.com/design/spec/components/tabs.html

> What does this component or feature allow you to do which isn’t possible at the moment?

There's no way (AFAICT) to programmatically select a different tab, when using an mdl-tabs component.

> Please provide any URLs or screenshots of good examples of usage of this component or feature that you may have come across.

In [this StackOverflow answer][2] a few weeks ago, Garbee said there's no way to do this yet, and to file a feature request.  I couldn't find anything here already.

[1]: https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md#feature
[2]: http://stackoverflow.com/a/31373761

**Comment by surma** [comment]
Already in flight at #1239 :)
