### ISSUE TITLE
[Component Request] Navigation drawer clipped under the app bar

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1312]
In the Material Design Spec for [Navigational Draws it lists 3 types](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior), currently MDL implements the "Full-height navigation drawer" and I'm interested in implementing the "Navigation drawer clipped under the app bar" as seen below:

<img src="https://cloud.githubusercontent.com/assets/197231/9086060/413acf72-3bc5-11e5-8903-cb0ab0e708f7.png" width="300">

From a "use case" perspective I think a lot of developers are looking for this type of drawer. The spec says it should be used for "Apps focused on productivity that require balance across the screen".

I've [prototyped an example (codepen)](http://codepen.io/anon/pen/Nqodew) as close to an actual implementation, it works by adding the ```mdl-layout--clipped-drawer``` class to the ```mdl-layout``` div. This is the same place you add ```mdl-layout--fixed-drawer``` which it will [work alongside (codepen)](http://codepen.io/anon/pen/oXmZPW).

I was considering doing a PR for this but wanted some feedback on the prototype before I try to dig into MDL.

**Comment by Download** [comment]
I'd be very interested in this PR.

**Comment by surma** [comment]
@SeanBannister Great work! Your implementation looks good to me, so feel free to open up a PR and @sgomes can give it a more critical look ;)

**Comment by CreativeParts** [comment]
Currently working on a few other projects, not sure when I'll get back to this at this stage. So if anyone else has a chance please do.

**Comment by SeanBannister** [comment]
Currently working on a few other projects, not sure when I'll get back to this at this stage. So if anyone else has a chance please do.

**Comment by traviskaufman** [comment]
closing; superseded by #4476 which will include support for this layout as well as floating and mini.

We are still in the very early stages of v2 and are currently working towards an alpha. Our master branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄
