### ISSUE TITLE
Title in header is clipped with --fixed-header and --fixed-drawer on mobile.

### ISSUE THREAD

**Issue by eziante** [google/material-design-lite#1313]
If you are using the fixed header and drawer example layout from http://www.getmdl.io/components/index.html#layout-section/tabs and you move the title from the drawer to the header and go into mobile view, the title gets clipped by the menu icon.

I have made a codepen example showing the error. Follow the link an active mobile mode and the bug should be visible by looking at the title and menu icon.

http://codepen.io/anon/pen/VLgpEz

**Comment by mspl13** [comment]
This is a duplicate of #1245 and #1262 and should be fixed by #1249. The fix will be part of the 1.0.3 release.

**Comment by eziante** [comment]
Do you know when 1.0.3 will be released?

**Comment by surma** [comment]
Well, according to our milestone deadline is August 15th ;) That’s a goal, not a promise, though.
