### ISSUE TITLE
[Feature Request] Allow configuration of layout--fixed-drawer breakpoint

### ISSUE THREAD

**Issue by dryror** [google/material-design-lite#1317]
Currently the layout--fixed-drawer breakpoint is hard coded at 1024px. While this is better than the previous 850px, it is still too narrow for certain applications.

It would be nice to able to set this without having to go into the MDL code to change it.

Currently the sass variable $layout-screen-size-threshold doesn't have the !default modifier to allow it to be modified. 

The breakpoint is also set in the layout.js file under MaterialLayout.prototype.Constant_.MAX_WIDTH. While it is possible to override this without touching the MDL code, it feels a bit hacky.

Adding the !default modifier to the sass variable and documenting that the js variable has to be changed as well could be a easy way to allow this option.

Just for reference, the [Material Design website](https://www.google.com/design/spec/material-design/introduction.html) uses a breakpoint of 1479px for the fixed nav drawer.

**Comment by surma** [comment]
Layout needs to be brought in line in general with the [adaptive UI](https://www.google.com/design/spec/layout/adaptive-ui.html) break points. Thanks for the issue :)

**Comment by patrick-jones** [comment]
I want to chime in that this should definitely be configurable, not just raised from 1024. The spec doesn't mandate that everyone makes the drawer permanent at a specific width -- it [*recommends*](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior) it as the default for desktop. Elsewhere, the spec emphasizes that ["your app's structure should be influenced by the content and tasks you want to show your users"](https://www.google.com/design/spec/patterns/app-structure.html). For some content-focused apps, a permanent drawer would be an unwelcome waste of space.

**Comment by traviskaufman** [comment]
closing; superseded by #4476 . Because the drawer will be broken out of an overarching "layout" component, it will no longer make assumptions about when it should be fixed vs. not. 

We are still in the very early stages of v2 and are currently working towards an alpha. Our master branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄
