### ISSUE TITLE
Textfield placeholder label isn't updated when programmatically setting value

### ISSUE THREAD

**Issue by mgiuca** [google/material-design-lite#1319]
When an MDL textfield is assigned a value using the `value` attribute, like this:

    textfield.value = 'Some text';

the placeholder label is not updated.

If the value was the empty string, and a non-empty string is assigned, the placeholder is not removed:

![mdl-textfield-setvalue](https://cloud.githubusercontent.com/assets/228433/9106807/40c86c42-3c66-11e5-873d-2c2bc0a7ac9e.png)

I will attach a full reproduction.

**Comment by mgiuca** [comment]
OK, apparently GitHub doesn't allow attachments. Here is a pastebin of the repro page:

http://pastebin.com/2pyMB5UZ

**Comment by hebbet** [comment]
can you provide your example as a [jsfiddle](https://jsfiddle.net/)?

**Comment by mgiuca** [comment]
Certainly: https://jsfiddle.net/jmvcy07L/

**Comment by surma** [comment]
See #1287

**Comment by mgiuca** [comment]
Thanks @surma. The fixed fiddle: https://jsfiddle.net/cks15p5w/
