### ISSUE TITLE
Variable to customize vendor prefix?

### ISSUE THREAD

**Issue by davidbwaters** [google/material-design-lite#1321]
Why not use a variable to customize or remove the 'mdl-' prefix for those of us who aren't using anything that conflicts would prefer something else?  An option for shorter, prettier class names for those of us who want to customize or integrate would be awesome.

**Comment by Garbee** [comment]
This is just an inherent design decision. Changing the prefix also involves modifying the JS which means running that through a template engine as well.

**Comment by Garbee** [comment]
A way around this is to use `@extend` from Scss to make your own shorter classnames. It is the recommended way to handle this.
