### ISSUE TITLE
Label on radio button example wraps

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1322]
In the [toggles documentation](http://www.getmdl.io/components/index.html#toggles-section) the label on the radio button example is wrapping to the next line:

![image](https://cloud.githubusercontent.com/assets/197231/9129390/88260d2e-3d1a-11e5-9fe4-4661581a54f4.png)

I'm unsure why this is happening, the following is a fix but feels wrong:
```
.mdl-radio__label {
  white-space: nowrap;
}
```

**Comment by SeanBannister** [comment]
I should mention, this appears to just be an issue in the documentation and not a larger issue. It works fine in the codepen.

**Comment by sgomes** [comment]
This is happening because of our overly aggressive table sizing in the docs. I'll make this `Option&nbsp;1` for now :-/
