### ISSUE TITLE
Change the mdl custom build cdn link to something easily copy-able?

### ISSUE THREAD

**Issue by biwin** [google/material-design-lite#1326]
The cutom build cdn link is much hard to copy as it need mouse drag,
double click selects more content than the needed link,

can you guys make it a copy-able text field or some thing that functions as seen on http://www.bootstrapcdn.com or as click to copy as on http://cdnjs.com/libraries/font-awesome ?

**Comment by surma** [comment]
I never thought about people just wanting to copy the URL. We’ll try and come up with something :)

**Comment by biwin** [comment]
There ain't any download button there and yes, its said
> CSS hosted on our CDN (17.6kB gzipped):

some one has to assume thats a cdn link? or whats that link is for??

http://www.getmdl.io/customize/index.html

**Comment by biwin** [comment]
PS. There is a download button in the middle, discovered accidentally.

**Comment by surma** [comment]
We definitely do have a download button :smile: 
<img width="1105" alt="screenshot 2015-08-07 13 14 47 copy" src="https://cloud.githubusercontent.com/assets/234957/9169855/eb641808-3f55-11e5-8eb0-6331ed613f79.png">

But you are right, the link should be easily selectable.
