### ISSUE TITLE
How to programatically collapse an expandable text-field?

### ISSUE THREAD

**Issue by Blechhirn** [google/material-design-lite#1330]
I have a search box inside a form. On submit, I would like to collapse it. Any pointers how to do so?

So far I tried:
a) to set value to the empty string / null.
b) call MaterialTextfield's various check* methods.
c) call blur on the input field
d) call focus on something else
e) all of the above in combination

**Comment by surma** [comment]
It should be sufficient to add the `.is-focused` class to the `div.mdl-textfield`. Can you check if that solves your problem?

**Comment by Blechhirn** [comment]
No, that did not yield anything. I will put together a sample of what I am trying to do later,

**Comment by surma** [comment]
@Blechhirn Yes please :)

**Comment by Blechhirn** [comment]
I am unable to reproduce this standalone, so I am closing this one. Probably the mixture of MDL and RiotJS that I am using is messing up some of the key events.

**Comment by RobertoAlvarezCeballos** [comment]
Hi,

Sorry to pick up this topic again but I'm having the same issue. Does anyone know if there is a way to collapse the textfield from code?

**Comment by mm18hun** [comment]
Hi,
The `.is-focused` and `.is-dirty` classes together keeps `div.mdl-textfield` opened.
