### ISSUE TITLE
MDL + AngularJS + ngRoute (animation not work inside ng-view)

### ISSUE THREAD

**Issue by Shyam-Chen** [google/material-design-lite#1332]
Code: http://codepen.io/Shyam-Chen/pen/vObqQO

**Comment by surma** [comment]
First of all: What animation is not working? The issue like that is rather unspecific, unfortunately.

In any case, MDL is focused at static content sites for now. We don’t support Angular directly. People on StackOverflow have made it work, however. As the issue you are encountering is most likely related to Angular and not MDL at its core, I’ll close this. Please use the `material-design-lite` tag on StackOverflow for support :)

**Comment by kristino-web** [comment]
Our looking for that answer poque was not able to solve CDM and Angle .
Thank you for answering this question

**Comment by Shyam-Chen** [comment]
I have resolved.
![example code](http://codepen.io/Shyam-Chen/pen/oXOrQQ)
