### ISSUE TITLE
"Invalid line break" error on build

### ISSUE THREAD

**Issue by solsend2l** [google/material-design-lite#1334]
Can't get the guild to work. On my Windows 7 machine, running `gulp all`:

```
(many tests pass)
...
[11:54:26] Finished 'styles' after 2.21 s
[11:54:26] Starting 'jscs'...
[11:54:27] Starting 'jshint'...
[11:54:28] Finished 'jshint' after 1.21 s

events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: ←[1mInvalid line break←[22m at ←[32mmdlComponentHandler.js←[39m :
 ←[90m    1 |←[39m/**
←[90m-----------^←[39m
 ←[90m    2 |←[39m * @license
 ←[90m    3 |←[39m * Copyright 2015 Google Inc. All Rights Reserved.

←[1mInvalid line break←[22m at ←[32manimation\demo.js←[39m :
 ←[90m    1 |←[39m/**
←[90m-----------^←[39m
 ←[90m    2 |←[39m * @license
 ←[90m    3 |←[39m * Copyright 2015 Google Inc. All Rights Reserved.
...
```

Also, my `.gitconfig` is set to `autocrlf = true`

**Comment by surma** [comment]
Please see #1299. I’m closing this. If the issue persist, please re-open :)

**Comment by solsend2l** [comment]
Nope - after running [the commands](https://github.com/google/material-design-lite/issues/1299#issuecomment-127661456), I get the same result. :disappointed:

**Comment by surma** [comment]
Ah, my bad, that answer only contains part of the actual solution (the rest being hidden in a link further up).

Take a look at [this section from the README](https://github.com/google/material-design-lite#download--clone). You need to change 2 git config variables.

**Comment by solsend2l** [comment]
That works, ty! :smile:
