### ISSUE TITLE
Different @import in _variables.scss

### ISSUE THREAD

**Issue by veged** [google/material-design-lite#1345]
Is here any reason to make different style imports in https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L70:
```sass
@import "_color-definitions";
@import "functions";
```

Seems like better to have consistently underscored or not. BTW in `src/*/_*.scss` only variant without underscore is used (`@import "../variables";` and `@import "../mixins";`).

Maybe it's very minor issue since doesn't affect final result, but it's sloppy inconsistent.

**Comment by sgomes** [comment]
Nope, so specific reason behind this, just a typo. I'll get that sorted, thanks @veged!

**Comment by veged** [comment]
thnx! :+1:



-- 
  Сергей Бережной
