### ISSUE TITLE
Checkbox Font Size

### ISSUE THREAD

**Issue by jhawlwut** [google/material-design-lite#1347]
Checkbox font size should be inherited with a variable defined globally. I'm not sure if this occurs in other element definitions, but _checkbox.scss has the following:
```css
.mdl-checkbox__label {
...
  font-size: 16px;
```

**Comment by sgomes** [comment]
Thanks, @jhawlwut, good catch!

**Comment by jhawlwut** [comment]
Let me know if you need me to do a pull request, otherwise thanks for the quick response

**Comment by sgomes** [comment]
No worries, I'm already halfway through one myself :) Currently looking for other components with the same issue.
