### ISSUE TITLE
Github wiki's are not easy to contribute to

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1353]
I was hoping to contribute to the [wiki](https://github.com/google/material-design-lite/wiki). After a bit of a search I [found](http://stackoverflow.com/questions/7197937/on-github-can-i-fork-just-a-wiki) you can't fork github wiki's so there isn't an easy way to contribute.

Would it make sense to move the wiki to a page on the microsite called "Documentation"? It'd be handy to allow people to contribute and also nice to keep everything in one place.

**Comment by mspl13** [comment]
What about cloning the wiki with `git clone https://github.com/google/material-design-lite.wiki.git`, make the changes you want to and commit it then?

**Comment by surma** [comment]
@mspl13 He still wouldn’t have permissions to push and AFAIK there’s no way to PR a change to the wiki.

@SeanBannister The wiki is really a 2nd class citizen at the moment. We are using it more as an info dump than actual documentation. If you find mistakes that you think are worth fixing, just open up an issue for now.

**Comment by Garbee** [comment]
As Surma said, the wiki is a dump currently. Eventually what is there will get moved into the site itself and expanded upon.

We can't open up the wiki since every submission needs a verified CLA signed.

**Comment by SeanBannister** [comment]
It was more that I wanted to write a few guides, like "how to create a component" its stuff I'm figuring out at the moment so figured I may as well document it as I go. They often say the best people to write documentation is those who are learning because once you know it you "don't know" what you "don't know" :)
