### ISSUE TITLE
Ripple effect not working properly for double-clicks.

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#1354]
I recorded this video here to demonstrate: https://youtu.be/Flbp-1WtKqo

Not sure if this is the intended behavior but I think some clean-up is missing when a second click is registered before the first ripple effect ends.

**Comment by surma** [comment]
@Zodiase Thanks for the detailed report. Definitely a bug. We’ll look into it.

**Comment by traviskaufman** [comment]
ref. #4467

**Comment by sgomes** [comment]
This issue appears to be fixed now.
