### ISSUE TITLE
Tabs should allow deep linkining (by changing the URL fragment identifier)

### ISSUE THREAD

**Issue by steren** [google/material-design-lite#1359]
Open the [demo template 'text-heavy'](http://www.getmdl.io/templates/text-only/index.html) ([sources](https://github.com/google/material-design-lite/tree/master/templates/text-only)).
See that when clicking the tabs, the URL does not change. This has for consequence that you cannot deep link to a given tab.

Tabs are using `id="a-tab"` to identify tabs to open. I would expect that when clicking on such tab, it also appends `#a-tab` to the URL. And that when loading an URL with such fragment, Material Design Lite would open the corresponding tab if available.

**Comment by sgomes** [comment]
I don't see a problem with adding this functionality as an option to tabs, but I'm reluctant to make this the default, even with an eventual v2. Having a component modify the page URL by default would probably come as a surprise to many developers.

@surma What do you think?

**Comment by surma** [comment]
I have to agree that at the very beginning I expected the behavior @steren is describing. But I have come to the conclusion that it is rather counter-productive for a library to behave that way as it makes integration with other tools potentially hard or even impossible.

I’d like to see tabs supporting this (maybe we can even go so far and be completely JS free by using `:target`?), but, as you said, it should not be the default behavior but be explicitly enabled with a class(?).

**Comment by monteslu** [comment]
As it stands I'm not able use the tabs along with react-router.  Would love to be able to use just the styling with perhaps a class to disable the current behavior.

**Comment by Garbee** [comment]
Just don't use our tab js code and write your own logic.

**Comment by janpieterz** [comment]
@monteslu there is actually a way to use it with react-router! I've got it currently implemented (used https://github.com/google/material-design-lite/issues/1165 and https://github.com/google/material-design-lite/issues/1665). 

This would be amazing though! I'd like to be ably to log to Google Analytics when someone hits a tab, and without a url change this seems rather tedious.

**Comment by traviskaufman** [comment]
Closing as we will be addressing this in our v2 tabs - #4481 

We are still in the very early stages of v2 and are currently working towards an alpha. Our master branch is where all v2 work is happening if you are interested in keeping up with its progress. 😄
