### ISSUE TITLE
_resets.scss: @import paths are longer than needed

### ISSUE THREAD

**Issue by veged** [google/material-design-lite#1363]
In https://github.com/google/material-design-lite/blob/master/src/resets/_resets.scss#L17 there are two `@import`'s:
```css
@import "../resets/h5bp";
@import "../resets/mobile";
```
They can be written without `../resets/`. It will be better to avoid lookups to non-current folder (so solid folder can be moved and/or renamed).

**Comment by sgomes** [comment]
Looks like some legacy code that predates the current directory structure. Nice catch, @veged!
