### ISSUE TITLE
CSS selectors specific to the microsite are being distributed in material.min.css 

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1366]
If you look at [styleguide.scss](https://github.com/google/material-design-lite/blob/master/src/styleguide.scss) there's a number of styles that appear to be specific to the microsite. However this file is part of the SCSS build process and therefore these styles are being distributed in material.min.css

**Comment by sgomes** [comment]
Good catch, @SeanBannister, looks like we have something wrong in our build process. The task that generates `material.min.css` should be using `material-design-lite.scss` as the source, not `styleguide.scss`.

@surma Could you take a look at this?

**Comment by surma** [comment]
Oh boy. How did this happen? Thanks @SeanBannister.
