### ISSUE TITLE
No cursor/mouse pointer on the sliders

### ISSUE THREAD

**Issue by mustafa-x** [google/material-design-lite#1370]
From a usability point of view if the cursor changed state to pointer to indicate that the user can slide this. 
This is the link to the sliders I am thinking of. 
http://www.getmdl.io/components/index.html#sliders-section

This is the CSS needed. quite small. 

.mdl-slider {
/* Exisint styles */
    max-width: 260px;
    width: 30vw;

    cursor: pointer;
}

**Comment by sgomes** [comment]
This is a very good point, and I agree we should add that in. I swear we had that at some point, but I could be wrong.

Thanks for the feedback, @mustafa-x!

**Comment by mustafa-x** [comment]
No problem, I dont mind running through things and testing things out. ITs pretty amazing so far though so I doubt id find anything else :)
