### ISSUE TITLE
MDL Icons not displaying properly in Android WebView

### ISSUE THREAD

**Issue by Andy561** [google/material-design-lite#1375]
I tried to see if there may have been someone who posted something similar, but I couldn't find anything so I figured I would mention.

We have a client running a trial application, therefore I don't have direct access to test on the older versions of Android. However, in a WebView in Android 4.1 icons do not display. In Android 4.4, the icons display however some of them are incorrect. Not sure if this may have to do with CSS/HTML/JS support or not but I thought I would bring this issue to attention.

ANDROID 4.1
![4 1](https://cloud.githubusercontent.com/assets/13260499/9225465/99ba5610-40d7-11e5-9426-9d8c027af997.jpg)

ANDROID 4.4
![4 4](https://cloud.githubusercontent.com/assets/13260499/9225463/941e5b8e-40d7-11e5-97a0-e149b60a745b.jpg)

ANDROID 5.0 / iOS / Chrome (desktop) /Firefox (desktop) / How it's supposed to look
![img_0113 1](https://cloud.githubusercontent.com/assets/13260499/9225460/8ed58616-40d7-11e5-9247-8097d9c606b5.PNG)

**Comment by surma** [comment]
@Andy561 Thanks for the bug report. We’ll try to reproduce.

In the meantime: Would you mind adding screenshots to the issue itself (you can drag'n'drop into the textfield!)? I can’t open the links you have provided (access denied).

**Comment by Andy561** [comment]
@surma Whoops, sorry about that. Fixed the images, sorry the top two are kinda bad, but its enough to see the issue.

**Comment by sgomes** [comment]
Adding the 1.0.3 milestone to see if we can get a fix by then.

**Comment by surma** [comment]
Hey @Andy561, I finally got all my emulators running :computer: 

As it turns out, Android 4.1 WebView does not support ligatures at all. Android 4.4 does, but doesn’t know what to do if one ligature is a prefix of another, which is why your `keyboard_backspace` icon turns into a literal `keyboard`.

There’s nothing we can do about this, obviously, but there is a workaround: Code points :point_up:
Go to the [official icon font website](https://www.google.com/design/icons), lookup the icons you are using and use the code point instead of the ligatures, like `&#xE317;` for `keyboard_backspace`.
![screenshot 2015-08-13 15 50 18](https://cloud.githubusercontent.com/assets/234957/9252939/1039db34-41d3-11e5-84af-e4b0b055eafa.png)

Hope this helps :)

**Comment by Manduro** [comment]
http://google.github.io/material-design-icons/ mentions support for ligatures on the Android browser from version 3, but as mentioned here it only works correctly on Android > 4.4, right?

**Comment by surma** [comment]
Hm,... you are right. Material Design Icons is claiming that they do indeed support Android Browser 3. Maybe I did something wrong? According to [caniuse.com](http://caniuse.com/#feat=kerning-pairs-ligatures), there’s a bug with all Android Browsers < 4.4 which they describe as

> Partial support in Android browser versions is due to a serious bug where text-rendering: optimizeLegibility causes custom web fonts to not render.

**Comment by Manduro** [comment]
Yes, I have looked into that. It causes problems rendering, but as far as I could tell it doesn't have to do with ligatures, which are just not supported. 

I have spent a few hours trying to get it to work on Android < 4.4, but in the end I have rewritten all icons using html entities.

**Comment by Zuurkern** [comment]
How am I supposed to replace the hamburger menu icon ligature by a code point when it is generated automatically with JS? This is the most important icon of all and now it looks like it is doomed to never work in Android browsers :(

**Comment by Garbee** [comment]
It is already fixed for 1.1 @Zuurkern. We did that update internally.

The only way to fix in in 1.0.x is to run JS after-layout upgrade that changes the innerHTML of the icon's div.

**Comment by pathakNishant** [comment]
Hi,

Thanks for the material design library, I am hitting similar issue where material switch is not showing properly in android API level 22. Please check image below:

<img width="279" alt="screen shot 2016-06-29 at 7 49 33 pm" src="https://cloud.githubusercontent.com/assets/12965010/16455661/c9c8146a-3e32-11e6-8783-c0314dcebc0f.png">

**Comment by Garbee** [comment]
@pathakNishant Please file a new issue specifically for that issue.

**Comment by pathakNishant** [comment]
@Garbee Issue created: https://github.com/google/material-design-lite/issues/4512

**Comment by creativeprogramming** [comment]
This can help: https://github.com/google/material-design-icons/blob/master/iconfont/codepoints

**Comment by creativeprogramming** [comment]
Anyway, sure that such ligature coolness is the more performant way to implement material-icons even on modern browser, why not offering also some css helper classnames (like font-awesome) with content attribute? That may help for who wants to use an human-readable code but also ensure a better browser support...

**Comment by Garbee** [comment]
@creativeprogramming This issue tracker is about Material Design Lite only. That icon customizer and what is provided are handled over in the Material Design Icons repository. Please file an issue there with your request for the proper team to triage and take any action if necessary.

Thank you.

**Comment by creativeprogramming** [comment]
@Garbee,  I reasoned a bit, had new issues, and anyway tought that's better to keep the request to you

I repeat my point: are you sure that such ligature technique is the most good way to implement your icons?

Even from semantic web point of view, having those 'keywords' as html 'content' and not a CSS class name is wrong and not convenient.

For instance one issue I'm having is that I'm having icon name treated as text by many html parsers for generating preview (even by Google sometimes) 

Why reinventing the wheel? Why you don't use a css class for icons? You master this cool technique but something simpler is better,  please consider adding also some simple CSS classes for helping developers using your icons, like fa and other frameworks

Another point of that is that IDEs usually do autocompletion for CSS class names but not for html content
