### ISSUE TITLE
Is there a way to remove hamburger icon from screen ?

### ISSUE THREAD

**Issue by foo-baar** [google/material-design-lite#1379]
I am using the dashboard template, but for one view I need to hide the drawer (which I did by removing  "mdl-layout--fixed-drawer" from '.demo-layout') using Jquery, but I am not able to remove the hamburger icon from the header as its appended dynamically in to the DOM.

Is there a way to do it ?

**Comment by surma** [comment]
Sounds like this 11 hours old issue #1368 might be the solution you are looking for :smile: 

If not, please re-open :)

**Comment by foo-baar** [comment]
@surma: Looks like are asking about removing the spaces for hamburger not the actual icon, I need to remove the icon itself and #1368 has too many reference to confuse the reader, please share if there is an easy fix.

**Comment by surma** [comment]
How about this:

```CSS
.mdl-layout .mdl-layout__drawer-button {
  display: none;
}
```

**Comment by foo-baar** [comment]
:) :+1:
