### ISSUE TITLE
Scrollable tabs really scrollable?

### ISSUE THREAD

**Issue by cliffordp** [google/material-design-lite#1380]
I forked the Scrollable Tabs demo from http://www.getmdl.io/components/index.html#layout-section/layout simply attempting to add content "down the page": http://codepen.io/cliffordp/pen/gpyMdb

From the name, I assumed the Scrollable Tabs would have been like Bootstrap's Scrollspy: http://getbootstrap.com/javascript/#scrollspy

Is it not working (my codepen link) or does the name maybe need some context / documentation?

tyvm for the help.

**Comment by surma** [comment]
Scrollable tabs are called scrollable because [you can scroll the tabs](http://codepen.io/surma/pen/RPOREb) :D

We don’t have any functionality equivalent to scrollspy, which is also related to the fact that we actually switch out the content when switching to a different tab.

**Comment by cliffordp** [comment]
AH!! lol

*Horizontally*-scrollable
tyvm!

I like Scrollspy so you can add that functionality just for me in the future if you want, lol :)

**Comment by tleunen** [comment]
This scrollable demo is really not usable :D 
Would probably be better to scroll the size of the next tab instead of a fixed value :/

**Comment by cliffordp** [comment]
I noticed your codepen link only has scrollable tabs if the browser is 1025px or wider. Shouldn't scrollable tabs work on all browser widths?

**Comment by surma** [comment]
I can scroll on smaller screen sizes just as well. The buttons disappear, because we can assume that you are on mobile and have a touch interface.

**Comment by cliffordp** [comment]
Gotcha. Thanks for the insights.

**Comment by johngonzalez** [comment]
Would be good add more tabs in documentation for most clarity.
http://www.getmdl.io/components/index.html#layout-section.
How here: http://codepen.io/surma/pen/RPOREb
