### ISSUE TITLE
Using Navigation Layouts without <header> and especially <main>?

### ISSUE THREAD

**Issue by cliffordp** [google/material-design-lite#1381]
http://www.getmdl.io/components/index.html#layout-section/layout -> Configuration Options states `<main class="mdl-layout__content">` is required, and the tabbed Navs require stuff inside `<main>`.

What if I want to use a Nav inside `<main>` -- like Bootstrap Scrollspy (linked to in https://github.com/google/material-design-lite/issues/1380)

http://www.w3schools.com/tags/tag_main.asp says, "There must not be more than one <main> element in a document. The <main> element must NOT be a descendant of an <article>, <aside>, <footer>, <header>, or <nav> element."

I looked at the CSS and it seems it's not actually tied to `<main>` element, just the `mdl-layout__content` class (i.e. `.mdl-layout__content` vs `main.mdl-layout__content`).
Same for `<header>` -- why not just use `<div>`?

http://www.w3schools.com/tags/tag_header.asp says, "You can have several <header> elements in one document... [but one] cannot be placed within a <footer>, <address> or another <header> element."

**So, just wondering if it's *wrong* to use `<div>` or something other than `<header>` and especially `<main>`.** Thanks for any help/advice.

**Comment by sgomes** [comment]
Nope, there's absolutely no requirement to use `<main>` or `<header>`; you're free to use `<div>`! Our examples do because we feel it's more semantically meaningful, but it's not in any way needed.

If there's any specific bit of the docs that you think is misleading in their regard, let me know and I'll take a look!

**Comment by cliffordp** [comment]
Good to know.

When Configuration Options says "Required on main element" or "Required on ___ element", to me that reads that "main" or "___" element is required, especially when reiterated in Basic Use and Examples. I'd generally suggest adding a note somewhere (even an asterisk if necessary) that communicates -- assuming an asterisk -- "this class is required but can be applied to any comparable element"

Anyway, I did try the `<div>` for the Fixed Header, Collapsible Drawer and the Scrolling Header. Because of `.mdl-layout__container` absolute positioning, width/height 100%, and `.mdl-layout__obfuscator` empty area to put the Drawer back in its place by clicking outside the Drawer... placing one of these Navigation Layouts in the midst of other content doesn't really work...

So it's probably really only suited for 1 nav per page and to be outside of `<main>` and then the documentation would be accurate as-is...

... something about this just doesn't feel like it's as useful as it should be. Am I missing something?

tyvm for the help.

**Comment by Garbee** [comment]
The layout and navigation follow Material Design specs. If you are having a problem with implementing something, then please use StackOverflow for support.

**Comment by cliffordp** [comment]
Good answer. Thanks.

**Comment by sgomes** [comment]
@cliffordp Thanks for pointing out that bits that were less clear, I'll see if I can change the wording a bit there to make it less confusing. As for your use case, you're right, those elements weren't designed to be used more than once in the page. You may have some luck getting them to do that, but in general it may be easier to look for other components you can use to fulfil the same goals.

We plan on making these elements more independent in a future v2, so hopefully at that point it'll be easier to reuse them in several contexts.

**Comment by cliffordp** [comment]
:)
