### ISSUE TITLE
MDL not applied to elements loaded through AJAX

### ISSUE THREAD

**Issue by ArielAbreu** [google/material-design-lite#1393]
When using `$('#element').load('some-page.html')`, MDL events are not applied to any MDL elements on the requested page (style works fine, though). A simple fix would be http://stackoverflow.com/a/23247146, simply attach the event to the body and test for the class, right?

**Comment by Garbee** [comment]
This is out of the scope of what MDL supplies. Please use StackOverflow for support in building your web sites.

**Comment by ArielAbreu** [comment]
Ok, but thanks anyway!

**Comment by tleunen** [comment]
Not sure what you use to load your page, but you should be able to set a callback and manually upgrade the elements in the new page.

**Comment by ArielAbreu** [comment]
I finally had the time to look through the source and I found a solution, call `componentHandler.upgradeAllRegistered()` in the AJAX callback, simple as that!

**Comment by maaadmin** [comment]
Thank you for finding this. 🥇 for you.
