### ISSUE TITLE
Tooltip follows mouse pointer when scrolling page

### ISSUE THREAD

**Issue by nxrighthere** [google/material-design-lite#1398]
http://postimg.org/image/b9p8crls5/full/

**Comment by surma** [comment]
@nxrighthere Can you tell me which browser and OS  version you are using?

**Comment by nxrighthere** [comment]
Firefox 41.0b1, Windows 10 Build 10240.

**Comment by surma** [comment]
[Confirmed](http://youtu.be/94AOz3HaReg). Tooltip disappears in Firefox *after* scrolling has stopped. Maybe we need to add a `scroll` handler.

**Comment by karanjthakkar** [comment]
@surma Can you see if #4370 seems like a good fix for this?

**Comment by Garbee** [comment]
Commit 5065fe8d41c2bb233956f240ff7620f59ba2c00a just went into `mdl-1.1` with a fix for this from @karanjthakkar. I confirmed that it is works on Ubuntu FF 46.0.1.

Should be out in 1.1.4.
