### ISSUE TITLE
Icons in navigation drawer not aligned with text

### ISSUE THREAD

**Issue by pokonski** [google/material-design-lite#1400]
Hi!

I noticed that icons do not get properly aligned with text inside navigation links:

![material design lite](https://cloud.githubusercontent.com/assets/135402/9293552/9a024ef6-442f-11e5-9c3b-093069ecdf65.png)

This looks correctly on demo pages ( http://www.getmdl.io/templates/dashboard/index.html ), but they add some `demo-*` classes which do not exist in MDL itself. 

Are icons inside nav links supported or is this a shortcut someone took while preparing demo in the above link?

**Comment by surma** [comment]
Related: #1068.

**Comment by Hunsin** [comment]
Simply change `.mdl-layout__drawer .mdl-navigation .mdl-navigation__link {display: block}` to `display: flex`
But I'm not sure if it will be other side effects.

**Comment by surma** [comment]
In the last meeting everybody was pretty sure we fixed that already, turn’s out we didn’t, @tleunen did :smile: (in #1456)

Fix is already in master, will roll out with 1.1
