### ISSUE TITLE
Add AJAX info to wiki

### ISSUE THREAD

**Issue by ArielAbreu** [google/material-design-lite#1401]
I recently opened an issue on loading elements through AJAX (#1393). I then got an email from someone that saw the issue and had the same problem, asking me how I solved this. After the issue was closed, I found a solution, call `componentHandler.upgradeAllRegistered()` in the AJAX callback. Maybe something like:
```
When loading MDL elements through AJAX, be sure to call componentHandler.upgradeAllRegistered() in the callback.
```
could be added to the component handler wiki.
I can perfectly understand if this issue closed and nothing is done about this, I just think it'd be nice to have that kind of info in the wiki.

**Comment by Garbee** [comment]
This is going to be handled with the addition of JS docs right  into the primary site. The wiki is some pre-conceived ideas that have yet to be  fully fleshed out into a full developer story.
