### ISSUE TITLE
Icon buttons in datatable are misaligned

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#1402]
Rows in a datatable are 48px height, but because it's hardcoded like that, when we put some other things than just text, the alignment is therefore wrong.

Here's an example with icons:
<img width="220" alt="screen shot 2015-08-16 at 5 08 46 pm" src="https://cloud.githubusercontent.com/assets/1972567/9295369/c625f8b6-4439-11e5-98f3-9838d8ce8e4c.png">

The spec has an example with icons:
<img width="1197" alt="screen shot 2015-08-16 at 5 12 00 pm" src="https://cloud.githubusercontent.com/assets/1972567/9295375/0511706e-443a-11e5-81c0-48b7746a291c.png">

**Comment by Garbee** [comment]
Can we get a codpen example that reproduces the issue please? Seeing the exact markup structure being used may help find a robust solution.

**Comment by tleunen** [comment]
Sorry, seems I forgot to comment.
Creating an example was not hard. Here's one: http://codepen.io/anon/pen/mVqrVR

**Comment by Garbee** [comment]
So quick possible patch here:

* Change `.mdl-data-table td .mdl-data-table__select` to no left rule. Vertical-align middle. And no absolute position.
* Change `.mdl-data-table td` to vertical-align middle and padding to also have 12px on the bottom.
* Change header checkbox to have no extra rules.

See [this demo](http://codepen.io/Garbee/pen/NxwpML?editors=010) for output.

@sgomes and @surma Seem like something we can drop in real fast? Not sure about direct spec alignment, but it gets things functional.

Or should we just hold off and handle this in 2.x?

**Comment by surma** [comment]
@Garbee My vote goes to MDL 1.1

**Comment by Garbee** [comment]
Alrighty, I'll work on fixing up a PR for this real quick.

FTR there are BC concerns changing this stuff so heavily... but... ugh, whatever.
