### ISSUE TITLE
Icons don't show in Vivaldi Browser

### ISSUE THREAD

**Issue by ryanmurakami** [google/material-design-lite#1404]
Icons don't show in the Vivaldi Browser - 1.0.219.53 (Developer Build) (64-bit).

Screenshot of getmdl.io page in browser:
<img width="1369" alt="screen shot 2015-08-16 at 9 01 37 pm" src="https://cloud.githubusercontent.com/assets/767105/9297833/1d43cd9c-445a-11e5-9de6-c01ccd719de1.png">

**Comment by surma** [comment]
As you can tell, we don’t support Vivaldi right now. Out of curiosity: Could try out [this fix](https://github.com/google/material-design-lite/issues/1375#issuecomment-130721748) and tell me if it changes anything?

**Comment by ryanmurakami** [comment]
@surma Thanks for the response! Using the ligature actually works great in Vivaldi! I'll use that for now. Thanks a ton for your help!

**Comment by surma** [comment]
Glad to hear :)
