### ISSUE TITLE
Another component loader system?

### ISSUE THREAD

**Issue by Jabher** [google/material-design-lite#1415]
For now I see that component loader is loading everything only on page load, with manual load interface exposed.
I think that experience of working with mdl can be improved significantly by moving component management (load, unload and so on) to framework-level with no manual actions from developers to perform on DOM alteration.

I've made an extremely tiny library named [corner.js](https://github.com/Jabher/cornerjs) about a year ago and only now (during working with mdl) I understand that looks like it super-fits any frontend framework like mdl, or bootstrap, or foundation.

It relies upon single-callbacked MutationObserver (including polyfill by Polymer for ie9-10 and one-time onload trigger for ie8) and is able to trigger specific callbacks on class, attribute or tag add, remove or alter, is able to capture attribute change and so on.
I'm not quite sure about performance of MutationObserver on mobiles but on desktop browsers it is showing very good results.

mdlComponentHandler is heavily expecting manual updates, which is not always a good option, as far as it is expected to be used in the simpliest way possible, so "magical" bindings looks quite good option. It can be something like Foundation "reflow" but just working.

Why it's useful?
- single-page applications
- framework abstractions (no need to make special component bindings)
- mostly anything else as far as we're bringing API directly to HTML instead of making some JS abstraction layer to handle components manually on any DOM change.

I can adapt my library to make its interface to be as close to componentHandler if it will be useful.

**Comment by Garbee** [comment]
So, your library requires a polyfill for MutationObserver? If so, that is an instant no-go since we are not requiring any of them to use MDL.

**Comment by Jabher** [comment]
Yes, but it's bundled for now. IE 9-10 have mutation events instead of
mutationObserver, polyfill is just unifying the interface. It can actually
be even rewritten to rely on this events directly instead of using the
polyfill.

**Comment by Garbee** [comment]
Closing on up since the recommended replacement requires a polyfill for support which we will not require for our users.

You are free to fork MDL and setup your own JavaScript structure. Or even make your own version requiring this package for the styles only.
