### ISSUE TITLE
Hyphen is not displayed

### ISSUE THREAD

**Issue by ckashby** [google/material-design-lite#1417]
mdl 1.0.2

Hyphens are not displayed in the Blog template and the text-only template.

**Comment by Garbee** [comment]
Can you provide an example please? They seem to be working here in the templates just fine.

**Comment by ckashby** [comment]
Close the issue.

It is working now.

Cheers



Clay Kalei Ashby
clay.ashby@gmail.com

**Comment by surma** [comment]
Glad to hear :)
