### ISSUE TITLE
.mdl-navigation__link--current styles — color theme mismatch?

### ISSUE THREAD

**Issue by rpominov** [google/material-design-lite#1421]
Styles for current item in Layout's navigation menu seems too dark. Is this intended?

![image](https://cloud.githubusercontent.com/assets/825702/9331479/77f56df8-45c8-11e5-8295-28f30a42fd16.png)

**Comment by Garbee** [comment]
This is because we are using the light-contrast color for the background... I think I chose that based on one of the templates we were testing in, not a raw template.

**Comment by surma** [comment]
Looks fine to me on the components page. Where are you seeing this, @rpominov? (We DID just upgrade the website to 1.0.3, though, so maybe that fixed it already?)

**Comment by rpominov** [comment]
I see it on http://www.getmdl.io/components/index.html#layout-section (added class using dev tools).
Just checked, still seems broken.

**Comment by surma** [comment]
@rpominov Ah, sorry, I totally misunderstood the issue. Will investigate

**Comment by kingstenbanh** [comment]
I checked the Google Design Spec and saw that the website didn't use any background color for the current navigation link (Please see the image below). Should we remove the background color for current navigation completely or is there an alternate that MD Team would like to use?

<img width="237" alt="screen shot 2015-08-26 at 10 11 58 pm" src="https://cloud.githubusercontent.com/assets/7540669/9513066/b180f402-4c3f-11e5-8d26-1c2925f68550.png">

**Comment by Garbee** [comment]
@kingstenbanh We don't follow other example implementations. Each varies a bit and may not align with the spec. You can reference [this old comment](https://github.com/google/material-design-lite/issues/99#issuecomment-99486738) for why we are using an active state.

Since they don't specify the exact color for highlight, I'd just find a light gray in the pallet and use that.
