### ISSUE TITLE
[1.0.3] Search textfield in header broken.

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#1423]
Compare [this codepen using 1.0.3](http://codepen.io/Zodiase/full/QbRVGp/)
and [this codepen using 1.0.2](http://codepen.io/Zodiase/full/zGQJNa/)

![Comparison](http://f.cl.ly/items/2J0j142Y2832410B0K1z/MDL-textfield-1.0.3-1.0.2.png)

**Comment by tleunen** [comment]
All the textfields are broken, not just the expandable one...
http://www.getmdl.io/components/index.html#textfields-section

**Comment by Zodiase** [comment]
For the textfield in header, simply adding `background: 16px;` made it work. This line was in 1.0.2 but removed in 1.0.3.

**Comment by Zodiase** [comment]
That line was removed in d1be0391a8e6e4f12d10900eef7a2b1b376a2111. Why?

**Comment by tleunen** [comment]
`background: none` makes more sense than just using an arbitrary value. That's probably why it was removed.

**Comment by Zodiase** [comment]
@tleunen
Except `background: none` is missing. Now I wonder why that arbitrary value was used in the first place. :S

**Comment by Zodiase** [comment]
Probably should @sgomes.

**Comment by sgomes** [comment]
@tleunen is right, that's exactly why it was removed, but it had the unintended behaviour this bug describes. Thanks for reporting this, @Zodiase!

**Comment by addyosmani** [comment]
Thanks for catching this so quickly folks and sorry about the regression. Let's land a fix for this in a 1.0.4 and get it out the door asap so it doesn't cause further breakage.

**Comment by sgomes** [comment]
PRs out for both `master` and `mdl-1.0` branches.
