### ISSUE TITLE
Image path as variable

### ISSUE THREAD

**Issue by toddmbloom** [google/material-design-lite#1426]
Currently the path to images is hardcoded to /images/. Would it be possible to move this into a variable that can be overridden? My images are not in the root but this would require me to put them there or hack the scss files. 

I'm specifically talking about /images/tick.svg, found in /src/checkbox/_checkbox.scss.

**Comment by surma** [comment]
Yes, that totally makes sense.

Keep in mind, though, that SVGs are currently inlined by our gulp pipeline and you’d have to compile MDL in any case to replace the images.
