### ISSUE TITLE
Add CDN far future expires header

### ISSUE THREAD

**Issue by YousefED** [google/material-design-lite#1427]
The CSS and js files are currently served without a far future expires header. Since the files are versioned I think it would be suitable to have browsers cache them longer on the client side.

**Comment by mfonville** [comment]
Can't this be added to the 1.0.x series too?

**Comment by Garbee** [comment]
The milestone is just a target for us to look into this by. It isn't stating it will only apply to that version on the server. Odd milestone since this is a server problem, but making extra milestones to sit besides versions would get confusing.

**Comment by DanTup** [comment]
Has this become broken? PageSpeed is reporting these files as 60 minutes. Eg:

```
danny@raspberrypi:~$ curl https://code.getmdl.io/1.0.0/material.indigo-red.min.css --head
HTTP/1.1 200 OK
Last-Modified: Wed, 08 Jul 2015 08:17:55 GMT
Cache-Control: public, max-age=3600
Content-Type: text/css
Etag: W/"57e1b22c4fa4ae2e7ffab21e50e826f2"
Allow: GET, HEAD, OPTIONS
Date: Mon, 25 Apr 2016 17:57:41 GMT
Server: Google Frontend
Alt-Svc: quic=":443"; ma=2592000; v="32,31,30,29,28,27,26,25"
Transfer-Encoding: chunked
```

**Comment by mfonville** [comment]
@DanTup no it is not broken, just check with version 1.0.5 or higher

**Comment by DanTup** [comment]
Whoops, sorry! I read @Garbee's comment and thought it applied to all (and tbh, didn't realise how out of date I was; upgrading an existing site). 1.0.5 looks fine. Thanks :)
