### ISSUE TITLE
[1.0.3] Drawer not scrollable

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#1428]
Compare [this codepen using 1.0.3](http://codepen.io/Zodiase/pen/GJazqm) and [this one using 1.0.2](http://codepen.io/Zodiase/pen/XbwOdw).

Is this a bug or a design decision?

(I like it when it was scrollable.)

**Comment by Garbee** [comment]
Certainly should be scrollable.

**Comment by Garbee** [comment]
@surma Looks like commit 426395b3d22c971c1bf8339eb2074e4057aec266#diff-5640973567ec096b5b4327368615afaf is the source of this. Anything off-the-top you can think of to make this work as expected again while still fixing the original issue?

**Comment by addyosmani** [comment]
@Zodiase are you just seeing this with mousewheel events?

**Comment by Zodiase** [comment]
@addyosmani I could use the scrollbar to scroll. Mouse wheel scrolling has no effect. I don't know what else I could use. Trackpad also triggers mouse wheel scrolls I presume?

**Comment by Garbee** [comment]
I think if we just drop line 317 that may solve both issues... Testing now.

**Comment by Garbee** [comment]
Yup, dropping that listener on the drawer does it. I'll take this one to patch.

**Comment by Zodiase** [comment]
@Garbee @surma @addyosmani Just wanna say this issue still seems to be present in 1.0.4 and 1.0.5.
See [this codepen using 1.0.4](http://codepen.io/Zodiase/pen/PqMjrV) and [this one using 1.0.5](http://codepen.io/Zodiase/pen/bVgQLL). And the commit history of `src/layout/layout.js` is just confusing...

**Comment by surma** [comment]
@Zodiase I am pretty sure that this will be resolved once #1652 lands
