### ISSUE TITLE
Why mdl-js-* classes needed for bind JS functionality?

### ISSUE THREAD

**Issue by veged** [google/material-design-lite#1429]
As I can see in blocks sources (`src/`) and pages templates (`templates/`) it's possible to use only block class to find all instances and bind all JS to it. For example `menu` block — is it possible to have `mdl-menu` without `mdl-js-menu`? Why not to be more implicit here and skip `mdl-js-*` usage?

**Comment by Garbee** [comment]
This is simply so using the js provided is very explicit. You may want to use some js we provide and then your own custom scripts in place of other parts while still using our styling.

**Comment by veged** [comment]
ok, got it! thank you :+1:
