### ISSUE TITLE
Add Gitter chat

### ISSUE THREAD

**Issue by langan** [google/material-design-lite#1433]
Would it be possible to add gitter to this project?

**Comment by surma** [comment]
Is our freshly created Slack channel also acceptable to you? :)

https://webtooling.slack.com

**Comment by langan** [comment]
wow that was fast!

**Comment by chrispantazis** [comment]
Do I need an invitation to join the slack channel?

**Comment by surma** [comment]
Actually, just to confuse you guys a little. We just switched over to Gitter because of some compelling convenience features.

Feel free to join :)

**Comment by bradjonesca** [comment]
How exactly does one access the MDL Gitter room?

**Comment by surma** [comment]
You go here: https://gitter.im/google/material-design-lite :)

**Comment by bradjonesca** [comment]
Suggestion: you might want to add a gitter badge to the readme
