### ISSUE TITLE
Getting Started instructions for Bower: missing minified files

### ISSUE THREAD

**Issue by odbol** [google/material-design-lite#1443]
MDL version: 1.0.4

What steps will reproduce the problem:
1. Follow Getting Started: http://www.getmdl.io/started/#download
2. Click "Bower" option
3. Follow instructions

What is the expected result?

Minified final build files should be included in bower repo.

What happens instead of that?

````
bower_components/material-design-lite/material.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND
bower_components/material-design-lite/material.min.js Failed to load resource: net::ERR_FILE_NOT_FOUND
````

Am I supposed to build the bower component with gulp first? If so, the instructions should mention that. However, I'd prefer if the bower repo had the minified final files included so I don't have to.

**Comment by odbol** [comment]
I believe the NPM instructions will need the same treatment.

Thanks for this project! This is EXACTLY what my team needs. So much easier than trying to shove Polymer into our already written Backbone codebase...

**Comment by hdra** [comment]
Is this a somewhat recent change? My bower install from a few days ago contains the minified files I need.

But when I saw this issue and try to re-install it, the files aren't there anymore.

**Comment by tonytonyjan** [comment]
+1

**Comment by Garbee** [comment]
@surma Was this due to the mis-tag which has since been addressed? Ref: https://github.com/google/material-design-lite/pull/278#issuecomment-132951679

**Comment by surma** [comment]
Yes, this is due to the mis-tag. Bower has been fixed. npm is being worked on :) Closing this.
