### ISSUE TITLE
Version 1.0.4 on NPM doesn't contain compiled .css / .js files

### ISSUE THREAD

**Issue by rpominov** [google/material-design-lite#1448]
I import `material-design-lite/material.min.css` and `material-design-lite/material.min.js` from NPM package. It works with `1.0.3` but not with `1.0.4`.

Not sure if I doing something wrong or `1.0.4` broken on NPM.

**Comment by surma** [comment]
Can confirm, both `npm i material-design-lite` and `npm i material-design-lite@1.0.4-1` don’t contain the build files. We thought we fixed that yesterday, something must have gone wrong. Thanks for reporting, @rpominov

**Comment by kushdilip** [comment]
I was also facing the same issue. Do `bower cache clean` and then do `bower install`. It will work.

**Comment by addyosmani** [comment]
We've pushed 1.0.4-2. Please use `npm i material-design-lite@1.0.4.-2` and you'll get the version with minified files in there. We're going to try making this version explicit on the site. Sorry about the default package snaffu. Entirely my fault.

**Comment by rpominov** [comment]
Version `1.0.4-2` works fine. Thank you!

**Comment by jjalonso** [comment]
+1

**Comment by rpominov** [comment]
I wonder, why not simply publish `1.0.5` with same content as `1.0.4` but with build fixed? Or maybe there is a way to make `npm install material-design-lite` install `1.0.4-2` (currently it still installs `1.0.4` which is broken).

**Comment by jjalonso** [comment]
To be honest. Each day through more people is having errors. Is better
release it as stable quickly.

**Comment by addyosmani** [comment]
> I wonder, why not simply publish 1.0.5 with same content as 1.0.4 but with build fixed? Or maybe there is a way to make npm install material-design-lite install 1.0.4-2 (currently it still installs 1.0.4 which is broken).

1.0.5 is an in-progress version. If we bumped the npm package prematurely to releasing it, we would then have the chicken and egg problem of managing two different release versions (git vs. npm). I completely agree it sucks having to opt in to `1.0.4-2` atm, but npm doesn't offer a way to overwrite the busted 1.0.4 package. We'll hopefully aim to get out 1.0.5 soon (cc @sgomes)

**Comment by sgomes** [comment]
+1 to what @addyosmani said. I'm hoping we can release 1.0.5 either this week or the next.

**Comment by tbaeg** [comment]
+1! Definitely threw me off for a second. Thought I was going blind for a moment, haha.

**Comment by sgomes** [comment]
FYI: 1.0.5 now has a planned release date, this coming Monday 28 Sep :)

**Comment by tbaeg** [comment]
@sgomes +1 for that! :)

**Comment by addyosmani** [comment]
New release is out! https://www.npmjs.com/package/material-design-lite. It should now contain the correct end-user build files for both CSS and JS.
