### ISSUE TITLE
mousewheel disabled for drawer

### ISSUE THREAD

**Issue by smcardle** [google/material-design-lite#1451]
Hi.

What was the reasoning behind disabling the mousewheel events in the drawer ???

The reason I ask is because I am using the drawer to contain a large list and the only way to scroll is via the keyboard. The mouse wheel will not cause a scroll because the material.js file eats the mousewheel event.

Due to the way it is disable I am unable to re-enable this event without modifying the material.js file directly.

Regards

**Comment by Garbee** [comment]
1.0.4 fixed this regression.

**Comment by jakobrosenberg** [comment]
I'm having the same issue, using v1.0.4

**Comment by Garbee** [comment]
The patch wasn't merged into the 4th patch. 5 should have it.

**Comment by alvinthen** [comment]
even the template site still having this issue
http://www.getmdl.io/templates/android-dot-com/index.html
