### ISSUE TITLE
scss "&--fab" mdl - Fix

### ISSUE THREAD

**Issue by el-rotny** [google/material-design-lite#1454]
First off, I have to say that other than the error below, this repo is very much welcomed in the community.

I wanted to give you a heads up. I am getting a compiling issue with in a project that uses sass-rails and compass.

'Invalid CSS after "  &-": expected number or function, was "-fab {"' 

Heres the offending bit: https://github.com/google/material-design-lite/blob/master/src/button/_button.scss#L274

```
&--fab {
    // Bump up specificity by using [disabled] twice.
    &[disabled][disabled],
    &.mdl-button--disabled.mdl-button--disabled {
      background-color: $button-primary-color-disabled;
      color: $button-secondary-color-disabled;
      @include shadow-2dp();
    }
  }
```

When all was said and done the offending Sass wasn't supported in Sass 3.2 

```gem 'sass', '~> 3.4'
gem 'sass-rails', '< 5.1'```

New projects won't have a problem getting everything to work if they use the proper packages. We are integrating patches of mdl into our project so a warning would have been nice. 

Thanks for the work.

**Comment by Garbee** [comment]
We don't directly use Sass in our pipeline. Not sure where messages on support like this would fit in.

**Comment by sgomes** [comment]
Adding a list of dependencies to CONTRIBUTING.md somewhere sounds like a good option.

That said, as @Garbee mentioned, we don't actively support direct usage of our SASS; MDL is built with it, but our main focus is on outputting plain CSS that can be integrated into any site.

**Comment by Garbee** [comment]
So where would a note about this fit in? It doesn't fit in `CONTRIBUTING.md` since using Sass has nothing to do with contributing to the project since we use a nodejs pipeline. Also, `README.md` doesn't seem like a fit place since this is a niche case that most developers won't care for. The FAQ on the site, doesn't really seem justified since this is the only report on this.

Any where this could go that isn't the wiki wasteland?

**Comment by surma** [comment]
Hm, I think a “Out Development Stack” would fit into `README.md`. But that’s only one option.

**Comment by Garbee** [comment]
I don't see enough benefit to us documenting this tbh. The sass version in question is 3 years old. Further, we directly don't use it. When integrating in your application stack, of course you will need to keep an eye out for issues. Especially when integrating into an existing and old-ish stack.
