### ISSUE TITLE
Responsive Columns In A New Grid

### ISSUE THREAD

**Issue by juRiii** [google/material-design-lite#1457]
Hi, is it possible to have:
- 4 mdl-cell in a mdl-grid for desktop
- 2 mdl-cell in a mdl-grid for tablet
- 1 mdl-cell in a mdl-grid for phone

i dont want them to break into a new line, i want to create new "rows" instead. some ideas?

**Comment by Garbee** [comment]
Please use StackOverflow for support and usage questions.

**Comment by sgomes** [comment]
As an added note, our tag there is [material-design-lite](http://stackoverflow.com/questions/tagged/material-design-lite); using it will help you get the right folks looking at your question :)
