### ISSUE TITLE
navbar spacing

### ISSUE THREAD

**Issue by Bound3R** [google/material-design-lite#1462]
the navbar has space for `mdl-layout__drawer-button`, but if you get to delete still have an extra space by default:
```css
padding: 0 40px 0 80px;
```
eg: http://codepen.io/Bound3R/pen/waVeYO?editors=100

**Comment by sgomes** [comment]
Thanks, @Bound3R. I think it's time to revisit this now we're at 1.1.

I'm thinking of adding the `mdl-layout--no-drawer-button` and `mdl-layout--no-desktop-drawer-button` options to `mdl-layout`. Would that work for you?

**Comment by sgomes** [comment]
PR out at #1467.
