### ISSUE TITLE
Dialogs Component

### ISSUE THREAD

**Issue by jalalazimi** [google/material-design-lite#1464]
Dialogs
Dialogs inform users about critical information, require users to make decisions, or encapsulate multiple tasks within a discrete process. Use dialogs sparingly because they are interruptive in nature. Their sudden appearance forces users to stop their current task and refocus on the dialog content. Not every choice, setting, or detail warrants interruption and prominence.
Alternatives to dialogs include menus or inline expansion within the current content area. Both approaches present non-interruptive options while maintaining the current context.

https://www.google.com/design/spec/components/dialogs.html#dialogs-specs

**Comment by copynpaste** [comment]
#781
