### ISSUE TITLE
Drawer menu icon

### ISSUE THREAD

**Issue by smcardle** [google/material-design-lite#1465]
Hi people.

How can I change the icon from the standard hamburger menu item for the drawer ??

I use the draw as a chat area and would like to change it to a more specific icon for chat.

Regards

**Comment by hebbet** [comment]
That is a bugtracker. For Questions please use Stackoverflow. http://stackoverflow.com/

**Comment by Garbee** [comment]
Currently changing the icon is not supported internally. The drawer is built to follow the specification as closely as it can.
