### ISSUE TITLE
Material Icons not showing in MS Edge

### ISSUE THREAD

**Issue by dryror** [google/material-design-lite#1468]
Environment: MS Edge on Windows 10 vm from modern.ie http://dev.modern.ie/tools/vms/mac/

Material Icons are not being displayed. I was able to reproduce by visiting the preview of the blog template:
![screen shot 2015-08-25 at 9 59 38 am](https://cloud.githubusercontent.com/assets/6842818/9473684/faebd18c-4b10-11e5-913c-ba6d9c581c18.png)

EDIT: 
Confirmed not displaying when defining the icon as:
```
<i class="material-icons">add</i>
```

Does display when defining the icon as:
```
<i class="material-icons">&#xE145;</i>
```

Not sure anything can be done about this as it may be a MS Edge "feature."

**Comment by hebbet** [comment]
can't reproduce on windows 10 running on real hardware. 

test if that page works:
https://www.google.com/design/icons/

**Comment by surma** [comment]
This an open issue with the font https://github.com/google/material-design-icons/issues/179

**Comment by sgomes** [comment]
@surma Should we add the fix in https://github.com/google/material-design-icons/issues/179#issuecomment-132168462 or will we wait for this to be fixed upstream?

**Comment by surma** [comment]
@sgomes I guess fixing it on our side can do no harm. I’ll run a test shortly

**Comment by sgomes** [comment]
This is actually related to http://stackoverflow.com/questions/32061829/microsoft-edge-user-agent-from-modern-ie/32102663#32102663. Long story short, it's a bug with the modern.ie VM, which is providing the wrong useragent, and thus not getting the full CSS from Google Fonts. Switching your modern.ie VM to a non-mac version or using a real Windows 10 install should fix it.

**Comment by aseemgautam** [comment]
Console error message when this happens - 

CSS3120: No fonts available for @font-face rule
