### ISSUE TITLE
Changelog and subscribe to them

### ISSUE THREAD

**Issue by kritsky** [google/material-design-lite#1470]
Hello, how can I subscribe to changelog to update css/js on my site? And where can I see changelog

**Comment by peterblazejewicz** [comment]
> And where can I see changelog

In releases:
https://github.com/google/material-design-lite/releases

You could subscribe to repository Atom feed to get *release* tag update and go to Github page:
https://github.com/google/material-design-lite/releases.atom
![image](https://cloud.githubusercontent.com/assets/14539/9487388/705bd05a-4bd1-11e5-8235-03d992b579db.png)

The feature is sparsely documented I think:
https://help.github.com/articles/viewing-your-feeds/

**Comment by kritsky** [comment]
Thanks
