### ISSUE TITLE
Roadmap Readme

### ISSUE THREAD

**Issue by djalmaaraujo** [google/material-design-lite#1486]
Hey guys! I was reading through a bunch of feature-requests and I believe that would be very nice to see which new components we are going to add in the next releases. Maybe, we could just point in some readme or an specific roadmap document. 

I think that by doing this, people would be more excited with new releases and maybe even contribute more to find/fix bugs.

What do you guys think?

**Comment by Garbee** [comment]
We use issue [milestones](https://github.com/google/material-design-lite/milestones) to try and do this. However, like anything, assignments can be moved if things get to a crunch.

**Comment by djalmaaraujo** [comment]
I see. Ok then, don't think we need this issue anymore.
