### ISSUE TITLE
Switch component positionning

### ISSUE THREAD

**Issue by cmalard** [google/material-design-lite#1488]
Hi,

The [switch component](https://www.getmdl.io/components/index.html#toggles-section/switch) is made with absolute positionning and it seems hard to make it appears _after_ its label and not before.
Is there any simple way ?

Thanks

**Comment by surma** [comment]
The switch component should only use absolute positioning *inside* it’s scaffolding, you should be able to position it freely. Can you provide a CodePen with your attempt and maybe a mock showing the desired result?

**Comment by cmalard** [comment]
Here it is : http://codepen.io/anon/pen/rOBmxd

**Comment by surma** [comment]
Ah, I understood you completely wrong. Thanks for the codepen @cmalard.

@sgomes WDYT about `mdl-switch__label--right` or something along those lines?

**Comment by Garbee** [comment]
`mdl-switch__label--right` sgtm.

**Comment by sgomes** [comment]
Yup, makes sense.

**Comment by cmalard** [comment]
:+1:

**Comment by sgomes** [comment]
I spent some time investigating this today, and sadly it's too complicated to implement under the current component structure. We're absolutely positioning 3 separate elements, so we'd either have to move all of those to relative positioning and play around with negative margins, or we'd have to add a container somewhere in the hierarchy, to group the 3 together.

I'll move this to v2, with the goal of making sure this is possible under the new component structure.

**Comment by szimek** [comment]
Just in case somebody is looking how to solve it in the current (i.e. 1.1.x) version - I've just had this issue today and solved it with a second label. Fortunately, according to the spec one input can be associated with multiple labels. I just put a second label first, then the switch and position everything using grid and cells: http://codepen.io/szimek/pen/XdWOYM?editors=1100. There's an issue with the ripple effect though - it's not removed after clicking the label. Maybe there's a better way that doesn't break ripple effect.

**Comment by Garbee** [comment]
This issue is superseded by #4478

**Comment by amanagarwal2189** [comment]
Hi, did we arrive at any workable solution to this issue?
