### ISSUE TITLE
Markdown not rendering headings

### ISSUE THREAD

**Issue by mattbond21** [google/material-design-lite#1492]
Bug in the docs where Markdown is rendering headings.

![screen shot 2015-08-27 at 7 34 23 pm](https://cloud.githubusercontent.com/assets/870094/9537869/d1cda454-4cf2-11e5-904f-ae998477f533.png)

**Comment by mspl13** [comment]
This was already fixed in #1450 by @victorhaggqvist and should be part of the next release, I guess.

**Comment by Garbee** [comment]
Closing per previous comment.
