### ISSUE TITLE
mdl.css crash Edge

### ISSUE THREAD

**Issue by Darkham666** [google/material-design-lite#1494]
Hello, I've updated my website using MDL.
And I was surprised when I test it on Edge and see it crashed.

In fact,after research it's seems, to do like the Dashboard template (http://www.getmdl.io/templates/dashboard/index.html)

**Comment by surma** [comment]
The problem is most likely with Edge. AFAIK, Edge is not a stable product and we are not using exotic CSS in any stretch of the imagination. So you should probably bring this up with the IEdge team rather than with us.

**Comment by Garbee** [comment]
Just a quick FYI, Edge went stable with the release of Windows 10 about a month ago. I'll download a clean VM from MS and see if I can replicate the crash.

**Comment by surma** [comment]
Oh, my bad. Thought Edge was still in dev.

**Comment by surma** [comment]
The tab crashed for me as well in my VM :disappointed: Developer Tools won’t load. I still think that this should be brought up with the IEdge team. We can try to figure out a workaround, but I have no idea where to start.

**Comment by Garbee** [comment]
If you have a clean VM and it is crashing, just report upstream to Edge then. I don't know what we can really do to find the issue on our end. When IE, Chrome, FF, and Safari all work fine the problem area is clear. ;)

**Comment by Darkham666** [comment]
I've looked hard but see nothing in the css too.
I've allready make a bug report to Edge but I want you to know this bug too ;)

**Comment by surma** [comment]
@Darkham666 Can you give us a link to the bug report?

**Comment by Darkham666** [comment]
@surma unfortunately I've no link...
I've tried to contact them by the Microsoft Support but they didn't understant why I want to report a bug...
So I've used the "Send comments" tool in Edge. I hope somebody will received it ^^^"
Why they didn't have a GitHub like everybody... An issue and it's okay ! :)

I will try others ways to contact them, I keep you inform ;)

**Comment by Garbee** [comment]
You can report bugs on the [connect site](https://connect.microsoft.com/IE) as linked to from [modern.ie](http://dev.modern.ie/). That will let you get a specific link back for sharing and tracking.

**Comment by Darkham666** [comment]
@Garbee yeah I'm actually on the connect site ;)
For modern.ie I'll take a look after.

https://connect.microsoft.com/IE/feedbackdetail/view/1724368/edge-crash

**Comment by sgomes** [comment]
No longer seems to be the case.
