### ISSUE TITLE
Drawer button's icon does not display on non-ligature browser

### ISSUE THREAD

**Issue by duyluandethuong** [google/material-design-lite#1500]
The issue is similar to issue #1468 and #1489 and I am testing my site on Samsung's default browser on Galaxy Note 5 and Galaxy S6 Edge. For other parts of the web, I changed the lirature name into characters and they work fine. However, the drawer button's icon does not. When I try to change the lirature name of the drawer's button in **material.js** file, the menu's icon only render those characters, not the icon themselves. 

The constant which I changed in the **material.js** is as follow:

*MENU_ICON:"menu"*

Change to

*MENU_ICON:"&#xE5D2;"*

**Comment by surma** [comment]
Sadly, I don’t have a Samsung phone handy, but it seems like the issue you are encountering is specific to that phone or browser.

[Here’s a codepen](http://codepen.io/surma/pen/ojNLqL) where I switch out the `menu` for `android` and it works fine for me. Could give that codepen a run on your phone and report the results back to us?

**Comment by duyluandethuong** [comment]
No it still does not work. The menu is there, I can click on it, but the android icon does not show up. I think the problem is about the **lirature**, but I have tried to changed it to *&#xE5D2;* in the code pen and it still does not work. Could try to change that in the mdl.js source code?

**Comment by duyluandethuong** [comment]
Yeah it should be Samsung browser's issue

**Comment by surma** [comment]
@duyluandethuong Sorry, nothing more we can do about this. Closing the issue for now.
