### ISSUE TITLE
Convert font units from PX to EM

### ISSUE THREAD

**Issue by mustafa-x** [google/material-design-lite#1501]
Current build seems to use PX's instead of EMs or REMs. This can be problematic as some high-resolution/high-pixel-density screens report true resolution which would make the type appear smaller. [Jason Pamental mentions this in his responsive type book] (https://books.google.co.uk/books?id=tE59BAAAQBAJ&pg=PT72&lpg=PT72&dq=Samsung+touch-screen+laptops+reporting+true+instead+of+standard+resolution&source=bl&ots=oV-54RRQzU&sig=4CVw5VCjVRwVssRXL72dNn1tkZo&hl=en&sa=X&redir_esc=y#v=onepage&q=Samsung%20touch-screen%20laptops%20reporting%20true%20instead%20of%20standard%20resolution&f=false). 

Might be worth including a sass function to convert so you could think in PX but the output would be EM;

    $browser-context: 16; // Default
    @function em($pixels, $context: $browser-context) {
      @return #{$pixels/$context}em;
    }

**Comment by surma** [comment]
@mustafa-x That is definitely something we stumbled upon ourselves but can’t change this anymore before v2. I like your approach of defining one base size and using `rem` afterwards. I’ll keep this open as a reminder for v2.

**Comment by AliMD** [comment]
:+1:
Its will be perfect if all size (dimension/position) convert to em
Because we can change size of components by change font-size
Could you please accept pull request to change it in current version/milestone ?
You can create another branch for do it now with safety and merge it to master in the future.
Thank you in advance

**Comment by hebbet** [comment]
as that would be a breaking change, it is not possible to add rem in the 1.x version, so you have to wait for 2.0

**Comment by Garbee** [comment]
Let's wrap this back into #864. They seem like the same issue.

I'm working on converting everything that makes sense into `rem` in my 2.x mockup. This way we provide a base that aligns directly to Material Design, but if users increase the font-size (or developers) then the components will adjust with it.
