### ISSUE TITLE
Table not responsive

### ISSUE THREAD

**Issue by adiramardiani** [google/material-design-lite#1504]
I check table for small device is not responsive

**Comment by Garbee** [comment]
The data table spec has no guidance for mobile tables. Doing responsive tables is very difficult and there are numerous possible ways to handle it.

If you need responsive data tables, then you need to implement it yourself at the moment.

**Comment by KristerV** [comment]
as this is the third result in google, I though I'de list the options:
* [CSS-Tricks](https://css-tricks.com/responsive-data-tables/)
* [techblog.livingsocial.com](https://techblog.livingsocial.com/blog/2015/04/06/responsive-tables-in-pure-css/)
* [A Comprehensive List of Solutions](http://www.sitepoint.com/responsive-data-tables-comprehensive-list-solutions/)

**Comment by rhroyston** [comment]
Here's how it's done.

[Responsive Material Design Lite, MDL, Table](http://codepen.io/rhroyston/pen/dXdPEx)

The secret sauce is `table-layout:fixed;`

**Comment by rohanshenoy96** [comment]
> Here's how it's done.
> 
> [Responsive Material Design Lite, MDL, Table](http://codepen.io/rhroyston/pen/dXdPEx)
> 
> The secret sauce is `table-layout:fixed;`

This works fine if number are column are very less. Even in this the data can overlap sometimes. A better solution will be one that gives a horizontal scroll to the material table.

**Comment by ghaschel** [comment]
![image](https://user-images.githubusercontent.com/5878866/71821331-9d322100-3070-11ea-945f-060fb61612aa.png)


> > Here's how it's done.
> > [Responsive Material Design Lite, MDL, Table](http://codepen.io/rhroyston/pen/dXdPEx)
> > The secret sauce is `table-layout:fixed;`
> 
> This works fine if number are column are very less. Even in this the data can overlap sometimes. A better solution will be one that gives a horizontal scroll to the material table.

otherwise it looks like this:
![image](https://user-images.githubusercontent.com/5878866/71821359-afac5a80-3070-11ea-9d5d-743c1195a443.png)

A much better approach IMHO would be something like this: https://stackblitz.com/edit/angular-material-table-responsive
