### ISSUE TITLE
Some form component not styled

### ISSUE THREAD

**Issue by adiramardiani** [google/material-design-lite#1505]
For select tag like :
```html
<select>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
```

Or textarea is not styled ?

**Comment by surma** [comment]
Select are not styled as they are notoriously hard to style. We are aware and thinking about possibilities. See #854.

Textareas are styled and can be found on the [components page](http://www.getmdl.io/components/index.html#textfields-section).

For future reference: Please use the issue search before opening a new issue.
