### ISSUE TITLE
MDL for devdocs.io

### ISSUE THREAD

**Issue by CyanoFresh** [google/material-design-lite#1510]
Hello again. MDL was accepted into To Do section so it needs some votes. Will be nice if this message will appear somewhere(site or this repo) for more views. 
Where to vote: https://trello.com/c/M7O6Qu7f/252-material-design-lite 
Sorry, but I don't know where I had to put this message

**Comment by Garbee** [comment]
If people want us to have docs in other places, cool. However this isn't a problem with what MDL provides so I'm closing it out since there is no action we can or should take as far as I can tell.
