### ISSUE TITLE
[milestone] it seems there is a problem with date and versions

### ISSUE THREAD

**Issue by pierr** [google/material-design-lite#1511]
It seems there is a problem with the milestone version and the release date.
Is **v1.1** really due by October 15  ?
![milestone](https://cloud.githubusercontent.com/assets/286966/9569416/369d72a4-4f6b-11e5-91dd-7883fb2e39c5.png)

**Comment by surma** [comment]
Yeah, the v2 is more of a symbolic milestone right now. We should probably remove the deadline or move it very far into the future. @addyosmani or @sgomes you mind?

**Comment by pierr** [comment]
Ok thanks for the quick reply.

**Comment by addyosmani** [comment]
V2 is definitely aimed at farther in the future. I'll push back to Jan.
