### ISSUE TITLE
Grid Centering

### ISSUE THREAD

**Issue by seanmavley** [google/material-design-lite#1515]
Coming from Zurb Foundation, the first thing I noticed missing (or I couldn't do in cleanest form possible) in mdl was grid centering.

At the moment, I do this to center my grid in max screen mode in mdl
```
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--3-col"> 
        <!-- this is just dummy columns --> 
    </div>
    <div class="mdl-cell mdl-cell--6-col">
        Will put content here
    </div>
    <div class="mdl-cell mdl-cell--3-col"> 
        <!-- this is just dummy columns --> 
    </div>
</div>
```
Same thing above could have been done in foundation as
```
<div class="row">
    <div class="small-12 large-6 large-centered columns">...</div>
</div>
```

The `large-centered` class makes all the difference. Can this be considered as a feature request?

**Comment by surma** [comment]
Our grid is not supposed to be an entire layout engine, we are keeping it intentionally simple – both in features and code. If I understand your intent correctly, I’d use `margin: 0 auto;` to center content. I’d not be using the grid at all. I’d encourage you to take a look at the code of our templates, where we use the grid. 

As for this issue, I don’t see us implementing this,

**Comment by Garbee** [comment]
The new offset classes added in for V1.1 will also help here. And the last dummy column isn't necessary at all.
