### ISSUE TITLE
Links In Layout Not Working In MSEDGE

### ISSUE THREAD

**Issue by jig9** [google/material-design-lite#1517]
I had used the tutorial on the transparent layout . But both the title and the links will not show on MS Edge
It works perfectly with Chrome.

**Comment by surma** [comment]
@jig9 The demo (and the corresponding codepen) work fine for me in Edge. Could you provide us with a codepen, that reproduces the issue for you?

**Comment by jig9** [comment]
Oh i went back to Windows 8.1
