### ISSUE TITLE
Support of development for Angular2

### ISSUE THREAD

**Issue by emirdeliz** [google/material-design-lite#1520]
Hello,

The MDL contains suporte for development with angular2? I tried used button with effect 'mdl-js-ripple-effect'. After loading page effect is working, but when utilized event click as '(click)="someFunction()"', this not working. What seems MDL overwrites click function of angular2. Somebody use something like this?

**Comment by addyosmani** [comment]
MDL is primarily targeted at projects building sites that require vanilla JS. While we do support a level of dynamic JS component creation, we don't currently target special support for any specific third-party libraries and this includes Angular2. If you're looking for a Material library to use with Angular I would recommend checking out https://github.com/angular/material which is a better fit.

**Comment by surma** [comment]
Additionally, you could try heading over to StackOverflow using the `material-design-lite` tag. A lot of people have spent time getting MDL to work with Angular, so I can imagine there’s some Angular2 going on as well :)

**Comment by emirdeliz** [comment]
Thank you!
