### ISSUE TITLE
Adding fields in a form dynamically

### ISSUE THREAD

**Issue by stunaz** [google/material-design-lite#1521]
Hi,
Is there a way to add dynamic fields to a form via javascript ? Seems like i can't do it just by add a field with his mdl properties. Doing this way I have no animation (the label doesn't move up) with the added field, and I guess no validation.

**Comment by Garbee** [comment]
You need to upgrade the components that get added in. An example of how to do this is shown in the [getting started guide](http://www.getmdl.io/started/index.html) under the dynamic usage section.
