### ISSUE TITLE
Switch cursor issue

### ISSUE THREAD

**Issue by web2style** [google/material-design-lite#1530]
When switch is off, the cursor over it is pointer. But when you turn the switch on, cursor is no longer pointer. Is it a bug or intentional behavior?

**Comment by surma** [comment]
I think that’s a bug. Good catch, @web2style.

**Comment by rohanthacker** [comment]
@web2style http://codepen.io/rohanthacker/pen/JYdEOV

What version are you using? With v1.4 the bug isn't visible

**Comment by narendrashetty** [comment]
@surma Please review the PR for the issue. Thanks :)
