### ISSUE TITLE
Textarea!

### ISSUE THREAD

**Issue by krishnakumar-kapil** [google/material-design-lite#1536]
* Allows users to input a multiline message
* Material Design Spec linkhttps://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3VlBlN2N6TkZ2TFE/components_textfields_multiline1.png
* Use Case(s) - In forms

**Comment by Garbee** [comment]
It is already in the Textfield component.
