### ISSUE TITLE
Drawer button selector

### ISSUE THREAD

**Issue by disillusions** [google/material-design-lite#1537]
As of nested layouts (one in one) I think var drawerButton must be this.element_.querySelector(':scope >.' + this.CssClasses_.DRAWER_BTN); But I don't know what to do with IE. Maybe smth like this http://stackoverflow.com/a/17989803/5295695

**Comment by Garbee** [comment]
Closing this out since it doesn't seem like a problem with what MDL provides. Please use StackOverflow for support in using and implementing sites with it.
