### ISSUE TITLE
Cards: `.mdl-card__subtitle-text` uses non-customizable `grey` text color

### ISSUE THREAD

**Issue by stevebest** [google/material-design-lite#1538]
https://github.com/google/material-design-lite/blob/v1.0.4/src/card/_card.scss#L76

This basically prevents using card subtitles on non-white backgrounds, unless overridden in a user stylesheet.

Perhaps it should specify no color and use `opacity` instead?

**Comment by surma** [comment]
The hard-coded color is definitely an oversight, although I *think* the grey is defined by the spec. Looping in @Garbee for more input on this :)

**Comment by stevebest** [comment]
BTW, spec is inconsistent in naming this component:

- in text it's either `subtext` or `subtitle`,
- on screenshots it's `subhead`.

On some screenshots it (or its doppelgänger :wink:) is pure white, and some are white-ish grey, much brighter than just `grey`.

https://www.google.com/design/spec/components/cards.html

**Comment by Garbee** [comment]
> On some screenshots it

Screenshots in the spec should be taken with a grain of salt. Always go with written text over the visual examples.

On the note of proper color, it should be 54% of black or the primary color. Let's go with straight black here to keep it simple and if developers want to go with primary color they can do that themselves. This comes from the [subheader spec](https://www.google.com/design/spec/components/subheaders.html#subheaders-list-subheaders) for lists, but is the closest thing we have to an actual number for use here.
