### ISSUE TITLE
manual javascript for components  and it's bug

### ISSUE THREAD

**Issue by alien3d** [google/material-design-lite#1539]
Text Field
1\. need to mention the validation error are using html5 object. http://pastebin.com/rnwNHWv8 
2\. Table: Weird padding left 24 on first td.. ?What purpose of it..Can be table with no weird padding upon put in    

```HTML
<div class="android-content mdl-layout__content">
  <table class="mdl-data-table">
    <tr>
      <td>text</td>
      <td>e</td>
    </tr>
  </table>
</div>
```

3\. Normal jquery prop checked wouldn't changed the  switch on and off.Is there any example jquery/javascript can toggle the switch ?

**Comment by surma** [comment]
Before I start: Please open one issue per bug that you find in the future. Bonus points for using codepen examples that reproduce the issue.

1. I agree that we could make that more explicit in the docs. However, is there any other way of validation than what the browser provides (Considering the examples don’t mention any form of custom validation shipped with MDL)?

2. Data Tables have a very cleary defined [spec](https://www.google.com/design/spec/components/data-tables.html). You are not using the data tables correctly (i.e. you are skipping the `<td>` classes, see [examples](http://www.getmdl.io/components/index.html#tables-section)). The padding is for the checkboxes.

3. You can do something like `document.querySelector('.mdl-checkbox').MaterialCheckbox.check()` and `document.querySelector('.mdl-checkbox').MaterialCheckbox.uncheck()`

**Comment by surma** [comment]
I hope I answered your questions sufficiently. If not, please feel free to re-open this :) However, keep in mind that the issue tracker on GitHub is for bugs only. For support, please head over to Stackoverflow and user the `material-design-lite` tag :)

**Comment by alien3d** [comment]
okay i open another. 1 by one 1.

**Comment by Garbee** [comment]
Please don't open issues for point's 1 and 3. They are support/usage questions and should be put on StackOverflow. Point 2 here looks to be the only thing we need to review internally to see if there is a problem.

**Comment by alien3d** [comment]
for number 3 , i have check at stack over flow and it's suggest   but it output same error

TypeError: document.querySelector(...).MaterialCheckbox is undefined
	document.querySelector('#'+id).MaterialCheckbox.check()

reference image :http://snag.gy/g6kTV.jpg

**Comment by Garbee** [comment]
Let's please keep support *on* StackOverflow where the most developers can get the information.
