### ISSUE TITLE
table th and td first padding.

### ISSUE THREAD

**Issue by alien3d** [google/material-design-lite#1541]
Image 1 .http://snag.gy/JEwRv.jpg
Image 2  http://snag.gy/GHW1n.jpg
Image 3 http://snag.gy/rloOA.jpg
1. User experience doesn't suppose to have check box at left side.It might be on the right side . It might be a list of row.
Refer to Image 1

2. Normal with td should be fixed not overwritten by padding.
Refer to Image 2. and Image 3

3. By Normal like Contact must have filter character and row. If you overwrite padding first it quite  odd.

My Suggestion is css based on normal td tr and not padding at all.

**Comment by Garbee** [comment]
Can you please provide a [codepen](http://codepen.io) that reproduces the problem? It is hard to understand what the exact problem is with the images and description provided. Much less be able to recreate it.

**Comment by alien3d** [comment]
other bugs... own mistake.
