### ISSUE TITLE
Date picker and Time picker

### ISSUE THREAD

**Issue by nickretallack** [google/material-design-lite#1544]
Is this a new component, or a missing feature in an existing one? New
Component name: Pickers: Date picker, Time picker
Material Design spec URL for the component (if any): https://www.google.com/design/spec/components/pickers.html

What does this component or feature allow you to do which isn’t possible at the moment?
Have a nice UI for picking a date and time.  Good general purpose UI for this is rare.

Please provide any URLs or screenshots of good examples of usage of this component or feature that you may have come across.

**Comment by Garbee** [comment]
Duplicate #782
