### ISSUE TITLE
body.mdl-layout gets wrapped in a div

### ISSUE THREAD

**Issue by flying-sheep** [google/material-design-lite#1549]
when specifying the CSS class `mdl-layout` on `<body>`, layout.js wraps it in a `<div class="mdl-layout__container">`.

it should ensure that the body element’s parent stays `<html>`

**Comment by Garbee** [comment]
The [documentation](https://github.com/google/material-design-lite/tree/master/src/layout#to-include-a-basic-mdl-layout-component) is pretty clear that you need to code a div within the body to use layout against. Not sure there is anything we should do here.

**Comment by flying-sheep** [comment]
> ## Basic use
> ### To include a basic MDL layout component:
> 1. Code a <div> element.

that’s a tutorial, not a specification.

besides, farther down on the same page, it says

> Defines *container* as an MDL component

and indeed. why should anything be required of that container apart from it being a block-level element?

body, main, section, article, … are all fitting imho

**Comment by Garbee** [comment]
From the same line you pulled from the configuration...
> Required on outer div element

Supporting layout directly on the body like this is going to be an edge-case and the proper thing to do is as the documentation says and set it up *within* the body, not on it (which as far as I can tell is implied nowhere.) The Layout is going to undergo a complete refactor with 2.x already, we can keep this in mind when working on that.
