### ISSUE TITLE
some bugs on getmdl.io

### ISSUE THREAD

**Issue by flying-sheep** [google/material-design-lite#1552]
it is pretty buggy right now:

1. in the footer there’s no space between the links:

    ![snapshot_tj2397](https://cloud.githubusercontent.com/assets/291575/9687727/3ec9fbbe-532b-11e5-817c-a333602291a0.png)

2. the components docs contain broken markup:

    ![snapshot_tj2471](https://cloud.githubusercontent.com/assets/291575/9687752/62dac826-532b-11e5-813e-2acdc428597a.png)

**Comment by Garbee** [comment]
Both already fixed. Just waiting for next site refresh.
