### ISSUE TITLE
Small markdown bugs in the checkbox component page

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#1554]
![](http://i.imgur.com/7mSZ1o2.png)

**Comment by Garbee** [comment]
I thought this was already fixed. It was with the spacing between markup statements and the text. A site refresh should fix it.

**Comment by mspl13** [comment]
As far as I can tell the missing spaces were fixed/added in #1450.

**Comment by surma** [comment]
Yup, fixed by #1450.
