### ISSUE TITLE
Components style disappearing (Checkbox and textbox)

### ISSUE THREAD

**Issue by faridprogrammer** [google/material-design-lite#1555]
I am writing an angular js 1.X mobile application that is built with cordova.
When using MDL checkbox style when a view loads first it works fine but when changing between views the style for components disappears. For now I am using checkbox and text input elements . 
Is there some one that experience this?

**Comment by Garbee** [comment]
Please use StackOverflow for support requests. This way as many developers as possible can help and find similar problems. There is a `material-design-lite` tag to show you are using MDL.
