### ISSUE TITLE
Attribute for not allowed on element ul at this point

### ISSUE THREAD

**Issue by filippomartini** [google/material-design-lite#1556]
The Menu component gives a validation error. 
<img width="1285" alt="schermata 2015-09-05 alle 13 36 11" src="https://cloud.githubusercontent.com/assets/11539305/9699060/4e6db29c-53d3-11e5-869d-826c2bf3ddcd.png">

**Comment by Garbee** [comment]
Technically invalid markup yes, but browsers do just fine with it. Nothing we should do about this until 2.x, if anything. Adding to the milestone for that as something to look into.

**Comment by surma** [comment]
@Garbee @addyosmani @sgomes Is it worth our time to add additional support for `data-for` to allow strictly valid markup for the 1.x timeline?

**Comment by Garbee** [comment]
Sgtm for a 1.1 addition.

**Comment by addyosmani** [comment]
SGTM for 1.1 too.

**Comment by sgomes** [comment]
:+1:

**Comment by Garbee** [comment]
FYI in #1734 we are updating the `data-for` here to `data-mdl-for`. This will namespace out our bindings to cause the least amount of conflict with existing third party and userland code.
