### ISSUE TITLE
Unstyled Markdown Headers on getmdl.io website

### ISSUE THREAD

**Issue by hatzopoulos** [google/material-design-lite#1557]
While reading the docs on http://www.getmdl.io/components/index.html#layout-section I noticed the various markdown style headers are not rendering to header tags.

![image](https://cloud.githubusercontent.com/assets/1771931/9700046/282f211a-53c4-11e5-8911-c086eda3a335.png)

**Comment by rohanthacker** [comment]
Similar issue in discussion at #1554. #1450 has fixed this issue.

**Comment by surma** [comment]
Yup, this was fixes in #1450. Will go live with the next site push.
