### ISSUE TITLE
Text Field issue

### ISSUE THREAD

**Issue by mrfaizanhaider** [google/material-design-lite#1559]
there is just browser-default select option available for TEXT FILEDs.

there is any soloution for material select option??

**Comment by surma** [comment]
Duplicate of #854. We don’t have anything for select fields in MDL yet, sadly.

**Comment by mrfaizanhaider** [comment]
so what about future???

**Comment by surma** [comment]
@mrfaizanhaider Please read the issue #854 I linked to. We will implement select fields.
