### ISSUE TITLE
mdl-data-table__select should be part of MaterialDataTable.prototype.CssClasses_

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#1560]

**Comment by surma** [comment]
Yup, agreed. Totally missed that in the review. [This section](https://github.com/google/material-design-lite/blob/master/src/data-table/data-table.js#L113-L117) needs a little cleanup. Nothing major, though.

**Comment by MikeMitterer** [comment]
+ there are some other css-classes like mdl-checkbox__input aso. 
> Nothing major, though.
No, I just stumbled across these classes while porting some things over to Dart...

If you are checking data-table maybe you can check something else:
If I check all checkboxes by selecting the header-checkbox and if I deselect one of the child checkboxes shouldn't the header-checkbox also deselect?
![checkboxes](https://cloud.githubusercontent.com/assets/116654/9720622/0dc663a6-5590-11e5-83b0-0c92eb6c2fc6.gif)

**Comment by surma** [comment]
@MikeMitterer You mind turning that into a separate issue? It’s probably a bug as well

**Comment by MikeMitterer** [comment]
OK - I file another issue. (If I'm back from biking... ;-))

**Comment by Garbee** [comment]
I'll handle this for 1.0.6. I don't see any reason to hold of fixing this to the minor version.
