### ISSUE TITLE
[Add offsets to mdl-layout]{mdl-grid}

### ISSUE THREAD

**Issue by krishnakumar-kapil** [google/material-design-lite#1562]
* Description - Without offsets to the grid it becomes very challenging to deal with breakpoints on the largest of displays due to the constant resizings.
* Material Design Spec link - This is a web dev requirement and I do not believe it is there in material design though I am not sure
* Use Case(s) - Used pretty much everywhere when needed for centering / having offsets

**Comment by hebbet** [comment]
possible duplicate of #239 

:mag: before filing a new :bug:

**Comment by surma** [comment]
Offsets have been added in #1460. Closing this :)
