### ISSUE TITLE
checking/unchecking row / parent checkboxes in data-table seem wrong

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#1564]
If I check all checkboxes by selecting the header-checkbox and if I deselect one of the child checkboxes shouldn't the header-checkbox also deselect?
![checkboxes](https://cloud.githubusercontent.com/assets/116654/9722716/bec10c48-55b2-11e5-85ab-44d14a95972f.gif)

**Comment by Garbee** [comment]
Duplicate of #932
