### ISSUE TITLE
Are there any material design transition animations ? 

### ISSUE THREAD

**Issue by ArEnSc** [google/material-design-lite#1565]

**Comment by surma** [comment]
There are a lot of animations in the [MD spec](https://www.google.com/design/spec/material-design/introduction.html). All the components we provide try to stay as close as technically possible to the animations shown in the spec. Not every animation has a corresponding component in MDL, though.

Is that an answer to your question?

**Comment by ArEnSc** [comment]
For instance if I wanted to do an on enter transition and on leave transition, I would assume that I would have to program it my self ?

**Comment by surma** [comment]
Correct. We don’t have any components for animations of that kind right now nor do we have immediate plans to provide such components. This is both part of the *Lite* philosophy and our relatively generous browser support philosophy. 

We may consider this in the future, but probably not before v2.
