### ISSUE TITLE
Material Icon color

### ISSUE THREAD

**Issue by alien3d** [google/material-design-lite#1567]
http://codepen.io/anon/pen/QjbgGv
All the color i take from _color-definition.scss 
I done it because when i using <span class="material-class mdl-color-red">favorite</span>only color the background .
The naming standard following the http://google.github.io/material-design-icons/
Sample php script i generate this color http://pastebin.com/82GB8P6A

**Comment by Garbee** [comment]
The `mdl-color-text--{color}` classes work just fine with Material Icons. No need to add extra weight for no benefit. You can see all that are available in [_palette.scss](https://github.com/google/material-design-lite/blob/master/src/palette/_palette.scss)
