### ISSUE TITLE
After trigger form reset then the Textfield get wrong classes

### ISSUE THREAD

**Issue by andyyou** [google/material-design-lite#1568]
![img](http://i.imgur.com/xaAbMWe.png)

Although it's a bit issue...

**Comment by andyyou** [comment]
[codepen example](http://codepen.io/andyyou/pen/KdpmwK)

**Comment by andyyou** [comment]
I just trigger change itself but does any solution for that

**Comment by andyyou** [comment]
[solve in my solution](https://github.com/andyyou/material-design-lite/blob/master/src/textfield/textfield.js#L223)

Because I need some way to reset component.

**Comment by Garbee** [comment]
@andyyou Can you PR that fix? Looks like a good solution to the problem.

**Comment by andyyou** [comment]
OK
