### ISSUE TITLE
Data-Badge Dynamic Update

### ISSUE THREAD

**Issue by skolade** [google/material-design-lite#1572]
Data-badge does not watch for changes in a shopping cart, the page has to be refreshed before data-badge update count! This is with .Net application!

**Comment by surma** [comment]
@skolade The content of the badge is set with CSS via `attr()`. There is no JavaScript involved so you must be doing something wrong on your side.

Here’s a quick demo: http://codepen.io/surma/pen/QjbVjr

However, please head over to StackOverflow for support and use the `material-design-lite` tag, as the GitHub issue tracker is for MDL bugs and feature requests only.
