### ISSUE TITLE
Drawer menu always opened in Android Stock Browser

### ISSUE THREAD

**Issue by jmtalarn** [google/material-design-lite#1574]
Hello.

I use a fixed header and the drawer menu is always open in the Android Stock browser I'm testing. I tried it with the installed Chrome version in the Android device and it works fine any other browser and device tested is also working fine.
This is the user agent of the browser in a LG G2 updated to Lollipop 5.0.2 "Mozilla/5.0 (Linux; Android 5.0.2; LG-D802 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/34.0.1847.118 Mobile Safari/537.36"

It's a bit worrying because it should be a widely used browser and the side drawer menu uses more than half screen when is opened.

**Comment by jmtalarn** [comment]
Ok. It was my fault.

I'm including material-design-lite.scss in my scss source and the resulting css is not including the WebKit prefix to make the css3 transforms work in the android stock browser. 

[Answer:Does Android's Stock Browser support CSS3 transforms](http://stackoverflow.com/a/17709038?stw=2)

**Comment by surma** [comment]
@jmtalarn Good to hear you worked it out. Yes, we are [running gulp-autoprefixer](https://github.com/google/material-design-lite/blob/364026628aaacd0fd6c84ced9e1a470560092862/gulpfile.js#L185) on the compiled CSS rather than the SASS.

**Comment by felixvictor** [comment]
@surma: Could you mention the required use of autoprefixer in the docs for people using the scss files? I spent some time finding the error in my html code until reading this post...

@jmtalarn: Thanks a heap.
