### ISSUE TITLE
Mega footer checkbox chevron visible

### ISSUE THREAD

**Issue by peiche** [google/material-design-lite#1582]
There is a case where the chevron to indicate an expanded footer section is still visible on wide screen layout.

Steps to reproduce on a page with a mega footer:
1. Shrink the window size down so that the menu sections collapse.
2. Click a section title to expand that section.
3. Enlarge the window so that the menu sections are no longer collapsed.
4. See that the chevron ("^") is still visible.

The bug in action (using assets straight from [getmdl.io](http://www.getmdl.io/)):
http://codepen.io/peiche/details/wKabJZ/

**Comment by surma** [comment]
Good catch! Seems like a missing media query. Thanks for the report, @peiche!

**Comment by narendrashetty** [comment]
@surma Is this bug fixed? or can i send a PR for the issue?

**Comment by surma** [comment]
@narendrashetty No, hasn’t been addressed yet. If you have a PR that would be greatly appreciated :)

**Comment by narendrashetty** [comment]
@surma here is the PR (https://github.com/google/material-design-lite/pull/1591) have a look. Thanks :)
