### ISSUE TITLE
Bug - material-icons not showing on Blackberry 10

### ISSUE THREAD

**Issue by listedegarde** [google/material-design-lite#1583]
The material-icons are not visible on BlackBerry 10.  Tested on Z10 using 10.3.1.  Here's a screenshot of the [Android demo](http://www.getmdl.io/templates/android-dot-com/index.html) page, with the invisible material-icon menu and material-icon search on the left and right, respectively.  

I can click on the menu icon, and it the menu opens.

![Screenshot of bug](https://drive.google.com/uc?export=download&id=0B6CvYWA0jNMrRmI3alhybWZEQXM)

I thought I'd send this out there in case someone has an idea what's going on.  Otherwise, I'll put a little time into debugging this, and update this week-end with results.

**Comment by surma** [comment]
I’d guess that this is related to https://github.com/google/material-design-icons/issues/179

I don’t have any Blackberries to test nor I know much about their browser engine, so any help with this is greatly appreciated, @listedegarde :) Maybe you can test the workaround mentioned in the issue above.

**Comment by listedegarde** [comment]
Thanks for that suggestion!  You saved me a lot of debugging time.  Indeed, the workaround from that post works.  `.material-icons {text-rendering: optimizeLegibility; }`

I'm not sure how you deal with issues, but I suppose this could be closed as a duplicated of issue 179.

**Comment by surma** [comment]
Yeah, we ran into the same issue wie Edge. Thanks for testing and letting us now :) I’m optimistic that this issue will be fixed upstream soon-ish.
