### ISSUE TITLE
Bug, when using text field with floating label with jQuery DatePicker.

### ISSUE THREAD

**Issue by shranet** [google/material-design-lite#1587]
Hi. Sorry, my english bad.
If you change value of field with datepicker, label of field doesn't change style and the label stays on same position.

I tested on Safari 8.0.8 (Mac OS 10.10.5).

<img width=“414" alt="bug-mdl" src="https://cloud.githubusercontent.com/assets/1712200/9800603/4cb6f924-5827-11e5-9eca-4964b7853346.png">

**UPDATE:**
I solved the problem this way:

```javascript
$("input.birthday").datepicker({
  onSelect: function(dateText) {
    $(this).parent().addClass("is-dirty");
  }
});
```

**Comment by Garbee** [comment]
Calling `updateClasses` on the widget after modifying the value is what should be done.

Nothing for us to do internally, it is out of scope of what is provided. For support in the future, please use StackOverflow and apply the `material-design-lite` tag along with any other applicable tags.
