### ISSUE TITLE
When Google Chrome available For Windows Phone 8, 8.1 and Windows 10 Mobile?

### ISSUE THREAD

**Issue by AKSHAYPATEL147852369** [google/material-design-lite#1590]
When Google Chrome available For Windows Phone 8, 8.1 and Windows 10 Mobile. Please we request make it available for Windows Phone all versions. We need all Google apps can run on Windows Phone 8, Windows Phone 8.1 and Windows 10 Mobile.

**Comment by hebbet** [comment]
@AKSHAYPATEL147852369 that is an issue tracker about a framework for web development and not for Chrome. 

For your problem/suggestion see [Chromium Bugtracker](https://code.google.com/p/chromium/issues/detail?id=489037)
