### ISSUE TITLE
SVGs are 404 not found

### ISSUE THREAD

**Issue by ahmadawais** [google/material-design-lite#1593]
I downloaded the GMDLite and found out that svgs are no where to be found, whereas there are links in CSS to several SVGs. Which leads to such errors http://prntscr.com/8frw4a

**Comment by surma** [comment]
@ahmadawais Just to make sure: What is GMDLite? Is 

Our SVGs are inlined in the building process, so there is no dependency in the final CSS. How are you pulling in MDL?

**Comment by ahmadawais** [comment]
@surma  Google Material Design Lite. 

I downloaded GMDL from https://storage.googleapis.com/code.getmdl.io/1.0.4/mdl.zip

Why would it give me the error, one in the screenshot above? Looking forward

**Comment by Garbee** [comment]
Looks like we need a reproducable sample case. Searching the zip file linked to, there are no calls directly to SVG files. They are all inlined as they should be.

**Comment by surma** [comment]
@ahmadawais Which CSS file are you including in your site?

**Comment by ahmadawais** [comment]
I see they are inline. Looking into the error to find out what is causing it. #strange
