### ISSUE TITLE
Is there a way to have an option to have always visible last header-row in waterfall layout tab?

### ISSUE THREAD

**Issue by ivanceras** [google/material-design-lite#1594]
```html
<header class="mdl-layout__header mdl-layout__header--waterfall">
    <!-- Top row, always visible -->
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title">Title</span>
      <div class="mdl-layout-spacer"></div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">
        <label class="mdl-button mdl-js-button mdl-button--icon"
               for="waterfall-exp">
          <i class="material-icons">search</i>
        </label>
        <div class="mdl-textfield__expandable-holder">
          <input class="mdl-textfield__input" type="text" name="sample"
                 id="waterfall-exp" />
        </div>
      </div>
    </div>
    <!-- Bottom row, not visible on scroll -->
    <div class="mdl-layout__header-row">
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation -->
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
        <a class="mdl-navigation__link" href="">Link</a>
      </nav>
    </div>
  </header>
```
Usecase is a multi-page tab, where in when the user scroll the title of the page doesn't matter anymore. The user needs to always see menu icons that is applicable to the current page.

**Comment by lascarayf** [comment]
+1 I have the same problem. If you see the "Google Play App" this is the behavior (hide the first line)

**Comment by lascarayf** [comment]
.mdl-layout__header--waterfall{
    flex-direction: column-reverse;
}

add style="order: 1;" to first line div.

**Comment by ivanceras** [comment]
The search and title disappears, but then it should be located initially at the top, then disappear when scrolled while the links are supposed to stay.

http://codepen.io/anon/pen/QjyPyg

**Comment by sgomes** [comment]
I'd go with a simpler approach:

```
.my-header {
  justify-content: flex-end !important;
}
```

See http://codepen.io/anon/pen/KdVjpp

That should make the bottom row stay in place while the top slides out of view. The menu button stays in place, since it's positioned absolutely.

If you want to add or remove elements which are only visible when the header is contracted, you can use the `.is-compact` class (which gets added automatically to the header when it contracts) in your selectors.

As for adding this as an option to the header, we can consider it. @surma @Garbee WDYT?

**Comment by Garbee** [comment]
Modifier sgtm for 1.1.

**Comment by surma** [comment]
Yeah, SGTM :)

**Comment by sgomes** [comment]
Merged in master.
