### ISSUE TITLE
Firefox Text-Field-Bug:-(

### ISSUE THREAD

**Issue by axxg** [google/material-design-lite#1596]
Hello everybody,
I use the FF Version 40.0.3 and have the following problem: the input fields are over the font.

i use MDL 1.0.4

![p1](https://cloud.githubusercontent.com/assets/2951327/9847409/f4132270-5ad8-11e5-9471-fe8c5c82edc5.png)
![p2](https://cloud.githubusercontent.com/assets/2951327/9847410/f41edab6-5ad8-11e5-809e-082c9b6326af.png)

Code Example:

CSS:
.labelS {
	color: rgba(0, 0, 0, .26);
	font-size: 16px;
}

HTML:
```
 <br /> <span class="labelS">Die <strong>erste</strong> Session an dem Tag <strong>beginn</strong> ca.
									</span>
									<div class="mdl-textfield mdl-js-textfield" style="width: 40px;">
										<input class="mdl-textfield__input" type="number" min="1" max="23" pattern="[0-9]*" id="dayEdit-startStd" /> <span class="mdl-textfield__error">Es sind nur Zahlen von 1 bis 9 erlaubt!</span>
									</div>
									:00 Uhr. <br /> <span class="labelS">Die <strong>letzte</strong> Session an dem Tag <strong>endet</strong> ca.
									</span>
									<div class="mdl-textfield mdl-js-textfield" style="width: 40px;">
										<input class="mdl-textfield__input" type="number" min="1" max="23" pattern="[0-9]*" id="dayEdit-endeStd" /> <span class="mdl-textfield__error">Es sind nur Zahlen von 1 bis 9 erlaubt!</span>
									</div>
									:00 Uhr. <br />
```

**Comment by hebbet** [comment]
can you provide a jsfiddle or codepen of that problem?

**Comment by axxg** [comment]
https://jsfiddle.net/nsm7ugL7/


![p2](https://cloud.githubusercontent.com/assets/2951327/9848681/9f773f70-5ae3-11e5-92e4-6be17543c71e.png)

**Comment by Garbee** [comment]
This falls under support more than a core problem. The components work as provided across browsers. For help with integrating MDL into your site please use StackOverflow with the `material-design-lite` and all other applicable tags.

**Comment by axxg** [comment]
it is a bug, because it wasn't in 1.0.1 and 1.0.2 and 1.0.3!

**Comment by axxg** [comment]
@Garbee 
....and no cool answer in StackOverflow:-/ 
http://stackoverflow.com/questions/32565160/mdl-firefox-input-fields-are-over-the-font

**Comment by surma** [comment]
I traced this down to 92d2ef2de3887507cc02dc59ea8c57abaef0b498. Not sure why Firefox is behaving this way. We’ll investigate for a fix.

**Comment by surma** [comment]
@axxg Sadly, I don’t think we can do much about this. Firefox doesn’t seem to be spec compliant when collapsing a node’s margins with its parents. Maybe you can make use of [this workaround](https://codepen.io/surma/pen/rOWZZw).

**Comment by axxg** [comment]
@surma 
Thanks for your help, but I don't understand the workaround. Should I always use the 1.0.3 version? For ever? Is it possible to report the bug at morzilla?

**Comment by surma** [comment]
@axxg Sorry! That was completely cryptic by me :smile:

No, what I did is to wrap the individual rows into `<div>`s and applied the following style to those `<div>`s:

```CSS
body > div {
  display: flex;
  align-items: center;
}
```

**Comment by axxg** [comment]
ok, i get it:)
thx!
https://jsfiddle.net/ow8572gt/1/
