### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by mebibou** [google/material-design-lite#1601]
Component name: `Tabs`
New feature: add a class to display the tabs vertically instead of horizontally. The Tabs could then go on the left and the content on the right side.

**Comment by nikhilsingh12** [comment]
Well
Check this - http://sh.st/v2tCH. Feature is available in this.

**Comment by sgomes** [comment]
Thanks for the issue, @mebibou! Unfortunately, we don't have a spec at the moment for vertical tabs, and we as engineers are unlikely to come up with something good (see http://dilbert.com/strip/2002-09-23).

I'm closing this issue for now, but happy to reopen it if we ever get vertical tabs in the Material Design spec!

**Comment by Rahul-Sagore** [comment]
For temporary solution, we can convert the MDL's horizontal tab to vertical, by dividing it in two columns using mdl-grid and mdl-cell. it will make it vertical. But the design won't look good. To make it look good, I have written a article on it, you can refer to it  : [Vertical tabs with material design lite](http://rahul-sagore.github.io/#/blog/vertical-tabs-with-material-design-lit)

**Comment by ashishpatil250795** [comment]
please give property for vertical material design tabs..high requirement for that by end users..
