### ISSUE TITLE
Markdown syntax (##) appearing in the microsite 

### ISSUE THREAD

**Issue by mustafa-x** [google/material-design-lite#1603]
Hey guys

I've noticed on the microsite for Material Design that the headings which have been written in markdown are not appearing correctly so instead of a header being styled as one you get the ## before a header. 

Example: http://www.getmdl.io/components/index.html#layout-section
![markdown-text-appearing-on-microsite](https://cloud.githubusercontent.com/assets/1212513/9881027/1e7d704a-5bc6-11e5-95a1-2d078f76bf6e.png)

**Comment by Garbee** [comment]
Fixed in commit a64e9b6809f6da7d43a46234af433e49c1d33e3a#diff-19aece333bacc9e2d1b4ce0e266c643c . Waiting on new deployment.
