### ISSUE TITLE
Feature request: styles for deeper shadows

### ISSUE THREAD

**Issue by kengruven** [google/material-design-lite#1606]
Is this a new component, or a missing feature in an existing one?
A missing feature.

Component name:
Card (sort of -- shadows aren't a "component" but the MDL shadow styles are documented on the MDL Card documentation page).

Material Design spec URL for the component (if any):
https://www.google.com/design/spec/what-is-material/elevation-shadows.html

What does this component or feature allow you to do which isn’t possible at the moment?
Deeper shadows.  MDL provides `mdl-shadow--2dp` through `mdl-shadow--16dp`, which is great as far as it goes, but the MD spec calls for shadows between 1dp and 24dp.

Please provide any URLs or screenshots of good examples of usage of this component or feature that you may have come across.
The Material Design "Dialogs" page shows dialog boxes with "Dialog elevation: 24dp": https://www.google.com/design/spec/components/dialogs.html#dialogs-specs -- there's no dialog boxes in MDL yet (I know about #781) but if we had the shadow mixins we could make our own easily enough.

**Comment by Garbee** [comment]
I think a mixin to generate any arbitrary DP of shadow may be a bit complicated to pull off. Probably best we focus on adding the 24dp shadow directly since it seems to be the major missing one from the spec.

**Comment by sgomes** [comment]
+1 to @Garbee's suggestion.
