### ISSUE TITLE
jQuery: Label overlaps the content

### ISSUE THREAD

**Issue by axxg** [google/material-design-lite#1607]
Hello,
I use FF Version 40.0.3/Chrome 45.0.2454.85 and i have the following problem: the placeholder/label overlaps the content, if i use jQuery.
I have also aked at stackoverflow: http://stackoverflow.com/questions/32579980/mdl-jquery-label-overlaps-the-content-into-a-input-field

**JS:**

    $("#eventAddKurzLB").val("test");

**HTML:**

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
		<input class="mdl-textfield__input" type="text" id="eventAddKurzLB" />
    	<label class="mdl-textfield__label" for="eventAddKurzLB">Kurzbezeichnung:</label>
    	<span class="mdl-textfield__error">Es sind nur Zahlen, Buchstaben und Bindestriche erlaubt!</span>
	</div>

**Example:**

[![enter image description here][1]][1]
 
**Live-Example:**
https://jsfiddle.net/vutLb9ut/2/

  [1]: http://i.stack.imgur.com/fKzAR.png

**Comment by sgomes** [comment]
The problem isn't jQuery, but rather the fact that the component is unaware of the changes you're making (programmatic changes to an HTML element don't trigger events). You can test this by manually typing into the box; that should work correctly, even if jQuery is loaded.

You can use the element's API for changing the text instead, by doing:

```
$("#my-textfield").MaterialTextfield.change('test');
```

(where `my-textfield` is the outer `label` element), provided the element is done upgrading. The other option is to perform the change directly, as you are doing, but triggering a "dirtiness" check on the element:

```
$("#my-textfield").MaterialTextfield.checkDirty();
```

Hope this helps!

**Comment by axxg** [comment]
where can I get the element API?
currently it does not work :-(

https://jsfiddle.net/vutLb9ut/4/

**Comment by sgomes** [comment]
That's likely because the calls are happening before the element is upgraded, since you're doing them `onLoad`. Try doing them `onDomready` instead and it should work!

**Comment by axxg** [comment]
I think I'm too stupid:-(

https://jsfiddle.net/vutLb9ut/7/

**Comment by sgomes** [comment]
You need to get the base element before calling a method on it, otherwise you're working on a jQuery object that doesn't have the `MaterialTextfield` property. Also, you need to get the element around the textfield, as that's the component element.

```JS
$(document).ready(function() {
    $("#myTextfield").get(0).MaterialTextfield.change('test');
});
```

Here's a fiddle: https://jsfiddle.net/Lzdez4s2/1/

**Comment by axxg** [comment]
you are the best! Thanks a lot:)
