### ISSUE TITLE
Navigation layouts, Menu Icon

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#1609]
Why is the material design menu icon not visible / editable in the HTML, [here](http://www.getmdl.io/components/index.html#layout-section).  The issue is that when css is applied to vertical align the material design icons, the menu icon is also affected and thrown off of alignment.  

![asdf](https://cloud.githubusercontent.com/assets/12751611/9913589/3e0fc59a-5c73-11e5-9a0e-79d7597ba25d.JPG)

**Comment by hebbet** [comment]
for support question use StackOverflow. Using the `material-design-lite` and any other applicable tags to get the best support in implementing MDL in projects.

**Comment by surma** [comment]
I have to agree with @hebbet. This is obviously support as it is working on the demo. The guys over at StackOverflow are really helpful, though. Give them a try :)
