### ISSUE TITLE
Chrome Bug - label text shows on auto-completed text field

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#1611]
![fdas](https://cloud.githubusercontent.com/assets/12751611/9915809/ae85c38c-5c7e-11e5-9cb5-edc7aaedd9ae.JPG)

**Comment by Garbee** [comment]
This is a limitation on auto fill not triggering a change or input event. Nothing we can do about it with our current browser support since it requires observers to fix.

**Comment by surma** [comment]
For completeness sake: Also a duplicate of #1253
