### ISSUE TITLE
Component styling?

### ISSUE THREAD

**Issue by laicosly** [google/material-design-lite#1612]
How does one go about styling textfield components (and others), such as adjusting the padding w/out breaking label positioning, and other styles?

Is it recommended to drop down to overriding .scss vars, or is there some other intended consistent approach to adjusting padding/spacing.

![Example](http://i.imgur.com/8RvWa8s.gif)

**Comment by laicosly** [comment]
In _variables.scss why don't the textfield vars use !default?

```scss
/* TEXTFIELD */
$input-text-vertical-spacing: 20px;
```

To successfully override the mdl vertical-spacing, should this be:
```scss
/* TEXTFIELD */
$input-text-vertical-spacing: 20px !default;
```

**Comment by Garbee** [comment]
Modifying styling is up to you to figure out. We provide Material Design aligned styling. If you need something else, it is on you. You can use StackOverflow for support questions like this.

**Comment by laicosly** [comment]
Fair enough, I'd suggest that the css could've been better, relying less on scss var based calculations.
