### ISSUE TITLE
[Component Request] {Calendar}

### ISSUE THREAD

**Issue by jason-c-schmidt** [google/material-design-lite#1613]
* Description: A Calendar component, as simple as it is.
* Material Design Spec link example: https://dribbble.com/shots/2193237-Full-Calendar-Events
* Use Case(s): A Calendar Component called by the name calendar that allows the user to see dates back and forth, click on a day as a link to show appointments and schedule.

Thanks.

**Comment by Garbee** [comment]
Duplicate of #782

**Comment by Garbee** [comment]
Oh wait, checking the dribble this isn't a duplicate since it isn't for the input type=date type thing. However, until we have a Material Design spec for calendar one won't be included here.

**Comment by jason-c-schmidt** [comment]
Ok. If you need any help, I can contribute, I'm a java programmer.
