### ISSUE TITLE
Mac touchpad tap instead of click does not trigger animation on buttons

### ISSUE THREAD

**Issue by babakness** [google/material-design-lite#1616]
On a Mac, Yosemite 10.10.2, using the touchpad, if one taps the pad instead of a full click, the button animation is not trigger. On a full click, pressing down on the pad and getting "click" it does work.

This is inconsistent with Polymer's implementation of button, ie paper-button, where a tap on the touchpad trigger animation at the place of the pointer.

**Comment by surma** [comment]
One of our oldest bug that just won’t go away :( Duplicate of #376.
