### ISSUE TITLE
Hamburger icon disappears when viewing page in device emulator ( Chrome )

### ISSUE THREAD

**Issue by paran0a** [google/material-design-lite#1624]
Hi , when I use device emulator in chrome on this page.

http://www.getmdl.io/components/index.html#layout-section/layout

The hamburger icon is gone. You can still activate navigation but the icon is invisible.

**Comment by surma** [comment]
Works for me 
<img width="439" alt="screenshot 2015-09-22 13 07 48" src="https://cloud.githubusercontent.com/assets/234957/10016948/f2b3922c-612a-11e5-811b-44af2d34fdca.png">

Do you have any error messages in the console?

**Comment by paran0a** [comment]
http://i.imgur.com/VGZ4ta5.png

Hm  , could it be that since I'm connected through Kerio client that it blocks font face?

**Comment by surma** [comment]
That’s exactly what I did, @paran0a. Maybe @sgomes can give this a try, but I’m afraid this is a problem on your end :confused:

**Comment by sgomes** [comment]
@paran0a Are you talking about the hamburger icon on the layout demo? If so, it's right there on your screenshot, only hard to see because it's overlaid on top of the building in the image.

**Comment by sgomes** [comment]
@paran0a @surma Just tried this and it shows up for me as well :-/

**Comment by paran0a** [comment]
I tried this at home and it works. It must be something with my network on work I guess.

Thank you for the help and tests!
