### ISSUE TITLE
Feature Request: "mdl-cell--0-col-phone" Hides/DisplayNone Inner HTML

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#1626]
For example, you want typography hidden completely on phone screens, it would be nice to have mdl-cell--0-col-phone markup simply hide the desktop-only content.

**Comment by surma** [comment]
We do have `mdl-cell--hide-desktop`, `mdl-cell--hide-tablet` and `mdl-cell--hide-phone` in our [grid](http://www.getmdl.io/components/index.html#layout-section/grid) already. Does this solve your problem?

**Comment by rhroyston** [comment]
Yes.  Ooops, forgive me.  Thanks Surma.

**Comment by rhroyston** [comment]
Maybe have mdl-cell--0-col-phone alias mdl-cell--hide-phone?

**Comment by Garbee** [comment]
No reason for aliases. They add extra bloat for no real purpose. The only aliases that currently exist (in footer component) are due to naming  issues in the initial release that we can't remove until 2.x.

**Comment by rhroyston** [comment]
mdl-cell--0-col-phone is inline with existing nomenclature mdl-cell—N-col-SCREENTYPE.

 

To remove bloat get rid of 


mdl-cell--hide-desktop

Hides the cell when in desktop mode

Optional on "inner" div elements


mdl-cell--hide-tablet

Hides the cell when in tablet mode

Optional on "inner" div elements


mdl-cell--hide-phone

Hides the cell when in phone mode

Optional on "inner" div elements

**Comment by surma** [comment]
Although I actually kinda agree that it would be more inline with the rest of the naming, I feel like it is not good on a semantic level. People could get confused about what `0-col` actually means.

In any case, we can’t remove anything anymore before v2 and I think the gain is very minimal.

**Comment by Garbee** [comment]
It wouldn't be removing anything to add the 0 columns. It would however, add more weight to what we provide for no gain other than some miniscule level of semantics that doesn't matter.

**Comment by surma** [comment]
@Garbee I think in his second answer @rhroyston suggested _replacing_ our current classes just GitHub hid that because it looks like a quote.

**Comment by Garbee** [comment]
IMO replacing is a bad idea. Less semantic overall. Hide is much more clear
to intent. But, no aliasing and can't think about the change until 2
anyways...
