### ISSUE TITLE
checkbox is not rendered when using with Angular.js view template

### ISSUE THREAD

**Issue by jma7889** [google/material-design-lite#1627]
<label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-33">check box value: 
                <input type="checkbox" id="checkbox-33" class="mdl-checkbox__input" />
</label>

When the above code put in a view template, the checkbox icon effect is not rendered, need to refresh the page in order to get it rendered. Other components on the same page are rendered fine. 
![screenshot 2015-09-23 15 27 28](https://cloud.githubusercontent.com/assets/225801/10056117/cb66ab36-6207-11e5-9f5f-5c6707264473.png)
![screenshot 2015-09-23 15 27 44](https://cloud.githubusercontent.com/assets/225801/10056118/cb682ba0-6207-11e5-9c0c-a7b22f3ca555.png)

**Comment by surma** [comment]
As of now, MDL is aimed at static content and not for dynamic content. So we don’t have any support for Angular. However, I do know that there’ve been multiple people making it work properly with Angular over at StackOverflow. I’d suggest you take a look there or as your questions yourself using the `material-design-lite` tag.

**Comment by jma7889** [comment]
@surma Thank you very much for clearing it up and pointing direction. Yes, the issue is solved from an answer from http://stackoverflow.com/questions/31278781/material-design-lite-integration-with-angularjs
by Emjay

The method I use is adding following code to angular controllers

angular.element(document).ready( 
      function() {
        componentHandler.upgradeAllRegistered();
    });
