### ISSUE TITLE
Easier styling of radio buttons

### ISSUE THREAD

**Issue by kengruven** [google/material-design-lite#1631]
(This is either a feature request, or a documentation request.  Or both.)

I'm trying to put an MDL radio button on a dark background.  With some help from the online styling tool, I've been able to discover that I can re-color it by overriding these selectors in my CSS file:

    .mdl-radio__outer-circle
    .mdl-radio__inner-circle
    .mdl-radio__ripple-container .mdl-ripple

Unfortunately, there's one piece that I can't get to work right in all browsers.  The checkmark itself is white, and I can't figure out how to make it dark.

It gets this from the `.mdl-checkbox.is-checked .mdl-checkbox__tick-outline` selector, which has a `background`, which is a data: URI, which is an SVG of a checkmark, with style="fill:#ffffff" (wow!).  So that's white.  At least, it's white in Firefox and Explorer.  (Chrome and Safari seem to make it dark, or maybe just transparent, which is great, except I don't know why.)

I can't figure out any way to style the MDL radio button to make the embedded SVG take a different fill color, using only CSS.  None of the obvious things I tried (like `.mdl-checkbox.is-checked .mdl-checkbox__tick-outline` with `color` or `fill`).  I'm not sure if it's even possible to style an SVG-in-a-background-in-a-data-URI from (HTML) CSS.

Then I went looking at the online theme builder, on MDL's webpage, and I found that it actually writes out data URIs for the checkbox style!  Yeah, that'll certainly do it.

So: I wish there were an easier way to style MDL radio buttons.  It's not impossible to download the data URIs, decode them, change the colors, re-encode them, and insert them in my own CSS file, but it's not exactly easy, or well-documented.  Everything else in MDL I've been able to style by poking around with my DOM inspector, finding the class name, and then applying my colors to that class.  It would be great if radio buttons were equally easy to style.

We're already loading material-design-icons, for example, which has a ligature which is extremely similar to this icon.  Or we could just build the SVG with JS, because we're doing a bunch of other stuff in JS, already, and it's a tiny image.  I can put together a PR if you let me know that a particular approach might be preferred.

Thanks!

**Comment by sgomes** [comment]
Hey @kengruven,

I'm a bit confused by your question, since you seem to be discussing both checkboxes and radio buttons, which are styled differently. Could you clarify?

In any case, MDL was mostly designed for customisation at the SASS level; we have a number of variables there that should help! Doing it at the CSS level may be quite hard in cases like this, since our main focus was following the spec, not making it customisable.

**Comment by Garbee** [comment]
I believe a better action here would be to make a modifier for dark backgrounds with these components.

Making it "more customizable" is iffy at best. It already is since you can just overrule our CSS on your own and do what you need to.

**Comment by sgomes** [comment]
Having dark versions of the components as defined in the spec is something that would be nice at some point, yup.

**Comment by sgomes** [comment]
Closing in favour of #328.
