### ISSUE TITLE
Pseudo state on Buttons not working

### ISSUE THREAD

**Issue by tomatau** [google/material-design-lite#1633]
Have created a PR #1632 

The problem becomes apparent when you set custom hover/focus/active colours for the buttons.

They work fine for raised, colored and flat buttons. But primary and accent buttons do not get the pseudo classes applied as they have too high specificity.

To see the problem:
```scss
$button-hover-color: unquote("rgb(#{$color-primary-dark})");
$button-active-color: unquote("rgb(#{$palette-red-500})");
$button-hover-color-alt: unquote("rgb(#{$color-primary-dark})");
$button-active-color-alt: unquote("rgb(#{$palette-red-500})");
```

**Comment by sgomes** [comment]
This should be fixed now.
