### ISSUE TITLE
How can do responsive design like bootstrap?

### ISSUE THREAD

**Issue by Pantic14** [google/material-design-lite#1634]
In bootstrap i can do responsive design. For example like this:
`<div class="col-xs-6 col-md-4">.....</div>`
How can do this in mdl?

**Comment by hebbet** [comment]
for support question use StackOverflow. Using the `material-design-lite` and any other applicable tags to get the best support in implementing MDL in projects.

**Comment by surma** [comment]
For completeness sake: That’s explained in the grid’s docs http://www.getmdl.io/components/index.html#layout-section/grid
