### ISSUE TITLE
Question: Use case for button colours.

### ISSUE THREAD

**Issue by tomatau** [google/material-design-lite#1636]
I'm attempting to customise the theme... but the colours seem to overlap and be hard to understand when it comes to combinations of primary/colored/accent/raised and the various pseudo selectors.

I tried to make a table for each and just got lost with making the colours work for all permutations.

So - questions:
- what's the use case for `colored` vs `primary`?
- how come most buttons don't have hovered states in the demo?
- is there an overarching method for using `primary-color`, `secondary-color` and the `alts` for each? e.g. keeping both `primary` and `primary-alt` both the same contrast? Seems like certain pseudo states seem to assume dark or light contrast. 
- Or is there some advised strategy to make a theme including pseudo states whilst keeping all the permutations of these buttons aesthetic?

**Comment by surma** [comment]
> what's the use case for `colored` vs `primary`?

They have different semantics. `mdl-button--colored` picks the right color based on the type of button (e.g. it will pick the primary color for a flat button, but the accent color for a FAB).

> how come most buttons don't have hovered states in the demo?

We implemented the buttons’ hover states as they are defined in [the spec](https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons).

> is there an overarching method for using `primary-color`, `secondary-color` and the `alts` for each? e.g. keeping both `primary` and `primary-alt` both the same contrast? Seems like certain pseudo states seem to assume dark or light contrast. 

Don’t quite sure what you mean, sorry :( The colors are chosen from the palette after talking to the MD team how to get an acceptable color combination.

> Or is there some advised strategy to make a theme including pseudo states whilst keeping all the permutations of these buttons aesthetic?

To be honest, I think you either have to choose from our color wheel or run the SASS compilation yourself with the [color variables](https://github.com/google/material-design-lite/blob/master/src/_variables.scss#L91-L93) set appropriately.

**Comment by tomatau** [comment]
>To be honest, I think you either have to choose from our color wheel or run the SASS compilation yourself with the color variables set appropriately.

I'm currently attempting to use colours defined in the _color-definitions file and compiling my own sass.. but it's very tricky to get a good combo and understanding how each of the colours affects all different states. This is what lead me to ask this issue :confused:

**Comment by surma** [comment]
@tomatau We really didn’t document the SCSS well as we didn’t consider it a major use-case for external people. We have understood by now that this was probably a mistake and are already collection things we want to do differently in this regard for v2.

**Comment by surma** [comment]
I’m closing this as I hope I solved your question. Feel free to re-open if that is not the case.
