### ISSUE TITLE
Not working as expected with the latest mdl lib

### ISSUE THREAD

**Issue by bitcubate** [google/material-design-lite#1637]
Hi, 

This template is not working as expected with the latest mdl lib. Menus disappear.

Could you update? Or even better could you update and also make it look like the newer android.com website?

**Comment by surma** [comment]
Can you give us a few more information about your Browser and OS version? Menus are working fine for me on the Android template.

**Comment by bitcubate** [comment]
Hi Surma

My apologies, it was a local caching issue, works as intended - even with the latest versions. Kindly close this issue. Thanks for the prompt response.
