### ISSUE TITLE
Infinite scroll, lazy load, or popup-overlay not working with MDL

### ISSUE THREAD

**Issue by sevekim** [google/material-design-lite#1640]
Hi.

So, I have a very simple google materials design lite framework for my site (nothing installed but the sample theme from the google site).

However, whenever I use either infinite scroll or lazy load, or popup-overlay, they simply do not work as if they are stuck on the initial view point.

I can provide examples but is anyone else having same issues as me?

Thanks

**Comment by surma** [comment]
MDL currently focuses on static content. Techniques like lazy-loading or infinite scrolling are therefore not as well supported. However, I know multiple people have asked the same question before (see closes issues) and people on StackOverflow have gotten it to work. I suggest you head over there and ask this question again using the `material-design-lite` tag, as this issue tracker is for MDL issues only.
