### ISSUE TITLE
Components rendering error.

### ISSUE THREAD

**Issue by rukshn** [google/material-design-lite#1641]
I'm using material design lite together with RactiveJS kinda like React to make a single page app. When the components are in the initial page it's fine, but when I change the route and go to a different state the components doesn't render properly. Specially text boxes.

They show like the image attached. Any fix guys?

![screenshot from 2015-09-27 12 39 00](https://cloud.githubusercontent.com/assets/2173259/10121659/d068a3f4-6514-11e5-90f8-06eba1abcacd.png)

**Comment by surma** [comment]
MDL currently focuses on static content. Frameworks utilizing dynamic loading like React (or clones thereof) are therefore not directly supported. However, I know multiple people wanted to do similar things (see closes issues) and people on StackOverflow have gotten it to work. I suggest you head over there and ask this question again using the `material-design-lite` tag, as this issue tracker is for MDL issues only.
