### ISSUE TITLE
Can not clear text field

### ISSUE THREAD

**Issue by res2k** [google/material-design-lite#1642]
Clearing a text field (call `change("")`) does nothing as change internally does `if (value) { ... }`.
Manually clearing `input_.value` before calling `change()` makes everything appear as expected.

Suggestions: either allow empty strings in `change()` or add a method `clear()`.

**Comment by surma** [comment]
Good catch! Definitely a bug. Thanks for reporting.

**Comment by surma** [comment]
I’ll leave it up to @sgomes to decide wether this still makes the cut for 1.0.5 or not.

**Comment by sgomes** [comment]
Good catch indeed, thanks @res2k! I'll fix this for 1.0.5.

**Comment by surma** [comment]
#1646 landed. Closing :)
