### ISSUE TITLE
Navigation Drawer and Header Pop

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#1656]
At the moment, the initial CSS pushes the header to the right by adding a margin to account for the nav drawer.

This is removed by JS once it kicks in, but this causes a pop on load.

Originally reported on Web Fundamentals.
https://github.com/google/WebFundamentals/issues/1869

**Comment by surma** [comment]
The drawer is being moved out of the frame later by a `transform`.

@addyosmani @sgomes Should we add a style hiding the drawer element until `is-upgraded` is added?

**Comment by sgomes** [comment]
@surma Yup, that's the solution I've already coded :)

**Comment by surma** [comment]
Go @sgomes! :clap:

**Comment by gauntface** [comment]
Is this ok to get into 1.0.5?

**Comment by sgomes** [comment]
Yes, it's already merged into the `mdl-1.0` branch and will make it to 1.0.5.

**Comment by surma** [comment]
Closing this as #1657 has landed.
