### ISSUE TITLE
Scrolling of nav drawer via mouse / touchpad doesn't work with overflowing content

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#1659]
If you visit this page and adjust your viewport such that the nav drawer overflows the scrollbar will display, however you can't scroll it with a mouse wheel or touchpad.

https://material-dot-web-central.appspot.com/web/resources/styleguide/

I'm trying to figure out what exactly is causing this but I can't find any way of making this work.

**Comment by surma** [comment]
Will be fixed once #1652 lands
