### ISSUE TITLE
Shadows broken on Android Chrome

### ISSUE THREAD

**Issue by cdiener** [google/material-design-lite#1662]
![bug](https://cloud.githubusercontent.com/assets/7153935/10166903/d4b061e0-668b-11e5-86bd-6050cf6b1d7f.jpg)
On Chrome for Android Shadows do not render correctly. They are shown as a series of transparent gray boxes which looks pretty ugly, especially for deeper shadows. 

This was observes on Android 5.1.1 with the stock Chrome (42).

Edit: Added screenshot of getmdl.io that illustrates the problem.

**Comment by hebbet** [comment]
your chrome is outdated.

**Comment by cdiener** [comment]
Updating Chrome to the latest version available did not fix the issue for me.

**Comment by surma** [comment]
I can’t reproduce on Android 5.1.1 with Chrome 45.0.2454.94. 
![screenshot_2015-09-30-11-51-57](https://cloud.githubusercontent.com/assets/234957/10189974/e0066f7e-6769-11e5-911f-9643c3f24e0f.png)

I’m pretty sure there’s something weird on your end, but I have no idea what it could be. I’m closing this issue, but please re-open if this does turn out to be a bug in MDL itself.

**Comment by cdiener** [comment]
Well, it's not 'weird'. It has to do with hardware acceleration on Chrome. The way you implemented shadows with three overlaying transparent box shadows puts a lot of work on the renderer so Chrome sends the alpha blending of to the hardware and how that will be handled is completely device specific. That's why it looks like that in my somewhat slow Moto G 3rd gen and looks a bit better on your device. The same effect will not appear on Firefox or Webview but MDL will lag while scrolling on there. So right now shadows will only render well on Chrome on high- end devices but detoriate on low-end hardware. I consider that an issue since the way it is implemented now there is no way to guarantee consistent rendering across devices.

**Comment by surma** [comment]
Interesting. I was not aware of this. @addyosmani @sgomes, WDYT?

**Comment by cdiener** [comment]
Thanks a lot for looking into this. Playing around a bit more I found that enabling "slimming paint phase 2" in the Chrome flags of the dev version (47) fixes the issue. So the problem lies with the compositor. Ergo this might be a bug in Chrome or Android but it might affect several devices at least until version 47+ of Chrome. Based on that I think that MDL is probably not the right place to fix this but maybe something to be aware of.

**Comment by cdiener** [comment]
Just for the sake of being complete. The issue is now fixed on current Chrome versions on Android due to an overhaul of the render tree in Chrome.
