### ISSUE TITLE
Link to CSS hosted on your CDN not working

### ISSUE THREAD

**Issue by watlandc** [google/material-design-lite#1664]
MDL CSS link 

https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-pink.min.css

I noticed the link was dead when trying the CodePen examples.

**Comment by nikhildev** [comment]
I notied the same thing. 1.0.4 works though.

**Comment by surma** [comment]
We believe we fixed the issue (and updated our process to avoid this happening in the future. Sorry)!
