### ISSUE TITLE
Dynamically opening mdl-layout--fixed-tabs

### ISSUE THREAD

**Issue by gjuchault** [google/material-design-lite#1665]
Hi
I'm starting a new issue following this one : https://github.com/google/material-design-lite/issues/1165.

I would have love to get more possiblities to make mdl dynamic; but 

Since this commit d45ab80, MaterialLayoutTab is not exposed, so the solution before does not work anymore.

Actually, I need to edit the material.js file to add `window.MaterialLayoutTab = MaterialLayoutTab;` after MaterialLayoutTab declaration, which is pretty ugly.

Could you make it available again ?

I do know that you want mdl to be used statically only; and some of you already gave me the advice to switch on polymer. But I do think you should try to improve `upgradeElement` to make it available to tabs/fixed tabs..

**Comment by surma** [comment]
I think this is completely fair and – honestly – was an unintended side-effect of d45ab8000c25f6ab5f160d8d92606552d3740781. 

If no one objects (@addyosmani, @sgomes, @Garbee), I’ll re-expose `MaterialLayoutTab`.

**Comment by sgomes** [comment]
Thanks, @surma, let me know if you need any help with the Closure bits.
