### ISSUE TITLE
Collapsible Header + Search Field Issue

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#1669]
If you have a collapsible header and and search field, the header will un-collapse when the search field is focused.

**Comment by surma** [comment]
Hm, I’m not 100% sure this is unintended (@sgomes?).

But if it is, it was most likely introduced way-back-when with #86, which implemented header-expansion on click.

**Comment by surma** [comment]
... I guess a possible fix would be to catch click events on input fields in the header bar and stop bubbling. Not sure if this is desirable, though. I’ll wait for the rest to chime in here.

**Comment by sgomes** [comment]
I don't see this as unintended behaviour. Any interaction with the header should expand it, imho.

**Comment by gauntface** [comment]
It feels weird on Web Fundamentals, feel free to close if you disagree.

**Comment by sgomes** [comment]
I think it's the correct default behaviour, but I agree it might be odd in some sites :) You should be able to override it with a click handler, though.

@addyosmani, WDYT?

**Comment by surma** [comment]
I tend to agree.

@gauntface In any case: You could include something like [this codepen](https://codepen.io/surma/pen/ZbLveb).

**Comment by Garbee** [comment]
FTR (again) our search in navbar is far from MD compliant. It may be best if WF really wants proper search by the spec to build their own search design. I have some functioning code that can be used as a jumpstart (but it does have its own issues that will need working out.)

**Comment by gauntface** [comment]
WF has a limitation on JS, but the MDL stuff is fine, so custom stuff isn't too much of an option. It's not a deal breaker, I just thought it was an unusual / undesirable behaviour.

Like a said - if it's intended, happy to to close the bug.
