### ISSUE TITLE
Does footer go inside "main" or mdl-layout?

### ISSUE THREAD

**Issue by salamanders** [google/material-design-lite#1670]
http://www.getmdl.io/components/index.html#layout-section/footer doesn't show where "footer" goes inside.

**Comment by Garbee** [comment]
It goes inside of `mdl-layout__content`

**Comment by salamanders** [comment]
So "footer" is inside mdl-layout__content, but "header" is outside.  How strange!

**Comment by salamanders** [comment]
Oh funny. 
When it is inside, it scrolls off the bottom of the page.
When outside, it attaches to the bottom of the screen.
Good to document.

**Comment by acgourley** [comment]
Does anyone know how to make the footer both scroll off the page and be stuck at the bottom of the screen in the case when your app content is not very tall?

**Comment by sdcinglis** [comment]
You could play around with body min-height: 100% or 100vh.

**Comment by surma** [comment]
@acgourley I usually do what @sdcinglis suggested:
```CSS
body {
  min-height: 100vh;
}
```

**Comment by ChickenNuggers** [comment]
I also came across this issue when working with the `--fixed-drawer` because I noticed that the footer didn't have a left margin of 240px but it did when in `__content` but I prefer it to be on the bottom of the page.

**Comment by Garbee** [comment]
The core team is focusing on V2 work, therefore v1 issues that are non-critical won't be addressed. As such, closing this out. If someone from the community wants to improve the documentation here, `mdl-1.x` is open for PRs.

Thank you.
