### ISSUE TITLE
Tooltip and Menu conflict

### ISSUE THREAD

**Issue by genmacg** [google/material-design-lite#1673]
Attaching a tooltip to a button that also functions as the toggle for a menu causes an issue with already open menus. Clicking that button to open its attached menu the callback that was setup at the end of MaterialMenu.prototype.show is never called (on document.click) because I think the event propagation is stopped by the tooltip, therefore another open menu will not be hidden.

**Comment by Garbee** [comment]
The tooltip prevents propogation for touch to be handled properly. Maybe for using tooltip and menu together we can try to figure out something for making sure they fire in the right order? JS doesn't give us control over this unfortunately.

**Comment by genmacg** [comment]
Preventing propagation is quite unfortunate because none of our my events are picked up that are not attached to the element directly but I fully understand the reasoning behind it.

**Comment by Garbee** [comment]
Closing this issue out. There are other issues that were floating around discussing possible alternatives, although I don't think any can be implemented due to touch support.

Nothing we can feasibly do here to fix this.
