### ISSUE TITLE
Menu not scrolling with fixed header

### ISSUE THREAD

**Issue by DarienFord** [google/material-design-lite#1675]
I've come across an issue when you have a fixed header layout and a menu within the content for that layout.

I've put up an example here: https://codepen.io/anon/pen/MaJLNG

Just open the menu and scroll down and you will see the menu does not stay with the button which opened it.

**Comment by jfily** [comment]
Add position: relative; to the button's parent node

**Comment by DarienFord** [comment]
Awesome thanks jfily, that worked.

**Comment by jfily** [comment]
You're welcome
