### ISSUE TITLE
Fixed header goes white when menu opens

### ISSUE THREAD

**Issue by DarienFord** [google/material-design-lite#1676]
In relation to the other issue I opened, you will notice the header will go white when you click on the button with a menu assigned to it.

This may be as designed, but since using a menu is how it's been suggested we implement drop downs, it's causing some confusion.

You can see the issue here: https://codepen.io/anon/pen/MaJLNG

**Comment by surma** [comment]
This is – sadly – a Chrome-specific bug that we have reported upstream. There doesn’t seem to be anything we can do at this point.

**Comment by jjalonso** [comment]
This happen to me I dont know why without press any button, having fixed-header y transparent class. :S

**Comment by jjalonso** [comment]
I have a menu INSIDE the header but to me is not happening with the menu,

is hapening with a layer that i have in content that is fixed full screen and transparent, is fine, but when is display none and the header is one of the first element on the browser render, is white.

Adding position:fixed is solved.
