### ISSUE TITLE
Codepen buttons in the reference docs are not working anymore

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#1678]
This is since today's new UI redesign of Codepen which might have introduced a bug.

Filed this on Codepen's bug tracker since this must be on their side: https://bugcrowd.com/submissions/740a218bae3df924d0df4f9dd10adb635d65320e1249febf9678f9820fb16e76

**Comment by sgomes** [comment]
[Their samples](http://blog.codepen.io/documentation/api/prefill/) still seem to work, so there could be something we're doing differently that doesn't work anymore. Investigating.

**Comment by nicolasgarnier** [comment]
After some investigation it seems that posting to http://codepen.io/pen/define works but https://codepen.io/pen/define fails

**Comment by sgomes** [comment]
Closed since #1683 has been merged.
