### ISSUE TITLE
Badge colour isn't accent contrast colour

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1680]
Hi,

Text colour on badges is not correct... Content is unreadable when yellow is accent colour.

I think it should be the same colour as .mdl-color-text--accent-contrast class.

![issue](https://cloud.githubusercontent.com/assets/10220170/10245447/e3b0a9f6-6907-11e5-9acc-76d19f67d867.PNG) => ![correct](https://cloud.githubusercontent.com/assets/10220170/10245518/72b5e7d8-6908-11e5-9940-026087674504.PNG)

**Comment by surma** [comment]
That is definitely what should be happening here. Thanks for the issue, @jfily!

**Comment by Garbee** [comment]
@surma I went on ahead and did up a quick PR for this. #1775
