### ISSUE TITLE
Adding is-mobile, is-tablet and is-desktop

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1686]
Hi,

Can you please add classes is-mobile, is-tablet and is-desktop to the mdl-layout in addition to the is-small-screen class ?

Thank you.

**Comment by Garbee** [comment]
Probably best we don't add these. Eventually this system will be phased out entirely. You should be using media queries to target different device types.

**Comment by jfily** [comment]
So, why is there a is-small-screen class ? Is it going to disappear ?

**Comment by Garbee** [comment]
I can't say for sure. But it should with the layout refactor in the next major.
