### ISSUE TITLE
Slider demo page seems to be broken on getmdl.io

### ISSUE THREAD

**Issue by not-much-io** [google/material-design-lite#1687]
http://www.getmdl.io/components/www.github.com/google/material-design-lite/src/slider/demo.html This link is on the components -> slider -> more information page.

Sorry if this is not the right place to report this.

**Comment by addyosmani** [comment]
@sgomes are these links from an old build or are they expected to still work on prod today?

**Comment by sgomes** [comment]
Old links, didn't survive the redesign. We should do a pass looking for broken links, thanks @not-much-io !
