### ISSUE TITLE
Arrows on footer sections remains on desktop

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1688]
Hi,

If a footer section is deployed when the browser is less than 774px wide, the arrow remains if the browser is resized.

**Comment by surma** [comment]
Can you try and describe the problem you are seeing a little bit more? I can’t reproduce the problem from what you are saying:

![footer](https://cloud.githubusercontent.com/assets/234957/10305085/0e74929a-6c16-11e5-9fc1-82e3fe4c9f5d.gif)

**Comment by jfily** [comment]
Yep I can !

![bug](https://cloud.githubusercontent.com/assets/10220170/10305475/95551b5e-6c20-11e5-8b76-d49e9000e58a.gif)

**Comment by jfily** [comment]
up

**Comment by surma** [comment]
Thanks for the bump, @jfily. Got lost. Seems like this is a valid bug. Gonna look into it.

**Comment by jfily** [comment]
no problem :)

**Comment by sgomes** [comment]
Should be fixed now.
