### ISSUE TITLE
Color definitions in _variables.scss take strings instead of HEX colors. Why?

### ISSUE THREAD

**Issue by nicholaswmin** [google/material-design-lite#1689]
For some reason the color variables in `_variables.scss` take this format for color definitions:

`$color-primary: "0,0,0" !default; // supposed to be black`

which is really, really odd. I expected, at most, something along the lines of

`$color-primary: rgba(0,0,0,1) !default;`

====

My color variables are stored in another file called `_globals.scss` in which I store my variables in regular HEX format so I can easily reuse them in other places:

`$brand-primary: #FA3166;`
`$brand-primary-dark: #E02C59;`

I don't want to define 2 times my colours (1 HEX & 1 MDL-compatible RGB string). 

What's the reason for this anti-pattern? Am I missing something?

**Comment by surma** [comment]
I agree that it is somewhat of an anti-pattern and it’s not a solution we are really happy with, but for now, we have to stick with it. For the reasoning, see #146.

**Comment by nicholaswmin** [comment]
Thanks,

Might be a little crude but this is what I did to make it tick, 
in case anyone comes across this:

- **A SASS function:**
```
@function hexToString($hexColor) {
  // 0.999999 val in alpha actually compiles to 1.0
  $rgbaVal:  inspect(rgba($hexColor,0.9999999));

  // slice substring between 'rgba(' and '1.0)' 
  @return str-slice($rgbaVal, 6, str-length($rgbaVal)-6);
}
```

- **Usage in `_variables.scss` of MDL:**

```
$brand-primary: #333;
$color-primary: hexToString($brand-primary);
```
