### ISSUE TITLE
The scrollable tabs layout has its menu icon too high

### ISSUE THREAD

**Issue by hoschiCZ** [google/material-design-lite#1690]
I am trying to build a website utilizing the scrollable tabs layout.

I tried to remove or edit the icon, but its tag is generated on DOM load thus it's not possible to remove or alter it right in the code.

How to reproduce: Copypaste the scrollable tabs layout from http://www.getmdl.io/components/index.html#layout-section and add the standard header (charset, title, viewport, mdl stylesheet, mdl js, material icons, colors stylesheet).

I tested it on Chrome Linux desktop/Android and Firefox Linux desktop/Android.

![mdl-issue](https://cloud.githubusercontent.com/assets/8470346/10268118/0321490a-6aaf-11e5-9358-d2cea3e13eba.png)

**Comment by hoschiCZ** [comment]
Additionally, I want to remove the menu icon.

**Comment by hebbet** [comment]
for support question use StackOverflow. Using the `material-design-lite` and any other applicable tags to get the best support in implementing MDL in projects.

**Comment by addyosmani** [comment]
Imo, whether this is a bug on our end depends on how customisable we expect layout icon menu toggles to be. At present, it's non-trivial to figure out how to replace this without using JS to replace the node we inject. 

<img width="1139" alt="screen shot 2015-10-05 at 10 34 38" src="https://cloud.githubusercontent.com/assets/110953/10277254/bcc7387c-6b4c-11e5-9cfa-fef3038fdd30.png">

This is the type of 'magic' we should try to avoid in MDL 2.0 by allowing the user to get as much of the upfront HTML that's going to be generated as possible in our copy/paste snippets. That would enable customisations like the request from the OP to be a lot more straight-forward.

**Comment by hoschiCZ** [comment]
@hebbet I'm rather submitting bug and providing user experience than expecting support.

Looks like this won't be any type of counterpart to Bootstrap until 2.0.

**Comment by Garbee** [comment]
> Looks like this won't be any type of counterpart to Bootstrap until 2.0.


Our goal is *not* to  provide a  framework. They get bloated with a lot of extras that most developers don't need. We are providing a base Material Design experience with a set of components for different  parts of the specification.

**Comment by sgomes** [comment]
Out of scope for 1.x, will be addressed by layout revamp in 2.x.
