### ISSUE TITLE
Toggle buttons???

### ISSUE THREAD

**Issue by mrfaizanhaider** [google/material-design-lite#1691]
is there Toggle buttons available????

**Comment by Garbee** [comment]
Switches and radios are provided. Please check the documentation for more details.

**Comment by hebbet** [comment]
is it really so hard to click through the documentation?

http://www.getmdl.io/components/index.html#toggles-section/switch

**Comment by hebbet** [comment]
@Garbee you were a little bit faster ;-)

**Comment by mrfaizanhaider** [comment]
we need Toggle Button with groups...

**Comment by Garbee** [comment]
You can build grouping yourself. Unless there is a part of the material design spec I am unaware of.

**Comment by pdebruic** [comment]
@Garbee I think @mrfaizanhaider means this:

https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons
