### ISSUE TITLE
Drawer page refresh.

### ISSUE THREAD

**Issue by LukaszLabedzki** [google/material-design-lite#1693]
I have an issue with a Drawer. Whenever I add it to a code it renders a short while after rest of the page and when it loads it refreshes entire page. It's especially annoying when I have background video playing from start as it starts again after this refresh. Is there any way to avoid that?

Here is Drawer code:

            <div class="mdl-layout__drawer">
              <span class="mdl-layout-title">
              </span>
              <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="../about.html">About</a>
                <div class="storygami-drawer-separator"></div>
                <a class="mdl-navigation__link" href="../press.html">Press</a>
              </nav>
            </div>

**Comment by addyosmani** [comment]
I attempted to reproduce this issue using the code snippet you provided, but there unfortunately isn't enough there for us to see the issue you reported. Would it be possible to put together a [codepen](https://codepen.io/anon/pen/zvZVyQ) demo reproducing what you're seeing?

**Comment by Garbee** [comment]
I've seen this brought up before in another issue. The problem is the layout depends upon JS to do some calculations. The best thing to do would be to hook into `mdl-componentupgraded` event, check if the node is the layout, then trigger the autoplay.

**Comment by Garbee** [comment]
Closing this out due to long time with no response and it seems to be something that developers simply need to hook into our upgrade event to work around.
