### ISSUE TITLE
http://www.getmdl.io/templates/blog/index.html

### ISSUE THREAD

**Issue by gertcuykens** [google/material-design-lite#1697]
At 1024 px things start shuffling in different orders. Don't do that :)

![image](https://cloud.githubusercontent.com/assets/863731/10297091/e3c58d48-6bce-11e5-9d16-2b3f25897229.png)

![image](https://cloud.githubusercontent.com/assets/863731/10297096/ef0b7230-6bce-11e5-99b7-4f117e3e0cdb.png)

**Comment by addyosmani** [comment]
I'm pretty sure this is a bug, but will wait for a confirmation from @sgomes or @surma

**Comment by sgomes** [comment]
@surma Any idea what's happening here?

**Comment by surma** [comment]
[Working as intended](https://github.com/google/material-design-lite/issues/579#issuecomment-118785603).

**Comment by jfily** [comment]
@sgomes : 

![capture3](https://cloud.githubusercontent.com/assets/10220170/10308715/f70da6b0-6c37-11e5-882c-190102b3b3e0.PNG)
