### ISSUE TITLE
scrol jump http://www.getmdl.io/started/index.html#download

### ISSUE THREAD

**Issue by gertcuykens** [google/material-design-lite#1699]
http://www.getmdl.io/started/index.html#download

When you hover over the grey part it jumps to a download scrol position

![image](https://cloud.githubusercontent.com/assets/863731/10299600/2d4ba480-6bec-11e5-87c6-50306d129123.png)

**Comment by surma** [comment]
Could you maybe make a short video or something showcasing the issue that you are seeing? I tried hovering over (and clicking) different areas and have no scroll jumps whatsoever.

Also, could you give us your OS and browser version?

**Comment by gertcuykens** [comment]
It seems you have to click download button first, then it wil jump all over the place when you hover over it :) (chrome mac os)

![image](https://cloud.githubusercontent.com/assets/863731/10307013/6519bb7e-6c2b-11e5-9ad9-60d07d16fdae.png)

Ps how do you make this animated gif things?

**Comment by surma** [comment]
I am on Mac OS X and Chrome as well and still can’t reproduce (even after clicking the download button).

![scrolljump](https://cloud.githubusercontent.com/assets/234957/10307217/e120fc7a-6c24-11e5-9f59-8f2a00c66d40.gif)

(Made by recording my screen wit [ScreenFlow](http://www.telestream.net/screenflow/overview.htm) and then running `ffmpeg -i input.mp4 -vf scale=640:-1 -gifflags +transdiff -y output.gif`. You could even [optimize the palette](http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html), if you wanted to.)

**Comment by gertcuykens** [comment]
http://ovh.to/qKZEt4R

Version 46.0.2490.52 beta (64-bit)
Google Chrome is up to date.

**Comment by surma** [comment]
Sorry, I got no idea what’s going on at your end. I tried doing the exact same thing you are doing in the video, but I can’t replicate :disappointed:

**Comment by gertcuykens** [comment]
I think it is going to be specifically chrome beta version? It also doesn't happen in safari.

**Comment by surma** [comment]
Well, I did test on v45 and v48 (canary) and it works in both. Can you test on stable, please?

**Comment by jfily** [comment]
You should try with Firefox to see if it's a webkit problem...

**Comment by gertcuykens** [comment]
Stable is ok, closing and reporting to chrome
