### ISSUE TITLE
problem in android webview

### ISSUE THREAD

**Issue by amtr** [google/material-design-lite#1708]
Hi
I have problem with viewing websites made with mdl.
My problem is when I load the site with webview suddenly all of the site messes up wich is terrible.
I loaded the site http://getmdl.io in a webview but as you see everything lookes messed up (java script is enable too) can u help me?
![screenshot_ - - - - -](https://cloud.githubusercontent.com/assets/3998368/10360977/e44a6998-6db1-11e5-82ae-052997c4f2d0.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/3998368/10360978/e44d9442-6db1-11e5-8404-5e86c5341541.png)

**Comment by surma** [comment]
Hey @amtr, I tested our website in a few Android webviews and they look fine for me. Is there anything extraordinary you are doing?

**Comment by amtr** [comment]
@surma Tnx for your answer .I have tested this with android jelly bean and kitkat
but as you see the screen shot everythings messed up. can you show me the code that you wrote?
Maybe you have mentioned something that I didn't noticed

**Comment by surma** [comment]
@amtr To be honest I just used off-the-shelf apps that I knew used webview. However, I was on Lollipop and Marshmallow. Let me the older versions.

**Comment by surma** [comment]
So I was able to reproduce the issue with Jelly Bean webviews (but a much more trippy version :smile:). @gauntface kindly pointed out that if you are targeting the Jelly Bean API, even higher versions will exhibit this behavior. So KitKat should be working fine as long as you target that API.

There’s nothing you are doing wrong, it’s a shortcoming of the browser engine used in these webviews of Jelly Bean and blow. We will most likely not apply patches to the microsite for an old browser engine like this.
![androidwebview](https://cloud.githubusercontent.com/assets/234957/10457076/8bf619fe-71bc-11e5-993d-f56c7854d05a.gif)
