### ISSUE TITLE
Drawer does not scroll by mouse wheel on Chrome

### ISSUE THREAD

**Issue by gen0083** [google/material-design-lite#1711]
For example, mdl template [ANDROID.COM MDL SKIN](http://www.getmdl.io/templates/android-dot-com/index.html) drawer content does not scroll by mouse wheel in Chrome.
Use keyboard, I can scroll it.
Other browser (e.g. Firefox 41.0.1) can scroll it.

[Material design](https://www.google.com/design/spec/material-design/introduction.html) drawer content can scroll by mouse wheel. (I know this is not mdl)

I checked Chrome version below, these versions can't scroll by mouse wheel.
 45.0.2454.101 (64-bit) Mac
 45.0.2454.101 m (64-bit) Windows
 48.0.2527.0 canary (64-bit) Mac

Is this bugs in Chrome? or problem in mdl?

**Comment by surma** [comment]
No, my stupid code is to blame :smile: 

This got fixed in #1652 and will be live with 1.0.6
