### ISSUE TITLE
Missing non-prefixed font-feature-settings property in https://fonts.googleapis.com/icon?family=Material+Icons

### ISSUE THREAD

**Issue by rtm** [google/material-design-lite#1712]
The file https://fonts.googleapis.com/icon?family=Material+Icons has the line

    -webkit-font-feature-settings: 'liga';

But for IE compatibility we need another rule without the prefix:

    font-feature-settings: 'liga';

**Comment by surma** [comment]
That is something you should raise with github.com/google/material-design-icons rather than with us :) We are just another user of Material Design Icons :)
