### ISSUE TITLE
Is there a good reason to style tabs (bar, panel) only when 'is-upgraded'?

### ISSUE THREAD

**Issue by lastid** [google/material-design-lite#1715]
I'm managing the tabs behavior by myself so I don't need the component to be upgraded. Of course not using the `mdl-js*` class and adding `is-upgraded` by myself should be enough, but I think relying on javascript to style tabs can be a problem when it takes time to download the javascript file. In this case, we will see multiple panels at the same time until the javascript file arrives.
```
.mdl-tabs__panel {
  display: block;
  .mdl-tabs.is-upgraded & {
    display: none;
  }
  .mdl-tabs.is-upgraded &.is-active {
    display: block;
  }
}
```

**Comment by surma** [comment]
That is some extraordinarily old code (January!) :smile: We tried to avoid relying on the `is-upgraded` class, but we didn’t have these kind of guidelines when we started. I don’t see any reason why we would need to rely on this class here, but I will refer this to @sgomes if he remembers anything. We might be able to remove this :)

**Comment by sgomes** [comment]
Sadly, we need to leave this in place for graceful degradation in older browsers that don't pass our JS mustard test. Those browsers get MDL JS features disabled, so we need to display all of the content, so that we have some amount of support for them.

**Comment by surma** [comment]
Ah! So there was a reason. Thanks for clarifying, @sgomes :)

**Comment by lastid** [comment]
That's sad. Is it only because of classList not supported by IE9?
If it's the case, I would trade some lines of helper code for not having a chance of seeing multiple panels at the same time, then some of them disappear.

Example:
`ripple.classList.add(ctx.CssClasses_.MDL_RIPPLE)`
vs
`MDL.removeClass(ripple, ctx.CssClasses_.MDL_RIPPLE)`

But well, I went to a different road so it's doesnt matter to me.

**Comment by surma** [comment]
@lastid No, it’s because we will only *hide* the other tabs if the JS is actually running (which we determine with the `is-upgraded` class). If the JS is not running, all content will be shown at the same time.

**Comment by lastid** [comment]
@surma Here is an example:
Code: http://jsbin.com/wehacinave/edit?html,output
Output: http://output.jsbin.com/wehacinave
Please view output page with cache disabled with Chrome, if you have a great internet connection, please throttle it like 2Mbps and Ctrl+Shift+r many times.

What happen is: when the html and css arrive, all names of 3 houses are visible and the Starks are at the beginning, after 0.3s (it can vary) the javascript file arrives, the needed class is applied and the names of 2 houses disappear, only the Lannisters are visible.

So you will see a *Flash of unstyled content* in this short time. And it's bad.

**Comment by Garbee** [comment]
I think this is a pitfall of progressive enhancement over graceful degradation.

That being said, I'd rather we keep doing things as they are now and look into possible changes later when we drop older browser support.

**Comment by surma** [comment]
@Garbee @lastid 

A possible workaround would be to give the developer the choice of graceful degradation vs. FOUC by adding a `mdl-tabs--unresolved` class. That class would hide all content until `is-upgraded` has been applied.

Not sure that’s something we want to go for, though.

**Comment by Garbee** [comment]
@surma I'd rather we not introduce behavior like that. It would lead to "when do I use X over Y" too much, among just more maintenance and debugging with issue reports. I think developers can implement user-land fixes to this on their own if needed.

**Comment by lastid** [comment]
I'm the only one who complained and already found a workaround, I dont mind if nothing is changed. So let developers find their way. See if someone shows up in this issue.

What bothers me is the approach, mdl sacrifices good experience in modern browsers, most of people can see the FOUC problem, for a confusing screen in old browsers (minority). And these 2 problems can be avoided by a few lines of code.

As you said, this will be fixed in the future. So we can move on :)

**Comment by Bilchenko** [comment]
Hi, I have same problem. I think, I have delay, because my page use Google Analytics in production and Visual Studio Browser Link in design. 
I have idea use same css without is-upgraded. What is your workaround?

**Comment by Garbee** [comment]
@Bilchenko Please use StackOverflow for support.
