### ISSUE TITLE
Menu scroll non-functional on small screens

### ISSUE THREAD

**Issue by listedegarde** [google/material-design-lite#1716]
**Issue:** when a screen is to small (height), one cannot scroll the menu without clicking and draging the scrollbar.  Tested in Chrome on Linux and Mac.  It's a major problem on Mac because the scrollbar is invisible, so the user is unable to scroll the menu at all.

**To reproduce:** Visit [this page](http://www.getmdl.io/templates/dashboard/index.html) and shrink the browser to <= 600px heigh.  Try scrolling the menu on the left with the mousewheel or trackpad.

**Tested on:** Chrome Ubuntu, Chrome Mac.  Reproducible 100% of the time.

I haven't taken the time to do any tests yet: I thought I'd through this out in case someone else has come across the same issue.

**Comment by surma** [comment]
Already fixed on master (see #1652) :)

**Comment by listedegarde** [comment]
Thanks!  In 1.0.6?  It's not working for me in 1.0.5.

**Comment by Soubkia** [comment]
Also not working for me in 1.0.5? Is the bower package up to date?

**Comment by listedegarde** [comment]
I can confirm that it does work if you clone and gulp the code.  So this should arrive in 1.0.6 @Soubkia

**Comment by surma** [comment]
Yes, sorry, my bad. It didn’t make it into 1.0.5. Will be in the next release :)
