### ISSUE TITLE
Unintentional bullets in the footer of the getmdl.io Styles page.

### ISSUE THREAD

**Issue by pdxbmw** [google/material-design-lite#1719]
There appears to be a [broadly written CSS rule](https://github.com/google/material-design-lite/blob/e6317bed83bea3ca23a19fcb045ff9658f0e9341/docs/_assets/main.css#L904) affecting the footer of the [Styles](http://www.getmdl.io/styles/index.html) page. The footer list items display bullets not visible on other pages. I believe the bullets are only intended for the **.content** section (`.styles .content li:before` rather than the current `.styles li:before`).

**Comment by surma** [comment]
Thanks for the issue! This has been fixed in #1709 already, just haven’t deployed the website yet :)

**Comment by pdxbmw** [comment]
👍
