### ISSUE TITLE
Should $button-padding be 16px as per material design specs?

### ISSUE THREAD

**Issue by lastid** [google/material-design-lite#1720]
Right now it's 8px.

**Comment by surma** [comment]
Can you link to the part of the spec where you get the 16px from? I looked [here](https://www.google.com/design/spec/components/buttons.html#buttons-usage) and it says 8px.

**Comment by lastid** [comment]
Yep. You linked to the *Flat buttons in dialogs* , mdl doesn't have dialogs, yet. Search in the same page for *Default Button*.

**Comment by surma** [comment]
I see. Seems legit to me. Waiting for @sgomes to confirm.

**Comment by Garbee** [comment]
Changing to 16px sgtm. Referring to the padding displayed in the density section of the linked page.

**Comment by sgomes** [comment]
Good catch, I had no idea these two types of buttons had different paddings! We should change it to 16px.
