### ISSUE TITLE
Use of "disabled" attribute on "li" elements

### ISSUE THREAD

**Issue by jbellsey** [google/material-design-lite#1722]
In the MDL spec, to disable a menu item, we're told to put the `disabled` attribute on the `li`. The presence of the attribute is used in the MDL code with a DOM query on `getAttribute('disabled')`. 

However, the HTML spec doesn't grant `li` access to the attribute ([here](http://www.w3.org/TR/html5/disabled-elements.html)).

This would just be an abstract comment, if it weren't for how this plays with Aurelia. That framework is filtering out the application of the `disabled` attribute on elements that don't specifically support it. So I can't actually disable my menu items.

I will pursue this with the Aurelia team, but a more robust solution would be to use a class on the `li` for DOM querying.

Thoughts?

**Comment by surma** [comment]
You are right, `disabled` is – strictly speaking – invalid on `<li>`.

We have had a similar request with the `for` attribute on `<ul>` that got fixed in #1651. I think we *could* do the same here and add `data-disabled` as an alternative to `disabled`.

@sgomes @Garbee WDYT?

**Comment by Garbee** [comment]
SGTM on data attribute. I have a small concern on not namespacing the  since collisions on broad selections are possible. Just a thing to ponder. Maybe we should do `data-mdl-disabled`?

**Comment by surma** [comment]
@Garbee I see your point, but we also did `data-for`. Also, if another framework happens to be using `data-disabled`, I feel like there would be no *semantic* mismatch.

**Comment by jbellsey** [comment]
Thanks. I have to throw in a pitch for namespacing... a client app may well do its own DOM queries on `data-disabled` for its own needs. Not the most likely collision in the world, but heck, you've namespaced every CSS class with BEM, why not your special-purpose attributes as well? Namespace all the things :)

However you want to go, I appreciate your work on this!

**Comment by Garbee** [comment]
@jbellsey pointed out exactly what I am worried about. `data-disabled` is fairly generic. Who knows what custom app code or other packages that exist which try to take advantage of that. Then say someones app is calling `document.querySelectorAll('[data-disabled]')`... boom, getting more stuff than you may want.

Too late to fix the namespace problem with `data-for`, but we can start here with a more specific pattern.

**Comment by surma** [comment]
@Garbee Agreed.

**Comment by iliasch** [comment]
May I point out that changing 'disable' to 'data-mdl-disable' is a minor breaking change on its own, so you might as well consider changing 'data-for'  to 'data-mdl-for' as well to keep things uniform. Namespace is a feature of MDL, some people like it other don't, but still it should work the same way across all components. It's fairly easy for developers to adapt their templates anyway, just adding a word to the mix.

**Comment by Garbee** [comment]
We dont need to remove them. We can add or operators and allow any to be
used. Then later in 2 remove all but the namespaced data attributes. Also,
if data-for hasn't shipped yet we can just change it without worry.

**Comment by surma** [comment]
@Garbee Good point, `data-for` is on master! I’ll whip something up
