### ISSUE TITLE
Layout options documentation bug

### ISSUE THREAD

**Issue by Brahmasmi** [google/material-design-lite#1728]
**Bug**
In https://github.com/google/material-design-lite/blob/master/src/layout/README.md, ```mdl-layout__header--transparent``` is repeated twice.
```
| `mdl-layout__header--transparent` | Makes header transparent (draws on top of layout background) | Optional; goes on header element |
| `mdl-layout__header--transparent` | Uses a header without a shadow | Optional; goes on header element |
```
**Suggested Fix**
In the second instance, I think we are referring to ```mdl-layout__header--seamed```.

**Comment by Garbee** [comment]
Done in 1.0 branch. Needs merging into master and a site redeploy.
