### ISSUE TITLE
Not scrolling to the bottom of the page.

### ISSUE THREAD

**Issue by Errvald** [google/material-design-lite#1729]
Viewing the blog template:
http://www.getmdl.io/templates/blog/index.html 
with Device Mode on tablet/mobile in Chrome, it can only scroll down half the page.

**Comment by surma** [comment]
Can you be more specific about the bug? I can’t reproduce the issue you are describing.
![blogtemplate](https://cloud.githubusercontent.com/assets/234957/10433251/3127f678-7108-11e5-9f46-3526ac071304.gif)
