### ISSUE TITLE
mdl-js-layout class breaks css transition 

### ISSUE THREAD

**Issue by Archiolidius** [google/material-design-lite#1739]
I have page like this: 
```
<div class="mdl-layout mdl-js-layout page"></div>
```
and styles like this: 
```
.page {
  opacity: 0;
  transition: transform 1s linear;
  transform: translate3d(100%, 0, 0);
}
.page.active {
  opacity: 1;
  transform: translate3d(0, 0, 0);
}
```

So for showing page i add `.active` class using js. 

When I didn't have `.mdl-js-layout` class - everything was working, but with `.mdl-js-layout` class i cannot see slide effect.

Any suggestion how to fix it?

**Comment by Garbee** [comment]
Please use StackOverflow for support. You can use the `material-design-lite` tag along with any other appropriate tags. The issue tracker is for core MDL issues, not implementation and usage support.
