### ISSUE TITLE
Obfuscator fails to appear in iOS Chrome

### ISSUE THREAD

**Issue by sdcinglis** [google/material-design-lite#1742]
The obfuscator (semi-transparent black overlay) fails to appear when opening the drawer in Chrome for iOS. The background content is still scrollable and there is no way to close the drawer.

Using iOS 9.0.2 and Chrome 45.0.2454.89

**Comment by Garbee** [comment]
Sibling selector bug in iOS 9's webview (which Chrome must use on that platform.) Fixed in #1713
