### ISSUE TITLE
Disabled button behavior

### ISSUE THREAD

**Issue by faergeek** [google/material-design-lite#1743]
Buttons can be used not only on `button` or `input` elements, but on `a` tags too, so `auto` cursor is not enough for that, may be it should be `default`?

Also it probably should have `click` handler which will call `preventDefault` or may be better solution?
Anyway, there's `click` handler already, but it points to `emptyFunction` (why it's there at all?).

And the last thing, do you have some specificity problems?
I mean `.mdl-button[disabled][disabled]` selector.

**Comment by surma** [comment]
> Buttons can be used not only on `button` or `input` elements, but on `a` tags too, so `auto` cursor is not enough for that, may be it should be `default`?

If someone uses the button styles on something else than a `<button>` or a `<a>` I feel like it’s the developer’s job to take care of the correct cursor. We try to be as non-invasive as possible.

> Also it probably should have `click` handler which will call `preventDefault` or may be better solution?
Anyway, there's `click` handler already, but it points to `emptyFunction` (why it's there at all?).

Our button code doesn’t define a click handler nor do we define a `emptyFunction` function anywhere. Can you link me to the code where you saw that?

> And the last thing, do you have some specificity problems? I mean `.mdl-button[disabled][disabled]` selector.

Yes, we are bumping the specificity there to ensure that the disabled style take precedence over any of the other modifiers.

**Comment by faergeek** [comment]
>Our button code doesn’t define a click handler nor do we define a emptyFunction function anywhere. Can you link me to the code where you saw that?

Sorry, actually there's no such a function, it's something on my end.

>If someone uses the button styles on **something else than** a `<button>` **or** a `<a>` I feel like it’s the developer’s job to take care of the correct cursor. We try to be as non-invasive as possible.

Did not understand you, I'm talking about `<a>` tag actually and it "doesn't work out of the box".

Let's take a [button from bootstrap](http://getbootstrap.com/css/#button-element-1) as a reference, it explicitly sets `not-allowed` cursor, so it works smoothly with any element in theory, even `div` or `span`.

**Comment by surma** [comment]
@faergeek Didn’t realize you were talking about the disabled styles. I actually don’t think we have guidance on the cursor shape on disabled button, let me pull in @sgomes :)

**Comment by faergeek** [comment]
@surma It's just about idea of BEM to try to not depend on used tag, so if prop is modified, it should not fall back I think.

**Comment by addyosmani** [comment]
Afaik, there isn't yet guidance around cursor selection for disabled buttons. We could ask the MD team to confirm, but will await input from @sgomes in case he knows.

**Comment by faergeek** [comment]
In case if you don't have any guidance then I guess you should not touch cursor property at all, but that's true only in half. That's an issue actually. Inconsistency.

So the question is should the cursor be set to `default` or `not-allowed` instead of `auto` **or** should not be set at all?

**Comment by sgomes** [comment]
No guidance here from the spec, I'm afraid. This should have been set to `default` from the beginning, not `auto`. My bad, sorry!

`not-allowed` doesn't see a lot of usage and looks pretty scary, so I think we're best avoiding it.

**Comment by faergeek** [comment]
@sgomes Great! Thanks for response :+1: !

**Comment by faergeek** [comment]
Should I submit PR for that?

**Comment by surma** [comment]
PRs are always appreciated, @faergeek  :)

**Comment by faergeek** [comment]
Here it is #1749

**Comment by sgomes** [comment]
#1749 Merged. Thanks, @faergeek!

**Comment by faergeek** [comment]
Glad to help a great project to be a little better :+1:
