### ISSUE TITLE
FR: Material "Stepper" for a wizard-like sequence of steps

### ISSUE THREAD

**Issue by salamanders** [google/material-design-lite#1748]
It would make a nice addition to mdl, and (as I recently found out) is a pain to code yourself.

**Comment by surma** [comment]
As far as I remember, this is not listed as a component in the [MD spec](https://www.google.com/design/spec/material-design/introduction.html) which is what we are trying to adhere to. We provide all the elements you’d need to build this yourself, but something like this is way too high level to go into the MDL library itself – especially considering the “L” stands for “Lite”.

**Comment by janpieterz** [comment]
@surma I did find this link, suggesting otherwise: https://www.google.com/design/spec/components/steppers.html

**Comment by Garbee** [comment]
Ah, steppers were added to the spec this month. So, this is a good feature request for future inclusion.

**Comment by sgomes** [comment]
@Garbee Do you think this is something that should be merged with Dialog, or is it something functionally different, in your mind?

**Comment by Garbee** [comment]
Stepper is a completely separate spec from Dialogs. It is for actual wizards whether on-page or in a dialog.

I already have mostly-working JS (minus dynamically adding/removing steps from the process), just need to redo styles to adhere to MD. Not going to work on that though until 2.x's lifetime.

**Comment by sgomes** [comment]
Thanks, @Garbee! Let's keep this feature request open and separate, then.

**Comment by shivasurya** [comment]
Any improvement !?

**Comment by Garbee** [comment]
As I already said, no core effort is going into this until 2.x is released. We have bigger things to do than this.

Further, we probably wouldn't accept a PR for this before 2.x since things are going to change quite a bit for JavaScript it seems. This is a complex component we'd rather have done right the first time.

For now, this is left to userland implementations.

**Comment by addyosmani** [comment]
> Further, we probably wouldn't accept a PR for this before 2.x since things are going to change quite a bit for JavaScript it seems. This is a complex component we'd rather have done right the first time.

:+1:

**Comment by brianthelion** [comment]
+1 for steppers.

**Comment by shivasurya** [comment]
https://github.com/shivasurya/materialsteppers hey guys inspired and implemented for android! check it out if anyone needs

**Comment by Garbee** [comment]
@shivasurya This is a *web development* library, Android components aren't really useful for developers to integrate with their projects.

**Comment by shivasurya** [comment]
completely sorry for off topic ! btw if anyone interested in java,i hope they can follow.

**Comment by axdemelas** [comment]
My polyfill: https://axdemelas.github.io/mdl-stepper/

**Comment by eshansingh** [comment]
What's the status of this issue?

**Comment by Garbee** [comment]
No effort going towards implementing this currently. It will be done post-v2 launch.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/60
