### ISSUE TITLE
Make footer sticky via css so it isn't hanging out in the middle of the page waiting for the JS to load

### ISSUE THREAD

**Issue by NathanielHill** [google/material-design-lite#1751]
I noticed this when I added an external JS to my site that was slow to load and saw that the mini-footer was just hanging out in the middle of the page until the script finally loaded. There seem to be several pure css solutions for sticky footers, could one be added so that the footer looks nice while people with slow connections wait for the javascript? Also, it will degrade nicely for people who have js turned off.

**Comment by surma** [comment]
The footer itself does not require JS, layout however does. We have a major rework planned (#1735), which will address this.
