### ISSUE TITLE
Can't download mdl-templates.zip due virus warning.

### ISSUE THREAD

**Issue by bboerendans** [google/material-design-lite#1754]
Can't download the mdl-templates.zip (http://www.getmdl.io/templates/index.html). Chrome and Edge are removing it directly in case of virus detected.

**Comment by surma** [comment]
@bboerendans I can’t reproduce this. Both Chrome and Edge are downloading the ZIP just fine for me.

Is some antivirus software removing the zip file? Although it is curios that any antivirus software would be triggered by this zip as it contains HTML only.

**Comment by bboerendans** [comment]
Have looked a bit further. Windows Defender removes it, maybe a false positive?

Trojan:Win32/Spursint.A 
http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fSpursint.A&threatid=2147705703&enterprise=0

**Comment by surma** [comment]
Sorry, there’s nothing we can do. The ZIP file is completely harmless and normal, no executables contained within. Definitely a false positive.

**Comment by perosb** [comment]
FYI only, I'm getting the same in Windows 10 with Windows Defender removing the files.
Not sure if MS have a tool to report false positives.

**Comment by addyosmani** [comment]
@surma can we reach out to MS (twitter.com/reybango may be able to help route) to see if there's a route for libraries like ours to report such issues upstream?

**Comment by surma** [comment]
@addyosmani I’ll see if there’s something I can do

**Comment by Garbee** [comment]
Via gitter the other day someone said the latest definitions removed the warning. There is also [this form](https://www.microsoft.com/security/portal/developer/contactus.aspx) but it requires quite a bit of detail from the package maintainer reporting the problem.

**Comment by surma** [comment]
@perosb @bboerendans Would you be so kind and try again? Apparently, we have been fixed/whitelisted :tada:

**Comment by pepelsbey** [comment]
@surma, I have [the same problem](shower/issues/232) with harmless [shower.js] file. Could you please tell me how did you manage to solve this problem?

**Comment by Garbee** [comment]
@pepelsbey As far as we know, nothing was "done". MS eventually just figured it out (probably due to heuristics on flags.)

I linked to a form in a previous comment where package maintainers can submit false-positives. So check that out and see if it helps.

**Comment by pepelsbey** [comment]
@Garbee, thank you!

**Comment by WoLfulus** [comment]
This is still happening.

**Comment by Garbee** [comment]
Maybe something is going on with the newer zips for 1.1. But, there is nothing that we can really do here. It is up to MS to detect the false-positive and address it on their end.

**Comment by WoLfulus** [comment]
Yeah, I know.

But its more like a bug than a false positive. package.json is detected as a virus. LOL

The 3 files getting false-positive are:

- js/velocity.min.js
- js/waves.js
- package.js

**Comment by Garbee** [comment]
We don't provide `js/velocity.min.js` or `js/waves.js`... So what exactly are you downloading? If those are provided in the MDL zip you have then we may have an issue.
