### ISSUE TITLE
checkbox not controlled dynamically with angularjs

### ISSUE THREAD

**Issue by suman-mits** [google/material-design-lite#1757]
switches and I want to control their states dynamically through angularjs controller. But it is not working as expected.

I have the problem replicated on the following codepen. Can anyone help quick?
`<html ng-app="">
    <head >
        
        <script src="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.min.js">            </script>
        <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-pink.min.css">
        
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    </head>
    <body ng-init="check={}">
        <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="switch-1">
            <input type="checkbox" id="switch-1" class="mdl-switch__input" ng-click="check.set=!check.set" />
            <span class="mdl-switch__label"></span>
        </label>
        <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="switch-2">
            <input type="checkbox" id="switch-2" class="mdl-switch__input" ng-model="check.set" ng-checked="check.set"/>
            <span class="mdl-switch__label"></span>
        </label>
        {{check.set}}
    </body>
</html>`

https://codepen.io/anon/pen/pjWQZb

**Comment by Garbee** [comment]
Please use StackOverflow for support and implementation help. The issue tracker is for problems with the provided code.

**Comment by suman-mits** [comment]
I just wanted to know why the css doesn't change on a switch even though a normal checkbox works.
I still think it is an issue
