### ISSUE TITLE
Cannot use fonts 

### ISSUE THREAD

**Issue by christoga** [google/material-design-lite#1759]
Hello google team!
Let me introduce my self : 

I'm Christo from jakarta, 11 years old that codes.
I'm confused because I cannot added new fonts to my `mdl`

Please reply me here or andre.christoga@gmail.com
Thx! :smile:

**Comment by Garbee** [comment]
Please use StackOverflow for support. The MDL issue tracker is for problems with the code we provide, not implementation or usage help.
