### ISSUE TITLE
Drawer issue on chrome

### ISSUE THREAD

**Issue by appie18** [google/material-design-lite#1760]
I have already faced this issue with firefox, but thats because drawers arent supported by firefox.

Now am facing the same issue on chrome after getting the latest update.

Format: ![drawer gif](https://gyazo.com/9d90c560eb04b2ce30d28e300a0327c9.gif)

**Comment by surma** [comment]
Can you provide a (preferably minimal) codepen that reproduces your issue?

Drawers work just fine for me (in both Chrome and Firefox) so I’m tempted to think that some of your custom styles are interfering.

**Comment by appie18** [comment]
After a lot of trial and error I realized that I had "display:table" somewhere in a parent div, the thing thats really confusing me about this is that, with the same code that would break my drawer on chrome, it would work perfectly fine on safari. Anyway you can close this issue now.
