### ISSUE TITLE
Menu reloads the content

### ISSUE THREAD

**Issue by epablo** [google/material-design-lite#1763]
Hi guys, I have a strange bug: when I close a simple menu this reloads the page content, like a DOM update or something. Has anyone had a similar issue?

Thanks

**Comment by Garbee** [comment]
Can you provide an example on [codepen](http://codepen.io) please. The demos don't have this activity so everything should be working as intended.

**Comment by epablo** [comment]
Hi Garbee, sorry the delay, I've fixed it, the problem was related to Foundation tabs (I think so), modifying the z-index of the mdl menu to "1" fixes the issue.

Thanks
