### ISSUE TITLE
background-attachment: fixed doesn't seem to work

### ISSUE THREAD

**Issue by carlsim** [google/material-design-lite#1765]
Hi,

I have an issue creating a parallax scrolling website using the background-attachment: fixed; element. The issue I have is that when you scroll down, the image I placed using background: url() doesn't appear on larger HiDPI screens but works on MDPI screens. 

![screenshot 2015-10-17 at 11 46 39 pm](https://cloud.githubusercontent.com/assets/15127805/10562423/65d86f04-7529-11e5-9915-a788eb10c77c.png)

The empty white space should have an image there but doesn't. I narrowed it down to the .mdl-layout class and disabling both display: flex and display: webkit-flex. 

Is there a way to fix this?

I'm on an Acer 720 Chromebook running 46.0.2490.71 beta (64-bit) and also doesn't seem to work on different browsers and on other laptops (Macbook Air)

**Comment by Garbee** [comment]
Please use StackOverflow for implementation support. This issue tracker is only for core MDL issues.
