### ISSUE TITLE
Is it possible to change the menu icon in toolbar?

### ISSUE THREAD

**Issue by shmshd12** [google/material-design-lite#1777]
Actually I'm looking for a back button to be replaced instead of menu button in the toolbar because i gave toolbar for all the pages so if i have an end the page i need to give back button instead of menu. Is it possible to do so?

**Comment by Garbee** [comment]
Changing the menu icon is not supported at this time by MDL. It can be done with JS that executes after the layout is upgraded, but this is out of the scope of what we support here. If you need help implementing something like that then StackOverflow is the best place.

This could be possible with the layout refactor being planned for V2.

**Comment by shmshd12** [comment]
Thanks for the great info.

**Comment by ghost** [comment]
what about in 2017 ?
