### ISSUE TITLE
Alignment of labels on switch (and possibly other toggle types)

### ISSUE THREAD

**Issue by rj33** [google/material-design-lite#1787]
The MD spec doesn't mention labels in the components section for the switch component, but it does show some guidance in the settings section under patterns:
https://www.google.com/design/spec/patterns/settings.html#settings-grouping-settings

By default MDL aligns the label to the right of the switch (even if you place the label element to the left in the markup).  Is it possible to consider a CSS marker to indicate the alignment of the label , or perhaps even default to aligning the label to the left, given the only guidance in the spec at the moment indicates the label being to the left of the switch?

**Comment by Garbee** [comment]
This is not guidance for switches/checkboxes/radios/etc, but only for how things should be displayed for a *settings panel*.

However, we should look into making the  position of labels modifiable. That has been brought up before iirc.

**Comment by rj33** [comment]
Yes, definitely only settings guidance, so perhaps the MD folks could be prodded to also provide some detail on how they see labels working for the switches/checkboxes etc that MDL could then use as guidance.

**Comment by rj33** [comment]
Sorry, just noticed this is a duplicate of:
https://github.com/google/material-design-lite/issues/1488

Closing this one, but maybe worth adding the "MD Guidance Needed" tag to the other issue.
