### ISSUE TITLE
Does ripple container element really need to be a mouse up target in checkbox/switch etc

### ISSUE THREAD

**Issue by rj33** [google/material-design-lite#1790]
Checkbox, switch, radio etc have this code when setting up the ripple container:
  this.rippleContainerElement_.addEventListener('mouseup', this.boundRippleMouseUp);

This creates a wide clickable area (48x48px square) around the toggle element which can be quite confusing if you are not going to add large margins around these elements. For example several vertically aligned switches with default MDL style will now have overlapping click activity areas due to the large ripple container area which is considerably larger than the fixed visual area of the switch. Element order ends up defining where your clicks land so the user can feel they are clicking closest to an earlier element, but have the click land on the next one.

Is there an MD reason the full ripple area need to be mouse active and not just the visible area of the toggle component? The ripple itself uses absolute positioning so it doesn't increase the size of parent element, which is what allows the clickable ripple area to easily overlap with surrounding elements. 

If there is a MD reason to have the full ripple area clickable , then perhaps a default margin should be added to avoid the click areas overlapping on adjacent clickable elements, although personally I'd prefer if the full ripple area wasn't clickable in the first place.

**Comment by surma** [comment]
I think that handler is there to capture a mouse release outside of the actual element. Consider triggering a mouse down on the very edge of a checkbox, moving the mouse a little and releasing on top of the ripple but outside the element itself. This should still be a valid click (as you are visually on the element, the ripple effectively enlarges it) and the ripple should disappears.

The ripple is only visible on click and is kind of intended to occasionally overlap with other elements. Are you running into technical difficulties with this setup?

**Comment by rj33** [comment]
Yes. The difficulty is if you have a column of switches, for example in a settings dialog, where the switch areas form a vertical column of aligned switches, the enlarged area of the ripple means that unless you add extra spacing the ripple of the second such element overlaps the switch area of the first element. This means when the user thinks they are clicking on the first switch, the click actually lands on the second switch. That is one example, but any case where the 48x48 ripple area can overlap with a neighbour that is clickable seems to be problematic. 

Having the ripple overlap with other elements seems to be a bad idea if those other elements is supposed to be a target of clicks. The problem is that the ripple area as defined by rippleContainerElement is clickable not just when the ripple is visible, but also when it is invisible. I can see the argument for the ripple area to expand the mouseup area while visible, but it seems to be very confusing to users to have the ripple area take clicks away from neighbouring elements when not visible.

It is fairly easy to workaround by adding a suitable margin around clickable elements such that the ripple container element never overlaps with other clickable elements, and it is possible that the MD specs require such padding, although it is not currently enforced by MDL. However it seems unfortunate that developers using the toggle type elements need to be aware that they risk stealing clicks from neighbouring elements if they use the ripple, and have to assign their own margins to avoid it.

Personally, I think that having clicks on elements that are overlapped by the ripple being assigned to the ripple's parent element is more of a problem than the risk of the user sliding the mouse outside of a clicked element, but still over the ripple and not registering. At the least I think the behaviour should be reduced to cases when the ripple has been recently triggered. If anything the current behaviour of still registering clicks outside the visible area of the element could be very confusing. It is common for users to have second thoughts on a click, and slide the mouse out of the button area to avoid the click being processed. It seems they would be surprised to do the same in this case, releasing after the ripple is gone, only to find that their click was still registered, despite releasing on what appeared to be empty space after the ripple has subsided.

**Comment by surma** [comment]
@rj33 Could I bother you to provide a codepen that reproduces the issue?

**Comment by Garbee** [comment]
@surma Check out the [toggle component demo](http://www.getmdl.io/components/index.html#toggles-section). Hover over the checkbox, then keep slowly moving up. The cursor stays as pointer for a good number of pixels above the checkbox. It is not tied to the label height, since if you move to the right when you are above the checkbox it will go away over the label.

**Comment by rj33** [comment]
http://codepen.io/rj33/pen/MaroQY

Click on the very bottom portion of the switch handle on switch 1, and watch switch 2 trigger.

I think @garbee is right, in that it is quite possible in a pure MD design there would probably be padding/margin requirements that would separate the elements more than this, but this is a default layout, so I still think it is an MDL bug either way. Either the expanded ripple click area is a problem, or the lack of default margin on the elements to avoid the proximity issue is a problem.  I think the ripple click expansion is the real issue, as there are probably use cases where you need proximity between clickable items and having non-visible areas that overlap other potentially clickable areas receive clicks seems problematic in general.

**Comment by Garbee** [comment]
I think this situation isn't anything we should work on. Whether we leave it as-is or change it so this "default" (which we never show as far as I am aware, so it isn't really default) works right away, someone is going to end up having to do work either spacing things out properly or undoing our spacing.

Ideally, you'd be implementing switches in conjunction with other Material Design principals and components which avoids this issue since the overall application would provide appropriate padding.
