### ISSUE TITLE
Waterfall header first row not visible on narrow screen

### ISSUE THREAD

**Issue by alextekartik** [google/material-design-lite#1791]
On a narrow screen, the samples in http://www.getmdl.io/components/index.html#layout-section does not show anything but the menu button for the waterfall and scrolling header although the comments in the code said

        
        <div class='mdl-layout__header-row'>

If I'm wrong what is the proper way to always have the first row on a narrow (phone) screen?

**Comment by Bound3R** [comment]
i saw your problem, and is quite rare, Because Then in mobile Does not Have a navbar, @sgomes  think they should assess the mobile navbar ?, but for now you can use a custom breakpoint to fix it. :sweat_smile:
if you need help let me know :ok_hand:

**Comment by sgomes** [comment]
Thanks for the feedback, @alextekartik! If you want the behaviour you're describing, just add the `mdl-layout--fixed-header` class to your `mdl-layout` element, which should make sure it's always visible, including in mobile.

The comment is actually talking about how the first row is always visible and the second one gets hidden, *as long as the header itself is visible*. I'll see if I can make that a bit clearer :)

**Comment by ccarsona** [comment]
This breaks in Android if you use a hash tag link on the page. Click the link and it doesn't stop scrolling at the header row - if you scroll back to the top. Example below - click one of the links (About or Services), the scroll back to the top - it keeps scrolling and scrolling. Example below:
http://www.mobotic.com/mld/bug.html

http://www.mobotic.com/mld/bug.html

**Comment by surma** [comment]
> it keeps scrolling and scrolling

It is actually quite satisfying to scroll infinitely ^^ Definitely a bug. I’ll open a separate issue. Thanks for the sample code, @ccarsona.
