### ISSUE TITLE
componentHandler.upgradeElements() don't work with jQuery selector

### ISSUE THREAD

**Issue by J2TeaM** [google/material-design-lite#1793]
Hi!

I have a table with dynamic data added from JavaScript. This table has a checkbox column, so I need to render the checkboxes using the `upgradeElements` function.

It's worked with plain JavaScript:

![e2](https://cloud.githubusercontent.com/assets/5250117/10636461/2671642a-782a-11e5-9d58-e525d2b404f4.PNG)

but not work with jQuery though using the same selector.

![e1](https://cloud.githubusercontent.com/assets/5250117/10636456/203d604a-782a-11e5-89cb-199ec6f56201.PNG)

So, how I can use this function using jQuery?

**Comment by surma** [comment]
jQuery doesn’t return the DOM object but a jQuery object. IIRC, `$('...').get()` should work.

**Comment by surma** [comment]
Also, questions like these belong on StackOverflow with the `material-design-lite` tag. The GH issue tracker is for bugs, issues and feature requests only.

**Comment by J2TeaM** [comment]
Thank you, @surma!
