### ISSUE TITLE
How to work with MDLite form validation and Angular form validation

### ISSUE THREAD

**Issue by davidshen84** [google/material-design-lite#1794]
I have posted my question on [SO](https://stackoverflow.com/questions/33249686/angular-form-validation-triggered-on-load).

I think it is caused by Angular form validation triggered the validation on both Angular and Material, but I do not have control over how Material should response on invalid fields.

Also, we do not have any guidance on http://www.getmdl.io/ related to form validation, and how it would work with Angular. I simply mix the two together, and caused some unwanted visual response. And I have no clue what I did wrong.

**Comment by davidshen84** [comment]
I just notice even working with Material along, the form is validated on load. Ex, required fields are marked as invalid on load.

Is it the by design behavior? Do I have a way to control this?

**Comment by rasanga** [comment]
> form is validated on load 

this really annoying me

**Comment by Garbee** [comment]
Forms are validated on load. This is in alignment with how browsers validate forms by default. Until we have intermediate states specified and implemented, this isn't changing. If you don't wish for it to function that way, you need to build your own components using custom dirty state checking.

As far as the rest of this, SO is the proper place for integration support. We can only provide help with direct problems from MDL. Supporting integration with other technologies is out of the scope of what we can handle.
