### ISSUE TITLE
Menu obfuscator should not change background-color

### ISSUE THREAD

**Issue by paullewis** [google/material-design-lite#1795]
I noticed that when the menu slides out that [the obfuscator changes `background-color`](https://github.com/google/material-design-lite/blob/525423e7dc4bb7984d2dc8c886f6dfc90e7509a5/src/layout/_layout.scss#L406), which will cause repaints.

Instead we should change `opacity` and toggle `pointer-events` from `auto` to `none`. That said, [`pointer-events` is IE11+](http://caniuse.com/#search=pointer-events) but I wonder if we could branch with `@supports` here?

**Comment by surma** [comment]
@paullewis Animation `opacity` rather than `background-color` seems easy enough. Why do you see the need to add `pointer-events`, though?

**Comment by paullewis** [comment]
Because with opacity: 0 (or any value) the obfuscator element should intercept clicks. Unless you are already toggling `display` to `none` and I missed it?

**Comment by samccone** [comment]
good spot @paullewis :heart_eyes:

**Comment by Garbee** [comment]
@paullewis Thanks for letting us know and providing such a nice solution wrapped up with a bow on top. It was very nice.

PR #1956 is now open to address this. If all is well there, should land in the 1.1 release.
