### ISSUE TITLE
Should per-component minified CSS/JS be provided?

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#18]
Open-question. This was requested by an early user this week and wasn't something included in the refactor. I guess we could spit out fairly independent:

* component.min.css (includes CSS for any deps)
* component.min.js (same, all deps included)
* Maybe a demo file

if we moved to a model with:

```
/dist
----/css/material.min.js
----/js/material.min.js
----/individual/button/
----/individual/spinner/
etc.
```

However, I'm not sure how desirable that is. @google/material-styleguide any thoughts?

**Comment by sgomes** [comment]
This will be addressed in v2 as a result of the new architecture.
