### ISSUE TITLE
Infected with Trojan:Win32/Spursint.A virus?

### ISSUE THREAD

**Issue by tropicfruit** [google/material-design-lite#1812]
While downloading from http://www.getmdl.io/ my anti virus (MSSE) tells that the zip is infected with Trojan:Win32/Spursint.A and put int in quarantine.

Anyone else experiencing this issue? Maybe a false positive?

**Comment by Garbee** [comment]
Duplicate of #1754.

Surely false positive. Users of MSSE need to report it to MS so they can figure out why their software is calling it out and get it fixed.

**Comment by tropicfruit** [comment]
Thx for the quick reply.
