### ISSUE TITLE
Downgrade Checkboxes

### ISSUE THREAD

**Issue by lepinejf** [google/material-design-lite#1819]
Is it possible to downgrade Checkboxes ?

I'm using Material Design in a project with Ractive.js and Checkboxes aren't working well when I'm updating my view.

**Comment by Garbee** [comment]
Checkboxes have a downgrade method. What exactly isn't working?

**Comment by lepinejf** [comment]
I have a localized page that is rendering multiples checkboxes according to the current language and there is a condition to check the values of the localized checkboxes which adds a checked attr or not.

{{#partial checkbox}}
  <fieldset>
    <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="{{id}}.{{value}}">
      <input type="checkbox" id="{{id}}.{{value}}" class="mdl-checkbox__input" name="{{{id}}}" value="{{value}}" {{#if localizedValue == value}}checked{{/if}} />
      <span class="mdl-checkbox__label">{{label}}</span>
    </label>
  </fieldset>
{{/partial}}

Everything is working as intended on the first render, but the moment I am switching languages, the checked attributes changes but Material design doesn't reflect the changes and becomes buggy.

That's why I wanted to downgrade the components, to manually replicate to behaviour.
It's also doing the same with the radio buttons, fyi.

**Comment by Garbee** [comment]
Would calling `checkToggleState` from the MaterialCheckbox property on the component solve the issue?

More dynamic web pages aren't something we fully support. Things like Polymer are more adept for those situations.

Radio doesn't currently have a downgrade method, a PR is open for that one.

**Comment by lepinejf** [comment]
I'll give it a try and give you a feedback.

**Comment by lepinejf** [comment]
It's returning 'undefined'

**Comment by KristerV** [comment]
yep, `$('.mdl-js-checkbox#'+menuitemId)[0].MaterialCheckbox.checkToggleState()` always returns `undefined` regardless of actual state.

As a workaround I'll use `$('.mdl-js-checkbox#'+menuitemId+' input').is(":checked")`

**Comment by Garbee** [comment]
FTR: `checkToggleState` is *meant* to not return anything. It does the check for you and updates the classes for the component as needed. If you need to check the actual check state to do something, just target the input and see. @KristerV showed a jQuery based solution, but here it is in raw JS...
`var isChecked = document.querySelector('{YOUR SELECTOR}').checked;`

Replace `{YOUR SELECTOR}` with whatever you need to directly target the node in question.

Sorry for not responding sooner btw, looks like I didn't get notified (or I marked all as red with this in a bunch of them.) 

Seeing as how this is particular to using some 3rd party library or framework, I'm closing it out as non-actionable for us. I'm not seeing a clear path to resolve the problem at hand internally. StackOverflow is able to provide more general support.

If you want to replicate the JS behavior in some other language, just remove the `-js-` classes from the markup so our component handler system will not fire against the node, then do whatever you want for another system to register things.
