### ISSUE TITLE
Double load for Youtube embed

### ISSUE THREAD

**Issue by JhoongRoh** [google/material-design-lite#1836]
I'm not exactly sure what's occurring, but using embedding a YouTube video is causing a sort of refresh where the video disappears for a fraction of a second.

Below is a link to a codepen that, when you refresh the page, will show you the "refresh" that I'm experiencing.
[http://codepen.io/JuneRow/pen/zvLvvW](http://codepen.io/JuneRow/pen/zvLvvW)

In addition, I've tracked down what lines of code in the js file that's causing the issue. This is starting at line 3183 of material.js

```
MaterialLayout.prototype.init = function () {
        if (this.element_) {
            var container = document.createElement('div');
            container.classList.add(this.CssClasses_.CONTAINER);
            //TODO Beginning of bug
            this.element_.parentElement.insertBefore(container, this.element_);
            this.element_.parentElement.removeChild(this.element_);
            container.appendChild(this.element_);
            // TODO End of bug
            var directChildren = this.element_.childNodes;
```

When you comment out the code in between TODO, the issue will be "fixed".

I apologize if I'm not being in depth enough. Busy designing a mdlite website for customers, and I have a host of other bugs :(

**Comment by Garbee** [comment]
I'm fairly certain there is nothing we can do here until the big refactor for 2.x. Assigning to @surma to take a look at triaging more in case he sees something we can do.

**Comment by surma** [comment]
Yeah, there’s nothing we can do currently. One of our big goals for 2.0 are not to make these kind of DOM manipulations in JavaScript anymore (see #1732 & #1735), which will resolve this.

The only thing I can suggest as a workaround: Listen to the `mdl-componentupgraded` event and add the YT video dynamically when the event was fired.
