### ISSUE TITLE
Conflict of mdl-cell with a previous spans 

### ISSUE THREAD

**Issue by skozz** [google/material-design-lite#1838]
I found a conflict using spans before a `div` with `mdl-cell`. Example: 

Works perfectly:
```
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div>
  <div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div>
  <div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div>
  <div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div>
  <div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div>
  <div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div>
</div>
```
![img](http://cl.ly/image/1G1H0k1U201t/Captura%20de%20pantalla%202015-11-02%20a%20las%2020.40.28.png)

Using a `span` before de `div`: 
```
<div class="mdl-grid">
  <span><div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div></span>
  <span><div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div></span>
  <span><div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div></span>
  <span><div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div></span>
  <span><div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div></span>
  <span><div class="mdl-cell mdl-cell--2-col"><img style="width: 100%;" src="http://assetsprx.matchesfashion.com/img/product/500/1028321_1_zoom.jpg"></div></span>
</div>
```
![img](http://cl.ly/image/0i2G1S1m1A0S/Captura%20de%20pantalla%202015-11-02%20a%20las%2020.42.54.png)
![img](http://cl.ly/image/3d061z1b0k2H/Captura%20de%20pantalla%202015-11-02%20a%20las%2020.43.37.png)
![img](http://cl.ly/image/150n3a2u0E1W/Captura%20de%20pantalla%202015-11-02%20a%20las%2020.43.49.png)

**Comment by tleunen** [comment]
This is not a bug. Why would you want to put a span before `<div class="mdl-cell">`?

**Comment by skozz** [comment]
@tleunen hi Tommy, in this case is a [technical limitation in application with ReactJS](http://stackoverflow.com/a/24470188/957253).

**Comment by tleunen** [comment]
I still don't see the problem. `<div class="mdl-cell">` is not a text

**Comment by Garbee** [comment]
This issue has nothing to do with MDL. You'd need to apply the cell classes to the spans if it needs to be wrapped in that. If React has a technical limitation, that is a problem on their end.

**Comment by surma** [comment]
Or to put it differently: We expect the `mdl-cell` class to be a *direct* decendent of the node with the `mdl-grid` class. Applying the `mdl-cell` class to the `<span>` should solve your issue, afaict.

**Comment by skozz** [comment]
@surma @Garbee thank you for the answer, but I tried this approach before sending the issue and is not working :(

**Comment by surma** [comment]
It might be related to React. But using `<span>` [definitely works](http://codepen.io/surma/pen/avjjzq).

**Comment by tleunen** [comment]
There are no reasons why React would add a span in that case anyway. It only adds a span around text, not around other elements.

**Comment by skozz** [comment]
Sorry @tleunen but this argument is `false`. React adds span to encapsulate each element of a iteration, like my example in the first post.

**Comment by skozz** [comment]
@tleunen another example in production: 
![img](http://cl.ly/image/2D0Y2n3z2F33/Captura%20de%20pantalla%202015-11-03%20a%20las%2017.45.07.png)

**Comment by tleunen** [comment]
Well... Show me your code.

**Comment by skozz** [comment]
Thank you @surma but is not the same example, It is not possible to inject classes in this auto generated span. The specific order it's like my first example <div> <span autogenerated><div with mdl-cell>.

**Comment by tleunen** [comment]
So, I don't know how you build you Grid, but I don't have any span in my solution: http://codepen.io/anon/pen/dYjqGo

Also, if you're using React, you can use React-MDL: https://github.com/tleunen/react-mdl

**Comment by skozz** [comment]
@tleunen wow I don't understand why your example don't have auto generated spans and if mine, I'm using the same approach! Ok, I will to check this point (and your components) when I get home today.
