### ISSUE TITLE
Buttons not working with other css

### ISSUE THREAD

**Issue by seanfrasure** [google/material-design-lite#1840]
I am trying to make my website using 2 CSS kits and it seems like the CDN isn't working. I think it has something to do with the multiple CSS files. 

Without MDL:
http://jsfiddle.net/seanfrasure/up0utcvt/

With MDL:
http://jsfiddle.net/seanfrasure/pupLxye9/

It looks 100% better with MDL but the buttons aren't working.

**Comment by surma** [comment]
You are using the layout component but have all your content outside of the `mdl-layout__content` container. That’s why it’s not working. Also, you need to move all the JavaScript to the *bottom* of the page. 

The code is pretty messy, to be honest. I recommend reading through our [Getting Started Guide](http://www.getmdl.io/started/index.html). 

For future reference, these kind of questions should really be asked on StackOverflow using the `material-design-lite` tag, as it is support and not a bug within MDL.
