### ISSUE TITLE
Layout bug on demo snippets.

### ISSUE THREAD

**Issue by mustafa-x** [google/material-design-lite#1841]
There seems to be a bug in the layout components (http://www.getmdl.io/components/index.html#layout-section/layout), every code example I add content too, in mobile the content gets pushed to the top of the page. 

For example this code taken from that page;

```
<div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header">
    <div class="mdl-layout-icon"></div>
    <div class="mdl-layout__header-row">
      <span class="mdl-layout__title">Material Design Lite</span>
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="#">Hello</a>
        <a class="mdl-navigation__link" href="#">World.</a>
        <a class="mdl-navigation__link" href="#">How</a>
        <a class="mdl-navigation__link" href="#">Are</a>
        <a class="mdl-navigation__link" href="#">You?</a>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout__title">Material Design Lite</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link" href="#">Hello</a>
      <a class="mdl-navigation__link" href="#">World.</a>
      <a class="mdl-navigation__link" href="#">How</a>
      <a class="mdl-navigation__link" href="#">Are</a>
      <a class="mdl-navigation__link" href="#">You?</a>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <div>Content</div>
  </main>
</div>
```

What is outputted is the content appears over the hamburger icon. E.G does this in mobile:
![screen shot 2015-11-03 at 5 47 48 pm](https://cloud.githubusercontent.com/assets/1212513/10916362/0cf4d698-8253-11e5-9d02-2dd42161c8d4.png)

However adding this class to the container div fixes the issue

```
.mdl-layout--fixed-header
```
So 

```
<div class="mdl-layout mdl-js-layout">
....
</div>
```

**Comment by surma** [comment]
Could you provide a codepen that reproduces the issue for you? Because the examples work fine for me. Also, please give us some information about browser and OS version you are using :)

**Comment by mustafa-x** [comment]
This code pen - http://codepen.io/anon/pen/mejGGM?editors=110

**Comment by Garbee** [comment]
I believe this is expected behavior. The default is a non-fixed header which means it lays on top of the content. By fixing the header you put it in the content flow, so it is then taking space on the page thus pushing the content down.

**Comment by surma** [comment]
@Garbee is right, this is working as intended. On mobile, the drawer button is floating on top of the content. 

There’s multiple options to change that behavior, please see our [documentation](http://www.getmdl.io/components/index.html#layout-section/layout).
