### ISSUE TITLE
Drawer button doesn't have ripple effect

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1842]
Hi,

The drawer button doesn't have ripple effect when it's added to header.
I can't find that part in the MD specs but the ripple effect is present on all Google's Android apps.

**Comment by surma** [comment]
You are right. I felt like we had an issue for this before but I can’t find it.

@sgomes Do we want to address this in 1.1 or the rewrite (and therefore v2)?

**Comment by Garbee** [comment]
I think we should handle this in 2.0. Handling this in 1.1 means introducing more coupling between ripple and layout, where in 2.0 we are should make Ripple a complete standalone component and will already be doing a lot of layout work. So adding this in means *more* logic to undo later. Best just wait and do it all in one swoop.

**Comment by sgomes** [comment]
+1, this sounds like 2.0 work.

**Comment by surma** [comment]
Added to #1735. Closing this. Thanks for issuing, @jfily :)
