### ISSUE TITLE
Drawer not working inside a div

### ISSUE THREAD

**Issue by samadmoizc8** [google/material-design-lite#1845]
I have added .mdl-layout__header and .mdl-layout__drawer in a div. After that the drawer button is not showing.
E.g.
```
<div class="my-mdl-layout-header"
<div class="mdl-layout__header">
...
</div>
<div class="mdl-layout__drawer">
...
</div>
</div>
```

**Comment by Garbee** [comment]
Can you please provide a codepen or some other working sample to show the issue in action?

**Comment by samadmoizc8** [comment]
I have place .mdl-layout__header and .mdl-layout__drawer in a div.my_drawer. The drawer menu button is not showing 
Here is a codepen link http://codepen.io/anon/pen/KdxNzY

**Comment by steamonimo** [comment]
This is exactly the problem I was referring to with my issue 1857. But sadly it was closed because I wanted to embedd the header and drawer into a custom html element not a div. With more generalized selectors these issues can be easily addressed I think:
https://github.com/google/material-design-lite/issues/1857

**Comment by Garbee** [comment]
This isn't working since your structure is not conforming to what is required, which is documented in the Layout docs. We are going to work on Layout heavily in 2.x, this could be fixed in that. However, for more dynamic sites we recommend Polymer instead of MDL.

**Comment by jriverabarzola27** [comment]
I could correct this issue, the only thing that you need to do is  put this links:

`<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>

<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
`

In the header of your code.
Regards
