### ISSUE TITLE
Scrollable Header Layout & IE11: Glitch with width calculations

### ISSUE THREAD

**Issue by Londovir** [google/material-design-lite#1849]
Here's a very stripped down CodePen: http://codepen.io/londovir/pen/JYapOE

If you load that, which attempts to set up a basic scrollable header layout with a content area that is larger than the vertical viewport space, under IE11 the header is completely glitched for the width calculation; the blue header will only be about as wide as necessary to contain the components. Use the mouse and subtly change the CodePen divider even 1 pixel wider or narrower, and the header snaps to the correct width (presumably because IE11 forces a reflow/repaint, which then "picks up" the width calculation.

From what I can see, it appears that the vertical scrollbar which gets triggered when the main content DIV is too long is the culprit in IE11. If you override the content DIV to be very small so there's no scrollbar, IE11 is able to determine the 100% width correctly. If the scrollbar is there, however, it cannot do so on the first load. 

This behavior does not exist in Chrome or FF, that I can see. It looks to be due to the `has-scrolling-header` class which ends up on the container. Why, I'm not sure; it's perhaps because of either the `position: absolute` that exists on the container, or the `overflow: visible` on the container. What's curious is in IE11 it looks like perhaps there's a race condition of sorts going on, because about 1 out of 20 refreshes of that CodePen will actually load the layout correctly as the full width, while 19 out of 20 come up the short width that needs a repaint to "figure it out". Since that container (and the class put upon) is managed in Javascript code, I'm guessing in rare cases that the JS runs and the class gets added just before IE11 performs its last reflow cycle, so in those cases it can get the correct container width, which trickles down to the header. Other times it performs the final reflow before the JS runs and the class is added, and apparently for some reason IE11 is bugged enough that popping up a scrollbar causes the `width: 100%` to be ignored.

I do know that overriding the container to have `position: relative !important` seems to do the trick for IE11, but only if the layout is a direct child of the body. If I try to create a layout inside of a div that lives somewhere else within the body, I haven't been able to stop this IE11 bug no matter what I try. (BTW: Edge does not appear to be affected by this from what I can see.)

**Comment by Londovir** [comment]
Update: Forcing `width: auto !important` on `.mdl-layout__header` may have solved the problem for me. Not sure why, but perhaps `auto` is somehow forcing IE11 to properly recalculate widths when `100%` is not?

**Comment by sgomes** [comment]
Tested with Edge and MDL v1.1.2, and no longer seems to be the case. Please reopen if I'm wrong!
