### ISSUE TITLE
Progress bar indeterminate is a modifier

### ISSUE THREAD

**Issue by Mistereo** [google/material-design-lite#1853]
Should `mdl-progress__indeterminate` be `mdl-progress--indeterminate`?

**Comment by surma** [comment]
Yup. That is correct. I am not sure how that slipped through, to be honest.

**Comment by surma** [comment]
Thanks for issuing, @Mistereo :)

**Comment by surma** [comment]
Already fixed on master by @Garbee in #2076. Will roll out with 1.1 :)
