### ISSUE TITLE
Tool tips need a pointer cursor on hover

### ISSUE THREAD

**Issue by mustafa-x** [google/material-design-lite#1855]
Currently when you hover over tool tips the cursor you get is the one you would normally get for selecting text. Ideally this should be a hand cursor / pointer.

**Comment by surma** [comment]
If you are talking about the tooltip demo, the cursor becomes a text cursor because the icons are text. We should change that in the demo, but the shape of the cursor is entirely up to the user and not affected by the tooltip.
