### ISSUE TITLE
Custom elements and drawer functionality, ES6 compatibility

### ISSUE THREAD

**Issue by steamonimo** [google/material-design-lite#1857]
With the ECMAScript 2015 (ES6) Standard it will be normal to built pages from components. These componentes are usualy injected via custom elements. With aurelia.io for example you could utilize your own custom element called &lt;nav-bar&gt;&lt;/nav-bar&gt;. At runtime this element will be filled with the navigation elements coming from the template of the nav-bar element. So after the injection it will contain the mdl header and drawer.

However by having the mdl elements wrapped in the custom element the drawer functionality will break. The hamburger icon will not be injected by mdl and with small screens the header will just disappear.

This codepen demonstrates the issue:
http://codepen.io/steamonimo/pen/OyBWrP

Just remove the &lt;nav-bar&gt; element in the codepen and the drawer will work again.

**Comment by Garbee** [comment]
We don't directly support integration with other projects. These kinds of issues are up to you to solve. If you need help, sites such as StackOverflow can provide it. This issue tracker is only for direct problems related to the code it provides.

**Comment by steamonimo** [comment]
I understand that you need to keep the focus. But this is about the concept of custom elements and not the aurelia project. I just wanted to suggest that the elements "mdl-layout__header" and "mdl-layout__drawer" are not working if they are embedded in another element. For example replace the custom element &lt;nav-bar&gt; in my codepen with a &lt;div&gt; and again the drawer will break. This is likely just because the selectors addressing these elements are expecting a fixed structure. With more general selectors you could support more scenarios.

**Comment by surma** [comment]
@steamonimo That is because we expect nodes with `.mdl-layout__header` and `.mdl-layout__drawer` to be *direct* descendants of `.mdl-layout`. `<nav-bar>` is currently sitting inbetween.

In any case, layout is getting a major rework so things are going work differently in v2
