### ISSUE TITLE
material spec: button disabled style

### ISSUE THREAD

**Issue by samccone** [google/material-design-lite#1866]
Disabled raised buttons should not have any shadow.

![](https://camo.githubusercontent.com/be1d968dfae6b928cd323dcc363c1b749427ee74/68747470733a2f2f70702e766b2e6d652f633632323431382f763632323431383337302f35363762352f53794a5746462d323039382e6a7067)

Left - Google docs, right - MDL.
To fix this, open _button.scss file, scroll to "disabled" section and remove following lines:

```scss
@include shadow-2dp(); // This should be removed
```

------

Originally from #1864

**Comment by samccone** [comment]
this seems like a quick and simple fix... any debates?

**Comment by Garbee** [comment]
Nope, it does look right to remove the shadow by the spec.
