### ISSUE TITLE
Card Supporting text doesn't follow MD guidance

### ISSUE THREAD

**Issue by virtyaluk** [google/material-design-lite#1870]
The specifications [say](https://www.google.com/design/spec/components/cards.html#cards-content-blocks) that the appropriate `font-size` for card Supporting text is `14px`, but MDL uses `13px` instead.

![image](https://cloud.githubusercontent.com/assets/795984/11103242/e5af1346-88c9-11e5-88a2-862059b4c0c6.png)

![image](https://cloud.githubusercontent.com/assets/795984/11103112/2bc7162c-88c9-11e5-8825-56340f883da3.png)

To fix this, open **_variables.scss** file and change incorrect value:
```sass
$card-supporting-text-font-size: 13px !default; // 14px 
````

**Comment by Garbee** [comment]
It didn't say `sp` before either as I recall. It seems like it should correlate to the user-set font size. So seems like `14 rem` is what we are looking for now instead of a direct pixel correlation.

Sound good? cc @addyosmani, @sgomes, @surma

**Comment by samccone** [comment]
:+1:

**Comment by surma** [comment]
:+1:

**Comment by Garbee** [comment]
So, testing just now, 14rem is *way* too big. Duh, it is multiplication. So, falling back to 1rem which is giving our base 14px. But, if a developer then changes their base font size, this would be updated with that.
