### ISSUE TITLE
Card Icons extra margin\padding

### ISSUE THREAD

**Issue by virtyaluk** [google/material-design-lite#1871]
As the documentation [says](https://www.google.com/design/spec/style/icons.html#icons-system-icons) that icons should have 
> Adequate space around the icon is needed to allow for legibility and touch.

![image](https://cloud.githubusercontent.com/assets/795984/11103449/1341acfa-88cb-11e5-9281-53f165dd1d7c.png)

But icon in MDL card placed a little bit strange. So, I think, the icons needs to be positioned with additional horizontal margin\padding.

![image](https://cloud.githubusercontent.com/assets/795984/11103545/afe313b4-88cb-11e5-8bb6-4a455dcea194.png)

**Comment by Garbee** [comment]
Yea, the original mock has a few extra pixels there. Adding now directly.

**Comment by Garbee** [comment]
Fixed with commit a2761e5f5d3a06877d4b44e2b0919d380e1c1e44
