### ISSUE TITLE
Infected downloads?

### ISSUE THREAD

**Issue by Nils-Kolvenbach** [google/material-design-lite#1872]
I just wanted to download an mdl template and saw that the download was canceled because of a found trojan. Well I think thats a false alarm from windows defender but wanted to inform you anyways. If I download the source from github everything is fine.

I am using Windows 10 with the lastest version of defender.

Anyone else having this issue?

![virus](https://cloud.githubusercontent.com/assets/2317940/11114840/c4bfe7ce-8927-11e5-8faa-ebf13f111b72.jpg)

![virus2](https://cloud.githubusercontent.com/assets/2317940/11114842/cb3a69a8-8927-11e5-9445-7270429e55fd.jpg)

**Comment by Nils-Kolvenbach** [comment]
I just tried it from another pc. Windows 7. Same problem.

![virus](https://cloud.githubusercontent.com/assets/2317940/11115269/96e5df40-892a-11e5-97b1-5cea0a2ca093.jpg)

**Comment by hebbet** [comment]
possible duplicate of #1851, #1812, #1754

**Comment by Nils-Kolvenbach** [comment]
Yep. I'm closing this.
