### ISSUE TITLE
Tooltip positioning

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1888]
Hi,

It would be great to change the position of tooltips with some classes mdl-tooltip--left and  mdl-tooltip--right.

Because i've done my own speed dial but I can't do something like Inbox 
![sans titre](https://cloud.githubusercontent.com/assets/10220170/11169249/76376608-8bb2-11e5-98c1-c8e7f9d94bc1.png)

**Comment by surma** [comment]
Already implemented in #1101, slated to get merged for 1.1 :)
