### ISSUE TITLE
README badges show up as ?.?.?

### ISSUE THREAD

**Issue by ryanseys** [google/material-design-lite#1894]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/163873/11280621/b2a33d50-8eab-11e5-9548-2c86da6482f9.png)

**Comment by samccone** [comment]
working for me.... right now

going to close, but we can reopen if anyone can repro

**Comment by surma** [comment]
Working for me too. Lol, this @ryanseys guy...

**Comment by ryanseys** [comment]
Works for me too. Probably an intermittent error on the badge's site. Or I've gone crazy.
