### ISSUE TITLE
Add Material Design style animations

### ISSUE THREAD

**Issue by SuicSoft** [google/material-design-lite#1897]
I want to use MDL on my new website but animations are not available, meaning polymer (or another Material Design framework) will need to be used.

**Comment by addyosmani** [comment]
When you say animations, can you go into more detail about what you're looking for? Material Design has delightful detail animations (smaller touches to icons/buttons), transitions between pages (things like what https://github.com/PolymerElements/neon-animation provides) and then animations on components. What do you need?

**Comment by SuicSoft** [comment]
Delightful detail animations and page transitions

**Comment by surma** [comment]
Those animations are highly complex and rather hard to abstract, especially if we want to stay light AND have support for IE10. This is one of the use-cases where Polymer really shines and I’d encourage you to take a look at the [Neon elements](https://elements.polymer-project.org/browse?package=neon-elements), which have managed provide these kind of animations.

I don’t see a viable way we can add generic support for these kind of animations in MDL.
