### ISSUE TITLE
Should we keep the component handler?

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#1898]
I've been playing with some V2 ideas lately. One thing that has come across converting some JS to ES6 is, should we even keep the component handler? It is only really replacing us telling people to query the element and pass it into a new instance of whatever component(s) you need.

Pros:
* Less stuff for us to maintain and support
* Less confusing for developers building dynamic applications.

Cons:
* Raises barrier to entry for beginners (however, the pro here is it makes a good place to educate them about what to do.)
* Puts more responsibility on developers for small and/or simple apps.

**Comment by sgomes** [comment]
My thoughts on this are that we should have a mechanism for declaratively attaching JS (which could be optional or mandatory, depending on component) to a component declared in HTML. The component handler gives us a standard way of doing this, but I'm sure we could also come up with a much simpler approach. I heartily support this research :)

**Comment by Garbee** [comment]
The component handler can be maintained in its own repository for developers to *chose* to opt-in to using. We then just provide objects that developers new-up however they wish. So you can build your own loader if you wish or pull in the CH separately from its own package.

I think this would be easier for developers in general to understand then when and how to run the component handler methods on top of understanding our JS system. In the end, making our overall documentation smaller and providing developers more flexibility without our predefined manager.

**Comment by morlay** [comment]
Glad to hear the plan to split the component handler.

For partial use, I have to create a fork to remove the componentHandler https://github.com/morlay/material-design-lite-cjs (exports ComponentClass with CommonJS, too)

If still have component handler in next version, could we not put `componentHandler.register` in each ComponentClass file ? or check componentHandler first?

**Comment by ashende** [comment]
+1

**Comment by Garbee** [comment]
Pretty unanimous among everyone I have heard from, dropping the CH is a good path. Closing this out until someone provides a compelling argument to keeping it around internally.
