### ISSUE TITLE
Tabs alignment issue and missing documentation

### ISSUE THREAD

**Issue by Deilv** [google/material-design-lite#1899]
I tried to utilize the tabs component using the example code provided on getmdl.io, but I noticed that while the tab buttons are aligned in the middle of the container (mdl-layout__content) the tab panels align to the left. Granted, this can be fixed with a custom container, but shouldn't the default behavior  be more unified (ie both tabs and panels align in a similar manner) or at least offer an easy way to change the alignment (ie mdl-tabs__align-center).
Additionally, I noticed undocumented classes: mdl-layout__tab, mdl-layout__tab-panel, mdl-layout--fixed-tabs etc. What are those intended for?

**Comment by Garbee** [comment]
The "undocumented" classes are for the Layout component when using tabs. Thus, they are documented in the layout component and not the tabs docs.

As far as alignment, what we provide for *tabs* aligns with what the spec provides as far as I can tell. The content is not defined, as it is up to developers to decide how to display the content. Also, yes it seems odd having 3 small tabs and the data flys out to the left, but what about someone with 10 tabs? It would look about right.

What exactly would you like us to provide? It isn't absolutely clear from the primary description. Do you want re-alignment of tabs or the content? Something else?

**Comment by Deilv** [comment]
Thank you for the reply Garbee.

I just noticed that they are listed at the first section of the layout component. Notice how they are not referenced or used in any of the tab examples, which are on the same page?
Actually, I tried to figure out how they are meant to be used, but they just messed up my panels.

Anyway, what I would like to have is an easy option to define how the tabs and the content aligns, instead of having to include my own custom css to modify the default behavior. I am talking about a set of classes (possibly usable elsewhere too) that aligns a component to the left or center or right. Please note that using three grid cells (4-col) does not work, because the default left margin of the panel is 0.

I will see if I can provide you with a specific code change later or today.

**Comment by Deilv** [comment]
After playing around a bit longer I found an easy solution to my problem, which isn't mdl's problem, so I'll close this issue.

I still think that mdl-layout__tab* classes should be listed in the layout/tabs section rather than layout/navigation, along with some usage example (can't get it to work properly, my panels just vanish).

**Comment by ghost** [comment]
What was the easy solution? I want my tabs to be aligned to the left as well.

**Comment by kcox1021** [comment]
This worked for me:

`div.mdl-tabs__tab-bar {
    justify-content: left;
}`
