### ISSUE TITLE
Waterfall header jumps to bottom on Android

### ISSUE THREAD

**Issue by surma** [google/material-design-lite#1901]
[Comment](https://github.com/google/material-design-lite/issues/1791#issuecomment-158801287) by @ccarsona:

On Android:
1. Go to http://www.mobotic.com/mld/bug.html
2. Click a link in header
3. Scroll to top
4. Page jumps to bottom when header expands

**Comment by surma** [comment]
Nvm me... Duplicate of #1900

**Comment by ccarsona** [comment]
Just an additional note. It works properly with fewer menu items.
