### ISSUE TITLE
Footer position changes on load, onresize script does not fire

### ISSUE THREAD

**Issue by noilly** [google/material-design-lite#1909]
When using a mini-footer, on page load the footer changes position - the footer moves form just below to the content to the bottom of the browser window. The fact the footer is at the bottom of the browser window is welcome, however it is causing issue with my resize script. My script is used to detect changes in size of the 'main' tag, and if such a change occurs, fires another script. The initial position of the footer causes the 'main' tag to have a certain height, however when the position of the footer is changed, this does not cause my script to be fired. If I then change the window size manually, the script fires as expected.

This is what the window looks like on initial load (the console shows the 'main' tag height):
![ginger_onload](https://cloud.githubusercontent.com/assets/7479776/11357646/241388e8-92b5-11e5-9b90-f66286e37900.PNG)

This is what the window looks like after manually changing the size:
![ginger_manual](https://cloud.githubusercontent.com/assets/7479776/11357650/2a882b8e-92b5-11e5-8dd7-b7fcc82e27e6.PNG)

In the first screenshot you'll see the 'editor' does not push up against the footer; that is because it has not been resized to fit the 'main' tag. In the second screenshot, after manually changing the window size the 'main' tag height changed triggering a resize, which can be seen as it caused the 'editor' to resize and push up against the footer.

**Comment by surma** [comment]
@noilly Would you mind setting up a codepen that reproduces this issue? (Maybe a resize handler is enough to show of a discrepancy?)

**Comment by noilly** [comment]
@surma I think this covers it! https://codepen.io/anon/pen/MadZpR

**Comment by noilly** [comment]
P.S. I am no longer sure it is the footer that causes the issue. Taking out the footer didn't solve the problem (though initially I was convinced that the problem didn't start happening until after I had inserted the footer) - the problem persists without the footer.

**Comment by surma** [comment]
Thanks for the codepen, @noilly. Luckily, the solution is quite simple. You run your `resizeAce()` before our JS has run so it actually does the correct thing, just way before layout has actually adjusted to the screen.

```JS
document.querySelector('.mdl-layout').addEventListener('mdl-componentupgraded', function() {
  resizeAce();
});
```

That should fix it :)

**Comment by noilly** [comment]
Thanks, that fixed it! :)

**Comment by Garbee** [comment]
FYI, I believe our `mdl-componentupgraded` events bubble. So, within that handler you may want to just check the event target and verify it is indeed the layout. That way it isn't running on every other component in your page being upgraded.
