### ISSUE TITLE
Checkboxes not visible on Chrome when checked on colored background

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#1910]
Hi,

Checkboxes on Chome are not visible when checked on a primary colored background.

Gif as exemple :

Firefox / IE11 / Edge
![ff](https://cloud.githubusercontent.com/assets/10220170/11364471/01803fa6-92a1-11e5-92a4-5a77131eef93.gif)

Chrome Canary
![chrome](https://cloud.githubusercontent.com/assets/10220170/11364476/08160a44-92a1-11e5-8f9b-841646657423.gif)

**Comment by Garbee** [comment]
Can you please provide a codepen example? Things are working fine here in
canary it seems.

**Comment by jfily** [comment]
Available here : http://codepen.io/jfily/pen/QjROwd

**Comment by jfily** [comment]
Adding .mdl-checkbox__box-outline { background-color: #fff; } seems to solve the problem.

**Comment by Garbee** [comment]
Can someone point out in the spec how this is expected to work? I'm not seeing anywhere defining how a selection control would look when the background is the primary color as well. Looks like an edge-case that has yet to be covered by anyone.

**Comment by surma** [comment]
The fact that it works in FF/IE is more of a coincidence, to be honest. We are using SVG masks which behave very inconsistently across browsers. 

As a workaround I can only offer to copy the `background` styles from the `.mdl-checkbox__tick-outline` element into your own CSS and adjust the color.

**Comment by Garbee** [comment]
IE/FF is also still not getting any animations to go along with it. Ideally, I think we should urge against using a checkbox in this context as it doesn't seem to make any sense from a Material Design point of view. The components are meant to be put onto light (or possibly dark but we don't directly support it) backgrounds. Not backgrounds that also take on the primary color pallet. I'm not seeing any instances of this in the specification for any component.

**Comment by jfily** [comment]
If it may help, this is what I wanted to do (in french sorry, translation is pending) :

![login](https://cloud.githubusercontent.com/assets/10220170/11406043/da43594e-93ab-11e5-8c41-1b9591f64385.PNG)

There is no specs (as far as I know) about login (/ register) forms, so I did this to try.

**Comment by Garbee** [comment]
I'm going to close this out as non-actionable for us. Colors in MD are not meant to be used like this. The primary background should be either light or dark, not a primary or accent color. They are used against the background to provide good contrast.

There is nothing we can feasibly do to account for the container background color when assigning colors to elements. You will need to handle these cases in custom code since it is not in alignment with MD.

**Comment by jfily** [comment]
Inbox android app is not thinking your way :)

Nervermind, i'm going to find a new way to make my login form.

![screenshot_2015-11-25-21-24-29](https://cloud.githubusercontent.com/assets/10220170/11408718/44a82850-93bb-11e5-9d31-9ee0b1b55f73.png)

**Comment by Garbee** [comment]
This is an example of an *empty page state*, where no data is present and you have no actions aside from the FAB which already has good contrast. Perfectly acceptable here to invert the colors a bit.

Also, so what? Different teams can (and do end up doing) whatever they please as far as Material Design goes. We can only do the best we can with the technology the web provides.

We are **NOT** a framework. We are not trying to provide developers with every little thing they may ever need to build an app using Material Design. We offer a basic set of functionality that will help achieve the upper 80 to 90 percent of what developers will need. From there, they can take it on their own to finish things off and make it look as good as they want.

As far as I can tell, what you are asking for is not specified and to achieve what you want nicely will take new web standards (or a bunch of extra complicate JS.) So it isn't in the projects best interest to provide this functionality.
