### ISSUE TITLE
Bug in Android.com MDL Skin Demo

### ISSUE THREAD

**Issue by j-norwood-young** [google/material-design-lite#1912]
1. Scroll down a bit and click the first turquoise down-arrow (#screen)
2. Scroll back to the top of the page

The page jumps back down to #screen as soon as you hit the top of the page.

Tested on Chrome.

**Comment by Garbee** [comment]
Upstream chrome bug with I'd references. Nothing custom here. Already fixed, just waiting for new stable release.
