### ISSUE TITLE
Snackbar got lost on v1.0.6 release

### ISSUE THREAD

**Issue by tylkomat** [google/material-design-lite#1913]
Snackbar is not included in the 1.0.6 release. Is this intended?

**Comment by Garbee** [comment]
It is not lost at all. It was never added to 1.0.x since it is a new feature. It went directly to master for 1.1.

**Comment by tylkomat** [comment]
Ok thanks. Maybe it could be marked for milestone 1.1 such that other people don't get confused too.

**Comment by Garbee** [comment]
Pull #1519 which added it already was tagged properly.

Also, we are following SemVer as best we can, so it should be known that new features go into the next minor.
