### ISSUE TITLE
Trigger tooltip programatically

### ISSUE THREAD

**Issue by rj33** [google/material-design-lite#1914]
Reading the code, it looks like tooltips require a mouse interaction to trigger. It would be nice if there was a way to trigger the tooltip via code. My use case is an SVG line graph where I want points on the graph to have tooltips triggered if the mouse is anywhere on the Y-axis at a point that is close to the X-axis value for the point (so the mouse pointer might be quite distant from the actual point). 

Because the tooltips only trigger on mouseover there is no direct way to do this right now (AFAIKS), so I need to resort to ripping out the positioning code from:
MaterialTooltip.prototype.handleMouseEnter_
and duplicating it into my own positioning code.

It would be great if the code in MaterialTooltip.prototype.handleMouseEnter_ could be factored out into a positioning function (you grab the target from the event in that code, but from what I can see you could just use the already saved target from the "for" attribute which would make such a function independent of the mouse event).

**Comment by Garbee** [comment]
The [tooltip specification](https://www.google.com/design/spec/components/tooltips.html) states:

> Tooltips are labels that appear on hover and focus when the user **hovers over an element with the cursor**, **focuses on an element using a keyboard** (usually through the tab key), or **upon touch** (without releasing) in a touch UI. 

Allowing tooltips to be programatically triggered would mean deferring from their specified function. Tooltips are also given specific dimensions to be away from their emitting point. So allowing arbitrary placement is also directly going against the spec.

Closing the request since fulfilling it means distancing from the specification in multiple ways. This is a use-case developers will need to handle on their own unfortunately.

**Comment by rj33** [comment]
Ok, although I'm not asking for arbitrary placement, I'm asking for arbitrary triggering (and subsequent arbitrary hiding), and would want to trigger the default placement myself rather than relying on hovering directly over the element to trigger.

I do see your point that my idea of triggering placement based on focusing near the element rather than on it does appear to be outside the spec description. I do believe the closest MD visual element to do what I want is the tooltip though, so it is a pity the only option to trigger placement is by either copying the tooltip's own code, or mocking up an event with the "for" element as the target, and passing it to the private handleMouseEnter_ function. 

I appreciate that the use is outside the current spec, and so I'm happy to handle it on my own, I just wish the positioning code could be factored out of the event handler so that "handle on my own" was able to look a little less ugly than it will with the current tooltip implementation.

Anyway, thanks for your response :-)
