### ISSUE TITLE
Move to travis.

### ISSUE THREAD

**Issue by samccone** [google/material-design-lite#1916]
Are there any reasons why we need to roll our own CI for this project? Moving to Travis would offload the burden of running the ci and also give us a better admin ui for things like retying builds

**Comment by Garbee** [comment]
Not a one. It was only done originally due to the project being private. Now that we are open, we can go anywhere. Someone just needs to provide the TLC for a smooth transition.

**Comment by surma** [comment]
In case it isn’t clear by now, we currently have our own private instance maintained by the prolific @crhym3. I don’t see a *functional* benefit for Travis over Drone except for reducing the workload on @crhym3 :wink: 

Currently we have a custom docker image where we can install anything. Would Travis be able to run our tests (needs non-headless... headful? Chrome)? I feel like it should, but I honestly don’t know.

**Comment by samccone** [comment]
yep to be clear the win here is less infrastructure work for @crhym3 and as @Garbee said in another thread an easier UI to retry tests and such.

I am pretty sure we will be able to do everything we want on travis

**Comment by crhym3** [comment]
if you guys want to move to travis, be my guest. just let me know and i'll disable drone in the settings. or other admins can do it, too.

**Comment by crhym3** [comment]
btw, i'm maintaining that drone instance anyway, for other projects.

**Comment by crhym3** [comment]
I just saw someone activated Travis, so assumed you're moving there and removed drone webhook.

**Comment by surma** [comment]
Uhm, are we? @samccone @addyosmani

**Comment by samccone** [comment]
I did not change it yet

**Comment by crhym3** [comment]
Well, someone else did it then. Check out Webhooks & services in Settings.

**Comment by Garbee** [comment]
Maybe it was leftover from a few months ago when travis was initially tested. Looks like the [first build](https://travis-ci.org/google/material-design-lite/builds/69757743) was @crhym3 setting it up. If the key was removed after testing then added back in, who knows how it got there. Just saying... could be leftover by accident.

**Comment by crhym3** [comment]
No, I cleaned up after my tests 5 months ago. Looks like @addyosmani did it:

![screen shot 2015-11-27 at 7 15 19 pm](https://cloud.githubusercontent.com/assets/25405/11447505/c70c017a-953e-11e5-9cb0-452c07e69431.png)

**Comment by sgomes** [comment]
There's no work going into changing our CI at the moment, so I've asked @crhym3 to re-enable Drone (thanks @crhym3!).

Drone is working pretty well for our current set of tests, and we'll likely be more preoccupied with feature work in the near future, so I'm closing this bug for now. We can look into changing CIs if we expand our tests beyond what we have right now and need new infrastructure, or if we find out that Drone is missing some other functionality we need.

**Comment by surma** [comment]
:+1:
