### ISSUE TITLE
Hide / Show Classes

### ISSUE THREAD

**Issue by abetsagaral** [google/material-design-lite#1917]
what is the class of showing and hiding content by device via media query? 

In bootstrap we have .visible-xs-*, .hidden-sm, etc... 

i want to hide some section when viewing small devices like tablet portrait (600x800). etc,,

thank you in advace
-Abet

**Comment by abetsagaral** [comment]
just figured out

Configuration options
https://github.com/google/material-design-lite/tree/master/src/layout

**Comment by Garbee** [comment]
The [grid docs](http://www.getmdl.io/components/index.html#layout-section/grid) cover what is available in the CSS Config section. `mdl-cell--hide-{whatever}` classes.
