### ISSUE TITLE
Layout search

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#192]
The layout component should have [search capability](http://www.google.com/design/spec/patterns/search.html#). This would make it easy for sites to have a nice searching experience in the header.

The update would not include typeahead type stuff. Developers would use their own solution for that and apply the mdl-list styling against results to get the proper style for that.

**Comment by sgomes** [comment]
This sounds like something that will be composed out of the modular components from v2, rather than something we should provide as a sufficient component. Closing, but feel free to reopen if you disagree.

**Comment by Garbee** [comment]
We should provide this as a full component, but on its own and not integrated into the core appbar implementation. A new issue was opened just now, so I set that one to the Post-V2 milestone and we can assess it further then once we know what we are dealing with. Depending on *how* we implement V2 appbar/toolbars it could be tricky.

This is still a piece of *core defined functionality* and search is fairly major to sites. So, we should provide this behavior imo.
