### ISSUE TITLE
menu display problem

### ISSUE THREAD

**Issue by time-river** [google/material-design-lite#1922]
That's a problem that I meet.
In chrome browser  46.0.2490.86 Linux
![menu_1](https://github.com/time-river/time-river/raw/master/issues/menu_1.png)
but in Firfox, the display is normal
![menu_2](https://github.com/time-river/time-river/raw/master/issues/menu_2.png)

I find it will display normally in chrome if deleting `mdl-layout__header--waterfall`  attribute.
I don't know whether it is bug.
here is my code(In order to make navigation-bar clear, I delete `mdl-layout__header--transparent`,

[gist](https://gist.github.com/time-river/524932a05a562e733525)

**Comment by Garbee** [comment]
You need to override the overflow property on the header. By default it is overflow none to prevent odd things with large menus. Since the menu is overflowing the container, it gets hidden by this.
