### ISSUE TITLE
data-table: check\uncheck behavior

### ISSUE THREAD

**Issue by virtyaluk** [google/material-design-lite#1925]
Once you click "toggle all" checkbox in the header section - all the table checkboxes would be checked.
But once you uncheck some of the checkboxes - header checkbox would be still checked.
I think, it would be correct  to uncheck header checkbox right after any of checkboxes has been toggled off.

**Comment by Garbee** [comment]
The current checkbox functionality is [deprecated](https://github.com/google/material-design-lite/wiki/Deprecations#data-tables). Developers should create checkboxes manually and then they are responsible for implementing such functionality.
