### ISSUE TITLE
Google adsense is loaded twice because of "mdl-js-layout"

### ISSUE THREAD

**Issue by RapidHunter** [google/material-design-lite#1926]
Here's the example: http://rapidhunter.ru/adsense-bug/
It's a simple page with a layout from the docs and a google adsense block. As you can see when the page is loaded an ad shows up, and after a moment there's a blink and it is replaced with another one. If you remove the "mdl-js-layout" from the layout div, then the bug disappears.

**Comment by Garbee** [comment]
Run the script after the layout is upgraded. You can listen for the `mdl-componentupgraded` [event](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js#L232) and check if the target is your layout. If it is, then execute the JS.

There are some known incompatibilities with quite a few other JS things around the web, but we can't solve them until 2.x due to backwards compatibility.

**Comment by rtwk** [comment]
@Garbee would you provide a jsbin / codepen snippet showing how to fix the issue?

**Comment by kaushal235** [comment]
@rtwk 
here is solution.
https://b.0218.jp/20160722000557.html

rather then loading static 'adbygoogle.js'(//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js),
create script dyanamic after "mdl-componentupgraded" event.

```
document.addEventListener('mdl-componentupgraded', function() {
    if (!document.getElementById('adsbygooglejs')) {
        var head = document.getElementsByTagName('head')[0];
        var script = document.createElement('script');
        script.id = 'adsbygooglejs';
        script.src = "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
        head.appendChild(script);
    }
});
```

Don't forgot to removed  statically loaded '//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'

**Comment by akoppa** [comment]
It doesn't work for me. I placed the script in the <head>
I have never had this problem until I changed my WP blog to run Acme Supermag theme.

**Comment by Aliiqbalch2** [comment]
can 

> @rtwk here is solution. https://b.0218.jp/20160722000557.html
> 
> rather then loading static 'adbygoogle.js'(//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js), create script dyanamic after "mdl-componentupgraded" event.
> 
> ```
> document.addEventListener('mdl-componentupgraded', function() {
>     if (!document.getElementById('adsbygooglejs')) {
>         var head = document.getElementsByTagName('head')[0];
>         var script = document.createElement('script');
>         script.id = 'adsbygooglejs';
>         script.src = "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";
>         head.appendChild(script);
>     }
> });
> ```
> 
> Don't forgot to removed statically loaded '//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'

where to put this code
