### ISSUE TITLE
responsive grid spacing

### ISSUE THREAD

**Issue by remkoboschker** [google/material-design-lite#1927]
On a phone I prefer `mdl-grid mdl-grid--no-spacing` and on a desktop I prefer with spacing. Could there be a responsive equivalent for grid spacing of the responsive colomn width i.e. `mdl-grid mdl-grid--no-spacing-phone`?

**Comment by surma** [comment]
I am not sure that changing the gutter size is spec compliant, but I do see your use- case.

@sgomes WDYT?

**Comment by sgomes** [comment]
Technically it's not too hard to do, but I'm not sure how frequent a use-case this is. I'll see if I can come up with a more generic approach when working on the grid for 2.0. Thanks for the suggestion, @remkoboschker!

**Comment by remkoboschker** [comment]
Thank you for this great framework!

**Comment by thejohnsmith** [comment]
The last four advertising agencies I've worked with constantly call for this.
A helper class for full-bleed on mobile would be very useful for me.

**Comment by sgomes** [comment]
Thanks for the info, @remkoboschker and @thejohnsmith! Out of curiosity, would it be an issue if the horizontal and vertical gutters (i.e., the spaces between cells) were 0px in that scenario?

**Comment by thejohnsmith** [comment]
You're welcome @sgomes! Happy to help.
It wouldn't be an issue for me and would use the same value as before:
```css
.mdl-grid.mdl-grid--no-spacing>.mdl-cell {
    margin: 0;
}
```

**Comment by remkoboschker** [comment]
You mean both horizontal and vertical? For me it would be enough if `mdl-grid--no-spacing` can be set depending on desktop / tablet / phone. I would use it to have a section appear from edge to edge on smaller devices. If need be I can add spacers that are optionally hidden to manage vertical spacing.
