### ISSUE TITLE
The mdl-data-table--selectable table can't change the line-height in CSS.

### ISSUE THREAD

**Issue by ceouk** [google/material-design-lite#1964]
The mdl-data-table--selectable table can't change the line-height in CSS.
So how to make rows shorter? 
![image](https://cloud.githubusercontent.com/assets/16193516/11641926/f8077060-9d32-11e5-8128-7d207f98594d.png)

http://www.getmdl.io/components/index.html#tables-section

**Comment by Garbee** [comment]
The table currently aligns to the Material Design specification as far as we are aware. Unless it is clearly not by having rows of the current size modifying it is on you.

General support like that can be asked for on StackOverflow. Using the `material-design-lite` tag along with any other appropriate tags for the task at hand.

**Comment by etale-cohomology** [comment]
To change the line height, try this:
```
th, tr, td{ height:0!important; padding-top:0!important; padding-bottom:0!important; }
```

**Comment by Garbee** [comment]
Please don't use important. It's a bad code smell that leads to harder to reconcile issues later. Also, general blanket element targets are also discouraged since they are too broad.

**Comment by etale-cohomology** [comment]
If you can think of a better way, please do provide the code!

**Comment by Garbee** [comment]
As I said, StackOverflow is the best place for general support. The problem asked is about modifying MDL to be out of alignment with the MD specification. That isn't something we can support here.
