### ISSUE TITLE
Snackbar is not working

### ISSUE THREAD

**Issue by Tim15** [google/material-design-lite#1995]
MDL v1.0.6
Google Chrome v46.0.2490.86 (64-bit)
[codepen to reproduce issue](http://codepen.io/anon/pen/JGdWML?fork=xGWgXa)
Javascript error: `Uncaught TypeError: Cannot read property 'showSnackbar' of undefined`

**Comment by oddui** [comment]
It is not in 1.0.6 #1913

**Comment by prajapati-jatin** [comment]
Hi Tim15,
I experience the same issue. When you try to directly call the showSnackbar on page load it will throw and exception because, as I think, material is not yet loaded or bound to the elements. If you put timeout then it will work.

`'use strict';
var sms = function(){
    var checkAndShowSnackBar = function(){        
        var snackbarContainer = document.querySelector('#notification');        
        var data = {message: 'Example Message #', timeout: 5000};
        snackbarContainer.MaterialSnackbar.showSnackbar(data);        
    };
    var timeout = function(fn, timeout){
        setTimeout(fn, timeout);
    };
    return{
        init: function(){
          new WOW().init();  
          timeout(checkAndShowSnackBar, 100);
        }
    }
}();

$(document).ready(function(){
    sms.init();
});`

`<div id="notification" class="mdl-js-snackbar mdl-snackbar">
            <div class="mdl-snackbar__text"></div>
            <button class="mdl-snackbar__action" type="button"></button>
        </div>`

Hope this will help you.

**Comment by shadyueh** [comment]
You're right about time, but I prefer this miraculous 'r' function 

```
r(function(){
    // put all that pesky code here
});
function r(f){/in/.test(document.readyState)?setTimeout('r('+f+')',9):f()}
```
The toast didn't want obey me, so it didn't give me another choice.
Explanations [here](http://stackoverflow.com/a/30319853/1214237)

**Comment by vladkalyuzhny** [comment]
This only works for me
```
angular.element(document).ready(function () {
    $timeout(function() {
        // DOM ready
    });
});
```

**Comment by cvrnogueira** [comment]
@prajapati-jatin  i try to user your solution and the solution from @shadyueh  and still not works. 
I literally copied the code of both of you and try and the same error occurs. I am using Vue, do you have any clue about what is going on?

**Comment by smourier** [comment]
I had the same problem, and only the combination of onready & timeout worked  for me (timeout can in fact be set to 0) for all recent versions of Chrome, IE11, Firefox and Edge (in fact, the setTimeout-only code worked for Chrome, IE11 and Edge, but Firefox required the onready to work, go figure...).

So, for what it's worth, here my complete minimal working solution. 

```html
<html>
  <head>
    <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  </head>
  <body>
    <div id="demo-toast-example" class="mdl-js-snackbar mdl-snackbar">
      <div class="mdl-snackbar__text"></div>
      <button class="mdl-snackbar__action" type="button"></button>
    </div>

    <script>
        // I used the modern & official onready way, but I guess you can replace it with more compatible (aka: funky) versions
        document.addEventListener('DOMContentLoaded', function() {
            setTimeout(function() {
                var snackbarContainer = document.querySelector('#demo-toast-example');
                var data = {message: 'Example Message !'};
                snackbarContainer.MaterialSnackbar.showSnackbar(data);
            }, 0);
        });
	</script>
  </body>
</html>
```

**Comment by mnogue** [comment]
I'm late to the party, but I noticed that the Material js file has a [defer ](https://www.w3schools.com/tags/att_script_defer.asp) property, which causes a delayed load. Remove it and should work fine (though it may introduce a loading hiccup).

Here's my complete solution. It stack-up notifications while the snackbar is not available and show them once loaded.

```javascript
var toast = {
    // elem contains the snackbar element. Change the id or use a 'querySelector'
    elem  : document.getElementById('toast'),
    init  : false,
    queue : []
}

function showToast(msg) {
    if (!toast.init) {
        toast.queue.push(msg);
        return;
    }

    var data = {message: msg};
    toast.elem.MaterialSnackbar.showSnackbar(data);
}

window.addEventListener('load', function() {
    toast.init = true;
    while (toast.queue.length > 0) showToast(toast.queue.shift());
    toast.queue = [];
})
```

**Comment by iHTCboy** [comment]
For me to use the delay time to solve：

    var snackbarContainer = document.querySelector('#div_toast');
    var attr = $(snackbarContainer.MaterialSnackbar).attr('showSnackbar');
    var isOk = false;
    // For some browsers, `attr` is undefined; for others, `attr` is false. Check for both.
    if (typeof attr !== typeof undefined && attr !== false) {
        // Element has this attribute
        isOk = true;
    }
    setTimeout(function () {
        snackbarContainer.MaterialSnackbar.showSnackbar({message: msg});
    }, isOk ? 0 : 0.5);

**Comment by lazluiz** [comment]
This is what I do, which is similar to some stuff people already did here:
```
function toast(value) {
    setTimeout(() => {
        if(document.getElementById('bigjo-snackbar').MaterialSnackbar) {
            document.getElementById('bigjo-snackbar').MaterialSnackbar.showSnackbar({
                message: value.toString(),
                timeout: 2000
            });
        } else {
            toast(value);
        }
    }, 9);
}
```

**Comment by lazluiz** [comment]
This is what I came up with, based on some answers in this post:

```
    toast(value, timeout = 3000) {
        setTimeout(() => {
            let snackBar = document.getElementById('snackbar').MaterialSnackbar;
            if(snackBar) {
                snackBar.showSnackbar({
                    message: value.toString(),
                    timeout: timeout
                });
            } else {
                this.toast(value, timeout);
            }
        }, 9);
    },
```
