### ISSUE TITLE
Downgrade in MaterialDataTable

### ISSUE THREAD

**Issue by datfinesoul** [google/material-design-lite#1997]
I've been running into some problems with the tables on a dynamically generated site.  Seems like once a table has been upgraded, there is no way to downgrade/re-upgrade it again, when the table data changes (new rows added/removed).  Looking at the code, it doesn't seem like MaterialDataTable has a mdlDowngrade method in it yet.  Are there plans to support downgrading tables?  If not, are there ways that I could just upgrade the new rows?

**Comment by samccone** [comment]
ref https://github.com/google/material-design-lite/pull/1815

**Comment by Garbee** [comment]
The Data Table component is officially [deprecated](https://github.com/google/material-design-lite/wiki/Deprecations#automatic-selection-checkboxes).

Manually creating your checkboxes allows you more control and relieves a bunch of internal logic from needing to be done to accommodate this.

**Comment by datfinesoul** [comment]
Thanks for the information.  I did not see that snippet about the deprecation before.
