### ISSUE TITLE
Mdl new attributes

### ISSUE THREAD

**Issue by xc4patryk** [google/material-design-lite#1999]
Hi,

Recently I noticed yours framework and i have a couple suggestion.
proposes to add:
1. Container based on the grid
2. Tooltip with position (left, right, bottom or top)
3. Responsive grid.... i mean that grid-auto-width should adapt to other
4. Visibility/Hide classes
5. Mobile First for grid. - That could see grid right or center not only left first for mobile scale.
6. Scroll function:
         a) when use button, page scroll down to '#example' - something like that
         b) sticky function, when page scroll = '#example' this '#example' = fixed
7. More Colors - not only primary and secondary or something to add easy more

may you think my proposals and... thanks for great stylish framework. If the framework will be developed, I will be happy to help.

**Comment by Garbee** [comment]
A good number of these requests either already exist, are being added with the next release (like tooltip positions), or are out of scope.

Please search current and past issues first, then file specific feature requests. We'd rather have 10 specific issues vs 1 mega-issue which is difficult to track and assign work towards.
