### ISSUE TITLE
Grid layout for tablet

### ISSUE THREAD

**Issue by LC43** [google/material-design-lite#2003]
Hi everyone!

by reducing the column number to 8, there's no rule for a 3 cell style. so, i would suggest to move back up to 12  or, just 6,  losing instead the 4 cell style.

I understand that 4 columns for smartphone makes sense, as one would mostly use a single or 2 cells.

thanks,

**Comment by Garbee** [comment]
The [specification](https://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-breakpoints) is what gives us the 4-8-12 grid structure. This isn't something we are willing to alter from. User experiences should be designed with this grid system in mind.

**Comment by LC43** [comment]
i see, thanks.
