### ISSUE TITLE
Scrollable elements doesn't work properly on iPhone 5s

### ISSUE THREAD

**Issue by marcinkowal2015** [google/material-design-lite#2014]
On my website I have problem when using layout component with scrollable content. Quite often when I want to scroll this content, whole body is scrolled. Or another case, when I have stacked elements and I want to scroll the top one, element beneath is scrolled(which isn't even visible). This behaviour occurs on iPhone 5s and doesn't occur on my htc desire 610 with android 4.4 and lastest version of chrome. Moreover it seems that on site getmdl.io in layout component this problem occures too also on http://www.material-ui.com/#/components/grid-list. Is it a problem with my iPhone or something wrong with mdl?

**Comment by surma** [comment]
It can happen anywhere, not only iOS. We are aware :confused: We made a bad choice in the way we implemented the layout, but we are stuck with it for 1.x. We are fixing it for 2.0, see #1735.
