### ISSUE TITLE
Documentation for list

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#2015]
The list component doesn't have any documentation at the moment. It needs a README.md, snippets, and an entry in getmdl.io, at the least.

**Comment by rohanthacker** [comment]
Hey @sgomes, Would you like me to work on this?

**Comment by sgomes** [comment]
@rohanthacker That would be fantastic, thank you! Anything you're able to put together would be great, and we'd fill in the blanks after that.

Also, sorry for the late reply, was off for holidays :)

**Comment by rohanthacker** [comment]
@Garbee  No Problem, Hope you have a good time.
I will start on this tonight.

**Comment by surma** [comment]
@rohanthacker Friendly ping about this. Did you find time to work on this?

**Comment by MashedPotats** [comment]
@surma I believe he did! I just built it with the list component. However, the documentation doesn't seem to be in there...

**Comment by Garbee** [comment]
@MashedPotats That is exactly what we are talking about here, the docs for the component.

**Comment by rohanthacker** [comment]
@sgomes  Hey, I've managed to get started and put the essential points into the README. However I was not sure how to go about the Step by Step Guide.

**Comment by MashedPotats** [comment]
@rohanhacker Interesting... I've found a branch with a documentation with instructions on usage. I'll link to it.

[https://github.com/google/material-design-lite/tree/styles-doc](https://github.com/google/material-design-lite/tree/styles-doc)

**Comment by surma** [comment]
Closing this as #3606 got merged.
