### ISSUE TITLE
Code style error

### ISSUE THREAD

**Issue by mtsweir** [google/material-design-lite#2031]
This is what I'm getting:

[23:36:22] Requiring external module babel-core/register
[23:36:23] Using gulpfile ~\Documents\GitHub\google\mdl\material-design-lite\gulpfile.babel.js
[23:36:23] Starting 'clean'...
[23:36:23] Finished 'clean' after 18 ms
[23:36:23] Starting 'default'...
[23:36:23] Starting 'styles'...
[23:36:23] Starting 'styles-grid'...
[23:36:25] styles-grid all files 18.77 kB
[23:36:25] Finished 'styles-grid' after 1.9 s
[23:36:27] styles all files 903.13 kB
[23:36:27] Finished 'styles' after 3.97 s
[23:36:27] Starting 'lint'...
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\mdlComponentHandler.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\animation\demo.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\button\button.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\checkbox\checkbox.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\data-table\data-table.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\icon-toggle\icon-toggle.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\layout\layout.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\menu\menu.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\progress\progress.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\radio\radio.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\ripple\ripple.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\slider\slider.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\snackbar\snackbar.js :
     1 |/**
-----------^
     2 | * Copyright 2015 Google Inc. All Rights Reserved.
     3 | *

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\spinner\spinner.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\switch\switch.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\tabs\tabs.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\textfield\textfield.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\third_party\rAF.js :
     1 |// Source: https://github.com/darius/requestAnimationFrame/blob/master/requestAnimationFrame.js
-------------------------------------------------------------------------------------------------------^
     2 |// Adapted from https://gist.github.com/paulirish/1579671 which derived from
     3 |// http://paulirish.com/2011/requestanimationframe-for-smart-animating/

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\tooltip\tooltip.js :
     1 |/**
-----------^
     2 | * @license
     3 | * Copyright 2015 Google Inc. All Rights Reserved.

1 code style error found.
Invalid line break at C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\gulpfile.babel.js :
     1 |/**
-----------^
     2 | *
     3 | *  Material Design Lite

1 code style error found.
[23:36:31] 'lint' errored after 4.16 s
[23:36:31] Error in plugin 'gulp-jscs'
Message:
    JSCS failed for: C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\mdlComponentHandler.js, C:\User
\Weir\Documents\GitHub\google\mdl\material-design-lite\src\animation\demo.js, C:\Users\Weir\Documents\GitHub\google\mdl
material-design-lite\src\button\button.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\checkbox\
heckbox.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\data-table\data-table.js, C:\Users\Weir\
ocuments\GitHub\google\mdl\material-design-lite\src\icon-toggle\icon-toggle.js, C:\Users\Weir\Documents\GitHub\google\m
l\material-design-lite\src\layout\layout.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\menu\me
u.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\progress\progress.js, C:\Users\Weir\Documents\
itHub\google\mdl\material-design-lite\src\radio\radio.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lit
\src\ripple\ripple.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\slider\slider.js, C:\Users\We
r\Documents\GitHub\google\mdl\material-design-lite\src\snackbar\snackbar.js, C:\Users\Weir\Documents\GitHub\google\mdl\
aterial-design-lite\src\spinner\spinner.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\switch\s
itch.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\tabs\tabs.js, C:\Users\Weir\Documents\GitHu
\google\mdl\material-design-lite\src\textfield\textfield.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-
ite\src\third_party\rAF.js, C:\Users\Weir\Documents\GitHub\google\mdl\material-design-lite\src\tooltip\tooltip.js, C:\U
ers\Weir\Documents\GitHub\google\mdl\material-design-lite\gulpfile.babel.js
[23:36:31] 'default' errored after 8.14 s
[23:36:31] Error in plugin 'run-sequence'
Message:
    An error occured in task 'lint'.

I have tried:
npm cache clean
Deleting the node modules folder then running npm install again.

My node version is 5.2.0

**Comment by addyosmani** [comment]
I haven't had problems building using your Node version, but do wonder if you have other global JSCS configs in a parent directory that might be interfering here. Is it possible for you to try running a build from a different path (perhaps `C:\Users\Weir\Documents\maerial-design-lite` and see if that makes any difference?

**Comment by Garbee** [comment]
Try the [instructions in the readme](https://github.com/google/material-design-lite#download--clone) for line endings on Windows. That seems to be the issue.

Closing this out for now assuming that is it, please comment if that doesn't fix it and we will re-open to investigate further.
