### ISSUE TITLE
Toggles don't animate in Safari

### ISSUE THREAD

**Issue by kengruven** [google/material-design-lite#2034]
MDL version: 1.0.6
Browser: Safari 9.0.1
Operating system: OS X
Operating system version: 10.9.5
URL: http://www.getmdl.io/components/index.html#toggles-section/checkbox

What steps will reproduce the problem:
1. Go to the demo page at http://www.getmdl.io/components/index.html#toggles-section/checkbox
2. Click on a checkbox, and watch it
3. Repeat in other browsers

What is the expected result?  It behaves the same in all "A-grade" browsers (e.g., Chrome, Firefox, Safari)

What happens instead of that?  Checkboxes have a smooth fade-in animation in Chrome and Firefox, but in Safari, they just click on and off instantaneously.

Please provide any other information below, and attach a screenshot if possible.

There's a demo [here](https://cloud.githubusercontent.com/assets/234957/10579158/724c517e-766e-11e5-8348-366f830d36a7.gif) that shows the fade-in animation working properly (possibly in Chrome?).

FWIW, [Polymer checkboxes](https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html&active=paper-checkbox) do animate in Safari 9, though the animation is different, and I don't see the specific style of animation mentioned in the Material Design specs, so I don't think it matters that MDL is different.

In Safari 9, the checkbox is still perfectly functional, but there's no fun animation.

**Comment by kengruven** [comment]
I tried this again today, and they do animate now.  Strange.

I'm still on Safari 9.0.x, but OS X 10.11 now.  I'll check my machine at work, too, but if I can't reproduce this any more, I'll close it.

**Comment by kengruven** [comment]
Hmm, I'm definitely seeing this bug (no animation) again on Safari 9, in OS X El Cap.

**Comment by sgomes** [comment]
I can't reproduce this issue on 1.1.2 and Safari 9.0.3. Please reopen if it's still around!

**Comment by kengruven** [comment]
It seems to work for me today, with those versions.  Looks good.
