### ISSUE TITLE
Javascript chart not showing

### ISSUE THREAD

**Issue by christoga** [google/material-design-lite#2035]
Hey There,

I have a project called "Cepat Sembuh", the project use bootstrap and material design framework,
The problem is...

I try to use Chart.js by @nnick, 
But the chart is not showing

The code is live at https://github.com/christoga/cepatsembuh
And the problem is at royal.html on www/ folder

Thanks!

**Comment by Garbee** [comment]
Please use StackOverflow for support. This tracker is only for direct problems with the code provided by MDL.
