### ISSUE TITLE
Button + Ripple initialization race condition

### ISSUE THREAD

**Issue by passy** [google/material-design-lite#206]
I discovered a bug, but haven't been able to reduce this to a minimal test case. I'll dig into this again in the next days, but perhaps this is already helpful.

When dynamically adding an `mdl-button` with ripple effect, it is possible to end up in a state where the `mdl-button__ripple-container` and its `mdl-ripple` are added, but `rippleElement_` inside `MaterialRipple` is uninitialized. When triggering a ripple, it causes an exception in this line:

``` js
MaterialRipple.prototype.upHandler_ = function(event) {
  'use strict';

  // Don't fire for the artificial "mouseup" generated by a double-click.
  if (event && event.detail !== 2) {
    // **Uncaught TypeError: Cannot read property 'classList' of null**
    this.rippleElement_.classList.remove(this.CssClasses_.IS_VISIBLE);
  }
};
```

([Source](https://github.com/google/material-design-lite/blob/830b8d01b94062c62a4b308c8fdbc9b46f877a87/src/ripple/ripple.js#L110))

Most other places in the file guard against `this.element_` being null, but adding a fix here would only mask the underlying problem that the initialization is incomplete. The DOM, however, looks like this:

``` html
<span class="mdl-button__ripple-container"><span class="mdl-ripple"></span></span>
```

I'll try to narrow this down further, I think there's a very small window when the component handler races against the initial render of my layout, which happens via `virtual-dom` materialization.

**Comment by samosfator** [comment]
+1

**Comment by sgomes** [comment]
@samosfator Could you elaborate on your "+1"? Are you running into this issue, and if so, could you provide more details?
