### ISSUE TITLE
how to align footer at the bottom of an empty page ??

### ISSUE THREAD

**Issue by an0nh4x0r** [google/material-design-lite#2077]
Please provide some notes or maybe docs on where to place footer so that it always sticks at the bottom of the page. 

here is the hack http://jsfiddle.net/zrqeskLk/12/ ... but please provide some good code.

**Comment by Garbee** [comment]
Sticky footer is not directly defined by MDL. (If you do see it in the spec, please point it out!) Therefore, it is not supported outright. If you need help with custom additions, StackOverflow is the proper channel for that.
