### ISSUE TITLE
[Component Request] {Component}

### ISSUE THREAD

**Issue by vamsikrishna290** [google/material-design-lite#2080]
Please include:
Angular2 support for MDL

if we are using MDL with Angular2 component templates, right now the page is not rendering properly. On the very first load all seems good but on page refresh the page is broken.

Can you explain us how do we fix this?

**Comment by Garbee** [comment]
We don't do integration support in the tracker. You should use StackOverflow or other support channels for building sites. This issue tracker is only for direct issues with material design lite.
