### ISSUE TITLE
[Component Request] {Component}

### ISSUE THREAD

**Issue by vamsikrishna290** [google/material-design-lite#2083]
is it possible to provide various javascript functions to customize the implementation? right now on load they are all binding to the elements. is there any way we can bind the events explicitly?

**Comment by Garbee** [comment]
The request is kinda vague. Needless to say in V2 developers will be binding most events themselves other than what is *needed* for components to function (like on blur/focus/active for form elements.)

I am looking into adding events to let developers handle custom logic for different situations. However, directly modifying the bound listeners is a no-no. If you want to do that, then you should be building your own custom implementation.

Once V2 stuff lands in master (after 1.1 is out which may still be a bit.) Take a peek and file specific bugs against that for what you would like to see improved along these lines.
