### ISSUE TITLE
Style ::selection

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#215]
Should we style selected text with the accent color of the theme? I think this would make a neat subtle enhancement.

The [spec](http://www.google.com/design/spec/patterns/selection.html) makes no mention of which color to use for the selected text. Do they expect you just always use the system default? Could we get some guidance from them as to what color to use?

cc @addyosmani since this could use some outreach to the MD team.

**Comment by sgomes** [comment]
Following our current "less is more" approach, I'm going to declare this out of scope and close the issue.

**Comment by Garbee** [comment]
We actually *should* do this where appropriate. It just needs to be handled at the component-level instead of some quick global method. Just something to keep an eye out for when going over the specs since some specifically declare selection styling. If it isn't directly declared, then we just don't worry about it.
