### ISSUE TITLE
Accordion needed?

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#221]
I have the SCSS, HTML and Dart-Code. If you want I can create a PR with SCSS+HTML. It should be easy to port the Dart-Code back to JS.

Demo: http://mdl.mikemitterer.at/#/accordion
Styles: https://github.com/MikeMitterer/dart-material-design-lite/tree/mdl/lib/assets/styles/accordion
Code: https://github.com/MikeMitterer/dart-material-design-lite/blob/mdl/lib/src/components/MaterialAccordion.dart

![screenshot-1773](https://cloud.githubusercontent.com/assets/116654/7298005/03553408-e9cd-11e4-8a92-3144b77179f4.png)

**Comment by nickretallack** [comment]
I need this too.  I was just using jQuery.slideToggle until a designer pointed out that it should use the easing function from material design.  I see that function is implemented in mdl-animation--default, but I'm not sure how to get an element to animate its height between zero and whatever height it wants to render at.  It only works if I set the height explicitly.

I took a look at these guys' example, and they seem to be hard-coding a max height of 1500px.  This is not ideal.  Aside from the fact that it puts an arbitrary maximum on the height of the element, it also messes up the easing.  Opening will happen too fast, and closing will have a slight delay as it collapses all the invisible extra content between the real height and 1500px.

I'll see if I can copy the way they're doing it on the material design spec site, where they're animating the "top" property to slide a div outside of an "overflow: hidden".

**Comment by innerpeace0** [comment]
Isn't this from another project also named Material Design Lite? I like the idea of an accordian, even though MD doesn't use the term. It's a common UI component.

**Comment by Garbee** [comment]
> It only works if I set the height explicitly.

This is a drawback of CSS. It must have a set height for animation.

**Comment by Garbee** [comment]
> It's a common UI component.

We are not worried about a checkbox listing of "common UI components" compared to other things. MDL implements Material Design as best it can. That is all we are worried about being in core. Anything else ends up being scope creep and deferring from the spec (if any.)

**Comment by nickretallack** [comment]
I just need it for the list control behavior.

**Comment by nickretallack** [comment]
[Here's my prototype](http://nickretallack.com/experiments/mdl/collapse/index.html).  Pretty cool, right?

It'd be nice if MDL had some better facility for putting icons into menus like in the [list controls spec](https://www.google.com/design/spec/components/lists-controls.html).  Currently I'm  fudging that with position:absolute.

**Comment by Garbee** [comment]
Just target what you need and use before and after pseudo elements. Works fine.

**Comment by nickretallack** [comment]
Can you show me an example?

Specifically, I'm asking how I should have positioned the "expand_more" icons in my example to match the spec.  They aren't quite right, and just putting them in before the existing content doesn't look right either.  The [Dashboard Template](http://www.getmdl.io/templates/dashboard/index.html) example positions some icons nicely, but that's all custom CSS that isn't included in MDL.

**Comment by MikeMitterer** [comment]
@nickretallack Check this out: http://www.material-design-lite.pub/#/accordion this is MDL/Dart

**Comment by nickretallack** [comment]
I did look at that.  Notice how it sets max-height to 1500px and then animates max-height?  That's bad.  My implementation is better.  I based mine on the navigation drawer used on [the spec site](https://www.google.com/design/spec/material-design/introduction.html) itself.

**Comment by maverix** [comment]
@nickretallack Can you make a pull request from your demo?

**Comment by nickretallack** [comment]
The JavaScript in my example is very small.  We could easily remove jQuery as a dependency.  I mostly use jQuery for browser compatibility, so I'd need to know what compatibility guarantees MDL has.  I'll consider making a pull request soon.

**Comment by Garbee** [comment]
To be honest, making a Pull Request currently is most likely not going to go far. First we need to get Lists      (issue #584 ) implemented, then we can work on the list controls specification where this is defined.

**Comment by nickretallack** [comment]
It can be orthogonal.  My demo is implemented on top of mdl-navigation inside a drawer, but since it's mostly behavior you could port it to anything.

**Comment by davidzchen** [comment]
Now that lists are implemented, is it feasible to add expandable list controls, such as from @nickretallack's prototype? Or is this on hold until V2 is done?

**Comment by Garbee** [comment]
No new features are being added to 1.x. It is patches-only until 2.x. 2 is not planned to include any new components either since we are reworking their architecture entirely.

**Comment by Thanood** [comment]
> No new features are being added to 1.x

That seems to [have changed](https://github.com/google/material-design-lite/issues/4163#issuecomment-192241485), though. :smile:

**Comment by sgomes** [comment]
@Thanood It has indeed! We're definitely open to PRs for new components now, although sadly we don't have the time to implement any new components ourselves while working on v2.0.

@nickretallack: if you're reading this and you like the idea of sending us a PR for your cool-looking accordion, I'd be more than happy to review it myself :)

**Comment by leifoolsen** [comment]
For those who might be interested, I have released an MDL 1.x WAI-ARIA friendly Accordion component to NPM. Code can also be cloned / downloaded from [GitHub](https://github.com/leifoolsen/mdl-ext).

![Accordion](https://github.com/leifoolsen/mdl-ext/blob/master/etc/flexbox-accordion.png)

Regards
Leif Olsen

**Comment by mibamur** [comment]
@nickretallack could you post sources prototype somewhere?

**Comment by salamanders** [comment]
I too would love Expand/collapse.

The little up carat / down carat that shows/hides divs would be super helpful.

https://www.google.com/design/spec/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by leifoolsen** [comment]
@salamanders 
You can find a MDL, WAI-ARIA compliant, accordion component in my git repo: https://github.com/leifoolsen/mdl-ext/tree/master/src/accordion. Live demo here: http://leifoolsen.github.io/mdl-ext/demo/accordion.html. 
![accordion](https://cloud.githubusercontent.com/assets/10088486/15094585/00bd09a2-14a9-11e6-92e3-0a2f21d89c97.png)

**Comment by sgomes** [comment]
Closing this for now. MDL is moving to closer adherence to spec, and there are currently no guidelines on accordions. I'd prefer we don't move ahead of spec here.

**Comment by ChristopheVersieux** [comment]
@nickretallack your demo looks awesome! 
Unfortunately, id doesn't provide a phone layout on an iPhone 6, instead I get the desktop version.
But strangely, while I resize a desktop browser to a decent width, it seems to work. Any idea what's wrong?

**Comment by Garbee** [comment]
@ChristopheVersieux Please get support either in the other projects repositories or on support locations such as StackOverflow. This tracker is only for discussion about issues related to the code provided by Material Design Lite.

Thank you.

**Comment by iryan2** [comment]
@sgomes The spec never mentions accordions by name but they're definitely in there: 
["Carded content that expands and collapses"](https://material.google.com/layout/structure.html#structure-whiteframes)

Google Inbox would be the obvious example of this pattern in the wild. I'm not necessarily saying that MDL should provide this component, just pointing out that it does make an appearance in the spec.

**Comment by Garbee** [comment]
The spec references a lot of things by mention. Just like badges, they are shown and used but never strictly defined by the MD team.

The only specified collapse elements that we currently know of are navigation drawer submenus. Until the MD team specifies other things directly, we are highly unlikely to implement them within MDL. The goal is to provide the specified components as best we can. Anything else leaves too much leeway to determine what is right and wrong.

**Comment by sgomes** [comment]
@iryan2 We will likely have expansion areas for cards, yes. Having it as a standalone accordion is less certain, though; it depends on how many components need the expanding section behaviour and whether we can make it generic enough.

**Comment by oneezy** [comment]
@sgomes is this getting brought into the new and improved Material Design Components? I looked there and an expansion panel/ accordion seems to be missing

**Comment by Garbee** [comment]
It is on the list of things to be done. No work towards it yet.

MDL is getting it with the final patch release. You can check it out by pulling `master` now and building it.

**Comment by BlkPingu** [comment]
Was the Accordion merged? I need this

**Comment by deemte** [comment]
I think there is a very good example  - already implemented to the project.
Check this out: [https://github.com/parys-github/material-webpack-boilerplate](https://github.com/parys-github/material-webpack-boilerplate)
