### ISSUE TITLE
BEM linting

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#2262]
We should [lint bem](https://github.com/postcss/postcss-bem-linter) to verify we are always adhering to the structure.

Targeting V2 to get this integrated into our chain.

**Comment by samccone** [comment]
good idea :)

**Comment by Garbee** [comment]
You can thank @pudly for bringing this idea to mind. He told me the tech exists after an off-the-cuff remark.

**Comment by Garbee** [comment]
I have this functioning now. But... I can't figure out how to get [Harry Robert's convention](https://en.bem.info/tools/bem/bem-naming/#convention-by-harry-roberts) to be recognized. The linter only wants to lint the default BEM syntax.

So, I'm going to move forward with this, which will mean converting `--` for modifiers to `_` for us. There may also be other little details to get figured out with how some of the more complex selectors are working. It also does not like double-class structures to increase specificity a bit.

**Comment by surma** [comment]
Changing convention is rough, even for a v2. Still might be worth to have the whole thing linted. Not sure.

**Comment by Garbee** [comment]
A lot of things are already being heavily modified. V2 isn't going to be something where there is a direct upgrade path. Might as well change now and have the tooling in place to keep us as straight as we can going forward.

FWIW, a quick `--` to `_` regex replace does just fine here. So where people can quickly upgrade things it shouldn't be a problem (except for colliding with custom classes. But, even that is solvable with regex.)

**Comment by shaneog** [comment]
Has any work been done on this?
If not, I'd be willing to have a go. 

Using [stylelint](https://github.com/stylelint/stylelint) and [stylelint-selector-bem-pattern](https://github.com/davidtheclark/stylelint-selector-bem-pattern) I think it would be possible to continue using the current `--` modifiers.

**Comment by Garbee** [comment]
V2 has the linting in place already. Since that is where it is needed this issue is resolved.
