### ISSUE TITLE
Let's get rid off all of these "mdl-js-" classes

### ISSUE THREAD

**Issue by MikeMitterer** [google/material-design-lite#246]
I think there is no reason for having them.
Why not registering, for example, mdl-button as component class instead of mdl-js-button?

```
html
<!-- current status -->
<button class="mdl-button mdl-js-button">Flat</button>

<!-- better -->
<button class="mdl-button">Flat</button>

<!-- cool! OK - let me dream.. -->
<mdl-button class="mdl-button--fab">Flat</mdl-button>
```

mdl-button would be enough. If a user wants no JS, which would be a bit strange but anyway, he needs not the register the button - thats it. Code changes would be easy:

``` js
componentHandler.register({
  constructor: MaterialButton,
  classAsString: 'MaterialButton',
  cssClass: 'mdl-button'
});
```

**Comment by AhmetFUsta** [comment]
d
