### ISSUE TITLE
How can I take a component out of this library in a stupid way like picking out an icon?

### ISSUE THREAD

**Issue by redstrike** [google/material-design-lite#2549]
Life will be easier if my project uses a lot of material design components => In that case, I just have to download material.min.css (120 KB / I don't care about gzip size) + material.min.js (60 KB) and throw them in my HTML's head.

But I don't want to use all of them, so is there any noob way to hand pick a component, and we have all of its "optimum / optimized / no code bloat" dependencies that combined in 2 minified files (js & css) without messing around with build tools? Similar to take an icon out of an icon collection.

**Comment by inexist3nce** [comment]
Its probably faster to use the entire library through Google's cdn instead of loading an optimized version from somewhere else.

**Comment by hebbet** [comment]
for general usage question please use stackoverflow. Tag ´´mdl

**Comment by Garbee** [comment]
> Its probably faster to use the entire library through Google's cdn instead of loading an optimized version from somewhere else.

Let's not get into this. But in short, test and measure results. Don't assume. CDNs are not always faster.

------

You can pull things out manually, but we can't do support for that in the issue tracker. It isn't a core issue with the code provided. As @hebbet said, use StackOverflow for this kind of help. In the future we could provide some docs helping with this. In the end there are too many different workflows and configurations to try and help with.
