### ISSUE TITLE
[Component Request] Material Icon Containers

### ISSUE THREAD

**Issue by junland** [google/material-design-lite#2553]
# Description
A container that can hold 'App Icons' similarly to the App Launcher or Applications folder in Android.

![Launcher](http://4.bp.blogspot.com/-EdQGvw2nT1Y/Uii8bi1XPlI/AAAAAAABMGg/xPa09C_UdhI/s640/google-app-launcher-welcome-2.png)

![Folder](https://lh4.ggpht.com/JUOZWme27vNa_ftZbQvoXytuM8mJCl96xSjsTMWvNv3OQES8nreqjIP0n9xEjOWD2KY=h900-rw)

# Use Case(s)
* Suite Web Apps - Landing web app to launch various other web apps.
* Dashboards
* Single Sign-On Applications
* Web Desktops - Like [OS.js] (https://github.com/andersevenrud/OS.js-v2)

Just thought I'd ask. Since from what I have seen there hasn't been a request for this yet.

**Comment by Garbee** [comment]
This type of component has way too niche if a use case. Also as far as I can tell, it is not specified by material design.

Not worth us building and including for everyone given these circumstances.
