### ISSUE TITLE
Tooltip on <button> not displayed on Canary (Version 49.0.2609.0 canary (64-bit))

### ISSUE THREAD

**Issue by raphaelsavina** [google/material-design-lite#2554]
MDL version: 1.0.6
Browser: Canary  49.0.2609.0 canary (64-bit)
Operating system: OS X

When a ```mdl-tooltip``` is assigned to a ```<button>``` it will not appears even if:
-the class ```is-active``` is added on ```hover``` 
-the animation is happening 
-and the position relative to ```<button>``` is correct.

All is working fine in Chrome (checked on Version 48.0.2564.48 beta (64-bit)) and Firefox 43.0.1.

Raphael

**Comment by Garbee** [comment]
Upstream bug, fixed in Version 49.0.2610.0 from Build Revision: 367261.
