### ISSUE TITLE
When will the next npm release happen?

### ISSUE THREAD

**Issue by amay** [google/material-design-lite#2562]
I need the changes in https://github.com/google/material-design-lite/pull/1525 but it looks like the current npm version (1.0.6) does not have these changes. Is there a plan to do a patch release anytime soon to expose those changes?

**Comment by surma** [comment]
So, our 1.1 milestone is due 22 days :smile: 

We are working to get 1.1 out asap – people are just starting to get back from the holidays, so give us a few days.

**Comment by samccone** [comment]
@amay you can install via a git sha with npm if need be

`npm i google/material-design-lite#SHA`

:+1: closing since this is a non-issue , thanks for asking though @amay
