### ISSUE TITLE
Ripple stops working when users clicks a button on the edge of the screen

### ISSUE THREAD

**Issue by Luigi123** [google/material-design-lite#2581]
When the users clicks a button on the edge of the page like in the image below (client x = 0, the problem only happens on the white button on the image), the ripple effect stops working.

The error happens in line 105 of ripple.js, where it tries to set a variable "clientX" as "event.touches[0].clientX", but "event.touches" is undefined (it's a mouse click at x = 0!).

Tested on Google Chrome.

![problem](https://cloud.githubusercontent.com/assets/6368056/12105086/826624b6-b338-11e5-836f-e592d7fe4f42.png)

**Comment by Garbee** [comment]
Discuss in PR.
