### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#266]
In some places of the Scss we have [no alignment](https://github.com/google/material-design-lite/blob/master/src/_mixins.scss#L27-30) for colons, while in other places [there is alignment](https://github.com/google/material-design-lite/blob/master/src/card/_card.scss#L20-27).

Is there any set style for the projects code?

Further, we should setup tooling to check the code style through a gulp task. Maybe even using something like [gulp-csslint](https://www.npmjs.com/package/gulp-csslint) to verify the output CSS adhears to some set rules.

**Comment by yuyokk** [comment]
As a suggestion for CSS code style to follow some [css guides](http://codeguide.co/#css-declaration-order) especially 'Declaration order' by Mark Otto. The CSS becomes more readable :)

**Comment by innerpeace0** [comment]
Great reference @yuyokk. Thanks.

**Comment by sgomes** [comment]
Superseded by the linting setup in #4464.
