### ISSUE TITLE
Designs left behind

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#267]
In the move from WSK we are losing some styles. This is perfectly fine to keep the provided core as minimal as we can. However, for anyone currently using WSK's styleguide, upgrading will be more difficult. Here is a quick list of things being left behind. A few things should be pulled into the current code as new components. Tables in particular, even if not responsive we can add that later and provide some decent enough styling to get updated without a problem. Then other things we should assess maybe building official components for each of those for developers to pull in if they are using the features.

None of this should block release (other than Tables).

* ~~Tables~~
    * We currently reset tables and have one styling for them in typography. This should be moved into a table component ( Issue #234 ) and the current styleguide look added to it.
    * EDIT: Removing outright due to no spec guidance for generic tables. See first comment below.
* Highlights
    * Own component? Need input.
* Editorial Header
    * Own component.
* Article Sections
    * Own component.
* Guides section
    * Own component.
* Page header
    * Looks like it can be dropped outright. Seems easy enough to replicate if you are using this.
* Quote
    * Drop? Has some styling issues already. Might just end up being a pain to maintain.
* Featured spotlight
    * Own component if not dropped. Seems useful enough to keep as a side component to me.
* Featured List
    * Should be replaced by cards eventually. Seems to have the same view structure as a horizontal card.
* Featured block
    * Can't tell myself if this should be its own component or dropped. Not sure how useful it is overall.
* Article navigation
    * Brought in but as a "simple" form of pagination.

**Comment by sgomes** [comment]
We shouldn't use WSK as a reference any more at this point, so let's track our progress against the MD spec instead.
