### ISSUE TITLE
Firefox: slider requires very precise clicks

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/material-design-lite#281]
Re http://localhost:3000/components/slider/demo.html on Firefox, clicking on a point on the slider line to move the circle seems to require much more accurate clicks on Firefox than on Chrome. On Firefox, it seems you need to click within about 2px of the line (and sometimes even clicking directly on the line doesn't seem to work); Chrome is much more permissive.

**Comment by dsomel21** [comment]
Yeah man, on firefox the thing looked really thin :(

Unless you go in and modify 

```
.mdl-slider__background-flex {
    position: absolute;
    /*Change 2px to 8px or something */
    height: 2px;
  /* more css below */
}

```
