### ISSUE TITLE
Proper usage of anchors in menus?

### ISSUE THREAD

**Issue by dylanjmcdonald** [google/material-design-lite#3072]
I'm wondering how to properly implement anchors within a menu. Is it possible to use the unordered list markup? Here's what I have for the time being:
```html
<div class="mdl-menu mdl-menu--bottom-right mdl-js-menu" for="menu-btn">
    <a class="mdl-menu__item" href="/settings/">Settings</a>
    <a class="mdl-menu__item" href="/logout/">Logout</a>
</div>
```

**Comment by Garbee** [comment]
Follow the structure provided in the [documentation](http://www.getmdl.io/components/index.html#menus-section). Diverting from that may lead to style issues that weren't accounted for in producing the V1.0 components.

I'm not seeing anything actionable within core here. This looks more to be a support question which belongs on StackOverflow. Therefore I'm closing this out. If there is some specific problem with the code we provide, then please try to make it more clear and we can re-open this.

Thanks!
