### ISSUE TITLE
Snackbars/Toast

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#324]
Looks like [Snackbars](http://www.google.com/design/spec/components/snackbars-toasts.html#) have been updated lately to include desktop/tablet specifications. Now that we have this to work with let's try to get something rolled in for this before launch. Notifications/Alerts are a huge part of what developers need.

I'll try and take a stab at it myself here in a bit, doesn't look like it should take too long.

**Comment by Garbee** [comment]
Re-opening for purely tracking the addition since the PR is about to change.

**Comment by flawyte** [comment]
Up?

**Comment by jfily** [comment]
I've done a snackbar following exactly Material design spec with pure css (using flexboxes and translation for animations):

Desktop
![capture](https://cloud.githubusercontent.com/assets/10220170/10247487/c3b7c8f2-6919-11e5-8baa-3ce0c8e632cc.PNG)

Mobile / Tablet
![capture2](https://cloud.githubusercontent.com/assets/10220170/10247492/ce0e00d2-6919-11e5-81bd-957f0fd1ad9c.PNG)

I don't know if it's possible to help...

**Comment by Garbee** [comment]
Added in PR #1519
