### ISSUE TITLE
www.getmdl.io isn't on TLS by default

### ISSUE THREAD

**Issue by sethladd** [google/material-design-lite#3273]
Just a friendly tracking issue. :)

**Comment by bbashy** [comment]
What is the .org domain? https://www.getmdl.io

**Comment by Garbee** [comment]
@bbashy Where are you getting an org TLD from?

Looks like all we need to do to finish this up is forward from HTTP to HTTPS.

**Comment by bbashy** [comment]
@Garbee I was asking the same thing. Both work, just redirect to do. Agreed :)

**Comment by sgomes** [comment]
Having a redirect is on the TODO list, yup! In the meantime, please redirect manually :)

**Comment by sgomes** [comment]
Updated bug title to reflect current state.

**Comment by crhym3** [comment]
This has been fixed by https://github.com/google/weasel/commit/60a25e5b1572f4c8651e9c096285da840ef19d7e for both http://getmdl.io and http://code.getmdl.io/...

Sorry for keeping this open for so long.

**Comment by Garbee** [comment]
Thank you @crhym3!
