### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#328]
Most of the components seem to have a "dark theme" option. We should add a dark theme option to MDL, either at the theme customiser level or via CSS classes (e.g. `mdl-button--dark`).

Not a high priority, can be done after v1.

**Comment by mariusbutuc** [comment]
Any progress towards supporting the [dark theme](https://www.google.com/design/spec/style/color.html#color-themes)? The [customizer](http://www.getmdl.io/customize/) doesn't help much, not yet.

Or are there any guidelines / best practices / 3rd party options worth recommending?

**Comment by mariusbutuc** [comment]
For any other beginners in the house, the [wiki on customizing colours](https://github.com/google/material-design-lite/wiki/Customizing-Colors) might lead the way.

**Comment by Garbee** [comment]
Nothing towards official dark themes yet. The issue, as any other, will be updated as we figure things out. However, this most likely won't even be a consideration before 3.X. It requires quite a bit of consideration to build properly and it isn't looking like we will have the ability before then to handle it.

**Comment by sgomes** [comment]
Let's reconsider this for V2 as a P2. I'll keep it assigned to myself.

**Comment by mariusbutuc** [comment]
@sgomes that sounds solid!
