### ISSUE TITLE
Page doesn't scroll if cursor is in tall waterfall multi-row header

### ISSUE THREAD

**Issue by sethladd** [google/material-design-lite#35]
1. Build a tall, waterfall, multi-row header.
2. add a body so large that one could scroll the page.
3. Place cursor in header.
4. Scroll with two fingers up on your track pad (or your mouse wheel)

Expected: page scrolls

Actual: page does not scroll

(if you put your cursor into main content, below the header, and try to scroll, it works)

**Comment by walter-schwarz** [comment]
In our tests we have found that users often do try to scroll down by sliding the header up, especially on mobile in landscape where the header might take up a sizable portion of the screen.

I fixed this via a scroll event on the header where I scroll the content down. 

I feel this should be default behavior as the header should never scroll vertically (its overflow-y should be hidden) so it can pass its scroll event to the content.
