### ISSUE TITLE
In-browser "back" button scrolls the content back to top in Google Chrome

### ISSUE THREAD

**Issue by listedegarde** [google/material-design-lite#3521]
**Problem:**
When hitting the back button in Chrome to return to a page using MDL, the page "scrolls" back to the top.

**Expected result:**
After hitting the back button, the content should still be scrolled to the same location on the page.  Example: if you visit a Google Search result and click back, you will scrolled to where you were before clicking the result.

**Steps to reproduce:** (Using Google Chrome):

1. Visit this page: http://www.getmdl.io/templates/blog/index.html
2. Scroll to the bottom and click the "More" link.
3. Click back in the browser.  You will be scrolled back to the top of the page.

**Tested in:**
- Google Chrome 47 on Ubuntu (reproducible)
- Firefox 43 on Ubuntu (not reproducible)

**Comment by surma** [comment]
Duplicate and will be addressed with #1735. Sadly, we will only be able to fix this for v2 :(

**Comment by listedegarde** [comment]
OK.  In case someone finds this post by searching, here's the roadmap: https://github.com/google/material-design-lite/milestones - v2 due at the end of March 2016.

**Comment by surma** [comment]
Please keep in mind that these are rough goals, not hard deadlines or promises – as you can tell by 1.1 :wink: We are a small team and our time available to spend on MDL varies. Any help is greatly appreciated. Talk to us via GH issues or our Gitter channel if you’d like to get involved in keeping your release dates :innocent:

**Comment by Garbee** [comment]
Yea, milestones are our "We really try to hit X" so there is a date for us to work towards. Things may fall behind depending on state, stuff happens. Especially around holiday's and the idiot (your's truly) submitting a bunch of last-minute edits that need review. (Clearly we know who the procrastinator on the team is now.)

I personally have been working on mockups for 2.x for a few weeks now. This way, we already have *something* tangible towards the next milestone in terms of component architecture to see how it works. This way, actual dev time towards it isn't lost if the ideas don't pan out. And if they do, then we already have a good enough foundation for moving forward.

**Comment by mariusbutuc** [comment]
@surma Gitter rookie here: how does one find the channel you've mentioned?

**Comment by surma** [comment]
@mariusbutuc The nice thing about Gitter is, that channels are tied to repositories. So our channel is at https://gitter.im/google/material-design-lite. See you there

**Comment by surma** [comment]
@Garbee Don’t sell yourself short. At least your were doing *something* over the holidays :dancer:

**Comment by listedegarde** [comment]
Sorry folks - that comment wasn't meant to be a complaint.  It was so that folks finding this by searching don't expect it tomorrow, and don't have to do the research to see that it *is* coming sometime (ex.: v2 is already in the works).  :smiley:

If I get some spare time, I'll *try* to contribute more than just bug reports.  :smile:

**Comment by Garbee** [comment]
*V2* is being **experimented** with. I'm just mocking things up based on existing conversation of what we should do along with some personal touches trying to improve a11y. Once 1.1 is out and it is really reviewed by the rest of the team deeper, we could decide to trash the work if it isn't panning out and go in another direction.
