### ISSUE TITLE
Move to CSSNano for minification

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#3526]
Move to using [CSSNano](http://cssnano.co/) to minify the CSS. It removes duplicate rules and can merge long-hand rules into short-hand for us. Along with a few other cool things if we want it.

**Comment by surma** [comment]
Definitely worth checking out, but we need to be evaluate carefully (maybe we should spin up our visual tests for this). Features like “Rebasing z-index values” are not to be taken lightly in connection to our microsite e.g.

**Comment by Garbee** [comment]
We can turn off the rebasing z-index. Already planning on that one due to dialogs and snackbars. I'm more worried about removing duplicate rules, super-minimizing of whitespace, combining selectors for things with exactly duplicate rules (just in case.) etc.

I'll go over the list again later and list out what I consider "safe", "possibly unsafe", and "hazardous" optimizations for us. We can turn off hazardous things, use the safe ones, and then analyze the middle ground for if they should get used or not.

**Comment by Garbee** [comment]
Oh cool, there is a [safe config option](http://cssnano.co/options/) to handle that already. But we can ofc get more granular if something becomes a problem beyond that.

**Comment by Garbee** [comment]
Webpack handles minification pretty well it seems like.

**Comment by traviskaufman** [comment]
Webpack's actually uses CSSNano [under the hood](http://cssnano.co/usage/#webpack) when optimizations are turned on 😄 .
