### ISSUE TITLE
Provide break points information in documentation

### ISSUE THREAD

**Issue by CodinCat** [google/material-design-lite#3553]
The current document is unclear, like:
**mdl-layout--large-screen-only**:	Hides an element on smaller screens
or
**mdl-cell--hide-tablet**:	Hides the cell when in tablet mode

What's the break points of *smaller screens* or *tablet mode*?
I have to read the source code to find out.

That will be great if the documentation can provide these information

**Comment by surma** [comment]
Yes, our documentation definitely could be improved here.

For now, let me [link you to the corresponding section](https://github.com/google/material-design-lite/blob/28e6c810a903cb0accb8f0c3e8690700762f1d48/src/_variables.scss#L518-L524( in the code :)
