### ISSUE TITLE
Overlap fixed header

### ISSUE THREAD

**Issue by johngonzalez** [google/material-design-lite#3554]
Hi. Thanks for the excellent package. I want overlay a div over fixed header. What would be the css code?.

**Comment by Ratts704** [comment]
I have root galaxy s3 i9300

**Comment by Ratts704** [comment]
Android 5.1.1 lollipop

**Comment by Garbee** [comment]
Please use stackoverflow for support and integration assistance. This issue tracker is only for problems with the code provided.
