### ISSUE TITLE
Remove or make "will-change" as opt-in for .mdl-button css property due to extreme GPU memory usage

### ISSUE THREAD

**Issue by fabiozaffani** [google/material-design-lite#3590]
Hi,

I searched around the issues looking if this was reported before but coudn't find anything, so, I'm sorry if this is a duplicate. Now, about the issue:

I just finished a "extreme GPU memory usage bug hunt" on my **react integrated with Google MDL app** (self-coded) and I finally identified the problem (poor React Shadow DOM, cursed so many times and wasn't even the guilty one) and the root of all evil's was the "will-change" attribute that get set on .mdl-button css class. 

Since I don't know if the issue was reported before I will be just leaving this note here, otherwise, if needed, I can post the before/after changing this attribute to show how big the difference was (memory usage on site dropped from around 250mb to only 8mb), also this is easily identifiable on machines with low GPU memory, elements on the page start to disappear, blink and do all sort of strange behavior once a certain memory threshold is reached or when many element's get added to the page, since the attribute was set in the **"button" component** (which I guess would be one of the most heavily used components in Google MDL) it might happen quite easily and so, would be worth to take a good look at it.

**Comment by samccone** [comment]
oh boy :/ good spot @fabiozaffani we will need to do some research around this

**Comment by Garbee** [comment]
Yea, we need to remove the will-change and even imo the transition of the shadow. The transition can be janky and isn't really providing much benefit to the UX since it is so small.

I recognized this and coded the 2.x mockup already without these issues. I'll hop in and backport the fix real quick so we can try to land for 1.1.

**Comment by sgomes** [comment]
@fabiozaffani First of all, thanks for the report!

Trying with a test page of about 100 buttons (a modification of [this one](http://codepen.io/Garbee/pen/Nxvdra) that @Garbee put together), all I see is an increase from around 8 MB to around 13MB, which would very much be in line with having 100 new layers to work with. This is perfectly acceptable, especially considering any UI is unlikely to have 100 buttons (and probably needs redesigning if it does).

This is really far from the massive increase you've reported, so assuming you're using a low number of buttons, I'm guessing that what you're seeing is not so much an issue with MDL or the usage of `will-change` in buttons, but rather the way that interacts with what React is doing.

Is there any chance you could share a test case that illustrates the issue? I'll keep looking into it in the meantime, but after running my tests, the buttons seem to be behaving perfectly normally on vanilla pages: `will-change` is not increasing memory usage in an unreasonable way, and it's actually massively improving animation smoothness, particularly on mobile.

**Comment by fabiozaffani** [comment]
Hi @sgomes

I looked at the sugestions and fixes in the issue #3592 and the removal of the transform made a huge difference, bellow are the GPU usage on my machine with the **will-change** first in it's default value and after set as 'initial'," (or box-shadow, both yield the same result). This prints were taken with 23 products in the DOM (my initial tests were 3 times that, that's the reason the numbers are a bit lower in this example, but the gpu consuption are basicaly a linear grow related to the amount of buttons or other components using will-change: 'transform')

![with-box-shadow-and-transform](https://cloud.githubusercontent.com/assets/1018480/12339917/ff7e8b78-bafe-11e5-9da6-4f93fca7fcb3.jpg)
![with-box-shadow](https://cloud.githubusercontent.com/assets/1018480/12339918/ff828cc8-bafe-11e5-81ca-b6eccf7df369.jpg)

I guess it might be something related to the integration between mdl and react, doing some more tests around the app I also notice that when rendering (or re-rendering) many components at the same time there are also a high increase on GPU usage (goes from 7MB to around 40mb and then drops, it's really fast but noticeable in weaker equipments with the "flickering"). The problem was that when both mdl and react were being used toghetter the spikes would reach past 300mb (with 80/90 itens on the screen).
