### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by JacobDorman** [google/material-design-lite#3599]
I haven't seen this kind of tagging done before. How can i compare commits between two released versions?

>Remember, the master branch is considered unstable. Do not use this in production. Use a tagged state of the repository, npm, or bower for stability!

but the version tags exist completely separately, without any history, and seem to be the compiled "dist" version of the codebase.

![pasted image at 2016_01_14 03_40 pm](https://cloud.githubusercontent.com/assets/1334947/12316063/9686bf5a-bad6-11e5-8228-d56f9cd436ea.png)

Which commit on the master branch, is this generated from? 
https://github.com/google/material-design-lite/commits/v1.0.4

**Comment by JacobDorman** [comment]
Do we just `git log | grep -i 'bump'` or is there a better way?

**Comment by Garbee** [comment]
We are working on a better way with 2.0. For now though, there is no real history comparison using the Git history.
