### ISSUE TITLE
documentation isn't clear on Loading components

### ISSUE THREAD

**Issue by kambanwait** [google/material-design-lite#3601]
Particularly with the progress bar. I can load the page and it'll appear but I can't dynamically update the progress bar with React. The doc's show how to load it in a page but nothing else after. 

I've spent most the day trying to figure it out as well as search for an answer online but no one seems to  have the same issue.

How do I increment the progress.

I'm making a survey and I want the progress bar to increment after an answer is answered.

I appreciate this may not be the best place to ask but it seems the only place to try and get some help specifically with this.

**Comment by Garbee** [comment]
You should use the [setprogress](https://github.com/google/material-design-lite/blob/master/src/progress/progress.js#L64) method. Like so

```document.querySelector('.mdl-js-progress').MaterialProgress.setprogress(45);```

That will update the progress placement.

Our current docs don't cover JS usage at all. New components have some form of it. Existing components however are going to be updated primarily with the 2.x update when we normalize the JS setup and configure things so we can auto-generate API docs.

**Comment by kambanwait** [comment]
Been trying that too and I get this: 

"Cannot read property 'setprogress' of undefined"

**Comment by Garbee** [comment]
Supporting React and integration with other systems is out of scope of what we can handle. Try asking for help on StackOverflow for that kind of assistance.

**Comment by kambanwait** [comment]
ah ok, thanks for looking in to it. I'll give it a shot on StackOverflow

**Comment by khooz** [comment]
I get the same Uncaught TypeError: "Cannot read property 'setprogress' of undefined" just after I embedded google's reCAPTCHA. Just inserted this script at the head:

`<script src='https://www.google.com/recaptcha/api.js'></script>`

**Update**
It works fine on fiddle. It seems I have some misconfigurations.
Here's the fiddle with google's reCAPTCHA:  https://jsfiddle.net/2hL7Lrg9/4/
