### ISSUE TITLE
jelly bean default browser support or polyfill in v2?

### ISSUE THREAD

**Issue by hir3npatel** [google/material-design-lite#3604]
A huge chunk of devices still run jelly bean (https://developer.android.com/about/dashboards/index.html). This is probably more so in my region (South Africa) where vendors are very slow to update :(

I understand that mdl supports only chrome which became the default in android at 4.4 (kitkat)? I have a site using mdl headers and nav and grid, the nav seems quite broken on 4.4's default browser.

Is there plans to support or polyfill devices with jelly bean default browsers on mdl v2? Considering the chunk of devices still on jelly bean, mdl may be off my list of tools to use for sites. I have used mdl on a site where at least 2 users have complained about it being broken on android 4.2's (jelly bean) default browser.

**Comment by surma** [comment]
Layout is really complex (and in it’s v1 incarnation has a lot of JS magic). All the basic elements *should* work fine in the old stock browser.

Seeing as we are actually dropping support for browsers in the transition to v2, I don’t think we will spend extra time on making MDL work 100% on such an old browser. However, we have plans to reduce the amount of JS magic in v2 in general and to completely overhaul the layout component, so there’s a good chance that the new layout will “just work”. No promises or previews just yet. If you wanna stay up to date and help us do the right thing, subscribe to #1735 :)
