### ISSUE TITLE
Misaligned buttons on Android skin

### ISSUE THREAD

**Issue by paullewis** [google/material-design-lite#3613]
<img width="781" alt="screen shot 2016-01-19 at 10 42 15 am" src="https://cloud.githubusercontent.com/assets/617438/12416427/63d3d766-be99-11e5-816f-90e7a58c0d9e.png">

Those arrowses aren't aligned. Not sure if MDL bug or skin bug.

**Comment by jfily** [comment]
Material specs don't define a button with text and icon

**Comment by paullewis** [comment]
The closest it gets is for -- say -- a dropdown, where the icon aside the text aligns properly.

<img width="584" alt="screen shot 2016-01-19 at 11 00 52 am" src="https://cloud.githubusercontent.com/assets/617438/12416874/fab726ae-be9b-11e5-89d0-9cd0a0649840.png">

**Comment by jfily** [comment]
I don't have this problem... Firefox 45.0a2 and latest Chrome Canary

http://codepen.io/jfily/pen/QjROwd

**Comment by Garbee** [comment]
Those aren't menu indicators. Just icons to enhance the view. I believe it is from custom CSS for that template.

Template work can be handled after the 1.1 release, just like any doc updates that may happen. Right now we are focusing on fixing up the core code for the next patch and getting it out.

**Comment by surma** [comment]
Looping in @sgomes as he did the template. Must be a regression, I am pretty sure the template used to look fine. Looks the same in FF btw. Thanks @paullewis

**Comment by sgomes** [comment]
Yup, looks like something changed and those icons got misaligned. Investigating.
