### ISSUE TITLE
Layout problem with dynamic DOM

### ISSUE THREAD

**Issue by RanzQ** [google/material-design-lite#3614]
I'm using [Riot.js](http://riotjs.com/) and I have a root element into which I render a different layout for login page and for the actual app. If I skip the login and call `componentHandler.upgradeAllRegistered()` or `componentHandler.upgradeDom()` after the app is added to dom, everything works as expected. It looks like this:
![image](https://cloud.githubusercontent.com/assets/1150613/12417617/fc105e42-beb1-11e5-9acb-862c6ef81454.png)

However, if I first render the login screen, which looks like this:
![image](https://cloud.githubusercontent.com/assets/1150613/12417642/2ddc0dcc-beb2-11e5-9c27-a59498fe1b66.png)

The layout in the app doesn't work anymore:
![image](https://cloud.githubusercontent.com/assets/1150613/12417671/51dbf4d0-beb2-11e5-8f20-78a43b8c6b39.png)

I've inspected the dom using `diff` and it's identical in both cases. I guess the the issue is within the `MaterialLayout` which doesn't work correctly if I use it multiple times. For me it looks like the layout is adjusted for the login box. The layout is based on the dashboard example.

Any suggestions how to reset the layout? If not possible, I can do a full refresh after login.

**Comment by surma** [comment]
MDL is focused at static content sites. For now, dynamic web pages are a 2nd class citizen. However, I know a lot of people made MDL work with things like Angular and similar dynamic frameworks. For support in this regard, please head over to StackOverflow and use the `material-design-lite` tag, as die GitHub issue tracker is only for issues, bugs and feature requests :)

**Comment by ApoorvSaxena** [comment]
I came across the same situation while using Riot.js, and the solution is to reinitialise the `MaterialLayout` component of MDL. It's done as follows:

```
<-- HTML -->
<div id="app" class="mdl-layout mdl-js-layout">
</div>

var element = document.querySelector('#app:not(.is-upgraded)')
element.MaterialLayout.init();
```

Note: reinitialising `MaterialLayout` on an already upgraded element is an issue, thus have added the check to see if the element has already been upgraded or not.
