### ISSUE TITLE
mdl-tabs (with Ripples?) going crazy and taking >100% cpu on Minisite/components/Button on FF (and Chrome)

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#364]
How to replicate:

 1 - Use Firefox
 2 - Open the minisite and go to Components > Button
 3 - Click on one of the tabs items (like "Fab w/ Ripples")

That's it. You can see the Firefox process on `top -o cpu` go crazy:

![screen shot 2015-06-08 at 4 32 06 pm](https://cloud.githubusercontent.com/assets/3766663/8037217/db0a9ac0-0dfc-11e5-831c-b7d545c7f700.png)

More or less the same happens on Chrome 43. Clicked once on the tab and then the tab takes 87% CPU constantly. If you click on a few tabs very fast you'll notice them going crazy and jumping around.

Weirdly this issue does not happen on Chromium 36.

**Comment by Soubkia** [comment]
I am having a similar issue. What did you do to fix it? Just update to the most recent version of mdl?

**Comment by nicolasgarnier** [comment]
@soubkia: Well this was a while ago on a pre-launch version of mdl. It disappeared after some updates on the page. This was pre-launch and lots was changing fast so I let this go but there might still be a bug somewhere. If you have a way to replicate this issue consistently please share as this could help us track down what's wrong.
