### ISSUE TITLE
Enhance progress bar animation

### ISSUE THREAD

**Issue by surma** [google/material-design-lite#399]
I take back everything I said about SVG animations being less powerful than CSS.

The animation of the buffering bar is currently simplified when compared to the spec, because I thought I wouldn’t be easily possible to implement the original animation with pure SVG. I was wrong.

It should be doable with something like this: `<animate dur="2s" values="#4e86b1; #000000; #4e86b1" keyTimes="0; 0.5; 1" attributeName="fill" repeatCount="indefinite"/>`

**Comment by sindresorhus** [comment]
Fyi: https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/5o0yiO440LM

**Comment by surma** [comment]
I believe I tried making this happen with CSS animations but to no avail. I’ll give it another try soon.

**Comment by sgomes** [comment]
Progress bar will be rewritten as part of #4489.
