### ISSUE TITLE
Change Footer color

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#4006]
We should change the primary color of the footer. Snackbars are required to be attached to the bottom of the screen. They have a dark grey background as well. Which means, it is **very** easy to miss snackbars and toasts.

Not sure what we should do instead since Footer isn't specified. Anyone have any input here? I'm thinking we should just go with a white background footer.

**Comment by RenDvila** [comment]
How about the footer color is based on the overall branding tonality of MD? Some fresh pastel tones are easy to identify on the CSS and pleasant to look at. You could take a look at this: #00FFCC or #33FFBB. 

Cheers!

**Comment by Garbee** [comment]
Yea, we should do some shade of the primary color I think. Accent colors shouldn't be used with such a large area. Should certainly not be the direct primary color, two or three shades in either direction would give it some decent contrast.

**Comment by RenDvila** [comment]
Agree, probably we can also apply some hue opposites based on the color wheel. || Cold tones gets a better contrast when put side to side with warm tones. The trick is to play with the opposite ends of the wheel for better composition, at times colors in between the ends tends to look nice as well. || 

I could help creating a color palette if you like? The palette could be utilized for multiple purposes, from headers, gradients, overlays, wrappers or footers. :)

![Uploading Color_wheel.png…]()

And here an example of how I'm using tones in between the two ends of the color wheel in my MDL site in progress:

![screen shot 2016-01-21 at 9 03 38 pm](https://cloud.githubusercontent.com/assets/12796514/12481241/bd386f84-c082-11e5-8f79-72dd99825ef0.png)

**Comment by Garbee** [comment]
We don't need help creating new pallet options. MD specs it out enough. We simply need to find a good shade to use from the provided pallets.

**Comment by RenDvila** [comment]
Maybe I rephrase my comment in fewer words, what I meant was a curation of the tonalities from the MD palette placed in a scheme of different shades for multi purpose utilization. We can start with this general selection to further curate two colors from each palette:

![pink](https://cloud.githubusercontent.com/assets/12796514/12502424/7f98b950-c103-11e5-805c-146e531eff67.png)
![teal](https://cloud.githubusercontent.com/assets/12796514/12502425/7f9a3000-c103-11e5-86bd-3822ad4429e1.png)
![deep purple](https://cloud.githubusercontent.com/assets/12796514/12502428/861c7064-c103-11e5-9108-894006262695.png)
![grey](https://cloud.githubusercontent.com/assets/12796514/12502430/8aaa0c7c-c103-11e5-94cf-5bf4562bacce.png)

Cheers!

**Comment by RenDvila** [comment]
My personal suggestions would be:

// Footer Background:

- A400 | #1DE9B6 or
- A200 | #69F0AE

// Footer Text Normal:

- 50 | #FAFAFA

// Footer Text Hover:

- A200 | #FF4081

Snackbars and Toasts will do just well over the proposed Footer backgrounds, as the dark grey will surely out stand enough while remaining pleasant to look at.

**Comment by Garbee** [comment]
Taking a peek at our existing setup, all we need to do is use the [darker primary color](https://github.com/google/material-design-lite/blob/6d90fd4cde3750f285e35686bc9ccfd4257c2297/src/_variables.scss#L95) that is already defined. For the text color, we just use the standard contrast color.

The existing color is also right on the "two or three shades" I was considering to begin with. So, looks like a good snug fit without much extra reworking to get done.

As far as text hover color... I'm not following on that one. We don't style text on hover so what is that supposed to mean? I'd assume it should be *selection* but, not positive enough.

**Comment by RenDvila** [comment]
So it means that you know what to do then. 

The hover is mainly for the footer and header text links. Unless you really don't feel it's "design friendly" to have such function added, then I would recommend that you discard that option fully as you said.

**Comment by Garbee** [comment]
Footer is being removed in V2 as it isn't a specified component. Therefore, closing this issue out as it is no longer relevant to the project's goals.
