### ISSUE TITLE
mdl-radio-* breaks name="..." attribution used by jQuery.validate (among others)

### ISSUE THREAD

**Issue by brianthelion** [google/material-design-lite#4007]
I admit to being a poor reader of the docs, so feel free to tell me to RTFM here if this is intended behavior. See my [gist](https://gist.github.com/brianthelion/5e3a7491631b7e09795e).

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration help. We can only handle problems directly related to the code MDL provides.

When filing an issue in the future, please provide a minimal reproduction case and clearly explain what is expected and what you get instead.

**Comment by brianthelion** [comment]
[Link to SO question](http://stackoverflow.com/questions/34914138/mdl-jquery-validate-integration-work-around-needed-for-mdl-radio-button-vali)
