### ISSUE TITLE
Buttons have a 2px left/right margin computed in Safari

### ISSUE THREAD

**Issue by oddui** [google/material-design-lite#4008]
The buttons have a 2px left/right margin computed in desktop Safari 9.0.3, which Chrome and Firefox do not have.

**Comment by Garbee** [comment]
Thanks for tracking this one down.

Do you mind seeing if `box-sizing: border-box;` on `.mdl-button` fixes the issue? I have a feeling if we just hard-set dimensions then that will be the best fix.

**Comment by oddui** [comment]
Not too sure what you mean by 'hard-set dimensions' @Garbee . I tried adding `box-sizing: border-box` in safari devtools, unfortunately it did not work.

**Comment by oddui** [comment]
Seems buttons if safari have 2px margins by default. https://github.com/necolas/normalize.css/blob/master/normalize.css#L264
