### ISSUE TITLE
Use of "for" attribute on elements for tooltips

### ISSUE THREAD

**Issue by gpgekko** [google/material-design-lite#4009]
The way it is set up now is against the HTML specs.

This is pretty much the same as issues #1722 and #1556, just for a different component.

**Comment by Garbee** [comment]
We can take a look at this with V2. It isn't a major issue since browsers work right through it.

**Comment by surma** [comment]
To be clear, the reason @Garbee is pushing it straight to v2 is because we are not planning to have a v1.2 but go straight for v2. 

In any case, as @Garbee said, it is really a non-breaking issue so no reason to cram it into v1.1 last minute.
