### ISSUE TITLE
SUIT CSS naming conventions

### ISSUE THREAD

**Issue by JosefJezek** [google/material-design-lite#4021]
I would like to see SUIT CSS naming conventions in MDL v2... ;-)

SUIT CSS is better methodology then BEM.

https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md
https://suitcss.github.io

**Comment by surma** [comment]
“SUIT CSS is better methodology then BEM” – that’s an pretty absolute statement; and one at that I don’t necessarily agree with. Why do you think it’s superior?

**Comment by surma** [comment]
*Disclaimer:* I never heared about SUIT and just read the site you linked to.

“SUIT CSS is better methodology then BEM” – that’s an pretty absolute statement; and one at that I don’t necessarily agree with. Why do you think it’s superior?

To me it seems like there’s only minor syntactical differences. What I actually dislike though:

> ComponentName.is-stateOfComponent
Use `is-stateName` to reflect changes to a component's state. The state name must be camel case. *Never style these classes directly; they should always be used as an adjoining class.*

If all packages use SUIT, that’s fine, but if you mix in another library that isn’t using SUIT, these `is-stateName` classes can easily conflict as they are not being namespaced.

**Comment by JosefJezek** [comment]
1. SUIT CSS naming conventions is more readable then BEM
2. SUIT CSS have not `_`
3. SUIT CSS define utilities - https://github.com/suitcss/utils
  - Syntax: u-[sm-|md-|lg-]utilityName
  - Responsive utilities
4. SUIT CSS have Style Guide - https://github.com/suitcss/suit/blob/master/doc/STYLE.md
5. SUIT CSS define vars for Media Query breakpoints - https://github.com/suitcss/utils-size#configuration
6. SUIT CSS is based on PostCSS ;-)

[ComponentName.is-stateOfComponent](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md#componentnameis-stateofcomponent) - Never style these classes directly; they should always be used as an adjoining class. -> can not conflict with other namespace

**Comment by Garbee** [comment]
> SUIT CSS is based on PostCSS ;-)

BEM syntax works just fine in PostCSS as well. As well as covering point 5 too.

Unless we have effective validation of the style, having a style guide is useless since creeping errors will occur.

Utilities, are also 100% possible with BEM, this is not SUIT-specific in any way.

Not having underscores *and* more readable... pure personal preference here. Nothing we should be making actionable decisions on.

**Comment by surma** [comment]
Thanks for getting back to us, @JosefJezek :)

> SUIT CSS naming conventions is more readable then BEM

Again, something phrased as an absolute without any arguments. I don‘t see notable difference in terms of readability.

> SUIT CSS have not _

I fail to see why this is important. Underscores are pretty common in CSS class names, are they not?

> SUIT CSS is based on PostCSS ;-)

How can a naming-convention be based on something like PostCSS? And why would that be an argument considering we are not using PostCSS (yet)?

I see where you are coming from, @JosefJezek, but my initial counter-argument is still a deal breaker for me: If the SUIT CSS naming convention prescribes to have classes named like `is-stateName`, we run the risk of clashing with other libraries. Example: Our buttons would probably have a class `is-disabled` which other libraries might inadvertently modify.

**Comment by JosefJezek** [comment]
@Garbee @surma Sorry for six argument, I love PostCSS.

SUIT CSS is better for me ;-)
