### ISSUE TITLE
Scrollbar causes fixed header to shift horizontally on page load in Chrome

### ISSUE THREAD

**Issue by jkrgr** [google/material-design-lite#4023]
The bug is found on any page using a fixed header, for example: http://www.getmdl.io/templates/android-dot-com/index.html

When the page is loading, the scrollbar covers the header. Then when the content is loaded the scrollbar pops down below the header, causing the header content to shift to the right.

This happens on Chrome only, and on all platforms (Linux, Mac, Windows).

**Comment by Garbee** [comment]
This is a side-effect of how Layout is handled with lots of JS. The 2.x layout refactor should clear it up.

**Comment by jkrgr** [comment]
Great! Do you have an ETA on when we can start testing 2.x?

**Comment by Garbee** [comment]
No.
