### ISSUE TITLE
rendering mdl-menu in rails partial with ajax, mdl-menu not working

### ISSUE THREAD

**Issue by stinovh** [google/material-design-lite#4026]
Hi I am trying to render the mdl-menu in the partial but I can't get it to initiate.
I've already tried componentHandler.upgradeDom(); but that did not work either.
Is there a way to reinitiate this mdl-menu element again?

**Comment by Garbee** [comment]
We can't help with integrating MDL into different stacks. Please use StackOverflow for integration help and general support. The issue tracker is only for core problems with the code we provide.

**Comment by stinovh** [comment]
I've already fixed it by putting a delay on the componentHandler.upgradeDom();.
Thank you anyway :)

**Comment by wicky-info** [comment]
hi @stinovh  can you help me, show your example code line. thanks

**Comment by wicky-info** [comment]
@stinovh  thanks already add put <script>componentHandler.upgradeDom();</script> at the end, and  turbolink and mdl work together thanks
