### ISSUE TITLE
When I insert new text field by JS, It doesn't show effect on click

### ISSUE THREAD

**Issue by lamekbig** [google/material-design-lite#4029]
Hi, I have a problem.

I need add new text fields but when I add it, the effect is not showed.

![video_1453833618](https://cloud.githubusercontent.com/assets/8567903/12589110/77f216f4-c45c-11e5-9aba-852c32c2d1b2.gif)

**Comment by Garbee** [comment]
Make sure you upgrade the element as descried in our getting started guide. Beyond that, please use StackOverflow for integration help. This issue tracker is only for problems directly related to the code provided.
