### ISSUE TITLE
Why mdl-checkbox is done using svg instead of icons?

### ISSUE THREAD

**Issue by RanzQ** [google/material-design-lite#4036]
I wonder why the checkbox is not done using icons? I have some perfomance issues on a table with tens of rows when I use checkboxes on them and I guess icons would perform better.

**Comment by Garbee** [comment]
SVGs scale better than icons overall. Also they don't have any issues with font replacement like fonts do. For a11y, some tools replace *all* fonts on a page which causes issues with font icons.

**Comment by RanzQ** [comment]
Ok, I'll try to to make a custom checkbox with icons too see if that improves performance. But thats a valid point to use svg. :)
