### ISSUE TITLE
Bug text field from load javascript

### ISSUE THREAD

**Issue by katsenkatorz** [google/material-design-lite#4037]
Hello everyone, thanks for your work.

I detect a bug when I load the form from javascript.
Is it really a bug? Or should I do differently? Can you give me the solution.

Thank you in advance

See : http://codepen.io/katsenkatorz/pen/LGmxRy

**Comment by surma** [comment]
MDL is targeted at static websites. Dynamically created components need some extra work. Please see the [corresponding section](http://getmdl.io/started/index.html#dynamic) on our website. Hope this helps :)

Also, please use the search next time before opening an issue. This had been answered numerous times.
