### ISSUE TITLE
Dialog buttons do not work inside mdl layout

### ISSUE THREAD

**Issue by oddui** [google/material-design-lite#4038]
http://codepen.io/anon/pen/qbYjKP

The dialog polyfill does not seem to work very well with the layout. I cannot click on the dialog buttons in firefox and safari.

It works in chrome. It also works in firefox and safari if the dialog element is outside the layout.

**Comment by Garbee** [comment]
Follow the dialog polyfill instructions. The dialog elements should be direct body children. Not children of positioned elements, especially absolute and static.

I'll double check the docs in a bit too make sure this is clear.

**Comment by oddui** [comment]
Thanks @Garbee it'll be good to mention the limitations in the doc. Quite restrictive though.

**Comment by Garbee** [comment]
It would have been necessary either using the polyfill or us doing our own thing. CSS positioning is a pain in the rear. Especially with how layout currently works.

**Comment by Garbee** [comment]
Fixed with commit 86608b2c816b851e1dacb3591e10e93011bbe37f.
