### ISSUE TITLE
Scrollable menu

### ISSUE THREAD

**Issue by RanzQ** [google/material-design-lite#4039]
I guess this doesn't work with current implementation, so would be a feature request. I tried to create a scrollable page selection menu for pagination using `mdl-menu` with `max-height` and `overflow-y: auto`. I have hundreds of pages on my data-table and the menu goes blank when scrolling. The items appear again on hover. I guess this is due to animations:

![image](https://cloud.githubusercontent.com/assets/1150613/12636750/15f1861e-c598-11e5-9f71-b550e38ac294.png)

UPDATE: It works ok if I use scrollwheel, this happens only with scrollbar. When scrolled to bottom using wheel first, then the items stay visible. So I think a solution would be to animate only the items initially visible, then reveal the rest which don't fit in the menu.

UPDATE2: This doesn't happen on a menu with class `mdl-menu--top-right`. Only if menu opens down.

**Comment by Garbee** [comment]
This has come up before. Nothing can be done in 1.x about it. Should be fixed in 2.x updates.

**Comment by charanjit-singh** [comment]
I am facing the same problem. 
Can anybody help please.

**Comment by rajatblogger11** [comment]
@charanjit-singh It can be solved by using two CSS properties in ul tag.

`<div class="mdl-textfield mdl-js-textfield getmdl-select" style="margin-top: 0; width: 100%; padding: 0;">
        <input type="text" value="" class="mdl-textfield__input" id="sample11" readonly>
        <input type="hidden" value="" name="sample11">
        <label for="sample11" class="mdl-textfield__label" style="top: 50px; color: rgba(0,0,0,0.6); font-size: 0.8em; bottom: -18px;">Select Doctor</label>
        <ul for="sample11" class="mdl-menu mdl-menu--bottom-left mdl-js-menu" style="overflow-y: scroll; max-height: 150px;">
            <li class="mdl-menu__item" data-val="DEU">Doctor 1</li>
            <li class="mdl-menu__item" data-val="BLR">Doctor 2</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 3</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 4</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 5</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 6</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 7</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 8</li>
            <li class="mdl-menu__item" data-val="RUS">Doctor 9</li>
            <li class="mdl-menu__item" data-val="RUS">Last Doctor</li>
        </ul>
    </div>`

You can change the max-height of ul to change the no. of items shown in the drop-down.
