### ISSUE TITLE
Snackbar action only works the first time

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#4041]
@Garbee FYI

In the snackbar snippets demo, the "undo" action only seems to work the first time. Subsequent tries produce no effect.

After some debugging, it seems that the click event isn't being fired, and I'm currently investigating why.

**Comment by sgomes** [comment]
The sample seems to be disabling the undo action, for some reason. Removing that.

**Comment by Garbee** [comment]
Yea, it disabled after click but while the notification was still shown. Maybe I didn't re-enable it. Idea was to prevent multiple action triggers. Probably not something we should handle internally though.
