### ISSUE TITLE
Unbalanced tags in documentation sample (dialog)

### ISSUE THREAD

**Issue by kengruven** [google/material-design-lite#4044]
In this file: https://github.com/google/material-design-lite/blob/master/src/dialog/README.md

it has this sample line:

    <p class="mdl-dialog__title">Allow data collection?</h4>

The "codepen" it links to uses `<h3>` (for both the start and the end).

I'm not sure what element is recommended for `mdl-dialog__title` -- and it looks like you guys aren't, either.  :-)

**Comment by Garbee** [comment]
Fixed, thanks.

Examples in the docs are also not directly what is given to codepen. So that isn't an issue.
