### ISSUE TITLE
Snackbar isn't centered properly

### ISSUE THREAD

**Issue by ramijarrar** [google/material-design-lite#4046]
Trying out the latest version of mdl (https://github.com/google/material-design-lite/commit/b7fd844a27c52905b2bf477421556887ecef6e92) in anticipation of the upcoming release, and I have noticed that the snackbar isn't quite centered right on the page:

![image](https://cloud.githubusercontent.com/assets/9661116/12696188/c0417842-c7b7-11e5-9def-efdd5f5ef34c.png)

I have verified that the ```margin-left: -50%``` property which is supposed to make this work is being loaded correctly and I have tried running in Chrome, Firefox & IE so I don't think it's a result of cross-browser inconsistency.

**Comment by Garbee** [comment]
The current snackbar centering is a hack for IE support. And it also depends on the size of the content. In some cases it works, in others, as this one with short text it doesn't.

V2 can address this by going full-flexbox. For now though, this is close enough in the majority of cases.

**Comment by ramijarrar** [comment]
@Garbee I just tried this with progressively longer strings of text and it hasn't solved any of the centering issues.

**Comment by Garbee** [comment]
I had it working at some point. Maybe another change caused longer strings not to center.

Either way, it is a best-effort kind-of thing considering our browser support. The only true alternative is flexbox, which means the styles wouldn't work at all in IE9. So, it is stuck until 2.x. This was brought up in the review, it is a known mis-alignment on desktops due to the support required.

**Comment by ramijarrar** [comment]
Can you re-open this in the meantime?

**Comment by Garbee** [comment]
This isn't planned to be fixed unless a community member contributes a workable patch. It is a known mis-alignment from the spec for the 1.x series.

**Comment by mfonville** [comment]
Personally I am using `@media screen and (min-width:480px){.mdl-snackbar--active{transform:translateX(-50%)} }` to fix the off-center problems. It is a very ugly hack, but it gets the job done in at least Chrome and Firefox for relatively long messages in the Snackbar.

**Comment by Garbee** [comment]
The thing is, it is technically centered. It is just *starting* at the middle vs the middle of the snackbar being centered.

With flexbox this is trivial, without it and having dynamic content length... harder problem to get perfect by the spec.

I went with what at least functions for our browser support and is very close. 2.x can bring about complete alignment.

**Comment by tleunen** [comment]
This could be "patched" with JS until MDL uses flexbox in v2

**Comment by Garbee** [comment]
PR #4106 has been merged into master and will soon be cherry-picked into `mdl-1.1` for the next patch release to address this.

**Comment by fennifith** [comment]
Just wanted to share a small adaptation of the snippet posted by @mfonville that prevents the snackbar from animating horizontally back to the original position when it hides. Might be useful for anyone else that comes across this issue before it's fixed.

``` css
@media screen and (min-width: 480px) {
  .mdl-snackbar:not(.mdl-snackbar--active) {
    transform: translate(-50%, 80px);
  }

  .mdl-snackbar--active {
    transform: translate(-50%, 0);
  }
}
```
