### ISSUE TITLE
List needs sizing and color changes to match spec

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#4056]
The line height makes the text very squished for 3-line list items. The [spec](https://www.google.com/design/spec/components/lists.html#lists-specs) (ref: "Three line lists" section) shows there should be more spacing around the text giving a good level of whitespace.

Investigate whether something is off in typography or with the line-height itself here.

**Comment by sgomes** [comment]
Looking at this, a lot of the numbers in lists are wrong, not just the line height. I'm taking a pass through the whole thing.

**Comment by Garbee** [comment]
Really? Most of them seemed right on my pass through. The only problem was the font weight made me think that stuff was right when it wasn't.

Maybe something got mixed up in the update to drop the mixin that was being used. I didn't do a run-through after that since it looked the same.
