### ISSUE TITLE
Waterfall menu bottom row disappears when resizing

### ISSUE THREAD

**Issue by listedegarde** [google/material-design-lite#4058]
**Problem:**
When shrinking and then growing the window, the waterfall's bottom menu does not reappear if the user has scrolled between times.

**Expected result:**
When growing the window, the bottom row should always reappear once scrolled back to the top.

**Steps to reproduce:**

1. Visit http://getmdl.io/components/index.html#layout-section
2. Scroll down to "Waterfall header" sample
3. Shrink the window to < 1024px, but > 850px and scroll to the bottom of the Waterfall sample.
4. Grow the window to > 1024px again, and scroll to the top of the Waterfall sample: no bottom row with menu items will be visible.

_Note: the issue doesn't seem to act quite the same way if you shrink below 850px.  When you do, the bottom bar can usually be restored in > 1024px by scrolling down to the bottom and back to the top._

**Tested on:**
Firefox 44 on Ubuntu 14.04
Chrome 48 on Ubuntu 14.04

**Comment by listedegarde** [comment]
Another interesting point I just discovered: if you double-click on the header's main "title" bar (with the title and search), the bottom row will with the menu items will magically reappear!

**Comment by sgomes** [comment]
Nice catch, @listedegarde! I'll look into this.

**Comment by sgomes** [comment]
Found while debugging: clicking the header seems to reset the incorrect behaviour, for some reason.

**Comment by sgomes** [comment]
Found the issue. PR at #4064.

**Comment by listedegarde** [comment]
Awesome!  Thank you.

**Comment by sgomes** [comment]
No worries, thank you for the clear bug description, @listedegarde! This has been merged into the `mdl-1.1` branch and will be included in v1.1.1 when released.
