### ISSUE TITLE
In Page Contents that does not use the full screen footer is wrongly positioned

### ISSUE THREAD

**Issue by arijitlaik** [google/material-design-lite#4070]
MDL version: All

Page Contents that does not use the full screen footer is wrongly positioned i.e. moves up leaving trailing whitespace
 
example reporduced here https://codepen.io/arijitlaik/pen/vLzLza

sorry if its any code arrangement issue
![screenshot_2016-02-03_21-15-59](https://cloud.githubusercontent.com/assets/10157121/12787427/65a4be74-cabb-11e5-811a-6a76d55bef38.png)

**Comment by sgomes** [comment]
Thanks, @arijitlaik!

Unfortunately, the footer cannot place itself relative to the screen (that would be incorrect), and page content is completely controlled by the developer.

My suggestion would be to add a minimum height to your page content to solve the issue, e.g.:
```css
.page-content {
  min-height: calc(100% - 100px);
}
```

You may need to adjust the `100px` value, depending on your setup.

**Comment by arijitlaik** [comment]
Thank you for your prompt help, i apologize for such a trivial issue

**Comment by sgomes** [comment]
No worries at all, happy to help! :)

**Comment by arijitlaik** [comment]
Sorry bother you again
but it doesn't seem to  on the example code pen css
`.page-content {
  min-height: calc(100% - 100px);
}`

i am not very well versed with the css  is there something that i might be doing wrong

**Comment by sgomes** [comment]
Needed an extra tweak :)

Here's a working example: https://codepen.io/anon/pen/EPeybq

**Comment by arijitlaik** [comment]
thanks yet again :+1:  :smile:
