### ISSUE TITLE
getmdl.io example snippets use mdl 1.0.6

### ISSUE THREAD

**Issue by arijitlaik** [google/material-design-lite#4071]
the open in codepen for examples at getmdl.io still use version 1.0.6

**Comment by sgomes** [comment]
Thanks, @arijitlaik! I tried a few, but they all seem to be correctly pointing to 1.1.1. Could you give me an example of an "open in codepen" button that's pointing to the wrong version?

**Comment by arijitlaik** [comment]
new components open in the 1.1.0 version
but for example
http://www.getmdl.io/components/index.html#menus-section 
![screenshot_2016-02-03_21-41-43](https://cloud.githubusercontent.com/assets/10157121/12788308/0b6b753e-cabf-11e5-95f0-bf9e732f2850.png)
![screenshot_2016-02-03_21-15-59](https://cloud.githubusercontent.com/assets/10157121/12788309/0b77fd68-cabf-11e5-92d5-fb26aec10377.png)

**Comment by arijitlaik** [comment]
menus and other older than 1.1.1 components 
![screenshot_2016-02-03_21-42-05](https://cloud.githubusercontent.com/assets/10157121/12788413/5fc344ea-cabf-11e5-8545-cfae9c5d4e3d.png)
![screenshot_2016-02-03_21-41-43](https://cloud.githubusercontent.com/assets/10157121/12788414/5fd4cf9e-cabf-11e5-9d5f-82371983dcb2.png)

**Comment by arijitlaik** [comment]
sorry chrome cache problem
