### ISSUE TITLE
[v1.1.1] NPM version dist files changed?

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#4073]
Previously (before v1.1.1) the dist folder conveniently contained all palette theme css files such as `material.teal-lime.min.css`. And one of my projects could simply grab the files without running gulp. These files are gone in v1.1.1. May I ask the reason for this?

**Comment by Zodiase** [comment]
Also `gulp styles:gen` clearly relies on `./docs/_assets/customizer.js` so there's no way I can generate those files on my own from the npm package (which doesn't have `docs` folder).

**Comment by simono** [comment]
I'm also missing `dist/material.css.template` which was included up to 1.1.0 but is missing in 1.1.1

**Comment by olegt-indicee** [comment]
I have the same problem - `dist` folder is missing most css themes that were there in version 1.0.6. 

> ls -l node_modules/material-design-lite/dist
-rw-rw-r-- 1 user user 347302 Feb  3 15:46 material.css
-rw-rw-r-- 1 user user  34734 Feb  3 15:46 material-grid.css
-rw-rw-r-- 1 user user  18772 Feb  3 15:46 material-grid.min.css
-rw-rw-r-- 1 user user 143704 Feb  3 15:46 material.js
-rw-rw-r-- 1 user user 136656 Feb  3 15:46 material.min.css
-rw-rw-r-- 1 user user 918767 Feb  3 15:46 material.min.css.map
-rw-rw-r-- 1 user user  61655 Feb  3 15:46 material.min.js
-rw-rw-r-- 1 user user 353114 Feb  3 15:46 material.min.js.map

**Comment by tleunen** [comment]
Time to add a check in the build system before releasing a version, to make sure everything is there :)

**Comment by Garbee** [comment]
Sergio will have to look at this when he gets some time. He is the poor soul who does the release stuff. I have no clue how to debug this, much less push a new revision. (I have the instructions, just not a good idea to go doing it on my own.)

**Comment by sgomes** [comment]
Yup, my bad, looks like I botched a step in the release process. This will be fixed in 1.0.2, which will be released once we have a few more fixes in.

**Comment by surma** [comment]
1.1.2*

**Comment by sgomes** [comment]
Indeed, 1.1.2, thank you, @surma :)

**Comment by sgomes** [comment]
This has been fixed with the [release of 1.1.2](https://github.com/google/material-design-lite/releases/tag/v1.1.2).
