### ISSUE TITLE
I do not understand the purpose of add stylesheet with no valid link

### ISSUE THREAD

**Issue by onigetoc** [google/material-design-lite#4074]
I do not understand the purpose of add stylesheet with no valid link

`<link rel="stylesheet" href="$$hosted_libs_prefix$$/$$version$$/material.teal-red.min.css">`

**Comment by onigetoc** [comment]
the gulp and bower things are becoming very boring

**Comment by Garbee** [comment]
Where are you seeing that reference?

**Comment by Garbee** [comment]
Just confirmed our [getting started guide](http://getmdl.io/started/index.html) does show the proper links.

Doesn't seem to be an issue with anything. Closing until we know where this is being seen from.
