### ISSUE TITLE
Snackbar should close when actionHandler triggered

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#4075]
When I click on "Undo" in the exemple provided by getmdl.io, I think the snackbar should close.

I don't know why but it really bugs me.

**Comment by Garbee** [comment]
As far as I recall, it is not spec-compliant that it close upon an action trigger. Please point this out if it is there, otherwise not something to fix.

**Comment by jfily** [comment]
Can I take for exemple Android apps like :
- Google Messenger
- Inbox
- Google Keep

It's propably why I found mdl snackbar strange.

You're right though, it's not in specs.
