### ISSUE TITLE
Action in snackbar is not MD specs compliant

### ISSUE THREAD

**Issue by jfily** [google/material-design-lite#4076]
Action in snackbar should at be 24dp/px from the text (currently, 48px) and 24dp/px from the edge (currently, 24px + 8px)

![sans titre](https://cloud.githubusercontent.com/assets/10220170/12808433/338e05e2-cb17-11e5-9ec4-b8d0ae98c743.png)

![components_toasts_mobile4](https://cloud.githubusercontent.com/assets/10220170/12808429/28e1bd50-cb17-11e5-8971-9fb0cd978c7f.png)

**Comment by sgomes** [comment]
Merged in #4120.
