### ISSUE TITLE
Footer obscures page content 

### ISSUE THREAD

**Issue by dturner** [google/material-design-lite#4078]
If page content is greater than 100% of the browser height the footer should move down the page. It does not and so obscures the content. 

Screenshot here: https://github.com/googlesamples/android-audio-high-performance/issues/26

Also affected: http://google.github.io/android-testing-support-library/docs/espresso/web/index.html

**Comment by Garbee** [comment]
This is because the pages are not constructed properly. The footer should be within the `.mdl-layout__content block`, not separate from it.

Closing since this is not an MDL issue but a page construction one.
