### ISSUE TITLE
Do not declare font family other than in body

### ISSUE THREAD

**Issue by viankakrisna** [google/material-design-lite#4080]
It is cumbersome to override each element with font declaration. It would make this framework more easier to customize.

**Comment by Garbee** [comment]
We should actually look towards doing font-family on each component and **not** any global element targets. That will make integrating with existing frameworks and libraries easier. Making the system truly componentized by making  each one self-sufficient.

**Comment by viankakrisna** [comment]
Well, component based is more like javascript thing, using a shadow dom or webcomponents. For css itself i think it is more beneficial to have as little declarations as possible, and let the rules cascade.

**Comment by Garbee** [comment]
We already have complaints about our global touches. And, seeing as how we are **not** a framework, it makes sense to not do cascading but instead have single isolated components.

MDL is a library of components, not a framework like Bootstrap.

If you want to modify all the fonts, then you can pull in the raw sources and override the font stack variables.

**Comment by viankakrisna** [comment]
Ok then :)

**Comment by andrei-gheorghiu** [comment]
You can overwrite the fonts using 

    body:not(...) * {
      font-family: whatever
    }

Where `...` is a non-matching `<body>` selector of desired specificity. For example, `body:not(#_)` will override any classes combo selectors. `body:not(#_):not(#_)` will override any id + classes combo and so on.

The `*` selector added is to overcome child priority in applying `font-family` (explained [here](https://stackoverflow.com/a/50085946/1891677)).
