### ISSUE TITLE
[Menu] Incorrect full bleed divider

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#4083]
The new full bleed divider released in 1.1.0 for the Menu items is incorrect.

As you can see, when hovering the element, the background touches the "border".
<img width="217" alt="screen shot 2016-02-06 at 1 45 14 pm" src="https://cloud.githubusercontent.com/assets/1972567/12868616/ebcba4c2-ccd7-11e5-9ed1-0924df469617.png">

But in the MD documentation, it's not the case.
<img width="331" alt="screen shot 2016-02-06 at 1 47 32 pm" src="https://cloud.githubusercontent.com/assets/1972567/12868629/3c636f6e-ccd8-11e5-93d0-e2fcd384a8ea.png">

I think having this modifier was not a good idea. Instead, we should integrate a new "Divider item", with a smaller height than a regular item.

**Comment by Garbee** [comment]
Yea, the divider was a quick hack. In  testing v2 stuff a full divider element  is better. Nothing we can do about this until major though.
