### ISSUE TITLE
Reset form with radio buttons does not clear checked state

### ISSUE THREAD

**Issue by OliverJAsh** [google/material-design-lite#4085]
Given:

``` html
<form>
  <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect"><input type="radio" class="mdl-radio__button">foo</label>
  <button type="reset">Reset</button>
</form>
```

When I check a radio and then press the form reset button, Material Design Lite does not clear the `checked` state from the input when it should. You can verify the input is in fact unchecked by using the console to do `$0.checked === false`.

This is true even if I call `window.componentHandler.upgradeDom()` after clicking reset.

Example: http://output.jsbin.com/kesixu/1/quiet

**Comment by Garbee** [comment]
We need to handle the reset event...

**Comment by OliverJAsh** [comment]
If you could point me in the right direction for this, I'm happy to pick it
up and raise a pull request

**Comment by Garbee** [comment]
It is just dig into the `src/{checkbox,radio}/{component}.js`, create an `onReset_` method, do what is needed for the component to reset (setting value back to defaultValue etc.). Shouldn't be too complicated, but not sure on whether we are going to do another patch to 1.x though, need to discuss that with the others tomorrow.

**Comment by OliverJAsh** [comment]
That's awkward because the event occurs on the parent `form` element, not the input element itself. Does it make sense to add an event handler for the parent form in `src/radio/radio.js`?

**Comment by Garbee** [comment]
No, resetting forms triggers the reset event on internal inputs. Just bind to the element of the radio like every other handler. iirc the textfield component already has this, you can check that for reference.

**Comment by Garbee** [comment]
FYI [codepen example](http://codepen.io/Garbee/pen/PZyVWL) of reset triggering.

**Comment by OliverJAsh** [comment]
In my testing the event is not fired on the input element:
http://codepen.io/anon/pen/BjqMRg

**Comment by Garbee** [comment]
ah, the basic test is just doing what reset does by default.

Hmm... Nothing we can do here then. In your reset method, you'll need to loop over the elements and call `item.MaterialRadio.checkDisabled()` and `item.MaterialRadio.checkToggleState()` or whatever methods are needed for state (checkboxes are MaterialCheckbox over MaterialRadio, etc.). Also bearing in mind `item` is where `mdl-js-*` is defined, not the input element itself.

**Comment by OliverJAsh** [comment]
It's a shame we can't handle this internally.

I ended up doing the following:

``` js
[...document.querySelectorAll('.mdl-js-radio')].forEach(el => el.MaterialRadio.checkToggleState());
```

Thanks

**Comment by Adeering** [comment]
Any update on this, Im trying to solve this issue right now

**Comment by RobertoIDL** [comment]
@Adeering I've done what @OliverJAsh suggested and seems to be working. 

You probably have something like this:

`<label id="opt4" class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option4">`

In your javascript function just do this:

` document.getElementById('opt4').MaterialRadio.checkToggleState();`

That seems to reset the UI on the radio button.
