### ISSUE TITLE
[Snackbar] Why is the action button always required?

### ISSUE THREAD

**Issue by tleunen** [google/material-design-lite#4086]
The title says it all.

I'm not sure to understand why a button is needed, even when there only text inside the snackbar.

**Comment by Garbee** [comment]
Because it can be used as either a snackbar or a toast depending on the parameters. We are not dynamically creating elements with new components. It is easy enough to hide from users, so causes no issues in applications.

**Comment by tleunen** [comment]
Ah yes I see. It's because of the queue system.
