### ISSUE TITLE
"is-dirty" doesn't toggle, if value cleared programmatically

### ISSUE THREAD

**Issue by dacodekid** [google/material-design-lite#4089]
When a `textfield`'s value cleared from javascript, `is-dirty` isn't toggling automatically. I have to manually enter a letter & delete to toggle back.  To produce this,

**Enter some value.** After an `ajax` post (with [vue.js](http://vuejs.org/)), `textbox''s value cleared with `this.status = ''`. But this isn't detected by `mdl`.

![image](https://cloud.githubusercontent.com/assets/10047844/12905799/3f75f5ce-cea8-11e5-94fd-11fc7aabc4d8.png)

**Type a letter or two and remove**

![image](https://cloud.githubusercontent.com/assets/10047844/12905868/e102548c-cea8-11e5-82eb-e527ffe5928a.png)

![image](https://cloud.githubusercontent.com/assets/10047844/12905877/f757811c-cea8-11e5-9f3f-7379045de04a.png)

.

**Comment by Zodiase** [comment]
For the textfields, either use `MaterialTextfield.change` for setting value, or use `MaterialTextfield.checkDirty` after changing the value.

**Comment by dacodekid** [comment]
Thx :). I was able to trigger it by 
```javascript
this.$el.querySelector('.mdl-textfield').MaterialTextfield.change()
```
I understand `observable` is not `mdl's` goal, but just not sure how feasible this is when a html form grows huge.
