### ISSUE TITLE
the snackbar is not shown in the middle of the screen

### ISSUE THREAD

**Issue by sranimez** [google/material-design-lite#4091]
I'm starting with the programming on web and I've been using mdl to create a website, I recently saw the update and the addition of the snackbar and implemented, but this is not shown in the middle of the screen but aside half let me know if this is designed to look like this or this can be changed, thanks for reading and I hope you can help me :)

the web is this [bajoweb.tk/mdl/login.php](http://bajoweb.tk/mdl/login.php) , leaving a field blank snackbar shown with the corresponding message.

**Comment by Zodiase** [comment]
The release notes mentioned this. See here: https://github.com/google/material-design-lite/releases/tag/v1.1.0

Although I think if I was implementing this, to make the container centered, I would have a wrapper container with 100% width outside and have the container `margin: 0 auto`.

**Comment by tleunen** [comment]
I know it's a limitation, but why not reset the snackbar position in JS once we know the size of it?

**Comment by sranimez** [comment]
sorry even with his help I have not been layers center it, the CSS is this perhaps can help me here , the problem is that the div has no absolute size :(

```
.mdl-snackbar {
    min-width: 288px;
    max-width: 568px;
    border-radius: 2px;
}
.mdl - snackbar {
    position: fixed ;
    bottom: 0px ;
    left: 50 % ;
    margin- right: -50% ;
    cursor : default ;
    background- color: # 323232 ;
    z -index: 10000;
    display : flex ;
    font -family: " Roboto " , "Helvetica " , "Arial" , sans- serif ;
    will- change : transform ;
    transform: translate ( 0px , 80px ) ;
    transition: 0.25s transform cubic- bezier ( 0.4, 0 , 1, 1 ) 0s , -webkit -transform 0.25s cubic- bezier ( 0.4, 0 , 1, 1 ) 0s ;
    pointer -events : none;
}
```

**Comment by sranimez** [comment]
hello friends wanted to tell them to achieve and center it with a function check on javascritp but I have a little problem when I use this sentence onload = " centrarDiv ();" in the < body> other javascritp of the page does not run .

**Comment by sranimez** [comment]
last update function properly and achieve the code javascritp just put the sentence onload = " centrarDiv ();" early in my javascript file and run properly  :+1:   : P thank you for your help without feedback I had not found the solution.:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Zodiase** [comment]
@sranimez Sorry you lost me. I just checked the link you posted and the toast is still not centered. Here's a generic solution if your snackbar content doesn't change per snackbar message. http://codepen.io/Zodiase/pen/obQrgP

**Comment by sranimez** [comment]
@Zodiase well then your solution is much simpler than mine , I believe another function in javascript to center it, the link is not appreciated because he was working offline but you can come and see it [here](http://bajoweb.tk/mdl/login.php)  and [here](http://bajoweb.tk/mdl/registro.php)

PS : Excuse my English , I speak Spanish and I 'm helping with the translator .

**Comment by Garbee** [comment]
It seems like @Rahul-Sagore has found a pure CSS fix using one of the translation parameters. He has kindly opened PR #4106 to address the problem. I'll take a look at that this weekend to verify and merge if everything checks out.

**Comment by Garbee** [comment]
PR #4106 has been merged into master and will soon be cherry-picked into `mdl-1.1` for the next patch release to address this.
