### ISSUE TITLE
Expandable lists

### ISSUE THREAD

**Issue by FranceBaril** [google/material-design-lite#4092]
Hi, 

I'm not sure if this qualifies a bug report, a feature request or just a request for extra documentation. 

Here is my problem:

I have to represent a book's table of content as a list. I found the layout I need here: https://www.google.com/design/spec/components/lists-controls.html#lists-controls-usage, under expand/collapse. 

I found nothing about how to apply it for the web. The documentation is silent here: https://www.getmdl.io/components/index.html#lists-section.

This is the code to my 1st level:

`<nav><ul class="map mdl-list"><li class="topicref mdl-list__item"><a href="test.html" class="mdl-list__item-primary-content">Lorem Ipsum</a></li><li class="topicref mdl-list__item is-active"><a href="test2.html" class="mdl-list__item-primary-content">Eum hinc argumentum te</a></li></ul></nav>`

If I add a `<ul>` as mdl-list after any of the `<a>` , it simply disappears. I tried adding it as secondary content, but then the list appears inline with the `<a/>.`

Please advise.

**Comment by surma** [comment]
This would be a feature request :wink: 

MDL doesn’t cover 100% of the MD spec (far from it, actually), so certain parts have not been implemented (yet). Expanding lists are one of these features. To be honest, I don’t think this will happen anytime soon as we are working on v2, so I suggest you either implement something yourself or choose another way of representing your ToC.

**Comment by davidzchen** [comment]
FYI, there is a prototype of expandable lists in a drawer linked in #221 [here](https://github.com/google/material-design-lite/issues/221#issuecomment-122143874).

**Comment by FranceBaril** [comment]
Great! I will use it as inspiration.

On Wed, Feb 17, 2016 at 4:02 AM, David Z. Chen <notifications@github.com>
wrote:

> FYI, there is a prototype of expandable lists in a drawer linked in #221
> <https://github.com/google/material-design-lite/issues/221> here
> <https://github.com/google/material-design-lite/issues/221#issuecomment-122143874>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/4092#issuecomment-185104280>
> .
>



-- 
France Baril
Architecte documentaire / Documentation architect
france.baril@architextus.com
