### ISSUE TITLE
List line too long

### ISSUE THREAD

**Issue by vince8864** [google/material-design-lite#4095]
In the new material design lite list component, whether we use two line or one three lines options, the first span is only limited to one line. If more than one line in first span, the subtext will float to left below the icon or avatar.

Example:
**253 Mulberry Lane Fall River, 
MA 02720**   <-- this line is too long
Address <-- this line will float to left below icon/ avatar

      <li class="mdl-list__item mdl-list__item--two-line">
        <span class="mdl-list__item-primary-content">
         <i class="material-icons mdl-list__item-icon">place</i>
         <span><?php echo $address ?></span>
       <span class="mdl-list__item-sub-title">Address</span>
       </span>
     </li>

So far, the best workaround i come up with is by wrapping the lines with div block element and set overflow:hidden to it. :

      <li class="mdl-list__item mdl-list__item--two-line">
        <span class="mdl-list__item-primary-content">
        <span><i class="material-icons mdl-list__item-icon" >place</i></span>
        <div style="overflow:hidden;">
         <span><?php echo $address ?></span>
       <span class="mdl-list__item-sub-title">Address</span>
       </span>
       </div>
     </li>

Not sure how material design or MDL tackle this issue, just my suggestion.

**Comment by surma** [comment]
Can you give us a CodePen that reproduces that issue? We have a working example in the docs, that is wrapping text over three lines.

**Comment by vince8864** [comment]
http://codepen.io/vince8864/pen/jWJqKd

Refer to above link.
In example 1 and 2, it shows that whether it is 2 lines or 3 lines, it will mess up if the first line actually occupies two lines of space. Example 3 is simple solution that support dynamic contents. It will always wrap nicely regardless of how many lines (as long as it is within line height). By the way, why use fixed line and height anyway. I understand that list is meant for use as link so long text can get truncated. Another function is to use list to display read only content like contact page. Thing like address is dynamic and not fixed by number of line.

**Comment by vince8864** [comment]
http://codepen.io/vince8864/pen/adrKVM

Here is a simple list that is flexible for showing information and not as entry point/link to deeper level. 

As for for fixed line with fixed height which is meant to used as entry point, there should be a hyphen to clip long text. For example, in the mdl 3 lines example, try to expand the text to fourth and fifth lines and you will see the list behave wrongly. hyphen support is limited in browser. So perhaps a javascript solution is required. Hope you can somehow add the hyphen to better simulate the material design. Thanks

**Comment by rohanthacker** [comment]
@vince8864 Please see the second comment in the PR [#1563] also the [List specification](https://www.google.com/design/spec/components/lists.html#lists-specs)


In the primary-content when the text of a list item overflows its container you'd need to substitute it with an ellipsis and take the appropriate action. As you mentioned above.
 
In a three-line list item however, text is limited to a maximum of three lines. according to the spec.

**Comment by vince8864** [comment]
I see, so it is up to us to include the ellipsis function. ok then. 
For second question, please help me clear my doubt. In the list usage, it stated: If more than three lines of text need to be shown in list tiles, use **cards** instead, so i'm guessing even if i use element which resembles a list but inside a card. It is considered to be a card and is not restricted by the list specification. Like the previous http://codepen.io/vince8864/pen/adrKVM example, this is a card not list, even it looks like a list, so it supports different line numbers without breaking any of the list spec. Plus all example i see in list are geared toward list being used to display links to deeper area and not display read only information. Can i assume like this?
