### ISSUE TITLE
Wiki lists non-standard element property in JS example

### ISSUE THREAD

**Issue by kittsville** [google/material-design-lite#4099]
The example in [Using Snackbars for notifications](https://github.com/google/material-design-lite/wiki/Using-Snackbars-for-notifications) uses `innerText` to set the text of a notification:
```
  text.innerText = message;
```
`innerText` is a [non-standard implementation](https://developer.mozilla.org/en-US/docs/Web/API/Node/innerText) of `textContext` that isn't (and won't be) supported in Firefox. I'd suggest replacing it with the standard `textContent` or, for better support, `innerHTML`.

Love MDL by the way so thanks for the amazing work :heart:

**Comment by kittsville** [comment]
I hasn't realised the current way Snackbars/toast works makes the `innerText` usage redundant. Here's an updated version of the example function:
```javascript
function createToast(message) {
  'use strict';
  var snackbar = document.createElement('div'),
  text = document.createElement('div'),
  button = document.createElement('button'),
  data = {
    message : message,
  };

  snackbar.classList.add('mdl-snackbar');
  snackbar.classList.add('mdl-js-snackbar');
  button.classList.add('mdl-snackbar__action');
  text.classList.add('mdl-snackbar__text');

  snackbar.appendChild(text);
  snackbar.appendChild(button);
  document.body.appendChild(snackbar);

  componentHandler.upgradeElement(snackbar);

  snackbar.MaterialSnackbar.showSnackbar(data);
}
```
Here's it working after running `createToast('Testing Foo Bar')` (it fades as it should):
![actypus_-_2016-02-10_21 39 08](https://cloud.githubusercontent.com/assets/6013087/12962773/c4cf51ba-d03e-11e5-9ec4-536908cb1dbf.png)

**Comment by Garbee** [comment]
Ah, whoops. I forgot to remove that wiki page. It is **very** outdated and referenced an old version of snackbar where I attempted to not provide JS internally but let developers do as they wanted in that regard.

I'll go ahead and remove the wiki page so it doesn't cause anymore confusion. They way to use snackbars is provided in the [snackbar documentation](http://getmdl.io/components/index.html#snackbar-section). Sorry for having left the page up when it wasn't relevant. Thank you for reporting it to us.
