### ISSUE TITLE
UX bugs with the product template

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#410]
Some high-level feedback. I just checked out latest and the UX for this layout was a little unexpected / jarring. Please correct me if I'm looking at the wrong version here: https://www.youtube.com/watch?v=RoVsywMLJXs&feature=youtu.be

Basically, the current tall header is fixed (it's super tall so that feels weird to begin with). On scroll, the navigation is disappearing for me and the content scroll area is super small atm. I remember the older version of this layout not having these issues - it was possible to scroll what was effectively a very static page that you scrolled through without this type of behaviour.

**Comment by surma** [comment]
Closing there are currently no plans to bring back the template.
