### ISSUE TITLE
mdl script cause problem when page is loading

### ISSUE THREAD

**Issue by tommgalati** [google/material-design-lite#4102]
Hi,
I'm writing an html page using mdl and I have a problem with material.min.js (I believe).
After the page is almost complete loaded with components and css, the script is parsed and this cause a strange effect.
For example, the hamburger icon's drawer is loaded at the end and css animation are launched again. If there's a anchor tag in the address bar, at first page loads right but when js is parsed the page come back to top.
I tried the async property in the script and to delete the defer property, but they're not working.
It's a mdl bug or am I doing something wrong?

**Comment by surma** [comment]
I can’t quite visualize what it is you are seeing. Do you mind preparing a CodePen that reproduces the issue for us?

**Comment by Garbee** [comment]
Same kind of issue it seems as [WebFundamentals](https://github.com/google/WebFundamentals/issues/2253) has. If you link to anything with a fragment on the page you will be at the fragment on load (if available) but then after layout is upgraded it will jump to the top of the page (because we move the content into another node.)

The only feasible fix we could do internally is use JS to detect a fragment in the URL. Then post-upgrade check the content for a matching `id` or `name` (since I believe fragments also work with that attribute) and if found do a JS scroll to that area within the content.

**Comment by tommgalati** [comment]
Yes, it's the same issue.
I fixed it, doing debug I discovered that my problem was on MaterialLayout component, so I modified the function upgradeAllRegisteredInternal() inside material.js avoiding it to upgrade that element.
```
/**
   * Upgrades all registered components found in the current DOM. This is
   * automatically called on window load.
   */
  function upgradeAllRegisteredInternal() {
    for (var n = 0; n < registeredComponents_.length; n++) {
        if(registeredComponents_[n].className != 'MaterialLayout') {
            upgradeDomInternal(registeredComponents_[n].className);   
        }
    }
  }
```
Now I have to upgrade the drawer manually using the [upgradeElement function](http://www.getmdl.io/started/index.html#dynamic) in the footer
`<script>
    componentHandler.upgradeElement(document.getElementById('fixed-header'));
</script>`

To fix the anchor tag problem, I listen for the mdl-componentupgraded event with a script tag in the header of my page. After all components are upgraded, I scroll to the anchor tag found in window.location

Do you need a CodePen to reproduce this issue?

**Comment by addyosmani** [comment]
A CodePen to repro would be super helpful.

**Comment by rtwk** [comment]
@tommgalati, would you please provide a jsbin / codepen of what you have done. In my newly created template, Adsense ads loads twice and even I tried to fix the issue as you have mentioned, it has not being fixed. Any other fix is also welcome.

**Comment by tommgalati** [comment]
Sorry @rtwk but I'm not on that project anymore so I can't access to its source code. Can I be helpful in another way?
Do you have an identical problem?

**Comment by rtwk** [comment]
Thanks for replying. We solved the issue. Not the way suggested there
though.

**Comment by sidraw27** [comment]
@rtwk 
Hello, could you show how to solved that, we encounter the same problem too, 
thx a lot!
