### ISSUE TITLE
More breakpoints

### ISSUE THREAD

**Issue by RanzQ** [google/material-design-lite#4103]
Would it be possible to add more breakpoints according to [MD breakpoint system](https://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-breakpoints)? For a website the desktop breakpoint of 1200px is enough but for example in a fullscreen webapp it would be nice to adjust the layout for larger screens. Personally I would use breakpoints 600 -> 960 -> 1280 -> 1920 and name them xsmall-xlarge / xs-xl.

Currently there are only two, tablet 840 and desktop 1200, which limits quite a lot in app usage.

**Comment by surma** [comment]
The grid only needs to care about the breakpoints that change the number of columns, which is why we only have 2 breakpoints built in. 

In your case, I’d encourage you to just write these classes/media-queries yourself.

**Comment by RanzQ** [comment]
@surma ok, that explains why there are only two. I'll add the ones I need myself. :)
