### ISSUE TITLE
Different position of footer in Safari and Chrome

### ISSUE THREAD

**Issue by kkpoon** [google/material-design-lite#4108]
Incorrect Footer position in Mac Safari 9.0.3.
As see in the screen shot, the position of the footer is rendered in the middle of the screen.
That position is the original bottom of the screen before scroll down.

![screen shot 2016-02-12 at 18 00 26](https://cloud.githubusercontent.com/assets/191992/13003874/e0d7df6a-d1b2-11e5-95bf-d798ef5c3e13.png)
![screen shot 2016-02-12 at 18 00 34](https://cloud.githubusercontent.com/assets/191992/13003876/e44ae8b8-d1b2-11e5-8748-db56064dbd31.png)

**Comment by Garbee** [comment]
Can you please provide a [codepen](http://codepen.io) where this problem reproduces?

We have seen these kinds of issues before, and they have stemmed from developers putting the footer outside of the `mdl-layout__content` area. Although I'm not sure why the effect would happen in only one browser if that were the case.

**Comment by kkpoon** [comment]
please visit: http://kkpoon.github.io/react-redux-boilerplate with those browsers, thanks

**Comment by kkpoon** [comment]
> developers putting the footer outside of the mdl-layout__content area

You are right. after put back the footer into the mdl-layout__content, it render good.
thanks
