### ISSUE TITLE
Snackbar hidden under the drawer

### ISSUE THREAD

**Issue by palsoft333** [google/material-design-lite#4124]
Snackbar is not at the very top z-index of the page, when the drawer is open. This is problem for example for mobile sites, where you open the drawer with login form and then you can't see the snackbar message.

![image](https://cloud.githubusercontent.com/assets/13525347/13057336/b01b001c-d41b-11e5-9f09-f63f849b572c.png)

Fiddle: https://jsfiddle.net/gjex514w/1/

**Comment by Garbee** [comment]
Thanks for filing an issue. I don't think the spec gives any clear guidance as to how to handle this from what I recall.

cc @sgomes to touch base with the MD Team to see if we can get some quick guidance on how this should interact.

We need to know if a snackbar should sit on top of the drawer and backdrop. The idea being if someone does an action, then opens the drawer before the action finishes, then should the alert show on top or not? We shouldn't focus on the login form in drawer scenario, this does not adhere to any spec guidelines as far as I am aware.

**Comment by palsoft333** [comment]
Thank you. The login form was just an example from my site. Let me think of it like any toast message fired while the drawer is open. When i was implementing it, i thought the snackbar's z-index of 10000 should take care of it, but i will probably look for another solution for showing the error message.

**Comment by Garbee** [comment]
Looking at the layout stuff again, 10k z-index is crazy overkill. I think I did that for dialog stuff, but even that is iffy sometimes.

I think the root cause is position absolute (of layout obfuscator and drawer) are winning over the fixed position of the snackbar. Not sure what we can do here with CSS tech that will work since snackbar needs to be fixed.

**Comment by sgomes** [comment]
@Garbee As per the spec:
> Snackbars appear above most elements on screen, and they are equal in elevation to the floating action button. However, they are lower in elevation than dialogs, bottom sheets, and navigation drawers.

So it sounds this is working as intended?

**Comment by Garbee** [comment]
Ah good eyes, @sgomes. I'll do a quick patch to tone-down the z-index then since even dialogs show above it.
