### ISSUE TITLE
A spelling mistake

### ISSUE THREAD

**Issue by tajpure** [google/material-design-lite#4128]
In this file: https://github.com/google/material-design-lite/blob/d27f47fd2811ff4139794e1ba899c7add40072a5/src/data-table/README.md

![20160216110714](https://cloud.githubusercontent.com/assets/1475405/13066180/7f041eb8-d49e-11e5-92df-727e28c6ce6b.png)

I think it should be changed to "mdl-data-table__header--sorted-descending".

**Comment by Garbee** [comment]
Fixed via commit f99892cbb1ec5691b906ea5a779762a3652b28d2. Thanks for the issue!
