### ISSUE TITLE
Investigate best practices for font loading

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#413]
The Material Design fonts are pretty much required for MDL.
Currently developers need to include it themselves using

``` html
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```

We should include it automatically using an `@include` in the MDL CSS.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/40
