### ISSUE TITLE
issue when using href="#id"

### ISSUE THREAD

**Issue by Adryd** [google/material-design-lite#4142]
There is an issue when attempting to go to a specific part of a page using `<a href=#anotherpage>next page<a>`.
instead of going to that page it just adds the tag to the end of the url.
i don't want to make a new html file unless it's the only option.
if this is intended is it possible to disable.

**Comment by surma** [comment]
This is due to our current implementation of layout. There’s nothing we can do about that in v1, but we have a rewrite planned for v2 that should fix this issue.
