### ISSUE TITLE
cannot align centred items in header to centred items in body due to scroll bar

### ISSUE THREAD

**Issue by Roaders** [google/material-design-lite#4143]
Hi

I am trying to create a site with centered content in both the header and the main but as the main has a scrollbar it is out of line with the header.
I have created a stackoverflow post about it:

http://stackoverflow.com/questions/35501469/best-way-to-deal-with-mis-aligned-header-and-main-due-to-scrollbar

**Comment by surma** [comment]
I agree with the answer given on StackOverflow. Closing this.
