### ISSUE TITLE
android.com skin template lacks carousel

### ISSUE THREAD

**Issue by pax** [google/material-design-lite#4144]
In the [template list page](http://www.getmdl.io/templates/android-dot-com/index.html), the _ANDROID.COM MDL SKIN_ description includes _feature carousel_  – which is not visible in [the preview page](http://www.getmdl.io/templates/android-dot-com/index.html)  .

![image](https://cloud.githubusercontent.com/assets/116795/13184049/6f072e46-d742-11e5-8733-91c69bf9d442.png)

**Comment by surma** [comment]
It is if you make your browser window smaller or open the webpage on mobile :)

**Comment by pax** [comment]
ok, still, I couldn't find anywhere an example (including desktop-view) or documentation for implementing a carousel in mdl

**Comment by surma** [comment]
That is because a carousel is not part of MD (or MDL). That template is just a very high-fidelity reproduction of android.com *using* MDL. Feel free to rip out the carousel code :smile:

**Comment by sendit34** [comment]
If I strip out from android.com is there a licensing issue?.

Can I use "Stripped" code for commercial applications?

**Comment by Garbee** [comment]
@sendit34 We are not lawyers and can't comment on any particular instance or use. Adhere to the [LICENSE](https://github.com/google/material-design-lite/blob/mdl-1.x/LICENSE) of the code provided and you're good to go.

**Comment by sendit34** [comment]
Thanks for your prompt reply.  I am clear on MDL license. I am thinking if I go to android.com and use  carousel code from that html/css, is it also under Apache License 2.0?

**Comment by Garbee** [comment]
The source code for that isn't open source. That's all I can say on the matter.

**Comment by MrCsabaToth** [comment]
@sendit34 could you send the stripped gist my way? Now 2 years later the android.com doesn't have that carousel any more (as far as I can see), but I'd be curious how was it in the past.

**Comment by MrCsabaToth** [comment]
I looked at the way back machine, everything is minimized so if anyone has a nice extraction of it please let me know.
