### ISSUE TITLE
Unchecking pre-checked checkbox

### ISSUE THREAD

**Issue by BurningLights** [google/material-design-lite#4149]
Platform: Google Chrome 43 on Windows 10

MDL Version: 1.1.1

If a checkbox has the "checked" attribute on page load, it refuses to uncheck. This is exhibited on the MDL component documentation. Demo: http://getmdl.io/components/index.html#toggles-section.

**Comment by jwashin** [comment]
There is another checkbox with id="checkbox-1" on the referenced page, in the "Lists: avatars and controls" section, next to Bryan Cranston. That's the source of the difficulties. This baffled me for a while, too.

**Comment by Garbee** [comment]
Ah, fantastic catch @jwashin! Merging this into the other related issue. Thanks for taking a look.

That issue is #4148.
