### ISSUE TITLE
Default font color for mdl-navigation__link

### ISSUE THREAD

**Issue by vince8864** [google/material-design-lite#4151]
mdl-layout__drawer .mdl-navigation .mdl-navigation__link {
    display: block;
    -webkit-flex-shrink: 0;
    -ms-flex-negative: 0;
    flex-shrink: 0;
    padding: 16px 40px;
    margin: 0;
    **color: #757575;**
}

.mdl-navigation__link {
    **color: #424242;**
    text-decoration: none;
    margin: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 24px;
    letter-spacing: 0;
    opacity: .87;
}

1. why different color is used in both places? The first one will always dominate the second one anyway. 
2. in https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs it states that the list item color should be #000000 rather than those 2 in above.

**Comment by Garbee** [comment]
`.mdl-navigation__link` refers to the links in the appbar (currently not specified.) While the first selector is specifically targeting drawer items.

As far as the drawer color being incorrect, that is right. We have some re-alignment happening in V2 so the drawer should be fully compliant again.

Does this explain the inconsistencies well enough?

**Comment by vince8864** [comment]
Crystal clear, that really clears my doubt. Keep the awesomeness coming. Thanks
