### ISSUE TITLE
mdl-slider__label

### ISSUE THREAD

**Issue by Inuart** [google/material-design-lite#4152]
[Here](http://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider) we see a "Media volume" label.

What would be the appropriate style for a mdl-slider__label? I am guessing `color: grey;` is not sufficient...

**Comment by surma** [comment]
You would probably combine an MDL slider with an [MDL icon](http://google.github.io/material-design-icons/) that we support directly. You might have to set the color yourself to match the example in the spec, yes.

For future reference, the GH issue tracker is for bugs and feature requests. Please use StackOverflow with the `material-design-lite` tag for support questions.
