### ISSUE TITLE
[docs] Snackbar default timeout is 2750

### ISSUE THREAD

**Issue by Maks3w** [google/material-design-lite#4155]
https://github.com/google/material-design-lite/blob/master/src/snackbar/README.md

> Optional (default 8000)

But

https://github.com/google/material-design-lite/blob/master/src/snackbar/snackbar.js#L118

> this.timeout_ = 2750;

**Comment by Garbee** [comment]
Thanks for the report. Fixed with commit 4fcdb11c3f77e202c4c966014537ee0de82b14db. This is in the `mdl-1.1` branch so the docs will be updated with our next tag. Eventually it will be merged into master and be good from there.
