### ISSUE TITLE
Material menu doesn't work on appended elements.

### ISSUE THREAD

**Issue by SaadeMotion** [google/material-design-lite#4157]
I have a little comment section on my project. I'm showing only 2 comments on DOM, and i have a little button when i click it's sends an ajax request for DB, and return 2 more comments. I'm getting the response of php and after append to the comments section. But the menu does'nt work for the appended comments. Any idea?

Here's my code:

`
$.ajax({

		  method: "POST",
		  url: root+"Fn/loadMoreComments",
		  dataType: "json",
		  data: { act : act, limit: limit }

		}).done(function(response) {

			for(var i = 0; i < response.length; i++) {			

			var comment = '';
		    	comment += '<div class="comment '+response[i].mine+'">';
		    	comment += '<div class="container-fluid">';
		    	comment += '<div class="row">';
		    	comment += '<div class="comment-header col-xs-12">';
		    	comment += '<div class="col-xs-2 post-user xs-p-0">';
		    	comment += '<img class="img-responsive post-user-photo img-circle" src="'+response[i].profilePic+'">';
		    	comment += '</div>';
		    	comment += '<div class="col-xs-10 comment-info">';
		    	comment += '<div class="col-xs-11 xs-p-0">';
		    	comment += '<div class="col-xs-12 xs-p-0">';
		    	comment += '<span class="post-user-name"><a href="profile/'+response[i].username+'">'+response[i].name+'</a></span>';
		    	comment += '</div>';
		    	comment += '</div>';
		    	comment += '<div id="comment-more_'+response[i].sha1+'" class="post-more col-xs-1 pull-right xs-p-0">';
		    	comment += '<i class="mdi mdi-dots-vertical"></i>';
		    	comment += '<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="comment-more_'+response[i].sha1+'">';
		    	comment += '<li class="mdl-menu__item">Editar Publicação</li>';
		    	comment += '<li class="mdl-menu__item">Editar Local</li>';
		    	comment += '<li class="mdl-menu__item">Alterar Data</li>';
		    	comment += '<li class="mdl-menu__item">Destaque</li>';
		    	comment += '<li class="mdl-menu__item divider">Desativar Notificações</li>';
		    	comment += '<li class="mdl-menu__item">Ocultar</li>';
		    	comment += '<li class="mdl-menu__item">Excluir</li>';
		    	comment += '</ul>';
		    	comment += '</div>';
		    	comment += '</div>';
		    	comment += '</div>';
		    	comment += '</div>';
		    	comment += '<div class="row">';
		    	comment += '<div class="col-xs-12">';
		    	comment += '<p class="comment-content">';
		    	comment += response[i].comment;
		    	comment += '</p>';
		    	comment += '</div>';
		    	comment += '</div>';
		    	comment += '</div>';
		    	comment += '</div>';

		    	$this.before(comment);
			}
`

My menu is appending with the comment, and the menu doesn't open.

**Comment by surma** [comment]
You need to run the upgrade method on dynamically created elements. Please read the documentation on how MDL works with dynamic websites: http://getmdl.io/started/index.html#dynamic

**Comment by SaadeMotion** [comment]
Still having no response... am i doing right?

```
var button = document.createElement('div');
button.className = 'post-more col-xs-1 pull-right xs-p-0';
button.id = 'comment-more_'+response[0].sha1;
		
componentHandler.upgradeElement(button);

document.getElementById('comment-info_'+response[0].sha1).appendChild(button);
```

Need to upgrade the menu itself too?

**Comment by SaadeMotion** [comment]
Thanks! It worked.
