### ISSUE TITLE
Tooltip positioning in ripple container via mdl-tooltip--* is ignored in 1.1.1

### ISSUE THREAD

**Issue by cdiener** [google/material-design-lite#4158]
Trying to positioning the tooltip as described on getmdl.io via mdl-tooltip--right will be ignored in Chromium and Iceweasel. Could it be related to the ripple container? 

Example: the back button on top at http://cdiener.com/posts/docker_training/.

**Comment by cdiener** [comment]
Trying to make a smaller example I discovered the error was on my part. sorry

**Comment by surma** [comment]
I am *very* relieved! Thanks for keeping an eye out, tho :D
