### ISSUE TITLE
Setting checkbox state from JavaScript

### ISSUE THREAD

**Issue by MikeGWem** [google/material-design-lite#4164]
I have a number of checkboxes on a form and wish to set and unset some from JavaScript after the page has loaded.

setting the "checked" property of the Input element in the DOM has no effect.
calling componentHandler.upgradeElement() after setting the checked state has no effect.

I looked at all of the issues tagged for checkbox but did not see a solution. Feels a tad fundamental - I am assuming there are methods to interact with the MDL upgraded HTML objects.

**Comment by MikeGWem** [comment]
Got there in the end by re-setting the is-checked class on the parent <label> tag

var te = $('#some-checkbox').prop("checked", false).parent();
te.removeClass('is-checked');

is a jQuerified version

**Comment by sachin8080** [comment]
Thanks @MikeGWem for your solution. I was facing the same issue. I feel there should be a more generic way of doing this and componentHandler.upgradeElement() should ideally do this job.

**Comment by comerc** [comment]
$('#some-checkbox').trigger('click');
