### ISSUE TITLE
Indeterminate Checkbox

### ISSUE THREAD

**Issue by kevinahuber** [google/material-design-lite#4171]
It would be nice to have a visible state for when a checkbox is indeterminate, as styled by a white hyphen surrounded by the primary color. This does not affect the checkboxes actual state. 

This is useful for when a checkbox is not necessarily fully true or false. It comes in handy for nested checkboxes where some children are selected, or when viewing the settings of multiple objects and some are checked and some are not. 

![image](https://cloud.githubusercontent.com/assets/6272414/13506604/8073a2de-e144-11e5-8043-2a83deb478f9.png)
(https://css-tricks.com/indeterminate-checkboxes/)

**Comment by sgomes** [comment]
The Material Design spec currently has no guidance for indeterminate values on checkboxes or other switches, I'm afraid :-/

**Comment by sgomes** [comment]
Alpha implementation in [the new checkbox](https://github.com/material-components/material-components-web/tree/master/packages/mdc-checkbox) on Material Components for the web. Happy to review any backports if anyone is interested in doing that work.
