### ISSUE TITLE
Mdl tabs

### ISSUE THREAD

**Issue by Ahmadbaba46** [google/material-design-lite#4176]
Mdl tabs doesn't stick on bottom of the page. I gave it fixed position but still failed to stick;

**Comment by sgomes** [comment]
Hey @Ahmadbaba46! Neither the layout tabs nor the content tabs in MDL were designed to stick to the bottom, I'm afraid. There's currently no guidance in the Material Design spec for bottom tabs, though, so we'll have to wait until that's available.

**Comment by Ahmadbaba46** [comment]
OK. Thanks

**Comment by Whiteseeker** [comment]
I had also loved this :) Specially to repro the behavior of other Material design app from Google (^_^).
Google+ Android app has bottom tab, Google play newsstand too and Google art & culture for instance. On mobile it's specially not practical to have the tab at the top of the page: it's hard to reach with your thumb ...

**Comment by Garbee** [comment]
@Whiteseeker Those are **not** tabs. That is *Bottom Navigation* [Spec](https://material.google.com/components/bottom-navigation.html) which is essentially just standard links with icons at the bottom. We do not currently have this component however V2 should introduce it at some point.

**Comment by Whiteseeker** [comment]
Glad to see that it's in the standard and coming in V2 (^_^)
Sorry for the confusion between tabs and navigation bar, as a user it's quite hard to see the difference (^_^). My bad
