### ISSUE TITLE
Proposal: Drop .mdl-js-* modifiers

### ISSUE THREAD

**Issue by KorsaR-ZN** [google/material-design-lite#4185]
We must drop modifiers:
`.mdl-js-layout`
`.mdl-js-textfield`
`.mdl-js-button`
`.mdl-js-checkbox`
`.mdl-js-radio`
`.mdl-js-icon-toggle`
`.mdl-js-switch`
`.mdl-js-slider`
`.mdl-js-progress`
`.mdl-js-spinner`
`.mdl-js-menu`
`.mdl-js-data-table`
`.mdl-js-snackbar`

I believe they impose additional responsibilities to keep in mind. All the necessary JS code should be registered automatically when the component initialization...

A modifier `.mdl-js-ripple-effect` propose to rename in general style in `.mdl--ripple`

P.S I think that adoption of this issue will make the documentation clearer and easier to work with MDL
I can create a PR

**Comment by Zodiase** [comment]
Now what if I'd like to use the styling of `.mdl-button` but not let MDL upgrade it?

**Comment by Zodiase** [comment]
To me that `.mdl-js-button` means "MDL should upgrade it". Although there are a few exceptions, especially in layout.

**Comment by gpgekko** [comment]
What's wrong with responsibilities and choice? Any dynamic component has a `.mdl-js-` class, I'd say that's not that hard to remember.
I doubt it will do anything for clarity or ease of use, as it is consistent and it's functionality is easily deduced from the class name. Personally, I got used to it rather quickly.

**Comment by Garbee** [comment]
This is going to be solved in developing 2.x. The new architecture is making the component handler entirely optional so you will chose whether to use these js classes or do your own thing.

We are unable to address this in 1.x since it is a backwards incompatible change.
