### ISSUE TITLE
Site Showcase Request

### ISSUE THREAD

**Issue by elfico** [google/material-design-lite#4200]
Please include: dropdown elements
* Description
* Primary Link
* Screenshot

**Comment by randrianov** [comment]
@elfico maybe this mdl select help you
[github page](https://github.com/CreativeIT/getmdl-select)
[demo](http://creativeit.github.io/getmdl-select/)

**Comment by elfico** [comment]
Thanks alot @randrianov

**Comment by sgomes** [comment]
Not a showcase request, and I believe we already have #854 open for select / dropdown elements.
