### ISSUE TITLE
Shouldn't MDL just be the Polymer paper elements minus the Polymer?

### ISSUE THREAD

**Issue by s-devaney** [google/material-design-lite#4202]
I don't like Polymer as a framework (it's just not my thing) but I want to use material design in my app with my framework of choice. MDL looked perfect but the range of components is not the same as Polymer. 

Given they're both Google projects why can't MDL components just be Polymer paper elements without all the Polymer stuff?

E.g. I want to use paper-header-panel with the cover mode but I can't do that in MDL - why?

**Comment by sgomes** [comment]
Assuming your question is about the range of components in MDL and not about the technical feasibility of having Polymer's paper elements without Polymer (which, to my knowledge, is rather impossible without a complete rewrite), MDL and Polymer's paper elements are two separate projects. They differ significantly in the use-cases they target, and they're not developed by the same team. You'll definitely find things which aren't in one project but are in the other, simply by virtue of what each project has been prioritising and how many resources they have.

If you need a specific component or option, please file a bug request and we'll take a look!
