### ISSUE TITLE
Remove Wrapping in MaterialLayout

### ISSUE THREAD

**Issue by awalacabab** [google/material-design-lite#4208]
In MaterialLayout.prototype.init, the first few lines wrap the content of the page in a div with class "mdl-layout__container" by essentially recreating the non-wrapped content inside the div wrapper.

I think for general use, this is not a good practice -I ran into an issue with event listeners when I have CKEditor embedded in the page (I've been implementing MDL into Drupal). The solution might be to make sure the CKEditor script (or any other for that matter) is included AFTER the MDL script, but sometimes this can be tricky or impossible to do with content management systems and hey, we want content management systems to start adopting the use of MDL. Furthermore, the easier MDL is to use, the more people will use it.

I propose we change this practice. Instead of wrapping the content, we either add the "mdl-layout__container" class to the div with class "mdl-layout" (which would require some JS and CSS changes) or we make the container part of how we tell users to setup their HTML.

I think the former option is better since there is no need to wrap a wrapper with another wrapper and would not cause structural problems in peoples' HTML. I'm going to create a fork and try to make the proposed changes. In the meantime, if anyone has any thoughts or ideas about this, please let me know!

**Comment by Garbee** [comment]
This will be taken care of when carrying out #1735. Until then, Layout is pretty much stuck in place for backwards compatibility reasons and making any modifications to it is worrysome due to how intricate the module is.

We do understand the current layout component is a massive pain-point, but we can't risk breaking sites using it. These changes need to wait until 2.x.

**Comment by sgomes** [comment]
Closing as we already have #1735 to track the change, as @Garbee pointed out.
