### ISSUE TITLE
Buttons have decimal pixel widths

### ISSUE THREAD

**Issue by jiaweihli** [google/material-design-lite#4210]
Check the buttons on http://getmdl.io/components/index.html#buttons-section

Decimal pixels can cause things ranging from blurriness to off-by-1-pixel issues that vary across platforms.

http://martinkool.com/post/27618832225/beware-of-half-pixels-in-css

**Comment by Garbee** [comment]
How exactly would we avoid decimal widths from being calculated?

We have `min-width` set plus some padding internally, then the content itself. All of that goes into calculating the size within the engine.

This blog post is also very old. Is there any recent investigation into these issues to see if they are in fact issues with modern engines?

**Comment by jiaweihli** [comment]
I guess you're right, I'm not sure what can be done to fix this if everything is calculated as an exact fit.  Going to close for now.
