### ISSUE TITLE
FAB ripple effect doesn't work properly in Mozilla Firefox

### ISSUE THREAD

**Issue by tsarapke** [google/material-design-lite#4215]
![ff_ripple](https://cloud.githubusercontent.com/assets/7983863/13924363/11e708e2-ef95-11e5-9dd0-a831437eb61c.gif)

The ripple effect goes beyond of the area of the FAB when you focused in.
Checked on Mozilla Firefox 45.0.1

**Comment by Garbee** [comment]
Testing in FF here it just kinda pulses. No actual Ripple.

Marking as a button and ripple bug, thanks for the report.

**Comment by tsarapke** [comment]
After checking of various cases, i found that the ripple effect don't goes beyond of the area of the FAB in FF, if you add **mask: url();** or **clip-path: url();** to the **mdl-button__ripple-container** class. Maybe it can help.

**Comment by brainscript** [comment]
**+1** I'm experiencing the same issue.

**Comment by wldpaul** [comment]
+1 sadly also seeing this which is making UI very fugly
