### ISSUE TITLE
Button clickable after disabling using mdl-button--disabled class

### ISSUE THREAD

**Issue by jyotman94** [google/material-design-lite#4231]
Its mentioned in the documentation that to disable a button we either use the standard HTML `disable` attribute or use the class `mdl-button--disabled`. But if I use the class `mdl-button--disabled`, it gives the button a disabled look but the button is still clickable and the action is performed as many times as we click the button. HTML `disable` attribute works perfectly.

**Comment by Garbee** [comment]
The `--disabled` modifier is only for the view state. You still need to stop the button from working in other ways (as using the disabled attribute will do.)

What exactly is the expected resolution here? For us to monitor when a disable modifier is applied then disable the action internally?

**Comment by jyotman94** [comment]
Yes exactly. Because that's what the documentation says - 

> <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" disabled>Raised Ripples Disabled</button>. Alternatively, the mdl-button--disabled class can be used to achieve the **same result.** This attribute may be added or removed programmatically via scripting.

**Comment by Garbee** [comment]
Ah, I need to fix the docs real quick then. The disabled class only provides the same styling.

**Comment by Garbee** [comment]
Fixed with commit f976806c9d1815b5634cc31850c487dba20a6b77
