### ISSUE TITLE
Lint step fails on windows

### ISSUE THREAD

**Issue by deuxcents** [google/material-design-lite#4232]
On Windows i encounter the "Invalid line break" after a gulp all on the lint step starting with the first line of src\mdlComponentHandler.js.

The .gitattributes file of master and the 1.1 and 1.2 branches do a : * text=auto which makes the files checked out with CRLF on Windows by default settings. It will be checked in on Github with LF according to git's documentation.

The problem is a rule is set to enforce LF on the lint step. On master the rule comes from eslint-config-xo ('linebreak-style': [2, 'unix']). On the 1.1 and 1.2 branches the rule comes from the .jscsrc file ("validateLineBreaks": "LF").

If this lint test is intended as a last resort solution, can the  * text=auto in .gitattributes be replaced by * eol=lf ? So the files will be checked out with an LF only on Windows and the test can pass.

**Comment by jiaming10** [comment]
Hi, I also suffered this problem but am able to solve it following [README's instruction](https://github.com/google/material-design-lite#download--clone).

Pasting the command here in case you don't want to waste a click.
```
git config core.eol lf
git config core.autocrlf input
git rm --cached -r .
git reset --hard
```
Please note that **`git reset --hard` will reset ALL of your uncommited work**.
