### ISSUE TITLE
Material spec for labeled switches exist?

### ISSUE THREAD

**Issue by ConAntonakos** [google/material-design-lite#4241]
Is there design spec for switches that are labeled? Rather than the traditional toggle, I'm referring to text embedded in the switches like so: 
![capture](https://cloud.githubusercontent.com/assets/1504302/14196284/e240dc0e-f790-11e5-8aa1-fe13858c56fd.PNG)

How would this be designed under MD guidelines? Perhaps, it would be more of a set of radio buttons?

**Comment by shmshd12** [comment]
There is no labeled switch button in Material Design Guideline. You can use MDL switch button because universally grey switch button is 'No' and colored switch button is 'Yes'.

**Comment by ConAntonakos** [comment]
For the traditional "Yes/No" switch, definitely. But if I'm trying to be more descriptive like let's say "Choose Choice 1/Choose Choice 2", what would be the design guidelines around that?

**Comment by shmshd12** [comment]
You could use MDL check buttons. This is question is not a part of MDL issue.

**Comment by ConAntonakos** [comment]
Yes, I understand. If it doesn't exist, would it possible to be a feature request or more clarity?  The current MDL radio buttons still don't satisfy the design goals I'm considering. If this is not the proper forum to ask, please let me know. Thanks!

**Comment by Garbee** [comment]
This isn't specified and won't be implemented by the core team as such. Developers should implement this pattern on their own.

Thank you.
