### ISSUE TITLE
material.min.js : two load of the page at start

### ISSUE THREAD

**Issue by PACIFIQUE140** [google/material-design-lite#4242]
Hi,

I have to solve a problem for my customer. I have see much time that it seem to have two loading of the page using MDL.

It's loading one time, and then, another one. This file (material.min.js) is responsable of this problem.  

Thanks a lot, I work in production only with MDL and made more than 5 site with it. 

Regards

**Comment by Garbee** [comment]
For support please use [StackOverflow](https://stackoverflow.com) and use the `material-design-lite` tag along with any other appropriate tags. This tracker is only for problems with the code provided. It does not call a request for itself, so the problem must be in the application stack.

Thank you.
