### ISSUE TITLE
[bug?] Menus will not display on dynamic content 

### ISSUE THREAD

**Issue by efortes** [google/material-design-lite#4243]
The menu items won't display if the content is loaded from the backend (dynamic data)
My code
`          <button id="menu-speed" class="mdl-button mdl-js-button mdl-button--icon">
            <i class="material-icons">more_vert</i>
          </button>
          <ul class="mdl-menu mdl-js-menu" for="menu-speed">
            <li class="mdl-menu__item">Fast</li>
            <li class="mdl-menu__item">Medium</li>
            <li class="mdl-menu__item">Slow</li>
          </ul> `

In non dynamic content the current div is added:

`<div class="mdl-menu__outline mdl-menu--bottom-right" style="width: 148.313px; height: 208px;"></div>`

Am i doing something wrong or is this a bug?

**Comment by efortes** [comment]
I am using angular 2

**Comment by efortes** [comment]
`<div id="container"/>
<script>
  var button = document.createElement('button');
  var textNode = document.createTextNode('Click Me!');
  button.appendChild(textNode);
  button.className = 'mdl-button mdl-js-button mdl-js-ripple-effect';
  componentHandler.upgradeElement(button);
  document.getElementById('container').appendChild(button);
</script>`

You need to use the componentHandler to fix this problem

**Comment by tjoskar** [comment]
Calling `.upgradeAllRegistered()` after the template has rendered should do the trick.

Eg. in angular 2:
```
ngAfterViewInit() {
    window['componentHandler'].upgradeAllRegistered();
}
```

**Comment by efortes** [comment]
Ahh great answer tjoskar. I will try that

**Comment by efortes** [comment]
For the typescript users. You might want to declare the window object on top.

`declare var window:any;`

**Comment by maiakaat** [comment]
I seem to have seen possible issues when using Angular 2, but I'm too much of a beginner to add anything meaningful at this stage.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
