### ISSUE TITLE
Get text from textarea

### ISSUE THREAD

**Issue by audiultx** [google/material-design-lite#4245]
Hi, i am not able to retrieve the text that is typed in a textarea. I have tried everything from jQuery element.html() to pure javascript. 
thx.

**Comment by dgrubelic** [comment]
Sorry if I'm being too harsh, but how is this related to MDL components?

BTW, this should do the trick...
`var txtValue = element.value;`

**Comment by audiultx** [comment]
Hi, thank you very much, that was it. Well, "Text fields" are in the "Component" area? Maybe i was wrong to post the issue here but where else?

**Comment by dgrubelic** [comment]
Yes, Text fields are in the Components area but this question has nothing to do with MDL components implementation. This is pure JS issue which you could Google...

**Comment by audiultx** [comment]
oh ok my misstake then. Trust me i did google but did not find any answer to my question that's why i posted here. But thx for the help i am now back on track.
