### ISSUE TITLE
jquery trigger click opens and immediately closes context menu ( only in firefox )

### ISSUE THREAD

**Issue by archonkulis** [google/material-design-lite#4247]
Hi guys,

I've made this fiddle to make debugging easier -> [https://jsfiddle.net/ayo8voh2/](https://jsfiddle.net/ayo8voh2/)

What I wanted to do is when user clicks with right mouse click on the menu button, disable default browsers context menu and trigger default left mouse click ( so that mdl context menu would open ).

**To re-create issue**:

1) First open fiddle in **Chrome**, and click on menu icon ( 3 dots ) with the **RIGHT** mouse button - notice how it opened menu nicely;
2) Now open same fiddle in **Firefox** and do the same actions - notice how menu opens and immediately closes; ( If you click and hold with right mouse, it will stay open, though. Also, if you click with right mouse and then move cursor to the menu that opened, it will also stay open )

I couldn't find a fix for this as this bug(?) looks really odd for me. Maybe there is something with Firefox that you guys know and I don't?

It's possible to overcome this with positioning menu so that when it is opened, it is opened where the mouse cursor is - and then it doesn't disappear, but it's not a normal fix, but more like a "ugly hotfix".

Thanks for looking into this and have a nice debugging ( if it will be needed ).

**Comment by Garbee** [comment]
Please use StackOverflow for help and integration support. This issue tracker is only for core problems related to the code MDL provides.

Thank you.

**Comment by archonkulis** [comment]
Hmm, sorry, but did you at least read my ticket? What it has to do with integration?!
