### ISSUE TITLE
`MaterialSlider.change` should trigger the `change` event of the underlying input

### ISSUE THREAD

**Issue by MrMitch** [google/material-design-lite#4248]
MDL version: 1.1.3
Browser: Chrome Stable
Browser version: 49.0.2623.110 (64-bit)
Operating system: Linux (Ubuntu)
Operating system version: 15.04 (kernel 4.2.0-34)
URL : CodePen for demo [http://codepen.io/anon/pen/NNwvwK](http://codepen.io/anon/pen/NNwvwK)

## What steps will reproduce the problem:
1. set a slider's value using the `MaterialSlider.change(newValue)` method

## What is the expected result?
The `change` event of the input is triggered.

## What happens instead of that?
The `change` event of the input is not triggered.

**Comment by Garbee** [comment]
Thanks for the feedback here.

The [change method](https://github.com/google/material-design-lite/blob/master/src/slider/slider.js#L175) is simply updating the value and then calling to styles to be updated. Being consistent with standard JavaScript, the event is not fired. Events are triggered on *user modifications* and not by developers pragmatic ones. Therefore, in alignment with how JS does things we decided not to manually recreate the events.

This is something developers need to handle in their code the same way they always have when pragmatically manipulating form inputs.

**Comment by MrMitch** [comment]
thank you for the clarification
