### ISSUE TITLE
Cleanup: don't assign numbers to style.left, top, width, etc.

### ISSUE THREAD

**Issue by pallosp** [google/material-design-lite#4253]
tooltip.js has the following line:
this.element_.style.left = 0;

While it's valid to set length typed attributes to 0, any other number is silently ignored. I would like to 
enforce in Closure Compiler that length attributes are always set to strings to prevent bugs due to missing units. Before that change all element.style.left = 0 and similar assignments need to be updated to element.style.left = '0'.

**Comment by awturner** [comment]
I've submitted a pull request for this: https://github.com/google/material-design-lite/pull/4254

**Comment by Garbee** [comment]
We've handled this recently as we were fixing some errors that came up recently in our linting. Thanks for the report, sorry we didn't get to it sooner.
