### ISSUE TITLE
Problem on mobile devices

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#4256]
If I search long words or a long phrase, the entire page moves to the left.

![screenshot 06-23pm mar 20 2016](https://cloud.githubusercontent.com/assets/17053051/13905765/4e9ad722-eec9-11e5-8251-248503f0cf09.png)

**Comment by Garbee** [comment]
this is an artifact from combining the textfield component with the layout. The core team is focusing on V2 work and only critical internal issues are going to be handled for V1. If someone from the community would like to contribute a patch here, `mdl-1.x` is open for pull requests.

Thank you.
