### ISSUE TITLE
Buggy Components page.

### ISSUE THREAD

**Issue by marcinant** [google/material-design-lite#4259]
http://www.getmdl.io/components/index.html

Components page itself is not good example how to code front-end.

Its code returns a lot of validation errors with something as obvious as this one:
```
A document must not include more than one main element.
```

**Comment by Garbee** [comment]
What exactly is causing usability issues?

Pure HTML validation isn't necessarily a guideline for what is a problem. Having specific issues and the problems they cause would help here.
