### ISSUE TITLE
Chevron Left/Right Not Working on Cards

### ISSUE THREAD

**Issue by deborah86** [google/material-design-lite#4260]
Working with an different icon:

```
<code>
<div class="mdl-card__actions">
									<a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="https://www.google.com/?gws_rd=ssl">Learn More&nbsp;
									<i class="material-icons">arrow forward</i>
									</a>
									<div class="mdl-layout-spacer"></div>
									
								</div>
</code>
```

Not working with the chevron icons:
```
<div class="mdl-card__actions">
									<a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="https://www.google.com/?gws_rd=ssl">Learn More&nbsp;
									<i class="material-icons">chevron right</i>
									</a>
									<div class="mdl-layout-spacer"></div>
									
								</div>
```

I tested in Chrome.  Instead of adding icon, it centers the "Learn More".

The code won't show up correctly in the comment box on Github.

-------

Garbee updated so the code shows correctly. Please use [github flavored markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) so the code shows properly. Just dumping in HTML will lead to it being parsed and sanitized.

**Comment by deborah86** [comment]
This can be closed.  I figured out I needed to make it chevron_right or chevron_left.  Some icons work without the "_" between the words.  It is weird.

**Comment by 5d5f8a0** [comment]
> Working with an different icon:
> 
> ```
> <code>
> <div class="mdl-card__actions">
>                                     <a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="https://www.google.com/?gws_rd=ssl">Learn More&nbsp;
>                                     <i class="material-icons">arrow forward</i>
>                                     </a>
>                                     <div class="mdl-layout-spacer"></div>
> 
>                                 </div>
> </code>
> ```
> 
> Not working with the chevron icons:
> 
> ```
> <div class="mdl-card__actions">
>                                     <a class="mdl-button mdl-js-button mdl-js-ripple-effect" href="https://www.google.com/?gws_rd=ssl">Learn More&nbsp;
>                                     <i class="material-icons">chevron right</i>
>                                     </a>
>                                     <div class="mdl-layout-spacer"></div>
> 
>                                 </div>
> ```
> 
> I tested in Chrome. Instead of adding icon, it centers the "Learn More".
> 
> The code won't show up correctly in the comment box on Github.
> 
> Garbee updated so the code shows correctly. Please use [github flavored markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) so the code shows properly. Just dumping in HTML will lead to it being parsed and sanitized.

"use client"

import { useState } from 'react'
import Image from 'next/image'
import { ChevronLeft, Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'

export default function DepositSettings() {
  const [isAdding, setIsAdding] = useState(false)

  const handleAddDeposit = () => {
    setIsAdding(true)
    // Here you would typically open a form or navigate to a new page for adding a deposit
    // For this example, we'll just toggle the state after a short delay
    setTimeout(() => setIsAdding(false), 2000)
  }

  return (
    <div className="bg-black text-white min-h-screen p-4">
      <header className="flex items-center mb-6">
        <Button variant="ghost" size="icon" className="text-blue-500 mr-2" aria-label="Go back">
          <ChevronLeft className="h-6 w-6" />
        </Button>
        <span className="text-blue-500 text-lg">Settings</span>
        <h1 className="text-2xl font-semibold ml-auto">Deposits</h1>
      </header>
      
      <div className="bg-zinc-900 rounded-xl p-4 mb-6">
        <h2 className="text-zinc-500 mb-4">RECENT DEPOSITS</h2>
        <div className="flex space-x-4">
          <div className="w-1/2">
            <Image
              src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1518-iYMuuaSh6DIElgZJHnL7a47n2suKNx.png"
              alt="Recent deposit preview"
              width={300}
              height={600}
              className="rounded-2xl mb-2"
            />
            <Button variant="secondary" className="w-full">View Details</Button>
          </div>
          <div className="w-1/2">
            <div className="bg-zinc-800 rounded-2xl h-[200px] mb-2" aria-label="Empty deposit slot"></div>
            <Button variant="secondary" className="w-full">Add Deposit</Button>
          </div>
        </div>
        <div className="flex justify-center mt-4 space-x-1" role="tablist">
          <div className="w-1 h-1 rounded-full bg-zinc-700" role="tab" aria-selected="false"></div>
          <div className="w-1 h-1 rounded-full bg-white" role="tab" aria-selected="true"></div>
          <div className="w-1 h-1 rounded-full bg-zinc-700" role="tab" aria-selected="false"></div>
        </div>
      </div>
      
      <Button 
        className="w-full bg-blue-500 text-white mb-6" 
        onClick={handleAddDeposit}
        disabled={isAdding}
      >
        <Plus className="mr-2" /> 
        {isAdding ? 'Adding...' : 'Add New Deposit'}
      </Button>
      
      <div className="bg-zinc-900 rounded-xl p-4">
        <h2 className="text-xl font-semibold mb-2">Manage Your Deposits</h2>
        <p className="text-zinc-400 mb-4">View your deposit history, set up recurring deposits, or manage your deposit methods.</p>
        <div className="bg-zinc-800 rounded-lg h-16 w-8 mx-auto" aria-label="Deposit illustration"></div>
      </div>
    </div>
  )
}

**Comment by Deanzulu** [comment]
What's this
