### ISSUE TITLE
[Feature Request] Persistent navigation drawer, mini variant

### ISSUE THREAD

**Issue by gpgekko** [google/material-design-lite#4262]
I'd like to request the addition of the so called 'mini variant of the persistent navigation drawer'.

I guess it's a missing variation on the existing layout component. The spec is very thin on it, which is mainly why I'm raising this issue, since I'm hoping you can get the design team to work it out a bit more.
It's mentioned under http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior, titled 'mini variant'.

It looks like a very useful feature for tablets and desktops, since it allows to have the navigation on the screen permanently / persistently without taking up as much width as a full size drawer, but it is only described briefly.

![](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ZVZzVEhrbF9YWk0/patterns_navdrawer_behavior_persistent4.png)

**Comment by Garbee** [comment]
This issue is superseded by #4476. We'll take a look at this when implementing the V2 component.

Thank you.
