### ISSUE TITLE
do I use the NAVMENU or the side menu?

### ISSUE THREAD

**Issue by russellharrower** [google/material-design-lite#4266]
Sorry, but I am unsure, what menu I use or how I go about making the menu look like the image below. What I am trying to achieve is the left hand side menu. if anyone can point me into any documentation that outlines how to use material design lite by it's self that would be great.

[http://i.stack.imgur.com/9Cu1E.jpg](url)

**Comment by Garbee** [comment]
For support and integration assistance please use StackOverflow. This tracker is only for problems with the code provided by MDL.

Thank you.
