### ISSUE TITLE
Alignment issue between hamburger icon and title in drawer layout

### ISSUE THREAD

**Issue by mddanishansari** [google/material-design-lite#4267]
![result](https://cloud.githubusercontent.com/assets/11080523/14535664/752dadde-028c-11e6-84aa-059138ecccdf.png)

Above image explains the problem very well.

Top screenshot is the one I took from the site and below screenshot is the one I took from my browser.

**Comment by rejhgadellaa** [comment]
You've probably forgot to set doctype and such. I had the same problem until I came across this:
http://evileyegames.com/article/46-material-design-lite-mdl-fix-menu-icon-vertical-alignment

basically you need to make sure you have...

`<!doctype html>
<html lang="en">
<head>

</head>`

at the top of your html

**Comment by mddanishansari** [comment]
thanks a lot... 
that solved my problem. why didn't i thought of that ???
anyways thanks...
