### ISSUE TITLE
Horizontal dividers in Table render only after a mouse-over on Chrome

### ISSUE THREAD

**Issue by mfonville** [google/material-design-lite#4270]
Not sure if a MDL issue, or a Chrome-bug.
But on the latest Chrome (Linux 50.0.2661.75 (64-bit)) the horizontal dividers don't render until the moment you mouse-over them.
I.e. http://www.getmdl.io/components/index.html#tables-section or any other MDL site using the tables.

I reported the issue via Chrome feedback, hope they can resolve it.

**Comment by xSirrioNx** [comment]
@mfonville 
I fix it by setting table position to "static"
`.mdl-data-table{ position: static; }`

**Comment by mfonville** [comment]
@xSirrioNx Thanks for the hint!

**Comment by dinever** [comment]
Same here.

**Comment by Garbee** [comment]
As discovered in #4325 this is a bug in Chromium itself. It has been fixed internally and is just awaiting landing in stable and getting rolled out to users.

As such, closing this issue since nothing here is actionable within the scope of this project.

Thank you.
