### ISSUE TITLE
Menus do not work. Just do not emerge.

### ISSUE THREAD

**Issue by wzup** [google/material-design-lite#4274]
Your menus just do not work.
I've included all the files from your CDN. Styles are in `<head>` and `<script>` is just before closing `</body>` tag.

```
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
</head>

    ....
    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
</body>
```

And here is my template for menu. And it doesn't make it. Menu doesn't emerge. A button ripple effect is the only piece that works.

```
<section>
                        <button id="numSelect" className="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
                            Select Number
                        </button>
                        <ul className="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="numSelect">
                            <li className="mdl-menu__item">1</li>
                            <li className="mdl-menu__item">2</li>
                            <li className="mdl-menu__item">3</li>
                            <li className="mdl-menu__item">4</li>
                            <li className="mdl-menu__item">5</li>
                        </ul>
</section>
```

**Comment by mspl13** [comment]
It actually does work if you replace the html-propertie `className` with just the proper `class`. You can find a working CodePen [here](http://codepen.io/mspl/pen/wGjzKq).

**Comment by wzup** [comment]
@mspl13 
If I replace the html-property `className` with just the proper `class` it will not work at all. I intend to use the component in React app. React has no `class` attributes.

**Comment by brucedlukens** [comment]
Are you calling componentHandler.upgradeElement on anything?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by consideRatio** [comment]
@wzup i have the same issue. And this is my take on it.

This script, needs to run after the DOM has loaded:

    <script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>

The `defer` attribute is meant to tackle that. But since we use React to dynamically add and remove items to the DOM, the script is run before React has updated the DOM using javascript.

Now what? Well...

Every time we insert some element to the DOM through React, we need to ensure that the MDL fields are registered I believe. But how would you do that manually? What function should we call etc? I'm uncertain.

**Comment by consideRatio** [comment]
https://github.com/google/material-design-lite/issues/4196

**Comment by consideRatio** [comment]
This might be of interest. It successfully enables the ripple effect on the React.Components rendered buttons which are referenced. I do not know how to upgrade the textfields yet though. Note that `componentHandler` is a global object initialized by the MDL .js file.

A React component lifecycle method:

    componentDidMount() {
      for (var key in this.refs) {
        componentHandler.upgradeElement(this.refs[key]);
      }
     }

Within the React components render() function:

    <a className="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect" id="btnSignIn" ref="btnSignIn">
      Sign in
    </a>

**Comment by consideRatio** [comment]
And my final issue was that that I had copied some rendered HTML, which had attributes like `is-upgraded"` and `data-upgraded=",MaterialTextfield"` set on them already, which causes the MDL code inside their provided .js file assume those elements are already processed. Removing those attributes solved my final issues. Below is the textfield html I rendered through my react component and then initialized using the lifecycle method, written about above.

    <div className="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" ref="txtUsernameContainer">
      <input className="mdl-textfield__input" type="text" id="txtUsername" />
      <label className="mdl-textfield__label" htmlFor="txtUsername">Text...</label>
    </div>

**Comment by matoslucas** [comment]
try this
<select className="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
		  <option value="Indistinto">Indistinto</option>
		  <option value="Venta">Venta</option>
		  <option value="Alquiler">Alquiler</option>
		</select>

**Comment by vmittal26** [comment]
componentDidMount() {
  for (var key in this.refs) {
    componentHandler.upgradeElement(this.refs[key]);
  }
 }

Thanks Erik Sundell it solved my problem , Cheers ! :)
