### ISSUE TITLE
Add card columns

### ISSUE THREAD

**Issue by qwertythefish** [google/material-design-lite#4276]
Add card columns, like in bootstrap 4. It will be cool for the desktop
Example, http://v4-alpha.getbootstrap.com/components/card/#columns

**Comment by Garbee** [comment]
Thanks for the suggestion. However, this request doesn't seem to provide any tangible benefit to developers. It just adds more classes internally to do something that developers can easily handle on their own as-needed in their space for layout. It is a single class that only adds two rules of CSS to the container. There is no reason for MDL to introduce this when it is trivial for developers to do on their own.

In the interest of keeping the core lightweight and easy to maintain, we should not introduce this into core.

cc @sgomes for a second opinion here.

**Comment by Garbee** [comment]
Seeing as how we are not a framework and this isn't providing any tangible benefit to developers over writing a few easy lines for them. This won't be implemented in core.

Thank you.
