### ISSUE TITLE
Bugs on css

### ISSUE THREAD

**Issue by chanalex** [google/material-design-lite#4277]
I want to try MDL by modifying the template of Android.com MDL Skin (URL: http://getmdl.io/templates/android-dot-com/index.html). However, after changing CSS of this template from https://code.getmdl.io/1.1.3/material.min.css into https://code.getmdl.io/1.1.3/material.<primary>-<accent>.min.css, the location of title in mobile mode is incorrectly placed.

**Comment by hebbet** [comment]
please provide an example like a jsfiddle etc.

see also [CONTRIBUTING.md#submitting-an-issue](https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md#submitting-an-issue)

**Comment by chanalex** [comment]
MDL version: 1.1.3
Browser: Mozilla Firefox
Browser version: 44.0
Operating system: openSUSE Tumbleweed
Operating system version: 20160411

What steps will reproduce the problem:
1. Simplify the template for easy testing
2. Change the material css to that with theme

What is the expected result?
The mobile title will be at the middle of the title bar.
![screenshot-2](https://cloud.githubusercontent.com/assets/2656712/14592476/ab3f35d8-0551-11e6-8108-df5c2ad43023.png)

What happens instead of that?
The mobile title appears in different locations.
![screenshot-1](https://cloud.githubusercontent.com/assets/2656712/14592477/ab3ff810-0551-11e6-96bb-d9d59ffb43b9.png)

Please provide any other information below, and attach a screenshot if possible.

**Comment by shmshd12** [comment]
Could you please provide a link to [jsfiddle](https://jsfiddle.net/) or [codepen](http://codepen.io/) showing your codes ?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
