### ISSUE TITLE
errors with lint in gulp

### ISSUE THREAD

**Issue by jlmagee** [google/material-design-lite#4278]
I get the 3 errors below when trying to build a distribution directory.  Correcting the source as indicated resolves the errors. 

This is my npm configuration [mdl_npm_ls.txt](https://github.com/google/material-design-lite/files/222709/mdl_npm_ls.txt)

[04:52:20] Starting 'lint:sources'...
[04:52:23] 
/home/jlmagee/webdev/material-design-lite/src/mdlComponentHandler.js
  232:49  error  Properties shouldn't be quoted as all quotes are redundant  quote-props
  366:51  error  Properties shouldn't be quoted as all quotes are redundant  quote-props

/home/jlmagee/webdev/material-design-lite/src/checkbox/checkbox.js
  123:5  warning  Unexpected 'todo' comment  no-warning-comments

/home/jlmagee/webdev/material-design-lite/src/icon-toggle/icon-toggle.js
  119:5  warning  Unexpected 'todo' comment  no-warning-comments

/home/jlmagee/webdev/material-design-lite/src/radio/radio.js
  133:5  warning  Unexpected 'todo' comment  no-warning-comments

/home/jlmagee/webdev/material-design-lite/src/switch/switch.js
  122:5  warning  Unexpected 'todo' comment  no-warning-comments

/home/jlmagee/webdev/material-design-lite/src/tabs/tabs.js
  88:7  warning  Do not use 'new' for side effects  no-new

/home/jlmagee/webdev/material-design-lite/src/textfield/textfield.js
  273:11  warning  Unexpected 'todo' comment  no-warning-comments

/home/jlmagee/webdev/material-design-lite/src/layout/layout.js
  520:11  warning  Do not use 'new' for side effects        no-new
  570:3   error    Block must not be padded by blank lines  padded-blocks

✖ 10 problems (3 errors, 7 warnings)

[04:52:23] 'lint:sources' errored after 2.42 s
[04:52:23] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 3 errors
[04:52:23] 'default' errored after 4.87 s
[04:52:23] Error in plugin 'run-sequence'
Message:
    An error occured in task 'lint:sources'.

**Comment by dsoldera** [comment]
I got the same error on Lint Task (after download by github) install node_modules and gulp globally.

This error is impacting the default task. Please check urgently.

**Comment by Garbee** [comment]
Please check the `mdl-1.x` branch. These were fixed a while ago in `mdl-1.1`.

**Comment by jlmagee** [comment]
Yesterday I cloned the latest 1.x branch and ran both gulp and gulp all successfully

I did try an npm update after the 1st clone but that created many errors. So, I deleted the directory and started over.

**Comment by Garbee** [comment]
> Yesterday I cloned the latest 1.x branch and ran both gulp and gulp all successfully

So it is working as expected. Closing this out since it has been fixed.
