### ISSUE TITLE
Ripple in Tabs stuck when double clicked.

### ISSUE THREAD

**Issue by Zodiase** [google/material-design-lite#4282]
![image](https://cloud.githubusercontent.com/assets/1815174/14620481/7ecd8a00-0582-11e6-9732-d7cea26f2980.png)

On any tabs with ripple, a double click would cause the ripple to stuck in place and won't fade away until the cursor moves out of the area.

Tested on latest Chrome and Safari on OS X El Capitan.

**Comment by Garbee** [comment]
The core team is focusing on V2 work and only critical internal issues are going to be handled for V1. If someone from the community would like to contribute a patch here, `mdl-1.x` is open for pull requests.

Thank you.
