### ISSUE TITLE
Clarification on resourcing of project

### ISSUE THREAD

**Issue by rj33** [google/material-design-lite#4285]
I've noticed a big slowdown in commits over the last month, with 0 updates on master , and only 2 commits on other branches. Has Google scaled back their resourcing of this project, or is this just a short term lull in activity? MDL is great, but still a work in progress in terms of full coverage of the material design spec. Is Google still committed to pushing towards as complete a coverage of MD as possible?

**Comment by Garbee** [comment]
The core team is focusing on getting V2 planned out right now. Also with I/O and other events with the team involved happening that means less time for this project right now.

V1 is effectively in a community-support place right now except for major bugs. V2 is the core teams current primary focus.

**Comment by rj33** [comment]
Thanks , that is what I was hoping to hear! Seeing the repo activity drop off sharply recently, I was worried the project had been de-resourced, glad to hear that is not the case, and that progress is being made towards V2.
