### ISSUE TITLE
Using Layout in React causes React DOM events to not work.

### ISSUE THREAD

**Issue by fisshy** [google/material-design-lite#4287]
Hi. 

Tried to use layout within my react app as a master-page and simply rendering
my components under "main".

But it looks like "mdl-js-layout" takes the Layout element and then appends it to another div.

Is there any workaround around this? 

https://github.com/google/material-design-lite/blob/master/src/layout/layout.js#L295

Epic lib btw!

Thanks

**Comment by Zodiase** [comment]
Have you tried putting another div outside of layout?

**Comment by fisshy** [comment]
I've not actually, not at home so can't try it atm.

But looking at the code. Isn't it always creating the div container ?

**Comment by tleunen** [comment]
You can use react-mdl ans the patched version of material.js to fix this particular issue ;) https://github.com/tleunen/react-mdl

**Comment by fisshy** [comment]
Yes I'm aware of that.. And I will probably end up using that. The API for your lib looks pretty clean. Thanks @tleunen

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by fisshy** [comment]
Allright @Garbee. 

But the problem was with the Material Design Lite code.

Thanks

**Comment by tleunen** [comment]
That's unfortunately the way MDL v1.x is written :s This is not a real issue for a basic usage, but with React it become an issue.
