### ISSUE TITLE
.mdl-color-border

### ISSUE THREAD

**Issue by markopaju** [google/material-design-lite#4288]
Hey guys,

I was wondering will there be a border color option as it is with background and text color?

.mdl-color-border--primary {
  border-color: rgb(63,81,181) !important; }

etc.

Second it would be great if the 
primary and accent colors/backgrounds also with the -50 .. -800 options.

I would set the label for this ticket feature request but it seems not possible.

**Comment by Garbee** [comment]
We aren't adding more generic color changing classes to 1.x. They add too much bloat to the output.

If you need this, you can add it into your own application's build pipeline.

Thank you.
