### ISSUE TITLE
Drawer menù icons

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#4295]
In the future, will be added the possibility to add some icons corresponding to the Drawer Menu items?

**Comment by Garbee** [comment]
We'll make sure it works in the V2 drawer component.  You can already handle this in v1 it may just need some custom alignment.

Closing this issue out to keep the tracker minimal for our V2 work. If someone from the community wants to contribute a way to do this to 1.x then `mdl-1.x` is open for PRs.

Thank you.
