### ISSUE TITLE
Dialog close button doesn't work in FF if dialog placed inside layout content

### ISSUE THREAD

**Issue by germn** [google/material-design-lite#4299]
http://codepen.io/germn/pen/MyBMgg
This snippet is almost same as on site, besides of layout/layout_content wrappers added.

Steps to reproduce:
1. Open snippet in Firefox
2. Click "Show dialog"
3. Click "Close dialog" (no reaction)

Tested in latest 45.0.2 FF.

**Comment by Garbee** [comment]
From the [docs](https://getmdl.io/components/index.html#dialog-section):

>  The element when using the polyfill must be a child of the body element.

Firefox uses the Polyfill, so this rules applies. Currently only Chrome and Opera have native support for the dialog element so this isn't necessary in those.
