### ISSUE TITLE
MDL not upgrading components after route changes in Angular 2

### ISSUE THREAD

**Issue by Foxandxss** [google/material-design-lite#4302]
Say I set up a button like:

```
<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
  <i class="material-icons">add</i>
</button>
```

I load my page and I get:

![](http://puu.sh/ov51W/b43375c165.png)

The button gets `data-updated` and adds a span. Ripple works fantastic.

If I go to another router and I go back to this one, I get:

![](http://puu.sh/ov53L/b96dce5eff.png)

The button doesn't get "upgraded" so I get no ripple.

So I imagine that the upgrade happens on bootstrap and changing the routes (which destroy and recreate the components) won't make MDL to upgrade the components again.

Cheers.

related: preboot/angular2-webpack#72

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by prijindal** [comment]
@Foxandxss Try This Solution: http://stackoverflow.com/a/35451821
