### ISSUE TITLE
Add support for opting in to MDL defaults without so many classes

### ISSUE THREAD

**Issue by DanTup** [google/material-design-lite#4306]
This stemmed from a [discussion on twitter](https://twitter.com/DanTup/status/724901841276907521) with @sgomes.

Let's say I have a simple page with a couple of buttons:

```html
<div>
    What game would you like to play?
    <button>Tennis</button>
    <button>Bowling</button>
    <button>Football</button>
    <button>Snooker</button>
</div>
```

I decide I want to pull in MDL (I'm no designer, and it looks pretty). The default button style looks good, but now I have to update my code to this:

```html
<div>
    What game would you like to play?
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Tennis</button>
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Bowling</button>
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Football</button>
    <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">Snooker</button>
</div>
```

Given that I just wanted the "default" buttons, this seems like quite a faff. When I create a new page, I need to go and look up what these classes are or copy and paste (will I remember them accurately? especially with the single dashes, double dashes and sometimes underscores!) and I need to ensure the whole team understands they need to do this whenever they build new pages. This feels like it goes against the idea of having styling in separate CSS.

Given that I'm going "all-in" with MDL it would be great if I could just opt-in to some sensible defaults. Ideally if CSS supported some sort of aliases, I could create my own stylesheet with something like this:

```css
button { import('mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect) }
table { import('mdl-data-table mdl-js-data-table mdl-shadow--2dp') }
ul { import('mdl-list') }
li { import('mdl-list__item') }
```

However, it seems we don't have anything like this  in the CSS specs :(
(Ahh, I'm also gonna need you to go ahead and fix this, too... ;))

It would be great if we could in some way say we're happy with a bunch of defaults to be applied to suitable tags (eg. buttons, tables, lists). Maybe by adding a class to a container:

```html
<div class="apply-mdl">
    What game would you like to play?
    <button>Tennis</button>
    <button>Bowling</button>
    <button>Football</button>
    <button>Snooker</button>
</div>
```

Or as @sgomes suggested, additional/different JS/CSS includes. I like the opt-in class, because you could put it on `<body>` if you wanted, or just `<main>` if it would interfere with other things (eg. `<li>`s in navigation).

Reducing the amount of MDL-specific classes in the HTML would also reduce coupling a little. We picked Bootstrap for our main project and now we seriously regret it. Our HTML is a mess and it'll be incredibly difficult to move away. Although you might not want people moving away from MDL, the advantages stretch to compatibility for new MDL versions too; the less that's in our HTML, the less you are unable to change without breaking compatibility.

**Comment by sgomes** [comment]
Thanks for the bug, @DanTup! Let me address some of your suggestions inline:

> Given that I'm going "all-in" with MDL it would be great if I could just opt-in to some sensible defaults. 

There are two problems with defaults, in the case of buttons (and many other components, but let's use buttons as the example).

One is that buttons have a lot of different options, and it's hard to guess what the user needs, and what would be best as a default. That said, we definitely could take a better look at the defaults we have chosen and see if they still make sense.

The other problem is that a single `<button>` tag isn't enough for everything we want to do; we'd need an inner tag or two for the ripple, at the very least. In v1, we've sometimes solved this problem by having components manipulate the DOM and adding sub-elements where needed, but this is a less-than-stellar practice we were hoping to get away from in v2 ("more boilerplate, less magic").

> Ideally if CSS supported some sort of aliases, I could create my own stylesheet with something like this
> ```css
button { import('mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect) }
table { import('mdl-data-table mdl-js-data-table mdl-shadow--2dp') }
ul { import('mdl-list') }
li { import('mdl-list__item') }```

CSS will actually support something like this with [CSS mixins](http://oocss.org/spec/css-mixins.html). It may be a good idea for us to expose some of our styles as mixins for devs using feature-enabling preprocessors like PostCSS.

> It would be great if we could in some way say we're happy with a bunch of defaults to be applied to suitable tags (eg. buttons, tables, lists). Maybe by adding a class to a container.

The problem with this approach is the JS side of things. Many components have JS bits to them that make them behave the correct way when being clicked, focused, etc. It strikes me as a bad practice to add behaviour to a component based on a class applied not to itself, but to a parent at an arbitrary number of levels above it.

> Or as @sgomes suggested, additional/different JS/CSS includes.

To expand on my suggestion here, the idea would be to pull in a different or additional set of CSS and JS that would enable that behaviour by default. That would be a stronger signal that that's really what the developer wants to do, and they're OK with MDL potentially interfering with all styles on their site.

> Reducing the amount of MDL-specific classes in the HTML would also reduce coupling a little. We picked Bootstrap for our main project and now we seriously regret it. Our HTML is a mess and it'll be incredibly difficult to move away. Although you might not want people moving away from MDL, the advantages stretch to compatibility for new MDL versions too; the less that's in our HTML, the less you are unable to change without breaking compatibility.

None of our decisions were based on lock-in; in fact, we're hoping to make v2 much more modular and customisable, so that folks can choose just the bits they're interested in, and plug them together as they see fit. We also want to reduce the impact we have on existing sites, so that nothing changes unless the developer wants it to; we'll likely be getting rid of global resets, for example, and applying them on a per-component basis to our component CSS classes.

In my opinion, having behaviours baked in actually creates a larger problem than explicitly declaring all the classes in the HTML; if a library adds styling to basic elements it may be really hard to figure out why things aren't aligning or flowing correctly after removing it, and why it's happening on parts of your site you thought had nothing to do with the library.

**Comment by DanTup** [comment]
> There are two problems with defaults, in the case of buttons _[...]_ have a lot of different options, and it's hard to guess what the user needs, and what would be best as a default.

Your docs already have pretty decent defaults as their samples. Your framework is entirely geared around making things look like material, so there really aren't that many (styling) options. Sure, some people might want shadows and some might not, but just pick one and it'll be right for a bunch of people. You may even already have style guidelines about these used across Google products?

> The other problem is that a single <button> tag isn't enough for everything we want to do; we'd need an inner tag or two for the ripple, at the very least. In v1, we've sometimes solved this problem by having components manipulate the DOM and adding sub-elements where needed, but this is a less-than-stellar practice we were hoping to get away from in v2 ("more boilerplate, less magic"; magic is inherently hard to customise or opt-out of).

It sounds like this is going to get worse for v2 then :(

> It strikes me as a bad practice to add behaviour to a component based on a class applied not to itself, but to a parent at an arbitrary number of levels above it.

It doesn't seem so weird to me, but we already do this so maybe I'm just used to it (CSS classes on containers as devs work on/test them so we don't risk breaking things globally). But if there was an option to only opt-in globally without classes for dong only part of the doc, I still think that'd be a big benefit for new projects.

IMO, things should bear as near-native as possible. When I put a checkbox in a page I don't need to tell the Browser I want tick/untick behaviour. Most people will want to use MDL define a new set of defaults for their app.

I previously thought custom html tags could solve this problem:

```html
<fancy-button>Text</fancy-button>
```

.. but last time I looked it didn't seem to play nicely (CSS didn't flow inside the template, so it didn't render as expected).

> In my opinion, having behaviours baked in actually creates a larger problem than explicitly declaring all the classes in the HTML; if a library adds styling to basic elements it may be really hard to figure out why things aren't aligning or flowing correctly after removing it, and why it's happening on parts of your site you thought had nothing to do with the library.

I think that's valid if you're pulling the library in for some small components. However, if you're pulling it in for a new project and intend to go "all in" for its styling, you just want it to be "the new default". And let's face it, it's very hard to use things like MDL/Bootstrap/etc. partially; I think most people will be going all-in or not-at-all.

It feels like we've lost sight of many of the advantages of CSS. I should be able to set my site up so that when someone builds a form with some inputs and buttons it looks like the designer intended. The team shouldn't have to explicitly re-apply the design and attach behaviour on every control they put on the page. It feels like we're moving further away from semantic HTML than towards it.

I know HTML and CSS still suck, but unless HTML pre-processors are going to become the norm I don't think we should just say 'to hell with it' and not try to keep the markup clean and terse. Every location we have to duplicate something is another place we can do it wrong, another place we need to update if it changes, another load of code that needs to be reviewed with every checkin and another load of code we need to scan through for typos when something isn't working correctly.

**Comment by tleunen** [comment]
You could use `sass` and `@extend`.
```sass
button {
    @extend .mdl-button;
}
```

**Comment by DanTup** [comment]
@tleunen There are many possibilities (especially if you're happy to pre-process), but they're all additional complications and dependencies.

I've no experience with Sass but when I just Googled to see whether you could extend classes from pure CSS files (MDL isn't written in Sass) the second result was [Why You Should Avoid Sass @extend](http://www.sitepoint.com/avoid-sass-extend/). I don't know if the post has merit but now suddenly I need to investigate Sass and decide if it's a good fit. I need to understand the implications of relying on it, what it means for developer machines, build servers and deployment scripts. What if it gets abandoned like so much of the stuff I've spent the last several years ripping out of our codebase? Or is buggy crap and doesn't get bugfixes (we already run custom forks of big projects like NHibernate because they don't fix their bugs). If I decide it's not a good fit then I need to look at another one. If it does fit, then I go to download it and I see:

> Windows
> Before you start using Sass you will need to install Ruby. 

(╯°□°）╯︵ ┻━┻

I'm not saying there aren't solutions, but suddenly just having nice Material design is looking like a chore and I'm just thinking hand-rolling my own stuff is a better choice. We should be making building web apps simpler but it feels like we're going the opposite way. We keep telling people duplication is bad and then we say you need to add 6 classes and nested tags to just render a button in the "standard" style?

Maybe I'm expecting the wrong things; maybe I don't have as much experience as the MDL devs do; maybe I just have different priorities, I don't know. I might be a minority (or even alone) but I thought it was worth sharing my thoughts even if they don't go anywhere :)

**Comment by toddmbloom** [comment]
The main thing I didn't like about MDL (forgive me) was that it was seemingly built for SASS but didn't take advantage of mixins or functions. I get that you want to have it usable out of the box, which is fun, but including grid, buttons, etc. as mixins or functions would go a long way to reducing the amount of class bloat.

**Comment by Garbee** [comment]
Closing this out as moving towards a classless model isn't something viable for a project like this. Developers should be very conscious of what they have when directly targeting elements. We shouldn't complicate things any further. As we are moving to a more modular approach, we won't have any direct element targets in V2.

Developers can handle this within their own projects if they want to avoid classes. That way the implications are understood when implementing it for your projects.

Thank you.
