### ISSUE TITLE
mdl-menu-- should check viewport boundaries before displaying

### ISSUE THREAD

**Issue by leifoolsen** [google/material-design-lite#4308]
MDL version: 1.1.3
Browser: Chrome
Browser version: Latest
Operating system: OSX
Operating system version: Latest

What steps will reproduce the problem:
1. Code a menu, e.g.
```html
<button id="demo-menu-lower-left-30" class="mdl-button mdl-js-button mdl-button--icon">
  <i class="material-icons">more_vert</i>
</button>
<ul class="mdl-menu mdl-menu--bottom-left mdl-js-menu mdl-js-ripple-effect" for="demo-menu-lower-left-30">
  <li class="mdl-menu__item">Some Action</li>
  <li class="mdl-menu__item">Another Action</li>
  <li disabled class="mdl-menu__item">Disabled Action</li>
  <li class="mdl-menu__item">Yet Another Action</li>
</ul>
```
Narrow the browser window so that the menu button is close to bottom of the wiewport.

What is the expected result?
The menu component should check the client rect and adjust it's position so all items in the menu is visible in viewport. This is the standard behaviour of e.g. the select element.

What happens instead of that?
Menu is clipped

Please provide any other information below, and attach a screenshot if possible.
![screen shot 2016-04-26 at 22 15 32](https://cloud.githubusercontent.com/assets/10088486/14833224/7b50a6d2-0bfe-11e6-906b-710801e9b3f3.png)

**Comment by Garbee** [comment]
Users changing the viewport isn't exactly a common scenario in most cases (orientation change aside.) That combined with the fact that this is an MDL 1.x issue and the team is focusing on V2, we won't be addressing this internally as it is non-critical.

If someone from the community can fix this in a non-breaking way, `mdl-1.x` is open for PRs.

Thank you.
