### ISSUE TITLE
Snackbar hide method

### ISSUE THREAD

**Issue by Whiteseeker** [google/material-design-lite#4310]
It would be nice for the [snackbar](https://getmdl.io/components/index.html#snackbar-section) to have a way to hide it once the user click on the button. Something like:

snackbarContainer.MaterialSnackbar.hideSnackbar(scnebarElt);

**Comment by Garbee** [comment]
This actually can get hairly to handle properly with the queue system. Things are already off-stack with the timer that will need to be canceled to speed up the queue if something else is on it. Implementing this kind of function in 1.x isn't something the core team will take on. If anyone from the community would like to handle it then `mdl-1.x` is open to pull requests.

Thank you.

**Comment by iandoesallthethings** [comment]
It's not yet in the official release. Does anyone know when this method will be deployed?
