### ISSUE TITLE
No header class for navigation drawer?

### ISSUE THREAD

**Issue by rejhgadellaa** [google/material-design-lite#4313]
I'm having trouble to find anything on how to use a header for the navigation drawer (as shown in the picture below, taken straight from [Material Design Navigation drawer](https://www.google.com/design/spec/patterns/navigation-drawer.html#) documentation.

Am I just using the wrong search keywords or is this not yet implemented?

![patterns_navdrawer_behavior_temporary2](https://cloud.githubusercontent.com/assets/4703109/14911907/d8542ccc-0df8-11e6-9dd3-f5979c93de31.png)

**Comment by Garbee** [comment]
Superseded by #4476.

We'll try to address this when implementing the drawer for V2.

Thank you.
