### ISSUE TITLE
Support for ShadowRoots

### ISSUE THREAD

**Issue by rianby64** [google/material-design-lite#4314]
Hello! Please let's check the PR #4300 
Currently I'm writing a simple interface based on custom elements. The concept about ShadowRoots is amazing, but I see material-design-lite still doesn't support shadow roots, more precisely, it doesn't upgrade shadowRoots document-fragments.

Hope that PR will be useful.

**Comment by Garbee** [comment]
We recommend Polymer for people building projects using Web Components. We can try to take a look into making sure this kind of thing is supported in future releases, but it won't be added to `mdl-1.x`.

Thank you.

**Comment by rianby64** [comment]
Thanks a lot @Garbee I got it )) I'll read more about Polymer.
