### ISSUE TITLE
MDL in Google Apps Script does not scroll on iOS 9.3.1

### ISSUE THREAD

**Issue by SergeRGravelle** [google/material-design-lite#4318]
I have used successfully the MDL framework in a web application implemented throught the Google Apps Script environment. It works well through chrome on desktop and android. When accessing the application through safari on iOS 9.3.1, there is an issue: the content does not scroll. The same web app worked well on an older version of iOS.

Here is the code illustrating the issue, using demo code from getmdl.io 

**Code.gs :**
```
function doGet(e) {
  var template = HtmlService.createTemplateFromFile('Index');
  return template.evaluate()
      .addMetaTag('viewport', 'width=device-width, initial-scale=1')
      .setSandboxMode(HtmlService.SandboxMode.IFRAME);
}
```
**Index.html :**
```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.getmdl.io/1.1.3/material.min.js"></script>
    <link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Title</span>
        </div>
      </header>
      <main class="mdl-layout__content">
        <div class="page-content"> 
        <p> Main page - text that should scroll
 		 <? for (var i=0 ; i < 25; i++) { ?>   <p>Item <?=i ?> </p>   <? } ?>
        </div>
      </main>
    </div>
  </body>
</html>
```

You can try this [published version](https://script.google.com/macros/s/AKfycbxrbg41gL4DG1r45ChMMpOy-0AK04ywZUIhBQ6Dv-cfxdj0ZYXT/exec) of the code above.

When executing the web app in chrome on a desktop or android, you can scroll the main content up and down.
When executing it from Safari on iOS 9.3.1 device (iPhone 5, iPad), the main content does not scroll.

If you deploy the index.html in a standard environment (see [example in codepen](http://codepen.io/sergergravelle/pen/LNXYpG)) it works well on iOS 9.3.1   I therefore conclude the issue has to do with the combination of MDL in Google Apps Script environment.

Using MDL framework within Google Apps Script helps build simple, beautiful web applications.... if this issue can be fixed.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
