### ISSUE TITLE
DataTable: data-mdl-data-table-selectable-name & data-mdl-data-table-selectable-value don't work at all

### ISSUE THREAD

**Issue by MathieuDerelle** [google/material-design-lite#4320]
You've forgot to implement your own specs ?

https://getmdl.io/components/index.html#tables-section 

Here's a fiddle with exactly the code given 
https://jsfiddle.net/t24kszqy/

and checkboxes are not customized at all

**Comment by Garbee** [comment]
The docs have been updated to remove that mention and are simply waiting for the next deploy.

The functionality was added, but then we decided to [deprecate the data table JS](https://github.com/google/material-design-lite/wiki/Deprecations#automatic-selection-checkboxes) that we provide. The code for it was removed and most of the docs, but I missed removing one area and it made it live by accident.

Please follow the deprecation guide for doing checkboxes in a way that allows developers much more control over what is going on.

**Comment by MathieuDerelle** [comment]
Thanks !
