### ISSUE TITLE
MDL Menu Hover specs

### ISSUE THREAD

**Issue by triplekdev** [google/material-design-lite#4321]
Hi,

I would like to see this in MDL as included:

    .mdl-hover__color--<color-pallete>-<palette #>
    .mdl-hover__color--text-<color-pallete>-<palette #>

or

    .mdl-hover__accent
    .mdl-hover__accent-text-color

Thanks!

**Comment by Garbee** [comment]
We aren't going to be adding more color classes en-mass to the codebase. They add too much bloat.

Thank you.
