### ISSUE TITLE
How to change drawer button color

### ISSUE THREAD

**Issue by JonatanSalas** [google/material-design-lite#4322]
Hi guys, I have a question, there is a way to change the color of the hamburguer icon from navigation drawer?
I have been expending a lot of with time not good results. Hope you can help me!

**Comment by Zodiase** [comment]
![image](https://cloud.githubusercontent.com/assets/1815174/14977967/3da74464-10de-11e6-82bf-c45d4614b84b.png)

Is this what you want?

**Comment by JonatanSalas** [comment]
Yes! Thanks!

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
