### ISSUE TITLE
Documentation needed for switch on off

### ISSUE THREAD

**Issue by alvarotrigo** [google/material-design-lite#4327]
It is provided in other components such as the slider:

>  Note: Although the value attribute is used to set a slider's initial value, it should not be used to modify the value programmatically; instead, use the MDL change() method. For example, assuming that slider1 is a slider object and newvalue is a variable containing the desired value, do not use slider1.value = newvalue; instead, use slider1.MaterialSlider.change(newvalue)

But totally omitted in the switch component.

```javascript
$('#demo').get(0).MaterialSwitch.on();
$('#demo').get(0).MaterialSwitch.off();
```

Although I would also add another one as in the slider for a more easier coding based on a variable:

```javascript
$('#demo').get(0).MaterialSwitch.change(true);
$('#demo').get(0).MaterialSwitch.change(false);
```

**Comment by Garbee** [comment]
We are overhauling the JS API in V2 and the V1 site/docs are in a maintenance/critical-only support mode from the core team. If someone from the community would like to contribute a patch for adding this, `mdl-1.x` is open for PRs.

Thank you.
