### ISSUE TITLE
MDL - Green color Custom CSS theme

### ISSUE THREAD

**Issue by edicarloslds** [google/material-design-lite#4332]
Hello,

I'm trying to use color green generate by "Custom CSS theme", but the result is not same that is in pallette.
![capturar](https://cloud.githubusercontent.com/assets/14222756/15124561/0e2e59f4-15ff-11e6-8477-2bd601705cdc.JPG)

**Comment by Zodiase** [comment]
There are way more than 2 colors in each theme; all of them are derived from the two main colors, with added/reduced brightness/saturation. The FAB in the preview is not using the exact `accent` color you are picking. But components using the exact `accent` color, buttons with `mdl-button--accent` for example, should match the `accent` color you picked, I believe.

**Comment by Garbee** [comment]
We are currently working on a complete rewrite for V2. The team won't be taking any action here for V1. If someone wants to track this down and submit a patch to `mdl-1.x` then it is open for PRs.

Thank you.
