### ISSUE TITLE
Custom Elements in Dart

### ISSUE THREAD

**Issue by eukreign** [google/material-design-lite#4333]
I realize this may be a bit controversial but has the MDL team considered implementing the JS portions of MDL in [Dart](https://www.dartlang.org) instead?

Using plain `dart:html` along with the [`web_components` polyfill](https://pub.dartlang.org/packages/web_components) would make Custom Elements available within MDL and as a result there won't be a need to re-invent the wheel with something like the [mdl-component-design-pattern](https://github.com/jasonmayes/mdl-component-design-pattern). When more browsers add native support for Custom Elements, MDL will instantly be able to take advantage of that.

This will have some semantic advantages as well, the button tag will change from:

```html
<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
  Button
</button>
```

to:

```html
<button is="mdl-button" class="mdl-button mdl-button--raised mdl-js-ripple-effect">
  Button
</button>
```

Maybe you can even drop the `mdl-button` class in favor of just selecting on the `[is=mdl-button]` in the CSS:

```html
<button is="mdl-button" class="mdl-button--raised mdl-js-ripple-effect">
  Button
</button>
```

When skimming HTML it will be very easy to tell which elements are plain and which have some code behind them.

In browsers that support Custom Elements, such as Chrome and Opera, there would be an immediate performance boost. [Other browsers](http://caniuse.com/#search=registerelement) are in the process of adding Custom Elements.

As far as why Dart, I'm not going to try and sell a Google technology back to Google, I think this choice is self evident :smile:

Also, I am aware of the [Dart port of Material Design Lite](https://github.com/MikeMitterer/dart-material-design-lite) but this port stays true to the original MDL implementation and does not use Custom Elements. My proposal is primarily about using Custom Elements and secondarily about Dart (which includes [`document.registerElement()`](https://api.dartlang.org/1.12.0/dart-html/HtmlDocument/registerElement.html) as part of the standard `dart:html` API).

**Comment by Garbee** [comment]
As it is, we currently are not looking to any alternative languages to use for the source. In V2 we are looking at going to ES6 JS and making a more modular component system using that.

The goal here is to stay as close to what runs in the browser as we can. This makes debugging easier for us and users. Further it means we have the widest audience of developers able to help contribute instead of only a subset of developers who know Dart.

**Comment by eukreign** [comment]
You addressed the question of Dart but my proposal was primarily about Custom Elements.

Is there a reason that MDL team has decided to implement their own component system instead of using HTML5 Custom Elements?

The polyfill for Custom Elements is very mature and used by many other projects:
http://webcomponents.org/polyfills/

Chrome and Opera already support Custom Elements natively.

Firefox has an implementation which can be enabled and would presumably be on by default eventually:
https://developer.mozilla.org/en-US/docs/Web/Web_Components#Enabling_Web_Components_in_Firefox

WebKit/Safari has completed a prototype and moving to final implementation:
https://lists.webkit.org/pipermail/webkit-dev/2016-March/027995.html

IE states that they will likely implement it:

> Roadmap Priority: Medium — Development is likely for a future release.

https://developer.microsoft.com/en-us/microsoft-edge/platform/status/customelements

**Comment by Garbee** [comment]
Custom Elements are still very early and won't have wide support for a while. Overall, we are sticking with our current implementation structure to keep things simple for developers. Custom Elements will be investigated as their usage and support grows in end-user browsers.

I'm currently building custom MD inspired components using Web Components for an internal project. While I'm excited about the opportunities Web Components provides, we discussed the move to them before and things are still too new for us to dive into building and supporting. It would require a polyfill of the Shadow DOM API (which currently is only V0 until Chrome ships the V1 API) and add extra architectural overhead to end-users to make sure things work properly. To minimize the amount of documentation and support that developers will need using V2, Web Components aren't a solid choice for us.

**Comment by eukreign** [comment]
So, you're saying that the component framework you are still building/just built is going to be more mature than the Custom Elements polyfill that's used by Polymer and Mozilla's X-Tag frameworks?

And I didn't understand what Shadow DOM has to do with any of this. I'm only talking about the Custom Elements polyfill. I'm not suggesting that you use all of the polyfills in the webcomponents.org package. To the contrary, I would suggest that *only* Custom Elements polyfill be used and that the Shadow DOM, HTML Imports and all of the other polyfills be ignored for now.

This would let MDL team focus on actual MDL related tasks, you would be building on a well documented and HTML5 spec'd technology and already benefiting on browser that natively support this with the other browsers coming soon. Seems like a win, win, win situation to me.

Implementing your own, non-standard, component architecture that you then have to maintain and document seems counter productive and outside the scope of MDL.

**Comment by Garbee** [comment]
We are moving to just supplying CSS classes and JS objects that developers instantiate on their own. Possibly with some automatic help from a helper thing. Simple, straightforward, and easy for developers to understand and integrate.

The Custom Elements polyfill itself still requires extra architecture overhead in planning and building out an application. Since you'd need to wait for the initialization event to do your custom logic. This is something we are trying to avoid needing to explain and support developers with.

Custom Elements (and Web Components in general) are **very** promising. However, for the foreseeable future they aren't in alignment with what this project can handle integrating, educating, and supporting developers with.
