### ISSUE TITLE
Tooltip in drawer not visible only in firefox

### ISSUE THREAD

**Issue by cirdes** [google/material-design-lite#4335]
MDL version: 1.1.3
Browser: Firefox
Browser version: 45.0.2
Operating system: OSX
Operating system version: 10.11.4 

Hi, 
I have a menu with icons on a drawer and each icon has a tooltip. In Chrome or Safari the tooltip is in the right position as expected but in Firefox it is not visible.

<img width="267" alt="screen shot 2016-05-10 at 8 02 52 pm" src="https://cloud.githubusercontent.com/assets/727781/15165199/511b490c-16ea-11e6-994d-a4eaf231dd27.png">

Codepen: https://codepen.io/cirdes/pen/QNodEp

It is possible to be related with "position: fixed;" of mdl-tooltip. If I inspect the element and disable and enable again the "position: fixed" property the tooltip become visible.

**Comment by markopaju** [comment]
Hey,

Its the .mdl-navigation and its flex box.

In your case might be something like this:

``
.ev-user-menu__nav {
    display: block !important;
    padding-top: 0 !important;
    margin-left: 27px;  
}

.ev-user-menu__link {
    padding: 9px 12px !important;
    color: #424242 !important;
  display: inline-block !important;
}
``

**Comment by cirdes** [comment]
@markopaju it didn't solve the problem, the bug is only in firefox.

I don't think that is a flexbox problem because it is happening on lasted firefox version...
<img width="1025" alt="screen shot 2016-05-11 at 9 23 06 am" src="https://cloud.githubusercontent.com/assets/727781/15180785/0da8a654-175a-11e6-88d3-2640bfb04a60.png">

**Comment by lyngbach** [comment]
Not sure what actually causing it but you we had similar problem with one of our applications and we solved it by taking the mdl-tooltip div out of the header. 

In your codepen, I took one of the tooltips out of the aside and it started showing up in Firefox. Sorry for no updated codepen.. I suck at that codepen stuff..

**Comment by cirdes** [comment]
@lyngbach, thanks man! Moving the tooltip out of header solve my problem too. 😃

**Comment by Garbee** [comment]
The core team is working on a complete rewrite for V2 currently. As such we won't be taking any action here. It seems like this is also related to other tooltip issues in certain display contexts as well, which can't be solved without completely rewriting the tooltip styling.

Thank you.
