### ISSUE TITLE
getmdl.io down

### ISSUE THREAD

**Issue by enesunal** [google/material-design-lite#4336]
I tried to check some documentation on getmdl.io website, but it seems the website is down as the time this issue submitted.

**Comment by Garbee** [comment]
Working here...

Where are you located roughly? Could be a regional thing.

**Comment by enesunal** [comment]
Located in Turkey, there is no problem with other websites (google's). When I ping, the IP address I got is: 216.239.32.21

**Comment by Garbee** [comment]
cc @crhym3 

Alex may know how to debug these kinds of things further. Not much I can do here without a VPN coming out of Turkey to test myself with (and hoping it has the same network conditions you're facing.)

**Comment by crhym3** [comment]
nice try :)
