### ISSUE TITLE
Responsive Material Framework not properly supported by Firefox

### ISSUE THREAD

**Issue by vaishnavmhetre** [google/material-design-lite#4353]
The **Responsive Framework of Mdl** is **not properly supported by Firefox.**

Below is the comparison of Firefox and IE response where IE view seems better

![firefox responsive material issue - github](https://cloud.githubusercontent.com/assets/14543290/15272693/22a4b898-1a9f-11e6-963e-54ab5ad89a03.png)

**Firefox gives a bit zoom in view** whereas **IE gives perfect output**. Need quick bug fix

**Comment by Garbee** [comment]
Can you please provide a [codepen](http://codepen.io) which reproduces this problem with a minimal example?

Debugging rendering issues off screenshots is extremely difficult. There isn't much we can do with this issue as it is.
