### ISSUE TITLE
checkbox does not contain checkmark

### ISSUE THREAD

**Issue by musicformellons** [google/material-design-lite#4356]
I attached the look of the checkbox which is just plain blue, so no checkmark. Other material icons are appearing ok. I checked whether any custom css overwrites anything label, checkbox connected but does not appear to be so...

Any idea?

![screenshot from 2016-05-18 11-20-04](https://cloud.githubusercontent.com/assets/10334123/15354701/26bdbbf8-1cef-11e6-8c60-3feed96e0b15.png)

**Comment by Garbee** [comment]
Can you please provide a [codepen](https://codepen.io) that reproduces the problem? Or is the page in question hosted publicly where we are able to view it? Further, what browser and OS are you running this on?

Thank you.

**Comment by musicformellons** [comment]
I made a codepen but can not reproduce it there...; I am on ubuntu gnome 16.04 and it happends in both Chrome (Version 50.0.2661.102 (64-bit)) and Firefox. Where do I look?

**Comment by Garbee** [comment]
If you can't make a reproducible sample on codepen then there are any number of things that could be in the way. Helping figure that out isn't something we can handle here. Try asking on [StackOverflow](https://stackoverflow.com) for support and integration assistance.

**Comment by musicformellons** [comment]
@Garbee I found it does not occur when using this link:
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">

But I get the problem building with webpack from scss. Other scss comes through ok.

**Comment by Zodiase** [comment]
You might want to make sure (the three image files)[https://github.com/google/material-design-lite/tree/master/src/images] are accessible with the correct url. One of them, the check mark, is used for displaying the, well, check mark in check boxes.

**Comment by musicformellons** [comment]
@Zodiase @Garbee The svg's are in the right place. I did notice that when building with either one of these two I do get the proper checkmark:
import '../../node_modules/material-design-lite/.tmp/material-design-lite.css';
import '../../node_modules/material-design-lite/material.min.css';

However when I use the scss one (which is the one I obviously need):
import '../../node_modules/material-design-lite/src/material-design-lite.scss';

I get the bug.

**Comment by Zodiase** [comment]
@musicformellons By any chance you could double check the compiled css file and see if the check mark file is accessible?

Alternatively you could open the inspector and check for this:
![image](https://cloud.githubusercontent.com/assets/1815174/15374183/afdc56c8-1d0e-11e6-8a46-0c377b93c1bc.png)

`.mdl-checkbox.is-checked .mdl-checkbox__tick-outline` should have a usable background image.

I could get a similar result you showed in OP by:
- Deleting the background image on `.mdl-checkbox.is-checked .mdl-checkbox__tick-outline`,
- Disabling the mask on `.mdl-checkbox__tick-outline`.

![image](https://cloud.githubusercontent.com/assets/1815174/15374236/e20e5f06-1d0e-11e6-8efa-82a1143c547e.png)

**Comment by musicformellons** [comment]
@Zodiase I do get a path but it seems incorrect (when I use a working checkbox the tick.svg appears when hovering over the pathlink). I attached my output. What should the path be?
![screenshot from 2016-05-18 23-16-02](https://cloud.githubusercontent.com/assets/10334123/15375482/9ad70b4c-1d4f-11e6-8981-68061144157b.png)

**Comment by Garbee** [comment]
> But I get the problem building with webpack from scss.

This indicates there isn't a problem with what we provide but instead your build process. We simply can't handle support within this issue tracker, it becomes too much work to maintain and handle all that. StackOverflow is a *far* superior platform to get support through and is more easily searchable then GitHub Issues.

**Comment by musicformellons** [comment]
Yes, it is a webpack with svg issue, will try to solve via stackoverflow. Thanks.
