### ISSUE TITLE
Strange behavior when add textfield component via javascript

### ISSUE THREAD

**Issue by 3mp3ri0r** [google/material-design-lite#4360]
The textfield add via javascript can not do floating text and don't have "is-upgraded" class.

Demo: http://codepen.io/3mp3ri0r/pen/jqjBjx

**Comment by Garbee** [comment]
You don't upgrade the input element itself. You upgrade whatever the container is with `mdl-js-textfield` applied to it. Also, it is best to upgrade after components are attached to the DOM just in case anything funky is going on.

Integration assistance is best provided on StackOverflow. If you are still unable to figure out how to get this working then please post there as this tracker is only for issues with the code MDL provides.

Thank you.
