### ISSUE TITLE
Firefox get different render for dropdown

### ISSUE THREAD

**Issue by 3mp3ri0r** [google/material-design-lite#4361]
Firefox browser (linux and widows) false render dropdown. I've try in chrome (linux and windows) and edge, they render it correctly.
Demo: http://codepen.io/3mp3ri0r/pen/bpPWax

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
