### ISSUE TITLE
multi level tab control

### ISSUE THREAD

**Issue by seematalanki** [google/material-design-lite#4374]
Hi,
We have requirement where in we need nested tabs. We tried doing it but getting 2 scroll bars.
The way it is implemented is
1. outer tab is using mdl-layout__tab-bar .
2. inside mdl-layout__content , we have send level tab which is using mdl-tabs mdl-js-tabs.

Provide us a sample for this usecase.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
