### ISSUE TITLE
Mini Footer is mis-sized in Chrome

### ISSUE THREAD

**Issue by CAD97** [google/material-design-lite#4376]
([A question asking for a workaround was posted on StackOverflow, which includes a minimal test case.](http://stackoverflow.com/q/37427956/3019990))

In Chrome, a very large content in the `main.mdl-layout__content` block will cause the `footer.mdl-mini-footer`'s height to shrink to the point that its content is larger than the footer itself. This behavior does not occur in Firefox or Microsoft Edge.

This does not seem to occur with the `mdl-mega-footer`.

Layout of reproducing case:

```
<div class="mdl-layout__container">
  <div class="mdl-layout mdl-js-layout">
    <main class="mdl-layout__content">
      <!-- 20 paragraphs of lipsum <p> elements -->
    </main>
    <footer class="mdl-mini-footer">
      <img height="32" src="https://raw.githubusercontent.com/CAD97/SO-resources/9ca92a11babb0766580e511d8473b960c040cc91/01/github-32x32.png">
    </footer>
  </div>
</div>
```

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
