### ISSUE TITLE
Standard Label does not show in expandable text field

### ISSUE THREAD

**Issue by sabrinaluo** [google/material-design-lite#4377]
Hi, 
I noticed that the **standard label** does not show. Is it supposed to show or not?

Demos are here: https://codepen.io/hiitea/pen/oLvbzM
- click the first :mag: , floating label shows as expected
- click the second :mag: , standard label does not show

when put below css in, the standard label shows.
```
.mdl-textfield__expandable-holder .mdl-textfield__label{
  top:3px;
}
```

**Comment by Garbee** [comment]
It isn't supposed to show. Floating labels show the label after editing and standard labels disappear when editing. This is per the Material Design specification on how textfields should operate.

The expandable bit is an implementation-specific work-around to a certain problem. It shouldn't be in core... but, it happened by accident.

**Comment by etale-cohomology** [comment]
> standard labels disappear when editing

Yes, but the standard label is *not* showing *at all* (even when there's *no* editing), unless one includes the CSS that the OP specifies.
