### ISSUE TITLE
How can I validate using HTML 5 validation provisions only upon user interaction or submission?

### ISSUE THREAD

**Issue by thecoffeehog** [google/material-design-lite#4389]
I just want to validate the fields only when user interacts with the field or submits the form.

Below is the code I am using:

```
 <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" type="text" name="titleOfTheEmailField" id="titleOfTheEmailField" onchange="updateTitle()" required>
    <label class="mdl-textfield__label" for="sample3">Title...</label>
</div>
```

Here is the output:

[![enter image description here](http://i.stack.imgur.com/WkroN.png)](http://i.stack.imgur.com/WkroN.png)

But I want this output only after the user interacts with the field or submits the form.

**Comment by Garbee** [comment]
This is proper by HTML5. We are using the built in validation methods that function this way.

There is no intermediate state (yet) in browsers to work from. So we decided to deal with what HTML5 provides even if it goes against a part of the MD spec for simplicity over recreating validation handling and more sophisticated dirty-state checking ourselves.

If you want something else, then you'll need to build your own JavaScript component to handle this.

**Comment by thecoffeehog** [comment]
Thanks a lot for the information @Garbee. Will try to implement the needed functionality using some JavaScript.
