### ISSUE TITLE
MDL - Card Title Div

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#4409]
This is not a help question - I know how to get the result that I want.  My question, or concern, is the `mdl-card__title` div seems like it should default to block display, automatically putting the title text and sub-title text on unique rows.  However, setting the outer title div to display block requires me to override MDL with the `!important` declaration.

..Just thought I would put this out there.  Seems like block would be the default.

[Here's the sample on codepen](http://codepen.io/rhroyston/pen/JKYpZL?editors=1100).

.mdl-card__title{
  display:block !important;
}

**Comment by Garbee** [comment]
I'm addressing this in V2. It is slightly more complicated than just changing the display type to align to MD.

**Comment by Bwc84** [comment]
Thanks man I'm new. I own a business in commercial high-rise window cleaning and I fell in love with this so I'm going to need as much help and support as I can get

**Comment by Garbee** [comment]
Sergio implemented the initial v2 cards already. This problem is addressed in that cleanly.

Thanks for the report.
