### ISSUE TITLE
[Component Request] Full Screen Dialog

### ISSUE THREAD

**Issue by b-kelly** [google/material-design-lite#4412]
The full screen dialog is similar to the dialog, except it takes up the full screen on mobile devices. These are perfect for operations too complex for a normal dialog, such as forms, etc.

https://material.google.com/components/dialogs.html#dialogs-full-screen-dialogs

**Comment by b-kelly** [comment]
I actually have the code for these all ready, just need to write up documentation if it is decided that these are a good fit for mdl.

The only issue is the lack of a spec for desktops, but I've made mine to be the width of a mobile device (to great success). I find that these work exceedingly well on the desktop as well as on mobile when implemented correctly.

**Comment by Garbee** [comment]
I don't see a compelling use-case for full-screen dialogs on web applications. It seems like something that a page would be for. Also, they are mobile-only according to the spec, so they wouldn't exist on desktops. This kinda works against responsive design.

I think this is a part of the specification best left out until a compelling use-case is provided and we get guidance on how this should be applied to web and tablet/desktop interaction.

**Comment by b-kelly** [comment]
I see where you are coming from, but I disagree. I'm finding a lot of use on these for forms for adding content when I don't want to leave the page. I actually originally had the forms on separate pages (as you suggest), but found that they work much better as a dialog, especially when you can send the request off as an ajax call and update the page in place with the response.

I agree with guidance needed though, as I feel the spec was short sighted on declaring these mobile only. They work exceedingly well on desktop and are very responsive.

I do have some examples if you'd like to try it out, but the site they are on is currently closed to the public due to active development / user testing and a really obvious security flaw that needs closing before going public.

I've attached an example image with some dummy data to showcase what I'm using it for.

![full-screen-dialog-desktop](https://cloud.githubusercontent.com/assets/14169651/15880550/92bc1706-2cfc-11e6-935d-cddb4ab2c58b.png)

**Comment by Garbee** [comment]
Just read the spec again, now I get it. Full-screen dialogs are used on mobile where normal dialogs are shown on desktop/tablet.

So, all we really need to handle is creating a modifier and adding toolbars into V2 and together that should handle this use-case elegantly. Developers will just be left to add animations if they want them for mobile.

**Comment by b-kelly** [comment]
I'm actually piggy-backing off the existing dialog here, I haven't added any extra JS (just styles). Media queries take care of the mobile case.

What do you mean when referring to "adding toolbars into V2"? Is there something in the spec I've missed?

**Comment by Garbee** [comment]
[Toolbar spec](https://material.google.com/components/toolbars.html#). Pretty straightforward spec to integrate, but need to test it within V2's components to make sure it works seamlessly.

Basically, this makes the upper part of a full-page dialog. Then on desktop it should be hidden and the normal dialog title and actions would replace it.

**Comment by b-kelly** [comment]
Ah, I see, that's for the mobile only version. Maybe its too early to ask, but how exactly would this work with the dialog? On some pages I have multiple potential dialogs and I'd hate to have to code 3 dialogs with 3 toolbars and swap the toolbars out with JS along with the dialog. I'd personally much rather just add a drop shadow to the title bar on mobile since the bar will never change and the layout is set via the spec.

**Comment by Garbee** [comment]
How it would work in details is up to you. We just provide the pieces to make the UX possible.

**Comment by Garbee** [comment]
This issue is superseded by #4486.

However, full screen on Desktop is not specified, it will be restricted to mobile-only most likely. Will decide when implementing it and discussing with the team what to do specifically.

**Comment by osechet** [comment]
A good example of "full-screen" dialog is visible in the Google calendar application on Android. When you add a new event, a dialog opens to fill the details. It's also a good way to see how it can be used on desktop.

On a device with a small screen, the full-screen dialog fills the screen:
![fullscreen-nexus4](https://cloud.githubusercontent.com/assets/462377/17100540/4c109546-526f-11e6-8e82-ddbc13e1c128.png)
*Nexus 4*

But on a device with a larger screen, the dialog does not fill the screen horizontally or vertically (depending on the screen orientation and the screen size):
![fullscreen-nexus10-portrait](https://cloud.githubusercontent.com/assets/462377/17100554/6cf88872-526f-11e6-8eed-9bd89e6c258f.png)
*Nexus 10 (portrait)*

![fullscreen-nexus10-landscape](https://cloud.githubusercontent.com/assets/462377/17100564/75725398-526f-11e6-88eb-70f5b19f0a11.png)
*Nexus 10 (landscape)*

![fullscreen-nexus7-portrait](https://cloud.githubusercontent.com/assets/462377/17100575/80a594d2-526f-11e6-8e3e-61bf245c5f4d.png)
*Nexus 7 (portrait)*

![fullscreen-nexus7-landscape](https://cloud.githubusercontent.com/assets/462377/17100603/b73e1cbc-526f-11e6-8bc2-64a29ed0bb03.png)
*Nexus 7 (landscape)*

**Comment by Garbee** [comment]
Other apps don't set the specification. The specification itself does and different teams do different things to make their UX's work. Until the specification itself says something (or we have it direct from the MD team how something will be specified) we only implement what is in-writing, otherwise it isn't Material Design.
