### ISSUE TITLE
mdl header placed scroll bar under it rather than its right side. 

### ISSUE THREAD

**Issue by vince8864** [google/material-design-lite#4413]
Right now, the header will put the scroll bar under it rather than its right side. Every Time a page loads, the scroll bar will appear at default position (right side along with the browser) at first then move to the bottom of the header. This behaviour causes the whole webpage to move left and right for a second. Any simple solution to fix this?

Remove position:absolute from mdl-layout__container seem to fix this but the header is no longer sticky

**Comment by Garbee** [comment]
This is a side-effect of how the layout component was implemented for 1.x. There is no solution to it. In V2 the layout component is being broken down and completely rebuilt which will solve this.

Thanks for the report, but there is nothing we can do in 1.x to address this and preserve compatibility.
