### ISSUE TITLE
Spinner loading animation doesn't show when HTML is added through Javascript

### ISSUE THREAD

**Issue by zachrattner** [google/material-design-lite#4415]
If I put this code in my HTML, I see the loading animation no problem: 

`<div class="mdl-spinner mdl-js-spinner is-active"></div>`

But if I add it to the page through Javascript, it just shows up as "Loading..." text. Is there Javascript I need to call to stylize it?

**Comment by Garbee** [comment]
You need to update the element using the component handler. `componentHandler.upgradeElement(ref)` where `ref` is the variable that contains the node with `mdl-js-*` elements.

**Comment by Garbee** [comment]
Yes, this is oddly documented only in the "getting started" area where we cover one specific component in a sample. This is all being addressed in V2 so things are clearer and more explicit for JS developers.

**Comment by zachrattner** [comment]
Awesome, thank you for the fantastic support!

**Comment by tinyweasel** [comment]
I'm trying to do this within an Ember JS function like so:

 `componentHandler.upgradeElement($('.mdl-js-spinner'));` 

and getting the error:

> "Invalid argument provided to upgrade MDL element." 

Any ideas how to fix?

**Comment by M-Beliaev** [comment]
@tinyweasel , you are putting an array of elements instead of one element. Try:
```javascript
componentHandler.upgradeElement($('.mdl-js-spinner')[0]);
```
It will set a first element from the selected list.
