### ISSUE TITLE
Can't override certain variables

### ISSUE THREAD

**Issue by bmfay** [google/material-design-lite#4416]
Certain variables (e.g. $input-text-bottom-border-color) are overridable, whereas others are not (e.g. $input-text-font-size, $input-text-padding, etc).

My app.scss is structured as recommended (I set all variables before importing material-design-lite source).  I'd noticed this on a previous project but tried to work around it, but this is a fresh project and I'm perplexed.

**Comment by Garbee** [comment]
Make sure you are using the latest version (1.1.3 currently.) These are set to `!default` in the source so if your structure is correct then it should work. Do remember though, some of the variables have calculations done on them, so if you get proportions incorrect then things can get weird. Particularly with animations when something is re-positioned (like textfield floating labels.)

If things still aren't working, then StackOverflow is probably the best solution to get help with your build process. Supporting those is not something we can handle here.

**Comment by bmfay** [comment]
Updating to latest version resolved the issue, thanks!
