### ISSUE TITLE
non dissmissible Dialogs

### ISSUE THREAD

**Issue by appunnicer13** [google/material-design-lite#4418]
Can we have addition options on dialogs which are non dissmissible , please give opinion on this .

**Comment by Garbee** [comment]
Is this specified by Material Design? I don't recall seeing it in the specification.

In my opinion, dialogs should *always* have a close option. Too much abuse can happen otherwise which isn't good for end users.

Whether you provide a close button or not is up to you, but they can still be closed via developer consoles if a user knows to do that.

**Comment by appunnicer13** [comment]
infact it is provided in the specification , but the enforcement is the problem . Because esc key closes it of , though anyone can deal with backdrop clicking  esc key is coupled which is creating problem

Confirmation dialogs require users to explicitly confirm a choice.

I am talking about confirmation dialogs  along with Full-screen dialogs (Mobile only)

so in responsive design a dialog which is a confirmation dialog can be full screen in mobile which associated with actions . The problem is there is no common events happening when modal is closed or opened so the confirmation cannot be implemented .

According to design its said clicking outside is taken as disagreement , which I want to be able to implement so the choice is either to send events on closing the and opening of dialogs or create static dialogs which cannot be closed by user .

conclusion : It will be nice to have events as it would solve most problems

**Comment by appunnicer13** [comment]
Talking about user experience I have some famous use cases , first time you signup on pinterest .
They ask for selection of 5 topics . So legitimate use cases are there

**Comment by Garbee** [comment]
Ah:

> Alternatively, dialog behavior can be overridden so that users must explicitly choose one of the actions.

Hidden away in the page.

This is doable if you *really* need it by listening to the `cancel` event on the dialog and preventing it. Thanks for the request, however nothing we should do internally to address this.

**Comment by appunnicer13** [comment]
Thankyou for heads up , I also missed dialog reference in W3C. Got it working +1
dialog.addEventListener('cancel', function (e) {
        e.preventDefault();
    });
in case anyone is ever wondering how
