### ISSUE TITLE
componentHandler is gone in latest master

### ISSUE THREAD

**Issue by rauhs** [google/material-design-lite#4422]
When I clone the current master and do a `gulp all` there is no `componentHandler` in `material.min.js`.

Also, is there a way to build the non-minified `material.js`?

**Comment by surma** [comment]
`master` is currently used to work towards MDL v2 (which won’t have `componentHandler` anymore). We are updating the `README.md` to reflect that as we speak. If you want to build MDL, please switch to the `mdl-1.1` branch :)
