### ISSUE TITLE
Should I use <h1> or a MDL class?

### ISSUE THREAD

**Issue by davidhtims** [google/material-design-lite#4425]
This is not clear to me from reading the docs - do I need to add MDL classes to all the HTML elements in order for them to take part in the subtle changes to text formatting by MDL?
Could I just use classless HTML and I would still be good?
What are the minimum classes I need to specify for a great looking, responsive MDL, mainly text  page?

**Comment by Garbee** [comment]
V1 includes a set of direct element targets to get some basic MDL text styling by default. You can take a look at the [typography component](https://github.com/google/material-design-lite/blob/mdl-1.1/src/typography/_typography.scss#L21-116) to see exactly what is done.

**Comment by speeddesigns** [comment]
@Garbee That link is 404.

I have the same question. Do I need to add mdl classes to my h1, h2, h3... If I do, what are they?

**Comment by Garbee** [comment]
I fixed the link to point to the new branch.

Check the [style documentation](https://getmdl.io/styles/index.html) for the classes (view source as well, checking now the docs are just saying what the display is, not the full class name to use.)

In our default builds, headings are handled by default (view the previous link to the component.) If you aren't using one of those native targets, then you'd need to use the classes.
