### ISSUE TITLE
How to change bottom-border color of textbox?

### ISSUE THREAD

**Issue by tommybstitch** [google/material-design-lite#4428]
I was wondering how I can dynamically change the color of the bottom underline of a textbox with a floating label when it's focused? 

When I focus the textbox, the bottom border animates and stretches to fill the textbox. I want this behavior to continue but with a different color.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite. As this is an issue not with the code we provide but instead how to customize it, this is out of scope for the issue tracker.

Thank you.
