### ISSUE TITLE
Please consider custom event registration.

### ISSUE THREAD

**Issue by dkemper01** [google/material-design-lite#4429]
Element.scrollLeft is not animatable via css transitions.  As such, please consider:

Revealing a method in mdlComponentHandler.cs which would allow for overriding default event behavior, implemented in layout.cs, by enabling custom event registration.

A registerCustomHandler method could take the name of a registered component, ‘MaterialLayout’ for instance, and an array of objects with suitable key/value pairs with enough information to locate and wire up a custom event.

The init method of the self-registering MaterialLayout class/component could have a new parameter representing the array of objects, with custom event information and handler functions, and a simple function which would determine if default event registration should be intercepted.  

For reference:
[Example from a web starter kit repo using Sass](https://github.com/dkemper01/d3-starter-kit/commit/8520099b6e818c498c67a892dc1e1e473a6dd11b)

**Comment by Garbee** [comment]
As of right now, we are working on V2 which will have a completely revamped scripting system and component architecture. This kind of modification won't happen in the 1.x lifetime as Layout is a fairly complicated beast of a component and any modifications to it can have unintended side-effects that we can't predict.

Once we announce an alpha for V2 we'd love to start getting your feedback on the new system to understand what may need changing to suite your needs here. As things are though, 1.x is "as-is" in these architectural terms.

You seem to have a functioning work-around for needing this internally within your projects. We encourage you to keep using that as you need it for 1.x builds.

Thanks for the suggestion, but it isn't something we can safely modify and maintain within the current architecture.
