### ISSUE TITLE
snackbar toast - not postioned where I want it

### ISSUE THREAD

**Issue by russellharrower** [google/material-design-lite#4434]
Hi, while I understand why you put it at the bottom, I really need it up the top of the page.

Does any one know how please - I have tried 

1. Top:0 but that makes top go all the way to the bottom and its one big stretch
2. position and display dont help

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As your asking for assistance in how to make a component provided not align to MD spec, this isn't something we can support internally. Therefore, nothing here is actionable for the team to work on.

Thank you.
