### ISSUE TITLE
Numeric input shows invalid on floats

### ISSUE THREAD

**Issue by jordyvandomselaar** [google/material-design-lite#4436]
I use this code to generate a numeric input `<input class="mdl-textfield__input" pattern="-?[0-9]*(\.[0-9]+)?" name="urenOpWeekbasis" type="number">`.
When I type 500 everything is fine, 500**.** is fine as well but when I type 500**.5** the input turns red.

I've tested the pattern on [https://regex101.com/#javascript](https://regex101.com/#javascript) and it works there.

**Comment by Zodiase** [comment]
What I learned from my many failed attempts at resolving this is the fact that `input type="number"` by default has `step="1"`, which doesn't allow decimals. Setting `step="any"` would resolve this. Also another important thing is `input type="number"` ignores `pattern`. If you want to use `pattern`, use `input type="text"`. I know it's weird.

**Comment by Garbee** [comment]
Closing as this isn't a problem with the code we provide but instead and implementation issue.
