### ISSUE TITLE
Ripple effect with scrollbar gets weird

### ISSUE THREAD

**Issue by GolanPachu** [google/material-design-lite#4441]
Hi, I'm using react with mdl, and I'm trying to create a navigation menu component using the drawer, list and list items components of mdl.
I'm pretty happy with the result except one thing, when the menu has scrollbar, the ripple effect on my menu items just gets crazy and weird:

EDIT: I just checked again and I think it happens because I set the html direction to rtl, I changed it back to ltr and It worked just fine. Any idea how to fix it on rtl?
![animation](https://cloud.githubusercontent.com/assets/8162335/16188169/ddce411c-36dc-11e6-9a1c-8a7020807cb7.gif)

It only happens with the scroll bar.

Here is my menu component:

`export default class Menu extends React.Component {
  
    render () {
        return (
            <div className='mdl-js-layout mdl-layout--fixed-drawer'>
                <div className='mdl-layout__drawer drawer scrollbar'>
                    <ul className='mdl-list'>
                    {this.props.modules.map((module, index) =>
                        <li key={index}>
                            <div className="mdl-layout-title menuHeader">{module.moduleName}</div>
                            <ul>
                                {module.screens.map((screen) =>
                                    <MenuItem key={screen.id}
                                              id={screen.id}
                                              screenName={screen.screenName}
                                              icon={screen.icon}
                                              isSelected={ false }
                                              onClick={this.onMenuItemClick}/>
                                )}
                            </ul>
                        </li>)}
                    </ul>
                    <button className="mdl-button mdl-js-button mdl-js-ripple-effect">
                        <i className="material-icons md-28">chevron_right</i>
                    </button>
                </div>
            </div>
        );
    }
}`

MenuItem component:

`export default class MenuItem extends React.Component {
    render () {
        return (
            <li className='mdl-list__item mdl-button mdl-js-button mdl-js-ripple-effect menuItem ' onClick={this.onClick}>
                <div className='mdl-list__item-primary-content'>
                    <i className={'material-icons menuItemIcon md-28'}>{this.props.icon}</i>
                    <span>{this.props.screenName}</span>
                </div>
            </li>
        )
    }
}`

css:
`.drawer {
    right: 0;
    background-color: #303030;
}

.scrollbar {

}

.scrollbar::-webkit-scrollbar {
    width: 14px;
    height: 18px;
}

.scrollbar::-webkit-scrollbar-thumb {
    height: 6px;
    border: 4px solid rgba(0, 0, 0, 0);
    background-clip: padding-box;
    -webkit-border-radius: 7px;
    background-color: rgba(255, 255, 255, 0.15);
    -webkit-box-shadow: inset -1px -1px 0px rgba(0, 0, 0, 0.05), inset 1px 1px 0px rgba(0, 0, 0, 0.05);
}

.scrollbar::-webkit-scrollbar-button {
    width: 0;
    height: 0;
    display: none;
}

.scrollbar::-webkit-scrollbar-corner {
    background-color: transparent;
}

.menuHeader {
    padding: 16px;
    font-size: 14px;
    color: rgba(255, 255, 255, 0.1);
}

.menuItem {
    cursor: pointer;
    font-size: 16px;
    padding: 16px;
    min-height: 40px;
}`

I dont know if its a bug or if I'm doing something wrong.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by GolanPachu** [comment]
I tried that, and I'm guessing the problem is with the code provided by MDL since its just a matter of rtl.

**Comment by Garbee** [comment]
We don't currently have RTL support. Issue #783 is open about that.
