### ISSUE TITLE
MDL "advanced" grid structure

### ISSUE THREAD

**Issue by dadatawajue** [google/material-design-lite#4442]
Hello, I'm trying to achieve something similar as the [mdl dashboard example](https://getmdl.io/templates/dashboard/) where you have one card on the left and two cards on the right in desktop view (like in the image below):

![desktop-layout](https://cloud.githubusercontent.com/assets/16490954/16192483/e534e5b6-36e9-11e6-8d78-ff6c9b5698a6.png)

and when it changes to tablet layout then it becomes like in the image below
![tablet-layout](https://cloud.githubusercontent.com/assets/16490954/16192501/fa5857f2-36e9-11e6-9230-ae6dff56c8c5.png)

The reason it works in the example is because img-C only has a width of 3 in tablet layout because there's a hidden 1-col separator to make up for the missing space caused by mdl-grid--no-spacing.

My question is, how could this layout structure be achieved if I wanted both img-B and img-C to have a 4-col width in tablet layout?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
