### ISSUE TITLE
body behavior of MDL breaks jQuery UI

### ISSUE THREAD

**Issue by bkroggel** [google/material-design-lite#4445]
jQuery UI autocomplete and datepicker components normally stick to their parent input element even when some scrolling action happens.
Using the Material Design Lite framework seems to prevent them from moving around with their associated input field. Instead they keep the initial position

Overwriting the given MDL code and changing the `position: absolute` of the `.mdl-layout__container` to `position: relative` seems to fix the jQuery UI problem but unfortunately breaks the Material Design Lite structure.
    
    .mdl-layout__container {
    position: absolute; // --> change to "relative"
    width: 100%;
    height: 100%;

I created a Pen which replicates this problem and uses JQuery UI autocomplete and datepicker as well as the jQuery Plug-in "[Timepicker][1]"
[CodePen][2]

Those jQuery UI elements seem to position relative to the body which doesn't play well with MDL where the body doesn't move at all and instead gets "mimiced" by the `page-content` class.

Are there any suggestions how I could use jQuery UI and MDL in one project?

  [1]: http://timepicker.co/
  [2]: http://codepen.io/bkroggel/full/EygrXB/ "CodePen"

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by bkroggel** [comment]
Thanks for your input @Garbee.
Just to clear things up. I am aware that this isn't the place to find an actual fix for my problem but my intention was much more to discuss if this behavior of the MDL framework is "right" in the way it is currently implemented or if it should be reconsidered on the long term.

Nevertheless I think you are right that this is probably not the right place or the right time.

**Comment by Garbee** [comment]
Layout is being completely re-built in V2. We know of numerous issues it causes. The V1 Layout was done as it is for IE9 support, now that it is not needed we can do things far more modern that get's in the way less.

**Comment by bkroggel** [comment]
Wow, great news that V2 is already in the pipeline. Just curious, is there a rough timeframe for release?

**Comment by Garbee** [comment]
No timeframe. Lots of experiments ongoing to see how it is even going to be. Then we need to carry that across all components and try to get/integrate feedback at the same time.
