### ISSUE TITLE
Gulp default not building the equivalent javascript as in CDN

### ISSUE THREAD

**Issue by intersides** [google/material-design-lite#4446]
When trying to build both minified css and javascript for custom changes the generated output is not functioning and far from the CDN JavaScript although both relates to version 1.1.3.
I noticed that there is a porting to v2 of some components and not of them are ready. In gulp SOURCES those components using componentHandler as global resource are commented out.
Is there any open issue with a branch in progress I could work with ?

**Comment by Garbee** [comment]
As the readme states, `mdl-1.1` is for continuing development of the 1.1 branch. `master` branch is now 2.0 development which we aren't currently supporting.
