### ISSUE TITLE
Prevent waterfall header from expanding?

### ISSUE THREAD

**Issue by aidanharris** [google/material-design-lite#4450]
Is there a way to prevent a waterfall header from expanding?

My extremely ugly hack is to modify the 'private' / internal `window.MaterialLayout.prototype.CssClasses_.IS_COMPACT` as follows:

```js
window.MaterialLayout.prototype.CssClasses_.IS_COMPACT = "is-not-compact";
...
window.MaterialLayout.prototype.CssClasses_.IS_COMPACT = "is-compact"
```

This prevents the waterfall header from expanding (assuming it doesn't have the class 'is-not-compact') but is extremely inelegant.

Is there a better solution to this problem?

**Comment by sgomes** [comment]
The whole purpose of a waterfall header is to expand and shrink, so I don't think I understand your question. Wouldn't one of the other header types (such as the default) work?

Could you elaborate on what you're trying to achieve by having a non-expanding waterfall header?

**Comment by aidanharris** [comment]
I have an expanding search field in the header and whenever the search field expands so does the header. This is undesired.

**Comment by sgomes** [comment]
Looking at the source, that should be caused by the header receiving a click, rather than the search field expanding.

We don't currently support any official way of overriding that behaviour, so your best bet is to override the click handler method `MaterialLayout.prototype.headerClickHandler_` to an empty function. Could you give that a try and let me know how it goes?

**Comment by aidanharris** [comment]
Thanks that's working much better than my ugly hack. For reference, in case anyone else stumbles across this I ended up adding the following script tag after loading Material Design Lite:

```js
<script defer>MaterialLayout.prototype.headerClickHandler_ = function(e) {
		if(e.target.id !== 's' && e.target.parentNode.id !== 's' && e.target.innerHTML !== '') {
			if (this.header_.classList.contains(this.CssClasses_.IS_COMPACT)) {
				this.header_.classList.remove(this.CssClasses_.IS_COMPACT);
				this.header_.classList.add(this.CssClasses_.IS_ANIMATING);
			}
		}
	};
</script>
```

Now the menu still expands unless the user clicks on the hamburger menu or activates the search.
