### ISSUE TITLE
Major issue/PR housecleaning

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#4462]
- [x] Draft template text for closing issues
- [ ] Close all non-bug issues for v1
- [ ] Analyse feature requests and decide whether to move them to v2
- [x] Close all open v1 PRs against master
- [x] Redirect open v1 PRs against mdl-1.x

**Comment by sgomes** [comment]
Sample text for closing open PRs against `mdl-1.1` or `mdl-1.2`:

Hello there! We're currently doing some housecleaning on the repository to prepare for the big changes to v2, and part of this is to currently move all PRs against 1.x to the `mdl-1.x` branch. Since it's not possible to target PRs at a new branch, we're closing this PR and asking you to reopen against `mdl-1.x` if you think it's still valid.

Thank you!

**Comment by traviskaufman** [comment]
@sgomes making a `v1-bug` label for all of the issues filed against the v1 codebase that we're keeping open / carrying over.

**Comment by sgomes** [comment]
Thanks, @traviskaufman!

**Comment by traviskaufman** [comment]
Resolving as this has been open for a while and we've begun active work on v2.
