### ISSUE TITLE
Implement Checkbox v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4471]
Spec reference: https://www.google.com/design/spec/components/selection-controls.html#selection-controls-checkbox

**Comment by ianspiro** [comment]
There's a small accessibility bug with the current checkbox. Screenreaders (ChromeVox, at least) use the underlying checkbox input for highlighting. The original input is offset somewhat from the upgraded version. Here's a screenshot. Could you keep this in mind with the v2 component? Thanks!

![checkbox](https://cloud.githubusercontent.com/assets/9756028/17421118/2e064c68-5a5c-11e6-8bea-ba32e31dfd3d.png)

**Comment by Garbee** [comment]
Yup, Travis is working on this honking component currently. Once it is up for review I'll be running it through Chromevox and NVDA to test. This is great feedback to keep an eye on. Thank you.
