### ISSUE TITLE
Implement Simple Menu v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4474]
Spec reference: https://www.google.com/design/spec/components/menus.html

Covers simple menus only, not cascading menus.

**Comment by HriBB** [comment]
Just a few questions regarding the v2 implementation of `Menu`.

Should menus be rendered in the `body` element to prevent overflow problems? If menu is rendered inside a parent with `overflow: hidden`, it will be clipped and in some scenarios (modals for example) it is virtually impossible to fix that.

Are there any plans to constrain `Menu` inside the viewport? There is a pending issue in v1 about this (#4308). I am willing to work on a PR for that, once the alpha is publicly available.

Looking forward to v2 ;)

**Comment by traviskaufman** [comment]
FYI https://www.w3.org/TR/wai-aria-practices/#listbox_div

**Comment by traviskaufman** [comment]
@HriBB 

> Should menus be rendered in the body element to prevent overflow problems?

Probably

> Are there any plans to constrain Menu inside the viewport?

Yeah, we should probably take this into consideration. The easiest way to do this would be to re-layout the component on a resize event, which we should probably be doing anyway. We could then do something like reposition the menu. Or, when the normal height cannot fit the size of the viewport, set height on the menu to 100%.

**Comment by HriBB** [comment]
I wanted to learn how to render components to body in React, so I wrote a simple menu that does this. It uses "portal" technique to render itself into the body - bye bye parent overflow:hidden problems. It is also constrained to the viewport.

Here's the repo
https://hribb.github.io/react-mdl-portal-menu/

And here are the examples
https://hribb.github.io/react-mdl-portal-menu/

I know this is for React, but maybe someone finds it usefull.

Haven't tested with npm install yet, hope it works :P

PS: would love to get some feedback on this ;)
