### ISSUE TITLE
Implement Dropdown Menu v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4475]
Spec reference: https://www.google.com/design/spec/components/menus.html

This is our `<select>` equivalent. See [this image](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3VGxlSGNVWmNJX3c/components_menus_behavior2.png)
- [x] Single-Select Mode
- [ ] Multi-mode

**Comment by haoxins** [comment]
we should also support `multiple` mode.
Such as https://material.angularjs.org/latest/api/directive/mdSelect

**Comment by Garbee** [comment]
Multiple mode doesn't seem to relate to a textfield. Do you mind elaborating on what exactly you want that the [Material Design Specification](https://material.google.com/) details?

**Comment by alexgig** [comment]
Hi @traviskaufman,

How is this different then the generic overflow dropdown button? (https://material.google.com/components/buttons.html#buttons-dropdown-buttons)

Seems like the dropdown button specification is the more complete solution. Are there plans to implement it in Mdl?

**Comment by HriBB** [comment]
I think this is just the dropdown part of the dropdown button. Menu with options/actions.

**Comment by traviskaufman** [comment]
@HriBB is correct; from a UX perspective this is pretty much combining a button with a menu. There is additional work that needs to be done though, particularly around accessibility.

**Comment by alexgig** [comment]
Cool. Thanks for the explanation guys.

**Comment by gaastonsr** [comment]
Is v2 going to cover dropdown menus?

**Comment by Garbee** [comment]
@gaastonsr That is a part of the drawer component which is #4476. Current plans is to offer one form of the MD specified menus.

**Comment by traviskaufman** [comment]
^ ah, ignore this. I referenced the wrong issue in the commit 😭

**Comment by traviskaufman** [comment]
FYI ^ :) 

Also note, we've built the v2 version of select such that it works as both a custom element _as well as with the native browser select_, and you can seamlessly switch between the two. This means you get the full-fidelity experience on desktop devices while being able to switch over to the native version on a mobile device for the best cross-browser UX possible.

**Comment by traviskaufman** [comment]
Closing for now. Single-select is done and multi-select will be moved to a new issue.

**Comment by NBurke1** [comment]
Sorry for dragging up an old topic...but I've read this thread, and the previous one https://github.com/google/material-design-lite/issues/854

and more recent ones which link to this thread as a "solution"...but i still have no idea where the MDL select component is? it's not on the components page: https://getmdl.io/components/index.html

Am i missing something? I'm using MDL v1.3 which is the only version i could find

**Comment by moog16** [comment]
@NBurke1 MDL is now [MDC](https://github.com/material-components/material-components-web/). Select is [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select).
