### ISSUE TITLE
Implement Text Field v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4479]
Spec reference: https://material.google.com/components/text-fields.html

- [x] Single-line
- [x] Multi-line (`<textarea>`?)
- [x] Full-width
- ~~Character Counter~~ (split into #4823)

This is our `<input type="text">`.

Auto-complete is not included in the scope of this feature.

**Comment by traviskaufman** [comment]
@Garbee to validate PRs for css-only solution correctness.

**Comment by Garbee** [comment]
One neat trick with the JavaScript to improve the experience is this...

<details>
<legend>Pseudo-code</legend>
```javascript
  element.addEvenListener('onblur', function(e) {
    if (e.target.validitiy() === false) {
      // check for error text node. If presented by the developer, just display it. If it does not exist, create it with the validation message and return.
    }
    // Hide error message if shown already since the form field is filled out according to spec.
  });
```
</details>

That will allow developers to not have the need to manually create error message holders while still using the native validation APIs to fill it in automatically.
