### ISSUE TITLE
Implement "FAB-Single Sheet Menu" v2 component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4483]
- Spec reference: https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
- Motion video mock: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B8v7jImPsDi-d09QRUZzVUdMSFk/components-buttons-fab-transition_card_01.webm
- [ ] Implement Proper transitions between FAB and Single Sheet Menu
- [ ] Add correct Keyboard A11y

There are internal motion mocks for these transitions that I can get when it comes time to implement.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/35
