### ISSUE TITLE
Implement Subheader v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4485]
Spec reference: https://material.google.com/components/subheaders.html

**Comment by Garbee** [comment]
I think with the subheader space it would be best to add subheadings into the components that they are defined for. This has been a quirky thing about the specification for a while with me. I don't understand why this is its own component defining a single piece of 3-4 other specs, when it should just be a section within those specifications. That way the class naming is more streamlined.

`.mdl-menu__subheading` vs `.mdl-subheading--menu`, I think the former version is much better for developers given the scoping of the BEM syntax we use.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/33
