### ISSUE TITLE
Implement Dialog v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4486]
Spec reference: https://www.google.com/design/spec/components/dialogs.html

I also made a Codepen mocking up a basic dialog sketch: http://codepen.io/traviskaufman/pen/yJayZj

Even though the spec doesn't have an "x" button in their mocks, it does work well for large dialogs on big screens, so we may want to consider it.

**Comment by Garbee** [comment]
Our current component uses the [Dialog Polyfill](https://github.com/GoogleChrome/dialog-polyfill) for the native HTML element. I believe it is best that we continue relying on the polyfill. That way we aren't maintaining all the positioning or JS API side of things. That means once other browsers implement the functionality, developers can simply remove the polyfill from their apps and with no other modifications be running.

Using the polyfill, we have a very simple CSS shim around that to get the styling right, keeping what we maintain internally super lightweight.

**Comment by samthor** [comment]
Minor aside: I'd suggest using `position: fixed` on this dialog to avoid positioning issues like you've experienced in v1.

**Comment by Garbee** [comment]
What we do now is simply document the polyfill is required and let developers pull it in themselves. I don't see why we need to include a component just to do a feature detection and error if it doesn't work. Developers will know very quickly in development if it isn't working.

Our dialog "component" is just some styling to meet MD specs, no JS on our end by recommending the polyfill. I suggest we keep it that way for the most simple implementation and least amount of code maintenance.

**Comment by traviskaufman** [comment]
Yeah I agree that's the proper strategy.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/32
