### ISSUE TITLE
Add Three-Line List support to List v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4487]
Specs: https://material.google.com/components/lists.html#lists-specs

**Comment by traviskaufman** [comment]
Pre-emptive Strategy: Set hard-coded height values on secondary text element, and use `text-overflow: ellipses;`. Document how this works so as not to surprise end users.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/31
