### ISSUE TITLE
Implement Circular Progress Indicator v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4488]
Spec reference: https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

**Comment by jestelle** [comment]
Reference:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/progress_indicator.dart

The circular indeterminate indicator for Flutter was written by me, and is correct :)
This should translate to something we can do in canvas if we choose that route.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/30
