### ISSUE TITLE
Implement Snackbar v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4490]
Spec Reference: https://www.google.com/design/spec/components/snackbars-toasts.html 

It's been called a "Toast" in the past, but the thing that's not Android-specific is a **snackbar**.
- [x] Initial Implementation
- [ ] Dark Theme (background: `#fafafa`, text: text-primary-on-dark, action: theme primary color)
- [ ] Keyboard Focus Handling

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/28
