### ISSUE TITLE
Implement Grid List v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4498]
Spec reference: https://www.google.com/design/spec/components/grid-lists.html#grid-lists-specs

**Comment by jswirus** [comment]
Do you have plan to support for the tiles of different sizes? If so, how?
- Grid layout is not supported
- Flexbox can't handle different tile sizes

I see there two ways:
- Use flexbox layout and give free hand to host environment to do layout (example: grid layout polyfill)
- Handle layout via javascript

**Comment by Garbee** [comment]
> Flexbox can't handle different tile sizes

Yes it can. You just individually set the `flex-basis`.

Handling it via JS-only is a **extreme** measure and we are avoiding that unless absolutely necessary with components. This layout piece is fairly critical, so requiring JS for basic usage is not feasible. We need to make sure the JavaScript is an *enhancement* and not required for basic functionality.

**Comment by jswirus** [comment]
Garbee, i know about it.
But i was talking about layout where you have tile with spans for 2 rows.

![Example](https://material.angularjs.org/material2_assets/grid-list/fancy-grid-list.png)

**Comment by Garbee** [comment]
We can always do a `grid` base with `flex` fallback and enhance with JS for the columnar support. We need to remember that the css-only methods don't need to be perfect fidelity as that is only achievable with JS in some cases. So long as things render fine-enough without JS it is good to muster.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/47
