### ISSUE TITLE
Implement Stepper v2 Component

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4501]
Spec reference: https://www.google.com/design/spec/components/steppers.html

- [ ] All steppers / step types, _except_ "Mobile Step"
- [ ] "Mobile Step"

Caveat: We might want to split this up differently once we get to this task, and recategorize the stepper types from the spec language to make it less ambiguous.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/44
