### ISSUE TITLE
Add support for Circular Progress Indicator FAB integration

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4509]
Spec reference: https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

See also: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B0NGgBg38lWWbTlSaHdQZEMtalk/components-progressactivity-typesofindicators-061101_Circular_Aspirational_xhdpi_002.webm

See also: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B6Okdz75tqQsa0QwVnd6NVlvWkk/components-progressactivity-typesofindicators-Circular_wFab_xhdpi_003.webm

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/52
