### ISSUE TITLE
how to get a srollTop

### ISSUE THREAD

**Issue by fanyer** [google/material-design-lite#4511]
excuse me,I want to know how to get a srollTop of mdl-layout--fixed-content
 when mdl-layout--fixed-header exist

**Comment by fanyer** [comment]
to b short, what i want to know is how to addEventListener of scroll in .mdl-layout__content

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Since this is a question about implementing custom code, it is out of scope of this projects tracker.

Thank you.
