### ISSUE TITLE
Using material design switch in web view

### ISSUE THREAD

**Issue by Nishant-Pathak** [google/material-design-lite#4512]
Hi,

Referring [issue comment](https://github.com/google/material-design-lite/issues/1375#issuecomment-229370919). Creating new issue.

**Description:** Switch is looking odd on the WebView (Android)

Android version: 5.1.1
material-design-lite version: 1.1.3

Issue image: 
<img width="279" alt="screen shot 2016-06-29 at 7 49 33 pm" src="https://cloud.githubusercontent.com/assets/724049/16486701/064b6cc8-3ee4-11e6-9b9c-0b369f7e5985.png">

code used:

```javascript     
        <div>
          <label className="shipmentForm-switch mdl-switch mdl-js-switch mdl-js-ripple-effect"
                 htmlFor="isTamperedShipmentId">
            <input id="isTamperedShipmentId" type="checkbox"
                   className="mdl-switch__input" {...isTampered}/>
            <span className="mdl-switch__label">Is Tampered?</span>
          </label>
        </div>

```

**Comment by Nishant-Pathak** [comment]
Please suggest if this is an issue or I am using it wrong.

**Comment by Garbee** [comment]
Please use [codepen](http://codepen.io) to provide a running sample of what reproduces the problem.

Android WebView isn't on our direct browser support, however it is the latest Blink engine so it should work the same as Chrome.

**Comment by Nishant-Pathak** [comment]
I am not sure what went in wrong in web view, it use to work on the same device in chrome browser. Please go ahead and close if you think it is not worth to put effort and resolve ( as it is reproducible in web view android).

**Comment by Garbee** [comment]
I'm going to close this out then. V1 is only receiving attention for critical problems from the core team now. If someone from the community wants to look into why this doesn't work in webview and make a non-BC breaking fix the `mdl-1.x` branch is open for PRs.

Thank you.
