### ISSUE TITLE
Speed testing

### ISSUE THREAD

**Issue by gargullia** [google/material-design-lite#4513]
I tested using your tool @google [Mobile Website Speed Test](https://testmysite.thinkwithgoogle.com/) results:
MOBILE FRIENDLINESS - 99/100
MOBILE SPEED - 67/100
DESKTOP SPEED - 82/100
Also tested through the test templates.. We must strive to 100/100

**Comment by Garbee** [comment]
Scoring is quite difficult and a lot of factors go into play. 100% doesn't mean, "Your the best" it means you hit the tests metrics, even though they could be a *detriment* to users.

While the components should be better, as a whole aiming for speedtest scores as a library doesn't make sense. This isn't actionable and the templates are just samples. Closing this out as any action here is too broad and unreasonable for the projects position to take action on.
