### ISSUE TITLE
Undocumented class ".mdl-list__item-sub-title"

### ISSUE THREAD

**Issue by com-taycor-rbutler** [google/material-design-lite#4515]
The Lists section of the MDL Components page includes span elements with the class `mdl-list__item-sub-title`; however, the configuration options section at the end of the page only references the class `mdl-list__item-text-body`, which seems to do about the same thing. 

https://getmdl.io/components/index.html#lists-section

**Comment by Garbee** [comment]
If someone from the community wants to handle documenting this then `mdl-1.x` is open for PRs. The core team is focusing on V2 efforts and won't be addressing non-critical v1 problems going forward.

Thank you.
