### ISSUE TITLE
upgradeElement() upgradeDom() doesn't work

### ISSUE THREAD

**Issue by littleguga** [google/material-design-lite#4519]
Demo: https://jsfiddle.net/littleguga/cgvy45nr/

MDL version: 1.1.3
Browser: last Google Chrome
Operating system: windows 7 x64

I try to dynamically add checkboxes, but no upgrade functions seems to work me.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by littleguga** [comment]
@markopaju shame on me( Great thanks for this and sorry for the panic.
