### ISSUE TITLE
Errata in HTML

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#4521]
view-source:https://getmdl.io/components/index.html#buttons-section
Line 8977

`<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js""></script>`

should be

`<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>`

**Comment by Garbee** [comment]
This won't cause a parsing error. So no action will be taken here by the team. We are open to a PR if someone wants to track this down and fix it in the `mdl-1.x` branch.
