### ISSUE TITLE
Textfield highlighting disappears after receiving input in IE11 

### ISSUE THREAD

**Issue by eruvanos** [google/material-design-lite#4529]
* MDL version: 1.1.3
* Browser: Internet Explorer
* Browser version:  11 (compatibility mode: Edge)
* Operating system: Windows
* Operating system version: 8.1
* URL: http://codepen.io/tutsplus/pen/XmWZBY

## What steps will reproduce the problem:
1. click into the textfield
2. start typing

## What is the expected result?
When clicking into a `mdl-textfield` it is highlighted(blue underline) and it remains to be highlighted when receiving input.

![screen shot 2016-07-06 at 12 02 06](https://cloud.githubusercontent.com/assets/9437863/16614427/7cfba194-4371-11e6-85c0-42aac0e35478.png)

## What happens instead of that?
When clicking into a `mdl-textfield` it is highlighted(blue underline) but highlighting disappears when receiving input. It works alright in all other browsers.

![screen shot 2016-07-06 at 12 00 14](https://cloud.githubusercontent.com/assets/9437863/16614392/43be67e0-4371-11e6-9691-eabe239afbc8.png)

Thanks for any help!

**Comment by Zodiase** [comment]
![image](https://cloud.githubusercontent.com/assets/1815174/16624123/2401c1a0-4366-11e6-9aa5-726350ee41e5.png)

Looks like in IE11 the `visibility` on a child pseudo-element can not overcome the `visibility` set on its parent. https://connect.microsoft.com/IE/feedback/details/1449224/ie-11-the-descendants-of-an-invisible-visibility-hidden-element-should-be-visible-if-they-had-visibility-visible

**Comment by Garbee** [comment]
Overall this is a minor inconsistency in one engine. The core team won't be addressing this in V1 as we are focusing fully on V2 work and only addressing critical issues.

If anyone from the community wants to handle fixing this in a non-breaking way, `mdl-1.x` is open for PRs.

Thank you.
