### ISSUE TITLE
Icon buttons in header don't have padding

### ISSUE THREAD

**Issue by shawmanz32na** [google/material-design-lite#4531]
MDL version: 1.1.3
Browser: Chrome 51
Operating system: Windows 10
Example: http://codepen.io/shawmanz32na/pen/wWqoGR?fork=xGWgXa#

The example here has the example code from the layout section, plus the example code for an expandable textfield and an icon button in the header.

As you can see, the icon buttons draw right next to each other, although the material spec shows padding between buttons.

![header icon button padding example](https://cloud.githubusercontent.com/assets/5596570/16637039/eb895592-4390-11e6-8479-0076deb6ce46.png)

**Comment by Garbee** [comment]
This is a minor issue in V1. Community contributions welcome to address it in a non-breaking way. Closing this out since it isn't something the core team will focus on since we are working on V2 which will change how most of this works anyways.

Thank you.
