### ISSUE TITLE
Expandable textfield icon isn't vertically aligned

### ISSUE THREAD

**Issue by shawmanz32na** [google/material-design-lite#4532]
MDL version: 1.1.3
Browser: Chrome 51
Operating system: Windows 10
Example: http://codepen.io/shawmanz32na/pen/wWqoGR?fork=xGWgXa#

The example here has the example code from the layout section, plus the example code for an expandable textfield and an icon button in the header.

As you can see, the icon button for the expandable textfield isn't in line with the rest of the icon buttons.

![header icon button padding example](https://cloud.githubusercontent.com/assets/5596570/16637177/24efdb52-4392-11e6-8496-bfa974f060f2.png)

![header icon button padding example - edited](https://cloud.githubusercontent.com/assets/5596570/16637172/1589e7d4-4392-11e6-99fa-66e8144eeb01.png)

**Comment by fanyer** [comment]
I think should position it manully

**Comment by Garbee** [comment]
This is a minor issue in V1. Community contributions welcome to address it in a non-breaking way. Closing this out since it isn't something the core team will focus on since we are working on V2 which will change how most of this works anyways.

Thank you.
