### ISSUE TITLE
Radio buttons styling not showing i SPA

### ISSUE THREAD

**Issue by Walraz** [google/material-design-lite#4536]
Only tested for radio buttons..
When navigating to another page (Single page app) with radio-buttons no styling appearing on them.. but on refreshing the page all styles are back on the radio-buttons.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Radio buttons work as expected. The problem most likely lies in your application architecture.

Thank you.
