### ISSUE TITLE
Suggest release the .css files in the template in .scss format

### ISSUE THREAD

**Issue by davidshen84** [google/material-design-lite#4543]
Since all the MDL styles are developed using SASS, why the styles in the `template` are developed in raw CSS? If there's no copy right issue, would it make sense to release the SASS version of the styles?

**Comment by Garbee** [comment]
They are raw CSS to show developers how to customize it to their needs. There are no Sass versions of those sources.

There won't be any modifications to the V1 template system at this point as it is a non-critical piece.

Thank you.
