### ISSUE TITLE
Snackbar / Toast Blends In With Footer & Position Is Not Configurable

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#4552]
It would be nice to control where the toast shows up.  Based on my reading of the docs, it shows up at the bottom center by design.  Notice how the dark grey toast background does not stand out when overlaid on top of the grey footer?

Can we make it show up top center or top right, like Google toast does (gmail for example)?

**Comment by Garbee** [comment]
This is aligning to the MD specification and positioning is forced to the bottom. I do know that it blends with the footer, however the footer is not in the spec and there isn't much we can do about that internally now.

A workaround is making your footer coloring different, like I made mine the primary color with accent color for links. With V2 I'm going to work on updating Snackbar a bit for desktop *if we can* in order to allow it to be more noticeable on desktop.

Thank you.

**Comment by rhroyston** [comment]
I see <https://material.google.com/components/snackbars-toasts.html#>.
Firebase.google.com sure does look Material, and their toast is top right.
Maybe the MDL folks could reconsider?

Thanks Frank.

BTW: MDL Swatch <https://rack.pub/swatch> !

On Wed, Jul 13, 2016 at 4:01 AM, Jonathan Garbee <notifications@github.com>
wrote:

> Closed #4552 <https://github.com/google/material-design-lite/issues/4552>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/material-design-lite/issues/4552#event-721268653>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMKS-9m2TcYFAwkU4o6lXCB9Elr4BkH8ks5qVKmGgaJpZM4JK888>
> .
>



-- 
- Ron Royston
  (504) 722-8412

**Comment by Garbee** [comment]
"Looks material" and "is material" are two different things. As I said, with 2.x I'm going to work on getting us allowed to move it into center or top-placement. As of right now, 1.x is fully aligning with the provided specification which means we "are material" not "emulating it".

**Comment by rhroyston** [comment]
Material Design
<https://material.google.com/style/color.html#color-color-schemes> - "All
color palettes should include sufficient contrast between different UI
elements."

Glance at the image below.  The toast is unseen.

I appreciate that this is a Material Design issue, not an MDL issue.  Just
thought I'd fully document the issue.


​
​

On Wed, Jul 13, 2016 at 9:38 AM, Jonathan Garbee <notifications@github.com>
wrote:

> "Looks material" and "is material" are two different things. As I said,
> with 2.x I'm going to work on getting us allowed to move it into center or
> top-placement. As of right now, 1.x is fully aligning with the provided
> specification which means we "are material" not "emulating it".
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/material-design-lite/issues/4552#issuecomment-232375345>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMKS-8_kAI9D1Qe4KT0n2OMg2ZLsLuWrks5qVPhKgaJpZM4JK888>
> .
>



-- 
- Ron Royston
  (504) 722-8412

**Comment by Garbee** [comment]
It isn't an MD issue specifically, because Footer is not an MD specified component. It was something custom we did for sites. Before Snackbar was done. However, we can make Snackbar deviate and we can't change the footer coloring due to SemVer. So it is stuck.
