### ISSUE TITLE
https://getmdl.io/templates/ Demo site broken links

### ISSUE THREAD

**Issue by newschapmj1** [google/material-design-lite#4560]
**Demo site - 6 broken links**

Simple 404 errors, verified by external website.

1
https://getmdl.io/faq/index.html
https://github.com/google/material-design-lite/blob/master/src/material-des
>>	url src	404
2	
https://getmdl.io/templates/blog/index.html
https://github.com/google/material-design-lite/blob/master/templates/blog/
>>	url src	404
3	
https://getmdl.io/templates/android-dot-com/index.html
https://github.com/google/material-design-lite/blob/master/templates/android-dot-com/
>>	url src	404
4	
https://getmdl.io/templates/dashboard/index.html
https://github.com/google/material-design-lite/blob/master/templates/dashboard/
>>	url src	404
5	
https://getmdl.io/templates/text-only/index.html
https://github.com/google/material-design-lite/blob/master/templates/text-only/
>>	url src	404
6	
https://getmdl.io/templates/article/index.html
https://github.com/google/material-design-lite/blob/master/templates/article/
>>	url src	404

**Comment by Garbee** [comment]
Fixed in commit 71cc8a35052d2c47ae113699e6d513dfe33f69d9. Just waiting for a new deployment.
