### ISSUE TITLE
translate3d breaks tooltip

### ISSUE THREAD

**Issue by alvarotrigo** [google/material-design-lite#4562]
Not quite sure if this is also taking place in v2. I couldn't find any example online with v2 and I was not bothered to download the latest as I still want to provide support for IE 10, but just in case this still being a bug I'll mention it.

## Bugs
Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
v1.1.3

> What browser(s) is this bug affecting (including version)? 
All

> What OS (and version) are you using?
Windows 7

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
https://jsfiddle.net/Lp3wco85/1/

> What is the expected behavior?
Tooltip showing in the right place.

> What is the actual behavior?
Tooltip showing in the wrong place

> Any other information you believe would be useful?

**Comment by Garbee** [comment]
Tooltips are not implemented in V2 yet and won't be for some time. As far as V1 goes, this is a side-effect of how it was implemented and the core team won't be putting any effort into addressing this as we are busy with V2 work.

If someone from the community would like to debug and patch this in a non-breaking way, then `mdl-1.x` is open for PRs.

Thank you.
