### ISSUE TITLE
Should we switch to an object composition pattern over mixins?

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4568]
I recently read [Dan Abramov's article on mixins](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html). Although their use of mixins is different than ours ("sharing code between multiple components" vs. "sharing functionality between different platforms"), the article makes some really good points.

I'll preface this by saying I still think mixins are an adequate solve. They allow our components to transparently integrate with any framework. They do not introduce class hierarchies (unlike traditional OO). They do not need to be explicitly `new`d within code, or injected via a DI mechanism (unlike traditional object composition). They do not get in the way of decorators or analysis tools that expect static class definitions to function properly (unlike the "higher-order components" pattern described in the article).

That being said, I see two major issues which parallel concerns raised in the article:

* Implicit Dependencies
* Name clashes

There are also the minor mixin issues that I think we can get around:

* There may be difficulty getting type systems to recognize the pattern.
* Composing mixins is not exactly straightforward, e.g. a `MDLButtonMixin` would need to be aware of a `MDLRippleMixin`.

I believe we can ameliorate these issues by using the object composition pattern.

Say we have a component `MDLFoo` that defines a mixin. With our current arch we might write this as:

```javascript
export default function MDLFooMixin(adapter = {}) {
  adapter = Object.assign({
    addEventListener: () => {},
    doFancyDOMStuff: () => {},
    // ....
  }, adapter);

  Object.assign(this, {
    initMdlFoo_() {
      // where bindAll() binds every method on the object to the given receiver
      this.adapter_ = bindAll(adapter, this);
      this.adapter_.addEventListener('click', () => this.adapter_.doFancyDOMStuff());
    },
    // ...
  });
}
```

Which can be used as follows, for example in the vanilla `MDLFoo` component: 

```javascript
export default class MDLFoo {
  constructor(root) {
    super(root);
    this.initMdlFoo_();
  }
}

MDLFooMixin.call(MDLFoo, {
  addEventListener(type, listener) {
    this.root_.addEventListener(type, listener);
  },

  doFancyDOMStuff() {
    requestAnimationFrame(() => this.root_.style.backgroundColor = 'green');
  },
 
  // ...
});
```

We can change this that so that the mixin actually becomes the base class itself, which _takes an adapter_ and _exposes `init` method_:

```javascript
// mdl-foo/base.js
export default class MDLFoo {
  /**
   * @param host The host instance (e.g. a vanilla component, React component, Angular2 
   *     component, etc) that we'll be operating on.
   * @param  adapter The adapter similar to the one given to a mixin.
   */
  constructor(adapter = {}) {
    this.adapter_ = Object.assign({
      addEventListener: () => {},
      doFancyDOMStuff: () => {},
      // ....
    }, adapter);
  }

  init() {
    this.adapter_.addEventListener('click', () => this.adapter_.doFancyDOMStuff);
  }
}
```

Now our vanilla components can be suffixed with `Component` (to avoid confusing names):

```javascript
// mdl-foo/index.js
export default class MDLFooComponent extends MDLBaseComponent {
  constructor(root) {
    super(root);
    this.mdlFoo_ = new MDLFoo({
      addEventListener: (type, listener) => {
        this.root_.addEventListener(type, listener);
      },

      doFancyDOMStuff: () => {
        requestAnimationFrame(() => this.root_.style.backgroundColor = 'green');
      }
    });

    // In other frameworks, this can be called during a component lifecycle hook.
    this.mdlFoo_.init();
  }
}
```

This gets rid of API ambiguities as well as (pretty much) all potential method naming conflicts. It also works better with type systems, and allows us to have nested composition, e.g. `MDLRadio` might compose `MDLRipple`.

p.s. I apologize for all this churn :/ I just want to make sure we get this as right as possible in the beginning so we don't wind up having to go back and make huge changes further down the road!

**Comment by Garbee** [comment]
So, it is more encapsulation between the mixin class and the classes implementing them.

SGTM.

**Comment by rfru** [comment]
Yes, I like this direction, and it will play more nicely with current type systems. The adapter could really be a pure interface, and then in the simplest case `this.mdlFoo_ = new MDLFoo(this)` would work fine if the methods are provided on the component.

Should the `host` parameter in your example be deleted?

**Comment by traviskaufman** [comment]
> The adapter could really be a pure interface, and then in the simplest case `this.mdlFoo_ = new MDLFoo(this)` would work fine if the methods are provided on the component.

That's true, but wouldn't that also make the API a bit more implicit? Implementers would have to add specific methods to their components without the context of where those methods will be used. Also, those methods may not be covered in tests, leading to false negatives for coverage.

**Comment by sgomes** [comment]
The naming might need some work, but I like the architecture; it's easier to grok composition than it is mixins. And since we had the implicit concept of an adapter anyway, we might as well make it explicit and thus easier to understand what's going on.

Plus, I really like that we're still leaving the class hierarchy simple with this approach, and open to being extended in the right place: adapters.

**Comment by traviskaufman** [comment]
👍 excellent.

**Comment by rfru** [comment]
Yes, it would make it more implicit, and wouldn't work as well unless we had an actual enforcing type system, but the pattern is the same as ObjC/swift's heavily reliance on interfaces/protocols/delegates and also golang's object composition model.

**Comment by traviskaufman** [comment]
> the pattern is the same as ObjC/swift's heavily reliance on interfaces/protocols/delegates

True, but then in practice that pattern leads to some pretty gnarly methods, e.g. [tableView:didSelectRowAtIndexPath:](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewDelegate_Protocol/#//apple_ref/occ/intfm/UITableViewDelegate/tableView:didDeselectRowAtIndexPath:). 

Which might, roughly, translate in JS to:

```javascript
class HostComponent {
  constructor() {
    this.mdlCheckboxDelegate = new MDLCheckboxDelegate(this);
  }

  mdlCheckboxGetNativeControl() {
     return /* ... */;
  }
}
```

basically we'd have to namespace everything or we wind up back at the mixin collision model. The other option would be to just enforce that host classes provide some _property_ that acts as an adapter, but in that case why not pass it to the object directly?

**Comment by traviskaufman** [comment]
(reopening to continue the convo)

**Comment by traviskaufman** [comment]
**Resolved**. See #4578
