### ISSUE TITLE
issue with raised button without color in toolbar

### ISSUE THREAD

**Issue by xenoterracide** [google/material-design-lite#4576]
```
   <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title">RPF</span>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <form action="#" name="login">
                <div class="mdl-textfield mdl-js-textfield">
                    <input class="mdl-textfield__input" type="email" id="username" name="username">
                    <label class="mdl-textfield__label" for="username">noreply@example.com</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield">
                    <input class="mdl-textfield__input" type="password" id="password" name="password"/>
                    <label class="mdl-textfield__label" for="password"></label>
                </div>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect">
                    Sign In
                </button>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect">
                    Register
                </button>
            </form>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Title</span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a>
            <a class="mdl-navigation__link" href="">Link</a>
        </nav>
    </div>
```

maybe I'm wrong, but shouldn't the register button be "white"?
![screenshot_20160720_210113](https://cloud.githubusercontent.com/assets/5517/17009120/40776ab2-4ebd-11e6-8d22-7438c5e838af.png)

**Comment by Garbee** [comment]
The raised button color is the primary color, so this is correct. This also isn't a MD pattern so not something we can support internally.

I'm about to work right now on the V2 button and FAB component and the naming will be much clearer for what you get.

Thank you.

**Comment by xenoterracide** [comment]
I mean I'm at least in part trying to deal with the fact that a darkish blue button with black text, is hard to read. Google inbox does have buttons in their title bar with text, the word Inbox is a button. whether it's flat or raised at least the text should be a different color at least, imho.

The Docs also imply that not applying accent would make the button white (side note that's what angular material design does)

![inbox white button](https://cloud.githubusercontent.com/assets/5517/17023927/7644ce92-4f1b-11e6-8fa3-d695e72d2d12.png)

**Comment by xenoterracide** [comment]
![full toolbar](https://cloud.githubusercontent.com/assets/5517/17024187/8d8cefb6-4f1c-11e6-8eb4-b56c34c0c6f5.png)

so, It would seem that a flat button should look like the header, but it doesn't

**Comment by Garbee** [comment]
Certain color builds have coloring that is off due to how the calculations were done in 1.x. At this point it is a breaking change to address these since people are already relying on them functioning as they are.

**Comment by xenoterracide** [comment]
by certain color builds that includes the default I guess

![image](https://cloud.githubusercontent.com/assets/5517/17041841/9ea11b04-4f6e-11e6-8131-15e04b8ec80c.png)
