### ISSUE TITLE
Timinig issues with SystemJS

### ISSUE THREAD

**Issue by danieladonna** [google/material-design-lite#4586]
Hello,

when loading mdl with Systemjs the material.js is executed before the dom is ready. The stuff from window.addEventListener('load'.... is not executed at all. I think it's a timing issue. Do you plan to solve this issue or what is your proposal to be able to load mdl with Systemjs?

Thanks a lot.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Since your question is specifically about how we interact with some other JS code that isn't something we are able to support here.

Thank you.
