### ISSUE TITLE
componentHandler.upgradeElement does not apply styles to an updated checkbox component

### ISSUE THREAD

**Issue by LukeSwart** [google/material-design-lite#4593]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

1.1.3 (via npm, but also tested using the script tags to the source)

> What browser(s) is this bug affecting (including version)? 

Firefox and Chrome

> What OS (and version) are you using?

I am using Arch Linux, details here:

```
uname -a
4.6.4-1-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
```

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

I have a repo where one can easily reproduce this bug. Instructions are here:
https://github.com/LukeSwart/mdl-choo-test#how-to-run-this-demo

In short, I am unable to render a checkbox component without using `componentHandler.upgradeDom()`. Here is the section of the code where `componentHandler.upgradeDom()` is working, but `componentHandler.upgradeElement(e)` is not working: https://github.com/LukeSwart/mdl-choo-test/blob/master/components/checkbox.js#L13-L28

> What is the expected behavior?

That example is supposed to render an MDL checkbox component in the browser.

> What is the actual behavior?

That example only renders a regular checkbox, without the MDL stylings.

> Any other information you believe would be useful?

 I was able to make this work for the slider component using `componentHandler.upgradeElement(e)`, but it does not work with the checkbox component.

**Comment by Garbee** [comment]
Please provide a reproduction case using something like [codepen](http://codepen.io) please. This is working fine here, so something smells like external code causing the issue. Or bad markup structure.

**Comment by LukeSwart** [comment]
@Garbee Thanks for the feedback! 

I think you are right - that this is an issue with the external code that I am using.

I am closing this issue because it is technically not relevant.
