### ISSUE TITLE
Spinner missing after parent becoms visible

### ISSUE THREAD

**Issue by kriddy800** [google/material-design-lite#4594]
I'm using IE 11.0.9600.18349 and have noticed the following issue.  If you set the parent container to display none and then revert the child spinner is no longer visible in IE.  Here is a [codepen](http://codepen.io/kriddy800/pen/xOjmLq?editors=1111) reproducing the issue.  I have attempted calling the componentHandler to update the DOM but the spinner remains hidden.  This only happens on IE not on chrome or firefox

To reproduce:
-open codpen
-SEE spinner in transparent container
-click button
-SEE parent and child now hidden
-click button again
-EXPECTED parent and child now visible again
-RESULTS parent is visible but child is not

**Comment by kriddy800** [comment]
A way I have managed to get around this issue is by setting the parents height to 0 and removing the is-active class on the spinner.  The spinner still takes space in the DOM doing this but I can position it out of the way.

**Comment by traviskaufman** [comment]
Looks like it has to do with [this IE11 bug](https://connect.microsoft.com/IE/feedbackdetail/view/941104). It's not that the spinner is not visible, it's that the spinner is not _animating_ . For example, in your pen in IE, try opening `F12 Developer Tools` and toggling the animation property on the different `mdl-spinner__layer` elements. You'll notice that it triggers an animation but then stops.

This is unfortunately an IE problem and MS pretty much doesn't patch any IE11 bugs except for critical security issues (I've filed bugs with them in the past around their animation engine and have received that response). If your workaround works however, I'd suggest sticking with that.
