### ISSUE TITLE
Checkboxes that are compiled from material-design-lite.scss are not visible when checked!

### ISSUE THREAD

**Issue by imalitavakoli** [google/material-design-lite#4596]
Hi,

I'm using v1.1.3 and this issue is actually true in all major browsers...

If we use the hosted css file, `<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">`, the checkbox is perfect like how we can see in the documentations.

However, if we use the sass version, `bower_components/material-design-lite/src/material-design-lite.scss`, when it is compiled to css, the checkbox doesn't show its tick svg icon when it is checked!

As you can see in the below image, the checkbox is checked (it is blue, using the primary color) but the tick icon doesn't appear.
![checkbox is not visible](https://cloud.githubusercontent.com/assets/12460805/17127177/c2baae08-5318-11e6-951b-baab9974a87e.png)

I'd like to use the sass version so that I can control my accent and primary colors locally by overriding variables instead of going to the [customize page](https://getmdl.io/customize/index.html).

**Comment by Garbee** [comment]
Check your DevTools and make sure the checkbox svg itself is being served properly please.

**Comment by imalitavakoli** [comment]
Yes the svg is not served... `jquery-1.7.2.min.js:1 GET http://localhost:9001/images/tick-mask.svg?embed 404 (Not Found)`
Is there something that we can do about it?

**Comment by Garbee** [comment]
Make sure the SVG is copied and served properly. This isn't an MDL issue but instead an issue with your applications build pipeline. Support for that is out-of-scope of this issue tracker as we focus only on issues with our produced output. If you need assistance figuring out what to do from here, you can try StackOverflow or other general support areas online.

Thank you.

**Comment by aderbas** [comment]
I copied the svg files to my assets folder and in my "styles.scss"
```
$image_path: "assets/" !default;
@import 'node_modules/material-design-lite/src/material-design-lite';
```
it works fine,.

**Comment by lucaswitch** [comment]
To solve this bug replace "$image_path: '/images' !default; to "$image_path: 'images' !default;" in /src/_variables.scss then compile material-design-lite.scss.
