### ISSUE TITLE
request email obfuscator component to avoid spam

### ISSUE THREAD

**Issue by condor0765** [google/material-design-lite#4606]
Would it be possible to introduce a email obfuscator?

## Feature Requests

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

mdl-1.x

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

Feature request

**Comment by Garbee** [comment]
As this isn't defined by Material Design it is up to developers to implement this as they need it. We are aiming to provide only what is specified by Material Design in order to limit the scope of the project's maintenance needs.

Thank you.
