### ISSUE TITLE
Create initial mdl-theme library

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4609]
- [ ] **Theme Variables**

| Theme Component | Description | Sass Variable | Custom property | Default value |
| --- | --- | --- | --- | --- |
| Primary Color | Theme's primary color | `$mdl-theme-color-primary` |  `--mdl-theme-color-primary` | `#3F51B5` (Indigo 500) |
| Accent Color | Theme's accent Color | `$mdl-theme-color-accent` | `--mdl-theme-color-accent` | `#FF4081` (Pink A200) |
| Background Color | Theme's background color | `$mdl-theme-color-background` | `--mdl-theme-color-background` | `#fff` (White) |

- [ ] **Text Color Helpers**

Given a background color, and an optional text "class" / "importance" (e.g. `primary`, `secondary`, `hint`) - which defaults to `primary` - return the correct color (either dark or light) of the text to place on that background.

**Comment by Garbee** [comment]
Something else needed within the theme boundary is the media query breakpoints. We can use [custom media queries](https://github.com/postcss/postcss-custom-media) to keep them consistent and able to be rolled out to clients down the road. This way all of the components that need breakpoints have a common set to rely upon.

**Comment by traviskaufman** [comment]
Theming brainstorm iteration: https://docs.google.com/document/d/1wy4EIy463vP8SegC6wrKf07QR41bwDuRcMIXPnL-U2o/edit#

Color classes will be dropped from mdl-typography and rolled into mdl-theme.
