### ISSUE TITLE
Icon fonts and accessibility

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#461]
## Problem

The icon fonts cause some issues with accessibility, primarily that screen readers will read the text out loud. This came to my attention via a [G+ Post](https://plus.google.com/115994601702879969997/posts/6XcHKNyrR13).
## Action:

[Filament Group](https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html) has a good write-up on how to handle icon fonts. We should summarize this for developers somehow with general guidelines on applying a11y aid in icons. Linking off to this article for the adventurous to get more information.
- [Font Awesome](http://fontawesome.io/accessibility/) as well for more.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/64
