### ISSUE TITLE
Investigate BrowserStack as an alternative to Sauce Labs

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4613]
We've been experiencing a lot of false negatives using Safari and Edge on Sauce Labs, which has caused us to disable running tests in these environments temporarily (#4612). Because of this, we should look at [BrowserStack]() and see whether or not their test infrastructure for their open source plan would be more reliable.

**Comment by Garbee** [comment]
Travis has the account there now with the proper resources we need. He'll handle investigating the service and how it plugs into our CI infrastructure.

**Comment by traviskaufman** [comment]
Closing; SauceLabs is working out fine for us so we'll probably stick with it for now.
