### ISSUE TITLE
Add Ripples to components which need it

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4614]
- [ ] Regular buttons
- [ ] FABs
- [ ] Checkboxes
- [ ] Lists (when interactive, e.g. `mdl-list-item--interactive`)

Pending #4467

**Comment by Garbee** [comment]
Quick reminder on implementation with this. The component here will need to add a class which will essentially disable (constant `opacity: 0` should do the trick) on the before/after psuedo elements. Then enhance the node with the proper events to handle ripple effects. This way it is enhances the base and doesn't rely on it or conflict against it.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/20
