### ISSUE TITLE
Missing docs on Icon font

### ISSUE THREAD

**Issue by igorsantos07** [google/material-design-lite#4620]
The Getting Started guide does mention we should include the icon font, but on the Styles guide there's only a huge explanation on CSS and SVG sprites and whatnot... Shouldn't that page first reference the icon font, it's basic usage and link to the [MD Icons](http://google.github.io/material-design-icons/) page instead/as well?

**Comment by Garbee** [comment]
If you feel an improvement can be made to the 1.x docs then the `mdl-1.x` branch is open for PRs. The core team is focusing fully on V2 and will only address critical problems with V1 going forward.

We understand that the docs are lacking in quite a few areas for 1.x. So far though there hasn't been much confusion around this topic that we have noticed.

Thank you.
