### ISSUE TITLE
What exactly are the -js- classes?

### ISSUE THREAD

**Issue by igorsantos07** [google/material-design-lite#4621]
A first-time user here...
I first went through the Getting Started page, selected a palette, installed the libraries into my system and saw some of the components pages and the Styles page as well to start using them.

Most of the examples and walkthroughs use the "plain" and "javascript" classes, such as `mdl-textfield mdl-js-textfield`, but there's no explanation of what's that JS class or what it does (in a place I've seen / looked for). I can guess it's for adding effects... but what effects? And why a styling class for behavior?

I can see text fields have that fancy border change, but what effects would happen in `mdl-js-layout`, for example?

**Comment by Garbee** [comment]
You can see the discussion in issue #246 for why we have these.

V2 we are going to make manual construction the preferred and default way to instantiate the classes. The autoloader will be secondary.

Thank you.
