### ISSUE TITLE
The buttons don't work on safari. is there a fix to this

### ISSUE THREAD

**Issue by PranjalDesai** [google/material-design-lite#4624]
Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.1.3

> What browser(s) is this bug affecting (including version)? 
Safari 9.1.2

> What OS (and version) are you using?
OSX 10.11.6

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

go to babyshah2016.com

> What is the expected behavior?
Button clicks

> What is the actual behavior?
the button click doesnt work

> Any other information you believe would be useful?

**Comment by kybarg** [comment]
@PranjalDesai Look into yours scripts. That is not MDL issue. If you turn off javascript at debug panel you'll see that button focus/hover animation work.

**Comment by Garbee** [comment]
Please provide a minimal reproduction sample on a site like [codepen](http://codepen.io).

**Comment by PranjalDesai** [comment]
@kybarg This is almost my first time doing anything with web. Could you please help me debug my problem? Thanks.

**Comment by kybarg** [comment]
@PranjalDesai I've had a look at your site, seems working to me now. If you want make `click` event more visible try adding `mdl-js-ripple-effect` class to enable `ripple` effect.

**Comment by PranjalDesai** [comment]
@kybarg It works on Firefox and Chrome but it doesn't work on Safari and thats the problem

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Since there isn't a direct reproduction case showing a problem within MDL there is no action the team can take here.

Thank you.
