### ISSUE TITLE
How can i build V2 on Windows?

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#4625]
Using master **branch** and having too many issues while building. Couldn't find aby isntruction for Windows users.

**Comment by Garbee** [comment]
V2 currently has no support. We will help out once alpha begins. Currently you build `master` at your own peril.

We understand this can be frustrating, but we are still deciding on the final pipeline and architecture ourselves. So while the foundation is still being worked out it simply isn't feasible for us to help everyone as well build it on their own.

**Comment by Garbee** [comment]
FYI I just updated the `master` branch with extra tools to abstract out the system commands we were relying on. That should solve the initial issues building.

Still no direct support though, if we change things before alpha I can't guarantee we will make sure it works on Windows. That is an extremely low priority while we are still churning over the architecture and tooling flows.

**Comment by kybarg** [comment]
@Garbee Thank you
