### ISSUE TITLE
MDL portfolio template header logo issue with iPhone / iPad version of Safari

### ISSUE THREAD

**Issue by terlandark** [google/material-design-lite#4636]
On the portfolio template (https://getmdl.io/templates/portfolio/index.html) the .iscompact for the class "portfolio-logo" doesn't appear on iPhone / iPad Safari when the page is scrolled. The waterfall for the header area works fine, except the background logo image doesn't appear.

**Comment by Garbee** [comment]
Thanks for the report. The core team is focusing on the complete rewrite for v2. Therefore, we won't be addressing any non-critical issues with V1 going forward. As such, we won't be triaging or taking action here. We do understand that one of our templates isn't working as expected, however our focus is on the work that will provide the most benefit to developers.

If anyone from the community would like to triage this and fix the template, `mdl-1.x` is open for community PRs to continue maintaining the existing system while V2 is in development.

Thank you.
