### ISSUE TITLE
[Request] Generate Externs for v2

### ISSUE THREAD

**Issue by flyboarder** [google/material-design-lite#4641]
Hello, glad to hear work has begun on v2.

I'd like to request that google closure library externs are generated once v2 is complete.

**Comment by traviskaufman** [comment]
Our current plan is to tackle this during either around or after our beta launch. We're thinking of writing typescript definition files, which could then be translated into closure externs via [Tsickle](https://github.com/angular/tsickle).

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/43
