### ISSUE TITLE
Can't Close Modal when form is included in it

### ISSUE THREAD

**Issue by maroof-ahmad** [google/material-design-lite#4642]
> MDL Version - 1.1.3

>Browser - Google Chrome Version 51.0.2704.106 m (64-bit)

> Windows 10

> http://codepen.io/anon/pen/xOQGKb

> The model Should have Closed

> Model didn't close

**Comment by routegroup** [comment]
@maroof-ahmad 

You have to select all buttons because right now it selects only one element.

http://codepen.io/fudin/pen/ZOmpqV

I suggest you to change selector from global to some class or other.
