### ISSUE TITLE
Text fields label position bug with Vueify

### ISSUE THREAD

**Issue by vadimsg** [google/material-design-lite#4648]
Using text fields in Vueify template I got a nasty bug, label doesn't render in right position [image](https://s9.postimg.org/9kik9qjzj/Screen_Shot_2016_08_09_at_23_48_45.png). Other components which I tested worked fine.

Is there any fixes for this one?

https://github.com/vuejs/vueify

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
