### ISSUE TITLE
Firefox 49.0b1 breaks Checkbox Style

### ISSUE THREAD

**Issue by DarkAtra** [google/material-design-lite#4649]
So the new Firefox beta seems to break the css mask for checkboxes. This Bug is occuring on the getmdl.io page (https://getmdl.io/components/index.html#toggles-section) and it only happend with Firefox 49.0b1 (Windows 8.1 Pro 64 bit) so far.

To reproduce just visit this page [getmdl.io](https://getmdl.io/components/index.html#toggles-section)

**What is the expected behavior?**
The checked Checkbox should look like this (using Chrome):
![Checkbox in Chrome](https://cloud.githubusercontent.com/assets/1337440/17539049/373c9154-5eab-11e6-8bc4-ffef55b25d6d.PNG)

**It actual looks like this (in Firefox 49.0b1):**
![Firefox 49.0b1](https://cloud.githubusercontent.com/assets/1337440/17539067/5ad64f7e-5eab-11e6-965e-65624247db2c.PNG)

Removing the mask css-property from class mdl-checkbox__tick-outline seems to fix it.
This could be a browser version specific bug, but i still want to give that information to you in case it persists in the next firefox release.

**Comment by DarkAtra** [comment]
I can reproduce this in Firefox 49.0b1 (Android 6.0.1).

**Comment by Garbee** [comment]
Please file a bug upstream with Mozilla as this is a regression in their engine they should be aware of. Nothing we can really do unless Mozilla shows where this change is in fact on purpose and won't be changing.

**Comment by karlcow** [comment]
This was fixed! Thanks a lot. And will be upstreamed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1294171
