### ISSUE TITLE
Site Showcase Request

### ISSUE THREAD

**Issue by wasder** [google/material-design-lite#4672]
Minecraft server website made with MDL.

http://randomcraft.ru/
![randomcraft.ru](http://i.imgur.com/HqQRDCx.jpg)

**Comment by shmshd12** [comment]
Even though you are using components of mdl, this website doesnt have a feel of Material Design.

Caught a bug at first look too :
[Tab border misaligned](http://imgur.com/x8tQRMO)

**Comment by wasder** [comment]
Updated.

**Comment by m-kermani** [comment]
@wasder  Good job, and thanks for your efforts
But I think, it does not look like Material design. You can take a look at https://material.google.com/
