### ISSUE TITLE
Menu is not showing in Google Map's InfoWindow when clicked

### ISSUE THREAD

**Issue by technowar** [google/material-design-lite#4676]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.1.3

> What browser(s) is this bug affecting (including version)? 
All

> What OS (and version) are you using?
El Capitan

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Inside a Google Map's InfoWindow, add a Material Design Lite Menu.

https://plnkr.co/edit/vkkYkzZuEj6bgBXaZORZ -- input yer own Google Map API Key please.

> What is the expected behavior?
Should display the menu

> What is the actual behavior?
Menu is not displaying

**Comment by Garbee** [comment]
This is not an intended use for MDL 1.x therefore it is non-critical to core. The core team is working towards 2.x and we can try to keep this use-case in mind with implementing issue #4474. However, we won't be taking any action to address this in 1.x ourselves.

If someone from the community wants to track this down and address it in a non-breaking way, `mdl-1.x` is open for PRs.

Thank you.
