### ISSUE TITLE
Hide cell in phone with High Resolution

### ISSUE THREAD

**Issue by Pantic14** [google/material-design-lite#4684]
I have a problem. I have to use "mdl-cell-hide-desktop" but this code use the size of screen and there are phone who resolution is like a desktop, and this function don't run.
Is there any solution for this?

**Comment by robertvasile** [comment]
you should play with media queries and pixel ratio

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

There is nothing we can do about this internally. It is too niche for us to work on internally as it won't provide a MD alignment benefit to the majority of users.

Thank you.
