### ISSUE TITLE
[Component Request] Hero Image

### ISSUE THREAD

**Issue by jhx4mp** [google/material-design-lite#4703]
Throughout many Google apps, one finds many **parallax hero images**. These are often at the top of the page (think Play Music album/playlist covers, similar to [this](https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsQ0l4MWpTMmJCTm8/style_imagery_integration_hero1.png)), although they are sometimes found within the page (like the Google Calendar [month breakers](https://material-design.storage.googleapis.com/publish/material_v_9/0B6Okdz75tqQsbUk0Z0FvdWxYYnM/style_imagery_integration_hero2.png)). According to the Material Design [Imagery specification](https://material.google.com/style/imagery.html), "They serve to draw in a user, provide context about the content, or reinforce the brand."

The parallax effect (i.e. the image scrolling more slowly than the main content) gives a delightful aesthetic feel. However, the spec sheet does not explicitly mention the effect; it seems to be implied throughout the document. Personally, I feel that a hero image in a material setting would seem out of place without the added scrolling effect.

Thoughts on the possibility of implementing this feature in MDL?

**Comment by Garbee** [comment]
Unless the spec team directly specifies something this complicated there is nothing we can do to handle this. Parallax scrolling is very complicated and specific to each given application and their content and node structure how it should be handled. Providing a generic method is simply getting too deep without direct specification from the MD team. Even then, the scope is still quite large and unlikely to be implemented.

This is a feature developers will need to implement on their own in any given project.

Thank you.
