### ISSUE TITLE
android default browser top navbar side navbar fotter menu doesnt show and layout not resize correctly

### ISSUE THREAD

**Issue by flint002** [google/material-design-lite#4706]
i use this template https://getmdl.io/templates/android-dot-com/index.html 
on desktop bwoser chrome firefox opera working awesome
but on android default browser top navbar side navbar  fotter menu doesnt show  and layout not resize correctly

Mobile browser detected.
Mozilla/5.0 (Linux; U; Android 4.2.2; en-gb; GT-I9060 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

mobile browser detected.
Mozilla/5.0 (Linux; U; Android 4.4.2; id-id; SM-T311 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30

Mobile browser detected.
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SM-G355H Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30

![octocat](https://lh5.googleusercontent.com/-YZH5esZG09w/V8Z9BBtFE7I/AAAAAAAAAJA/1CqK1WI-hTU6tJqCK46xlmqzDIJErwIjwCL0B/w343-h548-no/6373295405183847265%253Faccount_id%253D1)

![octocat](https://lh5.googleusercontent.com/-xm76Ta_9jPQ/V8Z85j5FKuI/AAAAAAAAAIw/dWQ83QWNpq8aZwb8_iw0YA8sSvRH2-6ZQCL0B/w343-h548-no/2256697165961601600%253Faccount_id%253D1)

and from showcase https://rework.withgoogle.com/
![octocat](https://lh3.googleusercontent.com/-By1XkfdyTk0/V8ahHx1bDnI/AAAAAAAAB80/P18SkM6nngUgGFtr0Y2eFfF9OTXDX0BWwCLcB/s512/unnamed.png)

what should i do ?

**Comment by Garbee** [comment]
MDL does not support the built in Android browser rendering engine. It is on developers to handle these cases in their own code to make it work if they need it.

Thank you.
