### ISSUE TITLE
Commercial Theme License

### ISSUE THREAD

**Issue by blitzwebtech** [google/material-design-lite#4714]
Hello, 

Apologize for this question. I am not sure about the Apache license. I see some people adopted it for free themes around and it seems fine.

I am not sure if it's allowed to adopt/integrate MDL to theme for sell, like themeforest or others? License and attribution will be kept for sure.

Thanks!

**Comment by Garbee** [comment]
You [should be fine](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) using it in paid themes so long as the license is included for MDL. Just obey the license as best you can. We are not lawyers and can't give any real direction here. If you are worried you are on some obscure line of usage, then get in touch with your lawyer to help sort it out.

Thank you.

**Comment by blitzwebtech** [comment]
Thanks so much Garbee for that awesome [link](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)). It explains more clearly and makes more sense, instead of the [original license page](http://www.apache.org/licenses/LICENSE-2.0). Cheers :)
