### ISSUE TITLE
Is there any easy way/guide on how to create a vertical slider?

### ISSUE THREAD

**Issue by igorsantos07** [google/material-design-lite#4720]
I'm having a hard time creating a vertical slider and I was wondering if I could get any help from the developers or any other that have stumbled upon this as well.

I made a [small codepen](https://codepen.io/anon/pen/NRPbpr) sampling my tries on this. Basically, it's hard to position the slider correctly after rotating it...

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
