### ISSUE TITLE
How to apply material design lite to asp .net form buttons?

### ISSUE THREAD

**Issue by gkn06** [google/material-design-lite#4721]
I am trying to materialize the button (ASP.NET web form control). Button is materialized but unable to get ripple effect. Actually this works for normal button (HTML control).

**## HTML Snippet**
```
<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
  Button
</button>
```

This works perfectly with ripple effect.

**## ASP.Net Snippet**
`<asp:Button ID="Button1" runat="server" text="button" CssClass="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--raised mdl-button--accent"/>`

This is not working as expected. I was searching this issue and finally got [this link](http://stackoverflow.com/questions/31790302/how-to-apply-google-material-design-to-asp-net-controls-i-e-checkbox-button-a). Anyways I cant solve the issue. The problem is I cant get ripple effect for asp.net controlled button. IS there any way to do this?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
