### ISSUE TITLE
Since v1.2.0, the drawer button is not well aligned on large screens

### ISSUE THREAD

**Issue by osechet** [google/material-design-lite#4723]
Tested on Chrome and Firefox, from v1.2.0, the drawer icon is not well aligned on large screens; it's too low.
You can see the difference in the 2 following codepen when the view is bigger than 1024px:
[v1.1.3](https://codepen.io/osechet/pen/XjJOdO)
[v1.2.0](https://codepen.io/osechet/pen/VKYgjv)

**Comment by Garbee** [comment]
Working on this in PR #4675
