### ISSUE TITLE
Direct hash URL does not scroll automatically to the ID

### ISSUE THREAD

**Issue by shmshd12** [google/material-design-lite#4726]
When this [example](http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-D) is clicked you are automatically scrolled to Method D of the page. But the same method used in MDL does not do anything. Page is always at the top. Manually clicking the button linked with the id works well.

I guess v2 rewrite would fix this, but is there any hack for this now?

Does not work in mdl 1.2.0 and 1.1.3.

**Comment by Garbee** [comment]
Duplicate cause of #4140. User-land fix for this is listen to the upgrade event on the layout, check for URL hash and if found do the scroll to it.

**Comment by shmshd12** [comment]
I tried [#1120](https://github.com/google/material-design-lite/issues/1120#issuecomment-169090777) this solution and no changes! & also tried changing `mdl-layout` `height `to `100%` and still the same.
