### ISSUE TITLE
Keffi Polo

### ISSUE THREAD

**Issue by mustiag** [google/material-design-lite#4735]
This is a simple website for keffi polo ranch, one of Nigeria's most prestigous polo clubs. Made using MDL and a ROR CMS. [keffipoloranch.com.ng](http://keffipoloranch.com.ng).
![screen shot 2016-09-11 at 1 10 09 pm](https://cloud.githubusercontent.com/assets/11164716/18417199/2cbe5d68-7821-11e6-9b2a-61853b541b85.png)

**Comment by frasurebuilds** [comment]
The site does not follow the Material Design guidelines.
https://material.io/guidelines/
Feel free to close this issue.
