### ISSUE TITLE
Cards with Input Fields

### ISSUE THREAD

**Issue by flyboarder** [google/material-design-lite#4736]
Hello, just a small suggestion for v2.

Since cards are used for a variety of things, it would be nice to have an "empty" card that allowed input fields for the title / content. 

Currently placing an input field in the title causes the label to not function correctly and is a weird input box size.

Just a suggestion, cheers.

**Comment by Garbee** [comment]
Can you point to where this is defined in the Material Design specification please?

If it isn't currently defined then we'd need to get in touch with the MD team and see if it is something they'd want to account for. In which case we'd need a compelling use-case to show to get the idea across.

Thank you.

**Comment by flyboarder** [comment]
@Garbee https://material.google.com/components/text-fields.html#text-fields-input Example image on the right. I am trying to do exactly this.

**Comment by flyboarder** [comment]
Note: I updated the link.

**Comment by Garbee** [comment]
That is in an application bar, not a card.

**Comment by flyboarder** [comment]
@Garbee Thanks for clearing that up, do you know if v1 MDL currently supports this use case? I have not attempted with the layout header as of yet. It seems to me that a card would be the correct alternative for this usage in a desktop view instead of mobile?

I cant seem to find a demo correctly displaying this use case, on desktop or mobile.

Either way we may want to confirm or deny with the MD team, how this use case should be handled on both mobile and desktop views.

**Comment by Garbee** [comment]
No, we don't support that in V1. It is pretty complex with our support requirements.

cc @traviskaufman here to look into anything that we could use MD guidance on.

**Comment by traviskaufman** [comment]
Hey @flyboarder,

you will 100% be able to do this with v2!

It would be relatively simple for you to put a text field (see #4479) inside of a `mdl-card__title mdl-card__title--large` element (see https://github.com/google/material-design-lite/tree/master/packages/mdl-card#usage). If you're feeling adventurous and want to check out master, feel free to try it out yourself. 

I hope this clarifies your suggestion! If so, please close the issue. Thanks!

**Comment by flyboarder** [comment]
@traviskaufman seems #4479 is still pending, nothing in master yet for inputs?
I will wait for v2-alpha and give it a try then, I couldn't groke the developer docs enough to contribute.

Closing this issue as you stated, it will be supported in the future.

**Comment by traviskaufman** [comment]
@flyboarder yup still pending. If you want a clearer timeline of when we'll get to it than GH issues, check out our [Pivotal Tracker](https://www.pivotaltracker.com/n/projects/1664011).
