### ISSUE TITLE
[Request] Common Component Sizes

### ISSUE THREAD

**Issue by flyboarder** [google/material-design-lite#4737]
One of the things that Semantic UI does well is component sizes, where all components come by default in multiple sized version.

**Comment by Garbee** [comment]
Our sizing follows Material Design guidelines. Anything outside of that is on developers to implement on their own.

We understand other frameworks and libraries provide this functionality. However, it goes against what MDL is trying to do. Therefore we won't be implementing this functionality unless multiple sizes are defined by the MD specification.

Thank you.
