### ISSUE TITLE
Tabs do not work correctly with React & react-router

### ISSUE THREAD

**Issue by vincaslt** [google/material-design-lite#4742]
I have implemented my own Tabs and Tab components in react, that use the same html code as in MDL examples, however when I try to navigate it just jumps to root page like: `localhost:3000/#tab0`.

If i refresh my current page first, and then navigate, it changes tabs correctly. I noticed the same problem in materialize-css, and that's why I tried moving from it, how do I solve this?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
