### ISSUE TITLE
mdl-animation: Implement event name queries

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4745]
We've got stuff in our constants files that look like:

``` javascript
return {
   ANIM_END_EVENT: (() => {
     const d = document.createElement('div');
     return 'transition' in d.style ? 'transition' : 'webkitTransition';
   })();
};
```

This is problematic since these constants files are evaluated at module load time, and used within foundation classes, which means that it implicitly makes our foundation classes require a DOM context before they're initialized. This has negative implications for frameworks which leverage server-side rendering.

We need to break these out into helper methods and put them in mdl-animation e.g.

```
export function getTransitionEndEvent(windowObj) {
}

// ....
```

This will ensure that we're not trying to work with any web platform context within our foundations until at least `init()` is called.
- Determine whether or not we need webkitPrefix

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/17
