### ISSUE TITLE
Shadows of menu don't disappear

### ISSUE THREAD

**Issue by wb9688** [google/material-design-lite#4747]
> What MDL Version are you using?

v1.2.1

> What browser(s) is this bug affecting (including version)?

Firefox 48.0-2

> What OS (and version) are you using?

Debian GNU/Linux stretch/sid

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

Go to the [example](https://getmdl.io/components/index.html#menus-section) and press the menu button twice

> What is the expected behavior?

The shadows should disappear

> What is the actual behavior?

The shadows don't disappear
![Screen record](http://i.giphy.com/l0MYu1L2yVfUXl3I4.gif)

**Comment by Garbee** [comment]
duplicate of #4549
