### ISSUE TITLE
standardize on scss approach for RTL

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4749]
cc @sgomes 

We've been taking different approaches for RTL depending on what the component is and who built it. We should probably have a consistent method of doing RTL across components, and factor that out into some sort of scss utility that can be shared across our codebase.

**Comment by sgomes** [comment]
Yup, I agree. 👍  There are interesting ideas on different components, which we should standardise in a single place.

**Comment by traviskaufman** [comment]
# Notes

* `mdl-rtl` mixin similar to `mdl-theme-dark`
* `mdl-rtl-reflexive($property-name, value, $property-rll-fallback: auto)` mixin which uses `mdl-rtl`

**Comment by MohammadYounes** [comment]
Why not to save the effort and automate the whole process ? See [material-design-lite (RTL)](http://rtlcss.com/cdn/css-frameworks/material-design-lite/#live-preview)

**Comment by Garbee** [comment]
Automation may not be 100% accurate to users and/or the specs needs. We need the ability to handle both as completely as possible.

**Comment by MohammadYounes** [comment]
Yes it can, see [processing directives](http://rtlcss.com/learn/getting-started/why-rtlcss/#processing-directives).

**Comment by traviskaufman** [comment]
@MohammadYounes thanks for sharing RTLCss. It looks like a really cool project. However, it's not a good use-case for us. As @Garbee mentioned, there are multiple scenarios where we need fine-tuned fidelity over the directionality of our components. Furthermore, we don't want to ask users to include an additional CSS file for RTL context, and instead provide one CSS file which has styles for both. This is especially important since we're not only providing one overall CSS file, but individual CSS files per component as well. 

Closing as we already have a solve in place for this.

**Comment by MohammadYounes** [comment]
@traviskaufman 

That's also possible, see [postcss-inline-rtl](https://github.com/jakob101/postcss-inline-rtl) which gives you one file (Currently used by [Office Delve](https://medium.com/@delveeng/how-we-build-css-in-office-delve-3440ae67bae9#d801) team).

Regardless of how you do it, I am happy that you'll be providing RTL support :) 

Thanks!
