### ISSUE TITLE
Incorrect Search Icon Layout in Dashboard Template

### ISSUE THREAD

**Issue by Mugen87** [google/material-design-lite#4757]
The position of the search icon on the following demo page looks wired. https://getmdl.io/templates/dashboard/index.html 

![image](https://cloud.githubusercontent.com/assets/12612165/18548350/8664b202-7b48-11e6-87b5-05ef7f837f77.png)

When i disable certain CSS classes in `templates/dashboard/styles.css` via dev tools, the layout looks good.

```CSS
.demo-layout .demo-header .mdl-textfield {
  /* padding: 0px; */
  /* margin-top: 41px; */
}
.demo-layout .demo-header .mdl-textfield .mdl-textfield__expandable-holder {
  /* bottom: 19px; */
}
```

![image](https://cloud.githubusercontent.com/assets/12612165/18548535/8e26b354-7b49-11e6-9561-520117538f83.png)

Tested with Chrome 53.0.2785.116, Firefox 48.0 and 9.1.3 (11601.7.8) on OS X 10.11.6.

**Comment by Garbee** [comment]
Dulicate of #4690.
