### ISSUE TITLE
dropdown menu of nav bar

### ISSUE THREAD

**Issue by wuyukewu** [google/material-design-lite#4763]
I would need to have my navigation bar contains dropdown menu.  Bootstrap provides such easy code for creating dropdown, I am very surprised that MDL doesn't has this feature for designer.  It should be a very common UI feature, and not sure why it's absent in MDL.  Does anyone know the solution or can find related code at somewhere ?  Thank you for your help.

**Comment by traviskaufman** [comment]
As stated in our [issue template](https://github.com/google/material-design-lite/blob/mdl-1.x/.github/ISSUE_TEMPLATE.md):

> The MDL core team has actively begun work on the next major version of MDL, dubbed MDL v2. Because we are a small team that's hyper-focused on delivering the best Material Design Library possible for the web, it is highly unlikely that we will be actively working on new features or making backwards-incompatible changes for MDL as it currently exists.

> If there is a non-breaking feature you would like to see implemented in mdl-1.x and are willing to contribute, we'd be happy to offer assistance with you doing so. But we will not personally be actively working on said features.

We will be implementing this in v2 (#4475), but we don't have the time and the bandwidth to work on it for v1. In the meantime, this looks it could be an adequate solution: https://www.npmjs.com/package/getmdl-select. Sorry we can't be of more help here.
