### ISSUE TITLE
The official site ripples is fine while the hosted version isn't

### ISSUE THREAD

**Issue by Kinark** [google/material-design-lite#4769]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
https://storage.googleapis.com/code.getmdl.io/1.0.0/material.purple-pink.min.css
and
https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js

> What browser(s) is this bug affecting (including version)? 
All

> What OS (and version) are you using?
Windows 10

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Just click it

> What is the expected behavior?
The slow and fine ripple effect obtained in the official website.

> What is the actual behavior?
Old fast, bugged and wrong ripple effect.

**Comment by traviskaufman** [comment]
Looks like you're using an older version of MDL. Note the version number (`1.0.0`) in the URL. Our current version is `1.2.1`. Can you try using these links:

https://storage.googleapis.com/code.getmdl.io/1.2.1/material.purple-pink.min.css

and 

https://storage.googleapis.com/code.getmdl.io/1.2.1/material.min.js

and see if it solves your problem?

**Comment by Kinark** [comment]
Solved! Thank you =)
