### ISSUE TITLE
CSS Scoping in v2

### ISSUE THREAD

**Issue by rj33** [google/material-design-lite#4770]
There was some discussion early this year on scoping of mdl to make it easier to use in widgets:
https://github.com/google/material-design-lite/issues/1730

I'm not that concerned with global style names given they are mdl_ prefixed, but rather the
changes to styling of basic html elements such as h,a etc.  This means you can't create a widget without the page that is using it completely buying into default element styling from mdl (or having to override on an element by element basis).

It was mentioned that adding a scoping class (on body) was considered but had issues (e.g. ".mdl h" instead of top level "h" styling), but that this would be revisited in v2 by scoping at the component level, which would address my concern. 

I've taken a quick look at the v2 docs, but wasn't sure after reading them if these style scoping changes had made it into the current v2 code/design, so just wanted clarification on the plans for this in v2.

Regards,
Richard.

**Comment by Garbee** [comment]
Yes, V2 will be 100% independent components with no global targets. `mdl-typography` on the body will provide basic styling to all the generic elements if a developer wants to opt-in to that method.
