### ISSUE TITLE
Design for old guy

### ISSUE THREAD

**Issue by wharsono1** [google/material-design-lite#4772]
Hi Guys.

Would you help me, to make design with old eye like me.
its hard to read, because light character / typhography.

Thank you

**Comment by traviskaufman** [comment]
Hey @wharsono1 ,

Thanks for your input. Accessibility, especially WRT contrast ratios, is something that we are very keen on getting correct for v2. In fact, our [v2 theming package](../tree/master/packages/mdl-theme) has mechanisms built in to ensure this. 

Although I'm closing this issue, we are 100% addressing this moving forward. Thanks!
