### ISSUE TITLE
Initial component upgrade cannot be prevented.

### ISSUE THREAD

**Issue by AlexanderOtavka** [google/material-design-lite#4780]
Initial component registration happens on page load and cannot be deferred or canceled.  This is a problem for me because I am working with the [shadydom polyfill](https://github.com/webcomponents/shadydom) and the initial upgrade prevents slot content from working properly.  This may just be a bug with shadydom, however a developer could conceivably want to defer registration for other reasons, especially if another framework isn't playing nice.

I propose the following solution.

Before loading the mdl javascript, the developer can set `window.componentHandlerConfig = { preventAutoUpgrade: true };`.  When `componentHandler` is created, the `preventAutoUpgrade` property is copied to a `componentHandler.config` object, but defaults to false.  If `preventAutoUpgrade` is true at page load time, the initial `componentHandler.upgradeAllRegistered()` call will not happen.

I'm going to go ahead and implement this on my fork, but I'll make a PR too.  Any suggestions on how to do this better are welcome.

**Comment by Garbee** [comment]
I'd rather we avoid introducing another global variable just for CH config. Why not add in a `componentUpgrading` event before the initialization happens? Which can be canceled to skip over initialization.

**Comment by AlexanderOtavka** [comment]
Ok, should I have the window fire that event on load?  I thought `event.stopPropogation()` only worked to prevent an event from bubbling up the dom.  Maybe the body or the rootElement should fire the `componentUpgrading` event?

**Comment by Garbee** [comment]
Not one window event. But, in the component handler as the component is upgrading. Fire it against the node itself which can be listened for and canceled. This provides an explicit way to stop initialization on any given component instance at any point in time instead of just during the initial page load.

**Comment by AlexanderOtavka** [comment]
Ah, smart.  I've done a little more reading, and it seems the Element.dispatchEvent() will return false if the event is canceled.  I'll update my PR.

**Comment by Garbee** [comment]
You should use `defaultPrevented` [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented) instead of checking for a cancel. That way it is clear and direct as to what will cause a bail and what won't.

**Comment by AlexanderOtavka** [comment]
Ok, sounds good.
