### ISSUE TITLE
 Fixed Up and Back Buttons - Feature Request/ Missing Documentation 

### ISSUE THREAD

**Issue by littleswany** [google/material-design-lite#4786]
Hey,

I am not sure if this would be counted a request or missing documentation so will explain what I am thinking and leave it to the powers at be to decide.

It revolves around mdl-layout--fixed-header and wether it is possible to add a fixed button for preforming functions such as back, replacing a menu open button on a home screen when using mobile devices.

An example of the usage feature would change the menu button on the main screen of a website to a back/return button when navigating away from the main home page.
Another example would be a search button taking you to a fixed search page opposed to the already implemented waterfall search.

The usage from the material design spec is found here: https://material.google.com/patterns/navigation.html#navigation-up-back-buttons 

I trust this dresses all the criteria for submitting an issue, if not I can update as required.

Noah

**Comment by Garbee** [comment]
In v2 this is possible since developers will have control over that button entirely along with its actions. In v1 it is not supported nor will it be supported. The layout is already complex enough for V1 and we'd rather limit adding any new functionality to it to keep maintaining it as-is easier.

**Comment by littleswany** [comment]
Thanks for the response, as the project milestones suggest is the release for v2 in 2021?

**Comment by Garbee** [comment]
No, it should be much sooner than that. I set 2021 just to let people know not to expect it soon months ago when we were still formulating the concepts for V2's architecture. We'll update the roadmap date once alpha launches and we can assess the remaining work more accurately.

**Comment by littleswany** [comment]
Cool, one other thing before I close this, I dint see in the project wiki or anywhere how I can get involved is this anywhere or could it be added?

**Comment by Garbee** [comment]
[V1](https://github.com/google/material-design-lite/blob/mdl-1.x/CONTRIBUTING.md) and [V2](https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md).

**Comment by littleswany** [comment]
Thanks!
