### ISSUE TITLE
Update angular2 example to ng2 final

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4788]
Now that [angular2 final](http://angularjs.blogspot.com/2016/09/angular2-final.html) has been released, we should update our angular2 example to match the idioms and structure present in the final version.

**Comment by mseemann** [comment]
@traviskaufman do you need help with this?

**Comment by traviskaufman** [comment]
@mseemann yes please! 😄  The code is in [examples/angular2](../tree/master/examples/angular2) and it was created from an older version of [angular/angular2-seed](https://github.com/angular/angular2-seed). We modified the webpack config so that we could load our scripts and styles from our `packages` dir without doing any hacky cross-transpilation.

**Comment by mseemann** [comment]
@traviskaufman ok! I'm on it 😄. I'll create a pr if I'm done!

**Comment by traviskaufman** [comment]
Thank you!

**Comment by traviskaufman** [comment]
Closed by @mseemann ✨ 👏
