### ISSUE TITLE
How to toggle menu upon user click

### ISSUE THREAD

**Issue by bojoyzhou** [google/material-design-lite#4791]
I have a table. When i click one row by right button, i hope i can control the menu to toggle.
What is recommends to do with this ?

**Comment by bojoyzhou** [comment]
![image](https://cloud.githubusercontent.com/assets/5258697/18829804/990c1bcc-8410-11e6-8dd0-d2287cfb959f.png)
just like gmail

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Material Design does not contain this type of interaction as right click is not a usable interaction on mobile interfaces. Therefore it is outside of the scope of Material Design Lite to supply a component for.

Thank you.
