### ISSUE TITLE
legal issues

### ISSUE THREAD

**Issue by JoaquimFMF** [google/material-design-lite#4796]
Hi.

I want to use the MDL in one or more web sites. However I have doubts about the legal issues regarding the "MDL", the "Material Icons" and "Roboto Font".
As a company can we use etc.? Can you enlighten me regarding the legal issues?

Best regards,
Joaquim Fernando

**Comment by traviskaufman** [comment]
Hey @JoaquimFMF 

We're not at liberty to give legal advice, given that we are not legal experts. 

All of our code is licensed under [Apache 2.0](https://github.com/google/material-design-lite/blob/mdl-1.x/LICENSE). I suggest you read over that license and consult with your legal team as to whether or not you can use MDL within your codebase.

I want to again state that _this should not be taken as legal advice, merely a suggestion on how one could proceed_. 

Sorry we can't be of more help.
