### ISSUE TITLE
Tabs not working in partial view

### ISSUE THREAD

**Issue by madhukarhere** [google/material-design-lite#4801]
Hi,

I am using the latest library of MDLite. Tabs are working fine in normal views but the same code is not working when I use them in partial view. Same is the case with the code available in your site under tabs section.

![screen shot 2016-09-28 at 7 59 16 pm](https://cloud.githubusercontent.com/assets/11751611/18917736/3d81bf58-85b6-11e6-94c5-56b653e74841.png)

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this appears to be using MDL in a template engine which isn't something we provide, it is out of scope for the issue tracker.

If you can recreate the problem in a [codepen](http://codepen.io) to provide us a reproducible test case to show the problem with what MDL provides, then we can re-open the issue and take a look at what may be causing this.

Thank you.
