### ISSUE TITLE
Misaligned search icon at Dashboard Template

### ISSUE THREAD

**Issue by rianby64** [google/material-design-lite#4805]
Hello!
In this image I [see the search icon misaligned](https://getmdl.io/templates/dashboard/index.html)
![issue](https://cloud.githubusercontent.com/assets/25993/18946804/36cf3d60-8639-11e6-823f-38b04124e48e.png)

Maybe this error is related to #4759 
Need more time to check why this happen in my chrome Version 53.0.2785.116 (64-bit) Centos 7

**Comment by Garbee** [comment]
Fixed in #4758
