### ISSUE TITLE
Tooltip focus problem on Chrome 53

### ISSUE THREAD

**Issue by carlosmourajunior** [google/material-design-lite#4810]
I try to use Tooltip with MDL in Chrome 53 and the tooltip is blurred. I can read the content o the tooltip. In other browser the Tooltip is Ok.

Afect only Chrome 53.
OS: MAC OS El Capitan

**Comment by Garbee** [comment]
This is because of some changes in the engine with GPU layers. M55 (current dev channel) fixes this problem. Nothing we should do internally since it would only be temporary and it isn't an MDL issue but a Chrome rendering engine issue.

Thank you.

**Comment by TheRojam** [comment]
@Garbee sadly i could to reproduce the problem in canavary version (55)

![Tooltips blur](https://chat.eccenca.com/api/v3/public/files/get/knxehyi4ib8wtfyp1co9kbtwzo/w1ykzfwr7iywtq3utjifo6966r/81pi9ijfspn8bppzo6p4ixscwc/wy9tsdbyjpn59kzcqgtk1khqhw/Bildschirmfoto%202016-10-05%20um%2011.44.30.png?d=%7B%22filename%22%3A%22wy9tsdbyjpn59kzcqgtk1khqhw%2FBildschirmfoto%25202016-10-05%2520um%252011.44.30.png%22%7D&h=%242a%2410%24GkMiPUM05YhCWbeyh6Dei.0Z2jcmwNjx0YUrG%2FBTiXwWs8kMrsGFe)

**Comment by TheRojam** [comment]
in canavary version (thats 55) its not fixed - see Screenshot
![Tooltip blur](https://chat.eccenca.com/api/v3/public/files/get/knxehyi4ib8wtfyp1co9kbtwzo/w1ykzfwr7iywtq3utjifo6966r/81pi9ijfspn8bppzo6p4ixscwc/wy9tsdbyjpn59kzcqgtk1khqhw/Bildschirmfoto%202016-10-05%20um%2011.44.30.png?d=%7B%22filename%22%3A%22wy9tsdbyjpn59kzcqgtk1khqhw%2FBildschirmfoto%25202016-10-05%2520um%252011.44.30.png%22%7D&h=%242a%2410%24mjJdXrKHPOT9YcG9cZBz0O7H52vmky7gSiv3izEmjc7acAIWtYrn.)
