### ISSUE TITLE
On page change Hamburger icon disappears

### ISSUE THREAD

**Issue by Allanramirez1** [google/material-design-lite#4812]
I am working with MDL with Rails, when I redirect to another view (page), hamburger icon dissapears.
I tried to add
 ```
<script type="text/javascript">
  document.addEventListener('page:change', function() {
      componentHandler.upgradeDom();
  });
  </script>
```

but does not work.

Ver: Lastest Rails, Lastest MDL

**Comment by Allanramirez1** [comment]
SOLVED:

<script type="text/javascript">
  document.addEventListener('turbolinks:load', function() {
      componentHandler.upgradeDom();
  });
  </script>

**Comment by stefanahman** [comment]
@Allanramirez1 Thanks, helped me alot!
