### ISSUE TITLE
Implement "vertical align cell with different heights in a mdl-grid"

### ISSUE THREAD

**Issue by Pantic14** [google/material-design-lite#4820]
I have a mdl-grid with different columns and rows, the problem is that the cell have different heights. To explain better I put two images:

- Now i have this -> [http://i.stack.imgur.com/KSCOz.jpg](url)
- I desire this -> [http://i.stack.imgur.com/ODjg1.jpg](url)

This style is used in [http://masonry.desandro.com/](url)

Has anyone managed to do this with mdl?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Multi-height column items are not supported by MDL as it requires JS to handle the layout. Therefore this is a support question asking how to handle custom code to achieve a problem which is out-of-scope for the issue tracker.

Thank you.

**Comment by westy92** [comment]
@Pantic14 I'm using [Masonry](http://masonry.desandro.com/) on [Checkiday.com](https://www.checkiday.com) to achieve this.
