### ISSUE TITLE
Radio button ripple does not disappear in Javascript examples on Firefox

### ISSUE THREAD

**Issue by sfdexter** [google/material-design-lite#4821]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

master

> What browser(s) is this bug affecting (including version)? 

Firefox 49.0

> What OS (and version) are you using?

OSX  10.11.6

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

step 1:  launch `npm run dev` and navigate to http://localhost:8080/radio.html
step 2: click 'Radio 1' under label 'With Javascript'
step 3: click 'Radio 2' under label 'With Javascript'

> What is the expected behavior?

ripple disappears from both buttons

> What is the actual behavior?
ripple circle remains around each radio button

> Any other information you believe would be useful?

works correctly on Chrome 53.0

**Comment by traviskaufman** [comment]
I was able to reproduce this issue by tapping with a trackpad on the radio button. When I actually depress the trackpad, it works fine. Only on taps it doesn't work.
