### ISSUE TITLE
Make snackbar more resilient to text overflow

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4828]
For a single-line snackbar, we could make it so that the text will not cause line breaks (and show an ellipses instead, perhaps). For multiline, we'd have to trust the user not to put in arbitrarily long strings of text.

Some browsers also support clamping to a certain number of lines, so we can progressively enhance for that as well

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/11
