### ISSUE TITLE
Add mechanism for allowing elements to move when snackbar is present

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4829]
- Attach css class / data attr to document element indicating that a snackbar is visible (and what type is visible)
- Create a mixin + css class combo that can be attached to elements and translates the elements using the correct easing curve, timing, and y offset depending on the type of snackbar.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/10
