### ISSUE TITLE
Radios should activate ripple when their corresponding label is pressed

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4830]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

v2 @ master

> What browser(s) is this bug affecting (including version)? 

all

> What OS (and version) are you using?

OS X El Capitan

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
1. Type `npm run dev` and navigate to http://localhost:8080/radio.html
2. Click on a label for a radio

> What is the expected behavior?

The ink ripple should activate

> What is the actual behavior?

Only the focus ripple activates

> Any other information you believe would be useful?

This is due to the fact that `isSurfaceActive` is always set to false in the radio's ripple adapter. Instead, we need to set it conditionally based on whether or not the label is being interacted with.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/9
