### ISSUE TITLE
Create initial v2 release infrastructure

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4834]
For alpha, the release needs to:
1. Run `npm test` and verifies everything works
2. Run `npm run dist` to build and minify all of the libs
3. Copy all of the dist'd components versions over to their respective packages, in a `dist/` subfolder per package.
4. Update component versions. This is probably going to be the trickiest part at this point. Preliminary thinking below.
5. Commit and tag an overarching release
6. Generate an overarching changelog 
7. Bump overarching MDL version. This can be done with a tool like [standard-version](https://github.com/conventional-changelog/standard-version), and can be applied to `packages/material-design-lite`.
8. Push changes to github
9. Publish to npm via `lerna publish --skip-git`
## Updating component versions

My preliminary thinking is we could do something as follows:
1. Gather all commit messages since the previous release
2. Parse the commit messages to figure out which component the commit references, if any. We could either extract this ourselves or use a tool like [git-commit-message-parser](https://www.npmjs.com/package/git-commit-message-parser). 
3. Analyze the commit message using a tool like [commit-analyzer](https://github.com/semantic-release/commit-analyzer) to determine the type of change.
4. Bump the version using [npm-version](https://docs.npmjs.com/cli/version) according to the change type.

Note that for some changes, like global refactors, this may not quite work. Then again, we may not release after a refactor. Otherwise, we could look and see which files in which `packages/` subfolders were changed. 

We could make this interactive at first, where every time we're about to bump a version, we prompt to confirm. Then as it stabalizes we can start making it automatic.

Additionally, Lerna has a command called [updated](https://github.com/lerna/lerna#updated) that may be useful in this case.
## Other notes

We may not want to include the Changelog within our repo, but rather add it as the tag description.

**Comment by traviskaufman** [comment]
cc @appsforartists @jverkoey anything from the Material Motion tooling side of things you'd want to collaborate and/or share regarding this?

**Comment by traviskaufman** [comment]
cc @sgomes

**Comment by traviskaufman** [comment]
So it turns out that lerna's publish command takes care of detecting which packages have changed, updating their versions, updating any dependent siblings with the new versions (🙌), and publishing the overall major version to npm.

So our release workflow - thanks to Lerna - becomes a lot simpler:

1. **pre-publish**: Test, build, and copy assets over.
2. **publish**: Simply run `lerna run publish -i`. This will tell lerna to run publish in independent mode.
3. **post-publish**: Using a personal repo access token defined in the environment (e.g. `MDL_RELEASE_GH_TOKEN`), we generate a changelog a create a new releases via the [releases API](https://developer.github.com/v3/repos/releases/#create-a-release) with the tag that lerna created for the overall repo, as well as the text from the generated changelog.

A major drawback to step 2 is that you have to enter every single version for all updated components manually, which can be error-prone. I'm going to follow up with lerna about this, but perhaps in the interim we could run a script to assist with this. It could do the following:

1. Collect all commit messages from the last release to HEAD
2. Parse each commit message via [git-commit-message-parser](https://www.npmjs.com/package/git-commit-message-parser) and group them by component
3. Analyze the commit message of each component via [commit-analyzer](https://github.com/semantic-release/commit-analyzer) and take the _most_ substantial version change.

E.g., let's say that between the previous release and now, we introduce three new commits:

1. `fix(drawer): Address silly bug`
2. `feat(drawer): Make non-destructive additive change to foundation and component APIs`
3. `fix(drawer): Address another silly bug`

The analyzer would look at the commits and determine that a _minor version update_ would be the most appropriate, since commits `1` and `3` would both be patch updates, but commit `2` would constitute a minor version update.

**Comment by rhroyston** [comment]
Not sure if this is proper channel to ask but...

Any word when v2 will be released?

**Comment by sgomes** [comment]
@rhroyston No firm dates yet, but we're gearing up towards an alpha soon.

**Comment by sgomes** [comment]
@traviskaufman How much work would be involved in building the analyser you're describing? Is it a case of just "frankensteining" a few of those packages together, or would it be a significant development task for us?

**Comment by appsforartists** [comment]
Why are you manually copying files to `dist`?

I'd expect that whatever tooling you're running would output to a `dist` folder in each package, and `lerna run dist` would kick off each package's `dist` script.

**Comment by traviskaufman** [comment]
@sgomes Given what I know now, I don't think _too_ much on our end would be involved. For the analyzer, there are already packages and tooling that get us most of the way there. Also, the releasing and changelog generation script should be relatively trivial thanks to `cz-conventional-changelog`.

**Comment by traviskaufman** [comment]
@appsforartists the way our webpack config is set up now is to output all built assets into a single top-level `build/` folder. We can then manually copy those files over to `dist` folders in their respective packages. 

Each package having its own `dist` script is something we considered, but it had a number of disadvantages:

- Duplication of scripting logic
- Either explicit reliance on build tools it does not need within `devDependencies` (and then having lerna redundantly install those tools per-repo), or implicit reliance on being housed `material-design-lite`
- Build logic distributed over multiple packages rather than being consolidated within a single source of truth.

Our goal is to keep our builds as simple as possible, as it reduces the amount of time we had to invest outside of writing components, as well as reduces the surface area for errors or misunderstanding due to complication.

**Comment by appsforartists** [comment]
Your responsibility as a package author is to provide a package that includes everything downstream authors need to consume it.  If someone's hacking on the internals such that they need access to devDependencies, it's reasonable to expect them to check out the monorepo and use whatever tools it includes.  Thus, you could write a script in the monorepo that runs on `packages/*/src` and outputs to `packages/*/dist`.

FWIW, `yarn` caches dependencies locally, so you wouldn't need to worry about installing them in each repo adding overhead if you went that route.
