### ISSUE TITLE
Cannot add tooltip dynamically

### ISSUE THREAD

**Issue by jecisc** [google/material-design-lite#4848]
**MDL Version:** v1.2.1

**Browser:** Firefox 31, Firefox 49

**OS:** OSX El Captain, Windows 10

**How I detected the bug:**

I tried to add a tooltip dynamically. I added the html and I called `componentHandler.upgradeDom();`

**What is the expected behavior:**

I expected the tooltip to works.

**What is the actual behavior:**

When I pass the mouse over the element with the same ID as the tooltip, the tooltip does not appear. There is no ".is-active" class added to the tooltip.

**Comment by jecisc** [comment]
I close it because I think this is caused by the framework I use.

**Comment by benthillerkus** [comment]
I just use getmdl.io and jQuery and it doesn't work either
