### ISSUE TITLE
[FAB with ripple] Sharp corners in Firefox

### ISSUE THREAD

**Issue by brainscript** [google/material-design-lite#4851]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

**1.2.1** (latest version from CDN)

> What browser(s) is this bug affecting (including version)? 

**Firefox 49.0** (on both :computer: desktop and :iphone: phone)

> What OS (and version) are you using?

**Ubuntu 16.04** & **Android 5.1.1**

> What are the steps to reproduce the bug?

Create a FAB with ripple like [THIS](https://jsfiddle.net/kswL773e/) ...
```html
<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
  <i class="material-icons">add</i>
</button>
```
... and click/tap hold on it.

> Can you create a plunker/codepen/jsfiddle which reproduces it?

[Yes, here you go.](https://jsfiddle.net/kswL773e/)

> What is the expected behavior?

The light or dark color that fills the FAB when you click on it should only fill the circle ...

> What is the actual behavior?

... but it fills the whole container (rectangle) while fading in.

> Any other information you believe would be useful?

![Screen recording](https://cloud.githubusercontent.com/assets/8706734/19409772/01dd403e-92dc-11e6-967d-ee6b444f848c.gif)
(The animation is showing the bug on the [blog template demo page](https://getmdl.io/templates/blog/index.html).)

**Comment by tsarapke** [comment]
Hello @brainscript. I have already created similar issue before. **[Here](https://github.com/google/material-design-lite/issues/4215)** you can read history about it. Also I want notice that this issue applicable to the angular-material (**[link to my issue](https://github.com/angular/material/issues/7745)**) and (to the best of my memory) to the **[React material implementation](http://www.material-ui.com/)**. Hope it would be useful for you.

**Comment by brainscript** [comment]
@tsarapke Ok, i'm gonna close this and +1 yours.
