### ISSUE TITLE
Issues with cards.

### ISSUE THREAD

**Issue by JustH3LL** [google/material-design-lite#4852]
Hello, I was just wondering, is it possible to have multiple cards on a single page, all of them having their own images, and is it possible to align those cards to the center?

     Thanks, 
     ~JustH3LL

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this is a general usage question and not an issue with the code provided, it is out of scope for the issue tracker.

Thank you.

**Comment by JustH3LL** [comment]
Ok thank you. Where exactly do I post on StackOverflow about my question
