### ISSUE TITLE
Error in material design spec -- easing

### ISSUE THREAD

**Issue by fulldecent** [google/material-design-lite#4855]
There is an error in the Material Design spec. 

In the animation section it describes easing curves for material leaving the screen. It mentions an easing in curve and gives parameters for the for this asymmetric curve. However, the graphic is incorrect and show a symmetric curve.

![screen shot 2016-10-16 at 12 37 39 pm](https://cloud.githubusercontent.com/assets/382183/19419078/ec8e5f02-939d-11e6-98c3-8dea6d6a77f7.png)

I am sorry if this is the wrong place to report this issue. That page has no contact information and it appears this project may be by a related team.

**Comment by Garbee** [comment]
cc @traviskaufman as he should be able to relay this to the MD spec team.

Closing the issue though as MDL is in no way capable of fixing the specification itself as that is a completely different team and project within Google.

Thank you.

**Comment by fulldecent** [comment]
Thank you @Garbee.

Hello @traviskaufman. If Google is accepting feedback somewhere, I have other corrections to submit.

**Comment by traviskaufman** [comment]
Hey @fulldecent ,

The best way to relay this would be to use the "Site Feedback" link at the bottom of the Side Nav:

![site-feedback](https://cloud.githubusercontent.com/assets/1185269/19446679/e85721e2-9467-11e6-8209-5a6847ad085b.png)

The link is present on every page so you could report your issue(s) this way. Hope this helps!
