### ISSUE TITLE
ISSUE with connection

### ISSUE THREAD

**Issue by hro2009** [google/material-design-lite#4856]
Today i got an issue with using google material design i like working with it but it destroyed my pages today as i guess you have some technical issues.
Can you fix it soon thanks.

http://prntscr.com/cvq3bh

**Comment by Garbee** [comment]
The files can be retrieved fine here. This seems like an issue specific to your network topology.

Where are you located?

Have you tried a fresh Chrome profile without any extensions?

**Comment by hro2009** [comment]
i am located in Armenia, yes i tired other browsers as well bu the same also the demo templates of the website doesnt work i cheked

https://getmdl.io/templates/blog/index.html

**Comment by Garbee** [comment]
Template is working just fine here in the US. So seems like a routing issue or a server issue with connections from that area.

cc @x1ddos to see if he has the time to look into this one at all.

**Comment by x1ddos** [comment]
Works fine in Switzerland, too, as well as in France.
@hro2009 it's a local issue on your side (ISP?), like @Garbee said.

**Comment by Garbee** [comment]
Thank you @x1ddos!
