### ISSUE TITLE
Microsoft Edge console errors due to css.map file

### ISSUE THREAD

**Issue by Lopton** [google/material-design-lite#4863]
Please include the following information with your bug report:
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
Version 1.2.1

> What browser(s) is this bug affecting (including version)? 
Microsoft Edge 38.14393
Microsoft EdgeHTML 14.14393

> What OS (and version) are you using?
Windows 10 Home

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Visit https://getmdl.io/ or any site that is using material design lite with the console open. In the console you will get 36 errors that appear to be related to the material.min.css.map file. 

> What is the expected behavior?
No errors

> What is the actual behavior?
36 errors

> Any other information you believe would be useful?

<img width="580" alt="2016-10-20 16_03_01-material design lite and 1 more page - microsoft edge" src="https://cloud.githubusercontent.com/assets/6832191/19580991/bd251e10-96de-11e6-8ebc-e8be812cf5e7.png">

**Comment by Garbee** [comment]
As this error in the sourcemap generation doesn't affect functionality, it isn't something we are going to look into for 1.x. If anyone from the community wants to dig into this and patch it, `mdl-1.x` is open for PRs.

Thank you.
