### ISSUE TITLE
Wiki for frameworks using a Virtual DOM

### ISSUE THREAD

**Issue by fgarcia** [google/material-design-lite#4876]
I love Material Design Lite, even more now after reading this one goal for V2:

> Components do not modify their own DOM structure.   Adding and removing classes and changing properties is OK, creating   and removing DOM elements is not.

I guess that goal is to improve the support for engines that manipulate the DOM like React, Incremental DOM, Glimmer, etc.

While I understand that React support issues are closed because they are not related to the project. It would be great having an official reference / comments about the compatibility with such engines. I do not mean support for things like React, but it would be great having some official comments, like in a Wiki, to grasp better the risks of combining MDL with things like React/Ember

Posts like [this](http://quaintous.com/2015/07/09/react-components-with-mdl/) which make it _look easy_, but according [this](https://github.com/google/material-design-lite/issues/1356#issuecomment-231884977) it seems there are some rough edges.

Overall just a short wiki commenting concerns, design decisions and current status of this topic would help me to choose MDL more often.

**Comment by sgomes** [comment]
@fgarcia Thanks for the feedback! MDL was not designed with virtual DOM frameworks in mind, so there will definitely be some rough edges, particularly around component lifecycle management.

If you're looking for an easier option, I'd recommend taking a look at the successor to MDL, [Material Components for the web](https://github.com/material-components/material-components-web). The architecture there was designed to make components easier to use with frameworks, and we even have some examples of how that integration would work.

Bear in mind it's still alpha, though!

**Comment by rianby64** [comment]
I hope you will keep on developing MDL for a long term. The first version of MDL is very simple and easy to use. The great part of MDL is that is possible to write apps without using any framework, I mean vanillaJS. Keep this style, please.

**Comment by Garbee** [comment]
Material Components for Web is MDLv2. Where things will move forward as they have been here, just in more alignment with the MD team itself. As Vanilla JS as we can manage for the base is still the goal.

**Comment by sgomes** [comment]
What @Garbee said :)

MDC-Web is simply a rebranded MDL v2, with the same goals and design principles. Every project needs to break backwards compatibility and release a new major version at some point, to really move forward; MDL v2 / MDC-Web is exactly that.
