### ISSUE TITLE
More of a critique than issue.

### ISSUE THREAD

**Issue by Merovex** [google/material-design-lite#4879]
Just wanted to offer a thought. Having used a few CSS frameworks in my day, I find the markup of MDL to be much. While MaterializeCss may not properly implement Material Design, its naming conventions are friendly and easy to grok. I ran into MDL because I was looking for a template to use with MaterializeCSS and didn't realize that one was a knock-off of the other.

**Comment by sgomes** [comment]
Thanks for the feedback, @Merovex! We use [BEM notation](http://getbem.com/introduction/), which can be quite verbose, but is a huge maintenance time-saver when working on large CSS projects like this one.
