### ISSUE TITLE
Investigate speeding up our webpack build

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4881]
Our webpack build is very, very, _very_ slow right now. My original guess was that this had to do with the fact that we're using a multi-entry build. However, it actually looks like this is [more efficient](https://webpack.github.io/docs/configuration.html#multiple-configurations) than splitting up our build files. 

I'd like to investigate why our builds are particularly slow and see if there's anything we can do to optimize them. 

Additionally, this would be a great time to look into switching over to Webpack 2.0, as it supports [tree shaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html) which could help us slim down the size of our output.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/8
