### ISSUE TITLE
How can I remove hover on mdl-navigation__link?

### ISSUE THREAD

**Issue by ahrherrera** [google/material-design-lite#4887]
I want to remove the hover on mdl-navigation__link, so I don't know how.

**Comment by shmshd12** [comment]
Search for this "`.mdl-navigation__link:hover{background-color:#e0e0e0}`" and remove it from the mdl css or Override it via your custom styles.css.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this is asking how to modify the core system for a custom look it is out of the scope for this issue tracker.

Thank you.
