### ISSUE TITLE
v2 build hosting

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#4892]
We should have a mechanism in place for hosting builds of MDL on `gh-pages`, for testing/review purposes. Some options:

- An `edge` or `master` folder that hosts a build of the current state of `master`, through a commit hook.
- A `stable` or `latest` folder that hosts a build of the latest release, through a publish hook.
- A collection of manually uploaded static builds, if needed.

**Comment by sfdexter** [comment]
Superseded by https://github.com/material-components/material-components-web/issues/6
