### ISSUE TITLE
Site Showcase Request: <Removed>

### ISSUE THREAD

**Issue by iKevinShah** [google/material-design-lite#4898]
* Description: Personal Blog
* Primary Link: `removing link because it shows up in Google search`

![HomePage Screenshot](https://cloud.githubusercontent.com/assets/1866752/19995168/d404949c-a27a-11e6-8b69-a117f21875cd.jpg)
![Blog post Screenshot](https://cloud.githubusercontent.com/assets/1866752/19995166/d4030c12-a27a-11e6-9a29-e7fd0b694ac3.jpg)
![Mobile Screenshot](https://cloud.githubusercontent.com/assets/1866752/19995167/d4043a92-a27a-11e6-8439-40bff9b5a872.jpg)

Simple basic Material design Resume : 

![untitled](https://cloud.githubusercontent.com/assets/1866752/19996008/6d0c3f26-a282-11e6-83b3-88308188125f.jpg)

**Comment by shmshd12** [comment]
Your Website is missing many laws of the Material Design guidelines.

**Comment by frasurebuilds** [comment]
Most of your elements are not elevated correctly. There should be no elevated material within cards. Your cards should not be within a larger 'card'. Your footer does not follow any Material Design guidelines.

https://material.io/

Feel free to close this issue.
