### ISSUE TITLE
GoogleFonts API trashing MacPro 2016 October Sierra font hinting

### ISSUE THREAD

**Issue by anyotherway** [google/material-design-lite#4899]
** PLEASE READ THIS BEFORE FILING AN ISSUE **

## Bugs

Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
Independent of version

> What browser(s) is this bug affecting (including version)? 
Safari and TOR and Epic and FireFox  

> What OS (and version) are you using?
End of last week new Mac Pro came with latest macOS Sierra

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Use any Google Font, wrecks font hinting, reboot required after deleting any Google Font download

> What is the expected behavior?
Font Hinting

> What is the actual behavior?
Really bad font hinting all system fonts. I suspect mdl templates simply relay a compatibility issue present in Google API

> Any other information you believe would be useful?
Yes, this would not be the first time Google lazy hinting has caused problems, e.g. notosans cherokee and 96 other notosans experiments.

[ @sgomes notes: heavily redacted. Please be civil, folks; nasty comments don't get your problem solved faster ]

**Comment by sgomes** [comment]
As you note, @anyotherway, this is not an issue with MDL, but rather Google Fonts. Filing an issue [there](https://github.com/google/fonts) may help; I know they tend to stay on top of new browser and OS versions, but there may be a bit of lag.
