### ISSUE TITLE
When the state of input element (type="checkbox") is altered programmatically, the UI isn't updated, even calling the upgradeElement.

### ISSUE THREAD

**Issue by tly1980** [google/material-design-lite#4906]
I try to alter the checkbox status programmatically, namely setting or removed the "checked" attribute of a input element. The UI won't change accordingly.
I've also try calling the calling

```componentHandler.upgradeElement(cbk1);``` and ``` componentHandler.upgradeDom();```

And it still doesn't work.

Here is the [codpen link](https://codepen.io/tly1980/pen/JbGyXm?editors=1111)

What is the correct way to signal the change here ?

**Comment by Thanood** [comment]
Try to use `MaterialCheckbox.check()`and `MaterialCheckbox.uncheck()` on the upgraded element container (its label).
Also in the CodePen the checkbox is somehow not upgraded correctly - it didn't have the `MaterialCheckbox` property assigned. I've added `upgradeDom()` to the pen.

https://codepen.io/anon/pen/Ypwaye?editors=1111

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

We do understand that the JS documentation is lacking for V1. With V2 we are aiming to provide full JS API coverage for the components. Until then though, checking the source to figure out the API or getting support on SO are the two best options to figure things out. Sorry about this, just something that slipped through V1 as we were rushing it out the door.

Thank you.
