### ISSUE TITLE
html template including mdl-checkbox doesn't render mdl styling for the checkbox

### ISSUE THREAD

**Issue by snitzsch** [google/material-design-lite#4916]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
Version: mdl-1.2.1

> What browser(s) is this bug affecting (including version)? 
Chrome 56, Safari 10, Firefox 49 

> What OS (and version) are you using?
macOS 10.12

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
http://codepen.io/snitzsch/pen/BQLJea
Press change template button and the list will be visible. 

> What is the expected behavior?
Checkbox should use mdl css-styling

> What is the actual behavior?
Checkbox doesn't render css-styling classes

> Any other information you believe would be useful?
I'm not sure if it is a problem of the mdl lib. It is also possible that i am don't understand the html template tag completely.

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Pointer though, you need to upgrade the component using the `componentHandler` once it is injected into the DOM. We undersatnd the docs here are lacking, but writing them for V1 is not a priority as V2 is under active development which will have far more inclusive JS usage documentation from the start.

Thank you.

**Comment by snitzsch** [comment]
Thanks for the advice!
