### ISSUE TITLE
[Component Request] Menu Bar

### ISSUE THREAD

**Issue by nh1402** [google/material-design-lite#4920]
Please include:
* A pure javascript material design version of a menu bar.
* Angular Material has this already, but was wondering if it could be added without the angularJS dependency: https://material.angularjs.org/latest/demo/menuBar
* Web app where a Menu bar is ideal for certain situations such as a WYSIWYG editor.

**Comment by sgomes** [comment]
We've moved new development to the [Material Components for the web](https://github.com/material-components/material-components-web) project, where we [already have this feature planned](https://github.com/material-components/material-components-web/issues/53) (or at least something that sounds very similar).
