### ISSUE TITLE
Investigate TravisCI Flakiness

### ISSUE THREAD

**Issue by traviskaufman** [google/material-design-lite#4922]
Our CI seems to be flaky yet again. Once we finish up the alpha milestone, we should prioritize diagnosing and fixing this issue so we can handle PR submissions reliably. Possible diagnosis off the top of my head would be that the karma tap reporter is streaming out more than TravisCI or SauceLabs can handle. The tests seem to have gotten flakier as we've added more. We may have to investigate either sharding our tests and running them via a CI matrix, figuring out how to suppress console output without losing vital information such as info on test failures, or - at worst - switching over to a different test framework which can scale out better.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/5
