### ISSUE TITLE
Does a zoom out variable exist in MDL?

### ISSUE THREAD

**Issue by udaysinghcode** [google/material-design-lite#4926]
Hey MDL Team,

I've been working with your library recently, I just wanted to know if there was anyway to mass scale the size of MDL similar to using a zoom: 0.85 in Google Chrome. In Chrome, forcing a zoom on the whole page works fine to get the element zoom out I like, but I feel like it's a very fragile piece of code that doesn't have full browser support (like it doesn't work in Firefox at all). 

Is there a way I can essentially zoom out 15% in the MDL library so I can skip on using the zoom and instead rescale the elements as if I had zoomed out to 85% on Chrome?

Thanks

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

This gets pretty specific into support for a specific integration concern. Therefore is out of scope for the issue tracker. Sounds like what you want is to change the size of components, which is standard user-land CSS included after MDL to target and modify things how you wish.

Thank you.
