### ISSUE TITLE
Remove redundant mdl-shadow-- classes

### ISSUE THREAD

**Issue by AlanSmithey** [google/material-design-lite#4932]
Because all components in Material Design have default elevation (z-index and box-shadow), I think this CSS properties must be included in every Component by default, according to Elevation table values from MD specs, rather then placed in separate class, as now.

**Comment by Thanood** [comment]
I find `mdl-shadow--` useful to provide non-mdl elements with elevation.

**Comment by AlanSmithey** [comment]
@Thanood I think MDL must be an implementation of MD rules and MD standard components)
Maybe I am wrong)
Otherwise, it will be another bootstrap with custom elements and no design consistency)

**Comment by Thanood** [comment]
@AlanSmithey You're right.

But MDL (v1) does not implement every possible Material Design component (and maybe it shouldn't). So if I'd like to create (just as an example) a datepicker or "accordion" (expansion panels) I would need elevation, too. And in that case I'd like to use the same box-shadows as MDL does, for consistency reasons.

Just my 2ct anyway. 😃

**Comment by Garbee** [comment]
We are expanding the elevation classes in V2 to cover 1-24dp fully. While we do implement the proper shadow in the components where required (using mixins of the classes) developers may still need different elevations within their applications and custom components. Or even want to change the elevation. The classes provide an easy way to do that.

In v1 we may have messed up and not included the shadows requiring the use of the shadow classes, but in V2 this is not the case. V1 is on required-updates-only at this point, so no changes will be made here by the core team.

If there is a problem here in V1 and someone from the community wants to address it, the `mdl-1.x` is open for PRs.

Thank you.
