### ISSUE TITLE
Wrong shadow depth on header?

### ISSUE THREAD

**Issue by vince8864** [google/material-design-lite#4939]
According to the material design spec, the app bar should be 4dp. However, i notice that the one in MDL only uses 2dp. Am i missing something? Just expressing my curiosity, though I have to say the shadow on 4dp is quite deep in mdl. thanks

.mdl-layout__header {
box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);
}

.mdl-shadow--2dp {
    box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);

.mdl-shadow--4dp {
    box-shadow: 0 4px 5px 0 rgba(0,0,0,.14),0 1px 10px 0 rgba(0,0,0,.12),0 2px 4px -1px rgba(0,0,0,.2);
}

**Comment by Garbee** [comment]
Just an oversight from early development or perhaps the spec changed at some point midway. The core team is focusing on V2 and this is a non-critical issue that doesn't affect usability of V1. Therefore, the core team won't be addressing this ourselves.

If anyone from the community wants to patch this, `mdl-1.x` is open for PRs.

Thank you.

**Comment by vince8864** [comment]
Nah...just wanted clear my doubt. Thanks
