### ISSUE TITLE
Side-nav a11y issue

### ISSUE THREAD

**Issue by ramlmn** [google/material-design-lite#4949]
Side-nav actually implements `aria-hidden` but still the contents are tabbable inside it even though the side-nav is hidden.

I think this can be solved by using `visibility: hidden` to the side-nav (like menu's) but it does repaint the side-nav and the other way to fix it is to use inert.

This issue can be found live on mdl [android.com template](https://getmdl.io/templates/android-dot-com/index.html).

**Comment by Garbee** [comment]
Yup, this is a problem. Changing visibilty isn't an option since the goal is to avoid repainting since the drawer is on a layer of its own for animation.

@sgomes Do we want to back-port the `inert` polyfill bit we are doing in V2's drawer to V1?

**Comment by sgomes** [comment]
We're not using a polyfill in v2; we're basically just implementing the same thing the polyfill would, but limited to the drawer.

I could see two ways of getting this in v1: we either add and remove the `inert` property, and rely on the developer using the polyfill; or instead we follow the same approach as in v2.

What do you think, @Garbee?

**Comment by Garbee** [comment]
That's what I meant, just doing the polyfill bit internally. I'd say let's do that so it "just works". Accessibility is a bit more important to have just-work than an extra component entirely like Dialog.

**Comment by ramlmn** [comment]
@Garbee @sgomes Oh, actually you might also need to implement a [keyboard trap](https://github.com/ramlmn/trap-keyboard) inside the side-nav.

**Comment by sgomes** [comment]
@ramlmn Indeed. We've done that in `mdl-simple-menu` in v2 and we still have to port it to `mdl-drawer`.

**Comment by Garbee** [comment]
Let's focus on the inert bit alone with this issue/PR. Adding a trap is slightly-more complex.

**Comment by sgomes** [comment]
@Garbee Worth creating a new issue for, though, so we don't lose track. I'll take care of that.
