### ISSUE TITLE
Add focus trapping to `mdl-temporary-drawer`

### ISSUE THREAD

**Issue by sgomes** [google/material-design-lite#4950]
It seems we forgot to do focus trapping while the drawer is open, as we do for `mdl-simple-menu`. We should refactor out the focus trapping code and use it across both components.

@traviskaufman FYI.

**Comment by traviskaufman** [comment]
Agreed. I think we had talked at one point about holding off on this until we had a general focusing strategy. However since we've had to do the work with simple menu I agree it's worth refactoring out and using across components.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/1
