### ISSUE TITLE
mdl1.x : Dialog with Polyfill wrong container padding

### ISSUE THREAD

**Issue by mikbry** [google/material-design-lite#4952]
## Bug
There is an extra padding=1em when using DialogPolyfill. Which is not right regarding components guidelines: https://material.google.com/components/dialogs.html#dialogs-specs
The green area:
![screen shot 2016-12-01 at 16 16 08](https://cloud.githubusercontent.com/assets/395718/20799145/9b630f34-b7e1-11e6-9679-c78d79c74c20.png)

Browsers: Any using DialogPolyfill (tested on Chrome, Safari)
OS: MacOSX
How to reproduce it: simply go to example for Dialog Component:
http://codepen.io/Garbee/full/JGMowG/

But it was tested on latest packages
MDL 1.2.1
DialogPolyFill 0.4.5

What is the expected behavior?
mdl-dialog {
padding: 0px; 
}

What is the actual behavior?
dialog {
padding: 1em;
}

**Comment by Garbee** [comment]
The core team is focusing on 2.x work. As this is a non-critical issue we won't be addressing this ourselves.

If anyone wants to submit a patch for this `mdl-1.x` is open for PRs.

Thank you.
