### ISSUE TITLE
MDL Tabs isn't working in Angular2

### ISSUE THREAD

**Issue by Sonntagskind** [google/material-design-lite#4953]
Hello!

I'm trying to use Material Design Lite Tabs in my Angular2 project. But it's not working as described in the [official example](https://getmdl.io/components/index.html#layout-section/tabs).

OS X: ElCapitan 10.11.3
Browser: Chrome 53.0.2785.143 (64-bit)
Version: material.min.js

My index.html:
`   <head>
    
    <link rel="stylesheet" href="/node_modules/material-design-lite/material.min.css">

    
    <script src="/node_modules/material-design-lite/material.min.js"></script>

    
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    
    <link rel="stylesheet" href="app/css/styles.css">

    
    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <script src="systemjs.config.js"></script>

    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
    </head>

    <body>
    <my-app>
        <div class="preloader mdl-spinner mdl-spinner--single-color mdl-js-spinner is-active">                </div>
    </my-app>
    </body>
`

My coponent.html:

`
    <div class="releases-list-component">
 
    <div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect" >//***** mdl container

    <div class="mdl-tabs__tab-bar">//***** mdl tabs
    <a href="#albums" class="mdl-tabs__tab is-active">Albums</a>
    <a href="#split" class="mdl-tabs__tab">Splits</a>
    <a href="#tributes" class="mdl-tabs__tab">Tributes</a>
    </div>

    <div class="mdl-tabs__panel is-active" id="albums">//***** mdl tab content
    <div class="release-list-item release_1"></div>
    <div class="release-list-item release_2"></div>
    <div class="release-list-item release_3"></div>
    <div class="release-list-item release_4"></div>
    <div class="release-list-item release_8"></div>
    <div class="release-list-item release_9"></div>
    </div>

    <div class="mdl-tabs__panel" id="splits">//***** mdl tab content
       <div class="release-list-item release_6"></div>
    </div>

    <div class="mdl-tabs__panel" id="tributes">//***** mdl tab content
      <div class="release-list-item release_5"></div>
      <div class="release-list-item release_7"></div>
    </div>

      </div>
     </div>`

My style.css:

`   #albums {
     display: flex;
     justify-content: space-around;
     flex-wrap: wrap;
   }

   .release-list-item {
     width: 400px;
     height: 400px;
     margin: 15px;
   }

   .release_1 {
      background: url('../images/cover.jpg') center center no-repeat;
      background-size: 100%; 
    }`

I am also using other mdl elements (e.g. preloader) and they work fine. But Tabs particularly don't work.

I also copy-pasted some working MDL Tabs examples into my component.html, and they didn't work as well.

Didn't find any suitable solution to me. Please, explain what should be done to make it work.

The same issue occurs in [a plunker example](https://plnkr.co/edit/Wi02CQVXwM7nvN8vFm2E?p=preview) based on Angular2.

**Comment by mh-cbon** [comment]
check https://github.com/google/material-design-lite/issues?q=is%3Aissue+angular+tab+is%3Aclosed
https://plnkr.co/edit/F7hdKaLllWgwl3GYqgPh?p=preview ?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this is technical support getting MDL to work in a 3rd party's environment it is out of scope for this issue tracker.

Thank you.
