### ISSUE TITLE
v2: a document to explain new components addition

### ISSUE THREAD

**Issue by mh-cbon** [google/material-design-lite#4954]
Hi,

small question, any chance v2 gets a document to explain the BP and ways to extend the core framework of new components ? Even tough nothing really automatic is provided.

In future i d like to avoid what i did with v1, fork + add my customs (see [this](https://github.com/mh-cbon/material-design-lite/tree/mdl-1.x/src)).

I found it was great to be able to depends on [this](https://github.com/mebibou/mdl-selectfield) repo and quickly update the gulp file to have a new component.

I had much more trouble with [this one](https://github.com/puranjayjain/md-date-time-picker)

**Comment by traviskaufman** [comment]
We'll definitely be providing a doc on how to author your own components. It's currently [in the works](https://github.com/google/material-design-lite/blob/master/docs/how-to-write-a-component.md)
