### ISSUE TITLE
Material Deisgn Lite Website

### ISSUE THREAD

**Issue by kyoukhana** [google/material-design-lite#4972]
Is there a Git repo for the Material Design Lite.  Would be nice for a starter template

**Comment by Garbee** [comment]
This repo has it. Everything is contained within the `mdl-1.x` branch for the current site.

**Comment by kyoukhana** [comment]
thanks which folder within the branch

**Comment by Garbee** [comment]
`docs`

**Comment by sgomes** [comment]
Closing issue, as the question seems to be answered.
