### ISSUE TITLE
Dashboard Template: Search Icon Misalignment on Mobile

### ISSUE THREAD

**Issue by rhroyston** [google/material-design-lite#4974]
Resizing browser to a more mobile layout/size, the Search icon does not position properly.  Pulled it up on Samsung s7 Edge w Android, same result.  See image/screen capture:

https://drive.google.com/open?id=0ByJ_bX8GebiKWE5NUUFSb0J0c3M

**Comment by maximiliankukla** [comment]
Duplicate with #4912

**Comment by sgomes** [comment]
Thanks, @maximiliankukla. Closing in favour of #4912.
