### ISSUE TITLE
Dropdown input field

### ISSUE THREAD

**Issue by tbrandenburger** [google/material-design-lite#4975]
Are there any plans for a dropdown field (<select>)?

**Comment by bmiller1** [comment]
There is some information [here](https://github.com/google/material-design-lite/wiki/Making-your-first-JS-component).

You might also try using a menu attached to a button or label.

**Comment by gaelicwinter** [comment]
I successfully integrated this https://github.com/westonganger/chosen-material-theme

Along with the chosen select from here
https://harvesthq.github.io/chosen/

**Comment by sgomes** [comment]
No plans for a dropdown in MDL, sorry.

We've recently moved new development to the [Material Components for the web](https://github.com/material-components/material-components-web) project, where we already have an [alpha version of this component](https://github.com/material-components/material-components-web/tree/master/packages/mdc-select). Given the new architecture and our resource constraints, it's not feasible for us to backport to MDL, but we're happy to review any PRs if someone's interested in undertaking that work.
