### ISSUE TITLE
v2/i18n 

### ISSUE THREAD

**Issue by joeblew99** [google/material-design-lite#4976]
For v2, we have RTL, but how is i18n done.
I had a look in the issues but only found RTL:
https://github.com/google/material-design-lite/issues?utf8=%E2%9C%93&q=i18n%20

Ideas ?
https://ebidel.github.io/i18n-msg/components/i18n-msg/

http://codepen.io/anon/pen/yNxKNw.html

Something very simple i feel is best.

**Comment by Garbee** [comment]
I18N is up to your application. MDL is just a library of *design* points, the content within it is up to developers and their projects to decide.

**Comment by joeblew99** [comment]
Ok makes sense. 
i guess i will copy the way Chromium does it

**Comment by joeblew99** [comment]
still curious to hear what others do for this ?

**Comment by Garbee** [comment]
Please discuss this in more general web development areas. This issue tracker is only for issues with the code provided by MDL. This is general support which makes the content undiscoverable here where the discussion could also benefit others if put into better areas. It also helps keep the signal-to-noise ratio down for anyone contributing and watching the issue tracker.

Thank you.
