### ISSUE TITLE
Live Site as template

### ISSUE THREAD

**Issue by kyoukhana** [google/material-design-lite#4977]
I did a git pull of the repo.  But I am not sure how to compile the site.  I tired running gulp but not sure which file to go to.  I am trying to use the material design lite home page as a template.  Just need some direction.  I know they are in the docs folder but its all markdown files.

**Comment by sgomes** [comment]
Thanks, @kyoukhana! Unfortunately, the live site isn't well suited as a template, as it's a complex implementation that can definitely do with a massive rework :(

In any case, you can find everything in the `docs` folder, as you mentioned. It's built using swig as a templating mechanism. The HTML bits are in the [templates folder](https://github.com/google/material-design-lite/tree/mdl-1.x/docs/_templates), and the CSS in [assets](https://github.com/google/material-design-lite/tree/mdl-1.x/docs/_assets).
