### ISSUE TITLE
Dashboard Template Search icon fell down

### ISSUE THREAD

**Issue by dmitriymarley** [google/material-design-lite#4980]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

> What browser(s) is this bug affecting (including version)? 

Google Chrome 54.0.2840.99 m

> What OS (and version) are you using?

Windows 8.1

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

Just visit: https://getmdl.io/templates/dashboard/index.html

> What is the expected behavior?

The "search" icon should be on the same level as a dropdown

> What is the actual behavior?

The "search" icon is broken and is below the nav bar.
![image](https://cloud.githubusercontent.com/assets/8083744/21198156/e150de1c-c246-11e6-85ee-b435c1c1da30.png)

**Comment by maximiliankukla** [comment]
Duplicate with #4912 and #4974 
The last issue was just created 3 days ago...

**Comment by sgomes** [comment]
Thanks, @maximiliankukla. Closing in favour of #4912.
