### ISSUE TITLE
Is MDC v2 of MDL?

### ISSUE THREAD

**Issue by shmshd** [google/material-design-lite#4984]
MDC-web mentioned in their github that MDC is the successor of MDL. So, is it v2 that MDL team were working on?

"Material Components for the web (MDC-Web) help developers execute Material Design. Developed by a core team of engineers and UX designers at Google, these components enable a reliable development workflow to build beautiful and functional web projects.

Material Components for the web is the successor to Material Design Lite, and has 3 high-level goals"

Please describe the difference between both.
thanks

**Comment by Thanood** [comment]
@shmshd12 Just had a look at the [master branch readme](https://github.com/google/material-design-lite/tree/master). MDL v2 officially moved to MDC. 😃

**Comment by ghost** [comment]
Should the getmdl website redirect people to the new project site, or is the getmdl site still relevant for the new library?

**Comment by Garbee** [comment]
Yes, MDC is MDLv2.

The site will not redirect. MDL still needs its docs and people will need it for reference even after MDC is around. MDC is its own separate project now. In the future we may do something to forward people over, for now though, MDC isn't even at an alpha point so... No point redirecting people to unstable code.

More to come on this front in the future.

**Comment by owencm** [comment]
Just curious if there's an update here? I always forget that MDC is the new MDL and it'd be nice if the MDL site would point people to MDC...

**Comment by Garbee** [comment]
MCW is still alpha-level, so no updates are going to happen currently.
