### ISSUE TITLE
How is MDL v2 related to Google Material Components?

### ISSUE THREAD

**Issue by rtarnec** [google/material-design-lite#4985]
Hi, I am not sure it is a good place ot ask this kind of question... If not, sorry...

I've noticed this new initiative from Google: **Material Components**
 
https://github.com/material-components

where it is explained that "Material Components for the web is the successor to Material Design Lite". I've also noted that for some elements it is mentioned "refactor(all): Rename Material Design Lite to Material Components Web. " 

Could you please give ore info on how MDL v2 is related to Material Components? Thanks in advance!

**Comment by Thanood** [comment]
See here: http://github.com/google/material-design-lite/issues/4984
😃

**Comment by Garbee** [comment]
MDL V2 === Material Components for Web.

**Comment by im-n1** [comment]
One dumb question. If MDC is new MDL, where is basic of all basics - (flex) grid?

**Comment by Garbee** [comment]
It isn't even at an alpha release yet. More things will come in time.

**Comment by CreativeMinds1981** [comment]
Hi Garbee, 

we have finished developing our platform on MDL, reason, MDL has an excellent documentation and it works well for our requirements. 

Question: Can MDC and MDL co-exist ? 
Question 2: Is it mandatory that we need to upgrade to MDC ? or can we keep running on MDL ?

**Comment by Garbee** [comment]
> Question: Can MDC and MDL co-exist ?

Possibly, in fact most likely given the design goals of MCW, but not recommended.

> Question 2: Is it mandatory that we need to upgrade to MDC ? or can we keep running on MDL ?

Just like any libraries, nothing is "mandatory". If MDL meets your business needs and you don't mind the fact it is no longer supported, nothing is stopping it from working going forward.
