### ISSUE TITLE
getmdl.io code

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#4991]
Could you please share the full code of website getmdl.io? I want to translate this documents to Chinese and  share them to Chinese developers and let more Chinese people know and contribute to this program. Thanks.

**Comment by ghost** [comment]
@Garbee

**Comment by ghost** [comment]
@sgomes

**Comment by Garbee** [comment]
It is all in the repository. The gulp system generates the microsite and the docs are built from the component README's.

**Comment by sgomes** [comment]
@zhaoweizhong Check the `docs/` folder. Also, #4977.

**Comment by ghost** [comment]
Sorry I'm still confused. But how to build them? How to make them a full site?

**Comment by sgomes** [comment]
Answered in #4993.
