### ISSUE TITLE
How to build /docs to a full site?

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#4993]
In #4991 , I asked about the code of getmdl.io. But now I'm still confused. How to build the code in `/docs` ? How to make them a full site?

**Comment by ghost** [comment]
@Garbee @sgomes

**Comment by sgomes** [comment]
@zhaoweizhong Check the [`pages` task in the gulpfile](https://github.com/google/material-design-lite/blob/mdl-1.x/gulpfile.babel.js#L435). It uses swig to compose the HTML templates and the markdown files into a built site.
