### ISSUE TITLE
mdl-dialog__actions--full-width children overflow 100% width in IE

### ISSUE THREAD

**Issue by lexaurin** [google/material-design-lite#5000]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

1.3.0

> What browser(s) is this bug affecting (including version)? 

Internet Explorer 11

> What OS (and version) are you using?

Windows 10

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

http://codepen.io/lexaurin/pen/ggOqxw?editors=1100

> What is the expected behavior?

Button does not overflow 100% width container.

![expected behavior screenshot](https://github.com/lexaurin/github/blob/master/mdl-ok.png?raw=true)

> What is the actual behavior?

Button overflows 100% width container in Internet Explorer 11. In other browsers Chrome, Firefox, .. it works fine.

![bug screenshot](https://github.com/lexaurin/github/blob/master/mdl-bug.png?raw=true)

**Comment by lexaurin** [comment]
See codepen for workaround http://codepen.io/lexaurin/pen/JEjzQJ?editors=1100
Pull request [submitted](https://github.com/google/material-design-lite/pull/5001)

**Comment by Garbee** [comment]
Merged the PR. Thank you very much!
