### ISSUE TITLE
Add Microsoft Edge in Browser Support README

### ISSUE THREAD

**Issue by Sparker0i** [google/material-design-lite#5002]
I think the title says it all. Microsoft Edge support is not being displayed in the README

**Comment by Garbee** [comment]
At the time we launched Edge was not released yet which is why it isn't listed. We do support IE11 as an A-grade, so Edge should follow that just fine without any extra effort.

**Comment by Sparker0i** [comment]
But Edge uses the EdgeHTML engine and IE 11 uses Trident. Both varying in nature. Not including this is bound to create some confusion

**Comment by Garbee** [comment]
We didn't build the vast majority of it with Edge testing, since it wasn't stable during the build. So, for us to then add Edge without going through every component and manually testing things could be misleading.
