### ISSUE TITLE
Transparent header background not displayed correctly

### ISSUE THREAD

**Issue by marcfuchshofer** [google/material-design-lite#5005]
**UPDATE** Text in italics indicates statements that were true when I started writing, however now after a few more reloads of the page, the header doesn't work correctly on any browser of any machine.

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.3.0

> What browser(s) is this bug affecting (including version)?
All of them _, except in Chrome 55.0.2883.95 (64-bit) on my rMBP 13" with macOS 10.12.2._

> What OS (and version) are you using?
macOS 10.12.2

I'm working on a Vue.js project where MDL is used for implementing Material Design. Now, we have a landing page in a .vue file, where the transparent mdl header is used with a background image. On my machine in my Chrome version, everything works fine. However, in any other browsers on my machine and all other browsers on my friends' machines, the background image is only as high as a usual Material design header, so just a few dozen pixels.

> What is the expected behavior?
Background image should cover the entire viewport

> What is the actual behavior?
_Background image only covers entire viewport on my machine in Chrome 55._
Background image is only a few dozen pixels high on all other machines in all other browsers.

> Any other information you believe would be useful?
We tested Linux with Firefox; Windows 10 with Edge, Chrome and Firefox; and macOS 10.12.2 with Safari, Firefox and Chrome

Currently displayed version
![image](https://cloud.githubusercontent.com/assets/24942798/21692969/6f8a4508-d37f-11e6-80db-77f034688ea3.png)

Earlier, correct version
![image](https://cloud.githubusercontent.com/assets/24942798/21693003/86dee92a-d37f-11e6-9c4a-a0ea19e3e228.png)

**Comment by Garbee** [comment]
Can you please provide a [codpen](https://codepen.io) that reproduces the issue?

Thank you.
