### ISSUE TITLE
.mdl-card__title has invalid property value; justify-content: stretch;

### ISSUE THREAD

**Issue by leifoolsen** [google/material-design-lite#5024]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.3.0

> What browser(s) is this bug affecting (including version)? 
Any browser

> What OS (and version) are you using?
ubuntu 16.0.4 lts / macOS Sierra (10.12.3)

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
* Go to: https://getmdl.io/components/index.html#cards-section
* Inspect first "mdl-card__title" class
* The styles inspector shows warning "Invalid property value" for justify-content 

> What is the expected behavior?
justify-content should be one of "flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly". 

> What is the actual behavior?
**justify-content: stretch ** is invalid

> Any other information you believe would be useful?
See https://developer.mozilla.org/en/docs/Web/CSS/justify-content for valid prpoperties.

**Comment by Garbee** [comment]
Oops. I thought we removed that a while ago... Oh well, commit 2265e3d0bf7045f8332a968c8a0eeda0ae71f1e2 fixes that!

Thank you.
