### ISSUE TITLE
[Component Request] Expansion Panels

### ISSUE THREAD

**Issue by landonhaley** [google/material-design-lite#5029]
* Description:
An expansion panel is a lightweight container that may either stand alone or be connected to a larger surface, such as a card.
* Material Design Spec link:
https://material.io/guidelines/components/expansion-panels.html
* Use Case(s):
They may be used for a variety of tasks, such as:
To edit a setting
To create a tool for ad campaigns

**Comment by Garbee** [comment]
We can implement this using the `<details>` element pretty easily. [Demo](http://codepen.io/Garbee/pen/egjxBv) of what I'm currently thinking. This will require a polyfill for IE/Edge, but that's fine considering we do one for Dialog for a larger browser-base.

The demo works in Firefox, Chrome, and Safari all right out of the gate.

**Comment by frasurebuilds** [comment]
I know this is different, but here is an *Accordion* example on Google Support: https://support.google.com/websearch/
It has a similar use and structure to an *Expansion Panel*.

**Comment by Garbee** [comment]
That accordion doesn't follow MD guidelines.

The demo I have is actually fully compliant aside from font stuff. All I need to do is figure out the polyfill situation and how to handle that before making a PR.
