### ISSUE TITLE
License

### ISSUE THREAD

**Issue by JoaquimFMF** [google/material-design-lite#5040]
As a company can we, without any cost, download and use the "MDL" and third party software that may be included in the "MDL" (for example: third party codes etc.) in as many projects as we want?

**Comment by Garbee** [comment]
MDL is licensed under [Apache 2.0](https://github.com/google/material-design-lite/blob/mdl-1.x/LICENSE). So long as you adhere to the license, you're good. We are not lawyers and cannot give guidance as to each users specific cases. If you can't seem to make out what is required by the license, then you'll need to consult your lawyers on how to adhere to it.

Sorry we can't be of more help.
