### ISSUE TITLE
Cannot read property 'classList' of null - RadioButton

### ISSUE THREAD

**Issue by msefidi** [google/material-design-lite#5048]
Hi

I am using MDL version 1.3.0. 
In chrome version 53 and Mac OS I am getting this exception while using radio-buttons
```
Uncaught TypeError: Cannot read property 'classList' of null
    at MaterialRipple.<anonymous> (material.js:3886)
material.js:3886Uncaught TypeError: Cannot read property 'classList' of null
    at MaterialRipple.<anonymous> (material.js:3886)
```

this is how I am using it:

```
<label className='mdl-radio mdl-js-radio mdl-js-ripple-effect' htmlFor='test'>
          <input
            type='radio'
            className='mdl-radio__button'
            id='test'
          />
          <span className='mdl-radio__label'>label</span>
        </label>
```

this will happen on `mouse over` event and also `click` event on the radio input.

Your helps is appreciated in advance.

**Comment by rianby64** [comment]
At first sight I suppose you're doing something wrong with the attribute ```htmlFor={'test'}```. It should be ```for="test"```.

**Comment by msefidi** [comment]
@rianby64 fixed it. that was because I had copied it from my react component. but the problem is still there. no difference.

**Comment by rianby64** [comment]
Can you give me an snippet?
