### ISSUE TITLE
pattern validation  lang

### ISSUE THREAD

**Issue by Bonobomagno** [google/material-design-lite#5051]
version 1.3
mdl dont use the lang="" tag for language choose.
 So if you have a multilanguage website and want to change it, how to do?. How to override default mdl lang prediction ?

**Comment by ZanderBrown** [comment]
Not sure i understand this

**Comment by Bonobomagno** [comment]
mdl has a validation error, localized in some languages, but mdl use own logic for chosing the lang of this localization. 
So you can have mdl validation in english, and the website in italian. I just want to have all in one lang

**Comment by Garbee** [comment]
Can you provide a [codepen](http://codenpen.io) example with MDL that shows what you're talking about? As far as I know we don't do any language stuff internally. It's all done using native JS APIs so things should "just work" in the regard of languages.

**Comment by Bonobomagno** [comment]
my fault, i thought mdl was using a meta-attribute syntax for this. Instead it was defined elsewhere
