### ISSUE TITLE
Angular2 mdl-select multiple align vertically is not working

### ISSUE THREAD

**Issue by dalidovski** [google/material-design-lite#5056]
> angular2-mdl : "^2.12.1"

> Browser Google Chrome

> Actual behavior : mdl-select mutiple values : When I select my multiple options, in the view my options stack horizontally.

`                <mdl-select placeholder="Libellé" [(ngModel)]="immo.toRelation.actifs.immo.type" [disabled]="residencePrinpale=='true'">
                    <div *ngFor="let items of parent.parent.referentiel.patrimoineImmobilier">
                        <div *ngIf="getCategorie(items.code)">
                            <mdl-option mdl-ripple *ngFor="let item of items.sousRef" [value]="item.code" floating-label>{{item.libelle}}</mdl-option>
                        </div>
                    </div>
                </mdl-select>`

![mdl-select](https://cloud.githubusercontent.com/assets/22326523/23750689/6734c498-04ce-11e7-9b7e-9baa86b544a3.png)

> Expected behavior : I would like to list them vertically

**Comment by Garbee** [comment]
We don't provide `select` styling. This isn't an issue with MDL but whatever library you are using that implements it.
