### ISSUE TITLE
Phone & Tablet grid 12 columns possible ?

### ISSUE THREAD

**Issue by Altessaire** [google/material-design-lite#5062]
> A grid has 12 columns in the desktop screen size, 8 in the tablet size, and 4 in the phone size.
Is there a way to get 12 columns in the tablet & phone size ?

**Comment by Garbee** [comment]
Only by making your own grid. Our grid follows the [columns required](https://material.io/guidelines/layout/responsive-ui.html#responsive-ui-breakpoints) by the MD specification.

There are no plans to modify this as what we have is in alignment with the specification.

Thank you.

**Comment by Altessaire** [comment]
Thank you for the answer !
