### ISSUE TITLE
Slider onchange doesn't work in Chrome

### ISSUE THREAD

**Issue by DanTup** [google/material-design-lite#5064]
I just noticed the sliders on my website aren't firing their onchange events. I'm certain this used to work only a few months ago but I haven't made any changes recently so it's possible this was caused by a Chrome change.

Here's some code:

```html
<input class="mdl-slider mdl-js-slider" type="range"
  min="0" max="100" value="0" tabindex="0" onchange="document.getElementById('log').value += '.'">
  
  <textarea id="log"></textarea>
```

Without MDL, this onchange fires fine and dots appear in the textarea when you slide. With MDL pulled in, the onchange never fires.

Here's a JSFiddle with MDL loaded (you can remove the resources or the classnames to see it working).

https://jsfiddle.net/2jwgkp8L/

**Comment by aderbas** [comment]
+1 same problem here. Mdl version: 1.3.0, OS Linux, Chrome version: 56.0.2924.87

**Comment by aderbas** [comment]
Nothing about it? =/

**Comment by frct1** [comment]
Yeah, i too see this problem
But onclick is work!
https://github.com/google/material-design-lite/issues/5042

**Comment by DanTup** [comment]
I've removed all the MDL styling from my controls across all sites. I've somewhat lost faith in this project if something so basic can be broken (and reports in #5042 ignored for a month while other cases have been responded to) :(

**Comment by OmriSoudry** [comment]
Same problem here, a few days ago all of our systems which rely on this sliders stopped working.

**Comment by kasperkamperman** [comment]
Same problem here. OSX 10.10.5, Chrome 58.0.3029.110
I hope this project gets some love, because it's the most accessible implementation.
