### ISSUE TITLE
Question: How to create the color picker wheel?

### ISSUE THREAD

**Issue by Mashiane** [google/material-design-lite#5065]
Hi, this is not necessary an issue, but just a question. I saw your picker color wheel here https://getmdl.io/customize/ . I need something like that for my own app, can you please advise me of the js and css used to create this?

Thanks a lot!

**Comment by ZanderBrown** [comment]
I would suggest `view-source` as good place to start

**Comment by Garbee** [comment]
The code all runs in the browser. You can use the developer tools to look at how it works out find the source in the repository.

We can't help you take this and use it elsewhere. It is a component we built for our needs and that's it.

Thank you.
