### ISSUE TITLE
Programmatically tab changing

### ISSUE THREAD

**Issue by rianby64** [google/material-design-lite#5068]
Hello! I'm trying to active a tab via JS, but I see you don't have the necessary function to do that.
Does MDL consider the case of "programmatically tab changing"? If so, I'd be glad to open a PR with this feature. Thanks!

**Comment by eKoopmans** [comment]
Seconded that this would be a useful feature - it's a bit of a mess to do it externally. I'd propose something like this:

```js
  /**
   * Set the active tab.
   *
   * @public
   * @param {number} index The tab index to set active.
   */
  MaterialTabs.prototype.setTab = function(index) {
    this.resetTabState_();
    this.resetPanelState_();
    if (index > 0) {
      if (index < this.tabs_.length) {
        this.tabs_[index].classList.add(this.CssClasses_.ACTIVE_CLASS);
      }
      if (index < this.panels_.length) {
        this.panels_[index].classList.add(this.CssClasses_.ACTIVE_CLASS);
      }
    }
  };
```

**Comment by rianby64** [comment]
Sounds great! Hope your solution PR will be accepted.
