### ISSUE TITLE
web page is not reponsive. Table must align in center of the page and should be responsive. Please help

### ISSUE THREAD

**Issue by chethan25rksa** [google/material-design-lite#5069]
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
  <style>
  body .column
  {
    display: flex;
    flex-direction:column;
    padding-top: 6px;
  }

  body .element
  {
    align-self: flex-end;
    font-size: 12px;
    opacity: 0.3;
    color: black;
    margin-left: 94%;

  }
  body
  {
    font-family:  "Roboto", "Helvetica","Arial",sans-serif !important;
  }
  </style>
  
  <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body style="background-color:#F5FFFA;">
  
  <div class="mdl-layout mdl-js-layout">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        
        <span class="mdl-layout-title"><font-family:'Open Sans', 'Helvetica Neue', Arial, sans-serif !important;>ONEDIGITALAD</font></span>
        
        <div class="mdl-layout-spacer"></div>
        
        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <a class="mdl-navigation__link" href="../hello/">Home</a>
          <a class="mdl-navigation__link" href="..//"></a>
        </nav>
      </div>
    </header>
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title">Menu</span>
      <nav class="mdl-navigation">
        <a class="mdl-navigation__link" href="../hello/">Home</a>
        <a class="mdl-navigation__link" href="..//"></a>
      </nav>
    </div>
    <main class="mdl-layout__content">
      <div class="page-content">
        <div class="column">
          <div class="element">{{ update_time }}</div>
          <div align="center" style="vertical-align:bottom">
            <div align="center" style="vertical-align:bottom">
              <table class="mdl-data-table mdl-js-data-table">
                <thead>
                  <tr>
                    <th class="mdl-data-table__cell--non-numeric">Campaign Name</th>
                    <th>Click</th>
                    <th>Impressions</th>
                    <th>Spend</th>
                    <th>win%</th>
                    <th>cpc</th>
                    <th>ctr</th>
                    <th>cpm</th>
                    <th>cost_per_user</th>
                    <th>unique user</th>
                  </tr>
                </thead>
                <tbody>
                  {% for result in array %}
                  <tr>
                    <td class="mdl-data-table__cell--non-numeric">{{ result.campaign_name }}</td>
                    <td>{{ result.click }}</td>
                    <td>{{ result.impressions }}</td>
                    <td>{{ result.spend }}</td>
                    <td>{{ result.win }}</td>
                    <td>{{ result.cpc }}</td>
                    <td>{{ result.ctr }}</td>
                    <td>{{ result.cpm }}</td>
                    <td>{{ result.cost_per_user }}</td>
                    <td>{{ result.users }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table></div>
            </main>
          </div>
        </body>
        </html>

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
