### ISSUE TITLE
Add clear ("x") button for resetting input fields

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#5088]
It will be good if something like `data-clear-btn="true"` will add a clear button (like [jquery](http://demos.jquerymobile.com/1.4.0/textinput/#Text)).
Problem temporary [solved](http://codepen.io/z56/pen/LyYEzz).

**Comment by Garbee** [comment]
This isn't a part of the Material Design specification. Therefore it is up to web developers to add it in for their sites as-needed.

Material Design Lite is a library of components to provide Material Design components for use when building a web page. It is not a general framework to handle any odd-and-end that developers may need.

Thank you.
