### ISSUE TITLE
Radio buttons not grayed when disabled

### ISSUE THREAD

**Issue by AnixPasBesoin** [google/material-design-lite#5094]
When a radio button is disabled, it's expected to fade to gray, so the user can guess that it's not possible to interact with it. Currently this is not implemented.

**Comment by Garbee** [comment]
>it's expected to be fade to gray

It sounds like you are using JavaScript to change the disabled state dynamically. If this is the case, then you need to call `node.MaterialCheckbox.disable()` on the node where the checkbox JavaScript was initialized (the node with `mdl-js-checkbox` on it for the radio.) This will trigger the class updates for disabled state.

If that isn't the case, then you'll need to provide a sample codepen that reproduces the problem please.

Thank you.

**Comment by AnixPasBesoin** [comment]
Indeed, I'm toggling the checkbox programmatically. 
For some reason, `node.MaterialCheckbox` is returning `undefined`. However, when logging the node object in the console, it looks like the property `MaterialCheckbox` is there.
Any explanation?

**Comment by Garbee** [comment]
No clue, I'd need to see what you're running exactly. `node` in my example was meant to be a stored reference to the node. Not something we add to the global JS. You need to query the object the same way you log it to the console and call `MaterialCheckbox` on that.

**Comment by avocadoboi** [comment]
You need to upgrade it with componentHandler.upgradeElement(node). This adds MaterialCheckbox to the node. I had this problem before :^)

**Comment by Akshat162001** [comment]
Can it be the error of css code 
try this:
input[type="radio"]:disabled + label {
  color: #888; /* Gray color */
}

input[type="radio"]:disabled + label: before {
  background-color: #888; /* Gray color */
}
