### ISSUE TITLE
Snackbar doesn't render on Firefox & Firefox Mobile

### ISSUE THREAD

**Issue by ScottRFrost** [google/material-design-lite#5103]
This bug can be repro'd on the official page - https://getmdl.io/components/index.html#snackbar-section

Load the with Firefox (I'm using Developer Edition / Aurora 54.0a2 (2017-04-18) on desktop and Firefox 53.0.1 on Android, but it appears to affect all versions) and click the snackbar button.  Nothing is rendered at the bottom of the page.

It works with latest Chrome, IE, and Edge.  It works on Chrome for Android.

**Comment by Garbee** [comment]
Works fine in FF 53 here.

If it isn't rendering properly in a developer edition but it is in stable for you, then you should file a bug with Firefox as that means they have a serious regression that needs to be handled.

Closing this out as there is nothing actionable here for us to do as this is a problem in an unstable browser. If the bug makes it to Stable, then we may look into a patch to work around the issue. However this is clearly a Firefox bug in Dev edition currently.

Thank you.
