### ISSUE TITLE
MDL switch event is not working on jquery dialog with Modal

### ISSUE THREAD

**Issue by susundee** [google/material-design-lite#5108]
We're using MDL components in our project. we have several jquery dialogs.

When we added switch or checkbox components in jquery modal dialog, the events are not working anymore.

Here is the example on http://jsfiddle.net/sundee/r8xn9aua/45/

Could anyone please help?

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

As this is about integrating MDL with another library/framework it is out of scope of the issue tracker.

Thank you.
