### ISSUE TITLE
SELECT(and option) COMPONENT

### ISSUE THREAD

**Issue by alivetytan** [google/material-design-lite#5114]
Hi guys, i have 1 question. Can you tell me if there is a component in the getmdl.io for the SELECT tag in the form? Because I'm using getmdl.io and I saw this component in other frameworks. PLZ help! :)

**Comment by Garbee** [comment]
MDL does not provide a select component. Material Components For Web does which is the successor to the MDL project.

A select component in MDL is too complex of a task to be implemented at this point. Developers can use the one from MCW or use another MD styled select component from around the web if they wish.

Thank you.

**Comment by Justice4Code** [comment]
Please consider adding select as well.
