### ISSUE TITLE
How to run the project on my localhost

### ISSUE THREAD

**Issue by burakuluu** [google/material-design-lite#5115]
I couldn't find how to run the project on my local after cloning the project. Also there is no any script on package.json to run though. How can I run this?

**Comment by ZanderBrown** [comment]
run babel then gulp

**Comment by burakuluu** [comment]
When I run 'gulp', I took this error;

```
1 code style error found.
[12:26:27] 'lint' errored after 2.46 s
[12:26:27] Error in plugin 'gulp-jscs'
Message:
    JSCS failed for: ............

[12:26:27] 'default' errored after 5.51 s
[12:26:27] Error in plugin 'run-sequence(lint)'
Message:
    JSCS failed for: ............
.
.
.
.
.

Stack:
    at finish (D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\run-sequence\index.js:56:13)
    at Gulp.onError (D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\run-sequence\index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\orchestrator\index.js:264:8)
    at D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\orchestrator\index.js:275:23
    at finish (D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\orchestrator\lib\runTask.js:21:8)
    at DestroyableTransform.<anonymous> (D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\orchestrator\lib\runTask.js:52:4)
    at DestroyableTransform.f (D:\Users\buraku\Desktop\ReactProjects\material-design-lite\node_modules\end-of-stream\node_modules\once\once.js:17:25)
    at emitOne (events.js:101:20)
```
Why do I take this error? @ZanderBrown

**Comment by kmskrishna** [comment]
Do you want to use it in any project? If yes, you can use this [https://getmdl.io/started/index.html#download](url).

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

However it looks like JSCS failed and you're on Windows. Make sure you've checked out with line endings properly so they are pulled as unix-style. In the future to provide the whole error and not clip important information as you have, uses the [details element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) in the issue comment to make the output collapsible for easier reading.

Thank you.
