### ISSUE TITLE
Youtube iFrame is stretching over the whole width.

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#5119]
I am working on a school project and I need to include a video from youtube into my website, and I wanted to use mdl to make it look fancier but now I am sitting here while being frustrated because the video frame keeps on stretching on the whole width from the window, so if anyone can help me figuring it out I would be so thankful!

The code looks something like that: '<iframe width="600" height="360" src="https://www.youtube.com/embed/pVt-BDPgaDk?start=240&end=223" frameborder="0" allowfullscreen></iframe>'
![2017-05-20 21_24_44-](https://cloud.githubusercontent.com/assets/20644108/26278784/101b2f72-3da3-11e7-90fb-9c01f1358a24.png)

**Comment by haroldoramirez** [comment]
Hello

Working with iframe always and complicated, in my projects I try to avoid it to the maximum possible. I find it difficult to always add a size and if it is a question of resposivity, it is not good. I did not analyze your code completely but I would put that iframe in a mdl card

Try something like:

 <iframe src="https://www.youtube.com/embed/pVt-BDPgaDk?start=240&end=223" frameborder="0" allowfullscreen style="width:100%; height:360px; border:none;"></iframe>

Even so it may not be a good solution.

Try something different like:
[http://sorgalla.com/lity/](url)

good luck

=D
