### ISSUE TITLE
How to delegate those functions ?

### ISSUE THREAD

**Issue by Khumayun** [google/material-design-lite#5126]
After AJAX-request for data from other page, the JS(material-design-lite) is not applied to 'AJAX'ed elements. Probably it needs to be delegated ? or how to do it ?

**Comment by ZanderBrown** [comment]
[The docs exist for a reason](https://getmdl.io/started/index.html#dynamic)

> ### Use MDL on dynamic websites
> Material Design Lite will automatically register and render all elements marked with MDL classes upon page load. However in the case where you are creating DOM elements dynamically you need to register new elements using the `upgradeElement` function. Here is how you can dynamically create the same raised button with ripples shown in the section above:
> 
> ```html
> <div id="container"/>
> <script>
>   var button = document.createElement('button');
>   var textNode = document.createTextNode('Click Me!');
>   button.appendChild(textNode);
>   button.className = 'mdl-button mdl-js-button mdl-js-ripple-effect';
>   componentHandler.upgradeElement(button);
>   document.getElementById('container').appendChild(button);
> </script>```

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.
