### ISSUE TITLE
Do you have Dropdown-sidebar?

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#5131]
Just like materializecss.com, the dropdown sidebar

**Comment by ghost** [comment]
mdl-layout__drawer

**Comment by Garbee** [comment]
The expansion panel component coming in the next (and final) release will fill this use-case. Might need some extra tweaking in an app to be used in a drawer with the right UX.

**Comment by ghost** [comment]
Thx man @Garbee

**Comment by Garbee** [comment]
Since that will fill the case I'm going to close this out.

Thank you.
