### ISSUE TITLE
mdl-switch inside ng-repeat doest work 

### ISSUE THREAD

**Issue by hariharana** [google/material-design-lite#5132]
`<div ng-repeat="a in [1,2,3,45,6,7,8]"> 
        <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="switchasd{{$index}}">
            <input type="checkbox" id="switchasd{{$index}}" class="mdl-switch__input">
        </label>
    </div>`   

mdl switch doesnt work inside ng-repeat above is a sample code .

**Comment by hariharana** [comment]
'<div ng-repeat="a in [1,2,3,45,6,7,8]">
        <label class="mdl-switch mdl-js-switch mdl-js-ripple-effect" for="switchasd{{$index}}">
            <input type="checkbox" id="switchasd{{$index}}" class="mdl-switch__input">
        </label>
    </div>'

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

Thank you.

**Comment by hariharana** [comment]
I am not sure but still i feel this is a bug . Doesn't look like integration issue .

**Comment by Garbee** [comment]
You're asking why the integration with Angular isn't working how you expect. We can't support every framework/library integration here. If you can boil it down to a codepen using vanilla MDL to show the problem in action then there is something that could be assessed.

At this point though we are gearing up for the last patch now to tag and ship. So unless there is a critical error somewhere further patches aren't getting merged unless they are simple direct fixes.
