### ISSUE TITLE
https://getmdl.io/components/index.html#tables-section doesn't have the sample tables

### ISSUE THREAD

**Issue by robertsearle** [google/material-design-lite#5137]
https://getmdl.io/components/index.html#tables-section

The two examples just show code, no actual table sample.
- A data-table with a "master" select checkbox and individual row select checkboxes.
- A data-table without select checkboxes containing mostly text data.

> What is the expected behavior?
Please add the two table samples to the website

**Comment by Garbee** [comment]
We aren't updating the site any further. And all the examples that were meant to render do in fact render.

Thank you.
