### ISSUE TITLE
Material design lite ignoring different font types? 

### ISSUE THREAD

**Issue by SethuSenthil** [google/material-design-lite#5138]
I was trying to add my custom fonts (not self-hosted) but the font size didn't seem to work since Material design lite ignoring different font types, is there a way to fix/bypass this?

**Comment by Garbee** [comment]
Analyze our targets, and write a selector to override where needed and set the rules you want. Nothing different than any regular custom CSS modifications. We don't provide help to do every given task, what we provide tries to stay as close as we could to the MD Spec. Anything beyond that isn't in the project's scope.

Thank you.
