### ISSUE TITLE
FireFox: dialog.showModal is undefined before window.load

### ISSUE THREAD

**Issue by simonferndriger** [google/material-design-lite#5140]
MDL Version: 1.3.0
FireFox Version: 54.0.1 (32-bit)
OS: Windows 10

Steps to reproduce:
1) Visit dev.sonnige-aussichten[.ch/]index_new.php with FireFox (remove the [] from the URL)
2) Click on any card while the page is not yet fully loaded (you have to be quick)
3) The overlay does not open because dialog.showModal is not defined, it gets defined only after the page is full loaded (window.onload)

**Comment by Garbee** [comment]
You need to handle this in your own code. It is because the polyfill isn't loaded yet.

**Comment by simonferndriger** [comment]
Ah, OK. Thank you. From the example I check if `dialog.showModal` is there before I call it, and call `dialogPolyfill.registerDialog(dialog)` if not. But it looks like I need to call `dialog.showModal` again after I call the polyfill? Because it seems that it is not the window.onload event that makes it work, it is only working after the _second_ click, no matter how long I wait.

**Comment by Garbee** [comment]
It depends :tm:. It all comes down to how your logic is for the code, how it meshes with MDL and the polyfill, and what is going on in the engine. It can work on the first click once the polyfill is loaded, always has for me, it just depends on the way your stuff is. It's something you'll need to debug within your application to figure out what is happening as actions occur.
