### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by kovaacs** [google/material-design-lite#5142]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
Build from mdl-1.x branch

> What browser(s) is this bug affecting (including version)? 
Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on LinuxMint 18.1 (64-bit)
Firefox 54.0 (64-bit)

> What OS (and version) are you using?
Linux Mint 18.1 Serena

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

Create plenty of MDL textfield inputs dynamically, and use upgradeDom() to upgrade them.

> What is the expected behavior?
All being upgraded.

> What is the actual behavior?
Only the first few will upgrade.

> Any other information you believe would be useful?

material.js:2929 Uncaught TypeError: Cannot read property 'trim' of undefined
    at MaterialTextfield.checkDirty (material.js:2929)
    at MaterialTextfield.updateClasses_ (material.js:2878)
    at MaterialTextfield.init (material.js:2999)
    at new MaterialTextfield (material.js:2798)
    at upgradeElementInternal (material.js:243)
    at upgradeDomInternal (material.js:194)
    at Object.upgradeDomInternal [as upgradeDom] (material.js:180)
    at (index):235
    at HTMLScriptElement.<anonymous> ((index):212)
MaterialTextfield.checkDirty @ material.js:2929
MaterialTextfield.updateClasses_ @ material.js:2878
MaterialTextfield.init @ material.js:2999
MaterialTextfield @ material.js:2798
upgradeElementInternal @ material.js:243
upgradeDomInternal @ material.js:194
upgradeDomInternal @ material.js:180
(anonymous) @ (index):235
(anonymous) @ (index):212

**Comment by kovaacs** [comment]
On inspection of the code, it appears that nothing checks if the textfield has a placeholder before calling trim() [here](https://github.com/google/material-design-lite/blob/60f441a22ed98ed2c03f6179adf460d888bf459f/src/textfield/textfield.js#L180)

**Comment by Garbee** [comment]
A check isn't required. If a placeholder doesn't exist it is equal to `""`. Hence the check against an empty string.

Without an actual reproduction case there isn't anything that we can do to debug this. Please make a reproduction on [codepen](https://codepen.io). There is still time if a bug exists with the new functionality to address this before our last patch is released. But without the ability to debug it, nothing will get done.

Thank you.

**Comment by kovaacs** [comment]
I found the source of the problem. I know that it's officially not supported,  but I used select elements with MDL classes, and they worked fine. But they don't have a placeholder attribute, so this version of MDL broke the compatibility with selects. I guess I'll just tweak the code to check for the attribute before trimming it.

Feel free to close this if you don't consider it within scope.

**Comment by Garbee** [comment]
Yup. We don't support select.
