### ISSUE TITLE
Site Showcase Request

### ISSUE THREAD

**Issue by paulocastroo** [google/material-design-lite#5149]
Please include:
* Description
Some links doesn work anymore
* Primary Link
https://getmdl.io/showcase/index.html
* Screenshot
![image](https://user-images.githubusercontent.com/25338933/29543444-c645841e-8713-11e7-9796-5955e9610626.png)

**Comment by Garbee** [comment]
It looks to be back up. Contributor is currently going through a re-build phase so it may have occasional downtime.

MDL is no longer being maintained so no updates to the showcase are going to occur from here on out.

Thank you.
