### ISSUE TITLE
Google Material Design Lite will break IE11 Print Function - Only prints first page. The file material.css is the culprit.

### ISSUE THREAD

**Issue by JOESIDinc** [google/material-design-lite#5150]
Hi Google,

This issue was not fixed in IE11. Material Design Lite will break the IE11 print function. The file that breaks IE11 is material.css. The break in IE11 is that after hitting print only 1 page is printed. Regardless of how many pages you have it will stop after the first page. It works fine in Chrome unfortunately my company still uses IE11. Any other attempt including this JavaScript work around will not fix it. My current version of IE is 11.0.9600.18738CO Update Versions 11.0.44 (KB4025252).

My MDL version is: v1.3.0
My OS is: Windows 7 Enterprise

This is the JavaScript work around code everyone raves about but wont fix the underlining issue in material.css:
var printContents = document.getElementById("YourDiv").innerHTML;
var popupWin = window.open('', '_blank', 'width=960,height=540');
popupWin.document.open();
popupWin.document.write('<title>Indirect TPMS Calibration (Interactive)</title>' + printContents + '');
popupWin.document.close();

The block of code in material.css that will break the print function is this:

/* Everything below here breaks IE11 Print Function /
.mdl-layout { width: 100%; height: 100%; display: flex; flex-direction: column; overflow-y: auto; overflow-x: hidden; position: relative; }
.mdl-layout:not(.is-small-screen) .mdl-layout--small-screen-only { display: none; }
.mdl-layout__container { position: absolute; width: 100%; height: 100%; }
.mdl-layout__drawer.is-visible ~ .mdl-layout__content.mdl-layout__content { overflow: hidden; }
.mdl-layout__header .mdl-layout__drawer-button { position: absolute; color: rgb(255, 255, 255); background-color: inherit; }
.mdl-layout__header { display: flex; flex-flow: column nowrap; justify-content: flex-start; box-sizing: border-box; flex-shrink: 0; width: 100%; margin: 0px; padding: 0px; border: none; min-height: 64px; max-height: 1000px; z-index: 3; background-color: rgb(63, 81, 181); color: rgb(255, 255, 255); box-shadow: rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px; transition-duration: 0.2s; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-property: max-height, box-shadow; }
.mdl-layout--fixed-drawer.is-upgraded:not(.is-small-screen) > .mdl-layout__header { margin-left: 240px; width: calc(100% - 240px); }
.mdl-layout__header > .mdl-layout-icon { position: absolute; left: 40px; top: 16px; height: 32px; width: 32px; overflow: hidden; z-index: 3; display: block; }
.mdl-layout.has-drawer .mdl-layout__header > .mdl-layout-icon { display: none; }
.mdl-layout__header--waterfall.is-casting-shadow { box-shadow: rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px; }
.mdl-layout__header-row { display: flex; flex-flow: row nowrap; flex-shrink: 0; box-sizing: border-box; align-self: stretch; align-items: center; height: 64px; margin: 0px; padding: 0px 40px 0px 80px; }
.mdl-layout--no-drawer-button .mdl-layout__header-row { padding-left: 40px; }
.mdl-layout__header--scroll .mdl-layout__header-row { width: 100%; }
.mdl-layout__header-row .mdl-navigation { margin: 0px; padding: 0px; height: 64px; flex-direction: row; align-items: center; }
.mdl-layout__header-row .mdl-navigation__link { display: block; color: rgb(255, 255, 255); line-height: 64px; padding: 0px 24px; }
.mdl-layout__content { position: relative; display: inline-block; overflow-y: auto; overflow-x: hidden; flex-grow: 1; z-index: 1; }
/ Everything above here breaks IE11 Print Function */

Removing the last line in that block will cause the print function to spit out 300 pages.
Please help me resolve this I SPENT A LOT OF TIME ISOLATING THIS CODE.

Thanks - Joe

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

This is a bug in IE's print functionality not MDL's code. Since IE is no longer supported by MS, them fixing this bug is highly unlikely. Therefore, you'll need community support in finding a work-around to the problem. This project is no longer being maintained any further. It has evolved into [Material Components for Web](https://github.com/material-components/material-components-web) as a true reference implementation from the MD team. If the problem persists within those components, then an issue there would be appropriate for triage as to whether those components are in need of changes to work on IE11.

The problem seems to be stemming from the content container being absolutely positioned for legacy IE support. So if you can in print mode undo those changes and make content container resize the body itself that should do the trick. It's just an untested hunch though based on previous experience with the layout system.

Thank you.

**Comment by JOESIDinc** [comment]
Hi Garbee,
Thank you for your fast reply. Just as a heads up, by removing that code block mentioned above I was able to fix the issue on IE11. The only tiny bug is that it puts a horizontal scrollbar on the bottom of the browser. This issue also shows on Chrome and FireFox so I want the block of code put back in but only if its not IE11.

    <link rel="stylesheet" href="css/material_IE11.css" type="text/css">

    
    
    <script type="text/javascript">
        var is_chrome = navigator.userAgent.toLowerCase().indexOf('chrome') > -1;
        if(is_chrome){
            document.write('<link rel="stylesheet" href="mdl/material.css" type="text/css">');
        }
    </script>

[MDL_IE11_Fix.txt](https://github.com/google/material-design-lite/files/1250320/MDL_IE11_Fix.txt)

Again referencing this code block:
/* Everything below here breaks IE11 Print Function /
.mdl-layout { width: 100%; height: 100%; display: flex; flex-direction: column; overflow-y: auto; overflow-x: hidden; position: relative; }
.mdl-layout:not(.is-small-screen) .mdl-layout--small-screen-only { display: none; }
.mdl-layout__container { position: absolute; width: 100%; height: 100%; }
.mdl-layout__drawer.is-visible ~ .mdl-layout__content.mdl-layout__content { overflow: hidden; }
.mdl-layout__header .mdl-layout__drawer-button { position: absolute; color: rgb(255, 255, 255); background-color: inherit; }
.mdl-layout__header { display: flex; flex-flow: column nowrap; justify-content: flex-start; box-sizing: border-box; flex-shrink: 0; width: 100%; margin: 0px; padding: 0px; border: none; min-height: 64px; max-height: 1000px; z-index: 3; background-color: rgb(63, 81, 181); color: rgb(255, 255, 255); box-shadow: rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px; transition-duration: 0.2s; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-property: max-height, box-shadow; }
.mdl-layout--fixed-drawer.is-upgraded:not(.is-small-screen) > .mdl-layout__header { margin-left: 240px; width: calc(100% - 240px); }
.mdl-layout__header > .mdl-layout-icon { position: absolute; left: 40px; top: 16px; height: 32px; width: 32px; overflow: hidden; z-index: 3; display: block; }
.mdl-layout.has-drawer .mdl-layout__header > .mdl-layout-icon { display: none; }
.mdl-layout__header--waterfall.is-casting-shadow { box-shadow: rgba(0, 0, 0, 0.14) 0px 2px 2px 0px, rgba(0, 0, 0, 0.2) 0px 3px 1px -2px, rgba(0, 0, 0, 0.12) 0px 1px 5px 0px; }
.mdl-layout__header-row { display: flex; flex-flow: row nowrap; flex-shrink: 0; box-sizing: border-box; align-self: stretch; align-items: center; height: 64px; margin: 0px; padding: 0px 40px 0px 80px; }
.mdl-layout--no-drawer-button .mdl-layout__header-row { padding-left: 40px; }
.mdl-layout__header--scroll .mdl-layout__header-row { width: 100%; }
.mdl-layout__header-row .mdl-navigation { margin: 0px; padding: 0px; height: 64px; flex-direction: row; align-items: center; }
.mdl-layout__header-row .mdl-navigation__link { display: block; color: rgb(255, 255, 255); line-height: 64px; padding: 0px 24px; }
.mdl-layout__content { position: relative; display: inline-block; overflow-y: auto; overflow-x: hidden; flex-grow: 1; z-index: 1; }
/ Everything above here breaks IE11 Print Function */

Hope this helps anyone who has this issue. Consider this resolved.

Thanks - Joe
