### ISSUE TITLE
Tooltips not working in table

### ISSUE THREAD

**Issue by SkyPunster** [google/material-design-lite#5152]
MDL Version - 1.3.0
OS - Windows 10
Chrome version -  60.0.3112.113

If you want to put tooltips on table callse, in some rows you will not see tooltip. Count of this rows may change. In this example https://codepen.io/SkyPunster/pen/yordKb on column "Вид работ" you can see, that in first row tooltip is not working. In my case with table with 91 rows first 6 wors is not showing tooltip. I tried to move table in document, in some positions it works, but in some it work every second update of document (i just pressed F5).
P.S. Sorry for my English, if you did not understand something, I can explain it, or show more detailed infomation.

**Comment by tabakisp** [comment]
Line 59, remove ` data-upgraded=",MaterialTooltip"`

**Comment by SkyPunster** [comment]
Finded out my problem, sorry, it's my fault. ID in my document was not unique.
