### ISSUE TITLE
Space at the top of the page

### ISSUE THREAD

**Issue by TheDiamondYT1** [google/material-design-lite#5157]
There is a gap between the content and top of the web page.

![screenshot_2017-09-17-19-14-04](https://user-images.githubusercontent.com/14148452/30523615-7941ef1c-9bdc-11e7-88a7-6900753ad755.png)

Here is my generated HTML from pugjs:

```html
<!DOCTYPE html>
<html>
  <head>
	<title>lol</title>
	<meta charset="utf-8">
	<meta name="description" content="null">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-pink.min.css">
	<link rel="stylesheet" href="style.css">
	<script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </head>
<body>
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
	<header class="mdl-layout__header mdl-color-text--white-600">
	  <div class="mdl-layout__header-row">
		<ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right"></ul>
	  </div>
	</header>
	<div class="mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
	  <nav class="mdl-navigation mdl-color--blue-grey-800"><a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a></nav>
	</div>
	<main class="mdl-layout__content mdl-color--grey-100">
	  <div class="landing">
		<h3>Hey there!</h3>
	  </div>
	</main>
  </div>
</body>
</html>
```

**Comment by TheDiamondYT1** [comment]
I still have the problem if i remove the navbar there's still a gap at the top

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

The Fire browser is not something we support internally. And the demos are all working as expected. I'd suspect something in the custom `style.css` file being the cause of it if the Fire browser isn't the source of the problem.

Thank you.

**Comment by TheDiamondYT1** [comment]
@Garbee It doesn't work in Android Chrome, either. It shouldn't be my CSS.

```css
.mdl-layout__header, .mdl-layout__drawer {
  background: white;
}

.landing {
  background-image: url("http://localhost:8080/static/images/code.png");
  height: 300px;
}

.landing > h3 {
  color: white;
  text-align: center;
}
```

**Comment by TheDiamondYT1** [comment]
Please check out this pen (ignore the fact the photo is duplicated, it still takes up the same screen space)

https://codepen.io/anon/pen/GMpXor

**Comment by TheDiamondYT1** [comment]
Sorry, you're right — probably to do with the height attribute
