### ISSUE TITLE
Footer at the bottom of the page not behaving as it should.

### ISSUE THREAD

**Issue by ghost** [google/material-design-lite#5158]
Ok so I was fiddling around with the `index.html` of the blog theme. And deleted all posts but one in said file. Now I noticed that the footer is hovering some way above the extreme bottom of the page. I want it to stick to the bottom of the page i.e.: there should be no space betwen the bottom of the page and the footer.  In order to illustrate what I mean here's a paste that illustrates just that: https://pastebin.com/w1FjDK91

Just substitute this with the `index.html` from the blog template and then you will see what I am on about. How do I fix this? It is quite urgent!! Thanks in advance!:)

**Comment by Garbee** [comment]
Please use StackOverflow for support and integration assistance. This tracker is only for problems with the code provided by Material Design Lite.

The footer is working as expected. You're asking for help with how to make custom code to make your design work which isn't something this issue tracker is for. General support such as StackOverflow will be able to help you figure out the custom CSS needed to make that work.

Also try searching previous closed issues for sticky footer stuff. It has come up a few times before and others have proposed workable code to address this need.

Thank you.
