### ISSUE TITLE
mdl-table-selectable

### ISSUE THREAD

**Issue by asarro** [google/material-design-lite#5160]
![image](https://user-images.githubusercontent.com/5725101/30688492-384d82d2-9eb6-11e7-8beb-bf9af90a0baa.png)
Hi, I tried to use your mdl-select-table and it seems to render the checkbox on its own then renders the table completely. For lack of a better word, it flickers this then shows the table.

**Comment by Garbee** [comment]
Custom elements aren't provided by MDL. Please ask for help from whomever provides those wrappers. Or for general support on StackOverflow. This isn't an issue with direct MDL components.

Thank you.
