### ISSUE TITLE
I hope to contribute code to MDL

### ISSUE THREAD

**Issue by achun** [google/material-design-lite#5161]
Hey, the team.

I know that MDL 1.X is no longer being maintained.
However, I am convinced that MDL is lighter than material-components-web.
I carefully read the componentHandler code, understand it to achieve the function.
The core problem is how to solve the DOM mutation.
I have this experience, see: https://github.com/zdhxiong/mdui/pull/96

Of course, solving DOM mutations under MDL requires redesigning code. This can be done.

I hope to contribute code to MDL. 

MDL's original design is very light, I believe that this is a lot of developers need.

I am waiting for my request to be supported.

**Comment by Garbee** [comment]
You will need to fork MDL into a new project. This project is no longer maintained and any new major patches won't be reviewed.

MDL is "lighter" than MCW in many respects, while not in others. MCW aims to address a good number of the issues developers had with MDL, hence the growth of the code complexity in a few areas.

Thank you.
