### ISSUE TITLE
Snackbar/Toast is always hidden

### ISSUE THREAD

**Issue by Serubin** [google/material-design-lite#5166]
## Bugs

Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

v1.3.0

> What browser(s) is this bug affecting (including version)? 

Firefox (57)

> What OS (and version) are you using?

MacOS 10.12, Windows 10

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

Simply try to use a snackbar. 
https://codepen.io/anon/pen/ZXqbja

> What is the expected behavior?

Snackbar should show up with text

> What is the actual behavior?

Snackbar does not show up at all.

> Any other information you believe would be useful?

Something is forcing the snackbar to be hidden. A hidden tag is forcibly applied and the following lines are injected into the source. I'm not sure what is causing this. 
```
:root [qk400lo][hidden] {
	display: none !important;
}
:root .container > .infoBoxList > .shareInfoBox, :root .mdl-snackbar {
	display: none !important;
}
```

Manually removing the "hidden" attribute generally works - other times, it will be re-added by something.

**Comment by Garbee** [comment]
The codepen is working as intended here. Have you tried disabling extensions?

**Comment by Serubin** [comment]
Oh wow - that's interesting. It looks like uBlock origin is the cause. Thanks for pointing me in the direction of extensions.
