### ISSUE TITLE
MDL layouts are too fragile, can't be split into reusable parts for an SPA.

### ISSUE THREAD

**Issue by jpodpro** [google/material-design-lite#5167]
I'm trying to split up a layout into reusable parts for my SPA. However this always seems to break the layout and render incorrectly. It looks like 2.0 is addressing this issue but I wanted to provide the feedback just in case since this framework is pretty much unusable for an SPA unless I want to duplicate code all over the place.

If this may be ready soon please let me know, otherwise I'll have to look elsewhere. thanks.

**Comment by Garbee** [comment]
MDL is no longer being maintained. It was designed with fairly static renderings in mind and not SPA usage. [Material Components for Web](https://github.com/material-components/material-components-web) is recommended for future projects, especially JS-driven ones.

MCW is MDL v2. It has been moved into another team and is being made as a reference implementation of the spec.
