### ISSUE TITLE
Cards cannot show their menus fully if they are less high than their menus and they're followed by other cards

### ISSUE THREAD

**Issue by axelerator** [google/material-design-lite#5173]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

1.3.0

> What browser(s) is this bug affecting (including version)? 

Google Chrome Version 62.0.3202.94

> What OS (and version) are you using?

Mac OS 10.12.6

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

https://jsfiddle.net/esc0mvqm/2/

> What is the expected behavior?

Menus from cards should overlap other cards.

> What is the actual behavior?

Menus that are longer than their cards get cut off.

> Any other information you believe would be useful?

I set some properties to the cards - see the actual text they are displaying in the example

**Comment by Garbee** [comment]
This is a long known issue. If you need the menus to overflow then you need to modify the overflow rule on the card containers.

No changes will be made internally to allow for this at this point. There won't be a v2 as that evolved into the Material Components for Web effort.

Thank you.
