### ISSUE TITLE
Text input is overlapped by Android keyboard. (autoscroll not working)

### ISSUE THREAD

**Issue by liflovs** [google/material-design-lite#5196]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.3.0

> What browser(s) is this bug affecting (including version)? 
Chrome Android

> What OS (and version) are you using?
Android

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Tap on MDL input (text) field

> What is the expected behavior?
Android keyboard does not overlap the input

> What is the actual behavior?
Android keyboard overlaps the input. Autoscroll is not working

This is popular bug. But unfortunately none of the fixes in the web helps. 
It even does no work on the demo website.
Disabling material css fixes problem

**Comment by manish-91** [comment]
I too faced this issue. Is there is any workaround. I think this is serious problem to be tackled asap.

**Comment by liflovs** [comment]
@manish-91 this is issue is rather related to Chromium on Android:
https://bugs.chromium.org/p/chromium/issues/detail?id=404315
https://bugs.chromium.org/p/chromium/issues/detail?id=490618
The ticket might be closed.

**Comment by manish-91** [comment]
So, how to overcome this ? Any suggestions or any plugin. I am using mdl with firebase.

**Comment by liflovs** [comment]
@manish-91  No real solution. If you like just how mdl buttons, headers look - you can omit default mdl navigation style, etc and have scrollable page. But then you should recheck whole application.
These were two hacks i did:
`.mdl-layout {
    width: auto;
    height: auto;
}
body {
    background-color: rgb(245, 245, 245) !important;
}`
But then it required much more and i gave up. Think will just ignore the issue until google fixes it.

**Comment by liflovs** [comment]
Closing the issue as mdl is really outdated atm, better use more up-to-date libs
