### ISSUE TITLE
Launch FAQs

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#521]
At launch, developers are going to have a few questions about MDL and where it fits in with the current landscape of things. Let's collect some questions that are likely to be asked and we can get answers drafted :star2: 

* [x] How does MDL compare to existing third-party Material CSS implementations, like Materialize? Why should we use it instead?
* [ ] Is MDL a replacement for using Polymer and the paper-* elements? Do they play well together?
    * Initial answer by Garbee, needs review from someone more knowledgeable with Polymer.
* [x] What use-cases does MDL tackle? Should we use it for content sites? Apps?
* [ ] What does the long-term support plan for MDL look like? Can we expect Google to support it for a long time?
* [x] Where does MDL sit when it comes to graceful degradation?
* [x] Is MDL comparable to Twitter Bootstrap? If we're using it instead of Bootstrap, can we expect the same level of component styling?
* [ ] What Google properties are using MDL? Are any of them using it in production today?
* [ ] what's the relationship between MDL and Web Starter Kit?
    * Initial answer by Garbee, needs review.
* [x] What is the CDN Service used?
* [ ] Should I build my own version or download the runtime objects or simply refer to CDN objects?
* [ ] How do I customize MDL for my needs?

**Comment by innerpeace0** [comment]
How it integrates with AngjuarJS would be helpful, too.

**Comment by surma** [comment]
@innerpeace0 There’s not much to tell. MDL is completely framework agnostic and mostly relies on CSS classes.

Some manual work might have to be done on dynamically created DOM elements, which we have a section for in the [Getting Started guide](http://www.getmdl.io/started/index.html#dynamic).
