### ISSUE TITLE
Variables throws an issue that incompatible variables are mixed

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#523]
This line threw an error when I tried to build my own css pulling in variables and _footer.

$spinner-duration: 360deg * $spinner-arc-time / (
    $spinner-arc-start-rot + (360deg - $spinner-arc-size));

Basically spinner-arc-time is ms and multiplying that by 360deg causes an error.

**Comment by 7immy** [comment]
I'm getting a very similar issue on line 308:20

**Comment by sgomes** [comment]
Closing as I believe this was fixed somewhere along the way. If not, please reopen!
