### ISSUE TITLE
MDL V.1.3.0 does not work in Microsoft Edge

### ISSUE THREAD

**Issue by dhuertasanchez** [google/material-design-lite#5239]
I am using version 1.3.0 of mdl, I have made some layouts with this version and they work correctly in Firefox, Google Chrome, Safari, Opera, etc, but when I visualize in Microsoft Edge all the styles are completely lost and appear as elements without css , at first I thought that maybe my css was badly written or something, so I decided to do a test by copying a section of example layout code put in the getmdl.io site, but the same thing happens, the styles do not work, I have done the same test on several computers and the result is the same, the version of Edge in which I have done the tests is the following:

Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

This in Windows 10 V.18.03 (compilation of OS 17134.285)

When opening a file with mdl it looks like in the image that I attached ...
![captura](https://user-images.githubusercontent.com/8291300/45932082-d064a580-bf3c-11e8-9ac0-0380d5ea3590.PNG)

**Comment by MichaelTimbes** [comment]
I know this is from over a year ago but for other people looking for a solution, you could start with using this:
[CSS PonyFill](https://jhildenbiddle.github.io/css-vars-ponyfill/#/)

However, the javascript with this library (at least for the pre-built version) may not be compatible. I'm not sure there is really a solution with for that.

**Comment by dhuertasanchez** [comment]
Thanks, I will try it, although I am also migrating to MDC because I have seen that MDL has not been updated anymore ...
