### ISSUE TITLE
Toasts need debouncing

### ISSUE THREAD

**Issue by thdoan** [google/material-design-lite#5240]
## Bugs

Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)

v1.3.0

> What browser(s) is this bug affecting (including version)? 

All

> What OS (and version) are you using?

Windows 10

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?

1. Go here https://codepen.io/thdoan/pen/XxbwVx
2. Click on the Notify button repeatedly fast

> What is the expected behavior?

The toast should have built-in debouncing so that rapid clicks in succession are better handled.

> What is the actual behavior?

A bunch of toasts showing up one after another.

> Any other information you believe would be useful?

I hope this issue will be dealt with in v2.

**Comment by Garbee** [comment]
The toast is just an element that provides the notification ability. It is up to *developers* implementing their applications to use it thoughtfully and debounce if appropriate in the contexts they are applying it.

**Comment by thdoan** [comment]
Thanks, I did just that.
