### ISSUE TITLE
Update Material slider UI when another slider is changed

### ISSUE THREAD

**Issue by vipera7** [google/material-design-lite#5250]
I'm in trouble with my inputs. Both of the inputs are connected. When you click on the first one, the second inputs will move but the css will not update.

Here is the fiddle to reproduce :
https://jsfiddle.net/j7rqb96t/

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/0BZDM.png

Solution: https://jsfiddle.net/j7rqb96t/1/

**Comment by aburai** [comment]
use instance method change
`$ra2.get(0).MaterialSlider.change(this.max - this.value);`
