### ISSUE TITLE
Text field is higher than sample page.

### ISSUE THREAD

**Issue by acollazomayer** [google/material-design-lite#5253]
Hi I copy the code from the codepen from the text fields:

And i get this:

<img width="538" alt="screen shot 2018-11-29 at 12 48 35 pm" src="https://user-images.githubusercontent.com/9849229/49233610-1e7ea500-f3d5-11e8-8822-f5e6e8a7cdc4.png">

Insted of this.

<img width="381" alt="screen shot 2018-11-29 at 12 49 01 pm" src="https://user-images.githubusercontent.com/9849229/49233642-2d655780-f3d5-11e8-8913-97440ac2b41f.png">

Is like the input has a bigger height.

**Comment by aburai** [comment]
ensure you load material.min.css and check that no other css override it (ex. dev tools elements styles)
