### ISSUE TITLE
It is invalid when used with pjax.

### ISSUE THREAD

**Issue by xxyangyoulin** [google/material-design-lite#5259]
When using pjax, MDL Components cannot be initialized more than once, and the dynamic effect is invalid.
Can it be solved? Thanks!

**Comment by xxyangyoulin** [comment]
For the same element, after MDL is initialized once, calling `componentHandler.upgradeDom();` again is invalid

**Comment by xxyangyoulin** [comment]
Thank you. I've solved this little problem.
As follows:
`var page = $('#page-content');
        page.find('*[class^=mdl]').removeClass('is-upgraded').removeAttr("data-upgraded");
componentHandler.upgradeDom();`

**Comment by bleonard252** [comment]
I believe the author can close if it's solved?
