### ISSUE TITLE
Is there any way to create a toolbar with tabs and no drawer icon?

### ISSUE THREAD

**Issue by wellingtoncosta** [google/material-design-lite#5260]
I would like to create a simple toolbar with fixed tabs and without drawer. I tried to remove the drawer icon but it seems like it still there, but invisible. Any tip?

**Comment by aburai** [comment]
you did not show code, but here is an example -> https://getmdl.io/components/index.html#layout-section/tabs

**Comment by wellingtoncosta** [comment]
Of course. I already saw this example, but it doesn't colored with the theme colors. Anyway I'm doing what I want with pure CSS.
