### ISSUE TITLE
Ripple Effect too fast

### ISSUE THREAD

**Issue by BerkeAras** [google/material-design-lite#5265]
Hi,

I think that the Ripple effect of the buttons is too fast. How can I make it slower like Angular Material (https://material.angular.io/components/button/examples) or Material-UI (https://material-ui.com/demos/buttons/)

**Comment by aburai** [comment]
you can overwrite `.mdl-ripple.is-animating` with your own transition or transition-delay

**Comment by BerkeAras** [comment]
@aburai Can you give an example Code?

**Comment by aburai** [comment]
Original
```
.mdl-ripple.is-animating {
    transition: width 0.3s cubic-bezier(0, 0, 0.2, 1), height 0.3s cubic-bezier(0, 0, 0.2, 1), opacity 0.6s cubic-bezier(0, 0, 0.2, 1), -webkit-transform 0.3s cubic-bezier(0, 0, 0.2, 1);
    transition: transform 0.3s cubic-bezier(0, 0, 0.2, 1), width 0.3s cubic-bezier(0, 0, 0.2, 1), height 0.3s cubic-bezier(0, 0, 0.2, 1), opacity 0.6s cubic-bezier(0, 0, 0.2, 1);
    transition: transform 0.3s cubic-bezier(0, 0, 0.2, 1), width 0.3s cubic-bezier(0, 0, 0.2, 1), height 0.3s cubic-bezier(0, 0, 0.2, 1), opacity 0.6s cubic-bezier(0, 0, 0.2, 1), -webkit-transform 0.3s cubic-bezier(0, 0, 0.2, 1);
}
```
set this inside your css that is loaded after material.css and change the delays by ex. from 0.3s to 0.6s
