### ISSUE TITLE
Text and Icon not on same line in button

### ISSUE THREAD

**Issue by BerkeAras** [google/material-design-lite#5266]
Hi,

I have a Button with a text and an icon in it. The text and the icon are not on the same line (see image).
How can I fix that.
![material-button](https://user-images.githubusercontent.com/36629890/54072706-d1855700-427e-11e9-909c-6f2da8584730.PNG)

**Comment by aburai** [comment]
i think as a hotfix, you can set `margin-top: -4px` or some other px to the icon tag
if i remember correct, change `vertical-align` doesn't work
does that work for you? if not, i can start my testserver and have a look

**Comment by BerkeAras** [comment]
`margin-top: -3px` worked perfectly. Changing `vertical-align` doesnt works :(
