### ISSUE TITLE
[Component Request] {Fully Outlined Text Field}

### ISSUE THREAD

**Issue by Haidar-Hammoud** [google/material-design-lite#5267]
* Would it be possible to create a new text field similar to that available on many Google sites?
* It outlines the entire textfield to better show which one is active - here's a screenshot of a selected and neutral one:
<img width="401" alt="Screen Shot 2019-03-09 at 3 41 40 PM" src="https://user-images.githubusercontent.com/26990440/54077125-5c1b8580-4282-11e9-9344-d13df367a19f.png">

**Comment by aburai** [comment]
these are Material Design 2 specs

**Comment by bleonard252** [comment]
This project has stopped all but critical development (even if they won't admit it). You need to use Material Components for Web or something similar if you want this.
