### ISSUE TITLE
Navigation Link with ripple effect

### ISSUE THREAD

**Issue by BerkeAras** [google/material-design-lite#5268]
Hi,

how can I make a navigation link with a ripple effect?

**Comment by aburai** [comment]
@BerkeAras you should provide some sample code so we can see what you try

**Comment by iamabs2001** [comment]
@BerkeAras

 **You give  class to nav items (class = "mdl-js-ripple-effect") and provide it ripple effect.**

example : https://codepen.io/mdlhut/pen/GJemae?editors=1000
