### ISSUE TITLE
Potentially outdated license

### ISSUE THREAD

**Issue by fifn2** [google/material-design-lite#5271]
https://github.com/google/material-design-lite/blob/60f441a22ed98ed2c03f6179adf460d888bf459f/LICENSE#L190
What's up with the copyright year? Does it need to be updated like with the MIT license?

**Comment by Garbee** [comment]
You don't update license years unless substantial work has gone into the system within that year. Otherwise it's pretty meaningless legally. It's fine how it is.

**Comment by fifn2** [comment]
Thanks I learned something
