### ISSUE TITLE
Selecting a Cloned Text Input doesn't change its label's style

### ISSUE THREAD

**Issue by ATablas** [google/material-design-lite#5276]
I'm using this version:
https://code.getmdl.io/1.3.0/material.min.js
I've only tested the script on Chrome.
I'm on Windows 10.
Here's a JSFiddle:
https://jsfiddle.net/gc4qzfxn/

I'm using a button to clone text inputs.
The label of the cloned text input must be dynamic and move upwards when I select it, as it usually does.
However, here it doesn't. And even when I type, the text I type appears over the label.

I tried updating the IDs of the text input and the label, but it doesn't help.

**Comment by aburai** [comment]
remove the upgraded informations on the textfield before upgradeDom
`clonedTxtBox.find('.mdl-textfield').removeClass('is-upgraded').removeAttr('data-upgraded');`

**Comment by ATablas** [comment]
Thank you. I hadn't thought of it.

> remove the upgraded informations on the textfield before upgradeDom
> `clonedTxtBox.find('.mdl-textfield').removeClass('is-upgraded').removeAttr('data-upgraded');`
