### ISSUE TITLE
maybe list something like this in the readme

### ISSUE THREAD

**Issue by ORESoftware** [google/material-design-lite#5280]
maybe list something like this in the readme:

```readme
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
```

instead of using npm etc, I just want to install via url/cdn, and I am looking for simple instructions for like that in the readme.

if you don't want to clutter the readme, that I understand, and in that case, you can use:

```
<details>
  <summary>Installation Instructions</summary>
</details>

```

to GREAT effect

**Comment by Garbee** [comment]
The website included this getting started information in the docs. The repository was for working on the code itself for the library and site. It wasn't written nor intended to help developers get to using it, that's what the site docs were for.

MDL has been superseded by Material Components for Web though, so you should be using that over MDL now.
