### ISSUE TITLE
Typo in styles.md documentation

### ISSUE THREAD

**Issue by huzaima** [google/material-design-lite#5282]
There is a typo in documentation for styles page.

mdl-1.x/docs/_pages/styles.md

> What is the expected behavior?
This portion is only to demonstrate header and display styles for **our** CSS.

> What is the actual behavior?
Typo is highlighted in following line:
This portion is only to demonstrate header and display styles for **out** CSS.

**Comment by ChiragAgarwal7** [comment]
I will fix that

**Comment by psyduck1203** [comment]
i can fix this issue !

**Comment by huzaima** [comment]
> i can fix this issue !

This is already fixed. Check #5283
