### ISSUE TITLE
Duplicate Display Directive in Card SCSS

### ISSUE THREAD

**Issue by kylie-sre** [google/material-design-lite#5331]
## Bugs

Please include the following information with your bug report:

> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.3.0

> What browser(s) is this bug affecting (including version)? 
N/A

> What OS (and version) are you using?
N/A

> Any other information you believe would be useful?
Display rule is duplicated here: https://github.com/google/material-design-lite/blob/mdl-1.x/src/card/_card.scss#L47

**Comment by aburai** [comment]
I think it's more a fallback for browsers which does not support `display: flex`.

**Comment by Garbee** [comment]
@aburai is correct. This was a fallback for older IE's that were supported but didn't have flex support.

MDL is also no longer maintained. Check out [Material Components for Web](https://material.io/develop/web/) for what MDL became.
