### ISSUE TITLE
Radio button doesn't reset to initial

### ISSUE THREAD

**Issue by vipera7** [google/material-design-lite#5334]
I have the following radio buttons which share the same `name` :

    <div id="main_div">
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="radio1">
            <input type="radio" id="radio1" class="mdl-radio__button" name="somename" value="1" checked>
            <span class="mdl-radio__label">Radio 1</span>
        </label>
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="radio2">
            <input type="radio" id="radio2" class="mdl-radio__button" name="somename" value="2">
            <span class="mdl-radio__label">Radio 2</span>
        </label>
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="radio3">
            <input type="radio" id="radio3" class="mdl-radio__button" name="somename" value="3">
            <span class="mdl-radio__label">Radio 3</span>
        </label>
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="radio4">
            <input type="radio" id="radio4" class="mdl-radio__button" name="somename" value="4">
            <span class="mdl-radio__label">Radio 4</span>
        </label>
        <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="radio5">
            <input type="radio" id="radio5" class="mdl-radio__button" name="somename" value="5">
            <span class="mdl-radio__label">Radio 5</span>
        </label>
    </div>

I can't make a fidle of it beacause, I need to change the page and go back. 

When I check for example the radio `radio3` and go the next page using a link and then click on the browser to go back. My radio `radio3` button is still  checked but I gave by default the `radio1` the attribute `checked` so I think the `radio1` should be checked.

I saw in the label in the `radio3` the following class `is-checked` but the input isn't checked.

## Bugs

> What browser(s) is this bug affecting (including version)? 
Chrome

> What OS (and version) are you using?
W10

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Can't reproduce, need to change page

> What is the expected behavior?
The default checked radio should be checked

> What is the actual behavior?
Another radio button is checked

> Any other information you believe would be useful?

**Comment by iamabs2001** [comment]
how you changing the page ? <a> anchor tag or going back through browser back button(cached) ?

**Comment by vipera7** [comment]
I'm moving back throught the browser. I resolved it using `autocomplete="off"`
