### ISSUE TITLE
Menu incompatibility with Svelte if condition

### ISSUE THREAD

**Issue by m1212e** [google/material-design-lite#5347]
> What MDL Version are you using? (please be specific, e.g. _major.minor.patch_)
1.3.0 via CDN

> What browser(s) is this bug affecting (including version)? 
Chromium

> What OS (and version) are you using?
Win 10

> What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
Using the Svelte Framework and the Menu component.
Open the menu via. click.
The menu is located inside an if condition which becomes false while the menu is opened.
The menu + button diappear from view but still got the "open" classes.
The if statement becomes truthy again and the menu gets rendered.
The dropdown menu isn't visible anymore, but can't be opened via click.

Discovered this while putting a log off button inside a dropdown menu.

**Comment by Garbee** [comment]
I understand you're having an issue integrating MDL with a new framework. Unfortunately, Material Design Lite is no longer being maintained. Please consider a move to the direct successor, [Material Components for Web](https://material.io/develop/web).
