### ISSUE TITLE
Minify scripts and styles in the microsite

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#546]
We currently don't do these leading to a growing number of network requests.

**Comment by sgomes** [comment]
It seems we're now minifying them, but keeping them as separate files. Is this enough, @addyosmani?

**Comment by samccone** [comment]
![screen shot 2015-10-22 at 9 17 31 am](https://cloud.githubusercontent.com/assets/883126/10671106/bfeb8680-789d-11e5-81b6-ac0511b30b2a.png)
![screen shot 2015-10-22 at 9 17 23 am](https://cloud.githubusercontent.com/assets/883126/10671107/bffbf0c4-789d-11e5-8ece-644f92fff8e7.png)


woot all done I think :)
