### ISSUE TITLE
Build fails when .jscsrc and .jshintrc are missing

### ISSUE THREAD

**Issue by PaulKinlan** [google/material-design-lite#549]
I copied the material design repo into my projects working directory and in that process none of the dotfiles were copied across.  Subsequently when I did `gulp` to make a dist build it failed.  It would be great to have the `gulp` build process handle this and fall back to defaults and WARN rather than fail the build.

**Comment by sgomes** [comment]
Moved to ESLint. We're keeping the failure state, though, as we'd like to enforce code consistency when developing MDL. It shouldn't be a problem for anyone reusing MDL (e.g. from the NPM package), since they'll have a separate build process if building our source.
