### ISSUE TITLE
Something is funky with the blog entry template. [place holder]

### ISSUE THREAD

**Issue by PaulKinlan** [google/material-design-lite#551]
I literally have the same CSS and I get, when I expected something a little more layed out (sans images like the actual teamplate).

I am leaving this as a placeholder and I will raise individual issues if I can.

![screen shot 2015-06-30 at 1 45 54 pm](https://cloud.githubusercontent.com/assets/45510/8431057/a67f3ec6-1f2e-11e5-8173-5029c13acd7b.png)
![screen shot 2015-06-30 at 1 46 51 pm](https://cloud.githubusercontent.com/assets/45510/8431056/a67c966c-1f2e-11e5-9795-8f6b07da4e3b.png)

**Comment by Garbee** [comment]
I don't see where in the CSS or JS it is specifically calling the main element. So why exactly is it required compared to say using a `div`?
