### ISSUE TITLE
comps index page not rendering correctly on IE11

### ISSUE THREAD

**Issue by marcacohen** [google/material-design-lite#559]
From @addyosmani : This is looking great. Just a few more minor nits. In IE11, we're seeing some sizing issues with the shapes graphic and a little positioning trouble with the intro paragraph:
![687474703a2f2f692e696d6775722e636f6d2f313761706443732e706e67](https://cloud.githubusercontent.com/assets/658327/8438958/e7fbd436-1f60-11e5-8ea1-f0ca8747ac20.png)

**Comment by sgomes** [comment]
This has been fixed since before v1.
