### ISSUE TITLE
Remove list component

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#578]

**Comment by vicmortelmans** [comment]
Can I be notified somehow when a list component becomes available?

**Comment by Garbee** [comment]
You can subscribed to notifications for issue #584 for updates on lists.

**Comment by rohanthacker** [comment]
@addyosmani  Hey Addy, is the code you refer to above available on github?

**Comment by Garbee** [comment]
@rohanthacker It is in the history of this repository yes. You can see what was removed in pr #581. Just remember you have a clean slate to implement the spec as best you can. No real need to work from what was done previously.

**Comment by rohanthacker** [comment]
+1 Will look through thanks again.
