### ISSUE TITLE
[Component Request] Lists

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#584]
Lists are one of the most widely used types of markup. Should be self-explanatory why we need this. [Material Design specification for lists](https://www.google.com/design/spec/components/lists.html).

Use cases:
* Display hierarchical information concisely
* Displaying information that directly relates to other information.
* Menus
* Neatly displaying application data lists that don't fit into a table.

**Comment by peluprvi** [comment]
It has some [controls ](https://www.google.com/design/spec/components/lists-controls.html) too.

**Comment by Garbee** [comment]
Controls are already implemented. Checkboxes, radios, etc. They would just need to be added to the list item markup.

**Comment by rohanthacker** [comment]
Is anyone working actively on the List Component? Would be more than willing to help out and get this feature added into MDL

**Comment by Garbee** [comment]
It isn't assigned to anyone. So I'd assume no current work is being done on the component.

Give it a shot if you want. Community contributions always welcome.

**Comment by rohanthacker** [comment]
Great, Thank you. will give it try. 

If anyone else wants to help out please do get in touch.
