### ISSUE TITLE
Component page doesn't render with JS off

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#585]
In particular something folks on a slow network connection may run into, we actually ship all of the content to this page down to the client but don't give them a way to view it unless they have JS on:

![](http://i.imgur.com/MSJeoqO.png)

One option is making `.mdl-components .mdl-components__page` `display:block` by default and hide using JS instead of the other way around.

**Comment by sgomes** [comment]
Documentation will be rewritten from scratch for v2.
