### ISSUE TITLE
Typography: <p> nested inside <blockquote>

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/material-design-lite#592]
Multiple `<p>` elements inside `<blockquote>` elements look a bit odd:

![screen shot 2015-07-01 at 5 24 02 pm](https://cloud.githubusercontent.com/assets/51244/8459576/36e6ce7e-2016-11e5-8ae6-af820d965fa9.png)

(The closing quote appears by itself, on a new line.) The raw markup is:

``` html
<blockquote>
<p><strong>Note:</strong> Because the Roboto font is intended to apply to the entire page, standard &quot;unclassed&quot; HTML elements (e.g., heading levels, divs, paragraphs, spans, tables, etc. with no <code>class</code> attribute) and text modifiers (e.g., strong, em, small, etc.) will use Roboto, while also retaining their inherent and/or inherited characteristics.</p>
<p>Also note that MDL typography provides some automatic adjustments based on its display environment. For example, the <code>body-1</code> style renders at 14px on a mobile device, but 13px on a desktop. You need not do anything to activate these self-modifiers; they are built into the MDL styles.</p>
</blockquote>
```

This is from http://mdl-staging.storage.googleapis.com/styles/index.html.

**Comment by riddla** [comment]
I think this is still an issue:
![bildschirmfoto 2015-09-06 um 16 35 52](https://cloud.githubusercontent.com/assets/174157/9704926/6957f6a2-54b5-11e5-9347-1f128525757f.png)

**Comment by remkoboschker** [comment]
```
blockquote p {
  display: inline;
  line-height: 1.35;
}
```
seems to take care of a single nested paragraph

**Comment by Garbee** [comment]
This isn't an MDL problem. Blockquote is only defined through the reset. Otherwise we aren't touching it for any component. So you need to modify it as-needed for your site. Nothing we can nor should do about it.

**Comment by remkoboschker** [comment]
As far as I can tell the blockquote styling is defined in the `_typograpy.scss` by the `typo-blockquote`  mixin.

**Comment by Garbee** [comment]
oh huh, that is interesting. As far as I know there is nothing defined by MD where we need to do that... That is something to figure out then for 2.x to fix. Thanks for pointing that out @remkoboschker.
