### ISSUE TITLE
Roboto not default body font

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/material-design-lite#609]
https://github.com/google/material-design-lite/blob/master/docs/_pages/styles.md (rendered as `/styles/index.html`) says "The 'Roboto' typeface is the standard for MDL display" however by default body text appears to be rendered as a "[performance font](https://github.com/google/material-design-lite/blob/e0f3f21a33e45886d8be738ad41a1bc3ca1ab84f/src/_variables.scss#L46)", which will typically be either Helvetica or Arial.

Perhaps either:

* the typography docs be changed to explain that Roboto is not the default body font, or
* Roboto be made the default body font

(Note that Roboto *is* the body font across the MDL site.)

**Comment by OliverJAsh** [comment]
Could we add this to the docs to make it explicit? Robot is part of the spec, but in this case it's optional—correct?

**Comment by innerpeace0** [comment]
A clarification on how to use Roboto everywhere the body would be appreciated. Many users will already have Roboto in their browser caches, so performance will probably not be a big issue. 

One of the things I especially like about MD is that it is *All Roboto -- All the Time* (for languages with Roman style alphabets). For me, it just works!

**Comment by Garbee** [comment]
>Many users will already have Roboto in their browser caches, so performance will probably not be a big issue.

We can't assume a cached item. The only thing we can test for consistently is a no-cache state. Performance doesn't rely on "Well, maybe if it is cached then it will be quick enough." It relies on absolute knowledge of if you have nothing, how fast can we get it to the client.

**Comment by innerpeace0** [comment]
In http://www.getmdl.io/assets/main.css, the very first declaration is:

`html>body{font-family:'Roboto','Helvetica','Arial',sans-serif!important;`

This is exactly what I want. It must be superceded later. 

Without combing through all the minimized code, what do I have to put later in my custom CSS to get Roboto everywhere.

**Comment by surma** [comment]
@innerpeace0 `assets/main.css` contains the styles specific to the website. This is not in distributed `material.css` for the previously mentioned reasons :) 

You can just copy that exact line to your own stylesheet and enjoy Roboto Everywhere™.

**Comment by innerpeace0** [comment]
Thanks, @surma.

**Comment by innerpeace0** [comment]
@surma, I don't think this issue is ready to be closed yet. I think @addyosmani still has some doc work planned for it.

**Comment by surma** [comment]
Thank you @innerpeace0! Got caught up in clean-up work :smile:

**Comment by sgomes** [comment]
Setting this as part of the investigation that needs to be done in #413.
