### ISSUE TITLE
Icons on Components pages are inconsistently blurry / pixelated

### ISSUE THREAD

**Issue by santokii** [google/material-design-lite#648]
Mainly on the Buttons and Tooltips pages, but the icons are inconsistently blurry. Can we figure out why this is?

- This is blurry on the right but not the left:
![screen shot 2015-07-03 at 12 03 00 pm](https://cloud.githubusercontent.com/assets/11649557/8498149/9258a50a-217b-11e5-83b1-9f97e10b382f.png)

- this is blurry on the left but not the right one:

![screen shot 2015-07-03 at 12 04 14 pm](https://cloud.githubusercontent.com/assets/11649557/8498163/a5b96e22-217b-11e5-99fc-3aea998f0cfd.png)

- this is blurry on the right

![screen shot 2015-07-03 at 12 03 18 pm](https://cloud.githubusercontent.com/assets/11649557/8498169/b384c6aa-217b-11e5-89ba-e1e53cbc8606.png)

**Comment by sgomes** [comment]
I'm marking this down as a Chrome icon font rendering bug, as I can't reproduce it in any other browser, and it seems inconsistent across OSes (doesn't seem to happen in Linux, for example).
