### ISSUE TITLE
Responsive Breakpoints

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#66]
Current advice from the Material team:

> 1. the keylines should still be used. desktop keylines are 24 and 80 from the edge of the screen and/or container.
> 2. gutters and margins between content or containers can be 4, 8, 16, 24, 40
> 3. We're still defining a responsive page layout system, but... it's complicated, and we're still refining breakpoints, testing different grid strategies across a variety of layouts. There will be a responsive layout section that will eventually get added to spec once we feel that the rules we're defining work well. 

As 3. is important for us and the ETAs are not yet defined, one option is to research what breakpoints other Google domains have opted for and review if they make sense as a stop-gap for our own recommendations.
- https://store.google.com/
- https://events.google.com/io2015/
- https://www.google.com/get/cardboard/

Also completely open to suggestions for alternative approaches to deciding our breakpoint strategy.

**Comment by Download** [comment]
A link to relevant docs on breakpoints would be great here as this is among the top search results when searching for this topic on Google:
https://www.google.com/search?q=material+design+lite+customize+breakpoints

This is a common issue (pardon the pun) with GitHub. It's SEO powers are so great they tend to overshadow the actual docs. Placing some clever links helps not only the people that find the issues, but should also end up increasing the docs rankings
