### ISSUE TITLE
Update Textfields on the Components Page

### ISSUE THREAD

**Issue by santokii** [google/material-design-lite#665]
Change mdl-textfield__label  font-weight to: 400;
Lets make each text field 260px wide
Numeric with floating label seems like it's missing the floating label:
![screen shot 2015-07-03 at 2 24 47 pm](https://cloud.githubusercontent.com/assets/11649557/8499909/52fdfe50-218f-11e5-9138-6409fb390441.png)

Seems like the multiple expanding element is missing. Can we add this one instead of the search icon, and move the search example onto another line like in the mock:
https://folio.googleplex.com/mdlmicrosite#%2F02%20Components%20-%2011Textfields.png

![screen shot 2015-07-03 at 2 26 51 pm](https://cloud.githubusercontent.com/assets/11649557/8499955/baea6e4a-218f-11e5-956b-47fc9df7ac47.png)

Spacing between the footer and the content should be 120px

**Comment by kingstenbanh** [comment]
Hi @santokii, could you please share the mock in public?

**Comment by sgomes** [comment]
Superseded by #4479.
