### ISSUE TITLE
Design polish for mobile pages (About, Templates & Customize)

### ISSUE THREAD

**Issue by santokii** [google/material-design-lite#676]
Lets remove the mouse over states on the About page (should just be the resting state images) get's cut off all funny

![screen shot 2015-07-03 at 3 39 03 pm](https://cloud.githubusercontent.com/assets/11649557/8501028/aca49cca-2199-11e5-8116-f14ee7516362.png)

On Templates page, can we make sure the body copy is left aligned with the Title and image:

![img_9768](https://cloud.githubusercontent.com/assets/11649557/8501059/e48e7dc2-2199-11e5-92aa-343605ef1492.PNG)

And on the Customize page, for some reason the footer icons are wonky

![img_9776](https://cloud.githubusercontent.com/assets/11649557/8501096/37cee1ca-219a-11e5-85b0-790335cdfeba.PNG)

**Comment by sgomes** [comment]
@surma @addyosmani I believe this is fixed now, right?

**Comment by surma** [comment]
Yeah, the only thing still to be done would be removing the hover states, which, as I said, I really like and nobody seems to complain :)
