### ISSUE TITLE
Checkmark in checkboxes behave inconsistently

### ISSUE THREAD

**Issue by surma** [google/material-design-lite#693]
Sometimes the checkmark is transparent (`mask`), sometimes it is white. This makes white checkboxes impossible.

Especially enjoyable: Safari and Safari Mobile behave differently :joy: 

Disregard the ugly colorization, that’s just for the visualization.

Chrome:
<img width="202" alt="screenshot 2015-07-04 18 39 31" src="https://cloud.githubusercontent.com/assets/234957/8508881/244accbc-227c-11e5-9b0f-a4d4c269c3da.png">
FF:
<img width="199" alt="screenshot 2015-07-04 18 39 35" src="https://cloud.githubusercontent.com/assets/234957/8508880/2449bf52-227c-11e5-957e-6691de79a73b.png">
Safari:
<img width="208" alt="screenshot 2015-07-04 18 39 44" src="https://cloud.githubusercontent.com/assets/234957/8508883/244c0820-227c-11e5-969a-e457dcebda37.png">
IE10:
<img width="176" alt="screenshot 2015-07-04 18 39 59" src="https://cloud.githubusercontent.com/assets/234957/8508882/244b0588-227c-11e5-942f-2026d0d1e03d.png">
IE11:
<img width="271" alt="screenshot 2015-07-04 18 41 09" src="https://cloud.githubusercontent.com/assets/234957/8508886/4088035e-227c-11e5-997a-41e1dcfdb41a.png">
Safari Mobile:
<img width="180" alt="screenshot 2015-07-04 18 40 08" src="https://cloud.githubusercontent.com/assets/234957/8508879/244961d8-227c-11e5-9c77-f372e10440e4.png">

**Comment by sgomes** [comment]
They are meant to be transparent, with the white as a fallback. Is there a better, cross-browser solution to this?

**Comment by surma** [comment]
I spent hours trying out different combinations. Couldn’t get it work consistently back then. I don’t think anything’s changed.

**Comment by Garbee** [comment]
Wouldn't `background-color: white;` applied to `.mdl-checkbox:checked` fix the issue? That should provide a set background color for the transparency to hit when present.

**Comment by ConAntonakos** [comment]
Since this issue was open, I wasn't sure to create another one, but I've also experienced inconsistent behavior regarding the checkbox ripple. Sometimes, when I click on the checkbox, it would not always trigger the ripple.

I'm on the latest Chrome on the latest Mac OS X.

**Comment by sgomes** [comment]
Not feasible to achieve consistency in v1. Checkboxes will be rewritten for v2 through #4471.
