### ISSUE TITLE
Sass upgrade blocked by mixed units

### ISSUE THREAD

**Issue by passy** [google/material-design-lite#702]
I tried to upgrade to libsass 3.2.5, but it's unhappy with the way we use units in one place:

```
Error: src/_variables.scss
  308:20  Incompatible units: 'ms' and 'deg'
```

Mentioned piece of code:

```sass
// Amount of circle the arc takes up.
$spinner-arc-size: 270deg;
// Time it takes to expand and contract arc.
$spinner-arc-time: 1333ms;
// How much the start location of the arc should rotate each time.
$spinner-arc-start-rot: 216deg;

$spinner-duration: 360deg * $spinner-arc-time / (
    $spinner-arc-start-rot + (360deg - $spinner-arc-size));
```

I think this is due to the changes introduced in https://github.com/sass/libsass/issues/1167.

Nothing critical at all, just to bear in mind for future update.s

**Comment by roughcoder** [comment]
Raised this issue with node-sass as well, might be a regression on their side.  sass/node-sass#1031
