### ISSUE TITLE
Seperation of logic in layout.js

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#726]
At the moment layout.js seems to manage the nav drawer, menu button, obfuscator (semi-transparent cover when drawer is open), wrapping content to control scrolling of the page, look and feel of header depending on it's class names.

Would anyone be opposed to separating out the nav drawer logic out into a separate class to make it easier for developers to re-use that logic and no require the other behaviors?

**Comment by Garbee** [comment]
Sounds like this would be a nice V2 enhancement. Depending on how things are broken up, this could end up as a BC breaking change.

**Comment by sgomes** [comment]
Adding this to v2, as part of the layout rework. We should strive to separate most components and make it easy to piece them together.

**Comment by sgomes** [comment]
Superseded by #1735.
