### ISSUE TITLE
Feature request to add Sketch 3 Material Color palette download in the Styles page

### ISSUE THREAD

**Issue by santokii** [google/material-design-lite#741]
As far as I know, there's no way to share General Color Palettes in Sketch yet, but there is a way to access OS color palettes in Sketch via the Colors window:
![screen shot 2015-07-06 at 6 13 51 pm](https://cloud.githubusercontent.com/assets/11649557/8528414/d031499a-240a-11e5-8a05-23d6083cfd35.png)

So I've created a clr file with the full Material Color Palette that users can download and use here:
https://drive.google.com/open?id=0B4Aowjp0SFvmWGJ5SFZKbmE1NkU

Let's add this to the Styles Page, under "Color Palette" with the instructions:

"Download the OS color palette for Sketch 3  ->

To use, open the Colors Window by going to View > Show Colors then select the Color Palettes tab 
![screen shot 2015-07-06 at 6 09 32 pm](https://cloud.githubusercontent.com/assets/11649557/8528305/3680ca96-240a-11e5-9f2b-d2598d01f2c7.png) and click on the gear icon to the right of the drop down menu. Select "Open" then choose the downloaded file "Material Design Color Palette.clr" which should then load with a list of all the colors, hex numbers and values which require white text for accessibility contrast ratios.

**Comment by santokii** [comment]
Updated the link for the public file https://drive.google.com/open?id=0B5EBOxetWHK7OGFRZTM0S0FCa2c

**Comment by Garbee** [comment]
Should we link the Drive file or toss it in the repository for tracking as well?

I think Drive does some throttling, so if it gets hit hard at some point it could be unavailable for a while.

**Comment by surma** [comment]
I’d put ’em on the CDN.

**Comment by Garbee** [comment]
If we can direct push to CDN so it isn't tracked (to keep the history here as light as we can)... that'd be a winning plan to me.

**Comment by santokii** [comment]
sgtm!

**Comment by addyosmani** [comment]
I'd put them on the CDN too. I think design resources might be a little heavy for the main repo, but we can periodically update the CDN bucket any time @santokii has a new version she wants to push. Otherwise happy for us to link to this from the Styles page.

**Comment by addyosmani** [comment]
@surma would you feel comfortable getting this hosted? I can add the content above into a PR and link once that's done.

**Comment by surma** [comment]
Sure thing.

**Comment by santokii** [comment]
Better instructions here(to replace the copy suggestion above): https://medium.com/@san_toki/import-the-material-design-color-palette-into-sketch-3-e31caf2f6a12
