### ISSUE TITLE
Live preview is broken

### ISSUE THREAD

**Issue by greenify** [google/material-design-lite#742]
Hey,

just a quick heads up that for me the live preview links lead to 404s

e.g. http://google.github.io/material-design-lite/test/visual/

I would guess that github requires development to happen at `gh-pages` - alternatively one can also try to use `rawgit.com` (e.g. https://rawgit.com/google/material-design-lite/master/test/visual/index.html), but it seems that the `dist` folder isn't committed ;-)

Cheers!

**Comment by Garbee** [comment]
I'm going to go ahead and dump these links from the README. The templates are covered in the [primary site](http://www.getmdl.io/templates/index.html). Visual tests was also most likely a preview template that has since been removed entirely.

**Comment by Garbee** [comment]
Fixed with commit 8932abe98526fc32fae01fce8f0bb368c4932374. Thanks!
