### ISSUE TITLE
Windows - jscs line endings

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#743]
JSCS currently [validates unix line endings](https://github.com/google/material-design-lite/blob/master/.jscsrc#L4). The problem is, git on Windows you can checkout windows-style and commit unix-style automatically. So cloning the repo, installing deps, then running `gulp serve` or anything that runs through jscs (ok, anything that touches JS) will cause this to error out.

Anything we can do here to help make it "just work" or should people checkout unix-style line endings?

This is pretty major for getting developers on Windows using the project and contributing back.

**Comment by patrickgrey** [comment]
Thanks for noting this issue. I abandoned running this on Windows as I wasn't sure what caused the error was on a quick look test of MDL. In case anyone else is looking in with the same problem, I changed the line in the .jscsrc file above to:
`"validateLineBreaks": "CRLF",`
and gulp serve worked without the linting issue. I agree it would help uptake though if this "just worked".

**Comment by Garbee** [comment]
It should warn vs error and die imo. Error and die is for code style checks on PR's and generating deployment builds.

**Comment by sindresorhus** [comment]
The correct way is to force git to always checkout with `lf`: http://stackoverflow.com/a/2517442/64949

**Comment by sgomes** [comment]
Switched to ESLint.
