### ISSUE TITLE
Slow navigation on http://www.getmdl.io/components/index.html

### ISSUE THREAD

**Issue by sqrrrl** [google/material-design-lite#748]
Noticed when clicking through the different component example pages that there is sometimes a very long delay navigating between pages. Easiest way to reproduce is:

- Go to http://www.getmdl.io/components/index.html#badges-section
- Click on 'Buttons'
- Immediately click on 'Badges'

Chrome dev tools showed that clicking on 'buttons' completed in 188ms, whereas clicking on 'badges' took a whopping 1.38s and the delay was clearly noticeable.

Using Chrome 44.0.2403.61 beta (64-bit) on OSX

**Comment by Garbee** [comment]
It replicates when quickly jumping back to the `Badges` section. The rest don't seem to display the lag as noticeably as badges.

**Comment by sgomes** [comment]
Documentation will be rewritten for v2. Not feasible to fix this until then.
