### ISSUE TITLE
Strange list styling on http://www.getmdl.io/styles/index.html

### ISSUE THREAD

**Issue by sqrrrl** [google/material-design-lite#749]
Seeing some strange styling on http://www.getmdl.io/styles/index.html

![material_design_lite](https://cloud.githubusercontent.com/assets/346343/8530311/247bd794-23d5-11e5-8275-648e85b997a0.png)

**Comment by surma** [comment]
This is most likely an UTF-8 problem. Can you tell me which browser and OS (+ version of each) you are using?

**Comment by sqrrrl** [comment]
Chrome 44.0.2403.61 beta (64-bit)
OSX 10.10.3

**Comment by sqrrrl** [comment]
Hmm, just cleared cache and reloaded and it's looking OK now.

**Comment by surma** [comment]
Alright, good to hear! I’m closing the issue for now. Don’t hesitate to reopen it, if the issue comes up again :)
