### ISSUE TITLE
Create a WordPress theme based off of MDL?

### ISSUE THREAD

**Issue by scottjenson** [google/material-design-lite#753]
If we start with a lightweight/responsive theme and add MDL to it might not be too hard...

**Comment by Garbee** [comment]
Go ahead if you want. This tracker shouldn't be used to track such an effort. Platform-dependent implementations should be tracked within their own repositories.

**Comment by addyosmani** [comment]
I asked for this to be opened. We won't implement this but can coordinate folks that want to then point to their independent repos.

**Comment by Garbee** [comment]
Hm, maybe we should make a Google Form for implementers to submit their repo/site links then. Hook that up in the README so they know we are open to implementations and will link off to them.

**Comment by matthijsdewit** [comment]
Following, also interested in this.

**Comment by braginteractive** [comment]
I actually just finished creating a WordPress theme with MDL. Feel free to fork it over at https://github.com/braginteractive/MDLWP

Feedback and pull request welcome!

MDL is pretty awesome, have a lot of plans for the MDL WordPress theme.

**Comment by innerpeace0** [comment]
WP and MD are both great, and a great combo. Thanks for the nice implementation.

**Comment by braginteractive** [comment]
@innerpeace0 I agree, they are a nice combo. Let me know if you have any feedback or ideas for the theme.

**Comment by sgomes** [comment]
Sounds like this can be closed! :)
