### ISSUE TITLE
Make snippets individually trackable

### ISSUE THREAD

**Issue by surma** [google/material-design-lite#756]
See #754

**Comment by Garbee** [comment]
How are the pre's generated? We could find some way to add a data attribute to it to name each one individually (component name + '-' + example file name ?) then just pull that for the tracking.

**Comment by surma** [comment]
yeah, something like that. It’s not urgent, I just wanted to have a reminder somewhere.

**Comment by nicolasgarnier** [comment]
Unfortunately we don't have a label for each snippet "group" but we have for each snippet. For instance there may be 2 or 3 snippets copied by the CodePen button. We could just take the first snippet's label.

**Comment by sgomes** [comment]
Documentation will be rewritten for v2. not feasible to fix this until then.
