### ISSUE TITLE
Should the components header stick?

### ISSUE THREAD

**Issue by samccone** [google/material-design-lite#757]
Tall component pages tend to feel barren on pages like http://www.getmdl.io/components/index.html#textfields-section
When you are 1000+ pixels scrolled down and there is no quick way to jump to another page or section. 

Making the header or the left sidebar fixed might be a nice solution.

Tthoughts?

<img width="1469" alt="screen shot 2015-07-06 at 3 49 47 pm" src="https://cloud.githubusercontent.com/assets/883126/8531636/d8032cba-23f6-11e5-84ac-39cb64a808c2.png">

**Comment by Garbee** [comment]
+1 I'd digg that.

**Comment by Garbee** [comment]
@santokii any design purpose that would prevent us from fixing the sidebar and header navigation? Assuming others agree that it would be useful to fix the layout.

**Comment by santokii** [comment]
I believe a sticky nav (and left nav) is something we are planning on building in soon @addyosmani for timing.

**Comment by Bound3R** [comment]
yeah, is very cumbersome be watching documentation and not have the menu to change the subject for eg in the layout section :confused:

**Comment by sgomes** [comment]
Documentation will be rewritten for v2. not feasible to fix this until then.
