### ISSUE TITLE
🚰 Menu component listener leak

### ISSUE THREAD

**Issue by samccone** [google/material-design-lite#761]
**Hypothesis**: The menu when opened and closed does not clean up all of the events that it registers for, thus causing a leak :droplet: .

<img width="616" alt="screen shot 2015-07-06 at 4 04 06 pm" src="https://cloud.githubusercontent.com/assets/883126/8532038/7c081a9e-23f9-11e5-900b-326be5486807.png">

#### Testing methodology: 

*visit http://www.getmdl.io/components/index.html#menus-section in chrome canary in an incognito window with no profile
* open and close the left menu once
* take a heap snapshot
* start a profiler (clearing the GC after starting)
* open and close the menu 5 times
* force a GC 
* stop the timeline profile
* take a heap snapshot.

#### Results: 

<img width="1057" alt="screen shot 2015-07-06 at 4 07 45 pm" src="https://cloud.githubusercontent.com/assets/883126/8532016/5438ac68-23f9-11e5-9ea9-5c37a8d0b30a.png">

The profiler shows us a step ladder of listener registrations (that never drops), over 5 iterations we can see that there are **15** new event registrations.

##### Looking at the heap comparison

<img width="1057" alt="screen shot 2015-07-06 at 4 03 55 pm" src="https://cloud.githubusercontent.com/assets/883126/8532059/a59f93d2-23f9-11e5-8325-f9061cc63223.png">

note how that **15** shows up for us :) it looks like here :point_up: is the manifestation of our leak :clap: 

-------

I have not investigated the menu code in depth for how the menu works, so this might be super obvious to you guys for how to fix (or even that this might not be an issue), if this is not enough info to go off of let me know and I can continue the dive.

:palm_tree:

**Comment by Garbee** [comment]
I think I found the leak. We are [adding a listener](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L441) to animate when hidden, but they are never removed. Therefore when it is opened repeatedly, the [same events](https://github.com/google/material-design-lite/blob/master/src/menu/menu.js#L346-347) keep getting added again and again.

**Comment by surma** [comment]
That’s one pretty issue you got there! Thank you very much for the in-depth analysis. Is either of you working on a PR already?

**Comment by Garbee** [comment]
I'm not working on a PR for this, much lower priority than my card goof that is very problematic for alignment. Go for fixing it if you want.

(Yea, he has been doing *loads* of good reviews like this for TodoMVC stuff.)

**Comment by addyosmani** [comment]
:star: Thanks again, @samccone!
