### ISSUE TITLE
Accessibility for menus

### ISSUE THREAD

**Issue by samccone** [google/material-design-lite#763]
Navigating to:
http://www.getmdl.io/components/index.html#menus-section

As a user using tabs to bring a menu into focus, when I hit enter to open the menu should I be able to hit tab to cycle through the menu items? Currently I have to use the arrow keys. I am not sure what is the industry best practice here (cc @marcysutton) But based on the limited experience I have it seems like supporting tabs would be a good idea.

Thoughts?

**Comment by samccone** [comment]
@Garbee sent me this as the pattern we should try and follow

http://codepen.io/grayghostvisuals/pen/ltjDa

^ which supports tabs


http://a11yproject.com/patterns/

**Comment by marcysutton** [comment]
The expected keyboard behavior depends on the semantics (which right now there are none, other than the triggering element being a `button`). That Codepen example is for a horizontal menu, which is a different pattern than a regular dropdown. I'd recommend against using complex ARIA patterns like that one and instead looking at the [Bootstrap dropdown](http://getbootstrap.com/components/#btn-dropdowns), a simple example that works! It uses `aria-haspopup` and binds both the arrow keys and TAB.

**Comment by samccone** [comment]
woot thanks for the expert advice @marcysutton :sparkling_heart: !

**Comment by tschiela** [comment]
As far as i know the correct behavior would be:
- menu could be opened with CLICK, ENTER and SPACE
- if opened with keyboard, first item is focused
- with ARROW_DOWN and ARROW_UP its possible to cycle through all items. On last item the first item will be selected and 	vice versa
- with TAB its possible to select all items. On last item the menu will be closed and the next element in taborder will be selected
- ESCAPE should close the meniu. focus will stay on menu button

The whole implementation (with tests) is not trivial but possible.

You can read more about it here
- [Keyboard Navigation within Widgets](http://www.w3.org/TR/wai-aria-practices/#kbd_general_within)
- [WAI ARIA best practise Combo Box](http://www.w3.org/TR/2009/WD-wai-aria-practices-20090224/#combobox)

**Comment by sgomes** [comment]
Superseded by #4474 for v2. Not feasible to fix in v1.
