### ISSUE TITLE
Fixed header drawer icon out of place

### ISSUE THREAD

**Issue by wescopeland** [google/material-design-lite#769]
Hi, I'm trying to follow the fixed header component example on the MDL site, but for some reason the drawer icon on the left is misaligned.

```
<body>
	
	<div class="mdl-layout mdl-js-layout mdl-layout--overlay-drawer-button">
		<header class="mdl-layout__header">
			<div class="mdl-layout-icon"></div>
			<div class="mdl-layout__header-row">
				<span class="mdl-layout-title">Simple layout</span>
				<div class="mdl-layout-spacer"></div>
				<nav class="mdl-navigation">
					<a class="mdl-navigation__link" href="#">Nav link 1</a>
					<a class="mdl-navigation__link" href="#">Nav link 2</a>
					<a class="mdl-navigation__link" href="#">Nav link 3</a>
				</nav>
			</div>
		</header>
		<div class="mdl-layout__drawer">
			<span class="mdl-layout-title">Simple Layout</span>
			<nav class="mdl-navigation">
				<a class="mdl-navigation__link" href="#">Nav link 2</a>
				<a class="mdl-navigation__link" href="#">Nav link 2</a>
				<a class="mdl-navigation__link" href="#">Nav link 3</a>
			</nav>
		</div>
	</div>

	<main class="mdl-layout__content">
	</main>

	<script src="material-design-lite/material.min.js"></script>
	<script src="angular/angular.min.js"></script>
	<script src="app/app.module.js"></script>

</body>
```
![screen shot 2015-07-06 at 4 42 34 pm](https://cloud.githubusercontent.com/assets/3984985/8533955/06f2ace2-23fe-11e5-9a77-9e7af11d7767.png)

I'm sure this is something incredibly simple that I'm overlooking. Any tips?

**Comment by wescopeland** [comment]
Figured it out. I forgot to set the doctype.

**Comment by surma** [comment]
Ha, I was just about to write that I can’t reproduce the issue on codepen. Glad you figured it out.

Anyways, make sure to put your `.mdl-layout__content` inside `.mdl-layout` :)

**Comment by wescopeland** [comment]
Thanks for trying at least :)

I've only begun to comb over the docs but I'm already really liking what I'm seeing. In the future I will remember to include a codepen URL :)

**Comment by Garbee** [comment]
Also for future reference, we would prefer support questions on StackOverflow with the `material-design-lite` tag. That would allow for more visibility and easier searching/maintenance of issues.

**Comment by bootuz** [comment]
Guys, do you how to change drawer icon's color? My background color is white and I just don't see it on screen.

**Comment by djtm** [comment]
Just for reference, this works: 
```html
<!DOCTYPE html><html class=''>
```
