### ISSUE TITLE
missing items from typography page

### ISSUE THREAD

**Issue by innerpeace0** [google/material-design-lite#772]
Styles and sizes of fonts for paragraph, button, menu, cards, popups, selects, and hints for inputs aren't listed on typography page, even though they may be included in the css. Only h1-h6 are currently shown.

**Comment by Garbee** [comment]
Can you point to where you are reading please?

I am not seeing any typography docs on the site itself. The docs that do exist are the [readme](https://github.com/google/material-design-lite/blob/master/src/typography/README.md) to the component, however I am not seeing where we explain what we do to elements directly at all within that content.

**Comment by innerpeace0** [comment]
http://www.getmdl.io/styles/index.html

**Comment by addyosmani** [comment]
Also see https://github.com/google/material-design-lite/issues/772

**Comment by surma** [comment]
Wouldn’t this end up with us duplicating the MD spec? Maybe a prominent link will do us better service

**Comment by Garbee** [comment]
Duplicate and be messy. I don't think we should be explaining every little thing done. It is overly verbose and very few people need to know that kind of detail. They are happy that it is just handled for them.

**Comment by innerpeace0** [comment]
What a paragraph will look like is not "every little thing" for a text heavy web page.

**Comment by surma** [comment]
@innerpeace0 I was actually leaning towards the opposite: Removing the typography altogether and rather linking to the MD spec explicitly. I’d value some input from @addyosmani @sgomes and @santokii here.

**Comment by innerpeace0** [comment]
As I understand it, the MD spec has more typography options than MDL. It would be nice to see what typography MDL has chosen to use from the MD set. I like the choices for h1-h6. It would be nice to see all the others. I expect others would like to see this, too.

**Comment by Garbee** [comment]
Ideally, we'd adhere to all the same MD typography setup stated in the specification, aside from not using Roboto by default for performance.

**Comment by surma** [comment]
This has been fixed in #1124
