### ISSUE TITLE
Quickstart in GitHub Readme.md is confusing

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#773]
The quickstart in the readme.md is a bit confusing because it seems like the first link will allow downloading the compiled source (the release) like on the minisite. However in this case it's a quickstart meant for developers who want to work on MDL (dev-dev) not for developers who want to use MDL on their site (dev-users):

![image](https://cloud.githubusercontent.com/assets/3766663/8535343/341155e2-2445-11e5-8c48-b3219e06d326.png)

I propose:
 - Add a section on top that makes it clear that developers who want to use the library need to go to the minisite quickstart.
 - Change this section to make it clear that we'll list instructions for developers who want to work on improving MDL:
   - Remove the "Download the latest Release" link.
   - Remove Bower and npm since these are for dev-users not dev-dev

**Comment by Garbee** [comment]
Makes plenty of sense to me. +1 to updating this to be a quick-start for developers working on MDL over just trying to use it.

**Comment by nicolasgarnier** [comment]
I'll get started on this.
