### ISSUE TITLE
Use progress element for progress bar

### ISSUE THREAD

**Issue by srsgores** [google/material-design-lite#776]
I suggest using the HTML5 ``progress`` element to take advantage of the ``indeterminate`` state [on the loaders component](http://www.getmdl.io/components/index.html#loading-section).

```
<progress class="mdl-progress" title="Please wait... loading all cover albums">
    <span class="mdl-progress-fallback">Loading album covers</span>
</progress>
```

It makes no sense to have the ``indeterminate`` modifier, as you can simply check that no ``value`` is present in CSS:

```
.mdl-progress:not([value]) {
    /* Custom styles here */
}
```

And likewise:

```
.mdl-progress[value] {
    /* Normal progress styles */
}
```

For browser support, I suggest placing the 3 divs which are normally appended via JS as the fallback:

```
<div class="progressbar bar bar1" style="width: 0%;"></div>
<div class="bufferbar bar bar2" style="width: 100%;"></div>
<div class="auxbar bar bar3" style="width: 0%;"></div>
```

This way, we can get the best of both worlds.

I can provide a PR on request, if needed.  Please advise.

**Comment by surma** [comment]
I dig the idea. Just looked up the support for `<progress>` in IE10 and seems like we would be fine. If you can whip up a PR, that’d be great.

**Comment by srsgores** [comment]
@surma, I can try to have it done in a couple weeks.  I'm very busy now, but I'll try to get things in place.

**Comment by surma** [comment]
As of now, this has to be for v2 release anyways as it is a breaking-change. Just FYI

**Comment by srsgores** [comment]
@surma, why would this be a breaking change?

**Comment by surma** [comment]
Because it would require existing sites to change their markup. We could support both old and new markups but that doesn’t feel like it’s worth the hassle.

**Comment by sgomes** [comment]
This component will be rewritten for v2. not feasible to fix this until then.
