### ISSUE TITLE
getmdl.io docs error

### ISSUE THREAD

**Issue by randyburhan** [google/material-design-lite#777]
In http://www.getmdl.io/styles/index.html

The part where you'd like people to embed Roboto into their page. Doesn't look right (below).
Sorry, not related to actual code, just want to help make the docs look good.

![screenshot-www getmdl io 2015-07-07 11-58-56](https://cloud.githubusercontent.com/assets/12962202/8537247/9ab8a278-249f-11e5-94dc-1fc0d4fa93e5.png)

**Comment by innerpeace0** [comment]
Suggest merging this issue with [#772] (https://github.com/google/material-design-lite/issues/772).

**Comment by addyosmani** [comment]
Thanks for the suggestion. Let's merge with #772.
