### ISSUE TITLE
upgradeElement and SPAs

### ISSUE THREAD

**Issue by peebles** [google/material-design-lite#778]
Have you seen https://github.com/uzairfarooq/arrive?  Bootstrap-material supports it, which makes using it on SPAs real nice.  When new pages get rendered into the DOM, absolutely nothing needs to be done in javascript.  Seems to me your upgradeElement() could be implemented using only the first element argument, and it could discover what to do based on the css classes already present on the element.  Then something like arrive() could be used to automatically materialize any component added to the DOM by a SPA without any additional code (esp if every element has a common class like "mdl").

**Comment by Hendrixer** [comment]
I like arrive, but seeing how it uses `Mutation Observers` underneath, this is could be a heavy dependency

**Comment by Garbee** [comment]
The problem with arrive is browser support. We need IE10 support for JS and arrive only supports IE11+.

If you wish to integrate this kind of setup into your own project, looking arrive over it seems entirely doable. Nothing appears like it can be done here though because of browser support.

**Comment by addyosmani** [comment]
Mutation Observers are currently not available in IE10 (http://caniuse.com/#search=mutation), one of our target browsers for support. I would be really hesitant to add in https://github.com/Polymer/MutationObservers (MO polyfill) just to enable us to use arrive there. We could layer support for the MO approach, but imo this adds significant enough complexity to the setup that while it's quite nice to have is a little out of scope for the project.

**Comment by saidimu** [comment]
@addyosmani So what is the recommended approach re SPAs? Repeatedly calling `upgradeElement()` seems like a hack.

**Comment by Garbee** [comment]
@saidimu that or `upgradeDom` to go over everything again.

Seem like hacks, but directly making calls is the only thing the current web supports en-mass. Without observers or a more complicated flow where we become a SPA framework ourselves, this is the only option.

SPA systems should be able to handle being told to call upgradeElement on things injected. Soon with other new additions to the API as well you can call upgradeElements against an injected node to have to loop over all children and upgrade.

We are working to make the API provided more flexible, but we are doing it without polyfills and shims for functionality to keep what is provided as lite as possible.

**Comment by saidimu** [comment]
@Garbee Sounds good. Thanks!
