### ISSUE TITLE
Dialogs / Modals in Material Design

### ISSUE THREAD

**Issue by rkusuma** [google/material-design-lite#781]
Hi.. 
is there dialogs (simple dialog, confirmation dialog, datepicker dialog, etc) in MDL ?

**Comment by Garbee** [comment]
Material Design spec: [Dialogs](http://www.google.com/design/spec/components/dialogs.html)

This has been discussed and can be added within the 1.x lifecycle. Simply wasn't done for launch because of time and people-power.

**Comment by rkusuma** [comment]
thanks @Garbee !

**Comment by rweas** [comment]
Do toasts fall under this category?

**Comment by Garbee** [comment]
No, they aren't. A PR ( Issue #325 ) is already open and working on that.

**Comment by triplekdev** [comment]
+1000 Modal :)

**Comment by grri** [comment]
+1 Modals, one essential thing in my opinion

**Comment by Garbee** [comment]
Once something is tagged as `future` it is an accepted request and just needs to be assigned and/or implemented. We don't need anymore +1 or other supportive comments please. They end up causing more noise and distraction than anything else.

**Comment by gsalvati** [comment]
Please, add modals!

**Comment by waltercolindres** [comment]
+1

**Comment by superpikar** [comment]
+1 :)

**Comment by JohnnyJai** [comment]
+1

**Comment by LudoBermejo** [comment]
+1

**Comment by Swatinem** [comment]
Guys please, this +1 is super annoying, please just subscribe: https://github.com/google/material-design-lite/issues/782#issuecomment-119653230

otherwise I would have to unsubscribe and miss anything important going on here…

**Comment by addyosmani** [comment]
Hey folks. To echo @Swatinem's comment, could we please ask that you use the subscribe option instead of +1's? I really want us to avoid having to lock issues to committers and subscribing gives you the best flow for staying on top of updates.

**Comment by Garbee** [comment]
I was kinda hoping to not need to get any help until after it was ready. However, IE's box modal is... well IE's box modal. How does this relate to the W3C's? I have no clue (Mostly sarcastic joke here.) (Edge is fixed though, thanks MS team!) Anyways, mobile for dialogs has a [hard width of 280px](https://www.google.com/design/spec/components/dialogs.html#dialogs-simple-dialogs). However, we have no guidance on tablet/desktop for what the size should be.

**It would be amazing if we could get direct widths for dialog popups against tablet and desktop sizes.** This way we can program hard widths at each size and allow developers to override if they have a UX that *really* needs more space.

Until I have some set widths (or we are told to do our best to infer our own) then the dialog is stuck. It will take a while to get it aligned proper in IE when every other browser works fine how it is now. Hard widths fix the issue in IE, so it is the best move.

cc @santokii for MD guidance on that note.

**Comment by richardanaya** [comment]
Modals are pretty important. As a developer comparing material libraries for the first time, I chose to use Materialize over MDL because their modals.  Once MDL gets modals, i'll probably switch over.

**Comment by Daniel-Gherard** [comment]
Well... since currently there is no MDL dialog/modal, I'm using Bootstrap's Modal to present images. But, I'm also using elements from MDL, such as the Navigation Drawer. But, as you guys know when open the Navigation Drawer makes all the background a little bit black. Just like Bootstrap's Modal. My problem is, when I open the Bootstrap's Modal everything becames blacks, including the Modal. I'm no expert in Javascript. But, I think the Modal is calling It's parent function. Any idea on how to fix this?

**Comment by Garbee** [comment]
@Daniel-Gherard Please use StackOverflow for support. This issue tracker is related only to core MDL problems.

**Comment by Daniel-Gherard** [comment]
Ok. Sorry for that. You're right. I solved it.
I'll leave my solution here in case someone else has this problem:
I was able to make it work by just setting the backdrop on the modal to false. Simple solution. 

I'll leave like this until a modal/dialog is add to the MDL. Thanks.

**Comment by dacheezypuffs** [comment]
+1

**Comment by joni2back** [comment]
+1 for dialogs

**Comment by hebbet** [comment]
@joni2back see: http://www.getmdl.io/faq/index.html#issue-updates

please stop posting +1 here.

**Comment by mateeyow** [comment]
I +1 your comment @joni2back HAHAHAHA!

**Comment by joni2back** [comment]
Ok @hebbet but I think is very important the priority for dialogs/modals... We are waiting for this component to start to moving a bootstrap layout to material lite..!!

**Comment by foo-baar** [comment]
@surma : Just wanted to check if its ready yet ?

**Comment by rogue780** [comment]
Someone could force the issue on the sizing by submitting a PR

**Comment by Garbee** [comment]
A PR won't force the issue anymore than I already am. All that will happen is an `md-guidance` tag and `dont-merge-yet` tag will get added until the team takes a look, but they don't prioritize based on MDL PRs.

The Material Design team is a limited number of people trying to help all kinds of different projects at Google figure things out. These kind of things don't get worked out quickly.

There is a lot of attention to detail that goes into the spec. What I am asking is for the spec to be done with an easy-out simply for IE support. However, that may not align with what is best for the spec in the long run. If the Material Design team decides something else is better, then we need to look into that. Either way, the decision still won't happen very quickly. 

I may move forward without them and simply do my best. Right now though I have plenty of other tasks that need doing for 1.1 that are specified and we have plenty of time. So I am going to focus on handling those while the MD team goes over the Dialog issue.

**Comment by rogue780** [comment]
See, I started a project yesterday. I thought, "Hey, let's try MDL. Maybe they have modals now." So I came to check it out. Still no modals. So, materializecss it is.

**Comment by addyosmani** [comment]
> It would be amazing if we could get direct widths for dialog popups against tablet and desktop sizes. This way we can program hard widths at each size and allow developers to override if they have a UX that really needs more space.

From my last conversation with the MD team, desktop and large-screen sizes for dialogs have not yet been started but the broader dialog rules still apply, like button positions, naming, colour use per the dialog spec. Desktop dialogs/modals have more layout complexity and flexibility and a greater variety of content than they might contain on say, mobile, so the rules in the spec need to reflect those differences. 

The current approach other teams at Google (and to an extent libraries outside) is implementing a version of modal dialogs that looks 'good enough' and waiting for the spec to evolve. That means opting for a default width we personally think makes sense and adjusting that later. It would avoid some of the layout hacks @garbee has been concerned with. My personal take is we could tackle this in 1.2 or 1.1 if someone had bandwidth, but it's likely going to be after 1.1.

**Comment by Garbee** [comment]
@addyosmani Sounds like from that all we need to do is ship with the mobile width as the default width period. If you need another width otherwise, just manually set it for now and we can adjust in a future major to align with the spec more fully.

We can't feasibly keep waiting for the MD team to spec it up. The decision needs to be made to implement as best we can at some point. The sooner (1.1) we get it out, the more use developers will get out of the library. We will then also get good feedback on the implementation that may also need addressing in the next major. With that, we can also upgrade the design later on once fully specified in another major since changing default widths like that is a BC concern.

**Comment by foo-baar** [comment]
@Garbee : That  would temporary solve the purpose, Any update about the menu DIV not getting cleared on hide ?

@rogue780: I know man how it feels, Imagine me working a client dashboard project, BTW don't try the "mdl-menu mdl-menu--bottom-left" yet, specially it overshadows any links undergrowth.

@addyosmani: Thanks for your consideration on these issues, would be helpful If we can at least close those issues which are show stoppers and barriers users to try this awesome thing.

**Comment by Garbee** [comment]
> Any update about the menu DIV not getting cleared on hide ?

Not sure what exactly this is referring to. But sounds un-related to modals in which case it is off-topic here. Please look for existing issues about the problem and try to follow-up on those or file a new issue if one doesn't already exist.

**Comment by surma** [comment]
@Garbee @foo-baar I think what you are looking for is #1406. The issue has been fixed since 1.0.3.

**Comment by foo-baar** [comment]
Also since we are on the topic, Please pardon me for posting it here but couldn't find relevant topic, Our CSS file have beautiful color choices, would be good if we project it on site via some sort of Pallet I guess.

**Comment by Garbee** [comment]
If there isn't an existing issue, just make a new one. Having specific issues to things is more useful to everyone than stuffing everything under one issue that isn't related to the topic at hand.

**Comment by foo-baar** [comment]
@Garbee : Make sense, removed my comment.

**Comment by oniseun** [comment]
Please guys, I need your help on this one. 
Any idea on how to get the codes for the dialog box in this link http://styleguide.material-design-lite.pub/#/dialog
I will gladly appreciate

**Comment by foo-baar** [comment]
@oniseun : Dart material is not Material Design Lite, both are different libraries, pick one for your job, that solves your purpose.

**Comment by oniseun** [comment]
@footboard Used to think they were the same. Thanks for that

**Comment by Garbee** [comment]
PR #1762 is open for adding the initial Dialog support.

**Comment by carusogabriel** [comment]
https://www.google.com/design/spec/components/dialogs.html#dialogs-alerts
WE N-E-E-D IT <3

**Comment by duduindo** [comment]
Dialog simple "temporary" in SASS:

.modal {	
	background-color: #fff;
	bottom: 0;
	height: 0vh;
	overflow-y: auto;
	position: fixed;
	transition: height .25s;
	width: 100vw;
	z-index: 4;

	&.modal.is-visible {
		height: 100vh;
	}
}

**Comment by erwinprasetyo** [comment]
maybe you can use this http://www.jqueryscript.net/lightbox/jQuery-Modal-Dialog-Plugin-For-Material-Design-Lite.html

**Comment by surma** [comment]
[Dialogs](http://getmdl.io/components/index.html#dialog-section) have been implemented and released with MDL 1.1. Closing this :)
