### ISSUE TITLE
RTL languages support?

### ISSUE THREAD

**Issue by HagaiBarel** [google/material-design-lite#783]
It would be great to see RTL languages (Arabic, Hebrew etc.) support in MDL.
The official MD specs don't clarify on this either, but it will be a valuable feature for the web.

**Comment by abodacs** [comment]
+1

**Comment by arhmnsh** [comment]
+1

**Comment by innerpeace0** [comment]
+1

**Comment by mahmoudmy** [comment]
+1

**Comment by HagaiBarel** [comment]
Ok, so the naive approach of just adding `direction: rtl;` obviously didn't work (had to give it a try :blush: ).

I'll try to build a simple example page with all elements in it (maybe just clone the getmdl.io site), and map all the places where rtl fixes should be inserted.

**Comment by Garbee** [comment]
RTL support isn't something that can be boiled down to a few quick classes. We need to do research to make sure RTL fits into each component fluently and that we have a structure in place to continue supporting it with future updates.

**Comment by HagaiBarel** [comment]
@Garbee Fair enough. Let me know if there's anything I can help you with regarding this, I'm a native Hebrew speaker.

**Comment by Garbee** [comment]
We will be updating this issue with information once we have some. Right now I simply tagged so it is categorized (not lost hopefully!) and the team can discuss further how this should get handled.

**Comment by mkzaker** [comment]
+1

**Comment by mhf-ir** [comment]
:like:

**Comment by innerpeace0** [comment]
> just adding direction: rtl; obviously didn't work
 
> RTL support isn't something that can be boiled down to a few quick classes.

What about some kind of logic where if the direction is ltr or rtl, then the other applicable selectors and properties would have their values set accordingly. Then, localizers would only need to indicate whether their local language is lrt or rtl, and the rest would be handled programmically? It may need some alpha and beta testers in rtl languages to catch everything.

Another possibility might be a supplemental rtl stylesheet that would load last and override the applicable ltr settings. It probably wouldn't be very big.

**Comment by matthiasg** [comment]
For bootstrap there is a rtl CSS file which can be loaded last and worked well in practice... In combination with flow layouts out should be a little easier still..

-----Original Message-----

**Comment by mhf-ir** [comment]
RTL design framework must be as core of framework. using less or sass it's must be a variable. patch of framework it's just ugly way. i guess the best way. Persian, Arabic and other languages need RTL

**Comment by gauntface** [comment]
Does anyone have any opinions on tools like CSS Flip?

https://github.com/twitter/css-flip

Only played with it a little bit, but it seemed to work pretty well.

**Comment by AliMD** [comment]
I think this way is better #1518
We start to fix these problems [here](https://github.com/WebRTL/material-design-lite-rtl/issues)

**Comment by AliMD** [comment]
I'm working on rtl layouts more than 10 years on many project
And we have many research about it
I don`t use css flipping anymore because
1. As a rtl native user We hate flip all layout for example in android or gmail or etc. we usually prefer to use english version because of that.
2. In many case we want combined layout in our website and we prefer to use `dir` attribute for exception layout in some section
3. As a developer we prefer to change and develop in single project for all langs not separate css and layout file for rtl users

For example as a user I want to support rtl writing in google keep not flip all the website
Thank you in advance

**Comment by surma** [comment]
Thanks for your input, @AliMD. As I said, we are still working on this and no final decisions have been made :)

**Comment by AliMD** [comment]
Thank you, can I help you on it?

**Comment by AliMD** [comment]
as @addyosmani said in https://github.com/google/web-starter-kit/issues/181
> After spending a few weeks investigating RTL and i18n/l10n for our other project Material Design Lite (getmdl.io) ...

@addyosmani @surma @gauntface 
Whats news ?
Could you please make a separate branch for RTL support and share your working result then we can work on it as a separate milestone and you can merge it to master when its ready to use.
As I said before I'm RTL native and I'll do my best.
Thank you in advance.

**Comment by traviskaufman** [comment]
Closing as we are addressing this incrementally within all of our v2 components.
