### ISSUE TITLE
Link to JSCS Configuration in contributing.md is broken

### ISSUE THREAD

**Issue by achalv** [google/material-design-lite#784]
Hey all, 
I was trying to see how this project uses JSCS, and saw that the link to the jscs config under the [Coding Rules section in contributing.md](https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md#-coding-rules) gives me a 404. I think(?) the link should point to [the .jscsrc file](https://github.com/google/material-design-lite/blob/master/.jscsrc), but it currently points to https://github.com/google/material-design-lite/blob/master/jscs-config, which doesn't exist.

I'd be happy to submit a PR that fixes this. Just wanted to make sure that I have the correct links.

Thanks!

**Comment by yuyokk** [comment]
I think this issue is fixed in the following PRs https://github.com/google/material-design-lite/pull/774 https://github.com/google/material-design-lite/pull/837 https://github.com/google/material-design-lite/pull/840

**Comment by surma** [comment]
Yes, as @yuyokk mentioned, this has been fixed. Thanks, @achalv :)
