### ISSUE TITLE
Modal component?

### ISSUE THREAD

**Issue by startswithaj** [google/material-design-lite#786]
Would be great to have a modal component.

**Comment by pixelpoesie** [comment]
+1

**Comment by arhmnsh** [comment]
+1

**Comment by Garbee** [comment]
Merge into #781. Modals and Dialogs are the same concept.

**Comment by ashishsajwan** [comment]
:+1:  + 1

**Comment by foo-baar** [comment]
@Garbee @addyosmani : Hi, Just wanted to check any update on this ? Or anything else I can use in the mean time ?

Thanks for help.

**Comment by surma** [comment]
I’ll swoop in here.
@foo-baar We literally opened the merge window for 1.1 an hour ago, so this is the very first moment we can start thinking about new features like dialogs and modals. We have definitely heard the big demand for these components and they are at the very top of the list. We just need to coordinate with the MD team and get an actual implementation ready :)

**Comment by foo-baar** [comment]
@surma : Thanks for the update, any timeline here Until we start seeing this in production/on the site ?

**Comment by Garbee** [comment]
No timeline. However as stated this is a *duplicate* issue. Please keep an eye on the primary issue for updates.

**Comment by foo-baar** [comment]
@Garbee : Thanks, hope its in place soon, otherwise I'll have to move back bootstrap as this really lacks many important features needed for a business line apps.

**Comment by oniseun** [comment]
Thought one was used in the showcase website http://styleguide.material-design-lite.pub/#/dialog

**Comment by surma** [comment]
@oniseun The Dart version of MDL is not by us but by the prolific @MikeMitterer. Has has done some elements on his own that we don’t have yet.

**Comment by oniseun** [comment]
@surma   I never knew that. Although I have used much of the css components and it worked but was surprised that modal window code wasn't working. Thanks anyway
