### ISSUE TITLE
Dashboard template alignment icons

### ISSUE THREAD

**Issue by IschaGast** [google/material-design-lite#787]
Page: http://www.getmdl.io/templates/dashboard/index.html
![image](https://cloud.githubusercontent.com/assets/39517/8541367/dc388144-248d-11e5-81da-d081267188c5.png)

The alignment of the icons isn't correct

**Comment by addyosmani** [comment]
Could you share what browser you were testing in when you ran into the misalignment issue?

**Comment by IschaGast** [comment]
![image](https://cloud.githubusercontent.com/assets/39517/8542899/571b6df8-2499-11e5-97b5-67b9cf255e66.png)

I was just clicking through all templates and when hovering over the icons I saw that misalignment issue.

**Comment by addyosmani** [comment]
Thanks for confirming your OS and browser version! We'll get this assigned.

**Comment by IschaGast** [comment]
I testen this solution and when you hover over an icon it gets a gray rounded background. But when you compare those two you see that there is a difference of two pixels.

Maybe it's because of my retine screen but for me padding-top: 25px; works better.
