### ISSUE TITLE
Form display issue on Firefox

### ISSUE THREAD

**Issue by bcbcarl** [google/material-design-lite#788]
The submit button is misplaced on **Mozilla Firefox** and **Firefox Developer Edition**.

![firefox_mdl](https://cloud.githubusercontent.com/assets/135734/8541448/dfec1958-24c0-11e5-90e3-5daefd0a0762.png)

```html
<form action="#">
    <h1 class="mdl-typography--display-4">Roboto</h1>
    <div class="mdl-textfield mdl-js-textfield">
        <input class="mdl-textfield__input" type="text" id="sample1" />
        <label class="mdl-textfield__label" for="sample1">Text...</label>
    </div>
    <input class="mdl-button mdl-js-button mdl-button--raised mdl-button--accent mdl-js-ripple-effect" type="submit" name="name" value="Submit">
</form>
```

**Comment by bcbcarl** [comment]
If I apply inline-block on the first input element, it works as expected.

```html
<input class="mdl-textfield__input" type="text" id="sample1" style="display: inline-block" />
```

**Comment by addyosmani** [comment]
Thanks for the feedback. Could you share what version of Firefox you ran into this issue with? We'll get it verified and fixed up if we can reproduce.

**Comment by sgomes** [comment]
Both the bug and the fix seem correct, thanks @bcbcarl! Running a round of cross-browser testing before PR-ing in the fix.

**Comment by bcbcarl** [comment]
I can reproduce this bug on **Mozilla Firefox** and **Firefox Developer Edition**.

**Comment by addyosmani** [comment]
lgtm

**Comment by bcbcarl** [comment]
@sgomes: :+1:

**Comment by escudero** [comment]
ops, there was another mistake. When the HTML is all on one line.
Follow the example below:
http://codepen.io/anon/pen/oXaGor?editors=110
=/

**Comment by Garbee** [comment]
@escudero That is a completely separate issue. Please file a new one instead of trying to add onto old and unrelated issues.

**Comment by mazyvan** [comment]
hey @sgomes, in this self-generated version https://code.getmdl.io/1.3.0/material.blue-pink.min.css the `.mdl-textfield__input` selector has block as the value for the display property.

I also recommend to add this `box-shadow: none;` to the selector to prevent this other issue
![image](https://user-images.githubusercontent.com/10915753/33150699-43be1932-cf9a-11e7-9650-2e8c4d09262f.png)
