### ISSUE TITLE
remove gulp-shell

### ISSUE THREAD

**Issue by contra** [google/material-design-lite#790]
https://github.com/google/material-design-lite/blob/master/gulpfile.js#L601 should be replaced with node's built-in child_process module. `gulp.src('').pipe(plugin())` is a really nasty pattern that emerged when people started making plugins for things that shouldn't be plugins. `gulp.src('')` will start to error in the final 4.0 release to discourage people from doing this

**Comment by contra** [comment]
As a sidenote, gulp-shell is useful but only when you need to use template string that are based on the file-name and commands that run per-file. I'll ask them to add that to the README

**Comment by addyosmani** [comment]
It's entirely my fault for letting this pattern land. Agree we should be just using child_process here. We'll get this fixed up. Thanks for catching this, @contra!

**Comment by contra** [comment]
No problem, just want to make sure the google gulpfiles are in good shape because people use them for reference all the time.

**Comment by surma** [comment]
Any feedback regarding the gulpfile is welcome, @contra! Thank you. I plan to do a complete overhaul because it’s become quite organic and convoluted (inefficient, even).

**Comment by addyosmani** [comment]
> I can review some of the other ones when I catch a spare minute and send some PRs as well.

:+1:

**Comment by contra** [comment]
@surma If you have any questions feel free to ping me on gulp issues, IRC, or twitter whenever

**Comment by traviskaufman** [comment]
Closing this as we are moving away from gulp in v2 and there hasn't been much activity on this issue in the past year. If someone would like to contribute the change to the `mdl-1.x` branch we can reopen it.
