### ISSUE TITLE
Paint background color of previously added colored button of Icon button

### ISSUE THREAD

**Issue by adatapost** [google/material-design-lite#796]
In IE 11, it shows background color around #mdl icon if it appears after colored FAB or button.

![image](https://cloud.githubusercontent.com/assets/314143/8544608/49d4d60e-24c4-11e5-94f6-e9aa45eed71d.png)

**Comment by Garbee** [comment]
Can you provide the exact markup used in the screenshot so we can replicate the issue locally?

**Comment by adatapost** [comment]
```HTML
<!doctype html>
<html>
  <head>
    <title>MDL</title>
    <link rel="stylesheet" href="mdl/material.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--mini-fab">
      <i class="material-icons">add</i>
     </button>
    <button class="mdl-button mdl-js-button mdl-button--icon">
      <i class="material-icons">mood</i>
    </button>
    <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored">
      <i class="material-icons">mood</i>
    </button>
    <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored">
      <i class="material-icons">add</i>
    </button>
   <button class="mdl-button mdl-js-button mdl-button--icon">
     <i class="material-icons">mood</i>
   </button>
   <button class="mdl-button mdl-js-button mdl-button--icon mdl-button--colored">
    <i class="material-icons">mood</i>
   </button>
   
  <script src="mdl/material.min.js"></script>
 </body>
</html>
```

**Comment by Garbee** [comment]
The [example](http://codepen.io/anon/pen/EjEEbR) does not replicate for me in IE 11 on Windows 7. Is there anything else you need to do for replicating the problem? I tried clicking on things and highlighting but nothing causes the error.

![replication-attempt](https://cloud.githubusercontent.com/assets/868301/8545335/97c4f504-247b-11e5-8fd6-df19bb4d74fa.png)

**Comment by adatapost** [comment]
But something is wrong with my environment IE11 Windows 8.1 I guess.

![image](https://cloud.githubusercontent.com/assets/314143/8548073/6438ef82-24e0-11e5-9157-0a6128d68c4e.png)

**Comment by Garbee** [comment]
Maybe it is an 8.1 issue, I'll download a VM from MS to test.

**Comment by Garbee** [comment]
I'm unable to replicate this here using the 8.1 VM provided by MS at [modern IE](http://modern.ie).

Seems environment specific. So I'm closing this issue until something reproducible can be brought forward. We can't fix a problem we can't see. :frowning: 

![selection_001](https://cloud.githubusercontent.com/assets/868301/8618174/97a93d40-26d9-11e5-8115-1111e688ed9d.png)
