### ISSUE TITLE
Way to reinitialize components in MV* framework views?

### ISSUE THREAD

**Issue by jh3y** [google/material-design-lite#798]
Hi!

There may be a real simple solution to this that I have overlooked but if using say `button` components that utilise the `ripple` effect within MV* style views, on page load, any buttons in views will work fine, with ripple effects present.

If you are then to destroy a view and create a new one, you would only then get the CSS effect for new buttons and the ripple effect would be gone.

There could then be further issues if say using a card with an overflow menu in a view where it won't get initialized. I would imagine there would be some demand to utilise the components within MV* style projects pretty rapidly.

@jh3y

**Comment by Garbee** [comment]
[Getting started](http://www.getmdl.io/started/index.html#dynamic) covers using MDL with dynamic websites. Also, most built-in components have a downgrade method for cleaning up event handlers and such. Not well documented at the moment (Sorry!) but will be soon.

**Comment by jh3y** [comment]
Hey @Garbee 

Forgive me for overlooking the dynamic function. Was late when I had a glance over last night and then just jumped straight in ha :+1: 

Looks like the issue I am having has come up elsewhere with #804 .

@jh3y

**Comment by surma** [comment]
@jh3y That’d be very much appreciated! Thanks for offering your help.

**Comment by SebastienDaniel** [comment]
@jh3y I think we're testing the same things here.

a quick test on my end shows that if you:
1. inject your view into a parent element, 
2. register the parent with componentHendler.registerElement
3. set the parent's innerHTML to an empty string ("")
4. Re-inject your view into your parentNode

the entire component still works. Essentially after reviewing the code, the only thing the `componentHandler.registerElement` cares about is the element being registered, and the jsClass being bound to it. That elements' children can change as much as they want.

Of course, this was in my quick use-case (*where my views re-render according to data changes*). If you really need a complete teardown of your view (*including events, to avoid GC issues*) then using the `componentHandler.downgradeElement` feature is what you're looking for.

final note, I did have the same issue you pointed to #804

**Comment by jh3y** [comment]
I'm not entirely sure that's the case, but thanks nevertheless for the intel on the behaviour.

Using `registerElement` in that way I don't believe is the intention but I'm sure you're aware of that as you are testing things out. I was more investigating the way in which MV* type frameworks/libraries deal with the dynamic nature of the DOM and had completely overlooked the documentation on dynamic content.

The documented approach is the best way to go and works for I would assume the majority of components based on what I've tested. With MV* type frameworks/libraries, it's simpler because in most cases the DOM element is already created for you and added to a document fragment.

However, there are components that maybe do not act quite as intended on the use of `upgradeElement`.

@surma , can I propose closing this issue as it's kinda broad and a non-issue IMO as the documented approach works for components such as `MaterialSlider` and I will go forward looking into #804 and raising an issue for other components if no issue is currently raised (have found `MaterialMenu` to be a little temperamental)

@jh3y

**Comment by Garbee** [comment]
I have this tagged as a Doc problem. I'd rather this stay open since it is an actionable issue to work on a new doc page for explaining how to use the system.

**Comment by jh3y** [comment]
@Garbee that's fair. I've raised a separate issue for `MaterialMenu`(has buggy behaviour).

I think the documentation for dynamic website, makes it relatively clear. I think it just requires maybe having the different `jsClass` listed or mentioned on each component section, `MaterialMenu`, `MaterialSlider` etc. because the documentation currently just gives the `MaterialButton` example.

@jh3y

**Comment by Garbee** [comment]
The documentation story for devs needs some addressing. I just got so deep in during development that I lost my outsider thinking for it. :frowning: So, that made writing more difficult. I have a few issues and questions from IRC that I'm using to build up the doc story. Just need to get the time to work on it.

**Comment by jh3y** [comment]
Completely understandable :sweat_smile:

**Comment by dgaisan** [comment]
Does anybody have an example of how to create icon toggle dynamically? 
Thank you

**Comment by sgomes** [comment]
v2 will provide a path for programmatic development, with developer-controlled lifecycle for objects.
