### ISSUE TITLE
Slider thumb zooms incorrectly on click in Safari when value is zero

### ISSUE THREAD

**Issue by kitgrose** [google/material-design-lite#799]
Hovering over the slider thumb should zoom it up as per the spec. That effect is almost working, but the counter inside the thumb ends up offset diagonally toward the bottom right, and not quite large enough:

![safari slider thumb issue](https://cloud.githubusercontent.com/assets/165977/8544810/e3f65088-24eb-11e5-8969-9a10251f343e.png)

This issue was observed in Safari Version 8.0.7 (10600.7.12) on OS X Yosemite Version 10.10.4 (14E46). It doesn't affect Chrome on the same machine.

**Comment by sgomes** [comment]
Thanks for the bug report, @kitgrose!

It took me a while to reproduce, because it only seems to happen on non-retina screens, but I can see it now when clicking on the thumb.
