### ISSUE TITLE
Support absolute URLs for image resources.

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#8]
> So how are we going to handle images with material-design-lite? I see for example the checkbox still loads from url("../checkbox/tick.svg"), but that's not going to work for the minified version

We could include `images/..` as one of the directories synthetically served during 'gulp serve' and just copy assets over to that directory during both `gulp serve` and the normal `gulp` build. 

I still need to write a patch demonstrating how this could work.

**Comment by web2style** [comment]
I would like to say, than not everyone is using gulp. I'm using webpack with url loader and I have to manually rewrite all the urls to `url(mdl/images/tick-mask.svg)` for it to work properly. So maybe we can use a variable here to concatenate with image name. For example:

```
$img-path: mdl/images/; // _variables.scss


mask: url(#{$img-path}tick-mask.svg); //_checkbox.scss
```

Or even create a mixin like this:

```
mask: @include img-url(tick-mask.svg);
```

**Comment by RanzQ** [comment]
I'm using webpack too and having problems with this... The latest version has `?embed` suffix (for `gulp-css-inline-images`) but I don't know how to setup a webpack loader to discard the suffix and look for the svg file.

I haven't used gulp and don't know if there's a better option but a size based inlining tool would be better imo.

Maybe this? https://github.com/zckrs/gulp-css-base64

**Comment by web2style** [comment]
@RanzQ I removed `?embed` suffix and use `url-loader` for embedding SVGs:
```
    loaders: [
      {
        test: /\.svg$/,
        loader: 'url-loader?limit=100000',
      },
    ],
```

**Comment by RanzQ** [comment]
@web2style yeah that's what I ended up doing too but for easier updates I like keeping the source in `node_modules/` and only define custom variables and decide which components to import. Now I have to check on every update that my modified files are in sync. :)

Another option would be to fork this repo and install it.
