### ISSUE TITLE
Do we need a CHANGELOG.md?

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#808]
... to keep track of what's changed in upcoming versions of the Components.

**Comment by addyosmani** [comment]
Imo, this is something that can live in the Releases page and be automatically generated/curated using `git log` rather than living in a changelog.md. As some folks may have differing opinions here, will keep this open so we can gauge opinions :)

**Comment by sindresorhus** [comment]
IMHO `git log` generated release notes aren't very user-friendly. Instead pick out and describe the important parts and also link to all the commits. Example of a good release note: https://github.com/sindresorhus/pageres/releases/tag/v1.0.0

**Comment by addyosmani** [comment]
Nice!

I've opted for the link to all commits approach too: https://github.com/PolymerElements/polymer-starter-kit/releases. With `git log` I just meant that we could generate the initial list and then trim down to the thin list of what's useful, but the manual approach to picking highlights also works.

Wrt the specific ask in this issue, looks like your modules like pageres opt for Release page notes too vs a changelog.md: https://github.com/sindresorhus/pageres.

**Comment by nicolasgarnier** [comment]
Personally I would very much like a curated set of release notes with pointers to issues rather than commit. Issues will speak to developers using MDL on their sites better than commits because they ultimately shouldn't care about how we implement it the fix :)

**Comment by nicolasgarnier** [comment]
Examples of good release notes to me: https://github.com/dart-lang/shelf/blob/master/CHANGELOG.md

**Comment by Garbee** [comment]
We don't need a `changelog.md` file to handle that though. We can comment the tags well and that will fill the need just fine.

**Comment by surma** [comment]
I agree with Addy. When we write our release notes we should just use `git log v1.0.0 v1.0.1` or whatever to make sure everything of importance gets mentioned. Completely automating the changelog is, as @sindresorhus said, not very user-friendly.

**Comment by nicolasgarnier** [comment]
OK +1 to using the GitHub releases page and notes: https://github.com/google/material-design-lite/releases :) With IMO a nice curated simple list of fixed bugs and new features ;)

If we do that we should point to it from the Readme.md because I wouldn't have thought to look there in the first place...

**Comment by sindresorhus** [comment]
I prefer GitHub releases.

**Comment by addyosmani** [comment]
Let's go with GitHub releases. For 1.0.0, it's not valuable to summarise the ~2K commits in master, but we'll definitely use the releases page with a changelog for 1.0.1 and onwards. 

@nicolasgarnier I think we should wait until 1.0.1 to link to it from the README. Until there's a changelog to review, it's not going to give folks more value than looking at the site. SG?

**Comment by nicolasgarnier** [comment]
Sounds good we'll link it when 1.0.1 comes out!
