### ISSUE TITLE
Are we counting negatives in the Number type text fields?

### ISSUE THREAD

**Issue by pravj** [google/material-design-lite#815]
Hi everyone,

This is really amazing. :zap: 

I was walking through the [components](http://www.getmdl.io/components/index.html) section and found the [text field](http://www.getmdl.io/components/index.html#textfields-section) example labeled as *Numbers..*

I tried entering negative number in it, and it resulted in "Input is not a number!".

I can feel that you people won't like me for filing such an issue, as then irrational numbers also come under *Numbers*, but labelling that field as *Positive Number* would prevent this mislead I think.

The pattern it uses is `[0-9]*`, so changing it to `-?[0-9]*` would do this, if we want both positive and negative numbers.

Again, please don't kill me if I'm being too silly here. :octocat:

**Comment by surma** [comment]
Negative numbers are definitely not a far-fetched request. Floats might also be relevant (price tags?).

@addyosmani @sgomes WDYT? `-?[0-9]*(\.[0-9]+)?`

**Comment by sgomes** [comment]
Well, it's a demo, so we're free to do what we want! :dancer: 

I agree it makes sense to cater for negative and floating point numbers; developers can tweak the regex if they just need integers.

**Comment by surma** [comment]
> it's a demo
I *literally* did not notice. I thought this would be an upstream fix. :facepunch: 

I’ll whip up a PR then :)

**Comment by Garbee** [comment]
Plus this is just a demo... People shouldn't copy & paste and expect it to work 100% in their context. :tongue:

**Comment by nicolasgarnier** [comment]
They shouldn't :D But they will :tongue:
