### ISSUE TITLE
Ripples not working properly with Opera

### ISSUE THREAD

**Issue by wpdildine** [google/material-design-lite#816]
Animation is not behaving correctly in opera.

**Comment by surma** [comment]
Can you be more specific about the issue that you are experiencing? The ripples on the [button components page](http://www.getmdl.io/components/index.html#buttons-section) for example work fine for me in Opera.

**Comment by wpdildine** [comment]
Version:	30.0.1835.55472 - Opera is up to date
Update stream:	Stable
System:	Windows 8.1 64-bit (WoW64)


Picture is probably worth a thousand words.
![ripple](https://cloud.githubusercontent.com/assets/737734/8549533/42eeada4-2499-11e5-88c7-656ed21bb41b.png)

**Comment by surma** [comment]
I just updated to Opera 30, and can reproduce the issue now. Thank you, @wpdildine, we’ll investigate.

**Comment by sgomes** [comment]
I've done some research on this together with @paullewis (read: he did it for me) and we suspect this could be an Opera-specific issue. I've filed a bug report and am waiting to hear back.

**Comment by sgomes** [comment]
The issue is still sadly present in Opera 33. It's likely tied to the browser in some way. DNA-40907 in their bug database.

**Comment by sgomes** [comment]
Ripples will be rewritten for v2. Not feasible to fix until then.
