### ISSUE TITLE
Fix component design pattern docs link

### ISSUE THREAD

**Issue by drublic** [google/material-design-lite#822]
There is a link [here in mdlComponentHandler.js#L21](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js#L21) which might be a link to a private repository (404ing).

It would be nice if this docs would be public (if it's not already). Otherwise I'd suggest to remove this link.

**Comment by surma** [comment]
Thanks for opening! See #779.

**Comment by jasonmayes** [comment]
I have updated my repo, cloned over, and claimed the new link.

**Comment by drublic** [comment]
@jasonmayes Thank you!
