### ISSUE TITLE
Incorrect appearance of submit button on mobile Safari

### ISSUE THREAD

**Issue by bcbcarl** [google/material-design-lite#825]
Here's the screenshot on iOS 8.4:
![mdl_input_submit](https://cloud.githubusercontent.com/assets/135734/8551988/b06dcdba-250c-11e5-9c3d-75067e53737c.png)

Add `-webkit-appearance:none` on `input[type=submit]` fix the problem:
![mdl_input_submit_fixed](https://cloud.githubusercontent.com/assets/135734/8552064/1e42ea0a-250d-11e5-8704-2f3fa2a033f0.png)

```html
<input class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit" value="Submit">
```

**Comment by Garbee** [comment]
Assigning Addy to verify the bug with an emulator (since I know you have access.)

**Comment by surma** [comment]
That’s actually me ;) Apparently, I am the iOS guy, now :D

**Comment by Garbee** [comment]
Ok, I'll try and remember that in the future.

<mental note>
Assign everything to Surma
</mental note>

**Comment by surma** [comment]
> Assign everything to Surma

Oh God! :sob:

**Comment by bcbcarl** [comment]
:laughing:

**Comment by surma** [comment]
Confirmed. I’ll whip up a PR. Thanks for noticing, @bcbcarl  :)
