### ISSUE TITLE
Home page http://www.getmdl.io/ is jank on scrolling

### ISSUE THREAD

**Issue by gokulkrishh** [google/material-design-lite#828]
**Steps to reproduce**

1. Open the [homepage](http://getmdl.io/)
2. Browse through various pages such as templates, components
3. On scrolling down on any page is slow and jank

**Found Issue:**
Page is continuously repainted on scrolling due to **.mdl-layout__container** CSS **position:absolute**

**Found fix:**
Adding CSS **will-change:transform** to **..mdl-layout__content** class

**Comment by surma** [comment]
@gokulkrishh Can you give me a little more information about your environment (browser + version, os + version, hardware specs, etc)?

I executed your steps and our timeline looks fine (60fps):
<img width="532" alt="screenshot 2015-07-07 18 50 45" src="https://cloud.githubusercontent.com/assets/234957/8553116/26b8b13a-24d9-11e5-895a-96c1a4177489.png">

**Comment by gokulkrishh** [comment]
@surma sure. Check the details below

Tested Browser: **Chrome v43.0.2357.132 (64-bit)** + **Chrome Canary v45.0.2450.0 (64-bit)** (both up to date)
System: **iMac 2013 model**
OS: **Yosemite v10.10.3**

I have attached screen shot of recorded timeline in Chrome below. Also I have turned on **Show paint rectangles** & **Show potential scroll bottlenecks** in console at the bottom of devTools to check painting and scrolling problem.

![screen shot 2015-07-07 at 11 25 31 pm](https://cloud.githubusercontent.com/assets/2944237/8553398/d711385a-2500-11e5-8011-8227e9f5351b.png)
.

**Comment by surma** [comment]
@gokulkrishh Thanks a lot! I’ll investigate!

**Comment by jokeyrhyme** [comment]
I experienced weird scrolling on my iPhone 6 with iOS 8.4. But that was yesterday, today it all seems fine. Have these changes been actioned?

**Comment by Garbee** [comment]
@jokeyrhyme Plenty of changes have been done. No way to tell exactly what was causing the problem you saw. Could have been addressed by accident or could have been the device itself being slow at the time.

This issue hasn't been addressed yet since we have yet to confirm it.

**Comment by surma** [comment]
@jokeyrhyme Yes! For iOS there was a very specific fix (#730) that went live today. They are, however, independend from the issue raised by @gokulkrishh

**Comment by Garbee** [comment]
We do have some paint problems, especially on the components page.

![mdl-record-problem](https://cloud.githubusercontent.com/assets/868301/8557459/88e7b3a0-24cb-11e5-9306-6659bb6bf5c5.png)

The huge purple spike is changing component area view. That forces a full page recalc. The rest is *mostly* fine. There are a few big spikes, but most of it is idle/un-instrumeted time getting up from the 60fps mark. Is there any way to separate out the content area so only that would be recalced on a component change?

**Comment by addyosmani** [comment]
I'm also investigating component page perf issues in IE11 over in #847. Will share profiling data soon.

**Comment by gokulkrishh** [comment]
Cool!! @addyosmani Good to know.

**Comment by sgomes** [comment]
Documentation will be rewritten for v2. Not feasible to fix this until then.
