### ISSUE TITLE
Form Component

### ISSUE THREAD

**Issue by mweimerskirch** [google/material-design-lite#829]
When used in the same form, checkboxes currently look "off", because checkboxes have 0 padding, whereas text fields have a padding of 20px.

**Comment by surma** [comment]
I think we’ve had a similar discussion before internally. The main reason why the text field has a padding is to accommodate for the floating label. In general, our philosophy was to not give any margins/paddings to elements as those are typically very specific to the environment.

My 2¢: I think it is desirable to have all form elements align naturally, so maybe we should have another discussion about this. cc @sgomes

**Comment by Garbee** [comment]
I think this would involve having a form component with specific classes to aid in form building. We shouldn't touch the existing components much like this, 1) BC, 2) MD alignment.

@MikeMitterer Brought this up earlier, but since forms aren't specified in any way I didn't like the notion. Developers *should* give forms due time to make sure they display properly for their case, since what works in one place may not work well in another. Maybe some general form classes for alignment wouldn't hurt too much though as a pure jumping board.

**Comment by sgomes** [comment]
I agree with the general sentiment here. Aligning components with our current system is hard, and we should be very careful about tweaking margins and paddings anywhere, as it can lead to breakage in sites that have already been implemented. I'm open to adding new classes for form alignment or the like, as suggested, though.

I think the long-term solution revolves a radically overhauled system, such as making components aware of their guidelines, and being able to make those snap to guidelines on container elements or the page. Not sure how doable this is with modern CSS, but in any case it sounds like material for a v2 :)

**Comment by Garbee** [comment]
> such as making components aware of their guidelines, and being able to make those snap to guidelines on container elements or the page. 

Welcome to my world with looking into the Cards component. :tada: 

If we are open to form classes to help with alignment there, then we should start scoping out a Form Component's contents.

# Hijack!

So, form component.

* Has no Material Design specification. Provided purely to aid in quickly aligning form items in a consistent manner.
* Should only touch alignment of children.
    * Make sure inputs align vertically
    * Optional view modes triggered via modifiers
       * Horizontal (inline)
       * Any others?

**Comment by sgomes** [comment]
Layout and composition will be fundamentally different in v2. Closing this as I'm sure we'll have entirely different and more specific issues when making the first alpha available.
