### ISSUE TITLE
Offline documentation

### ISSUE THREAD

**Issue by Krazitchek** [google/material-design-lite#830]
Hello, for an offline use is there a way to download the documentation available online at http://www.getmdl.io/components/index.html ?

Some of us work offline (without internet at work) because of compagny security reason, and it would be great to get this doc offline.

Thank you.

**Comment by Garbee** [comment]
Issue #740 is open to help with this. However, all you need to do is clone the repo, install deps, and run `gulp serve`. That will provide you with the full site.

**Comment by geoffreymwangian** [comment]
I really dont think garbee should have closed this issue since am also facing the same problem and the issue 740 isnt related to the documentation, I did clone the github repo and run npm install but this doesnt start the docs with gulp serve

**Comment by Garbee** [comment]
#740 *is* about the doc site. https://getmdl.io That way you aren't downloading and running the microsite manually which can be buggy and difficult. Make sure to run `gulp all` before serving, otherwise nothing will have been built.
