### ISSUE TITLE
Template Text-heavy webpage drawer menu doesn't work

### ISSUE THREAD

**Issue by guilhermetrovo** [google/material-design-lite#835]
MDL version: 1.0.0
Browser: Firefox
Browser version: 39
Operating system: Windows
Operating system version: 8.1
URL: http://www.getmdl.io/templates/text-only/index.html

What steps will reproduce the problem:
1. Open the URL for the template on mobile or make your browser screen small, the menu will change to the Drawer.
2. Open the menu clicking on the icon
3. Select any other page

What is the expected result?
Change to the page that the link is supposed to.

What happens instead of that?
Nothing. The obfuscator and the menu disappear, however the user is not dispatched to the new link.

I've done a workaround to make it work, I believe you guys can make it better, but I'm attaching my code here anyway :)
Sorry but I couldn't make it work or jsfiddle, so I just printed my code.

![drawerlinkhandler](https://cloud.githubusercontent.com/assets/13225824/8556004/0fa7ca74-24c2-11e5-8359-a18043cd5671.png)
![using_drawerlinkhandler](https://cloud.githubusercontent.com/assets/13225824/8556005/0fabcf7a-24c2-11e5-8db0-211faa60985d.png)

**Comment by surma** [comment]
Thanks for the in-depth report. That must have slipped through the cracks.

**Comment by Garbee** [comment]
It was working for me a few days ago... No idea what changed to cause it to break.

**Comment by guilhermetrovo** [comment]
If you assign a link to a tab on the footer it doesn't work as well. However if the tab is active it scrolls to the anchor normally.

**Comment by venuduggireddy** [comment]
Even dashboard template having similar issue on IPad chrome http://www.getmdl.io/templates/dashboard/index.html
Click on drop down menu next to User hello@email.com

**Comment by Garbee** [comment]
@venuduggireddy iirc that issue is being tracked in another issue and isn't related to this one.

**Comment by komplexb** [comment]
Does the closed status mean this is fixed and available in the CDN js file?

**Comment by Garbee** [comment]
@komplexb The fix isn't anything to do with the core files. It was in the template files (as the commit that closed the issue shows.) You will need to apply the new modifications if you already were using the old version.

The current content being served may not reflect these changes either, since I don't think we have automated deployment yet of site updates. It could be waiting for a manual site refresh before being served via getmdl.io.

**Comment by komplexb** [comment]
But the screenshot of his fix was made in material.js, isn't that the file, well the .min.js version that's at the CDN link?
`https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js`

**Comment by Garbee** [comment]
The screenshot was not the fix.  commit d53dceb34907833eb5b93be30f50e48e20a92d7d was the fix.

**Comment by komplexb** [comment]
ah I see. Good thing I asked, thanks for pointing it out.



On Sun, Jul 12, 2015 at 7:26 AM -0700, "Jonathan Garbee" <notifications@github.com> wrote:
The screenshot was not the fix.  commit d53dceb34907833eb5b93be30f50e48e20a92d7d was the fix.

---
