### ISSUE TITLE
Slow spinner load

### ISSUE THREAD

**Issue by Emil113** [google/material-design-lite#836]
I'm trying to use the default spinner.  It loads fine but before it's shown, I see a text placeholder of "Loading..." for a good while before I actually see the spinner animation.  Any way to speed that up?

Thanks!

**Comment by Emil113** [comment]
I figured out a way to preload it so it seems to work a lot faster now.

Talking about the spinner, is there any way to resize it?

**Comment by Garbee** [comment]
Support questions should be asked on StackOverflow and use the `material-design-lite` tag please. This will keep the tracker focused on core issues and give the wider community better access to questions and answers.

For re-sizing though, just change the width to whatever you want.

**Comment by sank8893** [comment]
I also have the same issue. 

It shows "Loading..." instead of the spinner.
