### ISSUE TITLE
Better customisation docs

### ISSUE THREAD

**Issue by innerpeace0** [google/material-design-lite#841]
The [customize](http://www.getmdl.io/customize/index.html) page of the docs do a great job of showing how to customize the color theme. However, some users may want more customization. I happen to know that simply adding an extra css file that loads last, with whatever customization a user wants, will override anything in MDL, but not every user will be aware that. Adding something to that effect might be helpful.

Great job so far. I'm especially impressed how fast issues are being addressed. Thanks for this.

**Comment by Garbee** [comment]
> adding an extra css file that loads last, with whatever customization a user wants, will override anything in MDL, but not every user will be aware that.

Considering this is a fundamental part of web dev, people using MDL should know this. There is a certain level of expected knowledge with any documentation project.

**Comment by adcoolguy** [comment]
unsub

**Comment by Garbee** [comment]
@addyosmani Do you think this is really necessary to add to the customizer page?

It is superfluous content at best to the great majority of users. We'd be better off spending time focusing on Sass level customization documentation to help developers get their own build pipeline going in that regard then handling this low-level information.

**Comment by addyosmani** [comment]
Imo, this content should be deferred to an FAQ. I consider it P2 compared to focusing on better improving the docs situation for Sass.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/49
