### ISSUE TITLE
When focused or clicked, the slider track and thumb are supposed to become darker as per the spec

### ISSUE THREAD

**Issue by kitgrose** [google/material-design-lite#842]
In the spec, the slider's colour changes from `rgb(176, 176, 176)` to `rgb(238, 238, 238)` when it has focus or is being clicked:

![The sliders image from the Material Design spec][1]

In practice, this doesn't seem to be implemented in MDL (the track stays the same colour), in both Safari and Chrome on OS X Version 10.10.4.

  [1]: http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7QkJlRGNfTGEzQlE/components_sliders_continuous1.png

**Comment by sgomes** [comment]
Wow, good eyes, @kitgrose! Can't believe how many times I looked at that image and never noticed o_O

I'll see if I can cook up a fix soon.

**Comment by Garbee** [comment]
It's the subtle things in the spec that drive us mad.

**Comment by sgomes** [comment]
Not feasible to fix in v1. For v2, the slider is being rewritten as part of #4494.
