### ISSUE TITLE
modify visibility the titles in docs

### ISSUE THREAD

**Issue by Bound3R** [google/material-design-lite#846]
I think convenient Improve the visibility of the titles in the documentation
I completely ignore the title, even I thought there not was :joy:

![image](https://cloud.githubusercontent.com/assets/5579520/8561627/e33a799c-24ed-11e5-826e-a639fc89bac8.png)

what is your opinion?

**Comment by addyosmani** [comment]
cc @santokii for her opinion here.

**Comment by santokii** [comment]
Thanks for the feedback! I will take a look and come back with a few alternative solutions!

**Comment by Bound3R** [comment]
I have an idea @santokii , you can use more space and a separate divider border, same as in the page style guide.

![image](https://cloud.githubusercontent.com/assets/5579520/8575584/5215a1a6-2562-11e5-9e5f-cd089fb26b34.png)

**Comment by Garbee** [comment]
Also styling the heading with the primary color and enlarging it a bit would be a good touch. Emulating the official styleguide more there as well.
