### ISSUE TITLE
Error when opening getmdl.io in Chrome

### ISSUE THREAD

**Issue by arkraft** [google/material-design-lite#850]
Browser: Chrome 
Browser version: 43.0.2357.132 m
Operating system: Windows 7

What steps will reproduce the problem:
1. Open www.getmdl.io in Chrome

When opening www.getmdl.io in Chrome, i get an "ERR_CONTENT_DECODING_FAILED" error.

I tested it in Firefox and everything works fine. I also tested it in Internet Explorer 9 (I know there are newer versions, but some of our clients are still using this version, so we have to test with it) and it tries to download the page.

**Comment by addyosmani** [comment]
I haven't been able to reproduce this issue I'm afraid. When you navigate to http://getmdl.io in Chrome is there any other information available? We've been doing backend refreshes to our gzipping strategy and there's a small chance this was related to the error you were seeing.

**Comment by arkraft** [comment]
I believe this has something to do with the proxy of my company. I still get this error using chrome, but when i use the https://hide.me/de/proxy, i can open the page in chrome. I just don't get why firefox is working fine and chrome has problems with it.
