### ISSUE TITLE
ripple animation is too fast

### ISSUE THREAD

**Issue by gksu** [google/material-design-lite#852]
The ripple effect is too fast and looks ugly.
I found the following [code](https://github.com/google/material-design-lite/blob/a3bfcf45209d1f5356fd3288cb1b1f83a1923dc2/src/ripple/_ripple.scss#L32-L37) in `/src/ripple/_ripple.scss`
```
.mdl-ripple {

  ...

  &.is-animating {
    transition: transform 0.3s $animation-curve-linear-out-slow-in,
    width 0.3s $animation-curve-linear-out-slow-in,
    height 0.3s $animation-curve-linear-out-slow-in,
    opacity 0.6s $animation-curve-linear-out-slow-in;
  }

  ...

}
```
The animation duration is *0.3s* (0.6s for opacity). I discovered that [angular material](https://github.com/angular/material)  uses `$sizeDuration: 0.65s * 2` as the animation duration for ripple ([see here](https://github.com/angular/material/blob/fb7b9b3977f61528f7dc42756b2f2b87257e5ce0/src/core/style/structure.scss#L123-L131)), and the effect looks really nice.

**Comment by addyosmani** [comment]
Thanks for the feedback. We should ask the MD team if the values for ripples have recently changed. Polymer uses `1.1 - 0.2 * (waveRadius / Ripple.MAX_RADIUS);` for the duration on their paper/material buttons.

cc @santokii as an fyi.

**Comment by gksu** [comment]
@addyosmani The animation of [TEXT-HEAVY WEBPAGE](http://www.getmdl.io/templates/text-only/index.html)'s tab switch and the expand search field in this [DASHBOARD](http://www.getmdl.io/templates/dashboard/index.html) page also have this issue

**Comment by sgomes** [comment]
Thanks for the report, @gksu! That will definitely be the case, yes; we have a single codebase for our ripples, so if there's a problem in one place it'll likely be everywhere.

We're going to try to get an authoritative response from the Material Design team on how fast the transitions should be, exactly, to make sure we switch to the right speed. We'll tweak the values when we hear back.

**Comment by addyosmani** [comment]
Assigning to myself. We have #973 that also requires ripple feedback from the MD team. I've repinged the review thread just now to try getting a response before 1.0.1. If we don't get one by end of Wednesday, moving this to 1.0.2.

**Comment by slugmandrew** [comment]
+1 It's way too fast

**Comment by shwaydogg** [comment]
+1, I was surprised how fast the ripple was.  Any updates?

**Comment by surma** [comment]
I’m closing this in favor of #1466. No code to show yet, @shwaydogg.
