### ISSUE TITLE
Make sure tooltips are always visible / don't overflow the page.

### ISSUE THREAD

**Issue by nicolasgarnier** [google/material-design-lite#858]
Right now (thanks to #839) tooltips don't overflow on the left of the window.

It would be great to improve this to also handle the other cases:
 - If the tooltip overflows on the right side of the screen.
 - If the tooltip overflows on the bottom of the screen.

**Comment by achalv** [comment]
I'd be happy to pick this up. :)

**Comment by addyosmani** [comment]
@achalv Go for it! :)

**Comment by sgomes** [comment]
Not feasible to fix in v1. Tooltips to be reimplemented in v2 under #4495.
