### ISSUE TITLE
Improve release build pipeline

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#862]
There's some redundancy in our current release pipeline that would be useful for us to remove short term. Walking through the current strategy:

1. Gulp generates the site, MDL build assets and all of the theme files needed for the site to `dist`. We publish the site to GCS (getmdl.io bucket)
2. Gulp generates a zip archive for (a) components ~mdl.zip and (b) components and templates ~mdl-templates.zip in `dist` that we then also publish to GCS, but under the code.getmdl.io buckets.
3. We separately do a local Gulp build of MDL, use a Bash script (ugh) to strip down what we need from `dist` and rewrite package.json. We publish this 'minimal' build to the `release` branch using `git subtree` and then create a release tag using this bundle.

Steps 2 (a) and 3 involve creating the exact same bundle, except for the package.json file which we should be using the same (minimal) version of anyway. 

I propose we refactor the above two steps so that (just using Gulp) we create a temporary release directory containing what 2(a) needs (say `_release`). We then publish the contents of this directory using `git subtree` (maybe with https://github.com/Snugug/gulp-subtree?) to the release branch and tag it (what 3. needs). We use the same `_release` directory for creating the 2(a) zip file. 2(b) otherwise stays the same. 

We effectively remove 3. and the need for that temporary Bash script at all. This also (I believe) removes the need for release branch vs GDS asset auditing in #727.

Thoughts, @marcacohen @surma?

**Comment by marcacohen** [comment]
This makes sense to me and seems worth pursuing. We might consider not pushing our release assets into the www.getmdl.io bucket (instead referring the code.getmdl.io versions). That would avoid the problem of people, inadvertently or not, picking up unblessed assets from the microsite. The downside of this change is that we wouldn't be able to push a site specific fix to the libraries.

**Comment by surma** [comment]
> There's some redundancy 

Ha, understatement!

All in all, I agree and I like the proposal. However I am unsure about how this is “useful for us to remove short term”. The current setup works (if you don’t think about it too much) and I am wondering if it is worth our while to bump up the priority of the complete Gulp overhaul, which would include what you just proposed.

I have no problem implementing this anyways, I just want to hear your thoughts if this is actually worth doing twice in the long run.

**Comment by addyosmani** [comment]
@surma if you have a chance, could you give us an update on what you were thinking we might be able to slip in for build tooling updates in 1.0.1? cc'ing in @Garbee as an FYI on our thinking here.

For #793 (related), we'll want to be able to generate a publishable package which includes the Sass sources in `src` but (ideally) excludes `docs`, `templates`, `test`, and the `snippets` directories to keep things relatively trim. The challenge there is making sure that a minimal set of Gulp tasks work for importing/building the Sass. 

So we effectively need to generate two local packages:

* Minimal distro (minified CSS/JS/source maps) which get published to the release branch and get tagged. This is what many of our users not using the CDN will grab.
* Complete distro for Sass users that we publish to npm and make available to Bower. Includes minimal distro (`dist` directory), `src` directory (and deps), Gulpfile, README, other necessary files for the Sass source to build.

If you think we can get this done as part of the Gulp pipeline for 1.0.1, great. If not, I can update my interim release generation scripts to tackle some of 793 and we'll punt the rest to 1.0.2. Let me know if you think you'll have time for this one :)

**Comment by Garbee** [comment]
>  The challenge there is making sure that a minimal set of Gulp tasks work for importing/building the Sass.

I'm not too sure where this comes into play with the sources distribution. We are not distributing the gulpfile or anything like that. If people are building using the sources, they should be knowledgeable enough to fill in their workflow without directly copying ours (or if they do understanding what to modify.)

**Comment by surma** [comment]
Will be closed by #1147.

**Comment by Garbee** [comment]
If anything is incorrect now with the build pipeline, or that just needs general improvement. Let's get specific issues filed since #1147 is landed.
