### ISSUE TITLE
Typography Notes

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#863]
After playing around with types on Web Fundamentals, the sizes are huge on mobile, should the fonts be responsive? cc @santokii for comment on her thoughts.

Looking through the code - tweaking isn't all that easy.

On a separate note, is there any value in following a patter similar to @csswizardry : https://github.com/csswizardry/typecsset/blob/master/typecsset.scss

I've used this for a few projects at its served me well and allows easy tweaking, plus adds rem + px support - which is a nice win.

**Comment by addyosmani** [comment]
I brought up the need for guidelines on responsive typography with MD team before. I believe we're still waiting on guidance there to be provided before we can implement something, but also happy for us to go with a proposal from @santokii if one becomes available.

**Comment by sgomes** [comment]
Typography will be completely revamped for v2. Not feasible to fix until then.
