### ISSUE TITLE
img and video max-width please

### ISSUE THREAD

**Issue by gauntface** [google/material-design-lite#865]
This is pretty much always a good idea - max-width: 100%; height:auto; for images a videos. Any objections to me adding this in?

EDIT: Changed to max-width.

**Comment by surma** [comment]
`min-width: 100%` for images sounds like a horrible idea. Am I not seeing the use case?

This would also be a major breaking change, but that’s a secondary concern.

**Comment by Garbee** [comment]
Yea, I actually am developing in a case where that min-width would be murder. I think we could do some quick helper classes for these though. So it is easy to add if you need it without breaking existing stuff (or making developers need to hack around to undo the defaults.)

**Comment by gauntface** [comment]
Sorry - max-width: stupid me.

**Comment by Garbee** [comment]
ah, *max*... then yea, that one kinda does make sense to keep things in the boundaries...

Height auto I'm still *slightly* worried about since it could offset the aspect ratio of images put into containers when the container could expand to show the image at a viewable size.

**Comment by surma** [comment]
`max-width` seems much more sensible. I do see the point, but that seems like something that belongs in a reset rather than MDL. We are not even styling `<h1>`s by default anymore. Everything is scoped behind `.mdl-xxx`, so I’m not sure we should be doing this in MDL.

**Comment by Garbee** [comment]
I mean, we do have our own reset values. The max-width for video,img can be added there just fine.

**Comment by brandonjpierce** [comment]
So far I have added the max-width for images and videos in two separate projects that I am using mdl in so I can definitely see it as something useful. Perhaps instead of baking it into the reset maybe have a small section of "helpful classes / styles" in the docs that people can copy and paste in? I understand @surma concern for wanting to keep things behind a scoped namespace so it may not make sense to make it a class (similar to bootstraps .img-responsive)

**Comment by Garbee** [comment]
I wonder if adding it as a reset anyways would cause a big BC issue... Seems like it could if people already are building with the expectation that images can expand beyond their container (even though this seems like something you wouldn't do intuitively.)

**Comment by innerpeace0** [comment]
I've been using max-width for images and videos, along with auto-height, for years, and it's been great on any size window. +1

**Comment by brandonjpierce** [comment]
@Garbee I could see adding it in as a reset potentially causing issues as you mentioned. Has the mdl team thought about adding generic utility classes to the library eventually? I could see a responsive image class fitting in nicely.

**Comment by innerpeace0** [comment]
`max-width` works quite well for responsive images. With videos, particularly from YouTube (which are the ones most often embedded into websites) there's  a little more to it. So you don't have to reinent the wheel, here's a [wordpress plugin] (https://wordpress.org/plugins/youtube-embed-plus/) that does responsive videos quite nicely.

**Comment by gauntface** [comment]
I'm with @Garbee on this being something that should probably live in the resets.

Regarding utilities class - love util classes, but I'd argue you'd want max-width: 100% by default and have a utility class to revert back to max-width: initial, or something to that affect.

**Comment by Garbee** [comment]
Nothing we can do here currently. But I'd say for V2 we investigate making `max-width:100%;` default via custom reset for `img` and `video`. With **no** utility class for resetting. The reason for not providing a utility class is that MDL is not a framework and we need to stay lite. If developers want something different, they can create their own helper classes. When they see they are using some often, then they can make their own packages to reduce their copy & paste between projects.

**Comment by sgomes** [comment]
We'll stop providing global resets in v2 (by default, at least). Closing.
