### ISSUE TITLE
Make mdlComponentHandler.js + components work with browserify

### ISSUE THREAD

**Issue by drublic** [google/material-design-lite#873]
We've set up an environment with Browserify for our JS components.
Requiring mdlComponentHandler.js does not export anything which causes a JS error since components are not able to access `componentHandler `.

`componentHandler ` is a global variable which is not exposed to the global scope via `window`, `module.exports` or other means. Thus it's not possible for components to access this global variable when using a tool like Browserify which encapsulates the modules with an IIFE or any other wrapper.

I would suggest to add something like `window.componentHandler = componentHandler;` sowhere around [L258](https://github.com/google/material-design-lite/blob/master/src/mdlComponentHandler.js#L258) in `mdlComponentHandler.js`. This gives you the chance to use with with Browserify w/ CommonJS, AMD, UMD or ES6 modules with a shim. Another solution would be to implement UMD directly.

In general I think using a more specific definition as a property of the global object should be favored over using an implicit (unspecific) mechanism like the current one.

I don't really care about the solution provided if there is any. Maybe I was just not able to find the correct transform for Browserify. So I am very open to suggestions. Please correct me if I miss something else here.

**Comment by Garbee** [comment]
Sounds a lot like issue #833. Closing in favor of having discussion there.

**Comment by drublic** [comment]
:+1:
