### ISSUE TITLE
[Component Request] Add Speed Dial & FAB toolbar

### ISSUE THREAD

**Issue by mukilane** [google/material-design-lite#874]
A speed dial component which opens upon clicking the FAB. And also a FAB toolbar.

Spec: http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
Image: 
FAB Speed Dial : 
http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B1PhAWhtrRTrenZ5RnRTMmEtcU0/patterns_actions_fab_actions14.png

FAB Toolbar:
http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-NXNEaXZ0Um1yc0k/components-buttons-fab-transition_toolbar_01.webm

**Comment by Garbee** [comment]
This should be split out into two issues to track, but we can handle that once it comes up. For now, looks like it would make a solid addition.

**Comment by jh3y** [comment]
I've had a play around with creating that speed dial effect. Would just need reformatting to the `mdl` code style. 

@jh3y

**Comment by Garbee** [comment]
@jh3y Make sure it is under the button component. I don't think we are ready to do a point release just yet to add new stuff in, but I'd more than welcome an active PR starting on the work for review. 

I'll forgo making an issue on that and we can just use the PR to track and leave this issue for the FAB Toolbar.

**Comment by jh3y** [comment]
Yes for sure @Garbee.

I haven't started looking at putting it in to a PR yet, but I had created the effect with a styled button based on the design spec before the MDL release.

**Comment by dcworldwide** [comment]
Materialize css framework has this...can use it as a basis. One issue with it however is that it does not work well on mobile at all

**Comment by jh3y** [comment]
I was able to have a quick go at putting something small together for this [here](http://jsbin.com/quworiropo/1/edit?html,css,js,output).

It's not in the MDL code nor style but it was to just get something working. I haven't really looked at Materialize.

@jh3y

**Comment by VamosErik88** [comment]
Any update on the state of the art on this components? Really need it....

**Comment by surma** [comment]
@VamosErik88 We haven’t started any development. There was higher demand on snackbars and dialogs, so those got the higher priority for now.

**Comment by VamosErik88** [comment]
Thanks for the answer man! 
In the mean time I found this workaround created by someone that is working pretty good in what I need. 

http://jsbin.com/seyukazowu/edit?html,css,js,output

Hope it's useful for others too ;)

**Comment by surma** [comment]
That’s actually pretty damn good visually. Thanks for sharing :)

**Comment by VamosErik88** [comment]
You're welcome :)

**Comment by jh3y** [comment]
Haha you're welcome, that's my creation :smile: I wrote a post on it but didn't want to put a blog post in the issue thread.

**Comment by VamosErik88** [comment]
You're great jh3y!!! Your work saved my day :100: ;)

**Comment by jfily** [comment]
Hi,

Here is a pure css solution here : http://codepen.io/jfily/pen/xwdMej

**Comment by nesgael** [comment]
Hello,

I also made a plugin for the Speed Dial. It's customizable with several options.
You can view the demo page [here](http://nesgael.github.io/mdl-speed-dial/).

**Comment by DragosDumitrache** [comment]
Hello,

I've also given the toolbar an attempt with a twist, as in the button turns into a toolbar on click.
The demo can be found [here](http://codepen.io/sireofdragons/pen/ZOYdbj). Positioning the toolbar is somewhat of a hack, if anyone has any ideas on how to improve it and make it more general, that'd be great.

**Comment by sgomes** [comment]
Superseded by #4482 and #4483.

**Comment by iryan2** [comment]
Hi @sgomes,

This issue is requesting a FAB Speed Dial, but the issues you've linked make no mention of it.

#4482 is for a FAB Toolbar and #4483 is for a FAB Single Sheet Menu.

The speed dial can be seen [here](https://material-design.storage.googleapis.com/publish/material_v_9/0B8v7jImPsDi-ZFR3dGtLUjZad1U/components-buttons-fab-transition_speeddial_01.webm) and on [this page](https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions), under 'Speed dial'.

Are there any plans to include this in material-design-lite?

**Comment by sgomes** [comment]
@iryan2 There are other preferred transformations in the spec now, namely the toolbar transformation, so it's not yet clear whether we'll be implementing speed dial. I suspect it will be a function of time, more than anything.
