### ISSUE TITLE
[Component Request] Autocomplete

### ISSUE THREAD

**Issue by viniciusdacal** [google/material-design-lite#877]
Please include:
Would be interesting have a autocomplete text-field
we have this one in angular material
https://material.angularjs.org/latest/#/demo/material.components.autocomplete
And I think, we could have an option to insert a new item too, instead of just list the source base.

**Comment by Garbee** [comment]
I think this works more into the chip request as far as UX goes. The underlying implementation of how you use it would probably end up being done in userland. That discussion can happen once that works has begun though.

Closing in favor of issue #857 for the UX.

**Comment by masaeedu** [comment]
@Garbee This was closed in favor of #857, but then #857 was closed without any implementation of autocomplete. I think this needs to be reopened.

**Comment by Garbee** [comment]
You use chips to build your autocomplete. The base  chip implementation for MDL does not provide the full-width chip style the spec uses for the dropdown selection.

Material Components for Web (MDC now, was MDL v2) is the next renovation of these components. It should include the full chip specs which developers can use to build autocomplete.

Do remember, we would not provide the autocomplete behavior, just the UX pieces to let you have the designs for it. The actual build-out of autocomplete functionality would still be on developers.

**Comment by masaeedu** [comment]
@Garbee I understand your point re: devs having to build the autocomplete functionality themselves. I don't expect MDL to manipulate the DOM for me, my JS will generate the suggestion entries and update the textbox when an item is selected. Instead, it would be good if MDL could provide CSS consistent with [the spec](https://material.io/guidelines/components/text-fields.html#text-fields-auto-complete-text-field), and the corresponding markup.

All users could of course implement their own CSS for a suggestions dropdown, but isn't this something that falls within the purview of this project?

**Comment by Garbee** [comment]
If you look at the [chip specification](https://material.io/guidelines/components/chips.html) you'll see they are the defined autocomplete UX. We however don't provide that full-width chip styling in MDL. If someone wants to contribute a patch to our chips to provide that UX addition, `mdl-1.x` is open for PRs.

The UX you want *is* chips. It is just styled differently then the basic inline chips. This is a case we didn't go over when reviewing the initial chip PR.

**Comment by masaeedu** [comment]
@Garbee But I don't want chips for this field. That is, I don't have multiple items to choose that appear in the vicinity of the text field. I just want autocomplete for the single text value that will occupy the field. If you read the part of the specification you linked to, there is no mention of autocomplete.

If you take a look at [this section of the spec](https://material.io/guidelines/components/text-fields.html#text-fields-auto-complete-text-field), you'll see that an autocomplete dropdown is an independently specified part of the UX for text fields.

**Comment by Garbee** [comment]
Chips call them "Contact chips" but they are just full width chips. That is the autocomplete UX. Whether you select multiple or not, is not relevant.

**Comment by masaeedu** [comment]
Contact chips can be used without autocomplete, and autocomplete without contact chips. You didn't comment on the previous link I gave you (which describes autocomplete as a feature of text fields), but please refer to:

 - [Other](https://material.angular.io/components/component/chips) [implementations](http://materializecss.com/chips.html) of chips, which you can see are independent of autocomplete
 - The ng2 [autocomplete feature spec](https://docs.google.com/document/d/1c9e9-5HlOFKqmdq147yugAQroMLfOeGdRGyB1JGxKVE/preview), which is independent of chips
 - The [ng1 implementation of autocomplete](https://material.angularjs.org/latest/demo/autocomplete), which is once again independent of [chips](https://material.angularjs.org/latest/demo/chips)

You can put chips inside the autocomplete suggestion list, or text, or whatever else you like. Chips and autocomplete are independent parts of the material design spec.

**Comment by Garbee** [comment]
We don't care how other MD implementations do things. Most add extra duplication that isn't needed or just do their own things anyways.

The *spec* defines autocomplete for textfield, yes. I've seen this. However I also look at the chip spec and see the exact same interface for the selections being used for contact selection. Therefore, it makes sense that they are in fact, one-in-the-same. One component, multiple possible use-cases depending on how developers take advantage of it. Therefore, it is a part of the *chip* specification style-wise unless the MD team comes out with more exact specs for textfield autocomplete to show where it differs from the chips.

I'm sorry the specification is confusing and the way components can be used within each other isn't clearly defined. I don't have any control over that however. All I can say is, from an *implementation point of view*, what you want is whole-width chips.

**Comment by Garbee** [comment]
FTR too, this is exactly why you shouldn't look at other implementations and how they do things. They just add more confusion to what MD already doesn't make clear. This is a very difficult thing to parse out to get isolated and modular components that can be re-used in numerous contexts.

No matter the other implementations, I promise you what you want is a part of chips. It simply is a part of it we didn't think about with the initial PR since the initial PR for chips covered the case it needed to hit.

If someone wants to PR an update to chips to get the full-width display, we'd be happy to review PRs for that.

**Comment by Garbee** [comment]
Thinking this over just now, you could make the autocomplete items out of a standard [list](https://getmdl.io/components/index.html#lists-section).
