### ISSUE TITLE
[Component Request]  UI Header alike paper-scroll-header-panel

### ISSUE THREAD

**Issue by viveking** [google/material-design-lite#881]
* Description:
 A good to have a UI Element same as polymer with a scrollable header.
* Material Design Spec link:
https://elements.polymer-project.org/elements/paper-scroll-header-panel?view=demo:demo/index.html

**Comment by surma** [comment]
If you are talking about the header behavior, we do have that. It’s called [waterfall header](http://www.getmdl.io/components/index.html#layout-section/layout).

Also, Polymer is not the MD spec, [this is](http://www.google.co.uk/design/spec/material-design/introduction.html).

Does this answer your question?

**Comment by viveking** [comment]
That doesn't work on small devices.

**Comment by Garbee** [comment]
Let's reach out to the MD team to see if Polymer's implementation adheres to some part of the spec. Looking over layout -> [structure](https://www.google.co.uk/design/spec/layout/structure.html#structure-ui-regions) it isn't jumping out at me if it is.

**Comment by sgomes** [comment]
Superseded by #4484.
