### ISSUE TITLE
[Component Request] Subheaders 

### ISSUE THREAD

**Issue by mukilane** [google/material-design-lite#882]
Subheaders are necessary. And even 'sticky' subheaders.

Spec: [Subheaders] (http://www.google.com/design/spec/components/subheaders.html)

**Comment by jamez14** [comment]
Has this request already been fulfilled? I see in the `src/typography` folder, there are references in the to `mdl-typography--subhead` class. Do subheaders just need to be documented on getmdl.io? Or does their functionality need expanded to better match the spec referenced above?

**Comment by Garbee** [comment]
Closing this specific issue out. Instead of a general subheader component, we need to build subheaders into the given components for which they are specified here.
