### ISSUE TITLE
Disabled Navigation Drawer

### ISSUE THREAD

**Issue by titlescreen** [google/material-design-lite#887]
Please allow for disabled navigation in the Drawer, I've written this which works...
```html
    <style>

        .mdl-navigation__link[disabled] {
            color: rgba(0,0,0,.26) !important;
            cursor: default;
            background-color: transparent;
        }

        .mdl-navigation__link[disabled]:hover {
            background-color: transparent !important;
        }
    </style> 

    <html> 

    <div class="mdl-layout__drawer">
           <span class="mdl-layout-title mdl-color--primary mdl-color-text--white">
                <img src="img/torus-logo.png" alt="Torus logo" height="100" width="135" />
                <br />
                User Name
            </span>
            
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" href="">Dashboard</a>
                <a class="mdl-navigation__link" href="">Clients</a>
                <a class="mdl-navigation__link" disabled>System Access</a>
            </nav>
        </div>
    </html> 
```

**Comment by surma** [comment]
I can’t find a disabled drawer item in [the spec](http://www.google.co.uk/design/spec/patterns/navigation-drawer.html#), but I agree that the use-case is definitely there. I’ll forward this to the MD team and see what their take is.

cc @santokii @sgomes

**Comment by Garbee** [comment]
`disabled` is an invalid attribute for anchors it seems. So, not sure what this is trying to achieve.

**Comment by surma** [comment]
Wether it’s via a `disabled` attribute or a class like `mdl-navigation__link--disabled` is secondary. We have no guidance on the styling currently.

**Comment by titlescreen** [comment]
Fan-flipping-tastic, for a v1 this is cracking, I'm just looking at using it to system and online recruitment system and it would be very useful to show features that exist but users don't have access to due to their security level.

**Comment by Garbee** [comment]
These would need to be buttons for disabled to be a valid attribute (and therefore do something.) We'd implement this as a modifier over using the disabled attribute for targeting.

**Comment by sgomes** [comment]
Yes, I think it makes sense to have this, thanks @titlescreen!

@Garbee the fact that it's an anchor is mostly an implementation detail, so I can definitely see a use for this. It may not be through the disabled attribute, but perhaps through an optional class in this case, though.

**Comment by Garbee** [comment]
@sgomes Yup, see above. Implementing a `--disabled` modifier is the method to go with.

**Comment by sgomes** [comment]
@surma You're right, the main issue here is we don't have any spec guidance for this, at the moment. We may need to get in touch with the MD team before we come up with some crazy styling ourselves :)

**Comment by titlescreen** [comment]
@sgomes Cool beans!

**Comment by surma** [comment]
MD team instructed us to use disabled text styles in the drawer for disabled links.

**Comment by sgomes** [comment]
This has been merged.
