### ISSUE TITLE
Problem with the material-design-lite package

### ISSUE THREAD

**Issue by kiril-stanoev** [google/material-design-lite#888]
Hey guys,
I tried installing the material-design-lite package. This is what I got. Ideas?

----------------------
$ npm install material-design-lite --save
material-design-lite@1.0.0 install D:\xxx\xxx\material design language\node_modules\material-design-lite
napa mojombo/clippy

'napa' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "material-design-lite" "--save"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! material-design-lite@1.0.0 install: `napa mojombo/clippy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the material-design-lite@1.0.0 install script 'napa mojombo/clippy'.
npm ERR! This is most likely a problem with the material-design-lite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     napa mojombo/clippy
npm ERR! You can get their info via:
npm ERR!     npm owner ls material-design-lite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\xxx\xxxmaterial design language\npm-debug.log

XXXX@XXXX D:\xxx\xxx\material design language`

**Comment by surma** [comment]
Luckily, @addyosmani already gave instructions how to work around this. We’ll fix it for good in v1.0.1.
See #859 for instructions. 

Closing this for now. If the problem persists, feel free to re-open :)
