### ISSUE TITLE
Negate touch delay

### ISSUE THREAD

**Issue by mikkokam** [google/material-design-lite#893]
Is there the old 300 ms lag on touch devices?

Seems I get a better response on touch devices when testing with fastclick.
Most libraries take care of this nowadays already, so was expecting MDL to do so, too.

**Comment by Garbee** [comment]
Chrome and FF have removed this [ref](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away) (FF referenced via ticket linked to in the end.)

There is an MS prefix rule we could use to remove it, and looks like Safari we may still be up a creek.

Something we should look into and fix upstream, without extra libraries, if possible.

**Comment by Garbee** [comment]
Assigning sgnomes to hopefully handle initial triage and deeper research on this. If you are unable to, then let me know and I can dig into it later this week.

**Comment by Garbee** [comment]
Oh yea, @paulirish may have some new light to share on this as well.

**Comment by mikkokam** [comment]
By default, no 300ms delay at least this way:
* Chrome 32+ on Android with width=device-width in the viewport meta tag.
* Chrome on Android (all versions) with user-scalable=no in the viewport meta tag. 

Libraries like Ionic, Angular Material etc. take care of this for the users by default on all mobile browsers, without them I've used fastclick in the past. Hoping MDL takes care of this by default, too - so no need for fastclick et al.

**Comment by paulirish** [comment]
fastclick isn't necessary any longer: http://developer.telerik.com/featured/300-ms-click-delay-ios-8/

**Comment by Garbee** [comment]
Fantastic, thanks for the update Paul!

Looks like our action here is to:

* Add touch-action rules via reset sheet.
* Make sure we instruct people that meta viewport is needed (since it should be there anyways but...)

**Comment by Garbee** [comment]
Both actions here have been completed. Touch action will be present with the next patch release in the mainstream builds.

**Comment by rj33** [comment]
My reading of Paul's link reaches a different conclusion, and that is that the 300ms click delay on iOS8 is still an issue , and MDL is still going to feel slugish on IOS8 under several situations, the  most important being:
1) If clicking quickly and
2) If using the page from a home screen web app.

The other checks seem to resolve this for all non-IOS cases, but IOS is still a pretty big case, and personally I think this should be re-opened.
