### ISSUE TITLE
Advice on using the Sass version

### ISSUE THREAD

**Issue by callumlocke** [google/material-design-lite#894]
The website [says this](http://www.getmdl.io/faq/index.html#options-available):

> **Sass:** If you would prefer to go all in, you can get the Sass version of MDL, which includes our original sources, docs and templates. This version allows maximum customisation using CSS variables and the rest of the Sass goodness you’re used to.

Could you expand on this? In particular:

- Looks like there's no Sass in the bower package – what's the best approach if I want to use a package manager?
- Does using the Sass directly mean I can just mix MDL styles into my own classes (and completely avoid using `mdl-*` classes in my markup), or does it only mean that I can change variables like colors and fonts? From looking through this repo it looks like the answer might be "it depends which parts you're using", but I'm not too sure..

**Comment by Garbee** [comment]
> no Sass in bower (and npm)

We are working on addressing this. Issue #793 

> Does using the Sass directly mean I can just mix MDL styles into my own classes (and completely avoid using mdl-* classes in my markup), or does it only mean that I can change variables like colors and fonts?

Full Sass power. You can call stuff into your own classes if you wish. Just remember, JS stuff always needs `mdl-js-component` by default unless you re-register with your own classname.

**Comment by sgomes** [comment]
This should be fixed, as we now package the sources in npm and bower.

**Comment by Download** [comment]
This issue is the third result for `'mdl sass'` in Google. At number one is the FAQ and at number two is a page from another project that actually seems to contain a little bit more info on how to set it up. If there are any more docs on how to use MDL with SASS, a link to it from this thread would be very helpful.

**Comment by sgomes** [comment]
@Download That's one area where our documentation is lacking, completely agree.

We're working hard on making sure that Sass documentation is well covered in v2, but in the meantime we're happy to review any PRs for improved Sass docs for v1, and we're also happy to help anyone working on those docs with figuring things out.

**Comment by Download** [comment]
> That's one area where our documentation is lacking

Well, at least it's good to know that it just doesn't exist, so we can stop searching for it  :)
Thanks for your reply!
