### ISSUE TITLE
Test the component handler itself

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#899]
We should introduce unit tests for the component handler itself. Checking to make sure any functions exposed continue to operate as expected.

**Comment by addyosmani** [comment]
Is this handled as of #922?

**Comment by Garbee** [comment]
Not fully, I think some methods still need to be tested. I'll check into it when I get the chance.

**Comment by Garbee** [comment]
The only thing left to do here is test and fix downgrading an element that has multiple components bound. Say `mdl-js-button` and `mdl-js-ripple-effect` on a single given element. This currently is in a broken state where only one thing is getting downgraded at a time.
