### ISSUE TITLE
Bad positioning of tooltips

### ISSUE THREAD

**Issue by brandonjpierce** [google/material-design-lite#900]
More of an edge case but nonetheless happening in an app I am currently developing. This scenario only happens if a scroll bar is present and the element in question has a translate applied via CSS.

[See example here](https://jsfiddle.net/ag06mxes/1/) (hover over red box)

Something like this would theoretically fix the issue (I think)

```javascript
let rect = el.getBoundingClientRect();
let left = rect.left + window.pageXOffset;
let top = rect.top + window.pageYOffset;

// now we have a more accurate representation of the current top / left coords
```

**Comment by Garbee** [comment]
Interesting bug. I can confirm it is happening due to the transform, but I don't understand *why*. This should be addressed since it could be a pretty common thing being done now with the recent push for animations by the web.

**Comment by surma** [comment]
TIL!

The observed behavior is correct as per [CSS spec](http://www.w3.org/TR/css3-transforms/#issue-ca2c412c):

> For elements whose layout is governed by the CSS box model, any value other than none for the transform results in the creation of both a stacking context and a containing block. The object acts as a containing block for fixed positioned descendants.

Our tooltips are positioned using `position: fixed`. That means, by applying a transform – even if it is a NOP – you moved the origin for fixed positioning.

The [easy fix](https://jsfiddle.net/ag06mxes/2/) is to move the tooltip to another container (or `body`).

**Comment by Garbee** [comment]
Hm, very interesting. At least we know now and can point people here if it comes up again. Thanks for doing the research @surma!
