### ISSUE TITLE
Navigation drawer becomes permanent at too narrow a width

### ISSUE THREAD

**Issue by patrick-jones** [google/material-design-lite#902]
The navigation drawer currently becomes permanent at screen width 851px.  Accoring to [the spec](http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior), permanent navigation drawers are recommended for desktop only.  The temporary nav drawer behavior is recommended for tablet.

I can't find in the spec where they are explicit about the break point between tablet and desktop, but [this table](http://www.google.com/design/spec/layout/adaptive-ui.html#adaptive-ui-breakpoints) implies that the smallest width that could be considered "desktop" is 1024px.  Realistically, most modern laptops have at least a 1440px wide screen, which corresponds to the "large" screen breakpoint in the spec.

I suggest that the navigation drawer should not become permanent until the screen reaches the "large" (1440px) breakpoint.

**Comment by Garbee** [comment]
`1280px` is large according to the [structure specification](https://www.google.com/design/spec/layout/adaptive-ui.html#adaptive-ui-patterns). This very well could be from when Layout was built before the grid system and the adaptive UI spec being released.

At this point, we do have some minor BC concerns...
