### ISSUE TITLE
Naming and future of the library

### ISSUE THREAD

**Issue by rogovdm** [google/material-design-lite#904]
I'm a bit puzzled about «lite» part in the naming of the library. And I want to close the question before using it in my projects.

How far is it planned to develop this library? Is it planned to cover all components, which we can see in other libraries? Any «complex» components that are no-so-light? Such as datepicker, adbanced animations etc. Eventually, can we find in this project all components like in Bootstrap?

Thanks a lot.

**Comment by Garbee** [comment]
Check our [FAQ](http://getmdl.io/faq/index.html) and the [release post](https://medium.com/google-developers/introducing-material-design-lite-3ce67098c031). It should cover most of the questions raised. If they don't, then let us know please.
