### ISSUE TITLE
Nav drawer (menu) icon is cut in half; icon font weirdness if you have icon font installed on your machine

### ISSUE THREAD

**Issue by romannurik** [google/material-design-lite#905]
This seems to be affecting several of the demos and the customizer tool. In this screenshot:

![image](https://cloud.githubusercontent.com/assets/100155/8583666/7722789e-259d-11e5-8e41-af73d8c6896b.png)

The menu icon is cut in half.

If you add this CSS to the page as a test:

```
.mdl-layout__drawer-button i {
  position: relative;
  left: -20px;
}
```

you'll see the full icon as it was intended to be shown:

![image](https://cloud.githubusercontent.com/assets/100155/8583703/c03be646-259d-11e5-8683-3361a622db50.png)

**Comment by Garbee** [comment]
I'm unable to replicate this with the customizer or any templates.

What kind of system are you seeing this on? Have you tested in a clean browser profile (no extensions) to make sure they aren't conflicting? Any device using Device Mode in the Chrome DevTools able to consistently replicate this for you?

**Comment by innerpeace0** [comment]
Mine stayed full size no matter how small I shrunk the window.

**Comment by romannurik** [comment]
Oh interesting. I'll experiment shortly and reply back. I'm seeing this on Chrome/Mac (don't have versions readily available)

**Comment by addyosmani** [comment]
@romannurik should you share what version of Chrome you're seeing this on? I'd test using my walkthrough in https://developer.chrome.com/devtools/docs/clean-testing-environment to make sure there aren't any extensions impacting how this renders.

**Comment by romannurik** [comment]
Version 43.0.2357.132. Will test w/ extensions off.

**Comment by romannurik** [comment]
BTW, I think it has something to do with the icon font, specifically ligatures and text measurement perhaps ![image](https://cloud.githubusercontent.com/assets/100155/8596030/dc733fd0-261a-11e5-888b-f62b68de6283.png)

**Comment by surma** [comment]
I feel like you might be on to something, then again you are the only one so far with that issue. Keep us posted, very interesting.

**Comment by romannurik** [comment]
OK, I had the [icon font TTF](https://fonts.gstatic.com/s/materialicons/v7/2fcrYFNaTjcS6g4U3t-Y5bbKic1PW3nceB3q24YFOMg.ttf) installed. Uninstalling it fixed the problem.

Note that not all icons are affected, per the two screenshots.

Bad:

![image](https://cloud.githubusercontent.com/assets/100155/8596169/96b9299a-261b-11e5-88cb-15244d5feda5.png)

Good:

![image](https://cloud.githubusercontent.com/assets/100155/8596172/9f40b07e-261b-11e5-8bc5-30b97ee243d7.png)

**Comment by Garbee** [comment]
Just installed the same TTF on my machine (Linux) and it isn't causing a problem. Maybe platform-dependent?

**Comment by romannurik** [comment]
Possibly... I'm on a Mac (Yosemite, 10.10.4). Also note it doesn't affect Safari; only Chrome.

**Comment by romannurik** [comment]
I think the solution might be for Google Fonts to remove `local('Material Icons'), local('MaterialIcons-Regular')` from the `@font-face` src… doesn't seem like a great idea for local system fonts to start messing with site iconography.

**Comment by romannurik** [comment]
This seems to be fixed in latest releases?

**Comment by surma** [comment]
Right! Thanks for reminding us! I Either the font fixed it upstream or we pulled in the necessary CSS into MDL. Don’t quite remember. But closing this :)
