### ISSUE TITLE
FAQ is not clear to what extent MDL replaces Bootstrap

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#912]
The FAQ states that MDL does not replace all features of Bootstrap, but it's not clear if MDL can replace Bootstrap for a minimal website, or not. For example, does MDL come with css reset?

Can people start developing a website with MDL css only, or are they supposed to provide the boilerplate by themselves? For example, does http://www.getmdl.io/assets/main.css contain only MDL-website-specific styles, or does it also include the boilerplate code?

**Comment by addyosmani** [comment]
Good questions. I'll get something written up in the FAQ about this.

**Comment by kelsmj** [comment]
I am currently experimenting with replacing Bootstrap with MDL, and I found I did have to include a css reset, in order to get the results I wanted.

**Comment by surma** [comment]
We do include a [reset](https://github.com/google/material-design-lite/tree/121ba91552277cd5959e52a96eb86c370177ceea/src/resets), but maybe it’s not sufficient for your use-case? What were you missing, @kelsmj?

**Comment by Garbee** [comment]
@addyosmani I'd be weary of adding a feature comparison anywhere within our stuff. That then gives the appears there is some direct competition with Bootstrap and we have checkboxes to fill over time.

If a comparison is done, please try to make it clear that it isn't a roadmap of missing features that will be added later, but purely for informational purposes. People should check this issue tracker for approved future additions.

**Comment by jimbojetlag** [comment]
Could someone clarify whether MDL is intended to be enough for the minimal css needs of a web app or not?

The [styles documentation](http://www.getmdl.io/styles/index.html) is incomplete, only covering typography, icon an color.

For instance, almost any web app these days will sooner or later need inline list:

1. Is it already covered by MDL? If so, where is the documentation?
2. It is something that MDL might cover in the future and I have to wait. In this case, I'd probably not call MDL to be at a state to be released as version 1.0.0.
3. MDL will never cover this feature, and I have to make my own style for inline list. In this case, MDL is missing an essential feature and I have to provide it myself for every app I build, or use an external framework, which would add an extra overhead (and many duplications).

**Comment by surma** [comment]
Hey @jimbojetlag. The issues you raise are valid and are actually being addressed:

* Incomplete styles documentation: See #772. TL;DR: We will probably remove the typography section as it is, as you say, only a fraction of what has to be covered and we don’t want to be a copy of the Material Design specification.
* Lists: #854 #857 both these issues have been marked as future which means they are in the MD spec and *will* be implemented. 

> Is MDL intended to be enough for the minimal css needs of a web app

My immediate reaction is: yes. 
You will still need styling of your own, of course. MDL should be completely sufficient to get the MD look'n'feel rolling across screen sizes and OSes.

**Comment by Garbee** [comment]
Also for lists, issue #584 for the MD list component itself.

On the note of "sooner or later needing inline lists", if you are referring to a class that styles an unordered list inline by changing the display type, then things that small are slightly out-of-scope.

MDL is not a full framework to handle every little need. It is a selection of components within Material Design implemented for the web. This helps bring Material Design to the wider web and helps the specification authors understand new needs that should be addressed in the specification (and fix existing issues.)

Some work is required to implement a Material Design site. If you find yourself using common patterns often, you should make a package (or find another that has them?) to use between projects to not repeat yourself as much.

**Comment by innerpeace0** [comment]
> We will probably remove the typography section as it is, as you say, only a fraction of what has to be covered and we don’t want to be a copy of the Material Design specification.

It appears that MDL has taken MD and specified certain typography styles for some html tags. This, to me, was a missing piece of MD and the MDL implementation for h1-h6 looks great. Rather than throw out that info from the docs, please consider, at the very least, a cross reference chart for all typography. (I wouldn't be surprised if they look great, too.) There is already redundancy in some other components in the docs. That's fine.

**Comment by sgomes** [comment]
Folks should already be familiar with MDL that this isn't too much of a concern. v2 will move us closer to a solid implementation of Material Design on the web, so it should make this clearer.
