### ISSUE TITLE
Performance of microsite

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#918]
[Pagespeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=getmdl.io&tab=mobile) isn't liking us too much. Most of the speed problems should be pretty easy to address (move JS to bottom. Only GA should be in the `<head>` so it can verify the site in Webmaster Tools if that is how it is configured.)

Let's try to get these issues addressed in the coming weeks.

**Comment by addyosmani** [comment]
Although it doesn't shave off too much on the homepage, we should definitely be minifying HTML. There are also a number of assets shipped down the line which we're not minifying. Caught this in #546, but would like to tackle it soon:

```
    <!-- Material Design Lite -->
    <script src="./material.min.js"></script>
    <!-- Add Copy-to-CodePen buttons to code blocks -->
    <script src="./assets/codepen.js"></script>
    <!-- Enable Prism syntax highlighting -->
    <script src="./assets/prism.js"></script>
    <script src="./assets/prism-markup.min.js"></script>
    <script src="./assets/prism-javascript.min.js"></script>
    <script src="./assets/prism-css.min.js"></script>
    <script src="./assets/prism-bash.min.js"></script>
    <script src="./assets/main.js"></script>
    <!-- Built with love using Material Design Lite -->
```

**Comment by addyosmani** [comment]
I think we can tackle this in phases. First phrase: basic optimisations/minification. We can then look at whether critical-path CSS is an option for this site.

**Comment by surma** [comment]
I agree. We got some low-hanging fruit here. I will take this on.

**Comment by sgomes** [comment]
To be completely rewritten in v2. Not feasible to fully fix until then, but happy to accept any PRs for low-hanging fruit. Please submit against the `mdl-1.x` branch.
