### ISSUE TITLE
[Component request] Dialog

### ISSUE THREAD

**Issue by rafaelguinho** [google/material-design-lite#919]
Some component of dialog will be made available ?

**Comment by Garbee** [comment]
Issue #781

**Comment by JdidouBrahim** [comment]
it's the dialog compoment is  compatible with firefox ?

**Comment by hebbet** [comment]
@JdidouBrahim for support questions please use stackoverflow

**Comment by JdidouBrahim** [comment]
@hebbet  Thank you  :)
