### ISSUE TITLE
100% width table makes the first th align right so the check boxes don't line up.

### ISSUE THREAD

**Issue by titlescreen** [google/material-design-lite#923]
Not sure if you are after stuff like this or you would consider it an issue but... 100% width table makes the first th align right so the check boxes don't line up. 

Fix
.mdl-data-table th:first-of-type {
            text-align:left;
        }

**Comment by apollo13** [comment]
That alone just fixes the checkboxes for me, but the first th is still longer than required for the checkbox: http://imgur.com/NOg3IZk

**Comment by djalmaaraujo** [comment]
+1

But, if you set the width of the first th/td, it will work as expected. For example, 
```css
.mdl-data-table th:first-of-type {
  text-align:left;
  width: 40px;
}
```

I don't know if this should be the default, but it works as expected.

**Comment by cthielen** [comment]
I can confirm @djalmaaraujo 's fix works for me.

**Comment by sgomes** [comment]
Thanks for the issue!

I went with a different approach for the fix, by making the header checkbox position absolute as well. See #1409.

**Comment by tleunen** [comment]
Why are they in absolute position?

**Comment by sgomes** [comment]
@tleunen To match the behaviour of the other checkboxes: staying at a fixed position regardless of available horizontal (and now vertical) space.

**Comment by rhroyston** [comment]
In fact, several th elements, for example those including only an MDL icon align funky in this case.  The fix is very simple.

```
.mdl-data-table th{
  text-align: left !important;
}
```
