### ISSUE TITLE
Tool tip alignment in Drawers

### ISSUE THREAD

**Issue by titlescreen** [google/material-design-lite#924]
Adding tooltips to a scrollable drawer, show the tool tip at the elements pre scrolled position. Also it can run off the left of the screen. Any chance we can get some way to position it, e.g. open bottom left, or can it work out if its off the window and nudge itself over?

![image](https://cloud.githubusercontent.com/assets/13239597/8599998/6d75aca8-265b-11e5-83e1-09ce6103a5d5.png)

**Comment by addyosmani** [comment]
Are you trying to use the tooltip with either the layout component or one of our existing templates? If not, could you share a snippet of the type of structure (assume it's a typical UI/LI drawer) you're using it on?

I personally wouldn't be opposed to us introducing positioning utilities, however we might want to figure out whether these should be specific to tooltips or should also be made available to other components such as badges.

**Comment by Garbee** [comment]
"Run off left of screen" may be fixed with PR #839 being accepted. 

Positioning... are we using transforms here? Could be related to issue #900.

**Comment by addyosmani** [comment]
https://github.com/google/material-design-lite/pull/839 has now landed.

**Comment by dflorey** [comment]
I'm still getting tooltips running off left of screen:

http://codepen.io/anon/pen/bdjbOx

**Comment by surma** [comment]
@dflorey And you will until we release v1.0.1 and you updated your import paths. Hopefully, we’ll push a new version this week (no promises, though).

**Comment by sgomes** [comment]
Drawers will be reimplemented in v2 as part of the layout rewrite. Not feasible to fix until then.
