### ISSUE TITLE
iOS Page Scrolling

### ISSUE THREAD

**Issue by Andy561** [google/material-design-lite#925]
This is a little difficult to explain, I have a page with table, that can get pretty long depending on what the server returns, scrolling down that page on an iOS device is really bad. Android seems to be working fine but iOS scrolling is very choppy and unresponsive.

**Comment by Garbee** [comment]
Could be caused from not having flicky scrolling?

@surma could the solution for the microsite in #730 fix this kind of problem? If so maybe consider moving upstream since it doesn't seem to be a BC break...

**Comment by surma** [comment]
This is most definitely related to #730. @Andy561 You can either look at #730 and copy the style additions yourself or wait for 1.0.1 which should be out in the next few days.

**Comment by addyosmani** [comment]
@surma Assigned to you for now so we can verify if the fix in #730 addresses this for OP.

**Comment by jimbojetlag** [comment]
Not sure if related to this issue, but scrolling the components page on getmdl.io on chrome iOS is awful. When the components bar is horizontal, and it's supposed to be sticky, it moves while scrolling, takes a long time to recalculate its position, and then it jumps back to up.

**Comment by surma** [comment]
@jimbojetlag Would you mind opening a separate issue for that? I thought I fixed that, but maybe iOS’s Chrome behaves differently.

**Comment by jimbojetlag** [comment]
@surma sure, #939 .

**Comment by surma** [comment]
@Andy561 I am closing this issue as I haven’t heard back and will be fixing #939. If this problem persists (even with my [suggestion in the previous comment](https://github.com/google/material-design-lite/issues/925#issuecomment-120110442)), feel free to re-open.
