### ISSUE TITLE
print media looks odd/ is unsupported?

### ISSUE THREAD

**Issue by jrabbit** [google/material-design-lite#926]
I'm writing effectively an enhanced to-do list application with polymer elements which don't support print media, and got excited that these might offer a way to get good print results while keeping a material style.
Example print view: (from dashboard example template) note missing content
![screenshot from 2015-07-07 18-37-52](https://cloud.githubusercontent.com/assets/178803/8604752/913b951a-264e-11e5-8bc6-9b40157a31fe.png)

To reproduce try to print any mdl page.

**Comment by Garbee** [comment]
Yea, we didn't handle print styles at all. No specification aid for how things get handled there and not enough time/manpower to figure it out.

It is something we can work on in the future perhaps.

**Comment by adcoolguy** [comment]
Can someone kindly unsubscribe me? Thanks!

**Comment by Garbee** [comment]
@adcoolguy We can't do that. Only you can using the GH UI. You probably clicked the "watch" button for the project, so just unwatch it (located to the left of where you star a project.)

**Comment by innerpeace0** [comment]
> Yea, we didn't handle print styles at all.

It might be helpful to have that mentioned clearly in the docs somewhere.

**Comment by steamonimo** [comment]
I just ran into weird printing issues myself. It is a bit sad that there was no hint at the missing print support in the mdl documentation. Because of the missing print support I do think that a version number like 0.8.x would be more justified for the library.

**Comment by Garbee** [comment]
Material Design itself offers no guidance on print views. A stable 1.0 tag was and is not a sign that absolutely everything possible has been done. It is simply saying what we do have and offer is good enough to be used without worry of things breaking (sorry, regressions do happen and we try to fix them ASAP.)

**Comment by sgomes** [comment]
We'll stop providing global resets/styles with v2, including print styles. This should be left up to developers rather than provided by the library.

**Comment by SimonBiggs** [comment]
If others find this by google I was able to fix this using:

```css
@media print {
  body {
    -webkit-print-color-adjust: exact;
    color-adjust: exact;
  }
}
```
