### ISSUE TITLE
Toggling a radio button or toggle switch to disabled via javascript is not graphically reflected

### ISSUE THREAD

**Issue by mfonville** [google/material-design-lite#927]
Not sure if this might already be fixed in the master branch, but when making a radio button or a toggle switch to be disabled, the change is not reflected graphically, only in functionality.

Somebody else also already experienced this bug: http://stackoverflow.com/questions/31322380/disabling-material-design-lite-toggle-switch

With the radio buttons I can add, that only when selects another radio button from the same 'group', the updated disabled state is at that point (but thus too late) graphically shown.

**Comment by surma** [comment]
We might have a similar issue here like #908 fixed. Thanks for reporting, we’ll look into it.

**Comment by Emil113** [comment]
I posted about this on StackOverlow yesterday thinking it's something I'm doing... more info here with JSFidle and video example: http://stackoverflow.com/questions/31322380/disabling-material-design-lite-toggle-switch

**Comment by Garbee** [comment]
@surma That is unrelated.

Here, we don't toggle views based on `[disabled]`. It is done via the `is-disabled` class which is only triggered via JS. I'd need to dig into the JS more to tell if we can do a simple style addition (`is-disabled,[disabled]`) to fix this in a BC way.

What's odd is, currently the only way to "disable" via JS is calling the widget against the element. However widget functionality for radio and checkbox are never exposed.

**Comment by HenriqueLimas** [comment]
Just linking the @Garbee answer in the [stackoverflow question](http://stackoverflow.com/a/31373882/3937750) and relating the #1013 PR that he does.

In the example mentioned in the answer we are querying the ```input``` element like this:
```javascript
document.querySelector('#my-checkbox').MaterialCheckbox.disable()
```
But, we need to query the ```label``` and not the ```input[type=checkbox]```. 
Maybe, we can query input and use something like this 
```javascript
document.querySelector('#my-checkbox').parentElement.MaterialCheckbox.disable()
```

With that implementation its working, but IMO it's strange that we need to access the ```parenteElement```.

**Comment by Garbee** [comment]
@HenriqueLimas Just think of it as "The widget is assigned to where I define the JS class, not the input itself."

**Comment by HenriqueLimas** [comment]
Yeah, it makes sense, Thanks. And I know you just make an example. Maybe we can close this issue.

**Comment by Garbee** [comment]
I'm going to allow Surma to review and close as he sees fit. He may see something actionable here that I don't.

**Comment by surma** [comment]
Definitely see the issue here. I am thinking whether we should add some very lightweight JS to the checkbox to make the widget accessible via the `<input>` as well.

Let me pull in @sgomes and @addyosmani ;)

**Comment by Garbee** [comment]
I'm worried about having multiple ways to target things like this. Consistency is best had by just saying "Target where you define the js class to access the widget." Instead of, "That works, except for X components where you can also target the inputs."

**Comment by surma** [comment]
@Garbee Now that you say that, I agree. Classes should be the way to address *the widget*. So is this a wont-fix?

**Comment by Garbee** [comment]
Well, this is actually "fixed" since the component is forced as a widget in 1.0.1 which allows for developers to update the checkbox dynamically. Before the widget check was failing somehow causing it to not be added, so there was no way to access `disable()` and other public methods for the MaterialCheckbox component. ;)

We can't fix it the way requested, since that means adding in observers and/or other polyfills which is not happening.

**Comment by mfonville** [comment]
I am not sure if it i something broken in my code, but on 1.0.1 I cannot toggle the disable state on MaterialRadio.

**Comment by Garbee** [comment]
@mfonville Please use StackOverflow for support. Disabling works as expected in 1.0.1.

**Comment by mfonville** [comment]
@Garbee Thank you for confirming that it works on 1.0.1, I will try to find the error in my code then :-)
