### ISSUE TITLE
Issue with mdl-data-table--selectable. Checking/uncheking body checkboxes should change the header checkbox

### ISSUE THREAD

**Issue by yuyokk** [google/material-design-lite#932]
Hi guys,

I was playing with selectable tables http://www.getmdl.io/components/index.html#tables-section
and I think that the current functionality can be slightly improved in the following ways:

- if you check all the body checkboxes, the header checkbox should be checked automatically
- if you have a header and body checkboxes checked and then you uncheck one of the body checkboxes, the header checkbox should be uncheked as well

**Comment by surma** [comment]
I agree with your sentiment. We’ll need input from the MD team, though. The spec doesn’t say how this is supposed to behave.

**Comment by Garbee** [comment]
I noticed this a while back. I'm pretty sure we don't need MD Guidance for putting this in. It is only a logical application of selectors. My main concern is with making sure we don't enter an infinite loop. I played with the code to implement it but got stuck in those too much; so I trashed it and moved on to more important things.

**Comment by addyosmani** [comment]
> I noticed this a while back. I'm pretty sure we don't need MD Guidance for putting this in. It is only a logical application of selectors

Imo this is fine and we can ask for feedback in the mean time.

**Comment by sgomes** [comment]
I believe the described behaviour is the current behaviour. Please reopen if not.

**Comment by PazerOP** [comment]
This is definitely not the current behavior. The header checkbox is completely independent of the row checkboxes: http://pazer.us/s/22.mp4
