### ISSUE TITLE
Inputs are not styled in dowload package

### ISSUE THREAD

**Issue by kowdermeister** [google/material-design-lite#941]
Sliders, checkboxes are not styled when I use the downloadable package from http://www.getmdl.io/started/index.html

**Comment by Garbee** [comment]
Can you provide an example of the markup you are using? It works on the
site so if you follow the setup instructions it should work just fine.

**Comment by surma** [comment]
@kowdermeister I can’t reproduce either. Just downloaded our package and tested with the following file in the same directory:

```html
<!doctype html>
<html>
<head>
  <link rel="stylesheet" href="/material.min.css" />
</head>
<body>
  <label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect" for="checkbox-1">
    <input type="checkbox" id="checkbox-1" class="mdl-checkbox__input" checked />
    <span class="mdl-checkbox__label">Checkbox</span>
  </label>

  <script src="/material.min.js"></script>
</body>
</html>
```

**Comment by kowdermeister** [comment]
Sorry, misfire. I didn't include the JS. 
Why is it depending on it?

**Comment by surma** [comment]
It’s mostly setup code. We need to create a couple of additional elements to accommodate for the ripple, the 2 SVGs (checkbox and checkmark) etc. See [code](https://github.com/google/material-design-lite/blob/master/src/checkbox/checkbox.js#L194-L242). You could create those yourself to get rid of the JS if you wanted to.

Closing this for now. Feel free to re-open if you keep running into issues.
