### ISSUE TITLE
Blog template issue - point the css to CDN

### ISSUE THREAD

**Issue by sujithgokul** [google/material-design-lite#946]
The blog template is not displaying properly since the material.min.css reference is wrong

**Comment by Garbee** [comment]
The [blog template](http://www.getmdl.io/templates/blog/index.html) is rendering fine here. What errors are you getting from your console about the network request?

**Comment by sujithgokul** [comment]
net::ERR_FILE_NOT_FOUND on material.min.css"

**Comment by surma** [comment]
@sujithgokul Do you mean after downloading the template zip file? Or do you mean our live version on getmdl.io?

**Comment by sujithgokul** [comment]
In the source, template folder. Not in getmdl.io

Regards,
Sujith

**Comment by Garbee** [comment]
If you are opening it without running your own server (from the project root, i.e. via `gulp serve`) then that could cause the file not found error. You can tell if you aren't running a server since you will see `file://` instead of `http://` in the URL of your browser. Is this the case?

**Comment by sujithgokul** [comment]
Okay. I didn't use ``` gulp ```. I recently upgraded to El Capitan beta and my machine is a mess. Will fix it and try. Thanks for your help
