### ISSUE TITLE
Menu positioned to a wrong place with "mdl-menu--top-left"

### ISSUE THREAD

**Issue by kowdermeister** [google/material-design-lite#948]
Click the vertical dots next to the select button.
http://codepen.io/kowdermeister/pen/eNrMQe

The menu opens at the bottom at the page and I'd expect it above the icon.

Remove `mdl-menu--top-left` and it's appearing correctly next to the icon.

**Comment by surma** [comment]
Hey @kowdermeister.

Thanks for providing a codepen straight up. Nice!

First of all: I fixed it for you: http://codepen.io/anon/pen/jPxxVG
Secondly: You basically found a bug in our documentation. The common parent of the button and the menu needs to be `position: relative` (or, more correctly, anything but `position: static`).

I’ll be closing this and open up a new issue to fix either the documentation or the way we do positioning.
