### ISSUE TITLE
Author guide to customisation

### ISSUE THREAD

**Issue by addyosmani** [google/material-design-lite#95]
Goal: provide users with the basic knowledge needed to theme MDL and use our Sass to create a custom build of the project.
- [ ] Where can I find the source files for CSS/JS? (ans: /src)
- [ ] How do I install the dependencies needed to build them? (ans: readme)
- [ ] What does the workflow look like? (edit/live-reload)
- [ ] How can I customise the MDL theme? What variables need changing? (maybe walk through customising a button)
- [ ] How should I build/use my changed MDL setup? (ans: `gulp`, reference material.min.css/material.min.js or just copy them to your new project)

**Comment by clementmas** [comment]
I'm glad I can finally install MDL with npm and use Sass to override the color variables.

I just thought I would be able to override the variables with hexadecimal colors (eg. #2196F3) but instead I need to use rgb (eg. "33,150,243").

I don't suggest you change your whole structure but I think it would be a good idea to add some information on the Wiki as to which format is expected :

- https://github.com/google/material-design-lite/wiki/Customizing-Colors

**Comment by sgomes** [comment]
Marking this as "V2 Post Release", as it's not essential to have customisation documentation for launch.

**Comment by Garbee** [comment]
De-assigning from myself due to a new project taking my time. Developing good customization docs is very time-consuming and when we get around to this I'm not sure how much time I'll have to put towards it.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/65
