### ISSUE TITLE
Documentation: language translations

### ISSUE THREAD

**Issue by choyiny** [google/material-design-lite#951]
Adding more languages to accomodate a wider user base, not only english.

**Comment by Garbee** [comment]
I think unless we have community members willing to contribute (and stay on top of) translations then this may be unfeasible. Let's see what happens!

**Comment by surma** [comment]
I think @hkminegod is right that we should provide translations. However, IMO it is too early just yet for MDL:

* We don’t have enough man-power (and language diversity) on the core team to maintain multiple languages. If the translations are not maintained by the core team this early in a project, they will most likely diverge, as MDL will change a lot.
* Our current build system for the website does have a weird HTML / Markdown mixture. Having external people maintain a language is even more error prone as they are not working on pure text content and could effectively break the website.

**Comment by hkminegod** [comment]
keep me updated as I can help with translations for Chinese and French. I'm pretty familiar with HtML and markdown as well.

**Comment by surma** [comment]
@hkminegod Cool! Thanks for offering your help. We’ll keep that in mind :)

**Comment by sgomes** [comment]
Documentation will be rewritten and redesigned for v2.

**Comment by sfdexter** [comment]
Superceded by https://github.com/material-components/material-components-web/issues/62
