### ISSUE TITLE
Menu position

### ISSUE THREAD

**Issue by surma** [google/material-design-lite#952]
@kowdermeister ran into issues with our menu in #948.

Internally, we knew that menus need a `position: relative` parent, but for some reason that didn’t make it into the documentation. We should fix that.

Alternatively, we could also change the way menus are positioned and take the same approach as tooltips and use fixed positioning. WDYT?

**Comment by addyosmani** [comment]
I think if we're going  to change the way menus are positioned, that may have to wait for 1.1. Would landing docs about the `position: relative` requirement be feasible for 1.0.x?
