### ISSUE TITLE
Nav Menu & Drawer are not showing up

### ISSUE THREAD

**Issue by skaxwng** [google/material-design-lite#953]
I tried the code on the website. It doesn't work. The menu button and drawer are not showing up. 

![image](https://cloud.githubusercontent.com/assets/9153498/8626704/aa728f58-270b-11e5-916d-aa7ce9e32e67.png)

**Comment by surma** [comment]
Hey @skaxwng. Sorry to hear things are not working out-of-the-box. Can you provide a link to a codepen which reproduces that problem for you?

**Comment by skaxwng** [comment]
Hey @surma , i got it fixed now. It's got something to do with Meteor and I needed to add componentHandler.upgradeAllRegistered(); to make it work.

**Comment by JohnAReid** [comment]
@skaxwng Could you give an example of how to add componentHandler.upgradeAllRegistered();  as I am using meteor and have the same problem - and when I add the above line I get the following:
Uncaught ReferenceError: componentHandler is not defined
