### ISSUE TITLE
Wrong tab underline animation

### ISSUE THREAD

**Issue by filippomartini** [google/material-design-lite#954]
The animation of the tab isn't fluid. Please fix it :)
Thanks

**Comment by Garbee** [comment]
I'm not exactly sure our implementation is outright incorrect. The [spec itself](https://www.google.com/design/spec/components/tabs.html#tabs-specs) says the animation may vary by platform. I suggest we ask the MD team if the animation we have is acceptable or not before rewriting the animation for it.

**Comment by filippomartini** [comment]
I think that this one looks a little bit glitchy! 
The best one would be this one: https://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-sibling-to-sibling

Thanks for evaluating my suggestion :)

**Comment by addyosmani** [comment]
I'll ask the MD team about this next week. Thanks for consulting the spec, both and sorry about the ambiguity.

**Comment by christophwolff** [comment]
any updates on this?

**Comment by surma** [comment]
We’ll actually have to change the implementation of the current tabs thing because the bar is supposed to move from one tab to the next. Using the border (as we are doing now) is therefore not an option. Not an easy change, but at least it’s not a BC.

**Comment by sgomes** [comment]
Tabs will be reimplemented in #4481. Not feasible to fix until then.
