### ISSUE TITLE
MDL RTL Support ( RTL file included )

### ISSUE THREAD

**Issue by ahmadaljazzar** [google/material-design-lite#955]
I'm currently working on RTL support for MDL.

> Note : This project will be updated until MDL adds RTL support to their next major release.

* [ Material Design Lite RTL ](https://github.com/ahmadaljazzar/google-material-design-lite-rtl)

I don't know if you guys thought of how could this be implemented with your major release, so we may contribute.

**Comment by Garbee** [comment]
Let's keep this conversation on the existing issue. That issue is #783

**Comment by innerpeace0** [comment]
Beautiful piece of work. Thank you.
