### ISSUE TITLE
Focus on fixed-header prevents keyboard navigation

### ISSUE THREAD

**Issue by datio** [google/material-design-lite#956]
Reproduce:

* Load http://www.getmdl.io/templates/android-dot-com/index.html

Up/down, PgUp/PgDown or Space will not scroll the ```main.mdl-layout__content``` element when focused on the header or its children.

I was expecting the functionality to be on par with the official android.com website.

**Comment by addyosmani** [comment]
Thanks for the bug report. Our Android.com sample is not meant to be a 1:1 reproduction of the original, but that said, I'll assign this and we'll take a look at whether there are general a11y improvements that can be made to the layout component that would have otherwise helped with this.

**Comment by sgomes** [comment]
Layout will be reimplemented in v2. Not feasible to fix until then.
