### ISSUE TITLE
Dynamically adding content to DOM

### ISSUE THREAD

**Issue by vikasprogrammer** [google/material-design-lite#957]
I am trying to load HTML files via jQuery load() function and add it to the div container.

`$('#content').load(filename);`

However, all the "mdl js" dom elements are not rendering correctly. Is there a way to `upgradeElement` the whole file?

Please advise.

**Comment by Garbee** [comment]
This is being worked on. For the time being just upgradeDom. That will
handle everything.

**Comment by vikasprogrammer** [comment]
thanks, it worked!

**Comment by addyosmani** [comment]
Closing as we appear to have a solution for OP that works for now and the upgradeDOM fixes are in flight.
