### ISSUE TITLE
Textarea label incorrect when setting value via javascript

### ISSUE THREAD

**Issue by dflorey** [google/material-design-lite#959]
When creating an empty textarea and setting the value via script the label is not small above the textarea but still rendered in initial state behind the text.

**Comment by addyosmani** [comment]
Thanks for your bug report. Could you share a little more information to help us repro this?

* Code snippet or runnable sample
* Browser / browser version

**Comment by dflorey** [comment]
http://codepen.io/anon/pen/QbrZdJ

Just tried to reproduce it, but it looks like it is working on my Pixel... I'll try on my PC when I'm back in the office.

**Comment by surma** [comment]
The codepen is working fine for me too. Weird. I’ll close this issue for now, but feel free to re-open if you manage to reproduce it.

**Comment by Garbee** [comment]
This is the same thing as an issue filed the other day about dirty state
not being applied. Nothing we can really do except document the oddity.
