### ISSUE TITLE
Gulp config

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#960]
Cant config gulp to regenerate <code>/components/index.html</code> while editing <code>\*\*/snippets/\*.html</code>. Someone help pls)

**Comment by surma** [comment]
The command you are looking for ist most likely `gulp pages`.

**Comment by kybarg** [comment]
You mean <code>gulp.watch(['src/\*\*/snippets/\*.html'], ['pages', reload]);</code>?

**Comment by surma** [comment]
That would be the corresponding gulp task, yes. But our gulp file is not 100% reliable right now, so it might be useful to run `gulp pages` manually in addition. We are looking to fix that in the days to come.

**Comment by kybarg** [comment]
@surma Would be nice, cause i find it improper to run <code>gulp pages</code> after each code edit)

**Comment by sgomes** [comment]
I believe this has already been fixed.
