### ISSUE TITLE
Compile error with node-sass v3.1.0 or higher.

### ISSUE THREAD

**Issue by roughcoder** [google/material-design-lite#961]
Doubt this is really a material-design-lite issue, more likely a node-sass or libsass but the source files wont compile with the latest version of node (fails on `v3.1.0` and `v3.2.0`).

The bug has been raised with the `node-sass` project but for visibility I have added here as well. 

https://github.com/sass/node-sass/issues/1031

**Comment by addyosmani** [comment]
Thanks for raising this. We've had a few team members run into this issue with the latest builds of node-sass. I believe this might be a dupe of #702. Could you take a look?

**Comment by roughcoder** [comment]
Yep, this would be the same issue, will close and link in the node-sass issue in ticket #702
