### ISSUE TITLE
Halo effect on radio button not centred on button

### ISSUE THREAD

**Issue by Krazitchek** [google/material-design-lite#962]
Hello, the halo effect on radio button click is not centred on the radio button.

Tested on Firefox 39 and Chromium 43.

See screenshot please.
![screenshot](https://cloud.githubusercontent.com/assets/11500208/8633526/5d2f6e3c-2792-11e5-9ff1-9331ced9f035.png)

**Comment by addyosmani** [comment]
Thanks for the bug report. It looks like we could improve the overall centring here, but will need to check this cross-platform too. @sgomes could you take a look?
