### ISSUE TITLE
Icon-button size and ripple effect

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#963]
According to MD specs Icon Buttons (Icon Toggles):
Card actions: 36x36px
Toolbar: 48x48px
Ripple effect size: 40x40px

Not sure about sizes when used in List component.
Secondary list action: 48x48px
Primary: 40x40px or 48x48px with negative margin

Hope it will be helpful.

**Comment by nicolasgarnier** [comment]
Hey @kybarg,

Could you be a bit more clear as to what the issue is precisely? Are you saying the Size of the ripple effect is incorrect in some case?

Thanks a bunch!
