### ISSUE TITLE
Radio and checkbox toggles size

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#964]
Radio toggles are about 40x40px what is right IMHO while Checkbowes are only 36x36px.

**Comment by Garbee** [comment]
Can you point out where you are getting the sizes from in the specification? I'm not seeing them mentioned anywhere on the [selection control](https://www.google.com/design/spec/components/selection-controls.html) page.

**Comment by kybarg** [comment]
@Garbee Dont know exact size, looked at https://www.google.com/design/spec/components/lists.html#lists-specs where checkbox is in the place of avatar whis is 40x40px. The point is  - radio and checkbox controls have different blocks sizes in MDL http://www.getmdl.io/components/index.html#toggles-section. There is a chance I'm mistaken but I suppose they should be the same size.

**Comment by Garbee** [comment]
List design may be its own sizing. I'm not even seeing exactly where checkboxes are placed instead of avatars. There are some squares, but they could be placeholders for icons.

cc @santokii to see if we can get some guidance here without needing to go back to the MD team directly.

**Comment by kybarg** [comment]
![screen](http://s22.postimg.org/4jcohnf8x/124234234234.png)

**Comment by sgomes** [comment]
Radios and checkboxes will be reimplemented as #4477 and #4471. Not feasible to fix until then.
