### ISSUE TITLE
Gulp Serve throws erro

### ISSUE THREAD

**Issue by seanmavley** [google/material-design-lite#965]
I updated my local repo a couple of minutes ago. 

`gulp` runs with success
`gulp serve` throws the error below

![screenshot from 2015-07-11 12 32 47](https://cloud.githubusercontent.com/assets/5289083/8633754/44708dfe-27c9-11e5-9de8-f657d3b33bcc.png)

**Comment by surma** [comment]
`EADDRINUSE` means that you already have something running on port 3000, the port that our dev web server binds to.

**Comment by seanmavley** [comment]
Thanks. Fixed.
