### ISSUE TITLE
Click link on tab

### ISSUE THREAD

**Issue by skaxwng** [google/material-design-lite#966]
Is it possible to do something like this:

    <div class=mdl-layout__tab-bar mdl-js-ripple-effect">
      <a href="/settings/account" class="mdl-layout__tab">Profile</a>
      <a href="/settings/profile" class="mdl-layout__tab">Account</a>
    </div>

I tried doing that and got TypeError: Cannot read property 'classList' of null.

**Comment by Garbee** [comment]
Related to #929.

However, this probably not a proper use-case for tabs. Normal menu navigation should be used instead.

**Comment by nickretallack** [comment]
@garbee no this is a case of mdl-js-ripple-effect not knowing how to deal with tabs.  See [this issue]( https://github.com/google/material-design-lite/issues/1096) for a workaround and possible discussion.

**Comment by Garbee** [comment]
Then there are two errors with the example code, not just the one I honed in on.
