### ISSUE TITLE
Improper BEM namings

### ISSUE THREAD

**Issue by vtambourine** [google/material-design-lite#968]
According to BEM rules, `__` separates element name from the block, and `--` separates modifier name. However, some class names looks very strange. For example, class `mdl-mega-footer--middle-section` should be named `mdl-mega-footer__middle-section`, as well is `mdl-mega-footer--heading` should be `mdl-mega-footer__heading`.

**Comment by Garbee** [comment]
Oops. Anything feasible we can do in 1.x to resolve this? I assume the only thing we could do is have two classes and "deprecate" usage of the modifier pattern in these situations.

Outright changes them isn't feasible due to backwards compatibility.

**Comment by surma** [comment]
We could add the correct classes *in addition* to the incorrect ones until v2. @addyosmani WDYT?

**Comment by addyosmani** [comment]
> We could add the correct classes in addition to the incorrect ones until v2. @addyosmani WDYT?

We need to be very careful with this otherwise people are going to end up with (potentially) a bunch of unnecessary cruft in their class strings. Can we whip up some PRs that show the additional classes we'd be introducing?

**Comment by Garbee** [comment]
Working on the fix now. But, this is essentially duplicating *every* rule in the file. It was all done with improper naming.

**Comment by chibicode** [comment]
:+1:
