### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#969]
I find strange that there are different ripple effect containers for each case (example <code>mdl-menu__item-ripple-container</code>, <code>mdl-button__ripple-container</code>) when "ripple" is standalone component. Why not to use modificators (like <code>mdl-ripple mdl-ripple--button</code>) instead? Cause editing global ripple effect i meet problems with compatibility with other components, so it could be easier if all "ripple" style were in one file according to BEM.
And have a look at https://material.angularjs.org/latest/#/demo/material.components.button. Angular "ripple" is more Material)
Working on this now.

**Comment by sgomes** [comment]
Ripples will be reimplemented in #4467. Not feasible to fix until then.
