### ISSUE TITLE
src / slider / _slider.scss @162: Expected a color

### ISSUE THREAD

**Issue by svenjuhnke** [google/material-design-lite#970]
![_slider scss](https://cloud.githubusercontent.com/assets/9152502/8635190/9dbe6738-2818-11e5-883a-f6d1f8c00a61.PNG)

**Comment by surma** [comment]
Which version of SASS (or node-sass) are you using?

Also, it says “expected a color”, but that’s exactly what comes next (i.e. `$range-color`). Maybe your IDE doesn’t deal well with line breaks? (Just an assumption as nobody else seems to have not encountered that error).

**Comment by svenjuhnke** [comment]
3.4.13

**Comment by svenjuhnke** [comment]
the same without lb
![_slider scss](https://cloud.githubusercontent.com/assets/9152502/8635322/5b2122b6-281e-11e5-891a-03e6532fe493.PNG)

**Comment by svenjuhnke** [comment]
it's probably compass (http://compass-style.org/) in https://github.com/Compass/compass/blob/stable/core/stylesheets/compass/css3/_images.scss
--
great work, guys

**Comment by rriemann** [comment]
I encounter the same issue with sass 3.4.16.

@svenjuhnke , can you please elaborate how you solved the issue?

**Comment by samthor** [comment]
@surma I've noticed this issue too. To be clear, `$range-color` is actually not a color: it's a string (incidentally, I'm honestly gobsmacked that sass/whatever doesn't convert them transparently).

**Comment by rriemann** [comment]
So how are we supposed to solve this issue? Wait for a fix in sass? Is there an intermediate work-around?

**Comment by Garbee** [comment]
Our direct rolling doesn't use Ruby sass nor any extensions to it. Therefore there is no immediate problem in MDL to be fixed. 

This issue seems to be with how other tooling is reacting with MDL's configuration, which we can't possibly try to solve for everything out there.

**Comment by surma** [comment]
@rriemann The workaround is using CSS’ `unquote()`. @samthor kindly provided a fix OOB, which I will give a test-run and merge if appropriate.
