### ISSUE TITLE
Unable to make move icon to left on header

### ISSUE THREAD

**Issue by skaxwng** [google/material-design-lite#971]
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
	  <header class="mdl-layout__header">

	    <div class="mdl-layout__header-row">
              
	      <button class="mdl-button mdl-js-button mdl-button--icon" onclick="history.go(-1);">
		 <i class="material-icons">arrow_back</i>
	      </button>

             
	      <span class="mdl-layout-title">Settings</span>
	    </div>

	    
	    <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
	      <a href="{{pathFor route='home'}}" class="mdl-layout__tab">Profile</a>
	      <a href="{{pathFor route='settings'}}" class="mdl-layout__tab">Account</a>
	    </div>
	  </header>

![image](https://cloud.githubusercontent.com/assets/9153498/8635477/6ba63f20-27e9-11e5-9ff0-9d26d4983e8f.png)

How do I move the arrow to the left?

**Comment by Garbee** [comment]
Support questions should be asked on StackOverflow so the most people can see the responses and find similar problems. You can use the `material-design-lite` tag along with any other applicable tag to get the most responses for help.
