### ISSUE TITLE
Colored raised buttons

### ISSUE THREAD

**Issue by kybarg** [google/material-design-lite#974]
According to [MD specs](https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons)
Raised buttons have different background colors for each state:
```
Normal color: 500 
Hover color: 600 
Pressed color: 700
```
But in [MDL](http://www.getmdl.io/components/index.html#buttons-section) there is only shadow changes in <code>:active</code> state

**Comment by surma** [comment]
That is interesting. Our current SASS setup won’t allow us to actually implement this. That’s something we should tackle when the planned re-org of the SASS files is happening.

**Comment by Garbee** [comment]
We should be able to handle it now... [Add states here](https://github.com/google/material-design-lite/blob/master/src/button/_button.scss#L61-67) just like [here](https://github.com/google/material-design-lite/blob/master/src/button/_button.scss#L89-108). But, "colored and raised" may be problematic...

**Comment by sgomes** [comment]
Buttons to be reimplemented as part of the v2 rewrite.
