### ISSUE TITLE
Icon buttons don't seem to support multi-word icon names

### ISSUE THREAD

**Issue by owencm** [google/material-design-lite#975]
Some of the material icons have multi-word names like "3d rotation", but it seems they don't work with MDL.

For example, try
 
    <i class="material-icons"><i class="material-icons">3d rotation</i></i>

**Comment by f3yisayo** [comment]
No, they do, you just have to replace the space in the name of any icon with an `_`.

Like this: `<i class="material-icons">3d_rotation</i>`

**Comment by Calvein** [comment]
If you go on the [icon list], when you click an icon you can then click the *Icon font* link at the bottom right, you'll have an example with (IE10+) & without the ligature (IE9-).



[icon list]: https://www.google.com/design/icons/

**Comment by owencm** [comment]
You're right. My bad :). Closing as WAI.
