### ISSUE TITLE
Missing docs on how to change slider's style programmatically 

### ISSUE THREAD

**Issue by Calvein** [google/material-design-lite#978]
I have a slider and an input that are related, as in, the slider update the input and the input update the slider. My problem was that the slider's bg wasn't updating when I was changing its value, I kind of didn't expect this to happen because you can't watch a value change but the [doc] didn't say anything about it.
I had to look at the [code] to see what I had to do (or at least what I think I had to do), so I simply did this:

```js
// From this
slider.value = value
// To this
slider.MaterialSlider.change(value)
```

I think that it should be somewhere in the doc, hopefully the code is very easily readable.

[doc]: http://www.getmdl.io/components/index.html#sliders-section 
[code]: https://github.com/google/material-design-lite/blob/master/src/slider/slider.js#L175

**Comment by kowdermeister** [comment]
I run into the same problem. http://codepen.io/kowdermeister/pen/RPJNRw?editors=101
In my case an external controller device changes the slider values.

**Comment by addyosmani** [comment]
>  I kind of didn't expect this to happen because you can't watch a value change but the doc didn't say anything about it.

I agree we should be documenting this. Sorry for the unexpected behaviour here!

**Comment by Garbee** [comment]
Opened issue #1008 to track the changes that should be applied to all docs to address the same problems with all the widgets we offer.

**Comment by dgash** [comment]
Edited slider component's README.md, added note to clarify process for programmatically changing a slider and resolve this issue. IMPORTANT: Edit was done in documentation branch -- needs to be merged into master before staging.

**Comment by surma** [comment]
Thank you, @dgash :)

**Comment by surma** [comment]
Has been merged into master, thanks @dgash :)
