### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by s-a** [google/material-design-lite#980]
Sorry I can not find more informations about this error. Using MDL 1.0.0.  
![image](https://cloud.githubusercontent.com/assets/1270662/8636325/5beafe0e-285c-11e5-97ad-e7aa34be50d2.png)

**Comment by nicolasgarnier** [comment]
Hey @s-a Thanks for the report. Could you provide a way for us to replicate so that we can investigate this issue? For instance is this code available online somewhere? Or better: could you put some code on codepen that replicates the issue.

Thanks!

**Comment by s-a** [comment]
Yes I started from scratch where the error is more clear.
https://github.com/s-a/mdl-test/tree/da27dc8dccaa1f5e01c7ae6d806f2cc7c9601bdc

![image](https://cloud.githubusercontent.com/assets/1270662/8636441/2ab5f6fe-2861-11e5-8653-fbf4f67810a3.png)

![image](https://cloud.githubusercontent.com/assets/1270662/8636447/447410b2-2861-11e5-87e8-1086b314001d.png)


As I am working at an Electron application I' ve testet Google Chrome environment only. So I do not need any polyfills here right?

**Comment by s-a** [comment]
Just figured out that the error does not occur when I remove class ```mdl-data-table--selectable``` from  ```table``` with CSS class ```mdl-data-table```

**Comment by Garbee** [comment]
Related to issue #984. This is because it is trying to make the rows selectable on load, but none exist since they are dynamically loaded.

**Comment by rubensq74** [comment]
So how do you create Dynamic Elements for them to be part of the DOM so they can be queried?
