### ISSUE TITLE
Badge z-index

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [google/material-design-lite#985]
How can I solve this?
![screenshot from 2015-07-12 05 36 12](https://cloud.githubusercontent.com/assets/12840136/8637120/42d42fca-2858-11e5-8188-4dc42f0818cf.png)
Thanks

**Comment by kybarg** [comment]
It is not z-index issue. Just <code>.mdl-tabs__tab</code> has <code>overflow: hidden;</code>.
Try to write in your css file
```
.mdl-tabs__tab {
    overflow: auto;
}
```
But I don't know if it is gonna break tabs layout.

**Comment by filipewl** [comment]
I had the same problem when I tried to add a badge to a button icon. The button's `overflow hidden` cropped the badge. I overwrote the button's overflow to `visible` to fix it.

**Comment by traviskaufman** [comment]
Closing this issue as it looks like it has a solid workaround and there hasn't been any activity on it for almost a year.
