### ISSUE TITLE
mdl-layout-icon not working in angular templates

### ISSUE THREAD

**Issue by andrerafaelmezzalira** [google/material-design-lite#988]
when use ng-view on my partials/page.html is not working mdl-layout-icon

**Comment by Garbee** [comment]
Please use StackOverflow for support. You can use the `material-design-lite` tag among any other relevant tags so the most developers can find it to help and can later find the answers if they need to solve the same problem.

**Comment by andrerafaelmezzalira** [comment]
Garbee,

how to reload the 'MaterialLayout' component?

**Comment by Garbee** [comment]
Downgrading Layout isn't supported, so "reloading" it isn't possible with the current implementation.

**Comment by andrerafaelmezzalira** [comment]
Sorry for posting here, but if you can evaluate:

http://plnkr.co/edit/mCQDsAlrz2HfuV9N3K19?p=preview

and 

http://plnkr.co/edit/0DlkPBiru0F0SFnETCL4?p=preview

I do not know what to do.

**Comment by Garbee** [comment]
I don't know what to do either tbh. I don't use angular so I don't know its constructs. Support is best asked on StackOverflow using the appropriate tags, in this case at least `angularjs` and `material-design-lite`. This will allow developers who know the technologies in use better answer the question and allow other developers with similar problems find answers more easily.
