### ISSUE TITLE
Primary Color selection

### ISSUE THREAD

**Issue by gregorsmith** [google/material-design-lite#989]
I use a lot of the mdl-color--primary style, but it appears that there is no subset like, for example, mdl-color--blue-50 for a very light accent in places. So I'm suggesting that an addition of mdl-color--primary--xxx or mdl-color-text--accent-xxx styles would be beneficiary, same for the text mdl-color-text--primary and mdl-color-text--accent set.

**Comment by Garbee** [comment]
As I recall we had those extra styles, they caused a bunch of bloat for something we felt wouldn't get used too much. Do you have any specific cases where they come in handy?

Ideally, if you are using colors to that extent then you should integrate the Sass version into your workflow (going to get easier soon once raw sources are in the npm and bower releases) and use the variables for the color pallet directly.

**Comment by gregorsmith** [comment]
I'm just experimenting with different pages/sections being a different colour, kind of like Inbox uses. Rather than hardcoding background page colors like <div class="page-content mdl-color--teal-50"> on each page, I was guessing a <div class="page-content mdl-color--primary-50"> would work better across the templating style. Not one to fight against the bloat. Consider this closed

**Comment by Garbee** [comment]
Ah, whoops. Reading your last response we didn't remove the old color classes it looks like. Just checked the [palette file](https://github.com/google/material-design-lite/blob/master/src/palette/_palette.scss) and we sure didn't. Oh well, can't fix it now (if I even recall us deciding on removing it correctly.)

Either way, I think there is something for scoping the current primary and accent color and making those available using this method. That way you can code to the pallet shade and no matter what people chose for the colors it will auto-adjust.

**Comment by sgomes** [comment]
The way we're handling colours in v2 will change, and we won't be providing colour classes by default. That said, I see some benefits to us having an optional palette CSS file with all these definitions. Targeting v2 launch.

**Comment by traviskaufman** [comment]
Superseded by #4492
