### ISSUE TITLE
Sass styleguide

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#992]
We should get a styleguide together for the Sass sources and make sure the existing files are updated for it. Right now we have multiple styles drifting around.

For Sublime Text there is [SassBeautify](https://packagecontrol.io/packages/SassBeautify) to help and WebStorm/PHPStorm have built in help for formatting. Once we get a styleguide together (or chose an open one) we should make sure we have rulesets for at least these two tools to help contributors keep consistency.

**Comment by sgomes** [comment]
SASS/PostCSS linting being tracked as part of 4464.
