### ISSUE TITLE
Unneeded horizontal scroll bar displayed in the menu of the dashboard template

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#994]
When viewing the [dashboard template](http://www.getmdl.io/templates/dashboard/index.html) with Chrome 45.0.2421.0 an unneeded horizontal scroll bar is displayed at the bottom of the the menu (drawer).

**Comment by tschiela** [comment]
The problem are the dropdown menu items in the header. They have a width of 100% and all the parents are position absolute. In my opinion they dont need the width of 100% because they are already block elements.

Remove the width: 100% of .mdl-menu__item will fix it.

**Comment by Garbee** [comment]
Assigning to Surma since I believe he was the one who wrote the template.

**Comment by surma** [comment]
I don’t have that scroll bar :scream: 

Could you guys provide a screenshot and specs about your system (browser, OS, zoom settings etc)?

**Comment by Garbee** [comment]
OS: Ubuntu (Mate) 15.04
Zoom: None
Screen size: 1920x1080
browser: Chrome 45.0.2454.6 Dev Channel (only because I don't get Canary :frowning: )


Screenshot (Scrollbar in lower left corner) :
 
![selection_003](https://cloud.githubusercontent.com/assets/868301/8721856/9fd8648e-2b8c-11e5-989d-272127a17e2a.png)

**Comment by DJWassink** [comment]
I noticed the same scrollbar. 

The `li` items on the dropdown (user/hello@email.com) have a padding of `0px 16px` if you set this to zero and give the 16px padding to the `ul` (resulting in a padding of 8px 16px) it is fixed.

![2015-07-17 08_54_29-material design lite](https://cloud.githubusercontent.com/assets/1822404/8742057/83a56c5a-2c61-11e5-8c39-1d855a30dd56.png)

**Comment by tschiela** [comment]
@DJWassink 
With the change of the padding i get a weird animation on 
43.0.2357.132 Chrome @ Ubuntu 14.04

**Comment by DJWassink** [comment]
@tschiela 
Didn't notice any weird animations on my end. However the highlighting does seems to get buggy, currently I implemented your solution by removing the 100% width which seems to be a better solution.

**Comment by emir-munoz** [comment]
I have the same problem. For me modifying the value of `overflow-y` to `initial` or `visible` in the class `.mdl-layout__drawer` solved the issue.

**Comment by surma** [comment]
I agree with @tschiela’s argument. Fixed in #1022
