### ISSUE TITLE
Is www.richmediagallery.com build on top of MDL?

### ISSUE THREAD

**Issue by jimbojetlag** [google/material-design-lite#997]
The FAQ states that http://www.richmediagallery.com uses MDL, but inspecting the final html code I was not able to find any traces of MDL.

Specifically the [filter page](http://www.richmediagallery.com/adtypes#filterAds:483~) seems to be build by closure library and soy template.

Could you clarify which components in that website are by MDL? Are there interfaces for MDL to interact with closure library and closure template, like the two way binding in the filter page?

**Comment by Garbee** [comment]
Yes it uses MDL. Type `componentHandler` into the console and you will see the object we provide. It is an older pre-release version though. It does seem to mix Polymer and MDL which is totally fine.

As far as closure stuff, what you see is what you get. Pure HTML, CSS, and JS. As far as what technologies you use and how you hook them up, that is up to you.

**Comment by jimbojetlag** [comment]
I see, I assume the pre-release version had no mdl- prefix on class names.

Given that MDL is a subset of Polymer material implementation, I do not understand why the two should be mixed though.

**Comment by Garbee** [comment]
> Given that MDL is a subset of Polymer material implementation

This isn't true at all. MDL is its own implementation entirely of Material Design. Polymer components also have their own quirks when compared to the spec. It isn't a "subset" of anything except the full MD spec, which we are working to fill in the gaps.

**Comment by jimbojetlag** [comment]
I can see two problems with this:

1. Overhead: Using both solutions together means loading more resources. These resources may have a lot of overlap in the implemented components. Using modules can remedy this, but managing them is a pain.
2. Inconsistency: Mixing the two brings UI inconsistencies, as one or both implementations may not 100% follow the specs. Eg, the ripple effect in one of them could be faster, or slower, than the other one, or have a different wavelength.

Also, according to [this faq](http://www.getmdl.io/faq/index.html#polymer):

> MDL focuses on delivering an experience that is optimised for static content sites, like blogs, marketing pages and more traditional text-based web pages.

While it's true that the UI for the blog readers is mostly static, the UI for the writer of the blog may need complex components, like chips for tags. If MDL is targeting these use cases, I believe it should address the controls for the content writer user as well.

**Comment by Garbee** [comment]
> Overhead: Using both solutions together means loading more resources.

Test, test, test. Yes, clearly it leads to more resources overall, but if one implementation doesn't handle some situations well when another does... It may make sense to include both and save dev time making things work. Also if you minimize what is used, it isn't as big of a problem. The size of MDL as a whole is negligible in most situations as well. You are much better off cutting an image out of your page then worrying about MDL being included. We never insist people toss Polymer and MDL in all the time and mix stuff up for no reason.

> Inconsistency: Mixing the two brings UI inconsistencies, as one or both implementations may not 100% follow the specs. 

True, but this also depends on what parts you are using. There is no solid "Using both in full" is valid or invalid. You need to build your application, understand the tools, and apply them properly and consistently. Using Polymer's buttons in one place then MDL's in another and both with ripples may be inconsistent, but if you use one or the other everywhere possible... Then you're fine. 

Developers need to understand their tools and know how to apply them properly. As they build, they then need to be constantly testing their output to see if it hits their UX/Performance/whatever targets.

> I believe it should address the controls for the content writer user as well.

Eventually yes, we will have more components. ;) What we have now is a subset of components that were the higher-target points to launch with.
