### ISSUE TITLE
Example code in the Badges documentation referencess an unused "icon" class

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#998]
In the [badges documentation](http://www.getmdl.io/components/index.html#badges-section) there's the following example:
```
<!-- Number badge on icon -->
<div class="icon material-icons mdl-badge" data-badge="1">account_box</div>
<!-- Icon badge on icon -->
<div class="icon material-icons mdl-badge" data-badge="♥">account_box</div>
```
It applies the ```icon``` class, however this class isn't used in the CSS. I'm presuming this is a mistake and should be removed from the example?

**Comment by Garbee** [comment]
ah yes, that is from an older build of the docs I believe. Updating to remove them now.
